### ISSUE TITLE
Release: 1.3.0alpha2 snarkworker crashes - Encountered an error while evaluating the checked computation

### ISSUE THREAD

**Issue by jrwashburn** [MinaProtocol/mina#10024]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Updated mainnet to 1.3 alpha 2. I run several snarkers using the mina internal snarkworker command. Snark workers have been rock solid for a very long time - they never die. After update to 1.3A2, all my snark workers are crashing with this error.

Encountered an error while evaluating the checked computation

`
{"timestamp":"2022-01-15 07:22:45.889255Z","level":"Debug","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 182, characters 6-18"},"message":"Snark worker using daemon $addr","metadata":{"addr":"157.0.0.0:8301","pid":6660,"process":"Snark Worker"}}
{"timestamp":"2022-01-15 07:22:46.117650Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 202, characters 10-21"},"message":"SNARK work $work_ids received from $address. Starting proof generation","metadata":{"address":"157.0.0.0:8301","pid":6660,"process":"Snark Worker","work_ids":[1011831149,713019563]}}
(monitor.ml.Error
 ( "Snarky.Checked_runner.Runtime_error(_, _, _, _)\
  \n\
  \nEncountered an error while evaluating the checked computation:\
  \n  (Failure\
  \n   \"Constraint unsatisfied (unreduced):\\\
  \n  \\n\\\
  \n  \\nall: File \\\"src/lib/snarky/src/base/snark0.ml\\\", line 612, characters 8-170\\\
  \n  \\nprevs_verified\\\
  \n  \\nstep_main\\\
  \n  \\n\\\
  \n  \\nConstraint:\\\
  \n  \\n(((basic(Equal(Add(Add(Constant 1)(Scale 28948022309329048855892746252171976963363056481941560715954676764349967630336(Add(Constant 1)(Scale 28948022309329048855892746252171976963363056481941560715954676764349967630336(Var 194761)))))(Add(Constant 1)(Scale 28948022309329048855892746252171976963363056481941560715954676764349967630336(Add(Constant 1)(Scale 28948022309329048855892746252171976963363056481941560715954676764349967630336(Var 194760))))))(Constant 2)))(annotation())))\\\
  \n  \\nData:\\\
  \n  \\nEqual 0 2\")\
  \n\
  \nLabel stack trace:\
  \nall: File \"src/lib/snarky/src/base/snark0.ml\", line 612, characters 8-170\
  \nprevs_verified\
  \nstep_main\
  \n\
  \n\
  \nRaised at Stdlib.failwith in file \"stdlib.ml\", line 29, characters 17-33\
  \nCalled from Snarky_backendless__Checked_runner.Make_checked.add_constraint in file \"src/lib/snarky/src/base/checked_runner.ml\", line 188, characters 8-329\
  \nCalled from Snarky_backendless__Checked_runner.Make.handle_error in file \"src/lib/snarky/src/base/checked_runner.ml\", line 345, characters 8-12\
  \n")
 ("Raised at Snarky_backendless__Checked_runner.Make.handle_error in file \"src/lib/snarky/src/base/checked_runner.ml\", line 355, characters 8-419"
  "Called from Snarky_backendless__Checked_runner.Make.run in file \"src/lib/snarky/src/base/checked_runner.ml\", line 417, characters 20-65"
  "Called from Snarky_backendless__Checked_runner.Make_checked.with_label in file \"src/lib/snarky/src/base/checked_runner.ml\", line 140, characters 16-46"
  "Called from Snarky_backendless__Checked_runner.Make.run in file \"src/lib/snarky/src/base/checked_runner.ml\", line 413, characters 19-43"
  "Called from Snarky_backendless__Snark0.Run.Make_basic.run in file \"src/lib/snarky/src/base/snark0.ml\", line 1808, characters 22-47"
  "Called from Pickles__Step_main.step_main.main.(fun) in file \"src/lib/pickles/step_main.ml\", line 346, characters 14-35"
  "Called from Snarky_backendless__Snark0.Run.Make_basic.with_label in file \"src/lib/snarky/src/base/snark0.ml\", line 2476, characters 14-18"
  "Called from Pickles__Step_main.step_main.main.(fun) in file \"src/lib/pickles/step_main.ml\", line 221, characters 10-1023"
  "Called from Snarky_backendless__Snark0.Run.Make_basic.with_label in file \"src/lib/snarky/src/base/snark0.ml\", line 2476, characters 14-18"
  "Called from Snarky_backendless__Snark0.Run.Make_basic.handle in file \"src/lib/snarky/src/base/snark0.ml\", line 2461, characters 14-18"
  "Called from Snarky_backendless__Snark0.Run.Make_basic.Proof_system.mark_active in file \"src/lib/snarky/src/base/snark0.ml\", line 2370, characters 20-24"
  "Re-raised at Snarky_backendless__Snark0.Run.Make_basic.Proof_system.mark_active in file \"src/lib/snarky/src/base/snark0.ml\", line 2375, characters 10-19"
  "Called from Snarky_backendless__Snark0.Run.Make_basic.as_stateful in file \"src/lib/snarky/src/base/snark0.ml\", line 1814, characters 14-18"
  "Called from Snarky_backendless__Snark0.Make_basic.Checked.auxiliary_input in file \"src/lib/snarky/src/base/snark0.ml\", line 207, characters 13-27"
  "Called from Snarky_backendless__Snark0.Make_basic.Run.generate_witness_conv.(fun) in file \"src/lib/snarky/src/base/snark0.ml\", line 1132, characters 12-132"
  "Called from Pickles__Step.Make.f in file \"src/lib/pickles/step.ml\", line 509, characters 6-1023"
  "Called from Pickles.Make.compile.f.step in file \"src/lib/pickles/pickles.ml\" (inlined), line 709, characters 10-246"
  "Called from Pickles.Make.compile.f.step in file \"src/lib/pickles/pickles.ml\", line 709, characters 10-246"
  "Called from Pickles.Make.compile.f.wrap in file \"src/lib/pickles/pickles.ml\", line 735, characters 12-63"
  "Called from Transaction_snark.Make.merge.(fun) in file \"src/lib/transaction_snark/transaction_snark.ml\", line 3583, characters 6-72"
  "Called from Async_kernel__Deferred0.bind.(fun) in file \"src/deferred0.ml\", line 54, characters 64-69"
  "Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5"
  "Called from Async_kernel
`

### Steps to Reproduce

1. Update to 1.3 Alpha 2
2. Launch snark workers with `  mina internal snark-worker --daemon-address [HOST]:8301 --proof-level full --shutdown-on-disconnect false &
3. Wait for it - just a minute or two

### Expected Result

Snark worker stays alive.

### Actual Result

Snark worker abends.

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

High

### Status

```shell
Mina daemon status-----------------------------------
`
Global number of accounts:                     87857
Block height:                                  99836
Max observed block height:                     99836
Max observed unvalidated block height:         99836
Local uptime:                                  21m13s
Ledger Merkle root:                            jx7z4zHJsvMNFZDgAzKGzfZr3gXDt9PPv96Q9yVb5wBHPqfKQsg
Protocol state hash:                           3NKtSWtXkLewipjRhKL4VVfr6nPNDjrfTvJ2qBjTJRKVCsgc1qC2
Chain id:                                      5f704cc0c82e0ed70e873f0893d7e06f148524e3f0bdae2afb02e7819a0c24d1
Git SHA-1:                                     271738546ff38127772494949de5c23fb6336727
Configuration directory:                       /home/minar/.mina-config
Peers:                                         63
User_commands sent:                            0SNARK worker:                                  NoneSNARK work fee:                                999999Sync status:                                   Synced
Catchup status:
        To build breadcrumb:           0
        To initial validate:           0
        Finished:                      291
        To download:                   0
        Waiting for parent to finish:  0
        To verify:                     0

Block producers running:                       1 (B62qkBqSkXgkirtU3n8HJ9YgwHh3vUD6kGJ5ZRkQYGNPeL5xYL2tL1L)
Coinbase receiver:                             B62qqyZ86GsrRV96xuiStZhJW5D9fzFZvasE6aAToRH8PP2bU2TsM8V
Best tip consensus time:                       epoch=20, slot=3268Best tip global slot (across all hard-forks):  146068
Next block will be produced in:                in ...
Consensus time now:                            epoch=20, slot=3270
Consensus mechanism:                           proof_of_stakeConsensus configuration:
        Delta:                     0        k:                         290
        Slots per epoch:           7140        Slot duration:             3m
        Epoch duration:            14d21h        Chain start timestamp:     2021-03-17 00:00:00.000000Z
        Acceptable network delay:  3m
`
```

### Additional information

Not sure these are helpful, iirc the snarkworker doesn't log anything there, but attached just in case. https://drive.google.com/file/d/1X56GpQMXKlw4MyN5JilfcPkij1VwXDC2/view?usp=sharing

**Comment by lk86** [comment]
does this same issue occur with `mina client set-snark-worker` on a block producer or only for standalone snark workers?

**Comment by jrwashburn** [comment]
I only run the coordinator + standalone workers so I do not know. I would normally test again, but due to the issues with Alpha 2 getting stuck, I don't want to upgrade a node again. Running the coordinator and separate worker is necessary to do well in the snarketplace, so I think this is an important issue either way.

**Comment by lk86** [comment]
It's certainly valid, just trying to see if I needed a similar setup to replicate these results to test + iterate more quickly

**Comment by p-shahi** [comment]
Looping back here. this PR https://github.com/MinaProtocol/mina/pull/10121 reverts the fix that introduced this problem and this issue is not reproducible in 1.3.0alpha3 (and beyond) right?
@jrwashburn

**Comment by jrwashburn** [comment]
> Looping back here. this PR https://github.com/MinaProtocol/mina/pull/10121 reverts the fix that introduced this problem and this issue is not reproducible in 1.3.0alpha3 (and beyond) right?
> 
> @jrwashburn

I have not had a reoccurrence and think his should be closed.
