### ISSUE TITLE
Lift the remaining transaction snark logic into a common source

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#10027]

**Comment by deepthiskumar** [comment]
Remaining: check account, protocol state predicates,and the checks in `apply_body`

**Comment by deepthiskumar** [comment]
remaining `Check_account_precondition` and `Check_protocol_state_precondition`

**Comment by deepthiskumar** [comment]
most of the zkapp transaction application logic is now lifted into a common source
