### ISSUE TITLE
Unable to generate key pair using mina-generate-keypair

### ISSUE THREAD

**Issue by PrernaPadhee** [MinaProtocol/mina#10046]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

I am following instructions on https://docs.minaprotocol.com/en/using-mina/keypair to set up my mina node, however i am getting the following error

![image](https://user-images.githubusercontent.com/29208607/150114018-b14ef937-6c4e-4171-b743-92c3c921e23f.png)

### Steps to Reproduce

1. echo "deb [trusted=yes] http://packages.o1test.net stretch stable" | sudo tee /etc/apt/sources.list.d/mina.list
2. sudo apt-get update
3. sudo apt-get install mina-generate-keypair=1.2.2-feee67c
4. mina-generate-keypair -version

### Expected Result

Commit feee67cc2836bf12e792510a2440f28a0275740e on branch master

### Actual Result

mina-generate-keypair: error while loading shared libraries: libjemalloc.so.1: cannot open shared object file: No such file or directory

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
unable to setup node
```

**Comment by shimkiv** [comment]
Hey @PrernaPadhee, as the workaround for now you can simply install Mina Daemon as it is described [here](https://docs.minaprotocol.com/en/using-mina/getting-started#ubuntu-1804--debian-9). It will install additional packages (`curl libcurl4 libjemalloc1 libpq-dev libpq5`) the `mina-generate-keypair` also depends on.
