### ISSUE TITLE
deploy backends for node error/status collection service

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#10057]
For each corresponding service:
1. create a `Google Functions` that functions as the http ingestion point:

2. create a sink for the user-defined log buckets for the service.

3. setup and configure elastic service in a k8s container and create a pubsub topic for the logs and feed the pubsub messages to logstash.

The above steps should all be done through a terraform script.

**Comment by joseandro** [comment]
This task maps to Q1.7 in our roadmap: node info collection system maintenance and support.

**Comment by samuelarogbonlo** [comment]
@joseandro I don’t seem to find the details for node status collection on the roadmap

**Comment by samuelarogbonlo** [comment]
@joseandro I don’t seem to find the details for node status collection on the roadmap
