### ISSUE TITLE
Intg test: port over snarkness integration test to new framework

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#10050]

**Comment by QuiteStochastic** [comment]
this test's test cases are not reproduced in the new framework, however we don't use snarkless for anything at the moment.  it's safe to remove this old integration test, eventually we'll make new features in the new integration test framework to test this when snarkless becomes relevant

**Comment by QuiteStochastic** [comment]
this test runs `src/app/cli/src/tests/full_test.ml` which might have further test cases which may need to be ported over, gotta check to make sure there's nothing new before just deleting it
