### ISSUE TITLE
Remaining Test cases for QANet

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#10067]
- [x] Payments + snapp transactions from the same account are accepted
- [x] A Snapp that's guaranteed to fail
- [x] Txns with multiple proofs
- [x] Update all the fields in one txn
- [x] transactions are ordered fee per weight unit
- [x] Max transactions per block

**Comment by psteckler** [comment]
Note: currently, we can't use the parties in a snapp as sender or receiver in a payment, so the test uses separate accounts for the payment. That will change eventually, and the test can be updated to use the parties accounts in the payment.

**Comment by deepthiskumar** [comment]
Suggest adding a test that check snark work is happening for snapp transactions. This might be higher priority than
the tests for Transactions are ordered fee per weight unit and Max transactions per block

**Comment by psteckler** [comment]
All the checklist items are done.
