### ISSUE TITLE
Docker image for minaprotocol/mina-generate-keypair not up to date

### ISSUE THREAD

**Issue by Trivo25** [MinaProtocol/mina#10065]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Summary

According to the [docs](https://docs.minaprotocol.com/en/using-mina/keypair), under section "Usage", 3b 

> In Docker on Windows/MacOS/Linux: Generate your keys using the minaprotocol/generate-keypair docker image. When prompted, type in the password you intend to use to secure this key. Do NOT forget this password.

> `docker run  --interactive --tty --rm --volume $(pwd)/keys:/keys minaprotocol/mina-generate-keypair:1.2.2-feee67c --privkey-path /keys/my-wallet`

Docker can not find image `mina-generate-keypair:1.2.2-feee67c`, because the last available image is of version `1.2.0`, see [docker hub](https://hub.docker.com/r/minaprotocol/mina-generate-keypair/tags)  hub for mina-generate-keypair

### Steps to Resolve this Issue

Either update the docker image to version 1.2.2, or change the docs to fit version 1.2.0, if no compatibility issues exist

**Comment by cscetbon** [comment]
The current documentation says to use version `1.3.0-9b0369c` however I can only see tag [1.2.0-fe51f1e](https://hub.docker.com/layers/mina-generate-keypair/minaprotocol/mina-generate-keypair/1.2.0-fe51f1e/images/sha256-7b61ac2646784a413e41d968280e83c716231cc2c0056935e07fd572272d9a07?context=explore)

**Comment by shimkiv** [comment]
Thank you @cscetbon and @Trivo25, works for me with image mentioned by @cscetbon:
```
> docker run --interactive --tty --rm --volume $(pwd)/:/keys minaprotocol/mina-generate-keypair:1.3.0-9b0369c --privkey-path /keys/my-wallet

Password for new private key file:
Again to confirm:
Keypair generated
Public key: B62qiaLLK5vLyog5iEbGseka9n3uTVuCo6hBCviQvawECXQwSH7QkQ1
Raw public key: 039B0CE01C981C1672FC52B3FAC3AA9B70EA88FF8441E403285E8B656D44088E
```
