### ISSUE TITLE
Fix txn logic so it's according to spec

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#10068]

**Comment by mrmr1993** [comment]
* Complete renaming to match spec
* Modify order of updates and permission/predicate checks to match those in the spec
* Move fields to the correct structures according to spec
* Specialise the `Party.t`, `Fee_payer.t` etc. to match the spec (for serialisation)
* Match the layout of call stack (for serialisation)

Nice to have:
* Uplift documentation into the OCaml code as doc-comments
