### ISSUE TITLE
Generate dependency graph for documentation

### ISSUE THREAD

**Issue by Firobe** [MinaProtocol/mina#10083]
The codebase being separated into dozens of different libraries with no apparent structure (in the file system or documentation), it would be useful to produce a legible dependency graph illustrating the actual usage structure of the code base, to compliment other efforts to document the purpose of individual libraries.

**Comment by ylecornec** [comment]
Since the project contains a lot of libraries, it is best to organize them into groups and use this information to make readable graphs.

See the following PR (https://github.com/MinaProtocol/mina/pull/10167) about an RFC for reorganizing the `src/lib` folder, and some examples of dependency graphs.

**Comment by robinbb** [comment]
@ylecornec @Firobe Can this issue be closed, now? If not, what remains to be done? (Also, please say more about the purpose of this work effort.)

**Comment by Firobe** [comment]
I've updated the issue description. @robinbb this issue is blocked by the ongoing re-structuration of the codebase libraries. It appeared that such a dependency graph *could not* be legible/useful with the current structure.
So this issue is not completed, and will not be until the re-structuration is done, which will take a long time.

Even then, I'd argue it shouldn't be closed since we want to remember to produce such a graph once this is done. What do you think?

**Comment by robinbb** [comment]
Thank you for explaining. Given that it will not be done for a long time, it is safe to close this issue.
