### ISSUE TITLE
Snapps Txn Testing

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#10130]
Sequencing
change a non-snapp account to snapp account
Parties using protocol state predicate
Parties using account predicate (fields other than nonce)
Update account data(delegate)
Parties using full commitment
Expired transactions are rejected (using protocol state predicate for snapps)
Transaction with multiple snapps
Transaction with one snapp calling the other

**Comment by deepthiskumar** [comment]
closing in favor of tickets for specific tests
