### ISSUE TITLE
Nodes crashed at the same time

### ISSUE THREAD

**Issue by 0xthrowaway** [MinaProtocol/mina#10164]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

All my nodes except one crashed **after** producing this **exact** block:
https://minaexplorer.com/block/3NLZAZ6T7ZmDdxbMDLrqJhrrwQWoTUu95Nfyftyug2DAFPrnAjYX
 
The block was successfully gossiped from the node that didn't crash to the other nodes **before** they finished producing an **identical** block. Is this an unexpected case? 
 
The exception:
> 2022-02-07 01:13:02 UTC [Fatal] Unhandled top-level exception: $exn
> Generating crash report
>         exn: {
>   "commit_id": "feee67cc2836bf12e792510a2440f28a0275740e",
>   "sexp": [
>     "monitor.ml.Error",
>     [
>       "**Hashtbl.add_exn got key already present**",
>       "27075374949796957509749973435300311463453769392196243846907867623788157890248"
>     ],
>     [
>       "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
>       "Called from file \"src/hashtbl.ml\", line 140, characters 4-21",
>       "Called from file \"src/lib/transition_frontier/full_frontier/full_frontier.ml\", line 520, characters 6-131",
>       "Called from file \"src/lib/transition_frontier/full_frontier/full_frontier.ml\", line 732, characters 31-74",
>       "Called from file \"list.ml\", line 117, characters 24-34",
>       "Called from file \"src/list0.ml\" (inlined), line 22, characters 40-81",
>       "Called from file \"src/lib/transition_frontier/full_frontier/full_frontier.ml\", line 730, characters 4-484",
>       "Called from file \"src/lib/transition_frontier/transition_frontier.ml\", line 333, characters 4-214",
>       "Called from file \"src/lib/transition_handler/processor.ml\", line 63, characters 9-67",
>       "Called from file \"src/lib/transition_handler/processor.ml\", line 326, characters 21-120",
>       "Called from file \"src/result.ml\", line 151, characters 9-15",
>       "Caught by monitor coda"
>     ]
>   ],
>   "backtrace": [
>     "Raised at file \"stdlib.ml\", line 33, characters 17-33",
>     "Called from file \"src/lib/pipe_lib/strict_pipe.ml\", line 159, characters 28-37",
>     "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
>     "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
>     "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
>   ]
> }
> 

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

-

### Actual Result

-

### How frequently do you see this issue?

Rarely

### What is the impact of this issue on your ability to run a node?

Low

### Status

```shell
-
```

**Comment by p-shahi** [comment]
@0xthrowaway what version of the node were you running?

**Comment by 0xthrowaway** [comment]
@p-shahi 1.2.2
