### ISSUE TITLE
Remove dead code from the code base

### ISSUE THREAD

**Issue by Firobe** [MinaProtocol/mina#10177]
Several parts of the code base (either internal or external) do not build at all.

Investigate if either :
- they must be fixed
- they are not used anymore and should be removed

**Comment by yorickvP** [comment]
Do you have a list of examples?

**Comment by Firobe** [comment]
> Do you have a list of examples?

Updated the description with a non-exhaustive list of problems.

**Comment by Firobe** [comment]
This issue is currently investigated by Gaga.

**Comment by ebresafegaga** [comment]
I have written a list of all the build errors [here](https://gist.github.com/ebresafegaga/e1a49d6edf12275a98a2207fae6e7ef8)

**Comment by kantp** [comment]
We removed all the code we know we want to delete, and not revive. Created #11717 to at some point revisit the code we might want to bring back.
