### ISSUE TITLE
Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by mediumjack1** [MinaProtocol/mina#10182]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

cryptofather@Minerrig:~$ sudo apt-get install -y curl unzip mina-mainnet=1.2.2-feee67c
Reading package lists... Done
Building dependency tree       
Reading state information... Done
unzip is already the newest version (6.0-25ubuntu1).
unzip set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mina-mainnet : Depends: libffi6 but it is not installable
                Depends: libjemalloc1 but it is not installable
E: Unable to correct problems, you have held broken packages.

### Steps to Reproduce

follow installment instructions provided : https://docs.minaprotocol.com/en/getting-started

### Expected Result

i assume mina should have been installed and ready to go

### Actual Result

the above pasted problem:
cryptofather@Minerrig:~$ sudo apt-get install -y curl unzip mina-mainnet=1.2.2-feee67c
Reading package lists... Done
Building dependency tree       
Reading state information... Done
unzip is already the newest version (6.0-25ubuntu1).
unzip set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mina-mainnet : Depends: libffi6 but it is not installable
                Depends: libjemalloc1 but it is not installable
E: Unable to correct problems, you have held broken packages.

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
cryptofather@Minerrig:~$ mina client status
mina aborted!
Don't know how to build task 'client' (See the list of available tasks with `mina --tasks`)
/usr/bin/mina:53:in `block (2 levels) in <main>'
/usr/bin/mina:26:in `block in <main>'
/usr/bin/mina:25:in `instance_eval'
/usr/bin/mina:25:in `<main>'
(See full trace by running task with --trace)
```

**Comment by shimkiv** [comment]
Hey @mediumjack1 please try it with the version described in updated docs [here](https://docs.minaprotocol.com/en/using-mina/getting-started#ubuntu-1804--debian-9). It works on `Ubuntu 18.04 / Debian 9`
