### ISSUE TITLE
Node restarts after ~30 mins

### ISSUE THREAD

**Issue by georgeee** [MinaProtocol/mina#10238]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Nodes is started and fails soon after launching

### Steps to Reproduce

`docker run -d --restart always --name mina --entrypoint=mina -p 8302:8302 -p 3095:3095/tcp -p 6060:6060  --network mina-network --mount "type=bind,source=pwd/keys,dst=/home/ubuntu/keys,readonly" --mount "type=bind,source=pwd/.mina-config,dst=/home/ubuntu/" -e CODA_PRIVKEY_PASS="" -e MINA_PRIVKEY_PASS="" -e UPTIME_PRIVKEY_PASS="" minaprotocol/mina-daemon:1.3.0alpha2-2717385-stretch-mainnet daemon --metrics-port 6060  --block-producer-key /home/ubuntu/keys/my-wallet --snark-worker-parallelism 4 --insecure-rest-server --file-log-level Debug --log-level Info --peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt --open-limited-graphql-port --limited-graphql-port 3095 --run-snark-worker B62qqFD9HDYWVyYfn4iEFXAjtef6LuFZYK7y4hvGeuZ7FKHsvaiVRtr --snark-worker-fee 0.000979   --uptime-url http://34.134.227.208/v1/submit --uptime-submitter-key /home/ubuntu/keys/my-wallet --external-ip 18.206.91.133`

### Expected Result

Node runs smoothly

### Actual Result

Node fails after 30 mins

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
-
```

### Additional information
version `1.3.0beta4`

https://drive.google.com/file/d/1emS79x74886a7Dgpd21ael1_2XdiVjgv

**Comment by p-shahi** [comment]
[syslog_beta_01.log](https://github.com/MinaProtocol/mina/files/8145008/syslog_beta_01.log)
[beta_01.log](https://github.com/MinaProtocol/mina/files/8145009/beta_01.log)

**Comment by p-shahi** [comment]
[mina-prover.log](https://github.com/MinaProtocol/mina/files/8150516/mina-prover.log)
[mina.log](https://github.com/MinaProtocol/mina/files/8150517/mina.log)

**Comment by p-shahi** [comment]
[mina.log](https://github.com/MinaProtocol/mina/files/8150821/mina.log)
[mina-prover.log](https://github.com/MinaProtocol/mina/files/8150822/mina-prover.log)
logs in binary format

**Comment by iregina** [comment]
From my sync with George, George recommended OnTab a solution that does not involve Docker. We'll wait for an update to see if it helps!

**Comment by p-shahi** [comment]
@iregina @georgeee can we close this one?
