### ISSUE TITLE
Figure out a way to provide authentication for the node status/error system

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#10263]
Currently the Kibana ingress for node status/error system is public. We want to make it private because the status/error reports may reveal vulnerability of our node operators to malicious attackers.

Currently there's 2 options:
1. Using Google's IAP system to guard the visit to Kibana ingress
2. Integrating Okta with elastic stack to provide the SAML Single-Sign-On service

**Comment by joseandro** [comment]
The agreement was to put this service behind OKTA.
