### ISSUE TITLE
sendRosettaTransaction broken (offline sign by Ledger and send by mina) in 1.3.0 beta 4

### ISSUE THREAD

**Issue by p-shahi** [MinaProtocol/mina#10271]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

```
Anyone having issues with Ledger wallet signatures being rejected by the node on 1.3.0 beta 4?
I don't send transactions often, but getting a new error:
 Error: Transaction could not be entered into the pool: This transaction had an invalid signature (in ["sendRosettaTransaction"])
```

```
For me, broadcasting to the graphql mutation is working okay, just CLI is broken. (I am using different signers for graphql (js lib) vs. CLI (ledger)
```

### Steps to Reproduce

Sign with ledger wallet and try to send tx with 1.3.0 beta 4

### Expected Result

Successful sign and send

### Actual Result

```
 Error: Transaction could not be entered into the pool: This transaction had an invalid signature (in ["sendRosettaTransaction"])

```

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Low

### Status

```shell
n/a
```

**Comment by jrwashburn** [comment]
Steps to reproduce: generate offline payment using ledger wallet, attempt to send transaction to the network using mina daemon.

mina_ledger_wallet send-payment --offline --network mainnet --nonce  --fee ... etc. 

from daemon, run mina advanced send-rosetta-transactions command, paste in signature from above, ctrl d to send
daemon cli returns: Error: Transaction could not be entered into the pool: This transaction had an invalid signature (in ["sendRosettaTransaction"])

**Comment by p-shahi** [comment]
fixed by https://github.com/jspada/ledger-app-mina/pull/22
