### ISSUE TITLE
Receipt chain hash updates for parties transactions

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#10350]

**Comment by deepthiskumar** [comment]
Needed for the ethereum bridge

**Comment by psteckler** [comment]
For non-zkApp transactions, the receipt chain hash is updated for the fee payer account, which uses a signature in the transaction. For zkApps, the proposal is to update the hash if its authorization is a signature or proof.

An account may appear multiple times in a zkApp, and we wish the new hash to be derived from the transaction, and the account's hash before the transaction. Therefore, we wish to update the hash just once. The updating can take place in `Parties_logic.apply`.

These changes only affect the contents of accounts when a `Parties.t` is applied. Accounts already have a receipt chain hash field, so no changes to GraphQL, the replayer, or zkApp creation should be required.

**Comment by psteckler** [comment]
The type `Mina_transaction_logic.Signed_command_applied.t` contains the field `previous_receipt_chain_hash`, for the fee payer. That was used for `undo`, which has been removed. We can remove that field, which is not otherwise used.

Accordingly, we won't need to add old receipt chain hashes to `Parties_applied.t`.

**Comment by psteckler** [comment]
The CLI command `advanced compute-receipt-chain-hash` currently accepts a transaction id corresponding to a `Signed_command.t`. We can update that to allow ids for `Parties.t`s. We'd need to compute the full transaction commitment from the `Parties.t`.

**Comment by psteckler** [comment]
We'll mix in an index for each party when computing the receipt chain hash, and we'll cons that index + commitment for each occurrence of the party. That's more informative than cons'ing the commitment just once per party, or cons'ing it without an index multiple times per party, should that party occur multiple times in a transaction.
