### ISSUE TITLE
GraphQL: Berkeley - balance changes are not included for new snapp accounts

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#10355]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

When creating a new snapp account via the CLI and assigning a `--receiver-amount` there is no way of obtaining this via GraphQL.

### Steps to Reproduce

1. Create a new snapp account via `mina-snapp-test-transaction create-snapp-account`
2. Once the block has been included check `block` or `bestChain` query and there is no way of getting the balance transfer from GraphQL.
...

### Expected Result

Should be possible to determine the balance transfer from GraphQL

### Actual Result

It's not possible to determine the balance transfer from GraphQL

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
Mina daemon status
-----------------------------------

Global number of accounts:                     6410
Block height:                                  288
Max observed block height:                     288
Max observed unvalidated block height:         288
Local uptime:                                  2h55m33s
Ledger Merkle root:                            jx4o854hHktZsvd94HuAx7pU8uEDuXwNr1RbDfL2yC1Dy8pX7pf
Protocol state hash:                           3NKpSd7NzMEeGxBZ7NKVWPE5n93pv3zRaQWAsyLNkmZTb7bjFazB
Chain id:                                      da081e702d0e02be30a7351bc2a54898593bb67934b46809400af4c890d13c89
Git SHA-1:                                     ba9a0e088b73a3c389550ee002ef0afc1ce3976d
Configuration directory:                       /root/.mina-config
Peers:                                         28
User_commands sent:                            4
SNARK worker:                                  None
SNARK work fee:                                100000000
Sync status:                                   Synced
Catchup status:                                
        Finished:  53
```

**Comment by deepthiskumar** [comment]
https://github.com/MinaProtocol/mina/pull/10342 added all the party fields
