### ISSUE TITLE
Setting vesting schedule in the genesis ledger and using snapps- (what happens when there is a conflict between the two?)

### ISSUE THREAD

**Issue by p-shahi** [MinaProtocol/mina#10360]
Test type: Integration test/Manual test

Acceptance Criteria: 

Desc: The snapp transaction should fail since the account exists and one can’t change the schedule

**Comment by psteckler** [comment]
Does this differ from #10489?

**Comment by deepthiskumar** [comment]
I guess it doesn't. It is the same code path.
