### ISSUE TITLE
Duplicate (already submitted)

### ISSUE THREAD

**Issue by p-shahi** [MinaProtocol/mina#10367]

**Comment by psteckler** [comment]
What does "duplicate" mean here?

If the transaction has a duplicate nonce, it will be rejected with an invalid nonce.

If the nonce is different, there's no reason to reject the transaction (assuming there's still sufficient funds).

**Comment by deepthiskumar** [comment]
Valid nonce but duplicate of a transaction that already exists in the pool

**Comment by deepthiskumar** [comment]
Integration test
