### ISSUE TITLE
Transaction construction end-to-end test in CI

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#10438]
A zk app that we deploy on a integration test network and send transactions with mina signer

In the test in the Mina repo

Maybe: `clone snarkyjs@alpha`, use local copy of signer; during the integration test

**Comment by mitschabaude** [comment]
* Instead of clone in CI, make `snarkyjs` a git submodule of `mina`
* Create process for snarkyjs releases that is tied to updating the submodule in mina, so that CI ensures the end-to-end test is passing
