### ISSUE TITLE
Balance and any auxiliary data for transactions in breadcrumbs

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#10459]
... rather than blocks. Part of transaction status is balances of the accounts involved in the transaction and if any account creation fee was paid. This data is required by the archive process. With snapps this information will be for each and every party in a transaction which could be significant when there are a lot of snapp transactions in a block. 
Instead of making it part of blocks, it could be part of breadcrumbs and sent to the archiver

**Comment by psteckler** [comment]
In the `Breadcrumb` RPC message, we can put information for every account affected by the transactions in the block. That could be the entire `Account.t`.  The archive db can use the balance and nonce, at least.

Account creation fees are associated with particular transactions, so those will need to mention what kind of transaction (internal, user, zkapp), the sequence no/secondary sequence no., and which account is involved (fee payer, receiver, etc.).

**Comment by deepthiskumar** [comment]
Changes:
* Use staged ledger in the breadcrumb to get the account states
* Change the diff sent to the archive processor to include `Account.t`s and account creation fees
* Archive processor
* Replayer
* Precomputed blocks

**Comment by psteckler** [comment]
Also, rename the RPC from `Breadcrumb`, which is a data structure associated with the transition frontier, to something like `New_block`.

**Comment by psteckler** [comment]
The task estimate in this issue is for the particular task of updating the RPC contents.

**Comment by psteckler** [comment]
Issues for subtasks: #10507, #10508, #10509

**Comment by deepthiskumar** [comment]
All the subtasks done
