### ISSUE TITLE
Update plookup spec to include multiple lookup tables

### ISSUE THREAD

**Issue by carterbrett** [MinaProtocol/mina#10494]
### Description
Update extend lookup spec to include a spec for multiple lookup tables.

### Acceptance Criteria
1. PR with plookup spec update  for multiple lookup tables reviewed by team (at a minimum Matthew).
2. PR (AC 1) merged to master.

**Comment by dannywillems** [comment]
Changes will be available in [this PR](https://github.com/o1-labs/proof-systems/pull/1070)

**Comment by dannywillems** [comment]
Note that this one is already implemented and in the spec. However, it might not be up-to-date with the code. It will be in the scope of [this PR](https://github.com/o1-labs/proof-systems/pull/1070).

**Comment by dannywillems** [comment]
This is already in the spec, see [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNiQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6f2b6213d415158d3162c29224f04b6d3ccb01a/image.png)
