### ISSUE TITLE
Implement runtime lookup tables in Kimchii

### ISSUE THREAD

**Issue by carterbrett** [MinaProtocol/mina#10497]
### Description
Implement the runtime lookup tables specification 💁. 

### Acceptance Criteria
1. PR is sufficiently reviewed
2. PR is merged

**Comment by joseandro** [comment]
I am closing this one for Kimchii and will open a new one for Pickles.

**Comment by joseandro** [comment]
Wrongly closed it. Reopening it to move it to "In Review".
