### ISSUE TITLE
Better (re)build performance

### ISSUE THREAD

**Issue by Firobe** [MinaProtocol/mina#10503]
This issue documents ongoing work and experiments towards decreasing the time Mina CLI takes to build from scratch and rebuild upon small modifications.

All measurements are made on a 48-threaded build machine with the following hardware: AMD EPYC 7401P 48-Core CPU and 128G of RAM, and after a first unmeasured warmup build to mitigate cache effects. The measured processes are limited to 24 threads, to mitigate the effect of other activity on the machine.

# Analysis

## Quality of parallelization
The following graph shows the CPU allocation of 10 consecutive builds over time.

![base](https://user-images.githubusercontent.com/5913585/162544229-4eb09adf-a596-449b-8a29-1bfcd2306e7c.png)

As we can see, `dune` makes full use of the different cores during a first build phase, but afterwards around 60 seconds the parallelization of jobs becomes very bad, which indicates several bottlenecks in the build system.

## Dune trace

Use dune's trace system to analyze where time is spent the most / visualize the overall dependency graph

TODO

# Potential solutions

## Better parallelization with .mli files

A potential solution to the parallelization issue described in the first Section is to increase the number of .mli files in the code base. This allows dune to quickly build the dependency graph and to begin building source files that depend on `a.mli` without having to build `a.ml` first to obtain its interface.

We use https://github.com/Firobe/mligen (still WIP) to automatically generate correct .mli files (other tools have many situations where the generated .mli is not correct, unfortunately). 

A first result with newly generated .mli files can be seen in the graph below, where measurements are made on the code base with [242 generated .mli files](https://github.com/MinaProtocol/mina/compare/tweag-cleanup...generated-mlis).

![compare_base_with_generated_mlis](https://user-images.githubusercontent.com/5913585/162547695-bd2a3ffa-a2c3-44d6-bb0c-38d53402491a.png)

The average build time is very slightly lower, which means that the parallelization gain is enough to compensate for the slowness of adding more files to build, but barely enough to reduce the overall time.

### to 2.9.3

Easy to upgrade as it doesn't break anything. But no noticeable difference in both average build time or parallelization quality, with or without generated .mli files.

### to 3.0.3

It's a bit harder to upgrade as there are conflicts with other packages, but they can be safely ignored and overridden. There is a slight time gain (3 seconds) but it is really more significant with generated .mlis:

![compare_base_dune3 0 3_mli](https://user-images.githubusercontent.com/5913585/162588085-247511e9-f929-4097-bff4-addd72c491f8.png)

Combining both the upgrade and the generation of .mlis allow to gain almost **20 seconds** in overall build time, on average. It seems dune 3.0.3 is better at leveraging interface files for better parallelization, in particular around 100 seconds.

*All further measurements are made with dune 3.0.3*

## Use a more performant linker

Linking steps are significant bottlenecks in the build process. I am trying to see if using different linkers can improve the overall build time. It would be especially useful for rebuild times.

Potential candidates are:
- mold
- LLVM's lld

Changing linkers from `GNU ld` to `ld.lld` [requires some effort](https://github.com/MinaProtocol/mina/compare/tweag-cleanup...build-with-lld), in particular in `ocaml-rocksdb`. This is facilitated by the use of Nix.

The table below illustrates some results, with each measurement averaged over 10 runs. We evaluate impact on *rebuild* times by measuring incremental builds after modifications in different core libraries.

|  Measurements (s)    | GNU linker | LLVM's lld | mold |
| --- | --- | --- | --- |
| Overall build  |  259.03 ±  3.07 | 244.61 ±  0.75 |  |
| Rebuild (no change) | 15.43 ±  4.37 |15.83 ±  4.93 | |
| Rebuild (white space change in Mina_base.Ledger) | 101.35 ± 12.13 | 76.52 ± 11.63 | |
| Rebuild (type change in Transaction_snark) |115.69 ±  8.59 |106.69 ±  8.15 | |

There is an improvement of between 10 and 25 seconds on average, depending on the situation. This is nice but not significant for whole builds. However for rebuilds this is a significant improvement since it can speed up the build up to 25%, which can really be felt while iterating during development.

**Hence, changing linkers is a simple low-hanging fruit to improve the developer experience (as well as the CI, marginally).**

## Solutions not tried yet
- improve compile-time configuration to not rebuild/generate files as much
- rebuild: improve cargo support in dune, as to not rebuild artifacts unnecessarily
- rebuild: same for OCaml artifacts

**Comment by Firobe** [comment]
One outcome of the analysis is that switching linkers is worth it. Making that change is tracked in #10761.

**Comment by rgrinberg** [comment]
> Easy to upgrade as it doesn't break anything. But no noticeable difference in both average build time or parallelization quality, with or without generated .mli files.

Is that with clean builds? .mli files should still offer a significant performance boost to incremental builds under these two conditions:

1. The incremental change only affects .ml files
2. The build is done in the development profile.

**Comment by Firobe** [comment]
Dune 3 upgrade has been merged, and LLD usage should be soon. I'll make experiments with incremental builds + MLI files to make a decision on whether MLI file generation should be considered in the long term, and then close this overarching issue.
