### ISSUE TITLE
Add a check that this completes in enough time for the protocol to remain secure

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#10513]

**Comment by stevenplatt** [comment]
A [DRAFT] final research report of bootstrap testing is located: https://github.com/MinaProtocol/mina-deployments/blob/main/benchmarks/bootstrap_process/research-report.md

At the end of this report is an explanation of consensus safety, based on the time required for bootstrap operations. Final bootstrap numbers are needed to complete this analysis. 

After PR 11973 is merged, I will rerun the bootstrap test cycle to complete this analysis.
