### ISSUE TITLE
Q1.2. Create benchmarks for bootstrapping new nodes

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#10511]
The following scenarios have been requested for bootstrap benchmarking: 

- network is still k blocks within genesis (no ledger download)
- network is > k blocks after genesis, but within 2 epochs (no epoch ledger downloaded)
- network is 2-3 epochs after genesis (1 epoch ledger downloaded)
- network is > 3 epochs after genesis (full bootstrap)

Additional notes from @nholland94 : 

"All of the above bullet points can be thought as of states of the chain. Ideally, we would have tests were we pair up different persisted states the node is in with these tests. Eg: test bootstrapping to the network at > 3 epochs when the persisted data base is empty, when the persisted database has a state > k block after genesis, etc...

Additionally, the parts of this bootstrap process that involve ledger download need to be tested with special care. The current ledger download process is slow and expensive. As the ledger grows, bootstrapping nodes take longer to download the ledgers, and put network pressure onto the participating nodes that are serving them data. So the ledger download needs to be measured (ideally on both sides -- how long does the download take, and how much time do the other nodes spend serving the requests)."

--------

These additional items are also requested, but are expected to be added as an update during a future sprint: 

Additional notes from @nholland94 : 

"Finally, there are some edge cases related to bootstrap that would be nice to test. These are kind of hard to enact reliably though. But we would like to test:"

- root ledger migrations during bootstrap (while we are downloading a ledger; code is supposed to retarget the new ledge quickly)
- epoch transition during bootstrap (before we download the epoch ledgers, during downloading them, and after)
- bootstrapping to a network where a certain % of nodes a stuck on a bad chain (non-canonical)
- bootstrapping to a network where adversaries lie to you about the network state (the bootstrapping node should ask enough parties and retarget the best states)
- bootstrapping to a network where adversaries try to get you to download ledgers that don't exists (this is sort of a subcategory of the above, but is different in behavior)

Daemon Version Requested: minaprotocol/mina-daemon:1.3.0 (pending confirmation)

**Comment by stevenplatt** [comment]
The assigned sprints have been updated to reflect that this item has not been worked in in 2023.

**Comment by stevenplatt** [comment]
All items within this epic have been completed or cancelled. Future work for benchmark items is being moved to Mina Foundation. There is also additional work to place bootstrap tests into CI, but these are being tracked as separate items from the initial manual bootstrap stress testing. 

Documentation for the process used to deploy testsnets and complete bootstrap benchmarks can be found here: 
https://github.com/MinaProtocol/mina-deployments/blob/main/benchmarks/bootstrap_process/README.md

Initial results of bootstrap tests can be found here:
https://github.com/MinaProtocol/mina-deployments/blob/main/benchmarks/bootstrap_process/research-report.md

Initial testing uncovered a bug in the libp2p message size allowance and was not able to fully complete. This configuration has been updated and merged into develop here: https://github.com/MinaProtocol/mina/pull/11971
