### ISSUE TITLE
Q1.6. Mainnet nodes launch

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#10515]
Redeploying the existing Mainnet nodes allows these improvements: 

- Documents node configurations fully as infra-as-code (repeatable deployment).
- Moves nodes into a global topology for improved observability of the prod environment (if needing to run tests or traces within Mainnet).

Validate Terraform combined with the new "generic node" helm chart (published to artifact hub), to deploy each of the node roles. 

- [ ] Seed Node
- [ ] Archive Node
- [ ] Rosetta Node
- [ ] Watchdog Node
- [ ] Block Producer
- [ ] Snark Worker Node
- [ ] Snark Coordinator Node

**Comment by stevenplatt** [comment]
this item is an old request and no longer valid
