### ISSUE TITLE
Automate benchmark for bootstrapping new nodes from a clean state to a network with a full ledger (using various ledger sizes)

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#10512]
This task is being updated, as there is already an epoch that capture the original title of this work. 

This task is now updated to document work needed at the conclusion of the initial bootstrap benchmarks - to automate the workflow and deployment use (and replace the manual data collection that was done as part of the initial iteration). 

When automated, the flow is proposed to run during each major release (not sooner), and would live within a dedicated CI pipeline that allows for long running jobs. 

Today, the flow should support testnets with ledgers of the following sizes: 
- 375,000 wallets [~79M json file size]
- 625,000 wallets [~138.8M json file size]
- 875,000 wallets [~195M json file size]

The flow may be expanded in the future to include large ledgers which to no boot today (but may after future code updates).

**Comment by stevenplatt** [comment]
Work for protocol benchmarking has recently moved to Mina Foundation and other Mina Foundation partners. Additional work on this item is not expected.
