### ISSUE TITLE
Intg test: Investigate and improve cleanup scripts

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#10548]
Our cleanup scripts are not functioning they way they were supposed to. We need to make sure we are properly cleaning our CI environments and releasing resources accordingly, even when tests have odd or unexpected failures

if the intg-test is cntrl-c'd or killed somehow, then it leaves the log sync and doesn't clean it up. gotta figure out how to clear out the log syncs better

**Comment by mrmr1993** [comment]
We have both automated cleanup and a docker backend that doesn't need the cleanup at all now. Closing.
