### ISSUE TITLE
Adapt the CI environment to work with a high resources demand from integration tests

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#10549]
- [x]  Add more resources to properly handle the integration tests load
- [x]  Use a unique Buildkite agent "size" for integration tests to queue them

**Comment by stevenplatt** [comment]
This item has been completed. The linked PR has been merged to allow calling the new buildkite pods which use the tag `size=integration`. The CI pipeline itself has also been tested with the `ci-buile-me` tag to confirm there are no conflict. In addition to the linked PR, these additional updates were applied: 

- A new node pool has been added to the `mina-integration-west1` kubernetes cluster to assign more physical resources to kubernetes. 
- 40 new buildkite pods have been deployed using yaml config [buildkite-central-integration](https://github.com/MinaProtocol/mina-deployments/blob/main/src/buildkite/buildkite-central1-integration.yaml)
