### ISSUE TITLE
Shutdown before Coda instance was created

### ISSUE THREAD

**Issue by shunzuowu** [MinaProtocol/mina#10565]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Summary:
"Shutdown before Coda instance was created"
Status:
{"OS_type":"Unix","Release":"4.9.0-6-amd64","Machine":"x86_64","Sys_name":"Linux","Exception":{"commit_id":"9b0369c27bb85c8ab2f8725c6e977eb27b53b826","sexp":["monitor.ml.Error",[["rpc_error",["Connection_closed",["EOF or connection closed"]]],["connection_description",["Client connected via TCP",["localhost","40783"]]],["rpc_tag","worker_init_rpc_1"],["rpc_version","0"]],["Raised at Base__Error.raise in file \"src/error.ml\" (inlined), line 8, characters 14-30","Called from Base__Or_error.ok_exn in file \"src/or_error.ml\", line 83, characters 17-32","Called from Async_kernel__Deferred1.M.map.(fun) in file \"src/deferred1.ml\", line 17, characters 40-45","Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5","Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 168, characters 6-47","Caught by monitor at file \"src/lib/mina_lib/mina_lib.ml\", line 1281, characters 35-35"]],"backtrace":["Raised at Base__Result.ok_exn in file \"src/result.ml\", line 187, characters 17-26","Called from Async_kernel__Deferred1.M.map.(fun) in file \"src/deferred1.ml\", line 17, characters 40-45","Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5","Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 168, characters 6-47"]},"Command":"Command: (mina daemon --peer-list-url\n https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt)","Coda_branch":"master","Coda_commit":"9b0369c27bb85c8ab2f8725c6e977eb27b53b826"}

### Steps to Reproduce

1.vmware work station
2.install mina
3.mina daemon --peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt
...

### Expected Result

mina running

### Actual Result

mina crashed

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
Error: Unable to connect to Mina daemon.
- The daemon might not be running. See logs (in `~/.mina-config/mina.log`) for details under the host:127.0.0.1.
  Run `mina daemon -help` to see how to start daemon.
- If you just started the daemon, wait a minute for the RPC server to start.
- Alternatively, the daemon may not be running the RPC server on (127.0.0.1 8301).
  If so, add flag `---daemon-port` with correct port when running this command.
```

**Comment by cscetbon** [comment]
Got a similar issue but this time on Mac using Docker which generated the following report
[coda_crash_report_2022-03-30_03-59-14.060426.tar.gz](https://github.com/MinaProtocol/mina/files/8376926/coda_crash_report_2022-03-30_03-59-14.060426.tar.gz)
Let me know if you prefer that I create a different issue but it seems to be a duplicate to me

**Comment by shimkiv** [comment]
Please try with the more recent version https://github.com/MinaProtocol/mina/discussions/11654 (if we're talming about Berkeley QANet).
And feel free to report another issue if it still happens. 
Note though that you might face issues with Docker on M1 Macs.
