### ISSUE TITLE
Improve SnarkyJS performance

### ISSUE THREAD

**Issue by mitschabaude** [MinaProtocol/mina#10638]
This is a tentative epic concerned with picking all low-hanging fruit to improve snark performance in SnarkyJS.

Potential issues to tackle in this epic:

* Implement prover key serialization to avoid compiling circuits on-the-fly before creating a proof. Performance impact: Proof generation 1-2x. 
* Find a way to compile smart contracts with `max_branching=0`, to avoid adding a branching=2 dummy circuit which blows up compilation and proving time. Performance impact: Compiling 5-10x, proof generation 2-3x
* Investigate whether concurrency is optimally used in the nodejs build of snarkyjs, and potentially improve it. Performance impact: Unclear, 1-8x.
* Set up an easy way to run snarkyjs scripts in a browser engine (i.e. puppeteer) to be able to benchmark browser performance (and, potentially, create CI test that ensures snarkyjs works in the browser). Performance impact: None (1x)
* Investigate whether concurrency is optimally used in the browser build of snarkyjs. Performance impact: Unclear, 1-8x.

**Comment by mrmr1993** [comment]
Stale and superseded, closing.
