### ISSUE TITLE
snark work uptime tracker issue

### ISSUE THREAD

**Issue by p-shahi** [MinaProtocol/mina#10678]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

`{"timestamp":"2022-03-29 16:03:00.006619Z","level":"Error","source":{"module":"Uptime_service","location":"File \"src/lib/uptime_service/uptime_service.ml\", line 354, characters 20-32"},"message":"Error when running uptime service SNARK worker on a transaction","metadata":{"error":{"commit_id":"9b0369c27bb85c8ab2f8725c6e977eb27b53b826","sexp":[["rpc_error",["Connection_closed",["EOF or connection closed"]]],["connection_description",["Client connected via TCP",["localhost","40983"]]],["rpc_tag","rpc_parallel_plain_9"],["rpc_version","0"]]},"host":"198.166.228.6","peer_id":"xxx","pid":14,"port":8333}}`

### Steps to Reproduce

Run new snark work uptime tracker service in docker container

### Expected Result

No issue

### Actual Result

Pasted in descriptoin

### How frequently do you see this issue?

Frequently

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
n/a
```

**Comment by Al3c5** [comment]
Same problem here. 

Running as a systemd service. 

Uptime SNARK worker service stopped working after an automatic restart (using  --stop-time parameter)

It worked again after a manual restart.
[uptime.txt](https://github.com/MinaProtocol/mina/files/8462668/uptime.txt)
