### ISSUE TITLE
Auto Cleanup

### ISSUE THREAD

**Issue by mkaito** [MinaProtocol/mina#10694]
Is there a standard or efficient way to clean up orphaned resources in Kubernetes? Some integration tests run terraform to spin up nodes. If Google cloud terminates the VM during a run (we are using preemptible nodes), the cleanup at the end does not happen (since there is no terraform destroy at the close of the test).

**Comment by stevenplatt** [comment]
We may be able to consolidate this item with another ZenHub task: 
https://github.com/MinaProtocol/mina/issues/10629

The above linked item mentions specifically removing unused storage volumes, but the reference GCloud 'Recommender' API may be a good option for removing orphaned resources in other part of GCloud as well.

**Comment by kaozenn** [comment]
I am unsure if this ticket is still relevant.
There is no much activity on the `mina-integration-west1` cluster.
I cannot see any PV (Persistant Volume) in an "Unused" state. There is lots of records of PV in a "Retain" state (~600 day olds average). These Volumes are no longer present from the Cloud Console nevertheless. It let me think we deleted them.
On the `default` namespace there are 2 cronjobs (integration-testnet-namespace-cleanup, integration-testnet-port-mappings-cleanup). They are responsible to clean up the namespace used for running the tests.
If the cluster is still active, we rely on the current cronjob for the auto cleanup. Else the cluster is no longer active. Either way, the ticket is no longer relevant.
