### ISSUE TITLE
Splitting BK Builds

### ISSUE THREAD

**Issue by mkaito** [MinaProtocol/mina#10691]
Can we split the build pipelines in a more efficient way? Because we use a monorepo, are the tests that get run configured efficiently?

**Comment by kaozenn** [comment]
We could use the [Parallel Build](https://buildkite.com/docs/tutorials/parallel-builds) property of Buildkite to run tests in parallel. This would speed up the build time. We would need to map first the list of the Tests that could run in parallel, then refactor the code to do so.
