### ISSUE TITLE
Improve CONTRIBUTING.md in MinaFoundation/mina

### ISSUE THREAD

**Issue by mkaito** [MinaProtocol/mina#10690]
Branch semantics and workflow should be clearly documented in a CONTRIBUTING.md file in the root of the project (or linked to from the primary readme document)

**Comment by yorickvP** [comment]
Current status: @mkaito: Cobbled together a draft of the CONTRIBUTING.md update, need to edit it a bunch

**Comment by mkaito** [comment]
I've been putting this off, since there always seems to be something more important to work on; but I've decided that I'll get it done by the end of next week.
