### ISSUE TITLE
Solutions to tests getting preempted

### ISSUE THREAD

**Issue by balsoft** [MinaProtocol/mina#10731]
- Get rid of preemptible nodes and use a beefy server for integration tests, running them locally (https://github.com/minaprotocl/mina/tree/feature/local-engine-network-config)
- Run, and then shut down, the preemptible nodes, for every integration tests (can only work if billed hourly or more granularly)

**Comment by mrmr1993** [comment]
Fixed under new integration test framework. Closing.

**Comment by robinbb** [comment]
@mrmr1993 Please remove me as assignee of this issue, when next you groom GitHub issues, please.
