### ISSUE TITLE
Mina crashed everyday

### ISSUE THREAD

**Issue by coinpayu** [MinaProtocol/mina#10755]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Here is my crash log.

I am using ubuntu 20.4. It crashes everyday, and it will only be restarted when I login again.

Apr 15 10:30:41 mina mina[65934]: 2022-04-15 10:30:41 UTC [Info] Updating new available work took 9.050846099853516 ms
Apr 15 10:30:41 mina mina[65934]: 2022-04-15 10:30:41 UTC [Info] Rebroadcasting $state_hash
Apr 15 10:30:41 mina mina[65934]:         state_hash: "3NLuLnLZ92B3fCNkGuw9LGUcdRscfCSdtAbbDvfQA4spcLNP2wrg"
Apr 15 10:30:41 mina mina[65934]: 2022-04-15 10:30:41 UTC [Info] Saw block with state hash $state_hash
Apr 15 10:30:41 mina mina[65934]:         state_hash: "3NLuLnLZ92B3fCNkGuw9LGUcdRscfCSdtAbbDvfQA4spcLNP2wrg"
Apr 15 10:31:25 mina mina[65934]: 2022-04-15 10:31:25 UTC [Warn] validation callback timed out before we could respond
Apr 15 10:31:25 mina mina[65934]: 2022-04-15 10:31:25 UTC [Error] libp2p_helper: validation timed out :(
Apr 15 10:32:21 mina mina[65934]: 2022-04-15 10:32:21 UTC [Info] Sending transition_chain_proof to $peer
Apr 15 10:32:21 mina mina[65934]:         peer: {
Apr 15 10:32:21 mina mina[65934]:   "host": "89.58.3.17",
Apr 15 10:32:21 mina mina[65934]:   "peer_id": "12D3KooWMNRGr8UknJWwWoLtbgCvJwLMxFQqF3Bj9v3MxRntzcFq",
Apr 15 10:32:21 mina mina[65934]:   "libp2p_port": 8302
Apr 15 10:32:21 mina mina[65934]: }
Apr 15 10:33:35 mina systemd[55216]: Stopping Mina Daemon Service...
Apr 15 10:33:35 mina mina[69697]: Using password from environment variable MINA_PRIVKEY_PASS
Apr 15 10:33:35 mina mina[69697]: Using password from environment variable MINA_PRIVKEY_PASS
Apr 15 10:33:35 mina mina[69697]: Using password from environment variable MINA_PRIVKEY_PASS
Apr 15 10:33:35 mina mina[65934]: 2022-04-15 10:33:35 UTC [Info] Running async shutdown handler: "Close transition frontier, if exists"
Apr 15 10:33:35 mina mina[65934]: 2022-04-15 10:33:35 UTC [Info] Running async shutdown handler: "Remove daemon lockfile"
Apr 15 10:33:35 mina mina[69697]: Daemon stopping
Apr 15 10:33:35 mina mina[65934]: 2022-04-15 10:33:35 UTC [Info] Mina process was interrupted by "sigterm"
Apr 15 10:33:35 mina mina[65934]: 2022-04-15 10:33:35 UTC [Fatal] Prover terminated due to signal, terminating daemon
Apr 15 10:33:35 mina mina[65934]: 2022-04-15 10:33:35 UTC [Warn] unhandled exception from daemon-side prover server: $exn
Apr 15 10:33:35 mina mina[65934]:         exn: {
Apr 15 10:33:35 mina mina[65934]:   "commit_id": "9b0369c27bb85c8ab2f8725c6e977eb27b53b826",
Apr 15 10:33:35 mina mina[65934]:   "sexp": [
Apr 15 10:33:35 mina mina[65934]:     "monitor.ml.Error",
Apr 15 10:33:35 mina mina[65934]:     [
Apr 15 10:33:35 mina mina[65934]:       "shutdown with inconsistent status",
Apr 15 10:33:35 mina mina[65934]:       [ "status", "1" ],
Apr 15 10:33:35 mina mina[65934]:       [ "status'", "130" ]
Apr 15 10:33:35 mina mina[65934]:     ],
Apr 15 10:33:35 mina mina[65934]:     [
Apr 15 10:33:35 mina mina[65934]:       "Raised at Base__Error.raise in file \"src/error.ml\" (inlined), line 8, characters 14-30",
Apr 15 10:33:35 mina mina[65934]:       "Called from Base__Error.raise_s in file \"src/error.ml\", line 9, characters 19-40",
Apr 15 10:33:35 mina mina[65934]:       "Called from Async_unix__Shutdown.exit in file \"src/shutdown.ml\" (inlined), line 104, characters 2-24",
Apr 15 10:33:35 mina mina[65934]:       "Called from Prover.create.(fun) in file \"src/lib/prover/prover.ml\", line 337, characters 8-20",
Apr 15 10:33:35 mina mina[65934]:       "Called from Async_kernel__Deferred0.bind.(fun) in file \"src/deferred0.ml\", line 54, characters 64-69",
Apr 15 10:33:35 mina mina[65934]:       "Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5",
Apr 15 10:33:35 mina mina[65934]:       "Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 168, characters 6-47",
Apr 15 10:33:35 mina mina[65934]:       "Caught by monitor at file \"src/lib/mina_lib/mina_lib.ml\", line 1281, characters 35-35"
Apr 15 10:33:35 mina mina[65934]:     ]
Apr 15 10:33:35 mina mina[65934]:   ],
Apr 15 10:33:35 mina mina[65934]:   "backtrace": [
Apr 15 10:33:35 mina mina[65934]:     "Raised at Base__Error.raise in file \"src/error.ml\" (inlined), line 8, characters 14-30",
Apr 15 10:33:35 mina mina[65934]:     "Called from Base__Error.raise_s in file \"src/error.ml\", line 9, characters 19-40",
Apr 15 10:33:35 mina mina[65934]:     "Called from Async_unix__Shutdown.exit in file \"src/shutdown.ml\" (inlined), line 104, characters 2-24",
Apr 15 10:33:35 mina mina[65934]:     "Called from Prover.create.(fun) in file \"src/lib/prover/prover.ml\", line 337, characters 8-20",
Apr 15 10:33:35 mina mina[65934]:     "Called from Async_kernel__Deferred0.bind.(fun) in file \"src/deferred0.ml\", line 54, characters 64-69",
Apr 15 10:33:35 mina mina[65934]:     "Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5",
Apr 15 10:33:35 mina mina[65934]:     "Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 168, characters 6-47"
Apr 15 10:33:35 mina mina[65934]:   ]
Apr 15 10:33:35 mina mina[65934]: }
Apr 15 10:33:35 mina mina[65934]: 2022-04-15 10:33:35 UTC [Error] verifier terminated unexpectedly
Apr 15 10:33:36 mina mina[65934]: 2022-04-15 10:33:36 UTC [Info] Starting a new verifier process
Apr 15 10:33:36 mina mina[65934]: 2022-04-15 10:33:36 UTC [Info] verifier successfully stopped
Apr 15 10:33:36 mina mina[65934]: 2022-04-15 10:33:36 UTC [Fatal] libp2p_helper process died unexpectedly: "died after receiving sigterm (signal number 15)"
Apr 15 10:33:37 mina mina[65934]: 2022-04-15 10:33:37 UTC [Fatal] Unhandled top-level exception: $exn
Apr 15 10:33:37 mina mina[65934]: Generating crash report
Apr 15 10:33:37 mina mina[65934]:         exn: {
Apr 15 10:33:37 mina mina[65934]:   "commit_id": "9b0369c27bb85c8ab2f8725c6e977eb27b53b826",
Apr 15 10:33:37 mina mina[65934]:   "sexp": [
Apr 15 10:33:37 mina mina[65934]:     "monitor.ml.Error",
Apr 15 10:33:37 mina mina[65934]:     [ "Mina_net2__Libp2p_helper.Libp2p_helper_died_unexpectedly" ],
Apr 15 10:33:37 mina mina[65934]:     [
Apr 15 10:33:37 mina mina[65934]:       "Raised at Mina_net2__Libp2p_helper.handle_libp2p_helper_termination in file \"src/lib/mina_net2/libp2p_helper.ml\", line 145, characters 8-45",
Apr 15 10:33:37 mina mina[65934]:       "Called from Async_kernel__Deferred0.bind.(fun) in file \"src/deferred0.ml\", line 54, characters 64-69",
Apr 15 10:33:37 mina mina[65934]:       "Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5",
Apr 15 10:33:37 mina mina[65934]:       "Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 168, characters 6-47",
Apr 15 10:33:37 mina mina[65934]:       "Caught by monitor at file \"src/lib/gossip_net/libp2p.ml\", line 171, characters 31-31"
Apr 15 10:33:37 mina mina[65934]:     ]
Apr 15 10:33:37 mina mina[65934]:   ],
Apr 15 10:33:37 mina mina[65934]:   "backtrace": [
Apr 15 10:33:37 mina mina[65934]:     "Raised by primitive operation at Core__Signal.send in file \"src/signal.ml\", line 162, characters 6-61"
Apr 15 10:33:37 mina mina[65934]:   ]
Apr 15 10:33:37 mina mina[65934]: }
Apr 15 10:33:37 mina mina[65934]: 2022-04-15 10:33:37 UTC [Error] Encountered $error while asking libp2p_helper for peers
Apr 15 10:33:37 mina mina[65934]:         error: {
Apr 15 10:33:37 mina mina[65934]:   "commit_id": "9b0369c27bb85c8ab2f8725c6e977eb27b53b826",
Apr 15 10:33:37 mina mina[65934]:   "string": "helper process already exited (doing RPC ListPeers)"
Apr 15 10:33:37 mina mina[65934]: }
Apr 15 10:33:37 mina mina[65934]: (monitor.ml.Error
Apr 15 10:33:37 mina mina[65934]:  ("Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference(\"7dcb25e2-b9ce-3f39-4919-27fca25eae1d\", \"File \\\"src/lib/mina_lib/mina_lib.ml\\\", line 1418, characters 49-56\")")
Apr 15 10:33:37 mina mina[65934]:  ("Raised at Merkle_mask__Masking_merkle_tree.Make.Attached.assert_is_attached in file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 118, characters 10-57"
Apr 15 10:33:37 mina mina[65934]:   "Called from Merkle_mask__Masking_merkle_tree.Make.Attached.merkle_root in file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 266, characters 6-26"
Apr 15 10:33:37 mina mina[65934]:   "Called from Mina_base__Ledger.Ledger_inner.merkle_root in file \"src/lib/mina_base/ledger.ml\" (inlined), line 259, characters 25-38"
Apr 15 10:33:37 mina mina[65934]:   "Called from Mina_commands.get_status.(fun).active_status.(fun) in file \"src/lib/mina_commands/mina_commands.ml\", line 278, characters 6-31"
Apr 15 10:33:37 mina mina[65934]:   "Called from Mina_commands.get_status.(fun).active_status in file \"src/lib/mina_commands/mina_commands.ml\", line 276, characters 4-1023"
Apr 15 10:33:37 mina mina[65934]:   "Called from Async_kernel__Deferred1.M.map.(fun) in file \"src/deferred1.ml\", line 17, characters 40-45"
Apr 15 10:33:37 mina mina[65934]:   "Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5"
Apr 15 10:33:37 mina mina[65934]:   "Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 168, characters 6-47"))
Apr 15 10:33:37 mina mina[65934]: ((2022-04-15 10:33:37.290092932Z)
Apr 15 10:33:37 mina mina[65934]:  ("unhandled exception"
Apr 15 10:33:37 mina mina[65934]:   ((monitor.ml.Error
Apr 15 10:33:37 mina mina[65934]:     ("shutdown with inconsistent status" (status 1) (status' 130))
Apr 15 10:33:37 mina mina[65934]:     ("Raised at Base__Error.raise in file \"src/error.ml\" (inlined), line 8, characters 14-30"
Apr 15 10:33:37 mina mina[65934]:      "Called from Base__Error.raise_s in file \"src/error.ml\", line 9, characters 19-40"
Apr 15 10:33:37 mina mina[65934]:      "Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5"
Apr 15 10:33:37 mina mina[65934]:      "Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 168, characters 6-47"
Apr 15 10:33:37 mina mina[65934]:      "Caught by monitor main"))
Apr 15 10:33:37 mina mina[65934]:    ((pid 65934) (thread_id 0)))))
Apr 15 10:33:37 mina systemd[55216]: mina.service: Main process exited, code=exited, status=1/FAILURE
Apr 15 10:33:37 mina systemd[55216]: mina.service: Failed with result 'exit-code'.
Apr 15 10:33:37 mina systemd[55216]: Stopped Mina Daemon Service.

### Steps to Reproduce

Just followed the doc to setup a block producer node.

### Expected Result

Mina runs without crashing.

### Actual Result

It crashes everyday. 

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
Mina daemon status
-----------------------------------

Max observed block height:              128401
Max observed unvalidated block height:  128401
Local uptime:                           18m55s
Chain id:                               5f704cc0c82e0ed70e873f0893d7e06f148524e3f0bdae2afb02e7819a0c24d1
Git SHA-1:                              9b0369c27bb85c8ab2f8725c6e977eb27b53b826
Configuration directory:                /home/mina/.mina-config
Peers:                                  32
User_commands sent:                     0
SNARK worker:                           None
SNARK work fee:                         100000000
Sync status:                            Bootstrap
Block producers running:                1 (B62qocWjfM3qAxskcdmcUfFPPShwmupTf1vhgciWuLDdqupPrUBys3t)
Coinbase receiver:                      Block producer
Consensus time now:                     epoch=26, slot=3973
Consensus mechanism:                    proof_of_stake
Consensus configuration:                
	Delta:                     0
	k:                         290
	Slots per epoch:           7140
	Slot duration:             3m
	Epoch duration:            14d21h
	Chain start timestamp:     2021-03-17 00:00:00.000000Z
	Acceptable network delay:  3m

Addresses and ports:                    
	External IP:    ******
	Bind IP:        0.0.0.0
	Libp2p PeerID:  12D3KooWC4aZ6ubZcxFFrMmgtg3JNipp65SFhZCd9756SUwiHtny
	Libp2p port:    8302
	Client port:    8301
```

**Comment by mrmr1993** [comment]
The relevant line appears to be
```
Apr 15 10:33:35 mina systemd[55216]: Stopping Mina Daemon Service...
```
This is coming from systemd rather than the Mina daemon itself, and the remainder of the log is the daemon shutting down (albeit noisily).

How are you running the daemon?

**Comment by coinpayu** [comment]
I finally use docker to run mina without any problem! Thanks.

**Comment by coinpayu** [comment]
Close it
