### ISSUE TITLE
Move catchup side effects entirely into super catchup code

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#10806]
Currently, the code for managing side effects related to catchup (cache invalidation, filling result ivars) is split between two locations in the code: `Full_catchup_tree` and `Super_catchup`. This makes it very difficult to avoid race conditions, and was the major contributing factor for the recent bugs we have observed on mainnet related to double cache invalidation.

In order to fix this, we should have all side effects be executed from within the super catchup fstm. However, in order to support this, we now need the ability to cancel active state transitions from the outside and override a catchup node's state. In order to acheive this, we will make the state transitions in the fstm interruptible, and expose a `Bvar.t` which can broadcast a state update into the fstm from the outside. When this happens, the current state transition would be canceled, and the new transition would begin executing in its place.

Once this refactor is done, we can easily move the side effects that currently live in `Full_catchup_tree` into the fstm by adding some new states which enact those side effects. This will eliminate a variety of hard to trace race conditions that we know exist in the code today, and make it easier to spot other existing race conditions internal to the `Super_catchup` implementation moving forward.

**Comment by deepthiskumar** [comment]
Focus on bitswap-catchup instead
