### ISSUE TITLE
Improper documentation for GraphQL Blocks

### ISSUE THREAD

**Issue by Makalfo** [MinaProtocol/mina#10807]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Summary

The GraphQL Documentation specifies that the `creator` field is deprecated for blocks:
```
# Public key of account that produced this block
creator: [PublicKey](https://docs.minaprotocol.com/graphql-docs/publickey.doc.html)! @deprecated( reason: "use creatorAccount field instead" )

# Account that produced this block
creatorAccount: [Account](https://docs.minaprotocol.com/graphql-docs/account.doc.html)!
```
Reference: https://docs.minaprotocol.com/graphql-docs/block.doc.html

However, when doing a subscription with the following:
```
    subscription(){
      newBlock(){
        creator
        creatorAccount
        stateHash
        protocolState { ...
```
An example follows:
```
{
      "newBlock": {
        "creator": "B62qqkTmZGQS181PCESpoAi3W3QF4wmW7FG6f3To9rpv5Q1CyXGsnDz",
        "creatorAccount": {},
        "stateHash": "3NLD4hpGKmyVu5TEwEP28DykQw65pqzzHzZgM4qA5UtCejJpkFLV",
        "protocolState"
```

### Steps to Resolve this Issue

1. Update Documentation or Update Code

**Comment by garethtdavies** [comment]
Not sure the issue here, but you'd want to select a selection of subfields under `creatorAccount` e.g:

```
creatorAccount {
      publicKey
      index
    }
```

The part about deprecated is best practice for deprecating GraphQL fields indicating that it shouldn't be used anymore (use `creatorAccount`) as presumably it'll be removed in future updates.

**Comment by Makalfo** [comment]
Yep! Just realized that! :( 
Closing it
