### ISSUE TITLE
Upgrade to dune 3

### ISSUE THREAD

**Issue by Firobe** [MinaProtocol/mina#10816]
Upgrading to dune 3 has several benefits:
- supports features allowing a more sane compile-time configuration (one example is #10761)
- in some cases, improves the build performance (see #10503)
- we would benefit from a huge number of various fixes and improvements (see [dune changelog](https://github.com/ocaml/dune/blob/main/CHANGES.md#300-11022022))

The upgrade itself should not be too hard. Some packages conflict with dune 3 but it turns out the conflicts are entirely artificial, as dune 3 is retro-compatible.

**Comment by Firobe** [comment]
> ocamlformat: I'm currently trying to relax the constraint (by finding where it is, first). We could also upgrade ocamlformat instead, but that mean would reformating most files, so I want to avoid that.

The conflict is on `odoc`. It was broken in two packages `odoc` and `odoc-parser` in version 2.0.0 and earlier `ocamlformat` don't know that. Unfortunately, `dune` > 3 explicitly conflicts with `odoc` < 2.0.0. We must either:
- remove the conflict on dune
- patch ocamlformat.0.15.0 to understand the newer  `odoc` packages
- upgrade ocamlformat, anyway

**Comment by mrmr1993** [comment]
I'm in favour of upgrading ocamlformat and accepting the one-time pain.

**Comment by Firobe** [comment]
> I'm in favour of upgrading ocamlformat and accepting the one-time pain.

I tend to agree. I'll check if we can make the .ocamlformat file explicit enough with the current version, so that the changes when upgrading are minimal. There will probably still be a lot.

The target for upgrading is `0.20.1`, the last version that doesn't require a breaking `cmdliner` upgrade (that can come later).

**Comment by Firobe** [comment]
PRs https://github.com/MinaProtocol/mina/pull/10896 and https://github.com/MinaProtocol/mina/pull/10906 try to achieve this. Hopefully they can get merged.

**Comment by Firobe** [comment]
Got all approvals, now to merge cleanly when there's not too much activity on the branches.

**Comment by Firobe** [comment]
Conflicts are resolved and PRs are in sync. If the CI passes in time, I'll merge.

**Comment by Firobe** [comment]
Merged!
