### ISSUE TITLE
DNS Migration From AWS to GCP

### ISSUE THREAD

**Issue by samuelarogbonlo** [MinaProtocol/mina#10821]

**Comment by matheus-o1labs** [comment]
Migration Plan

https://docs.google.com/presentation/d/1H6Sdg7Smfjdd8AL2UA3mbI5kNBYYrU7cNpRRh5kkAZg/edit#slide=id.g11b7f98ef73_0_0

**Comment by matheus-o1labs** [comment]
Domain Inventory List

https://docs.google.com/spreadsheets/d/1qH3K8mn5iuN0wTVyeIktmJzkaFm3fyy2wdGvh_-uzmU/edit#gid=831857864
