### ISSUE TITLE
berkeley-qa: archive node error when adding block (causes node to get stuck in catchup)

### ISSUE THREAD

**Issue by p-shahi** [MinaProtocol/mina#10892]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

![unknown](https://user-images.githubusercontent.com/50885601/167315744-4b6b9ee3-d202-4f25-ae22-cdd509923283.png)
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/50885601/167315766-1bd94c52-8a7f-4286-a576-9c762c0efdea.png">

### Steps to Reproduce

Run archive node on release 1.3.1beta1-release-2.0.0-a4eae89

### Expected Result

No error

### Actual Result

Failure as described in description

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

High

### Status

```shell
Mina daemon status
-----------------------------------

Global number of accounts:                     6410
Block height:                                  321
Max observed block height:                     326
Max observed unvalidated block height:         326
Local uptime:                                  1d2h23m5s
Ledger Merkle root:                            jxmCf6YbyFPcEjq66M9eRhGxGjuzZvQAq6xwd9sSTNAY1PePQhY
Protocol state hash:                           3NKjqA8T66VJ7YN7WHwk2peyxUPVHSjieuMTFKvQ5449r3TpaurE
Chain id:                                      44160dad015e5faabd954a053060cfe7d8ff87e8244640b0433c9374d37b9609
Git SHA-1:                                     [DIRTY]a4eae892e1019f82708d34b12164b9f51465189e
Configuration directory:                       /root/.mina-config
Peers:                                         35
User_commands sent:                            0
SNARK worker:                                  None
SNARK work fee:                                100000000
Sync status:                                   Catchup
Catchup status:                                
        To build breadcrumb:           0
        To initial validate:           0
        Finished:                      423
        To download:                   0
        Waiting for parent to finish:  0
        To verify:                     0
```

**Comment by p-shahi** [comment]
reported by @garethtdavies and @icohigh

**Comment by psteckler** [comment]
Were the databases re-initialized before running the nodes? If the schema changed, there may be a mismatch between the archive process code and the database.

I just tried running a local network with the code in `develop`, and was able to archive new blocks.

**Comment by icohigh** [comment]
> Were the databases re-initialized before running the nodes? If the schema changed, there may be a mismatch between the archive process code and the database.
> 
> I just tried running a local network with the code in `develop`, and was able to archive new blocks.

Yes, initialised before running nodes. Everything was fine until block 291, and after it the recording stopped and there were errors in the logs.
Used schemas:
`https://raw.githubusercontent.com/MinaProtocol/mina/a4eae892e1019f82708d34b12164b9f51465189e/src/app/archive/create_schema.sql`
`https://raw.githubusercontent.com/MinaProtocol/mina/a4eae892e1019f82708d34b12164b9f51465189e/src/app/archive/zkapp_tables.sql`

**Comment by psteckler** [comment]
The best way to debug this is to see the SQL command that caused the error.

The archive process should produce logs with that info, or it may be available in the Postgresql logs (maybe in /var/log/postgresql).
