### ISSUE TITLE
Auto Retry CI builds failed due preemption

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#10921]

**Comment by joseandro** [comment]
Can we get this done in q2?

**Comment by robinbb** [comment]
@joseandro Maybe we can. I will check with the team. Meanwhile, may I ask for your assistance with identifying issues that are desired for Q2 with a GitHub label? I suggest "2022Q2" or "2022-Q2" or "OKR-2022Q2" or something like that.

**Comment by michal0mina** [comment]
this is duplicate to #10731 

It will be solved by another project: AWS buildout of CI capabilities
