### ISSUE TITLE
[nix-EPIC] Nix-Based CI

### ISSUE THREAD

**Issue by balsoft** [MinaProtocol/mina#10941]
Nix-based build, test and deployment system for Mina.

**Comment by robinbb** [comment]
@yorickvP It's great to have these notes here to prompt some thought by others. Thank you. I propose that the next action is to gather as a team (those who would work on things related to Nix CI) and construct a set of GitHub issues that are a breakdown of the work into efforts that would sum to give the vision that you collectively develop for this (Epic) work.

**Comment by robinbb** [comment]
The vision shared in this issue, @michal0mina , need not necessarily be shared by you. It may be that this issue is not necessary to complete the "Nix-Enabled CI" project. At your discretion.
