### ISSUE TITLE
Identify any missing metrics for Gossip data collection

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#10962]

**Comment by nholland94** [comment]
## Checklist for metrics required as per this document: https://www.notion.so/minaprotocol/Load-and-Perf-Testing-86fc5bfb0bb5478dbcc2610b3df01ef3

- [ ]  Transaction pool
    - [ ]  processing delay (receipt time to inclusion/rejection time, measured together).
- [ ]  Snark work
    - [ ]  transaction snark proving time (TODO: how to surface this in grafana? are workers scraped by prometheus?)
- [ ]  Block creation
    - [ ]  staged ledger diff creation time, blockchain proving time
- [ ]  Block validation
    - [ ]  block validation delay (receipt time to inclusion/rejection time, measured separately)
- [ ]  Bandwidth, latency:
    - [ ]  libp2p_helper bandwidth usage
    - [ ]  block propagation delta (time sent vs time received, requires script to reconstruct)
- [ ]  Epoch ledger sync:
    - [ ]  time to download each epoch ledger
    - [ ]  time to perform sync ledger to root snarked ledger, number of root snarked ledger retargets while bootstrapping
- [ ]  Persistence
    - [ ]  time spent writing data to rocksdb
    - [ ]  time spent reading data from rocksdb
