### ISSUE TITLE
Support batching of parties transactions in User_command_input

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#11001]
The `inferred_nonce` logic within `User_command_input` does not currently have proper support for parties transactions which increment the fee payer nonce more than once. This is not currently an issue, as we do not publicly expose any APIs which allow submitting parties transactions in batch, but we should still fix this logic sooner rather than later. The offending code can be found here https://github.com/MinaProtocol/mina/blob/develop/src/lib/user_command_input/user_command_input.ml#L155.

**Comment by deepthiskumar** [comment]
sending batch payments have been disabled and not sure if this more useful than simply using sendZkapp command multiple times (since the command would require a fully constructed zkapp transaction; nonces aren't inferred)
