### ISSUE TITLE
intg tests: create a mapping from old framework test case to new framework duplication

### ISSUE THREAD

**Issue by QuiteStochastic** [MinaProtocol/mina#11017]
https://github.com/MinaProtocol/mina/tree/develop/src/app/cli/src/tests

The following are old integration tests currently being run in CI (test name in CI, the actual test file):

- [x] snarkless, src/app/cli/src/tests/full_test.ml.  this test runs src/app/cli/src/tests/full_test.ml which actually has a number of other things, like testing for replay attacks, and doing math after a transaction to make sure the balances are as expected.  once those two items are updated in the new payments_test.ml, then this should be good to remove.  it also tests the functionality of snarkless, which isn't tested in the new framework, but we don't use snarkless for anything at the moment, so it's safe to remove just remove this.   when snarkless becomes relevant again we can create a snarkless test.  it also tests some snarked ledger functionality but that's not pressing either, snapps sort of covers that
- [x] split, coda_shared_prefix_multiproducer_test.ml.  while it would be desirable to have a split-brain/network-partition test, it looks like the "split" integration test running in CI is not testing that at all. it's actually running coda-shared-prefix-multiproducer-test which looks like it's just sending a few transactions, which is well covered by the payments test. this test thereby can be deleted
- [x] delegation, coda_delegation_test.ml.  https://github.com/MinaProtocol/mina/pull/10325
- [x] bootstrap, coda_bootstrap_test.ml.  super-k bootstrap test needs to be written.  in the new integration test, set `k` as low as possible, then stop a node, then let the network run for 2k+1, then restart the node.
- [x] shared state, coda_shared_state_test.ml.  txn pool gossip test logic needs to be written into the new intg test framework.  The shared state test does a prefix check on all the nodes- meaning it checks that all the nodes are in sync with each other. I believe we don’t do that atm. We only check the test conditions on one of the nodes

The following are old integration tests which do not currently run in CI:

- [x] coda_archive_processors_test.ml.  it looks like this test merely checks that a block is produced and saved into the archive node.  this test logic is covered by our current archive_node_test
- [x] coda_block_production_test.ml.  it looks like this test just runs the network for 30 seconds.
- [x] coda_change_snark_work_test.ml.  this changes the key that a snark worker sends the money it gets from snark fees.  this is actually a meaningful test and we will write this into the payments_test.ml in the new framework.  
- [x] coda_five_nodes_test.ml.  this test just runs 5 nodes for 10 minutes to make sure it works.  we don't really need this anymore
- [x] coda_long_fork.ml.  this test stops a node and waits past the epoch duration before restarting it.  this is more like a super-epoch bootstrap test rather than a real long fork test.  in our new framework, we should eventually write 1: a real, adversarial long fork test, and 2: a long bootstrap test (where the node is down for longer than an epoch).  a super-epoch bootstrap test, which is what this test is actually testing, is not hard to write although it would take overnight in the current state of things, and so a few improvements to the integration test framework first would be ideal.  it should be fine to delete test for now, the super-epoch bootstrap test case is ok to not have for now. 
- [x] coda_peers_test.ml.  i think this just runs 2 nodes and makes sure those nodes are up.  we are beyond needing this test
- [x] coda_restart_node_test_test.ml.  this test stops and restarts a node.  we do node bootstrapping in several current integration tests so we don't need it.
- [x] coda_restarts_and_txns_holy_grail_test.ml.  this test sends txns, then restarts a node.  we have test logic for txn sending and restarting nodes in our current integration tests, although now that i think of it, not in the same exact test.  we could easily add this test logic if we like.
- [x] coda_shared_prefix_test.ml.  i'm not sure but it looks to me like this test is just running a network for 60 seconds.  in any case we have common-prefix test logic in chain_reliability test which I assume is the same thing.
- [x] coda_transitive_peers_test.ml.  this test is actually just a super-k bootstrap test, which we will write into the new framework.
- [x] coda_txns_and_restart_non_producers_test.ml.  just a restart test of non block producers.  probably not important, although we aren't actually using plain nodes (ie nodes that don't stake) in our integration test framework.  we could easily add that feature.  one thing this test does apparently try to is a long bootstrap, ie induce a full bootstrap where catchup cannot be performed.  while this would be a great test case to have, upon further inspection it doesn't look like this test is actually doing this test case, and as such nothing would be lost if this is deleted.

**Comment by joseandro** [comment]
@QuiteStochastic can you please add an estimate to this task?

**Comment by QuiteStochastic** [comment]
this ticket is technically just to make the documentation, but I'm reopening it just to help track the renewed effort to check off the rest of the boxes
