### ISSUE TITLE
Pin rosetta-cli to prevent CI breaking on rosetta-cli upgrades

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#11036]
During 5/20 afternoon PST, we noticed that CI jobs were consistently failing due to bad installs of rosetta-cli during the `4-production` dockerfile execution.

This issue resolved itself when rosetta-cli removed the bad releases.

Still, we don't want to break our ability to ship when a dependency upgrades. We should pin rosetta-cli to a known working version 0.7.7 seems to work in the container. Unfortunately, this may entail forking the `install.sh` script that is included within the rosetta-cli repo as the install script there always tries to install the latest release.

**Comment by kaozenn** [comment]
Created PR. Pinned Rosetta version to `v0.10.1`
