### ISSUE TITLE
Use MinaProtocol version of deb-s3

### ISSUE THREAD

**Issue by robinbb** [MinaProtocol/mina#11040]
Remove uses of the tweag/deb-s3 and replace with uses of the newly-created repo, MinaProtocol/deb-s3.

**Comment by Firobe** [comment]
@robinbb Could you give me enough access to https://github.com/MinaProtocol/deb-s3 so that I can make a release on it? The releases from the tweag repo didn't carry during the fork, and at least one of them is needed to update the Docker files of Mina.

**Comment by robinbb** [comment]
@Firobe I think this is done, now. Please verify.

**Comment by Firobe** [comment]
I confirm this is fine, thank you.
