### ISSUE TITLE
Research adding linting/static analysis to OCaml

### ISSUE THREAD

**Issue by Firobe** [MinaProtocol/mina#11048]
There is currently no semantic linting or static analysis of the OCaml codebase, except reformatting and ppx_version checking.

Look into existing projects to see if something is readily applicable or if it would need to be invented.
Non-exhaustive list:
- semgrep
- ...

**Comment by Firobe** [comment]
See discussion on https://github.com/MinaProtocol/mina/issues/11060

**Comment by Firobe** [comment]
Apart from the options mentioned in the above discussion, here are some linters that may not be outdated and usable easily:
- [camelot](https://github.com/upenn-cis1xx/camelot), improvable but worked on
- [typerex-lint](https://github.com/OCamlPro/typerex-lint/) (formerly `ocp-lint`), nice but seems unmaintained
- [bene-gesselint](https://github.com/NathanReb/bene-gesselint), same

**Comment by robinbb** [comment]
Outcome of this issue is a plan of action (or no action). Please refer to the associated (created) issue. Can this issue be closed after the follow-up issue?

**Comment by Firobe** [comment]
I believe the existing (fully automatic) linters are obsolete and/or too hard to maintain by ourselves compared to the benefits they offer. The focus should rather be on enabling as many compiler warnings as possible, as the compiler itself does a goob job at catching a lot of common mistakes.

Semi-automatic static analysis via contracts may still have value for a select number of critical code sections, but this is outside of the scope.

**Comment by robinbb** [comment]
@Firobe Is there an existing issue for the enabling of the compiler warnings? Or, do you perceive that they are already sufficiently "enabled"?

**Comment by Firobe** [comment]
@robinbb Most useful compiler warnings are enabled by default by dune. However in many places these warnings are silenced, sometimes for a good reason, sometimes not. One of Gaga's first tasks was auditing part of these silencings in https://github.com/MinaProtocol/mina/pull/11558

So, I think currently we are in an almost good state, but it's important to remain vigilant.
