### ISSUE TITLE
Add `Binable.of_binable1_without_uuid` to binable version linter.

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#11055]
See if there are corresponding multi-argument functors also to be added.

**Comment by Firobe** [comment]
The corresponding `Binable.Of_binable_**with**_uuid` should be added as well.

**Comment by psteckler** [comment]
The change is needed in `ppx_version`, in the file `tools/print_binable_functors`.

**Comment by psteckler** [comment]
The `with_uuid` functors should not be used in the Mina code. There's a claim that the `without_uuid` functors produce stable (de)serializations, so one can infer the `with_uuid` ones may be unstable.

We can lint for the presence of those functors in code as it's being written, or use the CI linter for that purpose.
