### ISSUE TITLE
Improve developer (onboarding) experience

### ISSUE THREAD

**Issue by robinbb** [MinaProtocol/mina#11061]

**Comment by kantp** [comment]
#11843, #11886 improve the onboarding documentation.

**Comment by kantp** [comment]
@robinbb, are you ok with closing this with the above additions to documentation? There are still things we can do to improve the experience of course, but without a description, the issue seems a bit open ended.

**Comment by robinbb** [comment]
The issue is not well defined, I agree, but also the developer onboarding experience is still not good. So, please leave this open. I will, as part of this issue, give more details about how to improve the experience. First step is to see if @balsoft and @bryanhonof believe the experience is good.
