### ISSUE TITLE
Automate OCaml library dependency upgrades such as with dependabot

### ISSUE THREAD

**Issue by robinbb** [MinaProtocol/mina#11060]

**Comment by Firobe** [comment]
There is currently no support for OCaml in dependabot: https://github.com/dependabot/dependabot-core
This would be non-trivial work, and there is no other similar tool of which I know that has support for OCaml either.

We could hack a script which tries various `opam upgrade` setups, tries the CI on the resulting codebase, and makes PRs for the largest compatible set of upgrades. This could work but would probably be very flaky, and I'm not sure it would be worth the effort.

**Comment by robinbb** [comment]
@Firobe Does there exist a tool that scans OCaml packages for security vulnerabilities? I suspect that the desire to automate upgrades is really a desire to detect when a package must be upgraded due to security issues.

**Comment by Firobe** [comment]
@robinbb  I'm afraid there isn't (yet) even a database of vulnerabilities for OCaml packages, let alone a tool to scan them.

**Comment by robinbb** [comment]
@mohammadreza-ashouri what do you think of this situation? Do you confirm? What method do you propose to automate the discovery of future vulnerabilities in the ecosystem of OCaml packages?

**Comment by mohammadreza-ashouri** [comment]
According to my research so far, there exist only a handful of deprecated syntax checkers and code staying tools for Ocaml code. For example here are some of those:
http://mascot.x9c.fr ->  Mascot is a style-checker for OCaml sources
https://github.com/cryptosense/ocamllint -> Ocamllint detects common errors in OCaml code
https://github.com/npm-ml/BetterErrors -> BetterErrors improves error messages of the OCaml compiler 
There are projects as well, but it seems they are mostly very outdated and focused more on style checking only.
and regarding the vuln data, there are just reports about the compiler and the libraries not about the OCAML written components. 
I think something like Clippy (similar to Clippy-rust) needs to be designed for the ecosystem, which comprises parsers, a semantic tree builder, a proper set of customizable rules, and in the end a public database that allows the communities to report vulnerabilities.

**Comment by Firobe** [comment]
Ah, if we're speaking about static analysis tools then yes, most existing tools are quite outdated. Except potentially [Semgrep](https://semgrep.dev/) which has experimental support for OCaml (and allows specifying custom rules).

There are some recent efforts for formal OCaml code verification, most notably [Gospel](https://github.com/ocaml-gospel/gospel) and its associated tools such as [Cameleer](https://github.com/ocaml-gospel/cameleer) (which needs manually proof effort) or [ortac](https://github.com/ocaml-gospel/ortac) (which is automatic but not static). These tools require a manual specification effort in all cases, so they cannot be applied to the ecosystem at large but rather on small, critical part of the codebase to ensure correctness.

**Comment by Firobe** [comment]
Yes, and indirectly tools to (semi-)automatically detect/report such vulnerabilities in code, and tools to scan dependencies for known vulnerabilities.

**Comment by robinbb** [comment]
Adding OCaml support in dependabot is a substantial task, perhaps appropriate for a community-aiding independent project. Doing so should not be done as part of this issue. This issue is really about solving the problem of detecting out-of-date/insecure dependencies in this code base. The latter requires the coordinated reporting of vulnerabilities by the community, as you mention. That also is out of scope for your mandate, @Firobe.

I propose that: (1) We tag this as an epic issue, and (2) assign it to me. I'll do those things.

**Comment by robinbb** [comment]
@mohammadreza-ashouri Based on the comment at https://github.com/MinaProtocol/mina/issues/11048#issuecomment-1234038437 it seems like the OCaml ecosystem has no good linter that would possibly help to reduce security vulnerabilities, note.

**Comment by mohammadreza-ashouri** [comment]
@robinbb As I stated before, I think the same

**Comment by robinbb** [comment]
Yup, it seems there is consensus. We may want to press for the improvement of this situation, but of course this GitHub issue is not the place for that.

I know of an initiative, currently underway, to augment the OCaml tooling for this kind of thing, but it is a long way from providing the automation required for this issue.

So, given the state of affairs, I will close this issue as "won't do", and we can revisit the matter with a new issue once the appropriate automation tools exist.
