### ISSUE TITLE
Introduce Absorb trait in Kimchi / Oracles

### ISSUE THREAD

**Issue by rot256** [MinaProtocol/mina#11099]
Currently the Sponge type has different methods for absorbing different types, e.g.

```
.absorb_g : for slices of group elements
.absorb_fr : for slices of field elements
```
This means that if one wants to absorb a new type, the `ìmpl` of the Sponge must change. I propose to instead introduce an `Absorb` trait which can be implemented for every "absorbable" type.

It might look something like:

```rust
pub trait Absorb<F: FftField + PrimeField> {
    fn absorb(&self, sponge: &mut Sponge<F>);
}
```

With implementations for "field" elements and "group" elements.
Then add a method to the Sponge type as follow:

```rust
pub fn absorb<T: Absorb<F>>(&mut self, val: &T) {
```

Enabling it to "absorb" any "absorbable" type. The advantages of this approach are numerous:

1. Unified notation for absorbing different types: it is always `sponge.absorb(val)` regardless of which type `val` has.
2. Allows implementing `Absorb` for new types defined in other crates.
3. Reduces the number of future changes to the Sponge type.
4. Allows automatically deriving implementations, e.g. slices of "Absorb" as follows:

```rust
impl<F: FftField + PrimeField, T: Absorb<F>> Absorb<F> for [T] {
    fn absorb(&self, sponge: &mut Sponge<F>) {
        self.iter().for_each(|c| c.absorb(sponge))
    }
}
```

It even enables us to `#[derive(Absorb)]` for structs in the future should we desire to.

**Comment by rot256** [comment]
Currently the Sponge type has different methods for absorbing different types, e.g.

```
.absorb_g : for slices of group elements
.absorb_fr : for slices of field elements
```
This means that if one wants to absorb a new type, the `ìmpl` of the Sponge must change. I propose to instead introduce an `Absorb` trait which can be implemented for every "absorbable" type.

It might look something like:

```rust
pub trait Absorb<F: FftField + PrimeField> {
    fn absorb(&self, sponge: &mut Sponge<F>);
}
```

With implementations for "field" elements and "group" elements.
Then add a method to the Sponge type as follow:

```rust
pub fn absorb<T: Absorb<F>>(&mut self, val: &T) {
```

Enabling it to "absorb" any "absorbable" type. The advantages of this approach are numerous:

1. Unified notation for absorbing different types: it is always `sponge.absorb(val)` regardless of which type `val` has.
2. Allows implementing `Absorb` for new types defined in other crates.
3. Reduces the number of future changes to the Sponge type.
4. Allows automatically deriving implementations, e.g. slices of "Absorb" as follows:

```rust
impl<F: FftField + PrimeField, T: Absorb<F>> Absorb<F> for [T] {
    fn absorb(&self, sponge: &mut VarSponge<F>) {
        self.iter().for_each(|c| c.absorb(sponge))
    }
}
```

It even enables us to `#[derive(Absorb)]` for structs in the future should we desire to.

**Comment by mimoo** [comment]
would it make sense to call this "send" to emulate a transcript? Otherwise I love this idea!

**Comment by mimoo** [comment]
btw, this issue would be more relevant in the proof systems repo :o
