### ISSUE TITLE
Nix CI: add integration tests

### ISSUE THREAD

**Issue by balsoft** [MinaProtocol/mina#11126]
We need to run integration tests in the Nix CI.

- [ ] Set up credentials for google cloud access
- [ ] Add corresponding jobs for each integration test

**Comment by yorickvP** [comment]
- [ ] check the status on local integration tests

**Comment by yorickvP** [comment]
Current process to run local integration tests:
```
nix build mina#mina-daemon-docker && docker load -i=./result
nix shell mina#mina_integration_tests
test_executive cloud peers-reliability --mina-image mina-daemon:INSERT_HASH_HERE
```

**Comment by yorickvP** [comment]
There is also a branch,
nix-ci-intg-tests, then do nix develop mina#integration_tests

**Comment by mzajda0mina** [comment]
Update after talking with @balsoft :
- integration test fails
- increasing timeout between triggering transactions and checking blockchain doesn't help
- not sure what to look for in integration test log
- only 1 of all integration tests is failing
- this one is failing https://buildkite.com/tweag-mina-demo/mina/builds/3317#01845aea-c3be-4813-be93-e0b3d6a037f9
