### ISSUE TITLE
Ensure the stability of Nix CI

### ISSUE THREAD

**Issue by balsoft** [MinaProtocol/mina#11124]
In https://github.com/MinaProtocol/mina/pull/10898, we propose a prototype of a Nix-based CI. To ensure that it works correctly, we need to run it in parallel with the current CI system. For that, a suitable webhook needs to be added, and some buildkite setup has to be changed.

**Comment by kantp** [comment]
I think it's safe to close this issue. The current state is that the nix CI is running side by side with the current CI (in a non-blocking manner), and it's working smoothly.

Switching over to the nix CI will of course require us to check that everything is still working, but we don't need to track that with this issue anymore.

Nice work @balsoft!
