### ISSUE TITLE
A user of receipt chain database should be able to provide their own custom database

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#1118]
Continuation of #1116

A user would most likely use their own database service to store their receipt chains, i.e. Amazon RDS or Amazon App sync. Their database will be running in another port or server that is independent of the daemon process. We can make RPC calls to their database to add transactions and query proofs. The user just needs to implement these calls on their end.

This could be a good first issue

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
