### ISSUE TITLE
Rosetta: Change logic for pulling archive backups to fallback to older days if one day is missing

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#11194]
The docker container that hosts the all-in-one Rosetta instance bootstraps itself from an archive node backup by looking for “today’s” backup.

This issue is referring to changing this logic to also accept backups from earlier than “today” if “today” had failed for some reason (this has happened before in rare circumstances).

**Comment by kantp** [comment]
@bkase Can you please give a bit more context what this issue is about?

**Comment by kantp** [comment]
@kaozenn Does that sound like something you can take on (not super urgently)?

**Comment by kaozenn** [comment]
I can take it on @kantp .

**Comment by kantp** [comment]
Perfect, thanks!

**Comment by kaozenn** [comment]
@bkase If I understand correctly

We need to loop this curl from"today" until "today - _n_" until we get a 200

https://github.com/MinaProtocol/mina/blob/develop/src/app/rosetta/init-db.sh#L30

Right?

**Comment by kaozenn** [comment]
!ci-build-me
