### ISSUE TITLE
Weekly job reports for CI

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#11217]
A simple report that includes:
* Number of failures (table + histogram)
* Why they failed (explanations about each exit code)
* Job timing: how long, on average for the week, the jobs took to run (in minutes)

**Comment by amc-ie** [comment]
@matheus-o1labs it makes sense to pick this up again when looking at the weekly reports; this is the information as discussed that will be very useful for quantifying our improvements (also showing performance degradation).

**Comment by mrmr1993** [comment]
Stale, closing.
