### ISSUE TITLE
Kimchi: Enforce number of prev IPA commitments in verifier index

### ISSUE THREAD

**Issue by carterbrett** [MinaProtocol/mina#11230]

**Comment by mrmr1993** [comment]
In review: https://github.com/MinaProtocol/mina/pull/11442 and https://github.com/o1-labs/proof-systems/pull/671

**Comment by o1-david** [comment]
still missing this check right? https://github.com/o1-labs/proof-systems/pull/609/files#diff-fc95db4d289fd33bc7fbefe8a487926ce8b47cbe71f047a1dd6933d7444b5d5aR159
