### ISSUE TITLE
When i tried to run block producer node it was giving side car issue

### ISSUE THREAD

**Issue by sbnair** [MinaProtocol/mina#11266]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

When i tried to run Block producer node using this minaprotocol/mina-bp-stats-sidecar:latest i got the invalid upload_url error : https://us-central1-mina-mainnet-303900.cloudfunctions.net/block-producer-stats-ingest/?token=72941420a9595e1f4006e2f3565881b5   

### Steps to Reproduce

1. Unable to run block producer node because of the upload_url as the side car was giving error.
2. docker pull minaprotocol/mina-bp-stats-sidecar:latest is command i used to install block producer node.
3.
...

### Expected Result

1. I was expecting to run block producer using this link : https://docs.minaprotocol.com/en/advanced/bp-sidecar

### Actual Result

Got this error when running BP node : urllib.error.URLError: <urlopen error [Errno -3] Try again>
ERROR:root:<urlopen error [Errno -3] Try again>
Traceback (most recent call last):
 File "/usr/local/lib/python3.9/urllib/request.py", line 1346, in do_open
  h.request(req.get_method(), req.selector, req.data, headers,
 File "/usr/local/lib/python3.9/http/client.py", line 1253, in request
  self._send_request(method, url, body, headers, encode_chunked)
 File "/usr/local/lib/python3.9/http/client.py", line 1299, in _send_request
  self.endheaders(body, encode_chunked=encode_chunked)
 File "/usr/local/lib/python3.9/http/client.py", line 1248, in endheaders
  self._send_output(message_body, encode_chunked=encode_chunked)
 File "/usr/local/lib/python3.9/http/client.py", line 1008, in _send_output
  self.send(msg)
 File "/usr/local/lib/python3.9/http/client.py", line 948, in send
  self.connect()
 File "/usr/local/lib/python3.9/http/client.py", line 919, in connect
  self.sock = self._create_connection(
 File "/usr/local/lib/python3.9/socket.py", line 822, in create_connection
  for res in getaddrinfo(host, port, 0, SOCK_STREAM):
 File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
  for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3]

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

High

### Status

```shell
As of now i was able to run BP using this docker image : minaprotocol/mina-daemon:1.3.1-3e3abec-bionic-mainnet.
```

**Comment by robinbb** [comment]
This issue is addressed directly in the Troubleshooting section of https://docs.minaprotocol.com/en/advanced/bp-sidecar - as indicated by your repro instructions, above, you did not configure an address (public key). In that case, we can close. If the repro instructions are not correct or incomplete, then we can also close as this is an insufficient bug report.
