### ISSUE TITLE
Dynamically allocate the proper toolchain container.

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#11300]

**Comment by joseandro** [comment]
@lk86 is there any more information you can share to help Tweagers understand the scope of this task? Thanks

**Comment by joseandro** [comment]
Can we keep this one in the backlog instead? "New Issues" should only track things that haven't yet been triaged.

**Comment by robinbb** [comment]
@joseandro @lk86 I think that there is no well-define work, here. Can we close?

**Comment by lk86** [comment]
Yeah you can close this. In the Google Cloud Build world the container will already be cached without too much extra effort, no need to hack something together on the existing setup.
