### ISSUE TITLE
Verification fails on proofs which merge 1 previous proof, after conversion with `Side_loaded.of_proof`

### ISSUE THREAD

**Issue by mitschabaude** [MinaProtocol/mina#11389]
impact: this would currently prevent these proofs from being accepted in transactions. for example, the mastermind example would probably not work when deployed on-chain

to reproduce, run the snarkyjs example `src/examples/program.ts`, and observe the `bad verify: dlog_check` messages

**Comment by joseandro** [comment]
@mitschabaude has this work been deprioritized?

**Comment by mitschabaude** [comment]
Not to my knowledge! It has to be fixed at least before the HF, otherwise we won't support fully recursion in user circuits

There's this PR, which has been open for a couple of weeks, which addresses the issue:
https://github.com/MinaProtocol/mina/pull/11698
It seems to have a couple of integration tests failing still
