### ISSUE TITLE
verify vk hash

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#11425]
Verify the vk hash when setting verification keys from parties transactions

**Comment by deepthiskumar** [comment]
make With_hash.t and friends non-`bin_io`-able, to make sure that we're not trusting any hashes that we get over the network.

**Comment by psteckler** [comment]
> make With_hash.t and friends non-`bin_io`-able, to make sure that we're not trusting any hashes that we get over the network.

For `Get_ancestry`, the hash in the query is documented to be untrusted, so we could have a `With_untrusted_hash` type that's serializable.

But there are several other uses of the serialized `With_hash` type.

**Comment by psteckler** [comment]
In #11531, the hashes for verification keys are not sent over the wire; the hashes are computed on receipt.
