### ISSUE TITLE
Create logic for recording receipt_chain_hash for multiple transactions

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#1143]
Right now, we are recording payments with Receipt_chain_database right after we schedule them. As a result, we do not accurately save the previous `receipt_chain_hash`. When we send multiple transactions at the same time, they would refer to the same previous `receipt_chain_hash`, but there may be a case where these transactions are applied on top of each other. Thus, they refer to different `receipt_chain_hash`s. We should accommodate for this.

**Comment by wu-s-john** [comment]
This is addressed in the client storage RFC: https://github.com/CodaProtocol/coda/pull/2901

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
