### ISSUE TITLE
Transaction hash for parties is very slow

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#11430]
The hash relies on `Parties.to_base58_check`.

Nathan has suggested using `Binable.of_string` as a faster replacement.

Issue: we also use the Base58Check in GraphQL as the "transaction id", so we're still calling that, even if we don't use it for hashing.

Suggestion: get rid of the transaction id, use the transaction hash in GraphQL for queries currently use the id, maintain a mapping from hashes to transactions (in the transition frontier?).

**Comment by psteckler** [comment]
`compute-receipt-chain-hash` uses a transaction id as input, so we'd want to be able to create one on demand, perhaps with a GraphQL endpoint (or maybe change that command to take a transaction hash).
