### ISSUE TITLE
Relax ppx_version checking when adding constraints

### ISSUE THREAD

**Issue by Firobe** [MinaProtocol/mina#11439]
As seen here: https://github.com/MinaProtocol/mina/pull/11387#issuecomment-1168984447, `ppx_version` considers that adding a type equality to an existing versioned type is a breaking change.

This should not be the case.
Note that if that if there was already a type equality in the declaration, changing it should be okay too, **except** if the type is an alias (i.e. only a type equality, with no definition).

**Comment by psteckler** [comment]
When we use `bin_shape_t`s for linting in CI, rather than the textual representation of types, this annoyance should disappear.

Or does the issue occur before CI?

**Comment by Firobe** [comment]
No, this is just a CI problem. So yes, this issue should disappear if the types are compared semantically. I'll close when this happens.

**Comment by ebresafegaga** [comment]
I have a local copy with a fix for this issue

**Comment by robinbb** [comment]
This issue is in the In Review/QA column, but there is no indication of what must be done next to make it "closed".

**Comment by Firobe** [comment]
As indicated by @psteckler in https://github.com/MinaProtocol/mina/pull/11478, the issue should be automatically solved by an upcoming linter update. So I'm closing it for now, will reopen if this update does not happen in the near future.
