### ISSUE TITLE
Replace existing integration test cluster node pools with fewer pool containing larger node sizes

### ISSUE THREAD

**Issue by stevenplatt** [MinaProtocol/mina#11485]
Today, the current integration test cluster has a portion of tests that result in error because they are launched into a node pool that is already near capacity. Consolidating the existing node pool into fewer pools will reduce the opportunity for this to happen.

**Comment by stevenplatt** [comment]
Adding a link to Google Cloud node sizing: https://cloud.google.com/compute/docs/general-purpose-machines#n2_machines

**Comment by stevenplatt** [comment]
Moving this item to @matheus-o1labs - as he is already working on items relating to updating integration cluster node pools.

**Comment by matheus-o1labs** [comment]
Change implemented in PROD.
