### ISSUE TITLE
Use Base64 for transaction ids

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#11505]
Linear, unlike Base58Check

**Comment by deepthiskumar** [comment]
### Transaction ID


The ID of a transaction is a base58Check encoding of itself.  With zkapps, the transactions are bigger and using base58Check is impacting the client performance. Hence, proposing to change it from [Base58Check](https://en.bitcoin.it/wiki/Base58Check_encoding) to Base64. 
If this change is introduced, it will change the IDs of all the existing transactions. 
There are no changes to existing transaction types itself (Payments, Delegations, Fee transfers, and Coinbase) and only the encoding/decoding for the ID changes.

To migrate to the new format, we will provide a mapping between the existing transaction ID and the new one for all the transactions (obtained from an archive database). Alternatively (or in addition) we can add a cli/graphql command that does the conversion from existing ID to the new one and vice versa.

This change does not impact signatures or block hash.

Currently on mainnet, transaction IDs are used in the following commands 

I. Transactions in the following GraphQL queries  have `id` field that show the transaction ID in base58 format.
`block`
`bestChain`
`pooledUserCommands`

II. Transaction ID passed as an argument in `transactionStatus` graphQL query

III. Transaction ID in the response of `sendPayment`, `sendDelegation`, and `sendRosettaTransaction` graphQL mutation

IV. Output of cli command `send-payment`, `send-delegation`, `pooled-user-commands`, `send-rosetta-transactions`

V. Input for cli commands  `cancel-transaction`, `compute-receipt-chain-hash`, `hash-transaction`


### Transaction hash

Transaction hash, as displayed in cli and graphQL commands, is currently computed by hashing transaction ID (which is a Base58Check encoding of a transaction). The new transaction hash for Payments, Delegations, Fee transfers, and Coinbase transactions will be now be the  hash of the `Bin_prot` serialization of a transaction. 

This changes the hash of transactions of existing transactions. Signatures or block hashes will not change.

Similar to transaction IDs, we will provide a mapping from old transaction hash to the new one for all existing transactions. On the cli, the existing command  `hash-transaction` will be modified to take a transaction ID in the new format and produce a hash (as listed in the above section).

Transactions hashes are also used in all the commands listed above. 
Transaction hashes are stored in the archive database as well. We'd provide migration scripts for the archive database
The column is `hash` in tables `user_commands` and  `internal_commands

**Comment by robinbb** [comment]
Great to see this improvement merged! Are archive database migration scripts also a part of this work? Are they merged, too?

**Comment by psteckler** [comment]
@robinbb The database migration work has not yet started.

**Comment by robinbb** [comment]
@psteckler Okay. There may be a way to avoid some of the migration work. I have a team that can help. Please contact me when planning this work, if the work quantity is large, if you want to offload some of it.

**Comment by psteckler** [comment]
@robinbb What did you have in mind? My thought was to use a modified version of the replayer app to populate a db with the new schema.

**Comment by robinbb** [comment]
Ah, ha! I was thinking same. Did you have plans on working on this any time soon?

**Comment by psteckler** [comment]
Probably not for 3 weeks, at least.

**Comment by psteckler** [comment]
The app should be able to start at a given block or height, so the migration can be done incrementally.

**Comment by deepthiskumar** [comment]
@robinbb thanks for checking. I've created #12331 to track this as part of all the migration related work. I'll reach out to you when we plan to prioritize that work
