### ISSUE TITLE
Change node and auto scaling rules

### ISSUE THREAD

**Issue by matheus-o1labs** [MinaProtocol/mina#11506]

**Comment by joseandro** [comment]
@matheus-o1labs please add an estimate to this task

**Comment by matheus-o1labs** [comment]
New node pool specs for the CI integration cluster:

Autoscaling: minimum 1 node per zone, and maximum 3 nodes per zone
Machine model: n1-standard-64 

Next steps:
* Change planning to non-working hours (dawn, weekends)

**Comment by matheus-o1labs** [comment]
Change implemented in PROD.
