### ISSUE TITLE
Add fuzzy test to CI

### ISSUE THREAD

**Issue by matheus-o1labs** [MinaProtocol/mina#11565]

**Comment by matheus-o1labs** [comment]
The proposal is to create a new FuzzyZkappTest.dhall file with different settings:
* Overwrite Timeout variable to a longer period
* Parametrize how many times it will run
* Check if environmental variable	NIGHTLY=true  is set and decide to run if True
* Disable the DirtyWhen method
After this changes, we will create a new scheduled job using the develop Branch, instead of the existing compatible Branch.

**Comment by matheus-o1labs** [comment]
https://github.com/MinaProtocol/mina/pull/11613/files

**Comment by matheus-o1labs** [comment]
PR adding the environmental variable NIGHTLY control statement.

https://github.com/MinaProtocol/mina/pull/11675

**Comment by amc-ie** [comment]
HI @matheus-o1labs , I think is done (thank you!), can we can close it?

**Comment by matheus-o1labs** [comment]
Pipeline created, issue closed.
