### ISSUE TITLE
Mina Signer: Add zkApps suggested min fee 

### ISSUE THREAD

**Issue by jasongitmail** [MinaProtocol/mina#11566]

**Comment by MartinMinkov** [comment]
Payments on main net currently have a minimum fee of `0.001`. Parties transactions should have at least `0.001*numOfParties` to make the two transaction models on par with each other. There is also the consideration that a higher fee will get into blocks sooner and not be removed from the pool. When sorting out which zkApp transactions to pick from the mem pool, it's done on a fee per party basis. This means that if we had one zkApp transaction that had 5 parties and a 5 mina fee (1 mina per party), and another normal transaction that had a 2 mina fee, the protocol would prefer the normal transaction in this case. 

The current API to sign a zkApp with the MinaSigner is as follows:
```ts
client.signTransaction(
  {
    parties: otherParties,
    feePayer: {
      feePayer: keypair.publicKey,
      fee: "1",
      nonce: "0",
      memo: "test memo",
    },
  },
  privateKey
);
```

To pick a min fee for zkApps, the following approach comes to mind.

To include a suggested min fee, we can make the `feePayer.fee` property optional. If the fee is not passed in from the user, we can default to using `0.001*numOfParties`. Going further, we can abstract this out into a function that has a parameter for the fee per party to be specified. We could additionally expose this helper function on the MinaSigner interface to make its usage a bit more explicit.

**Comment by ymekuria** [comment]
> If the fee is not passed in from the user, we can default to using `0.001*numOfParties`. Going further, we can abstract this out into a function that has a parameter for the fee per party to be specified. We could additionally expose this helper function on the MinaSigner interface to make its usage a bit more explicit.

I think this approach will work well. I like it @MartinMinkov !

**Comment by jasongitmail** [comment]
Looks great! 

> // This can be left optional but use the fee from above

... or more.

**Comment by mitschabaude** [comment]
Looks mostly good to me! +1 for exposing `getPartyFee`.
I'm not sure I like the idea of defaulting to `0.001*numOfParties`. To me it feels like, when spending user's money, "explicit is better than implicit". So even if we know that a transaction with a fee < `0.001*numOfParties` won't succeed, I would prefer to throw an error in this case instead of silently filling in the value. Just to avoid any surprises for people who might not think about the fee when using mina-signer, or assume the default is 0.

**Comment by MartinMinkov** [comment]
After thinking about it for a bit, I agree with that take! Defaulting to being explicit over implicit in these situations is definitely the way to go IMO, thanks for the feedback!
