### ISSUE TITLE
`as_prover` not executing code

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#11626]
Within a checked computation, add this to code, nothing from the `as_prover` thunk is printed, but the following printf statement is printed, suggesting the thunk is not run:
```
Snark_params.Tick.Run.as_prover (fun () -> printf "HI\n%!"; failwith "HELLO?");
printf "PAST AS PROVER\n%!";
...
```

**Comment by mrmr1993** [comment]
Confirmed that this works correctly in prover mode. Closing.
