### ISSUE TITLE
Filter 0-balance accounts from staking ledgers

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#11689]
Almost 3/4 of accounts have zero balance, and these don't contribute to the stake seen by block producers. Filtering these would save a lot of space.

**Comment by psteckler** [comment]
That changes the ledger hash, so maybe not a good idea.

**Comment by psteckler** [comment]
But also: https://github.com/MinaProtocol/mina/issues/9393

**Comment by deepthiskumar** [comment]
Impact: Reduces disk usage
