### ISSUE TITLE
generation of token accounts

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#11681]
The generation of token accounts in parties_generators.ml would be implemented like normal parties. There would be `1~max_other_parties` of parties that creates new token parties. The creation of token parties would be implemented as a pair of parties. The first one would just be a normal parties that pay the creation fee and the second would create a new account with the token_id being the derived token_id of first account.

**Comment by deepthiskumar** [comment]
duplicate of #11102
