### ISSUE TITLE
Running the `Snark-Worker` causes specific HW setup to reboot

### ISSUE THREAD

**Issue by shimkiv** [MinaProtocol/mina#11703]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Initial discussion started [in Discord](https://discord.com/channels/484437221055922177/754653322845356103/1007713235002216449). 
Author claim that running the `Snark-Worker` of [Berkeley QA Release 330d801](https://github.com/MinaProtocol/mina/discussions/11654) version on [MiniPC like this](https://www.amazon.com/Beelink-Windows-Computer-Display-2-5Gbps/dp/B09SYR619R) (`Debian Bullseye`) causes that hardware to faults at some point and reboot the system. 

Unfortunately no meaningful Daemon logs nor system logs are available to debug the issue at this point.
Lots of people tried to reproduce the issue, even using another MiniPC with similar configuration and not that good cooling system. But with no luck so far.

Author also claims that issue happens for them all the time on that specific HW configuration with that specific `Berkeley QANet` Daemon version, but at the same time no issues were spotted doing the same using the `mainnet` Daemon version (and network, of course).

Chances are that it might be caused by HW issues.

### Steps to Reproduce

Run Daemon with `Snark-Worker` enabled:
```
MINA_PRIVKEY_PASS="<password>" mina daemon \
  --block-producer-key <path_to_pkey> \
  --peer-list-url https://storage.googleapis.com/seed-lists/berkeley_seeds.txt \
  --max-connections 100 \
  --run-snark-worker <pub_key> \
  --snark-worker-fee 1000000 \
  --work-selection seq \
  --log-level Trace \
  --file-log-level Trace | systemd-cat &
```
Or run the:
```
mina transaction-snark-profiler --k 10
```

### Expected Result

Operation without reboot if not the HW issue.

### Actual Result

Snark-Worker causes specific HW setup to reboot. Might be cause by HW issues.

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

High

### Status

```shell
Not applicable for this specific issue.
```

**Comment by jrwashburn** [comment]
To clarify somewhat: 
1. The hardware also runs berkeley daemon without issue; only running with snark worker active, or the transaction-snark-profiler --k 10, causes the the fault. The hardware runs snarks fine on mainnet.
2. The hardware does not reboot; it powers off.

I'll be testing on an identical machine today and will post results later.

**Comment by jrwashburn** [comment]
Works ok (I now get an error with mina transaction-snark-profiler --k 10, but it does not kill the machine.)

This issue can be closed - it was hardware as suspected.

~$ mina transaction-snark-profiler --k 10
Transaction_snark.system: 15.94s
Uncaught exception:
  
  (monitor.ml.Error "Ledger.apply_transaction: insufficient funds"
   ("Raised at Base__Error.raise in file \"src/error.ml\" (inlined), line 8, characters 14-30"
    "Called from Base__Or_error.ok_exn in file \"src/or_error.ml\", line 84, characters 17-32"
    "Called from Init__Transaction_snark_profiler.profile_user_command.(fun) in file \"src/app/cli/src/init/transaction_snark_profiler.ml\", line 193, characters 10-157"
    "Called from Async_kernel__Deferred_list.foldi.(fun).loop in file \"src/deferred_list.ml\", line 10, characters 19-26"
    "Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5"
    "Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 169, characters 6-47"
    "Caught by monitor block_on_async"))

Raised at Base__Result.ok_exn in file "src/result.ml" (inlined), line 201, characters 17-26
Called from Async_unix__Thread_safe.block_on_async_exn in file "src/thread_safe.ml", line 132, characters 29-63
Called from Async_unix__Thread_safe.block_on_async_exn in file "src/thread_safe.ml" (inlined), line 181, characters 27-54
Called from Init__Transaction_snark_profiler.run.go in file "src/app/cli/src/init/transaction_snark_profiler.ml", line 440, characters 10-130
Called from Test_util.Make.with_randomness in file "src/lib/test_util/test_util.ml", line 54, characters 14-18
Re-raised at Test_util.Make.with_randomness in file "src/lib/test_util/test_util.ml", line 56, characters 40-47
Called from Core_kernel__Command.For_unix.run.(fun) in file "src/command.ml", line 2453, characters 8-238
Called from Base__Exn.handle_uncaught_aux in file "src/exn.ml", line 111, characters 6-10

**Comment by shimkiv** [comment]
Thank you @jackpaparian. That issue was resolved in `develop`
