### ISSUE TITLE
Remove daemon side lru caching for gossip messages

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#11704]
There are a few places in the daemon code where we are using an LRU cache to avoid reprocessing recently seen gossip messages. This is unnecessary, however, as the libp2p networking layer already contains a better caching layer that prevents reprocessing of gossip messages. We should just rip out the code on the daemon side that is recreating this logic as it is never really used (other than writing entries to the cache).

**Comment by svv232** [comment]
this pr has been merged
