### ISSUE TITLE
Update alert thresholds for mainnet and devnet

### ISSUE THREAD

**Issue by amc-mina** [MinaProtocol/mina#11719]

**Comment by amc-ie** [comment]
The `CriticallyLowMinWindowDensity` alert threshold needs to be changed on mainnet, at present it is not the correct value and is causing a lot of alerts to be triggered. 

We also need to split this out as an additional alert for devnet so we can leave the threshold for that "as is".

See [here](https://o1-labs.slack.com/archives/C01SJSXSM7H/p1661452516547129) for additional information.
