### ISSUE TITLE
Revisit tests from #11328

### ISSUE THREAD

**Issue by kantp** [MinaProtocol/mina#11740]
In #11328, we identified some tests that fail, when run locally. Apparently, at least some of those tests are run regularly during CI.

We should have a closer look and determine
- [ ] which tests are run in CI
- [ ] whether those tests are designed to only be run in CI, not locally.
- [ ] which, if any, tests are really broken and should be fixed or deleted.

**Comment by joaosreis** [comment]
Closed. Follow-up work tracked by #13198 and #13216
