### ISSUE TITLE
Unix.Unix_error

### ISSUE THREAD

**Issue by MinusGod** [MinaProtocol/mina#11777]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Summary

{"OS_type":"Unix","Release":"5.4.0-99-generic","Machine":"x86_64","Sys_name":"Linux","Exception":{"commit_id":"9b0369c27bb85c8ab2f8725c6e977eb27b53b826","sexp":["monitor.ml.Error",["src/bigstring.ml.IOError","0",["_[coda_crash_report_2022-09-07_06-50-40.278715.tar.gz](https://github.com/MinaProtocol/mina/files/9503506/coda_crash_report_2022-09-07_06-50-40.278715.tar.gz)_","Is a directory","read",""]],["Raised by primitive operation at Core__Bigstring.read in file \"src/bigstring.ml\", line 40, characters 2-40","Called from Async_unix__Reader0.Internal.get_data.(fun) in file \"src/reader0.ml\", line 300, characters 22-61","Called from Async_unix__Syscall.syscall.loop in file \"src/syscall.ml\", line 19, characters 12-16","Re-raised at Async_unix__Reader0.Internal.get_data.(fun) in file \"src/reader0.ml\", line 308, characters 34-39","Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5","Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 168, characters 6-47","Caught by monitor coda"]],"backtrace":["Raised by primitive operation at Core__Bigstring.read in file \"src/bigstring.ml\", line 40, characters 2-40","Called from Async_unix__Reader0.Internal.get_data.(fun) in file \"src/reader0.ml\", line 300, characters 22-61","Called from Async_unix__Syscall.syscall.loop in file \"src/syscall.ml\", line 19, characters 12-16","Re-raised at Async_unix__Reader0.Internal.get_data.(fun) in file \"src/reader0.ml\", line 308, characters 34-39","Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5","Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 168, characters 6-47"]},"Command":"Command: (/usr/local/bin/mina daemon --peer-list-url\n https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt --log-level\n Info --file-log-level Debug --block-producer-key /root/keys)","Coda_branch":"master","Coda_commit":"9b0369c27bb85c8ab2f8725c6e977eb27b53b826"}
[coda_crash_report_2022-09-07_06-50-40.278715.tar.gz](https://github.com/MinaProtocol/mina/files/9503516/coda_crash_report_2022-09-07_06-50-40.278715.tar.gz)

### Steps to Resolve this Issue

1.
2.
3.
...

**Comment by shimkiv** [comment]
@MinusGod so it seems to be related to file system access. Can you share any specifics of Daemon launch?

```
                "src/bigstring.ml.IOError",
                "0",
                [
                    "Unix.Unix_error",
                    "Is a directory",
                    "read",
                    ""
                ]
```

**Comment by MinusGod** [comment]
because of privateKey  is a directory, not a file
