### ISSUE TITLE
Add gossip types to `mina_wire_types`

### ISSUE THREAD

**Issue by Firobe** [MinaProtocol/mina#11771]
Continuation of https://github.com/MinaProtocol/mina/issues/11101 for gossip types, as mentioned in the initial issue:
- `Network_pool.Transaction_pool.Diff_versioned.Stable.V2.t`
- `Network_pool.Snark_pool.Diff_versioned.Stable.V2.t`
- `Mina_block.External_transition.Raw.Stable.V2.t`

Potentially also RPC types

**Comment by robinbb** [comment]
@ylecornec I'm glad to see that this issue is in-progress. Do you have an ETA or an estimate of size?

**Comment by ylecornec** [comment]
completed by #11836
