### ISSUE TITLE
Implement skip list for version compatibility lint step

### ISSUE THREAD

**Issue by kantp** [MinaProtocol/mina#11780]
The `version compatibility changes` check currently fails on some files in the codebase. This had not been detected, as the check is only performed on files that are changed in a given PR, and has never been done on the whole codebase. This can create a blocker for PRs which do modify one of the files which do not pass the linting step (see #11558 for a PR that did trigger this issue, and #11629 for a minimal example).

The clean way of resolving this would be to run the linter on the whole codebase, and make all files comply with the linter. This is a lot of effort, however. An alternative would be to accept that the codebase does not pass the linter, and disable the CI check. But the linter does have value, in ensuring that we do not introduce new files that fail the check.

Thus, we want to implement a skip list for this test, that contains files that are known to never having passed the `version compatibility changes` check. Those files shall be skipped in the check. Furthermore, when the check fails on a file that is not yet in the skip list, the error message should contain a link to this issue, and instructions on how to add a file to the skip list. That will ensure that future PR that trigger this issue will only be minimally interrupted.

The task of making the files compliant with the linter will thus be decoupled from the PRs that modify one of those files.

**Comment by psteckler** [comment]
There is a plan to update the version linter that will minimize CI noise, the current system is going away. Currently, that's block on #11743.

I should mention that a "skip list" is a particular kind of data structure, which is not at all what you intended: https://en.wikipedia.org/wiki/Skip_list

**Comment by mrmr1993** [comment]
This has been fixed as part of the work in https://github.com/MinaProtocol/mina/issues/11181. Closing.
