### ISSUE TITLE
Unable to run container after pulling image

### ISSUE THREAD

**Issue by NehaSunkum** [MinaProtocol/mina#11798]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

I was able to pull the latest image for the archival node but was unsuccessful in running the image. I believe the error might be caused because the start.sh file was unable to be found

### Steps to Reproduce

1. pull image for latest archival node from: https://hub.docker.com/r/minaprotocol/mina-archive/tags?page=1&name=latest. 
2. Then run this command: docker run -it --name mina-demo -e RUN_DEMO=true minaprotocol/mina-archive:latest  from https://github.com/MinaProtocol/mina/releases/tag/1.3.0 

### Expected Result

Expected to have the container running 

### Actual Result

Container did not run and the error below was produced:
![image](https://user-images.githubusercontent.com/8645790/189258115-9dd79d3a-7d8c-4442-9ea6-ae61d3eb3c61.png)

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
Error: Unable to connect to Mina daemon.
```

**Comment by shimkiv** [comment]
@NehaSunkum have you changed the `CODENAME` to be one of the values from listed above the example command?
> Every docker image is built for each of the supported platforms, replace CODENAME in the images below with your choice of bionic, focal, stretch, buster, or bullseye to select the base docker image.

**Comment by NehaSunkum** [comment]
Yes apologies, I specifically ran this command: docker run -it --name mina-demo -e RUN_DEMO=true minaprotocol/mina-archive:latest

**Comment by shimkiv** [comment]
@NehaSunkum thank you, we might have an issue with the [Demo script](https://github.com/MinaProtocol/mina/blob/3a2b64510459cc7afe479b8b53e10c99ec6805e4/dockerfiles/auxiliary_entrypoints/01-run-demo.sh) triggering. 
While in investigation, do you need the Sandbox Node for certain reasons?

**Comment by shimkiv** [comment]
@NehaSunkum mentioned PR https://github.com/MinaProtocol/mina/pull/11807 will fix the issue.
Meanwhile you can use the workaround command like this:

```
docker run -it --name mina-demo -e MINA_PRIVKEY_PASS="" -e RUN_DEMO=true minaprotocol/mina-daemon:1.3.0-9b0369c-bionic-devnet
```

The main difference is in additional envar parring to Docker container: `-e MINA_PRIVKEY_PASS=""`.

**Comment by garethtdavies** [comment]
Isn't this as running the archive container and not the daemon? User is running `minaprotocol/mina-archive:latest` The command provided should work, though, but the archive container is only a process that connects to a running daemon to archive blocks and isn't a node so that shouldn't be expected to work as you had originally run it.

**Comment by shimkiv** [comment]
Thanks @garethtdavies , yes you're right, I for some reason assumed that since we're talking about the `demo mode` then it must be Daemon.
> but the archive container is only a process that connects to a running daemon to archive blocks
It is another way around: daemons connect to archive service I believe.

Anyways I believe we can close it for now.
