### ISSUE TITLE
Incorrect block height in graphQL response 

### ISSUE THREAD

**Issue by NehaSunkum** [MinaProtocol/mina#11808]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Queries to get all transactions of a public key returned incorrect block height. 
Query: 
{
  transactions(
    sortBy: DATETIME_DESC
    query: {
      OR: [{
      to: "B62qpsikYYhTaAXw8XdgGhQtLsnecHF89LZdW2bGTa4aj4mePWPHxPe"
    }, {
      from: "B62qpsikYYhTaAXw8XdgGhQtLsnecHF89LZdW2bGTa4aj4mePWPHxPe"
    }]
      dateTime_lte: "2022-09-09T00:00:00Z"
    }
  ) {
    from
    to
    nonce
    dateTime
    amount
    hash
    blockHeight
    fee
  }
}
GraphQL response: 
![image](https://user-images.githubusercontent.com/8645790/189679552-250b8c75-5800-4bc4-9f7a-81a29fac1b06.png)

Explorer Response:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/8645790/189679423-cd2c0e1d-a083-4c9f-b208-921b5ef9c85e.png">

For transaction hash: CkpYrMyD6R5VsZHJbyjrr7YdyVmuLfMd5C27dJRF1uyebzFUED1H5 GraphQL response gives block height of 58158, while explorer return block height of 58160 

### Steps to Reproduce

1. Open: https://graphql.minaexplorer.com/
2. Run query above
3. compare the block height for transaction: CkpYrMyD6R5VsZHJbyjrr7YdyVmuLfMd5C27dJRF1uyebzFUED1H5 from https://minaexplorer.com/transaction/CkpYrMyD6R5VsZHJbyjrr7YdyVmuLfMd5C27dJRF1uyebzFUED1H5 with response from GraphQL
...

### Expected Result

GraphQL should respond with correct block height as displayed in explorer 

### Actual Result

GraphQL didn't respond with correct block height as displayed in explorer 

### How frequently do you see this issue?

Frequently

### What is the impact of this issue on your ability to run a node?

High

### Status

```shell
N/A
```

**Comment by garethtdavies** [comment]
This is from MinaExplorer GraphQL API so not applicable to the Mina daemon, but the issue is the MinaExplorer API, by default returns all blocks, whether canonical or not. So just add `canonical: true` to the query to get the expected response:

```
{
  transactions(sortBy: DATETIME_DESC, query: {canonical: true, OR: [{to: "B62qpsikYYhTaAXw8XdgGhQtLsnecHF89LZdW2bGTa4aj4mePWPHxPe"}, {from: "B62qpsikYYhTaAXw8XdgGhQtLsnecHF89LZdW2bGTa4aj4mePWPHxPe"}], dateTime_lte: "2022-09-09T00:00:00Z"}) {
    from
    canonical
    to
    nonce
    dateTime
    amount
    hash
    blockHeight
    fee
  }
}
```

**Comment by shimkiv** [comment]
Thank you @garethtdavies!
@NehaSunkum this issue can be closed then I believe?
