### ISSUE TITLE
graphql/cli command to convert back and forth between base58Check and base64 encoding of a transaction 

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#11819]

**Comment by psteckler** [comment]
May not need this, will poll users.

**Comment by psteckler** [comment]
Queried users in `#scripts-and-tools` on Discord.

**Comment by psteckler** [comment]
Gareth says he doesn't think the "payment ID" (which is a transaction ID) on Mina Explorer is much used. While transactions there are indexed by that id, they're also indexed by transaction hash.

**Comment by psteckler** [comment]
Closing for now.
