### ISSUE TITLE
Modify/add commands to hash a transaction passed in base58Check format in addition to the new base64 format

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#11821]

**Comment by deepthiskumar** [comment]
Also, provide a new cli command to produce hash using the base54Check serialization, bin_prot being the new one? This would help users in migration by being able to generate the hash of a transaction that was before the fork and that is after the fork

**Comment by psteckler** [comment]
The CLI commands to compute a receipt chain hash and cancel a transaction consume a transaction ID, those could also be updated to be version-agnostic

**Comment by psteckler** [comment]
We won't need to cancel transactions encoded with Base58Check, so `cancel-transaction` will only accept Base64 ids.

Past the hard fork, it's not likely that someone will want to compute a receipt chain hash for an old transaction, so `compute-receipt-chain-hash` will only accept Base64 ids.
