### ISSUE TITLE
Rosetta: change `/network/status` to point to genesis of hardfork

### ISSUE THREAD

**Issue by kantp** [MinaProtocol/mina#11849]

**Comment by Sventimir** [comment]
I have found and verified that in the response to the `/network/status` query in Rosetta API, the index of the genesis block is hard-coded in `src/app/rosetta/lib/network.ml:37`. However, under the `genesisi_block_identifier` key the API returns an object:
```
{
  "index": 1,
  "hash": "3NLx3eBDTvYmP27bUmYANzmhjL5rGe36nGW6N5XhGcuStF6Zv7ZD"
}
```
where `index` is hard-coded as described above, but the `hash` does not change along with it, so it seems to be hard-coded too. I'm investigating this further.

**Comment by Sventimir** [comment]
I verified that GraphQL returns genesis block's height depending on the fork configuration compiled into the binary. Hence, once the fork is configured, GraphQL will automatically return correct genesis_block_height. Therefore merging #11941 is sufficient to close this issue.
