### ISSUE TITLE
Re-create mina-signer inside snarkyjs, in pure JS, Part 1

### ISSUE THREAD

**Issue by mitschabaude** [MinaProtocol/mina#11855]
Impact: This will push the size of mina-signer below 4MB, which currently blocks Auro from supporting zkApps in their Firefox wallet

EDIT: updated title/description to reflect wider scope. this now refers to an MVP of signZkappCommand, without having the Poseidon constants compiled from Rust & without auto-generated tests for it.

**Comment by bkase** [comment]
How hard is this? The other thing in the pipeline for a while is transitioning the signer to depend on wasm from a rust implementation. Maybe we could still do this in the short term though

**Comment by mitschabaude** [comment]
I don't think this is much work, ~2 days, it's just porting what we do in snarkyjs already to mina-signer, plus a `fromJSON` method we don't have yet (but want anyway) in snarkyjs
