### ISSUE TITLE
Not filtering large transactions properly

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#11896]

**Comment by deepthiskumar** [comment]
Seeing `Rejecting block with at least one too-big transaction` on berkeley

**Comment by psteckler** [comment]
This is meant to keep too-big txns out of the txn pool: https://github.com/MinaProtocol/mina/blob/develop/src/lib/network_pool/transaction_pool.ml#L1015

**Comment by nholland94** [comment]
This was determined to be a version mismatch issue.
