### ISSUE TITLE
GraphQL: tokenOwner return wrong tokenId

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#11951]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

The query to find the token owner for custom token `y5DwEtVrPsSueEtVNoMuBvnRFU5wnst7WxXGara2Zca2LCCU8k` returns the wrong `tokenId`.

```
{
  tokenOwner(token: "y5DwEtVrPsSueEtVNoMuBvnRFU5wnst7WxXGara2Zca2LCCU8k") {
    tokenId
    publicKey
  }
}
```

returns:

```
{
  "data": {
    "tokenOwner": {
      "tokenId": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf",
      "publicKey": "B62qntBgBfjMHDFUJAqDzhKjRnsKE6QaP8a5JckarJtUcm6TxoSRRKR"
    }
  }
}
```

The  `tokenId` here should be `y5DwEtVrPsSueEtVNoMuBvnRFU5wnst7WxXGara2Zca2LCCU8k` as the default token is being returned.

### Steps to Reproduce

Create a token or check this existing one:

```
{
  tokenOwner(token: "y5DwEtVrPsSueEtVNoMuBvnRFU5wnst7WxXGara2Zca2LCCU8k") {
    tokenId
    publicKey
  }
}
```

### Expected Result

```
{
  "data": {
    "tokenOwner": {
      "tokenId": "y5DwEtVrPsSueEtVNoMuBvnRFU5wnst7WxXGara2Zca2LCCU8k",
      "publicKey": "B62qntBgBfjMHDFUJAqDzhKjRnsKE6QaP8a5JckarJtUcm6TxoSRRKR"
    }
  }
}
```

### Actual Result

Returns the default `tokenId`

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

High

### Status

```shell
Latest Berkeley `32a91613c388a71f875581ad72276e762242f802`
```

**Comment by garethtdavies** [comment]
Related to #11948

**Comment by garethtdavies** [comment]
Also the `isTokenOwner` of `tokenAccounts` doesn't seem to work. Given the above result `B62qntBgBfjMHDFUJAqDzhKjRnsKE6QaP8a5JckarJtUcm6TxoSRRKR` is the tokenOwner yet the following query returns false (eventually).

```
{
  tokenAccounts(tokenId: "y5DwEtVrPsSueEtVNoMuBvnRFU5wnst7WxXGara2Zca2LCCU8k") {
    balance {
      total
    }
    publicKey
    token
    tokenSymbol
    isTokenOwner
  }
}
```

Returns:

```
{
  "data": {
    "tokenAccounts": [
      {
        "balance": {
          "total": "5"
        },
        "publicKey": "B62qm6gwVzhkpjMcVrRBSMfUrsKpvX5autGXjGcQtkUFepKXwkNhnL9",
        "token": "y5DwEtVrPsSueEtVNoMuBvnRFU5wnst7WxXGara2Zca2LCCU8k",
        "tokenSymbol": "",
        "isTokenOwner": false
      },
      {
        "balance": {
          "total": "5"
        },
        "publicKey": "B62qo9YTrH71YaSaUhXqXuHHDz7mpFv7WvV89AhgUzTzsJz5uKrsjEY",
        "token": "y5DwEtVrPsSueEtVNoMuBvnRFU5wnst7WxXGara2Zca2LCCU8k",
        "tokenSymbol": "",
        "isTokenOwner": false
      },
      {
        "balance": {
          "total": "43"
        },
        "publicKey": "B62qntBgBfjMHDFUJAqDzhKjRnsKE6QaP8a5JckarJtUcm6TxoSRRKR",
        "token": "y5DwEtVrPsSueEtVNoMuBvnRFU5wnst7WxXGara2Zca2LCCU8k",
        "tokenSymbol": "",
        "isTokenOwner": false
      }
    ]
  }
}
```

**Comment by psteckler** [comment]
In the `berkeley` ledger, I see two accounts with the same public key, one with the default token, the other with the custom token mentioned above. I'll see if I can track down the source of the error.

**Comment by psteckler** [comment]
I think there's no bug for the first issue here. A new token id is derived from an owner, which is an account id consisting of a public key and existing token id. Only one token id can be immediately derived from that account id.

In OCaml:
```
let token_id =
    Token_id.of_string "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf"
in
let pk =
   Signature_lib.Public_key.Compressed.of_base58_check_exn
       "B62qntBgBfjMHDFUJAqDzhKjRnsKE6QaP8a5JckarJtUcm6TxoSRRKR"  in
let owner = Mina_base.Account_id.create pk token_id in
 Format.eprintf "NEW TOKEN: %s@."
    (Token_id.to_string @@ Account_id.derive_token_id ~owner)
```
I see `y5DwEtVrPsSueEtVNoMuBvnRFU5wnst7WxXGara2Zca2LCCU8k`. So I think the GraphQL is returning the correct result.

**Comment by psteckler** [comment]
For the second issue regarding `tokenAccounts`, the token owner is the public key `B62qntBgBfjMHDFUJAqDzhKjRnsKE6QaP8a5JckarJtUcm6TxoSRRKR` paired with the default token. So, none of the accounts denominated in that token is the token owner.

**Comment by psteckler** [comment]
@garethtdavies Do you buy my explanation?

**Comment by garethtdavies** [comment]
Ah OK, I get it after reading that a few times! Thanks. So the new token is a combination of the public key and token id. Agreed, given that context, this isn't a bug.

I tested the behavior of `isTokenOwner` by returning all default token accounts:

```
query MyQuery {
  tokenAccounts(tokenId: "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf") {
    isTokenOwner
    token
    publicKey
    tokenSymbol
  }
}
```

That returns the following (eventually), so not sure under what conditions `isTokenOwner` would return true. Also makes me wonder if it is possible to create a token where the default token is not the one paired - I don't think this is supported by SnarkyJS at least.

<img width="571" alt="CleanShot 2022-10-03 at 15 54 26@2x" src="https://user-images.githubusercontent.com/135382/193692898-156cb0d3-cf1f-48a3-8412-9ad9aabde1cd.png">

**Comment by psteckler** [comment]
I believe that `isTokenOwner` will never be true, because in any account, the unique token id derivable from the account's public key and existing token id will never be the same as that existing token id.

It should be possible to create a new token from any existing account id. The tests in this file: 

  https://github.com/MinaProtocol/mina/blob/develop/src/lib/transaction_snark/test/zkapp_tokens/zkapp_tokens.ml

contain a use of a custom token derived from another custom token. I haven't really used SnarkyJS, so I'm not sure what restrictions it might impose.
