### ISSUE TITLE
GraphQL: Getting token accounts in Berkeley is incredibly slow

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#11950]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

I created token accounts on the Berkeley testnet with tokenId `y5DwEtVrPsSueEtVNoMuBvnRFU5wnst7WxXGara2Zca2LCCU8k`. I then wanted to use GraphQL to get the balances of all the token accounts. However, the GraphQL response takes literally minutes to return:

```
query {
  tokenAccounts(tokenId: "y5DwEtVrPsSueEtVNoMuBvnRFU5wnst7WxXGara2Zca2LCCU8k") {
    balance {
      total
    },
    publicKey
  }
}
```

This is repeatable on any Berkeley node. 

### Steps to Reproduce

Run this query and wait...

```
query {
  tokenAccounts(tokenId: "y5DwEtVrPsSueEtVNoMuBvnRFU5wnst7WxXGara2Zca2LCCU8k") {
    balance {
      total
    },
    publicKey
  }
}
```

### Expected Result

Returned in a short period of time.

### Actual Result

While it does return the correct accounts with tokens, it takes minutes to return.

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
Current version of Berkeley `32a91613c388a71f875581ad72276e762242f802`
```

**Comment by psteckler** [comment]
The command is generating a list of all accounts, then filtering them by token. I think that can be sped up by filtering on the token in account ids before doing the account lookup.

**Comment by psteckler** [comment]
With that change, the particular lookup described here takes less than a second.
