### ISSUE TITLE
The rest api no response

### ISSUE THREAD

**Issue by leezijie** [MinaProtocol/mina#11987]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

I started the node correctly using docker (minaprotocol/mina-rosetta:1.3.1.1-f361ba1-focal), and it kept synchronizing block data.
But when I request the api for port 3087, I get nothing back.

curl --location --request POST 'http://127.0.0.1:3087/network/status' --header 'Content-Type: application/json' --data '{"network_identifier": {"blockchain": "mina","network": "mainnet"}}'

However, when I restart the node, it will return to normal, but after a while it will not work again.

This is so weird. Who can help me

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

Correct return data

### Actual Result

no response

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

High

### Status

```shell
Mina daemon status
-----------------------------------

Global number of accounts:                     124323
Block height:                                  187574
Max observed block height:                     187574
Max observed unvalidated block height:         187574
Local uptime:                                  20h46m33s
Ledger Merkle root:                            jwBd3CkAtdvQ5C9d8XXsehQbJ6jQiNP6rviQQpVaAXbTNy4gzig
Protocol state hash:                           3NLtCzNWjnjbhpFjhg8gn28BGrqAhaVuWR5SC4j2fBzArChFxarG
Chain id:                                      5f704cc0c82e0ed70e873f0893d7e06f148524e3f0bdae2afb02e7819a0c24d1
Git SHA-1:                                     f361ba19d78ba930b5b551f58d1a82942c0f724b
Configuration directory:                       /data/.mina-config
Peers:                                         39
User_commands sent:                            5
SNARK worker:                                  None
SNARK work fee:                                100000000
Sync status:                                   Synced
Catchup status:
	To build breadcrumb:           0
	To initial validate:           0
	Finished:                      543
	To download:                   0
	Waiting for parent to finish:  0
	To verify:                     0

Block producers running:                       0
Coinbase receiver:                             Block producer
Best tip consensus time:                       epoch=38, slot=5220
Best tip global slot (across all hard-forks):  276540
Consensus time now:                            epoch=38, slot=5221
Consensus mechanism:                           proof_of_stake
Consensus configuration:
	Delta:                     0
	k:                         290
	Slots per epoch:           7140
	Slot duration:             3m
	Epoch duration:            14d21h
	Chain start timestamp:     2021-03-17 00:00:00.000000Z
	Acceptable network delay:  3m

Addresses and ports:
	External IP:    52.194.8.37
	Bind IP:        0.0.0.0
	Libp2p PeerID:  12D3KooWQx4ihMKsUj7uRDBF1P2X7SnWhWDayLCcNnkjLxJ1b52q
	Libp2p port:    10101
	Client port:    8301
```

**Comment by shimkiv** [comment]
Hey @leezijie thanks for reporting this.
Please attach the logs.

**Comment by leezijie** [comment]
> Hey @leezijie thanks for reporting this. Please attach the logs.
Which logs do I need to provide? I observe that the logs are normal, but the rest request is not returned
```
root@d9e6a718642a:/data/.mina-config# ls
epoch_ledger.json                                 mina-prover.log           mina.log.1   mina.log.5    mina_net2
epoch_ledgerb16ce51b-43c7-3f9a-302e-1f7912c02a8d  mina-rejected-blocks.log  mina.log.10  mina.log.6    root
epoch_ledgere568556b-ba6b-3dd1-5334-797e0bcdbc63  mina-verifier.log         mina.log.11  mina.log.7    snark_pool
frontier                                          mina-vrf-evaluator.log    mina.log.2   mina.log.8    trust
genesis                                           mina.log                  mina.log.3   mina.log.9    wallets
mina-best-tip.log                                 mina.log.0                mina.log.4   mina.version
```

**Comment by shimkiv** [comment]
@leezijie also how much time usually passed when you start getting an empty response?

**Comment by shimkiv** [comment]
> @shimkiv  Which logs do I need to provide? I observe that the logs are normal, but the rest request is not returned
Can you please zip all of it and upload somewhere? 
Thank you.

**Comment by leezijie** [comment]
> @leezijie also how much time usually passes when you start getting an empty response (or nothing at all)? `UPD`: am running the same image for 3 hours now, Docker Engine consumes about 28Gb or RAM but network status request returns JSON.

@shimkiv Yes, I deployed several nodes. Everything else is normal. Originally, this node is also normal, I do not know why this situation suddenly appeared. This machine is very highly configured in relative terms. 8core32g

**Comment by leezijie** [comment]
> > @shimkiv  Which logs do I need to provide? I observe that the logs are normal, but the rest request is not returned
> 
> @leezijie Can you please zip all of it and upload somewhere? Thank you.

@shimkiv I don't have permission at present. I will upload it later

**Comment by shimkiv** [comment]
@leezijie I mean how much time usually passes between node reboot and nothing in response from Rosetta REST API calls?

**Comment by leezijie** [comment]
![image](https://user-images.githubusercontent.com/32590143/195836727-7434131a-b76b-4449-9f01-b53b1e5a155f.png)
@shimkiv 
I entered the inside of docker, you can see that each service started normally, but the request did not return any, will be stuck until the timeout disconnection

**Comment by shimkiv** [comment]
~5hrs of work and still works well so far.
By your screenshot it seems that `curl` still waits for response, maybe the system's performance dropped so that even simple requests are processed too slow?
What else do you do with the node after restart? Maybe I need to perform some specific activities?

**Comment by leezijie** [comment]
> 



> ~5hrs of work and still works well so far. By your screenshot it seems that `curl` still waits for response, maybe the system's performance dropped so that even simple requests are processed too slow? What else do you do with the node after restart? Maybe I need to perform some specific activities?
@shimkiv 
Just reboot for an hour and that's it. Nothing else. My other nodes are perfectly normal, which is weird.cpu and memory usage are not high

**Comment by shimkiv** [comment]
@leezijie still runs without issues on my end, I also did periodic restarts to emulate your case.
With this I'd consider the HW/VM issue.
Do you see any errors/suspicious events  in your `syslog`?

**Comment by leezijie** [comment]
> @leezijie still runs without issues on my end, I also did periodic restarts to emulate your case. With this I'd consider the HW/VM issue. Do you see any errors/suspicious events in your `syslog`?
@shimkiv 
I have now migrated to another machine, if this issue occurs in the future, I am turning on the issue.
Thank you for your help.
