### ISSUE TITLE
RPC heartbeat connection listens on all interfaces

### ISSUE THREAD

**Issue by jkrauska** [MinaProtocol/mina#1200]
Unknown TCP port listening. ( changes on restart, responds with 'RPC')

Upon starting coda daemon  with a client-port of 8301, external-port of 8302 and rest-port of 8304, I see these ports in listening, but also one other which is unexpected..  (8303 is assigned to coda-kademlia -- expected)

lsof check: (with inline comments to highlight)
```
jkrauska@joel-vm:~/src/coda-test$ lsof -Pan -p $(pidof coda)  -i
COMMAND   PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
coda    71478 jkrauska   23u  IPv4 255751      0t0  TCP *:8301 (LISTEN)
coda    71478 jkrauska   17u  IPv4 259171      0t0  TCP *:8302 (LISTEN)
coda    71478 jkrauska   21u  IPv4 255750      0t0  TCP 127.0.0.1:8304 (LISTEN)
# (continues below)

# Unexpected/Concerning:
coda    71478 jkrauska   13u  IPv4 258663      0t0  TCP *:46837 (LISTEN)

# And Also:
coda    71478 jkrauska   14u  IPv4 255745      0t0  TCP 127.0.0.1:36069->127.0.1.1:41945 (ESTABLISHED)
```

The last/established connection seems to be a socket to the /proc/71562/exe parallel-worker process.

The TCP listening port jumps around if you restart the daemon.

Connecting to it with netcat spits out 'RPC'.
```
$ nc 127.0.0.1 46837
�RPC
```

Note that it has a LOWER file descriptor, which may imply that it is opened before the other ports.

**Comment by cmr** [comment]
I discovered that rpc_parallel maintains a "heartbeat" connection that likely explains this port. When the connection is closed, the workers are supposed to die. Sometimes they are blocked on a long computation, though, and they'll die when it finishes.

**Comment by cmr** [comment]
We should convince rpc_parallel to only listen on localhost for this...

**Comment by cmr** [comment]
Now that we're already forking rpc_parallel, might as well hack this in imo.
