### ISSUE TITLE
Allow Mina Signer(Client SDK) to sign account updates

### ISSUE THREAD

**Issue by ymekuria** [MinaProtocol/mina#12014]
Currently Mina Signer only signs the feepayer part of transactions and not other account updates. This will allow wallets to be able to sign other account updates.

**Comment by maht0rz** [comment]
Could we also add .signFields as discussed here? https://github.com/aurowallet/auro-wallet-browser-extension/issues/16

**Comment by mitschabaude** [comment]
@maht0rz yes would be nice, but is a completely separate issue IMO
