### ISSUE TITLE
Stuck Block Height

### ISSUE THREAD

**Issue by mdlog** [MinaProtocol/mina#12051]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Summary

I am stuck in block 191635, block height does not increase more than 2 hours [https://github.com/mdlog/testnet-mdlog/blob/main/mina/coda_crash_report_2022-10-27_03-16-19.921181.tar.gz](url)

### Steps to Resolve this Issue

1.
2.
3.
...
[](url)

**Comment by nholland94** [comment]
The logs indicate that your port is already in use. Please make sure you do not already have another daemon running on the machine in question.

```
initializing helper error: failed to listen on any addresses: [listen tcp4 0.0.0.0:8302: bind: address already in use]
```
