### ISSUE TITLE
Pickles refactoring, phase 1

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#12055]
The phase 1 of 2 will refactor, or create, the following components:
1. Interfaces: #12056
2. Documentation: #12058
3. Warnings: #12057
4. Dead code elimination: #12059

You can find more about the plans to improve the Pickles codebase here: https://www.notion.so/minaprotocol/Pickles-code-evolution-roadmap-7b516db790cd4ab098fceadfc814134e#8110d404ab8a4ea08448fd659e367664

**Comment by joseandro** [comment]
@rbonichon can you add estimates to each of the issues found inside this epic?

**Comment by rbonichon** [comment]
#12059 and #10257 depends on PR #12120 , which in turn depends on #11897, which will close #12056

**Comment by rbonichon** [comment]
https://github.com/MinaProtocol/mina/pull/12120 has had a first round of review and should be cleared to go this week. This will end this epic.
