### ISSUE TITLE
broken links in release notes

### ISSUE THREAD

**Issue by mobileink** [MinaProtocol/mina#12070]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Summary

Broken link in notes on [releases page](https://github.com/MinaProtocol/mina/releases):

"Check out [our documentation](https://docs.minaprotocol.com/en/using-mina/connecting) for complete instructions"

=> page not found

### Steps to Resolve this Issue

fix the link

**Comment by mrmr1993** [comment]
Fixed in recent releases. Closing.
