### ISSUE TITLE
Document the Nix code and make it more maintainable

### ISSUE THREAD

**Issue by balsoft** [MinaProtocol/mina#12090]

**Comment by kantp** [comment]
@balsoft Is this already ini progress? I thought you mentioned you'd been working on this?

**Comment by kantp** [comment]
Also, this might be a duplicate of #10003?

**Comment by michal0mina** [comment]
Implemented and merged here: https://github.com/MinaProtocol/mina/pull/12287

**Comment by robinbb** [comment]
@michal0mina This issue is in the Done column, but still not closed. What is the correct status, in your opinion? Can we close this issue?

**Comment by michal0mina** [comment]
@robinbb yes, we can close.
