### ISSUE TITLE
Rosettta-cli tests against ZK Apps.

### ISSUE THREAD

**Issue by Sventimir** [MinaProtocol/mina#12184]
Once rosetta-cli test pass against usual coin transfers, we also need to run them against a blockchain containing newly added types of transactions related to ZK Apps. The plan here is againnto create a sandbox blockchain, deploy some ZK Apps on it and interact with them a bit. Then run rosetta-cli tests against these transactions as well.

**Comment by Sventimir** [comment]
Is I don't know how to develop ZK Apps yet, or what can or cannot be done with them, I need to learn a little bit first. At this point, I think, I have a working set up where I should be able to deploy a ZK App to a sandboxed blockchain. From this point I will experiment further to write something interesting to interact with.

**Comment by kantp** [comment]
This is being done as part of #12186

**Comment by kantp** [comment]
Closed via #12186
