### ISSUE TITLE
JSON encode/decode partial isomorphism for payment_proof fails 

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#1218]
See this error:

https://circleci.com/gh/CodaProtocol/coda/18771?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Perhaps try cranking up the number of trials in the quickcheck

**Comment by deepthiskumar** [comment]
Also this error:
https://circleci.com/gh/CodaProtocol/coda/23640?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Probably related to the new json library?

**Comment by cmr** [comment]
We haven't seen this in a long time.

**Comment by cmr** [comment]
... we should still try and repro though by cranking up the trials and letting it run for a while
