### ISSUE TITLE
Integrate npm into Nix environment

### ISSUE THREAD

**Issue by Sventimir** [MinaProtocol/mina#12218]
With the advent of zkapps it becomes useful to have the possibility of writing, compiling and testing them within our Nix environment. For this reason some additional software is required, specifically `npm` (Node.js Package Manager). Most importantly we want to be able to build `snarkyjs` bindings so that we can ensure we're using a version of `snarkyjs` compatible with our Mina daemon. Secondly, it'll also be useful to build zkapps, which additionally requires `npm`, `zkapp-cli`  and Typescript programming language.

Because it's a highly specialised set of packages (only required for zkapps) it might make sense to put them in a separate flake just like OCaml LSP. The required packages are at least:

* `npm`
* `typescript`
* `nodejs` (being dependency of `npm`).

It would also be nice to automatically install `zkapp-cli` package using `npm`:

* `$ npm install -g zkapp-cli`

(`-g` standing for "global" – not sure if it makes sense inside Nix).

Testing:
-----------
For this to be complete we need at least to be able to:

* sucessfully execute `scripts/build-snarkyjs-node.sh`
* go through zkapps tutorials in Mina documentation, esp. part 1 and 3 (development and deployment): https://docs.minaprotocol.com/zkapps/tutorials/hello-world

The same packages will also be required in Nix CI if we want to test zkapps there.

**Comment by Sventimir** [comment]
Note that `scripts/build-snarkyjs-node.sh` seems to be buggy at the moment. It tries to build `src/lib/snarky_js_bindings/snarkyjs/src/snarky/gen/js-layout.ts`, which is an undefined target. I have removed this line and was able to move on building the bindings, so maybe it's unnecessary/obsolete?

**Comment by kantp** [comment]
Deprioritized because it's no longer blocking Sventimir.
