### ISSUE TITLE
Postgres version is set to 9.6 on artefact minaprotocol/mina-rosetta:1.3.2beta2-release-2.0.0-32a9161-stretch

### ISSUE THREAD

**Issue by kantp** [MinaProtocol/mina#12232]

**Comment by kaozenn** [comment]
This is the default version of PostgreSQL available on Debian Stretch (Debian 9.0 was initially released on June 17th, 2017) 

All the distributions we support provide a different version of PostGreSQL

[Debian 11 (bullseye)](https://www.debian.org/releases/bullseye/) — current stable release: **PostgreSQL 13.8**
[Debian 10 (buster)](https://www.debian.org/releases/buster/) — current oldstable release: **PostgreSQL 11.18**
[Debian 9 (stretch)](https://www.debian.org/releases/stretch/) — oldoldstable release, under [LTS support]: **PostGreSQL 9.6.24**
[Ubuntu 20.04.5 LTS (Focal Fossa) ›](http://www.releases.ubuntu.com/focal/): **PostgreSQL 12.12**
[Ubuntu 18.04.6 LTS (Bionic Beaver) ›](http://www.releases.ubuntu.com/bionic/): **PostgreSQL 10.22**

What is the minimal version required by the archive node?
Do we still need to support legacy distribution?

**Comment by kaozenn** [comment]
I will align all the PostgreSQL version to the latest: **PostgreSQL 13.8** to close off this issue
