### ISSUE TITLE
Estimate the size for the zkOracles circuits

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#12247]
We need to estimate a size for the circuit given #12246 and #12245.
The outcome of this task should be an estimate for the number of constraints how many recursions are needed in Pickles to make it work (this is, if we can make it work by splitting the circuit containing the primitives and TLS transcript).

**Comment by xiangxiecrypto** [comment]
It is now ready to estimate.

**Comment by joseandro** [comment]
Closing this task as we have agreed on the approach to it.
