### ISSUE TITLE
Integration test to ensure txns with no failing account-updates add to pool, yes failing updates rejected

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#12256]
This should cover that any arbitrary failing txn / succeeding txn make it to the txn pool.

Specific failures can be covered by unit tests.

**Comment by deepthiskumar** [comment]
zkapp-timing, zkapp-nonce integrations tests send both failing and valid account updates that get included in blocks. src/lib/transaction_snark/test/ has a bunch of tests for specific field updates.
