### ISSUE TITLE
Test delegations with rosetta-cli

### ISSUE THREAD

**Issue by ylecornec** [MinaProtocol/mina#12277]
- [x] run tests locally
- [ ] add support for delegation transactions to rosetta-cli. See https://github.com/coinbase/rosetta-sdk-go/pull/457
- [x] add tests to the CI using the rosetta-go-sdk fork until changes are merged upstream. See #12373.
- [ ] Use new version of rosetta-cli after changes are merged upstream.

**Comment by robinbb** [comment]
@Sventimir this is an issue in review. Does that mean that you believe that #12373 is sufficient to close this issue? Do we really need to wait for upstream? What is the ETA on this task?

**Comment by Sventimir** [comment]
@robinbb There's also [PR ro rosetta-sdk-go](https://github.com/coinbase/rosetta-sdk-go/pull/464), which the PR you mentioned depends on. I think we don't have to wait for Coinbase to integrate our changes, though, as we can build `rosetta-cli` with updated SDK for our internal testing. Actually this is what #12373 does for the moment. So I think as soon as CI issues that block merging of #12373 are fixed, we can merge and close this issue. No need to wait for the upstream indeed.

**Comment by Sventimir** [comment]
I extracted the update our tests when our changes are accepted upstream to a separate issue: #12509.
