### ISSUE TITLE
Update to Halo2 pasta curves SRS generators

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#12322]
The update to the new pasta curve SRS generators enables compatibility with Halo2 once the customizable version of Pickles is shipped. Meaning that we will have all the tools needed to verify signatures created by other Halo2 proof-systems. 

We need it to be shipped in Berkley because it will be difficult to change it later, since we'll need to keep backwards compatibility with zkApps that are added to the version we ship in the HF.

This should take half a day to be implemented and shouldn't introduce any risks.

**Comment by carterbrett** [comment]
This was determined to be out of scope for Berkeley due to the complexities discovered with the change. It was believed originally we could largely "change a constant" to align our generators w/ Halo 2 Pasta generators, but the changes required are much more significant, would require audits, etc.

**Comment by joseandro** [comment]
I am closing this issue as we won't be working on it.
