### ISSUE TITLE
[mina-signer] - Hash incompatability with mainnet and devnet on current build

### ISSUE THREAD

**Issue by MartinMinkov** [MinaProtocol/mina#12328]
## Description

There are two methods that expose a transaction hash on a payment and stake delegation in the mina-signer -- `hashPayment` and `hashStakeDelegation`. It was reported that these hash methods generate a different hash value than what is returned by the node's GraphQL API when a transaction is broadcasted (for `mainnet` and `devnet`).

There are a couple of reasons for this

1. Mina-signer was built and published on the `develop` branch to be compatible with the Berkeley testnet. However, `mainnet` and `devnet` are running off the `compatible` branch and both these branches use a different mechanism to calculate hashes. `compatible` uses Base58Check serialization while `develop` uses `Bin_port` serialization.

2. mina-signer passes in a dummy signature when calculating the hash value. In `develop`, the hash always uses a dummy signature so that it can be calculated in the archive database data. In `compatible`, the GraphQL `sendPayment` endpoint uses the signature provided to calculate the hash.

Due to this discrepancy of calculating hash values, it seems we must have two different releases of mina-signer if we want to support proper hashes for all networks (at least until there is a hard fork, then all networks will be settled).

Posting this issue as a starting point for discussion moving forward

**Comment by mitschabaude** [comment]
this is actually closed with the new mina-signer release!
