### ISSUE TITLE
Add valid_until for account_update

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#12320]
To solve the invalid transactions creeps into the pool bug, we need a fix that adds a new fields to zkapp_precondition, which would be called `valid_until`. This would be predicate on the slot at which the transaction gets into a block.

Protocol change:
When we producing a block, we now needs to get the current block, and pass the current block to `Staged_ledger.create_diff` and `Staged_ledger.apply_diff` function. And when the account_update is actually applied the current slot would be used to compare against the valid_until field. If it falls in the range, then the check passes. If it doesn't, then the check fails.

Testing:
We could write a unit test or integration test that checks account_updates that fails this check would be rejected by the block_producer.

**Comment by nicc** [comment]
Already done.
