### ISSUE TITLE
Aggregate performance data for nix builds

### ISSUE THREAD

**Issue by michal0mina** [MinaProtocol/mina#12336]
Prepare nix timings in following conditions:
1. single builder
2. multiple builders (with current bug)
3. without caching benefits
4. with caching benefits

Compare with current CI

Definition of Done:
1. table in Nix notion page with all above numbers

**Comment by balsoft** [comment]
https://www.notion.so/minafoundation/Performance-Analysis-d669029d779c4a34801b27b99cb31905

**Comment by robinbb** [comment]
@Smorci I notice that this issue is in the Done column, but that it is not closed. Is there more to do, here?

**Comment by Smorci** [comment]
No, everything is done.
