### ISSUE TITLE
Archive DB migration- transaction hash post format change

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#12331]

**Comment by deepthiskumar** [comment]
Hashes for existing transactions will change because of the change in 
 the serialization format for transaction hash pre-image (refer https://github.com/MinaProtocol/mina/issues/11505)

**Comment by psteckler** [comment]
`hash_signed_command_v1` will change to use the `Bin_prot`-serialization of old commands, instead of using Base58

**Comment by psteckler** [comment]
#12649 uses the strategy to hash old transactions that we'll use when migrating hashes.
