### ISSUE TITLE
Mina client status incorrectly returns no slots won for epoch

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#12393]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Reported by Morello#0112 in Discord.

`mina client status` reports `None this epoch...`

![image](https://user-images.githubusercontent.com/135382/208316072-6742e88c-117e-446f-8be2-e83041a94cf6.png)

However, confirmed there are slots won using https://github.com/zkvalidator/mina-vrf-rs (5 for the epoch) and also looking in `mina-vrf-evaluator.log` confirms the slots as output by mina-vrf-rs tool were won.

```
{"timestamp":"2022-12-16 15:00:14.715704Z","level":"Info","source":{"module":"Vrf_evaluator","location":"File \"src/lib/vrf_evaluator/vrf_evaluator.ml\", line 201, characters 20-31"},"message":"Won slot xxxx in epoch 43","metadata":{"pid":17}}
```

### Steps to Reproduce

`mina client status` returns none this epoch

### Expected Result

Outputs the next slot won.

### Actual Result

None this epoch

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

High

### Status

```shell
Running Mainnet Stable Release 1.3.1.2 commit `25388a0fed9695e8e9d04f75f50c2bae1c9c80db`
```

### Additional information

Logs shared via email

**Comment by amc-ie** [comment]
@garethtdavies thanks for logging this apologies for the delay in getting back to you. Are you still seeing this behaviour consistently?
