### ISSUE TITLE
Test the off-by-1 error in pickles 

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#12422]
Add a test to cover the case of off-by-one error, where both uses of `max_n` should be `max_n+1`. The fix for this issue can be found [here](https://github.com/MinaProtocol/mina/pull/12416).

**Requirement:**
A test that generates a proof using domain size 16 for the step circuit, uses a side-loaded verification key in pickles to verify it.

It would probably be easiest to use the transaction snark to do this, since the logic is already set up apart from the step circuit size.

**Comment by o1-david** [comment]
the test is here, but I'm not able to trigger the error so far: https://github.com/MinaProtocol/mina/pull/12436/commits/f4e7d741039ed9198a598ec4e3d7354e0f8c36bf
