### ISSUE TITLE
Test the checks for domain size in Pickles Verify

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#12423]
**Summary:**
Add tests that validate domain size > 16 in Pickles. For example: `deferred_values.branch_data.domain_log2` <= `Nat.to_int Backend.Tick.Rounds.n` in src/lib/pickles/verify.ml. The fix for the issue found in Berkeley can be found here.

**Requirements:**
Tests that generate a proof with (claimed) domain size > 16, ensuring that it gets rejected by the Pickles.verify function. This test pattern should also be used to create correlated adversarial tests to cover for other possible similar validation errors.

The easiest/best way to do this is create a fake 'wrap' circuit that accepts any input you give it, then set the `domain_log2` value maliciously. If the circuit accepts any input, we can stuff in whatever malicious inputs we like and make sure everything behaves consistently. This test should give us enough coverage so that we can be more confident there are no other similar validation errors lurking around.

**Comment by o1-david** [comment]
I can't find that line in `verify.ml` and it seems like there's a missing link in the description of this issue.

> create a fake 'wrap' circuit that accepts any input you give it, then set the domain_log2 value maliciously

it'd be nice to get some pointers for that as well :o

**Comment by o1-david** [comment]
the PR that fixed the bug: https://github.com/MinaProtocol/mina/pull/12416
