### ISSUE TITLE
Berkeley: GraphQL get token symbol

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#12425]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

The behavior of getting a token symbol via GraphQL is confusing.

`"tokenSymbol"` is always empty except in a specific case of getting the owner account and default tokenId (or likely whatever the token account was derived from, by default `wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf`). 

Take the following example on current redeployment of Berkeley. There is a tokenId of `wSJmaBomjZT3JL7qtdDV3Hw15WGUSj1MEXq4wpwCD7tujd9fyZ` so we first need to find the `tokenOwner`:

```
query tokenOwner {
  tokenOwner(tokenId: "wSJmaBomjZT3JL7qtdDV3Hw15WGUSj1MEXq4wpwCD7tujd9fyZ")
  {
    publicKey
    tokenId
  }
}
```

Which returns:

```
{
  "data": {
    "tokenOwner": {
      "publicKey": "B62qj2f2rCVaUzwe3Dmzzw2fFNRcDqwZFXd9eANMRApvKh9vcc6bEza",
      "tokenId": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf"
    }
  }
}
```

You'd assume you could do something like this to get the tokenSymbol:

```
query tokenAccounts {
  tokenAccounts(tokenId: "wSJmaBomjZT3JL7qtdDV3Hw15WGUSj1MEXq4wpwCD7tujd9fyZ") {
    publicKey
    balance {
      total
    }
    tokenSymbol
    isTokenOwner
    token
  }
}
```

But that returns this:

```
{
  "data": {
    "tokenAccounts": [
      {
        "publicKey": "B62qj2f2rCVaUzwe3Dmzzw2fFNRcDqwZFXd9eANMRApvKh9vcc6bEza",
        "balance": {
          "total": "150"
        },
        "tokenSymbol": "",
        "isTokenOwner": false,
        "token": "wSJmaBomjZT3JL7qtdDV3Hw15WGUSj1MEXq4wpwCD7tujd9fyZ"
      }
    ]
  }
}
```

Note that here `tokenSymbol` is empty and `isTokenOwner` is false - this will always be false so not sure of the point of it.

So the only way to get the `tokenSymbol` is to get the accounts of the tokenOwner so:

```
query account {
  accounts(publicKey: "B62qj2f2rCVaUzwe3Dmzzw2fFNRcDqwZFXd9eANMRApvKh9vcc6bEza") {
    publicKey
    isTokenOwner
    token
    tokenSymbol
    balance {
      total
      blockHeight
    }
  }
}
```

And we can get it as it is tied to the default token, albeit this is very unintuitive.

```
{
  "data": {
    "accounts": [
      {
        "publicKey": "B62qj2f2rCVaUzwe3Dmzzw2fFNRcDqwZFXd9eANMRApvKh9vcc6bEza",
        "isTokenOwner": false,
        "token": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf",
        "tokenSymbol": "PUNK",
        "balance": {
          "total": "38300000000",
          "blockHeight": "229"
        }
      },
      {
        "publicKey": "B62qj2f2rCVaUzwe3Dmzzw2fFNRcDqwZFXd9eANMRApvKh9vcc6bEza",
        "isTokenOwner": false,
        "token": "wSJmaBomjZT3JL7qtdDV3Hw15WGUSj1MEXq4wpwCD7tujd9fyZ",
        "tokenSymbol": "",
        "balance": {
          "total": "150",
          "blockHeight": "229"
        }
      }
    ]
  }
}
```

### Steps to Reproduce

Use the queries above on https://proxy.berkeley.minaexplorer.com/graphql

### Expected Result

`tokenSymbol` should ideally be populated when requesting token information.
`isTokenOwner` should be removed or return `true` for a combination of publicKey and token.

### Actual Result

`tokenSymbol` is only accessible from the account combination of tokenOwner and defaultToken.

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Medium

### Status

```shell
Latest Berkeley
```

**Comment by garethtdavies** [comment]
Tested update locally and via https://berkeley.minaexplorer.com/transaction/CkpZP3dzbXfw1K656n1NdfhN8Cjk6WeChJZfoLX3chzJUWdQL8r1q

**Comment by psteckler** [comment]
The docs for `isTokenOwner` say it's about whether the account owns its token, which is never true. Accounts don't have a `token_owner` field (they did for a time, I believe). I propose removing the field in GraphQL (is that OK?).

The `tokenSymbol` field is the empty string, by default. It can be set to a meaningful value via a zkApp. It's the symbol for the (unique) token owned by the account, if that exists, not the token *of* the account. But it's not guaranteed to have been set. The doc string for GraphQL is wrong, and should be fixed.

**Comment by psteckler** [comment]
Created #12671.

It's a bit confusing that the token symbol appears only in the account of the token owner, and not in the accounts that are denominated in the token. That does mean that the symbol is in the ledger in exactly one place, which is good.

We might want to add a query like `getTokenSymbol`, so you don't have to know the token owner to find the symbol. The ledger maintains a table of token owners, so the daemon could lookup the owner, then lookup the account to find the symbol.
