### ISSUE TITLE
Sync Archiving node with Berkeley

### ISSUE THREAD

**Issue by michal0mina** [MinaProtocol/mina#12440]
Definition of Done:
* we have running archiving node synced with Berkeley
* we are able to have ad-hoc db dumps with the most recent data
* documentation how to run it locally, what are the problems, best way to run it lightly, docker?

**Comment by simisimis** [comment]
at the moment tried ways to spin archive node myself. 
1st. way that worked - used a docker image from [05c2f73](https://github.com/MinaProtocol/mina/discussions/12421) release.
Manual steps needed - install/create postgres instance. start mina daemon as well as archive. let them sync and then create database dump.
2nd. way - tried using rosetta-api image from the same release, but mina daemon would start with different chain-id and catchup/sync would fail.

to close this issue I'd_ say we need to solve 2 parts. 
1st have MF owned archive instance that would independently dump database backups into MF owned persistent cloud storage.
2nd - to have a similar image like the one for rosetta-api allowing users effortlessly spin up a container that would sync to the archives latest state together with documentation instructions how to use it.

for the 1st part I'd say our DevOps team first should prioritize on getting k8s up and running. As for the second, I would like to discuss with team what would be a better path to take. i.e. create yet another docker image that would bootstrap archive node, or try to reinvent less and reuse what we already have - rosetta-api docker image.
