### ISSUE TITLE
SPIKE: Breakdown of code areas to investigate in first batch

### ISSUE THREAD

**Issue by kantp** [MinaProtocol/mina#12442]
The objective of this spike is to get a good enough understanding of the code and tests in the new portion of the codebase to make a plan for how to break down the following investigation of how good our test coverage is.

We will need to look at the diff between `develop` and `compatible` to find the major new features (mostly, zkApps). We will want to create a list of new components, where they are in the codebase, and how large they are. With that, we can then create individual tickets to look at the test coverage of each of those.

**Comment by Sventimir** [comment]
One of the places where ZK App commands are processed is `src/lib/transaction_logic/zkapp_command.ml` module. This library does not have any test modules, byt `zkapp_command.ml` has some inline tests inside. Visually these tests are few and likely insufficient, although admittedly functions in this module seem to be quite basic, so it is possible that for some of them static type checking is enough. Overall though, I think we could try to expand the tests for this part of the code.

**Comment by Sventimir** [comment]
Module `src/lib/transaction_logic/zkapp_command_logic.ml` is completely without any tests and it seems to be a pretty significant part of the system. It contains a functor delivering a function to apply a zkapp command to any existing state (apparently). This  function is in addition very long (~800 lines of code) and could probably benefit from being split into smaller operations. Some comments explaining how it works would also be nice to have.

**Comment by Sventimir** [comment]
In addition to that, unfortunately `Zkapp_command_logic` and `Mina_transaction_logic`  throw a lot of exceptions, which is suspicious and makes things more difficult to verify. A refactoring aiming at improving the type safety of this code would only be in order.

**Comment by Sventimir** [comment]
I created issues to write tests for the modules mentioned above: #12530 and #12531. Therefore I close this one.
