### ISSUE TITLE
Create Buildkite CI Pipeline: "Javascript and SnarkyJS"

### ISSUE THREAD

**Issue by stevenplatt** [MinaProtocol/mina#12462]
This GH issue is to document the work of splitting the current monolith bulidkite pipelines into small pipelines. 

Splitting the monolith pipeline into smaller pipelines will allow engineers to manually trigger them for a specific, smaller batch of tests - rather than triggering tests only during pull requests.

**Comment by mrmr1993** [comment]
This is now the responsibility of the o1js CI. Closing.
