### ISSUE TITLE
Implement simple transaction generator for load testing

### ISSUE THREAD

**Issue by kantp** [MinaProtocol/mina#12515]
In order to test how the system operates under various degrees of load, we will want to have a component that sends a continuous stream of transactions to a cluster.

The first version of this can be very simple, and just send simple payment transactions from one account to the same account repeatedly, at a specified rate. We can later add more complez functionality, but for simple load testing, this should already be quite valuable.

**Comment by shimkiv** [comment]
Not for a load testing but good starting points are:
- https://github.com/MinaProtocol/mina/blob/4968f37b8cc3659445893794294b87dee3e03311/scripts/mina-local-network/mina-local-network.sh#L574
- https://github.com/MinaProtocol/mina/tree/4968f37b8cc3659445893794294b87dee3e03311/src/app/batch_txn_tool
- https://github.com/MinaProtocol/mina/tree/4968f37b8cc3659445893794294b87dee3e03311/src/app/zkapp_test_transaction
