### ISSUE TITLE
dangling parent reference in unit tests

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#12526]
Failure seen in https://github.com/MinaProtocol/mina/pull/12491

and when adding tests from test_zkapp_update.ml to account_timing tests in transaction snarrk

**Comment by mrmr1993** [comment]
Adding the test suggested [here](https://github.com/MinaProtocol/mina/pull/12492#discussion_r1081667400) also triggers the same bug. TODO: add this test when the bug is fixed.
