### ISSUE TITLE
Rosetta API - Test Commit Build in prior to the delivery to Coinbase

### ISSUE THREAD

**Issue by kaozenn** [MinaProtocol/mina#12565]
Test the `test-rosetta` tag and update the read me accordingly in prior to deliver Rosetta API to Coinbase

**Comment by kaozenn** [comment]
Rosetta Readme updated: https://github.com/MinaProtocol/mina/pull/12592

Note: There's an issue with the script in the Rosetta Artifact that populates the PostgreSQL/Archive Node and pulls missing blocks. It's failing against the Berkeley network.

This issue is not with the artifact, but with the Berkeley network itself. In November, Berkeley was redeployed and now runs in the namespace "berkeley-v2". The script, however, is still expecting "berkeley" which was the old network deployed in October. Until the Berkeley network runs in the "berkeley" namespace again, the script will continue to fail.

**Comment by kantp** [comment]
Thanks David!
