### ISSUE TITLE
Unit test for failing zkapp txns in staged ledger diff

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#12598]
A unit test involving a sequence of payments and zkapp txns where a transaction is dependent on the previous one, to be included included in staged ledger diff. 
In this sequence, one the transactions (somewhere in between) should fail. This should cause the remainder of the sequence to be discarded and only the payments up until the failed payment is included in a diff and successfully applied.

**Comment by Isaac-DeFrain** [comment]
@deepthiskumar I'd be happy to work on this! Could you possibly point me to an example unit test for something similar?
