### ISSUE TITLE
Remove "sequenceEvents" from GraphQL's "account"/"accounts" query schema

### ISSUE THREAD

**Issue by shimkiv** [MinaProtocol/mina#12633]
Internal Slack discussion is [here](https://o1-labs.slack.com/archives/C02ASV6BZCY/p1675953416808679)

**Comment by deepthiskumar** [comment]
Rename any user facing `snapp` to `zkapp` as well

**Comment by psteckler** [comment]
There is a misnamed field for the `zkapp` part of accounts, it's `sequenceEvents` when it should be `sequenceState`. Other than that, I don't see any uses of sequence events.

We might want to change "sequence state" to "action state", but that requires changes throughout the code.

**Comment by psteckler** [comment]
> Rename any user facing `snapp` to `zkapp` as well

There are no uses of `snapp` in the GraphQL schema

**Comment by psteckler** [comment]
Gregor agrees, `action_state` is better.

**Comment by psteckler** [comment]
Added #12693.

If that's done, this issue can be closed.
