### ISSUE TITLE
Add a test to confirm that supercharged rewards are properly removed

### ISSUE THREAD

**Issue by kantp** [MinaProtocol/mina#12634]

**Comment by ejMina226** [comment]
Lik here to MIP repo: https://github.com/MinaProtocol/MIPs/blob/main/MIPS/mip-remove-supercharged-rewards.md

**Comment by ejMina226** [comment]
Looks like standard reward is 720 mina for block-producer.

**Comment by ejMina226** [comment]
Looking at the CI, there is a step that executes `delegation-integration-tests` which might be a good place to see if a test could go here.

**Comment by ejMina226** [comment]
The file is `src/app/test_executive/delegation_test.ml`

**Comment by ejMina226** [comment]
A new integration test will have to be written. In it two networks will have to be created - one with a block-producer that has no locked tokens and one that does. Then the two rewards will be compared. I'm not sure any other integration test has two networks, so it remains to see if this is feasible.

**Comment by ejMina226** [comment]
Need to do three things with test:
1) Wait for block to be produced (I can already see the code how to do this)
2) Check balance on block
3) Compare increase to amount in config file
