### ISSUE TITLE
Create public page in docs on completed security audits

### ISSUE THREAD

**Issue by kantp** [MinaProtocol/mina#12653]
Over time, a number of security audits have been performed on Mina. The reports were made publicly available at the time, but we do not currently have a central, public, place that lists them.

We want to create a page on docs.minaprotocol.com to list the security audits that have been performed.

**Comment by ejMina226** [comment]
Speaking with Jason from O(1) labs who is responsible for the docs.minaprotocol page. The Security Audits are at https://www.notion.so/minafoundation/Security-Projects-a0c1fb037234422fb4208c57a2624161

**Comment by ejMina226** [comment]
Speaking with Barrie Byron from O(1) now.

**Comment by ejMina226** [comment]
This is the repo https://github.com/o1-labs/docs2
