### ISSUE TITLE
Add MinaProtocol Github Organization as a Repository Provider to the MinaFoundation Buildkite instance

### ISSUE THREAD

**Issue by Smorci** [MinaProtocol/mina#12680]
The Nix CI migration is hitting a wall due to git permission issues. Without the MinaProtocol Github Organization configured as the repository provider for the pipelines in Buildkite, the pipeline fails due to issues with git. Some of them were solved with various workarounds, but it's bad design to continue developing it like this.

Here are the instructions: 

- Go to "Settings" -> "Repository Providers" -> "Github" -> "@MinaProtocol"
- Authenticate and add the organization
- After that @Smorci can edit the pipeline to use the organization for github permissions
- @Smorci removes current workaround from VM

Cc: @michal0mina

**Comment by aneesharaines** [comment]
Added, please try now

**Comment by michal0mina** [comment]
FYI, I see Marton adding more details in slack thread as it's not resolved

https://minafoundation.slack.com/archives/C04QHJG3F4Z/p1677077236390709

**Comment by aneesharaines** [comment]
Hi @Smorci - Should be added to the correct organization now, please check again

**Comment by Smorci** [comment]
@aneesharaines the repository provider has been added, and everything is functional. Thanks!
