### ISSUE TITLE
`last_vrf_output` and `sub_window_densities` missing from Archive Node schema

### ISSUE THREAD

**Issue by MartinMinkov** [MinaProtocol/mina#12690]
### Description

The fields `last_vrf_output` and `sub_window_densities` used to calculate chain strength are missing from the [Archive Node schema](https://github.com/MinaProtocol/mina/blob/develop/src/app/archive/create_schema.sql) (the blocks table). Including such fields in the schema would allow for https://github.com/o1-labs/Archive-Node-API to calculate the best block to return at the tip of the network.

Could we add a migration to include this data related to all blocks in the Archive Node?

**Comment by psteckler** [comment]
Before doing a migration, we'd need to get the fields for blocks on the berkeley net.

I've implemented that in a branch `feature/vrf-out-win-sub-densities-in-archive-blocks`. I'll create a PR once #12741 is merged.

**Comment by shimkiv** [comment]
@deepthiskumar can you please take a look.
