### ISSUE TITLE
401 unauthorized while submitting uptime

### ISSUE THREAD

**Issue by SegaStakers** [MinaProtocol/mina#12695]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Uptime not submitted. Endpoint returns "401 unauthorized" while node set up correctly. This was confirmed by discord community leads.
I would like to ask to check web server status for requests sends from 46.21.151.114

Versions are the latest. Ports are open and reachable.
Discord :SegaStakers#0758
Thread: https://discord.com/channels/484437221055922177/799597981762453535/1077594260087513108

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

Submittion

### Actual Result

No submittion

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Low

### Status

```shell
Global number of accounts:                     147356
Block height:                                  227764
Max observed block height:                     227764
Max observed unvalidated block height:         227764
Local uptime:                                  2h2m28s
Ledger Merkle root:                            jwWhtcjs4MtbJBR4h937afwXjsD6ocyBWw6qJ1ZoWzpPePviWDd
Protocol state hash:                           3NL44Q2pGdZTWHcYL6YK4BipXjsup94zB1GED8YdtoKvH7Ms3dXo
Chain id:                                      5f704cc0c82e0ed70e873f0893d7e06f148524e3f0bdae2afb02e7819a0c24d1
Git SHA-1:                                     25388a0fed9695e8e9d04f75f50c2bae1c9c80db
Configuration directory:                       /root/.mina-config
Peers:                                         60
User_commands sent:                            0
SNARK worker:                                  None
SNARK work fee:                                100000000
Sync status:                                   Synced
```

### Additional information

Issue going for 3rd day

**Comment by shimkiv** [comment]
@lk86 can you please take a look.
