### ISSUE TITLE
Create simpler helm chart for production mina daemons/seeds/block producers

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#12710]
This new "daemon" chart should at a minimum support seed nodes, block producers, and "generic" daemon nodes with no special role. The CLI flags will be as flexible as possible to allow deploying the daemon in nearly any mode, including eventually snark coordination. Archive nodes are not supported at this time as the existing chart is already a great tool for production archival use cases.

This chart should also be multi-cloud to the degree that is possible with the daemon at the moment, at least supporting AWS-based kubernetes clusters.

**Comment by lk86** [comment]
The main goal at this stage is to support running a clone of our existing mainnet seeds and is at least feature complete with that deployment, additional features to come in future chart updates/releases

**Comment by mrmr1993** [comment]
Prior work can be found in #12585, for reference.
