### ISSUE TITLE
[transaction logic] Write tests for Inputs.Ledger

### ISSUE THREAD

**Issue by gltrost** [MinaProtocol/mina#12771]
The module `Inputs.Ledger` defines a ledger data structure. It contains functions like `get_account`, `set_account` and `check_account` which could use tests.

**Comment by gltrost** [comment]
Looking at the [Inputs.Ledger](https://github.com/MinaProtocol/mina/blob/develop/src/lib/transaction_logic/mina_transaction_logic.ml#L1259) module, I am not seeing anything code that looks particularly complex. The only function whose functionality looks somewhat complex is [check_account](https://github.com/MinaProtocol/mina/blob/develop/src/lib/transaction_logic/mina_transaction_logic.ml#L1280) which could maybe use tests.

For the test coverage project, I would love to know if the code in Ledger is worth creating a test suite for.

**Comment by ejMina226** [comment]
I would probably write a test. I had the same problem you did, which was trying to find modules meaty enough to actually get stuck into. If you already have a better module picked out, then get stuck into that, but if you don't maybe write a test for the Ledger one.
