### ISSUE TITLE
Berkeley: Archive node fails to restore block 4810

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#12809]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

There is an issue adding block 4810 to the archive node.

```
[BOOTSTRAP] Restoring blocks individually from https://storage.googleapis.com/xxx
Downloading berkeley-4810-3NK5N5GmtB6WrXY7ECvqidULAzmwsoSQwufJnKbj5RyUcoFTMJLe.json block
https://storage.googleapis.com/xxx/berkeley-4810-3NK5N5GmtB6WrXY7ECvqidULAzmwsoSQwufJnKbj5RyUcoFTMJLe.json
(monitor.ml.Error "Assert_failure src/app/archive/lib/processor.ml:102:8"
 ("Raised at Archive_lib__Processor.Token.add_if_doesn't_exist.(fun) in file \"src/app/archive/lib/processor.ml\", line 102, characters 8-50"
  "Called from Archive_lib__Processor.Account_identifiers.add_if_doesn't_exist.(fun) in file \"src/app/archive/lib/processor.ml\", line 186, characters 24-73"
  "Called from Async_kernel__Deferred0.bind.(fun) in file \"src/deferred0.ml\", line 54, characters 64-69"
  "Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5"
  "Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 169, characters 6-47"))
  ```

There was just a single failed zkApp tx in 4810 which was https://berkeley.minaexplorer.com/transaction/5JtbP8D6uUk7yaCf6gPyNoSEtxY4k5szEhSc5rvKX6tPVtaEhm88.

### Steps to Reproduce

Import block 4810 to the archive node

### Expected Result

It works.

### Actual Result

It throws an error.

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
gcr.io/o1labs-192920/mina-archive:1.3.2beta2-rampup-2884275-focal
```

**Comment by icohigh** [comment]
Yep, same for me. Also tried the new version `mina-archive=2.0.0rampup1-rampup-ae78a64`
```
[BOOTSTRAP] Restoring blocks individually from https://storage.googleapis.com/...
Downloading berkeley-4810-3NK5N5GmtB6WrXY7ECvqidULAzmwsoSQwufJnKbj5RyUcoFTMJLe.json block
https://storage.googleapis.com/.../berkeley-4810-3NK5N5GmtB6WrXY7ECvqidULAzmwsoSQwufJnKbj5RyUcoFTMJLe.json
(monitor.ml.Error "Assert_failure src/app/archive/lib/processor.ml:102:8"
 ("Raised at Archive_lib__Processor.Token.add_if_doesn't_exist.(fun) in file \"src/app/archive/lib/processor.ml\", line 102, characters 8-50"
  "Called from Archive_lib__Processor.Account_identifiers.add_if_doesn't_exist.(fun) in file \"src/app/archive/lib/processor.ml\", line 186, characters 24-73"
  "Called from Async_kernel__Deferred0.bind.(fun) in file \"src/deferred0.ml\", line 54, characters 64-69"
  "Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5"
  "Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 169, characters 6-47"))
  ```

**Comment by psteckler** [comment]
Looks like a bug when creating the `tokens_used` in the precomputed block.

```
"tokens_used":[["wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf",null],["yG6wUBq5UM4v7f53UxWwUKwCm546gZZLMF3jZvPa1FELUhwKc3",null]]
```
the first token is the default, and has no owner, correctly, the second token has no owner, but it's not the default

Same bug appears in block at height 4826.

**Comment by psteckler** [comment]
I see other precomputed blocks where non-default tokens have owners:
```
berkeley-3383-3NKrWShgSGiZTTpqM9xm5tsrnPWgd3wvWSDrg95WsSRfzr2nUAtw.json
berkeley-3383-3NLMNogZQPzsgSVduREsEcvWaA7qZjAv4NLJH4FWABurDAb25xjb.json 
```
Not sure why they're missing in these blocks.

**Comment by psteckler** [comment]
I believe the issue is: the token is mentioned in a failed zkApp, so the account that uses it is not added to the ledger, and we lookup the token owners from the ledger.

We could add the token owners to the ledger regardless of whether its account is accessed.
