### ISSUE TITLE
Tool to fork addresses from one initial SK

### ISSUE THREAD

**Issue by georgeee** [MinaProtocol/mina#12812]
Develop a tool to grow the amount of addresses from one initial SK to many so that they can be used later in round-robin fashion.

The tool is a CLI tool which takes the following arguments:

* `--secret-key` filepath to secret key which owns some MINA tokens
  * Secret key is protected by password stored in environment variable `MINA_PRIVKEY_PASS`
* `--amount` amount of MINA tokens to be split
* `--keys` total number of new secret keys to generate
* `--confirmations` number of confirmations for next transaction to be generated from a secret key
* `--key-prefix` prefix for secret key file
* `--max-tps` maximum rate of transaction sending
* `--repeat-slots` number of slots after which algorithm will retry sending the transaction

**Generation procedure**

Tool starts with a single secret key. It generates `n` secret keys (for `n` specified by `--keys` argument). Generated secret keys are saved in files with filename following pattern `{prefix}{i}.sk` where `i` corresponds to `i`-th key being generated and runs from `1` to `n`.

Then the tool funds these secret keys with MINA tokens.This is performed in number of rounds. Before the first round only the original secret key has some MINA tokens.

At each round a single transaction is sent from each existing secret key (including the original secret key) with the goal that after round ` ⌈log2(n + 1)⌉` each of `n` keys will have balance of exactly `amount / n`. Note that original key will be reduced by `amount + n * (fee + 1)` for `fee` being the transaction sending fee.

Funding will be performed by traversing a tree of keys. Here is a scheme of funding for `7` keys. Pair `(r, k)` stands for key with id `k` generated in round `r`: 

```
(0, 0)  ----------------------------------- (3, 4)
  |      \
  |       --------------- (2, 2) ----------- (3, 6)
  |     
  |     ------------------------------------ (3, 5)
  |     /
(1, 1)  ----------------- (2, 3) ----------- (3, 7)
        
```

At round `r` key `i` from range `[0 .. 2^(r - 1) - 1]` (for `0` being the original key) funds the key `i + 2^(r - 1)` if `i + 2^(r - 1) <= n`.

**Transaction sending**

Algorithm needs not be implemented in terms of sequential rounds. Rounds are to be preferably tracked on key basis. I.e. as soon as transaction from `i` to `i + 2^(r - 1)` passes necessary number of blockchain confirmations, new transactions from keys `i`  and `i + 2^(r - 1)` are to be sent (as part of round `r+1`).

Necessary number of blockchain confirmations is determined by `--confirmations` argument. When transaction is included into a block that is the best tip, it's assumed to have `1` confirmation. When transaction is in the block that's k-th ancestor of best tip, it's assumed to have `k+1` confirmations.

Transactions sent by algorithm should be queued in a way to ensure rate of transaction sending is not more than `max-tps` transactions per second. Additionally, if transaction has `0` confirmations after `S` slots, it's to be broadcasted once again, where `S` is determined by `--repeat-slots` argument.

In the algorithm, each generated address receives exactly one transaction. Amount transferred in this transaction is determined by expression `tx_amount(i, r)` for `r` being the round in which a transaction to address `i` is sent. Here is the recurrent formula for `tx_amount(i, r)` (all values can be calculated in one pass with recursion):

```
tx_amount(i, r) = amount/n, if  (i + 2^(r - 1)) > n
tx_amount(i, r) = 
  1 + fee //includes tx fee + creation fee for address (i + 2^(r - 1))
  + tx_amount (i + 2^(r - 1), r + 1) // includes amount of address (i + 2^(r - 1)), fees and amount required for all its children
  + tx_amount (i, r + 1) // includes amount of address `i` itself, fees and amounts of all its children in subsequent rounds
```

And pseudocode of the whole algorithm:

```
Q <- new queue
total <- 0

add (Q, (0, 1))

 // TODO it's possible that round variable usage is off-by-one in some occasions

while (total < N) {
 i, r <- wait_for_next (Q)
 send_transaction(from=i, to=i + 2^(r-1), amount=tx_amount(i + 2^(r-1), r)) 
 
 // register timeout for sending transaction above and if wasn't added to a block,
 // add (i, r) to Q again after repeat_slots passed

 // when transaction is added to block, add (i + 2^(r-1), r + 1) to Q
}
```

**Comment by psteckler** [comment]
Closed by #12960
