### ISSUE TITLE
Request sending regular transactions

### ISSUE THREAD

**Issue by georgeee** [MinaProtocol/mina#12819]
Develop an entrypoint for control graphql (introduced in #12811) to allow requesting node to send transactions to the network.

Here is the sketch of its interface:

```
mutation ($input: RegularPaymentsInput!) {
  scheduleRegularPayments(input: $input){
    handle
  }
}

mutation ($handle: String!) {
  stopRegularPayments(handle: $handle){
    status
  }
}
```

Where `handle` in return value is an unique identifier of the payment sending process represented by type `String`. It is returned by `scheduleRegularPayments` and can be used in `stopRegularPayments`. Mutation `stopRegularPayments` returns `status` which is a boolean, taking one of values:

* `false`, if the process is already finished or has never started
* `true` if the process was successfully stopped

Input type `RegularPaymentsInput` is represented by the following Ocaml type:

```
{ from : Private_key.t list
; to_ : Account.key
; amount : Currency.Amount.t
; fee : Currency.Fee.t
; memo : string option
; tps : float
; duration : Time.Span.t
}
```

Upon receiving the `scheduleRegularPayments`, Mina node starts generating `tps` transactions per second. Each transaction is added to the transaction pool and broadcasted to the network. Transactions are generated from keys specified in `from` field of the input type in round-robin fashion. After `duration` of time passed, process ends. ALternatively, process ends upon receiving the `stopRegularPayments` call.

**Comment by psteckler** [comment]
Closed by #12876
