### ISSUE TITLE
A new GraphQL interface with authentication to MF servers

### ISSUE THREAD

**Issue by georgeee** [MinaProtocol/mina#12811]
Implement a new GraphQL interface with authentication to MF servers.

New GraphQL should be completely separate from the existing GraphQL endpoint. It should be turned on only when a flag is provided.

**Authentication**

Header `Authorization` is expected to hold value:

```
Signature <pk> <signature>
```

Where `<signature>` is a base64-encoded 64-byte signature of the HTTP body bytes and `<pk>` is base64 encoding of the corresponding 32-byte public key. Signature scheme Ed25519 is to be used.

Add an empty query `auth` which returns boolean whether the secret key is granted access to the GraphQL control API.

When Mina node is configured for GraphQL, it should add `control_port` to the data submitted to uptime service.

**Comment by psteckler** [comment]
Implemented in #12873.
