### ISSUE TITLE
Request sending zkApp transactions

### ISSUE THREAD

**Issue by georgeee** [MinaProtocol/mina#12820]
Develop an entrypoint for control graphql (introduced in #12811) to allow requesting node to send transactions to the network.

Here is the sketch of its interface:

```
mutation ($input: ZkappPaymentsInput!) {
  scheduleZkappPayments(input: $input){
    handle
  }
}

mutation ($handle: String!) {
  stopZkappPayments(handle: $handle){
    status
  }
}
```

Where `handle` in return value is an unique identifier of the payment sending process represented by type `String`. It is returned by `scheduleZkappPayments` and can be used in `stopZkappPayments`. Mutation `stopZkappPayments` returns `status` which is a boolean, taking one of values:

* `false`, if the process is already finished or has never started
* `true` if the process was successfully stopped

Input type `ZkappPaymentsInput` is represented by the following Ocaml type:

```
{ from : Private_key.t list
; to_ : Account.key
; fee : Currency.Fee.t
; memo : string option
; tps : float
; duration : Time.Span.t
}
```

Upon receiving the `scheduleZkappPayments`, Mina node starts generating `tps` transactions per second. Each transaction is added to the transaction pool and broadcasted to the network. Transactions are generated from keys specified in `from` field of the input type in round-robin fashion. After `duration` of time passed, process ends. Alternatively, process ends upon receiving the `stopZkappPayments` call.

When iterating over the keys, first transaction will create a Zkapp with a pre-defined pair of proof/verification keys. This zkApp should be made in a way to simply green-light any transaction coming. Further transactions will be directed to this created zkapp and are to be generated using zkapp transaction fuzzying tool.

**Comment by ghost-not-in-the-shell** [comment]
The generation of zkapp account could be achieved by `Transaction_snark.For_tests.deploy_snapp` function and the rest of zkapps could be generated by the zkapp_command_generators.

For testing, I could run a local network for that.

**Comment by georgeee** [comment]
We'll need to support:

* Max byte size transaction
* "Max load" transaction
  * transactions that take maximum mount of CPU/memory/time to verify

**Comment by ghost-not-in-the-shell** [comment]
Implementation plan:
1. Creation of accounts using `Transaction_snark.For_tests.deploy_snapp`
2. Wait for zkapp to be deployed
3. generate random zkapp commands using the zkapp keypairs and fee payer key pairs
