### ISSUE TITLE
Make Graphql control excluded under mainnet profile

### ISSUE THREAD

**Issue by georgeee** [MinaProtocol/mina#12886]
When dune profile is `mainnet`, do not include the control graphql code so that it's not possible to run a mainnet node with Graphql capabilities.

Make sure there is no other ways to trigger execution of the code meant to be used by Control Graphql.

**Comment by georgeee** [comment]
Question up for discussion: do we want to take out of compilation only top-level code or most of the code involved in Graphql control API?

**Comment by psteckler** [comment]
Closed via $13007.
