### ISSUE TITLE
Remove create_and_verify workaround from kimchi_bindings

### ISSUE THREAD

**Issue by jspada** [MinaProtocol/mina#12926]
We need to remove `create_and_verify` workaround from kimchi_bindings  once the verifier index changes are merged [#12524 ](https://github.com/MinaProtocol/mina/pull/12524)

Furthermore, [#12524](https://github.com/MinaProtocol/mina/pull/12524) should make sure that it does this as part of its PR so that it confirms that the verifier index changes are complete and indeed working for the new custom gates.

In particular, in order to close this ticket [#12524](https://github.com/MinaProtocol/mina/pull/12524) should
1. Remove the create_and_verify that was added in [#12925](https://github.com/MinaProtocol/mina/pull/12925)
2. Update `kimchi_backend/gadgets/runner/runner.ml` to stop calling `create_and_verify`, instead call `create` followed by proof verification.  There are additional comments in this file describing how to update it.

**Comment by rbonichon** [comment]
Handled in #12524
