### ISSUE TITLE
Missing remote IP of the BP - Delegation Backend

### ISSUE THREAD

**Issue by Smorci** [MinaProtocol/mina#12964]
The application should log the IP of the client submitting the HTTP request.

Implementation details:

- The application was taking the IP from the `Request` type with no success
- Load Balancer configured to append `X-Forwarded-For` header key with the senders IP as the value
- Application now queries the `Header` object for `X-Forwarded-For` and logs that in the JSON
- As a fallback if nothing was retrieved it will try to retrieve from the `Request` type

**Comment by joaosreis** [comment]
Fixed by #12955
