### ISSUE TITLE
Uptime ITN analysis script

### ISSUE THREAD

**Issue by Smorci** [MinaProtocol/mina#12992]
Main goal is to compute the availability of nodes in the ITN project.

Create a go script and modify the current delegation_backend in order to:

- [x] The `delegation_backend` should include the public IP of the Block Producer in the submission name
- [x] The script needs to query the names of the submission files inside the S3 bucket (GCP for now)
- [x] Multiple BPs could run with the same key so distinguish them by IP
- [x] From these names include only the ones that are at least 15 minutes away from each other
- [x] Print out in text the outcome -> create a html table from it in the future

**Comment by EmrePiconbello** [comment]
You could also run multiple bp/nodes at the same server. Ip is not a good idea.

**Comment by michal0mina** [comment]
1. how to ensure that filenames behind uptime service will not over write each other
2. how to determine files to analize uptime

**Comment by michal0mina** [comment]
Consider having it outside mina monorepo and don't depend on mina repo

**Comment by Smorci** [comment]
Current situation:

Pushing for reviews and CI pass on the [PR](https://github.com/MinaProtocol/mina/pull/13039).

Features:

1. Application can read and add submissions from multiple buckets if the time window falls on two days
2. Prints out in uptime percentage
3. Print out to an excel sheet
4. Creates new sheet each week
5. AWS compatible
6. Constructs identities based on what the BP sends (pub-key, ip, graphql-port)
7. Always works with UTC time
8. Execution time and working interval is configurable

cc: @georgeee
