### ISSUE TITLE
refactor the usage of global slot

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#13058]

**Comment by deepthiskumar** [comment]
slots are referenced in multiple ways throughout the codebase which leads to a lot of confusion-
`slot`: slot number per epoch
`global_slot`: slot number across epochs
`global_slot_since_genesis`: slot number across forks 
`consensus_time` which is currently global_slot

**Comment by psteckler** [comment]
I suggest that the slot within an epoch, if needed, be called something like "offset"
