### ISSUE TITLE
Create a backend that tracks the array allocations

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#13088]
The backend should be also integrated into Plonk_constraint_system and emit lookup constraints

**Comment by dannywillems** [comment]
Backend means in Snarky. runtime_tables should be added to the type t in Proof_inputs, and it requires a snarky "backend". Runtime tables should be represented there. Still need to find out a good interface.

**Comment by dannywillems** [comment]
On it. Will be done in parallel of #13457

**Comment by dannywillems** [comment]
This must be finished to close the issue: https://github.com/MinaProtocol/mina/blob/2e733831e8ad5ab6ed8d21ba239b7c331acfe308/src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml#L854

**Comment by dannywillems** [comment]
TODO:
- Built on top of https://github.com/MinaProtocol/mina/commit/669bd52577a9cfc48696d515055d4cf31f8ef01e, a constraint kind to register lookups.
- Populate the runtime table in compute_witness.
