### ISSUE TITLE
Expose array lookups to SnarkyJS

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#13086]

**Comment by dannywillems** [comment]
(note) For more context, lookups from plookup are fixed lookup tables, i.e they are the same for all circuits, and we can not therefore make tables at runtime and perform lookups in it.
The [Extended lookup tables](https://o1-labs.github.io/proof-systems/rfcs/extended-lookup-tables.html) RFC describes, in particular, the concept of runtime tables.

The Rust code already implements the runtime table feature, but it is not exposed to Caml/Snarky/SnarkyJS.

**Comment by dannywillems** [comment]
List of PR's, in order:
- https://github.com/o1-labs/proof-systems/pull/1113
- https://github.com/MinaProtocol/mina/pull/13545
- https://github.com/o1-labs/proof-systems/pull/1112
- https://github.com/o1-labs/proof-systems/pull/1114
- https://github.com/o1-labs/proof-systems/pull/1115
- https://github.com/o1-labs/snarkyjs-bindings/pull/69
- https://github.com/o1-labs/snarkyjs/pull/1019
- https://github.com/o1-labs/snarkyjs-bindings/pull/70
- https://github.com/o1-labs/snarkyjs-bindings/pull/71
- https://github.com/o1-labs/snarkyjs-bindings/pull/73
- https://github.com/o1-labs/snarkyjs-bindings/pull/74
- https://github.com/o1-labs/snarkyjs-bindings/pull/75
- https://github.com/o1-labs/snarkyjs-bindings/pull/76
- https://github.com/o1-labs/snarkyjs-bindings/pull/77
- https://github.com/o1-labs/snarkyjs-bindings/pull/78

- https://github.com/MinaProtocol/mina/pull/13532
- https://github.com/MinaProtocol/mina/pull/13545
- https://github.com/MinaProtocol/mina/pull/13549
- https://github.com/o1-labs/snarkyjs-bindings/pull/79
- https://github.com/o1-labs/snarkyjs/pull/1020
- https://github.com/MinaProtocol/mina/pull/13549

- https://github.com/o1-labs/snarkyjs-bindings/pull/82
- https://github.com/o1-labs/snarkyjs/pull/1027
- https://github.com/MinaProtocol/mina/pull/13565
