### ISSUE TITLE
Write tests to cover the exposing of array lookups to SnarkyJS

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#13091]

**Comment by dannywillems** [comment]
Duplicated of #13457. Closing #13457 in favor of this one.

**Comment by dannywillems** [comment]
Description is:
Write tests with:
- one fixed lookup tables
- one runtime table
- one with fixed and runtime tables
- one with conflicting table ids to see what happens (optional)

It must be in kimchi_backends, and also in Pickles. For Pickles, base on the tests written in this PR, see here
