### ISSUE TITLE
Refactor mina_graphql code

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#13097]
The `Mina_graphql` currently contains a bunch of helper functions that don't logically belongs to it. The introduction of zkapp scheduler made things worse.

Here are a portion of code that I noted:
* [ ] `account_of_id`/`account_of_kp`/`is_zkapp_deployed`/`all_zkapps_deployed` function logically belongs the `Ledger` interface. It could live inside the `Base_ledger_intf`, but directly adding those functions to the `Base_ledger_intf` interface would require us to add each of those to different `Ledger` implementations. This naive refactor would introduce 3-4 same copy of the functions in each individual implementation. A better way to refactor those helper function would be put those in a functor around the `Base_ledger_intf` layer.
* [ ] `get_ledger_and_breadcrumb` should logically live inside the `Mina_lib` module.
* [ ] `send_zkapp_command` should live inside `Mina_commands`.
* [ ] After those refactor is done, then `wait_until_zkapp_deployed` could be moved to `Mina_commands`
* [ ] And the `go` loop of `schedule_zkapp_commands` function could also be moved to `Mina_commands`

**Comment by mrmr1993** [comment]
Corresponding refactors done in https://github.com/MinaProtocol/mina/pull/14037.
