### ISSUE TITLE
Think very carefully about every use of `choose_preimage`

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#131]

**Comment by cmr** [comment]
We should do this audit.

**Comment by mrmr1993** [comment]
Relevant code: https://github.com/CodaProtocol/coda/blob/010c9705dbc935dd0b615d9034949dfdde13c537/src/lib/coda_base/ledger_hash.ml#L24

A misbehaving node could create a valid proof by replacing the bit representation of `h1` (or `h2`) with the bit representation of `h1 + field_size` (or `h2 + field_size`) if it is less that `2^(field_size_in_bits+1)`. This happens about 23% of the time for MNT4753.

This could potentially be abused to cause one of the following scenarios when an honest node tries to create a proof that changes the (part of the) Merkle tree with that hash:
* the node checks the constraint system before creating the proof and fails hard when it doesn't match
  - Result: denial-of-service attack on the node
* the node checks the constraint system before creating the proof and aborts generating the proof
  - Result: denial-of-service attack on all transactions that affect that part of the tree
* the node does not check the constraint system and generates an invalid proof
  - Result: denial-of-service attack on the node (other nodes will ban it!)

I think we need to make sure that we do one of:
* confirm that we are checking these hashes outside of the SNARK
* modify the constraint system to make sure that the bit representation represents a value `< field_size`
* backtrack in witness generation when we notice that the hash doesn't match and try one of the other options
  - this would require large changes to Snarky

**Comment by mrmr1993** [comment]
> I think we need to make sure that we do one of:
> * confirm that we are checking these hashes outside of the SNARK

Discussed with Izaak, we are doing this already :smile:
