### ISSUE TITLE
Staged ledger hash mismatch

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#13108]

**Comment by psteckler** [comment]
The replayer checks the ledger hash after every block. Is running the replayer enough for this issue?

**Comment by psteckler** [comment]
On mainnet, the replayer found ledger hash mismatches at these slots: 146033, 146078, 146102, 146164, 146328, 146399, 146438, 146489, 146631,  and 146752.

The hashes in the db are the same as in the corresponding precomputed blocks.
