### ISSUE TITLE
Help facilitate security audit

### ISSUE THREAD

**Issue by kantp** [MinaProtocol/mina#13157]
The people conducting the security audit are having some questions about the functioning of the system and reasons why certain design choices were made. Our role is to unburden O(1) by answering these questions so that O(1) can just confirm or correct our answers. This requires some investigations, because questions often ask for reasons, which are usually not obvious from looking at the code.

The questions are listed in [an on-line document](https://docs.google.com/document/d/18Lu10NBN14XXkPP8-FWWPJVFFj4n-VI5HI9IIuwGsYk/edit), where we're going to put and discuss answers as well.

**Comment by Sventimir** [comment]
I'm still working on this. So far I have answered 2 questions to the extent sufficient for the auditors. My research seems to proceed at one question per day. See [#ext-least-authority-mina-protocol](https://minafoundation.slack.com/archives/C04QHGMPF52) Slack channel and the document linked above for more details.
