### ISSUE TITLE
Find out the best way to notify a slack channel when creating a PR

### ISSUE THREAD

**Issue by michal0mina** [MinaProtocol/mina#13206]

**Comment by kaozenn** [comment]
1. Created a Slack Channel #mf-eng-infrastructure-github-feed
2. Used the `/github` installed app and already available across Mina Foundation Organization
3. Subscribed event from the following repositories (as of today)

- [MinaProtocol/gitops-infrastructure](https://github.com/MinaProtocol/gitops-infrastructure)
- [MinaProtocol/gitops-production](https://github.com/MinaProtocol/gitops-production)
- [MinaProtocol/gitops-staging](https://github.com/MinaProtocol/gitops-staging)
- [MinaProtocol/mf-devops-workflows](https://github.com/MinaProtocol/mf-devops-workflows)
- [MinaProtocol/mina-helm-charts-private](https://github.com/MinaProtocol/mina-helm-charts-private)
- [MinaProtocol/node-stats-reporting](https://github.com/MinaProtocol/node-stats-reporting)
- [MinaProtocol/terraform-aws-kubernetes-cluster-module](https://github.com/MinaProtocol/terraform-aws-kubernetes-cluster-module)
