### ISSUE TITLE
`mina client create-token --sender PUBKEY` crashes mainnet daemon

### ISSUE THREAD

**Issue by Isaac-DeFrain** [MinaProtocol/mina#13213]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Please see the original issue [#13185](https://github.com/MinaProtocol/mina/issues/13185)

I understand that these commands have been excluded from the Berkeley daemon; no problem there.

However, they exist in `compatible` (and all versions of the mainnet daemon) and cause the daemon to *immediately crash* (please see the original issue for more info). Due to this fact, I feel the issue should be reopened. I don't have the ability to properly reopen so I made this issue and linked it to the original.

### Steps to Reproduce

1. See original issue
2.
3.
...

### Expected Result

See original issue

### Actual Result

See original issue

### How frequently do you see this issue?

Rarely

### What is the impact of this issue on your ability to run a node?

Low

### Status

```shell
See original issue
```

**Comment by shimkiv** [comment]
Please refer to this [comment](https://github.com/MinaProtocol/mina/issues/13185#issuecomment-1555955330).
Thank you.
