### ISSUE TITLE
proof-systems: code coverage with tarpaulin

### ISSUE THREAD

**Issue by dannywillems** [MinaProtocol/mina#13230]
See https://github.com/xd009642/tarpaulin

My first attempts show we should run with some non default parameters, like `-t`. We must increase the time as there are long tests. Work abandoned as not prioritized.

We should publish on a platform to get coverage diff in GitHub and PR.

**Comment by mrmr1993** [comment]
Closing in favour of https://github.com/MinaProtocol/mina/issues/13631
