### ISSUE TITLE
Invalid proofs and violated protocol log messages on `develop` CLI

### ISSUE THREAD

**Issue by Isaac-DeFrain** [MinaProtocol/mina#13241]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

We recently built the Berkeley CLI from the `develop` branch (commit `74337aef15fe65127de36d091340f396ae2f0c77`) and have noticed some strange log messages. Proofs are not being validated correctly.

Chain id: `8c4908f1f873bd4e8a52aeb4981285a148914a51e61de6ac39180e61d0144771`

We're getting a lot of entries like

```
{
  "action": "Trust_system.Actions.Sent_invalid_proof (external transition with state hash $state_hash)",
  "expiration": "2023-05-19 18:24:38.320328Z",
  "host": HOST_IP,
  "peer_id": "12D3KooWJQJJ6boizi6b9knQGYAVVrqnCbGGaXsZNAirunfQeFZS",
  "port": 8302,
  "sender_id": {
    "host": "65.108.72.143",
    "peer_id": "12D3KooWDKdHVbnkM7GJYML6ogYR5KmHUj9Ngnq1Lk42xcXnf2sx",
    "libp2p_port": 64779
  },
  "state_hash": "3NLGAuQumbvEq7svoLxFf1Q4bJx7Kc2i5pmnwHXQSW3y94XcmeJJ"
}
```

and

```
{
  "action": "Trust_system.Actions.Violated_protocol (Peer sent us bad proof for their best tip)",
  "expiration": "2023-05-19 15:31:28.462497Z",
  "host": HOST_IP,
  "peer_id": "12D3KooWJQJJ6boizi6b9knQGYAVVrqnCbGGaXsZNAirunfQeFZS",
  "port": 8302,
  "sender_id": {
    "host": "104.154.137.5",
    "peer_id": "12D3KooWP1B5ZinhnkatdA9rxEEbzKdj8j1MfKPmzQTNy1orYoy5",
    "libp2p_port": 46385
  }
}
```

and

```
Validation error: external transition with state hash $state_hash was rejected for reason "invalid proof"
```

We're connecting several peers (~15) but can't seem to progress past the genesis block.

Note:

Building from the `rampup` branch (commit `8bc96f320bd2b9fb0a2ef262e26265fe6b235a54`) works as expected, no faulty peers, syncing relatively quickly, etc.

### Steps to Reproduce

1. `git pull develop`
2. `./nix/pin.sh`
3. `nix develop mina`
4. `dune exec src/app/cli/src/mina.exe --profile=devnet -- daemon -libp2p-keypair ~/.libp2p/key --peer-list-url https:
//storage.googleapis.com/seed-lists/berkeley_seeds.txt --config-file genesis_ledgers/berkeley.json`

### Expected Result

Correctly validate proofs and observe blocks from peers

### Actual Result

See description

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
Mina daemon status
-----------------------------------

Global number of accounts:                     7405
Block height:                                  1
Max observed block height:                     1
Max observed unvalidated block height:         0
Local uptime:                                  2m55s
Ledger Merkle root:                            jxx14ajKiweveJ7iAxtzTiLfAm3KXj5Y4MMvkbLc2qhi2LYnzLS
Protocol state hash:                           3NKv6abeNz6uwAifpH7UmYi1NoAaiJXpQx1FKoDMUM7UD3v38ycB
Chain id:                                      8c4908f1f873bd4e8a52aeb4981285a148914a51e61de6ac39180e61d0144771
Git SHA-1:                                     74337aef15fe65127de36d091340f396ae2f0c77
Configuration directory:                       /home/quantifier/.mina-config
Peers:                                         6
User_commands sent:                            0
SNARK worker:                                  None
SNARK work fee:                                100000000
Sync status:                                   Synced
Catchup status:                                
        Finished:  1

Block producers running:                       0
Coinbase receiver:                             Block producer
Best tip consensus time:                       epoch=0, slot=0
Best tip global slot (across all hard-forks):  0
Consensus time now:                            epoch=2, slot=6357
Consensus mechanism:                           proof_of_stake
Consensus configuration:                       
        Delta:                     0
        k:                         290
        Slots per epoch:           7140
        Slot duration:             3m
        Epoch duration:            14d21h
        Chain start timestamp:     2023-04-06 23:30:01.000000Z
        Acceptable network delay:  3m

Addresses and ports:                           
        External IP:    _
        Bind IP:        0.0.0.0
        Libp2p PeerID:  12D3KooWJQJJ6boizi6b9knQGYAVVrqnCbGGaXsZNAirunfQeFZS
        Libp2p port:    8302
        Client port:    8301

Metrics:                                       
        block_production_delay:             7 (0 0 0 0 0 0 0)
        transaction_pool_diff_received:     1
        transaction_pool_diff_broadcasted:  0
        transactions_added_to_pool:         0
        transaction_pool_size:              0
```
```


### Additional information

_No response_

**Comment by shimkiv** [comment]
@Isaac-DeFrain the `develop` is not compatible with`rampup` or `berkeley` branches, hence, most likely won't work with currently deployed `Berkeley testnet`. Please use `rampup` instead.

Simple branching strategy is the following:
1. `compatible` is always compatible with the mainnet and has soft-forkable fixes for mainnet.
2. `rampup` is always compatible with the running `Berkeley testnet` and has soft-forkable protocol fixes and compatible `SnarkyJS` changes.
3. `berkeley` is the branch we’d be releasing off of for the mainnet hard fork. This should have all the changes in `rampup` but may additionally have fixes for `Berkeley testnet` that require a hard fork of the testnet and we may want to plan the release/redeployment for these fixes instead of disrupting the testnet immediately.
4. `develop` is for everything that we’d want to release as fast follow soft fork after the hard fork.

**Comment by Isaac-DeFrain** [comment]
Thanks for the info @shimkiv!
