### ISSUE TITLE
Booleans input/outputs or create Byte type in Snarky

### ISSUE THREAD

**Issue by querolita** [MinaProtocol/mina#13272]

**Comment by mrmr1993** [comment]
You probably want [`Field.project`](https://github.com/o1-labs/snarky/blob/14f8e2ff981a9c9ea48c94b2cc1d8c161301537b/src/base/snark_intf.ml#L380) and [`Field.unpack`](https://github.com/o1-labs/snarky/blob/14f8e2ff981a9c9ea48c94b2cc1d8c161301537b/src/base/snark_intf.ml#L467).

**Comment by querolita** [comment]
Oh well, indeed if I take the Boolean route. But I was wondering if having Byte could be interesting as well. It makes it easier to pad the input for Keccak. But I guess it would come with some range checks... So not sure about the tradeoff.
