### ISSUE TITLE
Integration Test Nginx Ingress Repair

### ISSUE THREAD

**Issue by stevenplatt** [MinaProtocol/mina#13282]
This items is to document work completed to repair graphql services used with integration tests. 
At the moment, the ingress API previously used has been deprecated and no longer functions. 

# Background: 
In July 2021, Kubernetes announced a deprecation of a series of APIs relating to ingress creation specifically: 

> All beta Ingress APIs (the extensions/v1beta1 and networking.k8s.io/v1beta1 API versions)

The impact of this change is:

> On any cluster running Kubernetes v1.19 or later, you can use the v1 API to retrieve or update existing Ingress objects, even if they were created using an older API version.

> When you convert an Ingress to the v1 API, you should review each rule in that Ingress. Older Ingresses use the legacy ImplementationSpecific path type. Instead of ImplementationSpecific, switch path matching to either Prefix or Exact. One of the benefits of moving to these alternative path types is that it becomes easier to migrate between different Ingress classes.

Original Link:
https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#what-to-do

## O(1) Implementation details

Integration tests running in CI rely on GraphQL interactions for orchestration. The infra underneath this works in 2 parts:

- Kubernetes Ingress Controller (exposed external) **<--- BROKEN PART**
- Kubernetes Ingress Interfaces (internal to Kubernetes cluster)

When an integration test runs, it spins up a testnet within Google Cloud. This testnet is not exposed externally (internal only), all requests for orchestration to graphql interfaces must therefore pass through a **Kubernetes Ingress Controller** that is a permanent installation in the GCloud environment and front-ended by the AWS Route 53 DNS entry ***.graphql.test.o1test.net** (currently pointed to the Kubernetes Ingress Controller IP: **35.230.72.176**)

The Kubernetes Ingress Controller itself is an Nginx container that is configured with a path rewriting rule that accepts a wildcard definition. At O(1), the wildcard definition is set to match names in the specific format used for integration tests. An example can be found in the Nginx documentation for rewriting targets here: https://github.com/kubernetes/ingress-nginx/blob/main/docs/examples/rewrite/README.md#rewrite-target

^^^^^
**This behavior of path matching is the functionality that was deprecated - causing the failure.**

# The Fix

The fix required a redeployment of the Kubernetes Ingress Controller that was being used for external graphql requests. A newer container image, with an updated configuration of path matching that is compatible with the latest versions of Kubernetes. 

Specifically a new helm deployment of chart version 4.5.2 was deployed to the graphql-ingress namespace, with all default chart values. The ingress-nginx docs suggest that this is the most up to date chart version that is compatible with kubernetes 1.23 which the cluster currently runs. This should provide at least 4 kubernetes version updates worth of support as-is. We also cleaned up the route53 dns zone that we are using for this test infrastructure, and moved *.graphql.o1test.net to the new IP.

The old ingress controller (called ingress-nginx in the default namespace) will be torn down early next week once we have sufficiently proven the correctness of the new configuration.

Linked PRs are pending...

**Comment by QuiteStochastic** [comment]
great write up, thank you steven!

**Comment by QuiteStochastic** [comment]
pr: https://github.com/MinaProtocol/mina/pull/13276
