### ISSUE TITLE
iOS Safari support for snarkyJS

### ISSUE THREAD

**Issue by halsaphi** [MinaProtocol/mina#13293]
Currently iOS Safari is not supported by snarkyJS. In order to encourage as wide adoption as possible add snarkyJS support to iOS Safari

**Comment by shimkiv** [comment]
https://github.com/o1-labs/snarkyjs/issues/823#issuecomment-1565757386

**Comment by mrmr1993** [comment]
Duplicate of https://github.com/o1-labs/o1js/issues/823, which is resolved.
