### ISSUE TITLE
Off-Chain Storage

### ISSUE THREAD

**Issue by halsaphi** [MinaProtocol/mina#13294]
I want to build complex apps that can use larger amounts of data than is available on-chain. This will open up more appealing use cases for zkApps.

**ZKFS**:
https://github.com/orgs/MinaProtocol/projects/16?pane=issue&itemId=19525989

**ZKDatabase**
https://zkignite.minaprotocol.com/zkignite/dev4dev-track-1/funded/suggestion/240

**Tutorial 6:**
https://docs.minaprotocol.com/zkapps/tutorials/offchain-storage

**Comment by mrmr1993** [comment]
ZKFS evolved and matured into Protokit, and o1js provides archive-backed storage in the main API.
