### ISSUE TITLE
disable snark pool persistence

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#13324]

**Comment by deepthiskumar** [comment]
@nholland94 what tests do we need for this?

**Comment by dkijania** [comment]
### Test plan 
1. Testing goals and objectives: 
    * Assure that snark worker no longer uses persistence
    * Assure that there is no critical bugs in snark worker/coordinator work
    * There is no regression in other parts of the system
    * There is no regression in performance or load
2. Testing approach: 
    * Ensure CI tests are green
    * Test locally the change (no persistent storage should be used for snark worker)
    * Compare performance on local network before and after fix. It should not be worse more than 5%
    * Test with local network setup for longer period (~2-3 hours) to ensure there is no problem with stability
    * Modify existing tests (for example payment to ensure no persistent storage is used)
3. Testing scope: 
    * Snark Worker setup / Snark Coordinator setup
    * Snarking transaction
    * Network performance
4. Testing requirements: 
    * No particular testing requirements
5. Testing resources: 
    * Local network environment
    * Gloud availability (for CI run)
    * Test cases in our quality and testing Github project

**Comment by dkijania** [comment]
@deepthiskumar @nholland94 please advise if you see anything not covered /missed in above plan

**Comment by deepthiskumar** [comment]
Snark pool persistence was added to reduce the chances of missing coinbase rewards when a node restarted and synced just before producing a block. But the persisted pool gets garbage collected during frontier initialization rendering this feature useless and negatively impacting node performance.

**Comment by deepthiskumar** [comment]
@dkijania The cases you added makes sense. I'd add saturating blocks with txns to test performance. @georgeee has confirmed removing this improves node performance in an internal testing

**Comment by dkijania** [comment]
This epic is now containing all items from this issue: #13690
