### ISSUE TITLE
running replayer in integration tests is flaky

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#13354]
In `zkapps-integration-test` and `zkapp-nonce-integration-test`, `running replayer` step sometimes fails because the archive-node pod can not be found. When looking at the log, there's no error message says the archive hit any specific exceptions or crashed explicitly.

**Comment by mrmr1993** [comment]
Fixed in https://github.com/MinaProtocol/mina/pull/15854.
