### ISSUE TITLE
Block production experiences long async cycles

### ISSUE THREAD

**Issue by georgeee** [MinaProtocol/mina#13508]
_Found on a cluster of 5 BPs, 5 regular nodes, 1 coordinator (with 20 workers) and 1 seed node, configured with 45s slot duration, `k=12` and 288 slots per epoch_

When block is produced, some long async cycles significantly delay its acceptance to frontier and broadcast.

Causes:

* Use of hashing in snark pool logic
* Mysterious background thread

On the latter, a long async cycle happens during or shortly after notifying the frontier extensions. When the network is started, it isn't visible, but over its lifetime it grows at a speed of `~0.5s` per hour with network dying after ~36 hours because all blocks start to be produced later than within a slot (because of 45s duration). Existence of the issue is to be confirmed on the 3-min-window cluster, but it's a serious complication in running tests on short-slot-window cluster.

**Comment by deepthiskumar** [comment]
I believe all the issues raised here are fixed. Tracking another long async cycle impacting BP in #13576.
