### ISSUE TITLE
Nodes on berkeley network is not stable

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#13510]
Since we are `spot` instances for berkeley network, this makes the k8s nodes on berkeley network sometimes very unstable. Depending on the workload of google's data center, gcloud may grab our nodes for its own purpose. This makes the pods on berkeley network restart much more often than we expect. The constant restart of pods causes the network to be unstable and is one of main contributors to the alerts.

What we could do is to use the same budget but deploy less node and move some of the more important nodes to a more stable instance. For example, we could have 6 whale block producers and the 3 seeds + 3 archive node + 1 snark coordinator lives on the stable instance while having other fish block producers living in the unstable world. This would at least guarantee the production of blocks/snarks on the network. If we decided to do so, we first need to change the stake distribution on the next berkeley network depending on the number of whales living on a stable instance. If we decide to leave a portion of the network in the unstable world, then we might want to change the alert for that part of the network, for example, `MultipleNodeRestarted` should not count those mina instances. We still have memeory leak in the current version of the mina daemon, but those memory leak usually takes at least 4-5 days to exceed the limit and kill the pod, so we don't need to worry too much about them for now.

**Comment by deepthiskumar** [comment]
This was due to using a cluster that was over-allocated. Has been fixed for now
