### ISSUE TITLE
update for genesis timestamp

### ISSUE THREAD

**Issue by vanarasiantonyswamy** [MinaProtocol/mina#13527]
update genesis time stamp for berkeley

**Comment by vanarasiantonyswamy** [comment]
https://github.com/MinaProtocol/mina/pull/13522

**Comment by vanarasiantonyswamy** [comment]
CR sent and merged after approval.

**Comment by Miniiii1989** [comment]
1989

در تاریخ پنجشنبه ۶ ژوئیهٔ ۲۰۲۳،‏ ۰۶:۲۸ vanarasi A ***@***.***>
نوشت:
