### ISSUE TITLE
Long async cycle during block production scheduling

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#13576]
In testing the Berkeley network, we are observing a growing long async cycle that happens immediately after a block is produced and before a new block is scheduled for production. This long async cycle grows linearly, and the rate of growth is significant. Once this long async cycle gets longer than a slot window (which doesn't take terribly long to happen), the block producers will begin having serious issues that prevent the network from properly progressing.

## Observations
- async cycle growth is linear as ledger grows from genesis state
- async cycle is inherited by bootstrapping nodes (not temporal state)
- starting from a large genesis ledger does not produce the issue
- running for 2 epochs w/o transactions (to generate non-genesis epoch ledgers) does not produce the issue
- issue is only produced when transactions are being sent on the network, causing new accounts to be created
- (unconfirmed) time spent is reported in interaction with vrf evaluator
  - the code reported here doesn't make sense to cause a long async job, so it's possible this is a bug in how the long async jobs are being reported

## Possible Causes
- zkapps accounts
  - we don't initialize genesis ledger with zkapps accounts, but we create zkapps accounts over time with our txn tooling
  - [ ] TASK: see if the issue happens when we only create non-zkapps accounts on the network
- computing delegatee tables
  - we have no reason to believe this should be called every iteration of the block production loop, but this is the most likely operation that could increase in time with ledger size
  - [ ] TASK: measure performance of Ledger.Db.iteri
    - [X] with non-zkapps accounts
    - [x] with zkapps accounts
    - [ ] using epoch ledger like rocksdb checkpoints
  - [ ] TASK: instrument threads and add more logs indicating when delegatee table computations are performed

## Additional Tasks
- [ ] try non-local storage solution for reporting o1trace thread stacks, in case local storage is leaking into other threads (could explain the async job reporting to somewhere that doesn't make sense)
- [ ] add a hack to o1trace to temporarily log *all* async jobs during the window we know the issue occurs
- [ ] attempt to repoduce locally with short params

**Comment by georgeee** [comment]
Some new information from an experiment:

1. Epoch ledger was taken from a cluster experiencing ~38s async job delays (ledger JSON of 34 Mb)
2. A cluster was launched with the 34 Mb ledger
3. Cluster was launched off commit `a4380f0` with 1 min block window, `k=12` and epoch length of 288 slots (top of `berkeley` branch at the time of launch)
4. One node (a block producer) was configured with a different commit, top of https://github.com/MinaProtocol/mina/pull/13542 with all recent long async cycle fixes)

Experiment went as follows:
1. For nearly 24 hours no significant transaction load was generated on the cluster. There was no significant long async job on block production (note that 24 hours amounts to 5 epochs, of these 24 hours first two epochs had literally `0` transactions)
2. After ~24 hours transaction generated was set to generate a high rate of transactions per second (around 0.5 tps for the whole cluster)
3. After ~10 hours (roughly 2 epochs from beginning of active tx generation) epoch ledger grew to 44 Mb and async job of 44s appeared on every block producer after each block produced

**Comment by georgeee** [comment]
So, async job duration is linear in epoch ledger size. Condition doesn't trigger on genesis ledger, but requires substantial transaction load to be activated. However the resulting delay is linear in total size of epoch ledger, not difference from genesis ledger.
