### ISSUE TITLE
Migrate and redeploy kubernetes cron jobs using "batch/v1" API

### ISSUE THREAD

**Issue by stevenplatt** [MinaProtocol/mina#13639]
At the moment, the infra code for a number of cron jobs in the `Mina` repo are set to use the `batch/v1beta1` API. 

- Example: https://github.com/MinaProtocol/mina/blob/develop/helm/archive-node/templates/dump-archive-cronjob.yaml#L2

Use of the `batch/v1beta1` API was deprecated 2 kubernetes versions ago (removed in GKE API version 1.21). It is scheduled to be fully removed in GKE API 1.25.  Cron jobs that still run using the unsupported `batch/v1beta1`  API are expected to hard break at the time.

- More information: https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-25?authuser=2

Updating and redeploying all existing cron jobs that use the old API is requested. The infra source files in all of the mainline mina repos (`compatible`, `rampup`, `develop`, `berkeley`) would need to be updated to reflect this, so that they are not accidentally reused in the future, reintroducing the retired API.

**Comment by dkijania** [comment]
berkeley is done. Compatible/Develop in review. rampup to go
