### ISSUE TITLE
Missing wasm-opt on Rosetta integration test CI job

### ISSUE THREAD

**Issue by joaosreis** [MinaProtocol/mina#13655]
Rosetta integration test job is failing with a missing `wasm-opt` error.

### Console output

```shell
./scripts/update-snarkyjs-bindings.sh: line 39: wasm-opt: command not found
```
### Build link(s)

https://buildkite.com/o-1-labs-2/mina-o-1-labs/builds/28102#0187b66c-10e6-45c9-a7ba-5341e7290475

**Comment by mrmr1993** [comment]
Rosetta integration test reliably succeeds now. Closing.
