### ISSUE TITLE
Test a node can connect to the network based on persisted peer store

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#13730]

**Comment by deepthiskumar** [comment]
Hard to test locally- disable MDNS and force libp2p to use peer discovery

**Comment by ghost-not-in-the-shell** [comment]
Tested by running rampup4 daemon locally on my laptop.
1. Connected to the network by passing it the peer list
2. Connected to the network by skipping the `peer-list` but passing it a fake peer `mina daemon -libp2p-keypair ~/keys/libp2p -peer /dns4/seed-11.berkeley.o1test.net/tcp/10000/p2p/12D3KooWAdgYL6hv18M3iDBdaK1dRygPivSfAfBNDzie6YqydVbs`. I changed seed-1 to seed-11 here. The node managed to connect to the network
3. Remove the .mina-config and tried to connect to the network with a fake peer. This time no peer is found.
