### ISSUE TITLE
Include network ID when generating account update hash

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#13759]
https://github.com/MinaProtocol/mina/discussions/13689#discussioncomment-6531046

**Comment by ghost-not-in-the-shell** [comment]
Implementation details:
1. pass network-id to `zkapp_body` defined in `hash_prefixes.ml`;
2. In `hash_prefix_states.ml`, do a match against `Mina_signature_kind` to get the network-id for `zkapp_body` function
3. Plumbing through all function call to `zkapp_body`
Testing:
Try to implement a unit test in transaction_snark that verifies and applies zkapp_command that use different network-ids.
