### ISSUE TITLE
Automatic patching of archive dbs

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#13797]
The archive nodes should be able to automatically patch themselves if they're missing blocks.

There is a script in `src/app/rosetta/download-missing-blocks.sh` that can be adapted for this purpose. The archive node deployment can run this script, which looks for missing blocks periodically (currently, every hour).

Make running this script part of the archive node deployment. The script requires the missing blocks auditor and archive blocks apps.

Run this on mainnet, devnet, and berkeley.

**Comment by dkijania** [comment]
Implemented on devnet and mainnet
