### ISSUE TITLE
Additional endpoints to ITN graphql server

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#13843]

**Comment by deepthiskumar** [comment]
Can we add the following endpoints (from existing default graphql server) to ITN  GraphQL server?
• query { account }
• query { bestChain }
• query { block }
• query { transactionStatus }
• query { snarkPool }
• query { pooledUserCommands }
• query { pooledZkappCommands }
• mutation { sendPayment }
• mutation { sendZkapp }

**Comment by psteckler** [comment]
Do we want the same sequence check and authorization for these as we have for the other ITN endpoints?
