### ISSUE TITLE
ITN fund command: use Get_balance instead of Get_ledger

### ISSUE THREAD

**Issue by georgeee** [MinaProtocol/mina#13874]
We plan to launch ITN with ledger containing >100k accounts.

During testing with ~85k accounts it was observed that `itn-create-accounts` command imposes a visible load onto the node it uses for sending the transaction. 

I believe this happens because the whole ledger is attempted to be downloaded, which becomes an expensive operation.

I suggest to use a series of `Get_balance` commands (or introduce a batch version of this RPC) to get balance of every account we expect to be created.

**Comment by psteckler** [comment]
Fixed by #13887.
