### ISSUE TITLE
Fix the custom gates in Pickles

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#13927]
The lookup gate isn't properly integrated with the custom gates integration in Pickles. We need to fix the lookup gate integration in order to re-enable proving custom gates in pickles. The underlying work will also update the wrap circuits to enable the verification for their step proofs. The goal is that this fix won't affect/change the circuits that are not using custom gates.

This fix will affect the pickles verifier for compatibility with the updated foreign field multiplication gate: a breaking change that will need to land in the Berkeley hard fork.

This PR already does the above, but there is still somethings TODO:
* tests for the lookup gate
  - this requires some routing to inject the correct lookup tables
* tests for runtime lookup tables
  - this requires some additional routing to setup the runtime table structure and inject the values for use in the proof
* the `Maybe` versions of the logic, with tests
  - these are all a straightforward modifications of the existing logic
  - the tests require a second set of pickles inductive rules, where there is an additional rule that *doesn't* use the optional gates
* integrating the tests into the unit tests
  - this is a trivial modification to the dune file.

**Comment by dannywillems** [comment]
Only runtime table tests left: https://app.zenhub.com/workspaces/core-crypto-621fcb82b7d49700156fd060/issues/gh/minaprotocol/mina/13961
