### ISSUE TITLE
Persistent frontier load is never working

### ISSUE THREAD

**Issue by georgeee** [MinaProtocol/mina#13949]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Persistent frontier load is never working. On startup, node always goes through the Bootstrap phase.

Most of the time it doesn't pose a trouble, however if the whole cluster is restarted at once, network will die because none of the nodes is able to load persistent frontier, none is able to help another to finish Bootstrap phase.

### Steps to Reproduce

1. Launch a node, let it reach Synced state
2. Restart the node

### Expected Result

Node restarts, loads persistent frontier and is able to skip bootstrap.

### Actual Result

Node reports not being able to load persistent frontier and goes through Bootstrap.

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Medium

### Status

```shell
N/A
```

### Additional information

N/A

**Comment by deepthiskumar** [comment]
TODO: Try writing diff buffers strictly for the test network

**Comment by deepthiskumar** [comment]
If long async job is < 5s then we are ok shipping it else we do this for testnets only and discuss further on the fix

**Comment by georgeee** [comment]
Seems like directly linked to PR #13557
