### ISSUE TITLE
Have a better error message sent to caml when calling `build`

### ISSUE THREAD

**Issue by dannywillems** [MinaProtocol/mina#13978]
At the moment, the error message is not sent to caml in [caml_pasta_fp_plonk_index_create](https://github.com/MinaProtocol/mina/blob/develop/src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_index.rs#L81).

**Comment by mrmr1993** [comment]
Fixed in commit https://github.com/MinaProtocol/mina/commit/e95103ab286 as part of the debugging infra for https://github.com/MinaProtocol/mina/pull/14317.
