### ISSUE TITLE
LookupTable: lookup tables given as parameter should not have an ID conflicting with the built-in XOR and range check.

### ISSUE THREAD

**Issue by dannywillems** [MinaProtocol/mina#13976]
At the moment, built-in lookup tables are XOR and range check. They have respectively the ID `0` and `1`, defined in [mod.rs](https://github.com/o1-labs/proof-systems/blob/develop/kimchi/src/circuits/lookup/tables/mod.rs#L8).

When we define new lookup tables, we must ensure there is no conflict. The initial idea implementation hopes that the user will not create a lookup tables with the wrong ID, and therefore give the user the responsibility of not messing up during the constraint creation.

**Comment by volhovm** [comment]
I think this is closed by https://github.com/o1-labs/proof-systems/pull/1652, please reopen if I misunderstood it.
