### ISSUE TITLE
snark-transaction-profiler job is failing on PR train

### ISSUE THREAD

**Issue by dkijania** [MinaProtocol/mina#14086]
#### PR train

Pr train is a situation in which we make a PR into another branch which is not a mainline branch. When a branch, like develop <- A <- B. We can merge B in a A and after that merge A. Or we can also merge A to develop and the target branch for B will become develop automatically. 

snark-transaction-profiler is angry when we do not target a branch in [develop, master, berkeley] 
see https://github.com/MinaProtocol/mina/blob/develop/buildkite/scripts/run-snark-transaction-profiler.sh#L11.
run-snark-transaction-profiler.sh

**Comment by mrmr1993** [comment]
Fixed in https://github.com/MinaProtocol/mina/pull/14638
