### ISSUE TITLE
Test to check `develop` is compatible with `berkeley`

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#14142]

**Comment by deepthiskumar** [comment]
1. check if `develop` is currently compatible with `berkeley` network- 
    a. Merge `berkeley` into `develop`
    b. Deploy a network using `berkeley` image
    c. Connect a node using `develop` image to the network

2. CI job that tests `develop` remains compatible with `berkeley`

**Comment by psteckler** [comment]
Think I've done 1 a, b, and c.

Created PR #14144.

Locally, started a daemon built with `berkeley` as a seed. Then built a daemon created with the PR branch, specifying the seed node as a peer. Both branches use the same chain id. The non-seed daemon was able to sync to the seed daemon.

Note: the chain id is different than in the current berkeley testnet.

@deepthiskumar is that enough? Can the CI job do the same as my local experiment?

**Comment by deepthiskumar** [comment]
@psteckler Yes, that should be enough. Can we do the same in a CI job?

**Comment by psteckler** [comment]
Done in #14181.
