### ISSUE TITLE
Automate updating submodules in Mina/o1js/o1js-bindings/proof-systems

### ISSUE THREAD

**Issue by dannywillems** [MinaProtocol/mina#14171]
Whenever we make a potentially breaking changes in one submodules, we should open a PR updating to the new commit, and be sure it doesn't break the tests or worse, the compilation.

**Comment by dkijania** [comment]
This issue should be resolved by #14196

**Comment by mrmr1993** [comment]
Closing in favour of https://github.com/MinaProtocol/mina/issues/14196
