### ISSUE TITLE
Mina book - Kimchi section regarding permutation is empty.

### ISSUE THREAD

**Issue by dannywillems** [MinaProtocol/mina#14186]
Links to add: https://minaprotocol.com/blog/a-more-efficient-approach-to-zero-knowledge-for-plonk.

In the code:
`zk_rows` is the number of blinders, and is set to `3` at the moment. It is because we evaluate at `\z` and `\omega * z` , and for the zero-knowledge property, we need `N + 1` blinders where `N` is the number of evaluations points.

Also https://mirprotocol.org/blog/Adding-zero-knowledge-to-Plonk-Halo and https://www.plonk.cafe/t/noob-questions-plonk-paper/73.

**Comment by mrmr1993** [comment]
The section is no longer empty. Closing.
