### ISSUE TITLE
Update to Rust 1.71

### ISSUE THREAD

**Issue by dannywillems** [MinaProtocol/mina#14188]
We start having issues with yanked packages and packages required to update Rust: https://github.com/o1-labs/proof-systems/actions/runs/6272446495/job/17033986391?pr=1253 from this PR.

We must update in Mina.

Also we could update the wasm binding

**Comment by dannywillems** [comment]
Related PR's to revive:
https://github.com/o1-labs/proof-systems/pull/1199
https://github.com/o1-labs/proof-systems/pull/1136
https://github.com/o1-labs/proof-systems/pull/1198

**Comment by rbonichon** [comment]
Update `src/lib/snarkyjs/src/bindings/kimchi/wasm/rust-toolchain.toml` and
`/lib/crypto/kimchi_bindings/stubs/rust-toolchain.toml` accordingly.

And add the corresponding line(s) to `nix/rust.nix`

**Comment by dannywillems** [comment]
Closing. Done.
