### ISSUE TITLE
I started getting "no space left on device" error even though the documentation says that 10 GB is enough for server disk capacity

### ISSUE THREAD

**Issue by kadiralan** [MinaProtocol/mina#14348]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Summary

In the document I have shared the link below, it says that 10 GB disk capacity will be enough. I ran a node with 10 GB capacity and after 1 day I started getting "no space on disk" errors. In this case, I think a change should be made to the document

https://docs.minaprotocol.com/test-world-2/technical-requirements

<img width="937" alt="image" src="https://github.com/MinaProtocol/mina/assets/24243976/7640198c-f048-4ba4-af30-baa27a3d5db2">
<img width="1149" alt="image" src="https://github.com/MinaProtocol/mina/assets/24243976/550f4e72-4502-4ce0-ba24-eb96542cd1ab">

### Steps to Resolve this Issue

1 - Run node for "Block Production" role on a machine with 10 gb disk capacity
2- Wait for about 1 day
3- Observe that the disk is full

**Comment by kadiralan** [comment]
> From my understanding, in your case, the `10Gb` of disk space is allocated for entire VM (or any other server). When in documentation states about `10 GB free storage` which means that we anticipate at least 10 GB of storage available after your VM/Server setting up (including OS, any additional software installation, Mina apps installation, etc.).

The limit I set for this VM I created is set to 10 GB. However, I am only running Mina Node in this VM. I did not run anything external. /dev/root is using 9.5 GB of space as you can see. Which only corresponds to Mina Node. In this case, would defining an 11 GB space solve the problem?

**Comment by shimkiv** [comment]
Can you maybe try to identify "who" consumed the most of the space? For example you can use the `du` utility against different paths on the file system.

**Comment by kadiralan** [comment]
<img width="376" alt="image" src="https://github.com/MinaProtocol/mina/assets/24243976/0dbc2e41-2881-436b-9ae4-5ae9e8d2a465">

<img width="306" alt="image" src="https://github.com/MinaProtocol/mina/assets/24243976/297bca6f-f65e-4117-965f-7587a48aa56a">
<img width="268" alt="image" src="https://github.com/MinaProtocol/mina/assets/24243976/5a537b58-9d9a-43b3-a1fd-b3b4402bdf68">


I changed the size of the disk to 15 GB and I continue to follow it. However, I still think that the document should be modified. Many people may have created a machine with a 10 GB Limit.

**Comment by kadiralan** [comment]
I started to get the same exception even I upgraded the disk capacity to 15 GB.

<img width="369" alt="image" src="https://github.com/MinaProtocol/mina/assets/24243976/a290c10e-cde2-48b1-bdc5-72b4ab86709d">

**Comment by vfrsilva** [comment]
@kadiralan we have updated the documentation. Thank you for your support.
