### ISSUE TITLE
Develop connects to berkeley test fails

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#14350]
The `berkeley` daemon, started as a seed, seems to be stuck in the `Bootstrap` state, never gets to `Synced`

Failing test: https://buildkite.com/o-1-labs-2/mina-end-to-end-nightlies/builds/611#018b372b-8923-4a3e-9d04-767c568e44ce

**Comment by psteckler** [comment]
I ran the locally, it succeeds for me.

**Comment by dkijania** [comment]
@psteckler you are right. As a result maybe we can merge my PR preventing this job from running more than 60 minutes and we can close it
