### ISSUE TITLE
Archive schema issue

### ISSUE THREAD

**Issue by nerdvibe** [MinaProtocol/mina#14365]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

According to my understanding in order to build the schema for Bekerley we need to execute [create_schema.sql ](https://raw.githubusercontent.com/MinaProtocol/mina/55b78189c46e1811b8bdb78864cfa95409aeb96a/src/app/archive/create_schema.sql) and [zkapp_tables](https://raw.githubusercontent.com/MinaProtocol/mina/55b78189c46e1811b8bdb78864cfa95409aeb96a/src/app/archive/zkapp_tables.sql)

But when being executed in that order, the schema throws attached errors

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

psql -h localhost -p 5432 -d archive -f <(curl -Ls https://raw.githubusercontent.com/MinaProtocol/mina/55b78189c46e1811b8bdb78864cfa95409aeb96a/src/app/archive/create_schema.sql)

### Actual Result

postgres@Ubuntu:~$ psql -h localhost -p 5432 -d archive -f <(curl -Ls https://raw.githubusercontent.com/MinaProtocol/mina/55b78189c46e1811b8bdb78864cfa95409aeb96a/src/app/archive/create_schema.sql)
Password for user postgres:
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TYPE
CREATE TYPE
CREATE TABLE
CREATE TYPE
CREATE TABLE
CREATE TABLE
CREATE INDEX
psql:/dev/fd/63:103: error: /dev/fd/zkapp_tables.sql: No such file or directory
psql:/dev/fd/63:120: ERROR:  relation "zkapp_fee_payer_body" does not exist
CREATE TABLE
CREATE TABLE
CREATE TYPE
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
psql:/dev/fd/63:190: ERROR:  relation "zkapp_permissions" does not exist
psql:/dev/fd/63:192: ERROR:  relation "accounts_accessed" does not exist
psql:/dev/fd/63:193: ERROR:  relation "accounts_accessed" does not exist
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
psql:/dev/fd/63:257: ERROR:  relation "zkapp_commands" does not exist
psql:/dev/fd/63:259: ERROR:  relation "blocks_zkapp_commands" does not exist
psql:/dev/fd/63:260: ERROR:  relation "blocks_zkapp_commands" does not exist
psql:/dev/fd/63:261: ERROR:  relation "blocks_zkapp_commands" does not exist

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Medium

### Status

```shell
not needed
```

**Comment by Sventimir** [comment]
Executing `zkapp_tables.sql` manually is not necessary. It gets called by `create_schema.sql` [here](https://github.com/MinaProtocol/mina/blob/develop/src/app/archive/create_schema.sql#L103).  Executing just `create_schema.sql` is sufficient. Does that work?

**Comment by nerdvibe** [comment]
Ah then this is the issue.  I followed the instructions on the [docs](https://docs.minaprotocol.com/node-operators/archive-node#set-up-the-archive-node) and executed `psql -h localhost -p 5432 -d archive -f <(curl -Ls https://raw.githubusercontent.com/MinaProtocol/mina/55b78189c46e1811b8bdb78864cfa95409aeb96a/src/app/archive/create_schema.sql)` as suggested, making sure to use the new URL for the schema(s).

so with the mentioned approach psql won't know the existence of zkapp_tables.sql .

I think this is a consequence of the frequently mentioned problems with the documention. For Testworld it has been very problematic to setup the different nodes due to lack of consistent documentation.

As users, we need working, non ambiguous, non scattered and tested documentation on how to achieve the results. It has been quite frustrating to setup up things correctly and the community had to come up with alternative documentations for fixing the issue of lack of documentation. Sorry for venting on this issue and going off topic, but I believe docs are fundamental for a good developer/user experience. 🙏

**Comment by Sventimir** [comment]
I completely understand your point of view, @nerdvibe. I think this documentation page has been written with the mainnet in mind, where there are no zkApps yet and consequently, there are no zkapp tables in the database. You cannot do this with current testnets anymore. We'll update the documentation to mention this. Thanks for raising this!

Meanwhile I suggest that you manually download both SQL files to your disk and only then feed `create_schema.sql` to Postgres. `zkapp_tables.sql` should automatically be picked up from the current directory.

**Comment by nerdvibe** [comment]
thank you for the suggestion, yes that's how I fixed the issue the other day. 🙏

**Comment by halsaphi** [comment]
hi @nerdvibe, 

The https://docs.minaprotocol.com/test-world-2/launching-a-node#archive-node page was intended to show that the testworld 2.0 network required both schemas ... with a link to the correct versions for testworld 2.0.

You are right - we need to improve the docs and produce step by step guides - the node operator docs have been neglected for a long time, rest assured we are working on it but it will take some time to get the docs good and right!

**Comment by Sventimir** [comment]
@nerdvibe, do you think we can close this issue?

**Comment by nerdvibe** [comment]
> @nerdvibe, do you think we can close this issue?

sure!
