### ISSUE TITLE
OOM when running max cost transactions

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#14369]
Running a max-cost transaction generator at rate of `> 30 txs/min` for some hours results in some nodes on the cluster OOM.

This effect is quite visible, at least 50% of nodes of 200-node cluster were found to OOM.

Each node in the cluster is deployed with 12 GB of RAM.

This effect is neither present with lower txs/min rate nor when generating non-max-cost transactions.

UPD: tested on 16 GB nodes, effect is still present.
UPD2: tested on 20GB, seems like no OOMs anymore

**Comment by georgeee** [comment]
Redeployed the cluster with the 20GB RAM nodes, OOMs are not detected after 4 hours of generation.

After running for a while more, plan to redeploy the cluster back with 16 GB to double-confirm the observation

**Comment by georgeee** [comment]
Redeployed the cluster with the 20GB RAM nodes, OOMs are not detected after 4 hours of generation.

After running for a while more, plan to redeploy the cluster back with 16 GB to double-confirm the observation

**Comment by georgeee** [comment]
| round | rate_min | max_latency     | missed | target |
|-------|----------|-----------------|-------------|-----------|
| 0     | 28.43    | 09:14:51.387548 | 0.15   | 29.70 |
| 1     | 29.75    | 07:08:43.177513 | 0.18   | 35.56 |
| 2     | 13.72    | 04:10:08.83601  | 0.08   | 27.04 |
| 3     | 28.86    | 03:07:57.335551 | 0.16   | 33.74 |
| 4     | 25.21    | 10:06:57.895292 | 0.22   | 29.51 |
| 5     | 27.37    | 10:09:59.425032 | 0.19   | 30.94 |
| 6     | 35.04    | 08:22:11.451213 | 0.13   | 37.75 |
| 7     | 32.62    | 05:56:30.715999 | 0.12   | 38.79 |

Finished a 8-hour experiment of max-cost transactions.
