### ISSUE TITLE
Change of RemoteAddr format

### ISSUE THREAD

**Issue by georgeee** [MinaProtocol/mina#14374]
A new version of uptime backend is used in ITN. This version wasn't tested yet with other pieces of software that uses uptime data.

Submissions made by the new version use the following format for `remote_addr` field:

```json
{ "remote_addr":"5.180.186.25" }
```

Whereas previous versions always used `ip:port` format, like:

```json
{ "remote_addr":"5.180.186.25:12345" }
```

This discrepancy leads to fetcher (and possibly other software) to fail in using the uptime data:

```
2023-10-18T11:37:22.081467Z ERROR ThreadId(06) src/main.rs:396:
Failure when updating list of nodes:
  wrong remote address in submission
  berkeley/submissions/2023-10-18/
  2023-10-18T11:36:50Z-B62qnKexFyFub6M6mhT3Va3C5kEEUcajb33rzoNWzQasY81oGTSMV5p.json:
  5.180.186.25
```

Other tools of ITN toolkit might be affected too:

* Orchestrator (a.k.a. tx generator)
* ITN uptime analyzer

Additionally, before launching this uptime backend on mainnet, following tools' compatibility with the new format should be checked:

* Stateless verifier (https://github.com/MinaProtocol/mina/pull/9693, awaits merge)
* Stateful verifier (by OnTab)

**Comment by georgeee** [comment]
On the cause of the format's change:

```go
remoteAddr := r.Header.Get("X-Forwarded-For")
if remoteAddr == "" {
	// If there is no X-Forwarded-For header, use the remote address
	remoteAddr = r.RemoteAddr
}
```

these lines replaced the previously used `remoteAddr = r.RemoteAddr`.

Crucially, `X-Forwarded-For` holds only address, not port. To be precise, existing handling is not accurate as there might be a few `X-Forwarded-For` headers each containing comma-separated list of addresses, some of which might be internal.

Following the advice of [Mozilla.org docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#selecting_an_ip_address), we need to consider all headers, filter out internal addresses and select the first external IP address. There is something said of trustworthiness checks, but I believe we can ignore it for our purposes.

As for the tooling, I think the best strategy is to allow treatment of remote address as either `addr:port` or just `addr`. I don't think any tool requires port.

**Comment by Smorci** [comment]
@georgeee I have developed the ITN uptime analyzer based on the change mentioned above so that tool is not affected by this change.
