### ISSUE TITLE
Libp2p helper crashing from unknown exception

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#14383]
In ITN, we have observed a decent number of libp2p crashes with an unknown error (139 in last 24 hours). We appear to lose the error's original content when we re-throw the exception and eventually wrap that replaced backtrace into the `Libp2p_helper_died_unexpectedly` exception.

### Originating Backtrace
```
Raised at Gossip_net__Libp2p.Make.T.create_libp2p.(fun).handle_mina_net2_exception in file "src/lib/gossip_net/libp2p.ml", line 220, characters 12-21,
Called from Base__Result.try_with in file "src/result.ml", line 195, characters 9-15
```

### Top Level Exception
```
monitor.ml.Error, Mina_net2__Libp2p_helper.Libp2p_helper_died_unexpectedly, Raised at Mina_net2__Libp2p_helper.handle_libp2p_helper_termination in file "src/lib/mina_net2/libp2p_helper.ml", line 144, characters 8-45,
Called from Async_kernel__Deferred0.bind.(fun) in file "src/deferred0.ml", line 54, characters 64-69,
Called from Async_kernel__Job_queue.run_job in file "src/job_queue.ml" (inlined), line 128, characters 2-5,
Called from Async_kernel__Job_queue.run_jobs in file "src/job_queue.ml", line 169, characters 6-47,
Caught by monitor at file "src/lib/gossip_net/libp2p.ml", line 236, characters 31-31
```

**Comment by nholland94** [comment]
In debugging this by looking through community crash logs, here are some observations:

- The crash always seems to happen when the libp2p_helper is first spawned by the daemon, during the time when we send the `BeginAdvertising` RPC request.
  - This can happen at daemon initialization, or upon a libp2p_helper restart due to a prior issue.
- The exit code is always 2, which is the exit code emitted from the Go runtime when an unhandled panic occurs (https://go.dev/src/runtime/panic.go).
- We do not get any information about the panic in the daemon log output, likely because we are failing to drain the stderr pipe before handling the exit status code.

**Comment by nholland94** [comment]
#14434 aims to address the issue where we are not getting the libp2p_helper panic logs in the daemon log output.

**Comment by mrmr1993** [comment]
Fixed in https://github.com/MinaProtocol/mina/pull/14696
