### ISSUE TITLE
Keccak sys-call, iteration 1

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#14393]
- [x] implement syscalls without full constraint support in the MIPS demo
- [x] Keccak must not be used to verify the data
- [x] syscall env can be faked, i.e. on disk. See [rfc](https://github.com/o1-labs/rfcs/pull/30/files) for a in-circuit description.
- [x] Merge with @rbonichon work on the CLI

The end goal is to be able to use syscalls with sysRead and sysWrite for the pre-image oracle

**Comment by stevenpack** [comment]
Howdy OP-nation 👋 . Some great progress over here at **O(1) Labs** in the last 2 weeks. 🔥 

1. Folding [landed](https://github.com/o1-labs/proof-systems/pull/1285) in our Kimchi proof system -- it is being integrated into zkVM now. I love how succinct this API is.

![image](https://github.com/MinaProtocol/mina/assets/2358881/31859948-dd0d-4ed3-a413-73cd17bbbede)

![image](https://github.com/MinaProtocol/mina/assets/2358881/d6e39e48-5072-495e-985f-2420bd05a216)

2. We're loading the `op-program`! That means we can read and parse all the instructions exported by Cannon. We're not successfully executing it e2e yet, so there are some instructions in the ISA we're debugging, but this is a good place to be.

3. As part of that execution, we need to support syscalls for loading block data from the preimage. Check out the very detailed design [here](https://github.com/o1-labs/rfcs/pull/30/files#diff-3bf27ab65b58efa5da01a8c774b07c39a5fb4cd14146c682334d0e43e0940123)

Our next goals 🎯  are:
- Completely execute the op-program (with mocked data)
- Completely execute with real pre-image data (sourced via syscalls)
- Completely execute with folded proof
- Capture first performance numbers

Onwards! 🏃‍♀️ 🏃‍♂️

**Comment by dannywillems** [comment]
Closing. Implementation in proof-systems will differ. RFC is being reviewed.
