### ISSUE TITLE
High memory usage in testworld and berkeley testnets

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#14406]
Gareth reports 120Gb used in `berkeley` daemon, running in the cloud, leading to an OOM crash.

A testworld seed is using 25Gb, according to `kubectl top pod`.

**Comment by garethtdavies** [comment]
I did grab a screenshot from htop for this excessive memory usage. Seems related to the network activity as memory usage grows far less quickly now:

![image](https://github.com/MinaProtocol/mina/assets/135382/71c74d30-0600-4b85-894b-05fa230a9187)

**Comment by deepthiskumar** [comment]
RFC for memory usage improvement- https://github.com/MinaProtocol/mina/pull/14675
