### ISSUE TITLE
OCaml polymorphic equal (=) should not be used when possible

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#1442]
OCaml's polymorphic equality, written `=`, doesn't always give the expected result, and may be less efficient that a module-specific equality. Better to use the module-specific version to avoid such problems.

**Comment by bkase** [comment]
I think we've been avoiding `=` pretty well. Do you have specific places in the codebase that you've caught us using this?

**Comment by psteckler** [comment]
For example, in `src/lib/kademlia/membership.ml`, some of the tests use `=` and `<>` on complex structures.
