### ISSUE TITLE
Catchup slow on testworld

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#14445]
* More than an hour
* Seeing validation timeouts on blocks

Happened on Oct 27:

* Finished around 11:45 am UTC
* Started around 21:00 UTC of October 26

**Comment by trevorbernard** [comment]
@deepthiskumar could this be a problem with persisted vs non-persisted frontier? Removing the conf directory resolves the syncing issue for some

**Comment by deepthiskumar** [comment]
> @deepthiskumar could this be a problem with persisted vs non-persisted frontier? Removing the conf directory resolves the syncing issue for some

@trevorbernard did you try this around the same time? We saw this when the node had to do a full catchup because its persisted state was far too behind (older than 280 blocks)

**Comment by trevorbernard** [comment]
Unfortunately no, I didn't run into this issue.

**Comment by mrmr1993** [comment]
Testworld has ended. Closing.
