### ISSUE TITLE
User-provided constraints for the FFAdd gate (iteration 2)

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#14460]
- [x] expose `Expr::PolishToken` as a type through the bindings.
  - [x] Figure out how to get  `#[cfg_attr(
    feature = "ocaml_types",
    derive(ocaml::IntoValue, ocaml::FromValue, ocaml_gen::Enum)
)]` to work with enums that have constructor arguments 
  - [x] [Implement rust-side manual PolishToken conversion helper](https://github.com/o1-labs/proof-systems/pull/1527/commits/a164fa85655df69a66979c2e532791e09d5c2e59)
  - [x] Add `decl_type!(w, env, PolishToken => "polish_token");` to `main.ml`
  - [x] [Update ocaml side bindings stubs](https://github.com/MinaProtocol/mina/pull/14730)
- [x]  Use the polish notation form in snarky as the custom gate expression, make the tests pass
- [x] Create `ScalarsMinus`
- [x] replace the flag with an `Option<Expr::PolishToken>`, but just use it as a flag (i.e.`Option.is_some` everywhere we need the boolean), and propagate it through kimchi and pickles.
- [x] write an interpreter for `PolishToken` in OCaml, panic on the complex stuff (caching, conditionals, etc.). 
- [x] Update uses of `Sc.constant_term` and `ft_eval0` to take an optional `custom_gate_type` RPN argument and internally call the interpreter to evaluate the RPN on the witness to return a field element (similar to what's happening in `evaluate` here https://github.com/o1-labs/proof-systems/blob/6233800e9a7dfb031145225492733fc5969e785a/kimchi/src/circuits/expr.rs )
- [x] write a converter [`PolishToken -> Expr` in rust](https://github.com/o1-labs/proof-systems/issues/1376) (so that we can use it in the prover), similarly TODOs on complex stuff
- [x] [get Kimchi side working with user-supplied gate defintion](https://github.com/o1-labs/proof-systems/pull/1526)
- [x] [Use the polish notation form in kimchi as the custom gate expression, make the test pass](https://github.com/o1-labs/proof-systems/pull/1526)
- [ ] Use the polish notation form in pickles as the custom gate expression, make the test pass 
- [ ] demo several different gates with degree at most 4 (as in FFAdd)

**Comment by jspada** [comment]
Interesting (1-on-1) meeting (with Matthew) decision: include powers of alpha inside user supplied RPN gate definition.
