### ISSUE TITLE
Uptime submitter keypair password loaded incorrect

### ISSUE THREAD

**Issue by WayneWayner** [MinaProtocol/mina#14519]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

I used a password with many special characters for UPTIME_PRIVKEY_PASS which results in 

a) without " "

> /entrypoint.d/mina-env: line 2: syntax error near unexpected token `('

b) with " "

> 
> FATAL ERROR
> 
>   ☠  Mina Daemon encountered a configuration error loading uptime submitter keypair.
>   
> The password was incorrect, or the key is corrupted
> Mina process exited with status code 1

To resolve this issue I imported the key with `mina accounts import` and exported it again with a weaker password with `mina accounts export`

Here's the password which caused this error: 
`?09tR(MF<qT#$iFf5T%-`

### Steps to Reproduce

1. generate keypair with `?09tR(MF<qT#$iFf5T%-` as password
2. use this keypair as uptime key
3. check logs

### Expected Result

Better password reading mechanism

### Actual Result

Mina daemon won't start because it can't handle the uptime key.

### How frequently do you see this issue?

Rarely

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
-
```

**Comment by amc-ie** [comment]
This is a shell issue, the string should be surrounded by single quotes and this should resolve the issue you are seeing. Please reopen if you are still having issues.
