### ISSUE TITLE
mina.service stopping

### ISSUE THREAD

**Issue by uniqnodes** [MinaProtocol/mina#14514]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

When installing Debian Packages on user (not root), the installer installs the "mina.service" sysdemd service on "user" (/usr/lib/systemd/user/mina.service). As a result, when SSH access is disabled (when the user is logged out), the services running on this user also stop. This was detected on "mina-berkeley=2.0.0rampup6-4061884". Its behavior in other versions is unknown.

### Steps to Reproduce

1. Configure debian packages:
`echo "deb [trusted=yes] http://packages.o1test.net/ focal rampup" | sudo tee /etc/apt/sources.list.d/mina-rampup.list`
2. Install daemon: 
`sudo apt-get install -y mina-berkeley=2.0.0rampup6-4061884`
3. Reload daemon services and start Mina
`systemctl --user daemon-reload`
`systemctl --user restart mina`

-> mina.service started working.
-> mina.service stops when SSH connection is lost

### Expected Result

mina.service should continue working when the SSH connection is lost.

### Actual Result

mina.service stops when SSH connection is lost

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
-
```

### Additional information

I solved this problem with the "sudo loginctl enable-linger <USER>" command, which allows user services to continue even when the user logs off.
As a solution, either mina.service should run on root (/etc/systemd/system/), or the "Lingering" feature should be added to the script.

**Comment by amc-ie** [comment]
Triage update: PE team to investigate.

**Comment by amc-ie** [comment]
Thanks for logging this and suggesting a path forward. This is primarily a `systemd` issue rather than a mina one; there are several solutions to keep processes running after ending an SSH session (like the one you mentioned) which can be utilised. We do not wish to recommend specific system level configuration changes, as such the easiest and least invasive approach as you have recommended is to use another approach (such as `screen` for example).
