### ISSUE TITLE
ZK-STARKs

### ISSUE THREAD

**Issue by mina10B** [MinaProtocol/mina#14510]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

ZK-STARK is an acronym for Zero-Knowledge Scalable Transparent Argument of Knowledge. ZK-STARKs are similar to ZK-SNARKs, except that they are:

### Steps to Reproduce

  why not use stark as scalable solution you claim mina is scalable how 

### Expected Result

why not use stark as scalable solution you claim mina is scalable how 

### Actual Result

why not use stark as scalable solution you claim mina is scalable how 

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

High

### Status

```shell
why not use stark as scalable solution you claim mina is scalable how
```

### Additional information

why not use stark as scalable solution you claim mina is scalable how

**Comment by mina10B** [comment]
can explain mina is scalable now or needed STARK instead of SNARK

**Comment by emberian** [comment]
Kimchi seems to be doing pretty good as a proof system. This is a discussion question, closing issue.
