### ISSUE TITLE
losing my winning slot 9410, and changes/jump into new winning slot 10847

### ISSUE THREAD

**Issue by scraido** [MinaProtocol/mina#14523]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Before this when my 2 node has the same winning slot number, i also experiencing, when i just went to create a block, that opportunity dissappear, and it's jump/changes to a new winning slot,,

### Steps to Reproduce

1. Not sure how to reproduce it, this one is came from the first version, and now happening again on this new rampup 6 version
2.
3.
...

### Expected Result

I should try to produce a block on slot that i winning 9410, either Canonical or not, not just skip it to another slot

### Actual Result

When i about to produce a block it skipped to the other winning slot

Here is the slot i'm about to produce, that skip to a new winning slot;
![280524544-7b9d15dd-4383-4978-bb84-467137812370](https://github.com/MinaProtocol/mina/assets/44559893/823f1462-dcea-43bd-8156-d4ced9ce8bf9)

Here is the new winning slot 10847;
![Screenshot_20231107-061401](https://github.com/MinaProtocol/mina/assets/44559893/7effb3c0-42d1-4801-9971-ca39f20d7cbd)

### How frequently do you see this issue?

Rarely

### What is the impact of this issue on your ability to run a node?

Low

### Status

```shell
I still couldn't copy pasting it from android, gonna get my laptop fix a.s.a.p 🙏
```

### Additional information

I still didn't know why it skip mine, as i use server specs. beyond the minimum and still hv a lot of ram and disk, also i hv 32TB Traffic with unlimited incoming, and hv sets firewall too 🤔

**Comment by scraido** [comment]
Found it slot 9410 or 2270 is missing

**Comment by ghost-not-in-the-shell** [comment]
The log is stale. But according to what I saw on the network, here's a possible guess of what has happened:
vrf evaluation is actually right, and block is being produced, but unluckily the block production takes too long (which is common during the stress test) and the produced block passes its slot and gets dropped by the node. And by the time vrf gets called again, it's picking the best tip block (which is the parent block of the orphaned), that's why in the `Next block will be produced in` field that it says `(Generated from consensus at slot: 9409)`.

**Comment by ghost-not-in-the-shell** [comment]
I actually find the orphaned block in `mina-rejected-block`, so I think my guess is probably right. The block gets produced but it's dropped immediately. And by the time vrf gets called, it's picking the parent block to get the consensus state.

**Comment by mrmr1993** [comment]
The root cause seems to be as described in https://github.com/MinaProtocol/mina/issues/14613. See the concrete error message in #14574.
