### ISSUE TITLE
Consider authenticating connections to the client RPC port

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#1452]
Maybe with a simple shared static secret? We only listen on localhost anyway. There's no confidentiality in our connections so I'm not sure how much it gets us. At the very least it will stop other users on the system from tampering (unless they can see the config dir which stores the secret).

**Comment by jkrauska** [comment]
Nuance: With snark coordination, we bind and listen to all IPs, but then drop connections that aren't whitelisted.    In theory it would be nice to be able to remotely initiate transactions, etc -- so opening up and providing some security could be nice.   Would probably best be implemented as a separate port with TLS.
