### ISSUE TITLE
Store Null value for parent_id in blocks table

### ISSUE THREAD

**Issue by olton** [MinaProtocol/mina#14533]
# Testworld 2.0, Archive Node

### Description

The archive process stores the `null` value for `parent_id` in the `blocks` table for blocks:

`3NLyQbP2cukXqupKTagdB1JbUe1xydJBL5hLSjiQmj4Gi3BG9TNf`
`3NL7z8fJNRyyf9MYDuBZkv7fPmpQk4d8H4qmodHJ8JixByBrCLUT`

for these blocks stored parent_has `3NKPVUEtgDquieh8p4y8D7daFwkZErKaDt3WcxyZVt4s1NiWE7SN` for not existing block.

Apparently, the archive process missed a block when writing to the database.

**Comment by vfrsilva** [comment]
Hi @olton, as far as I know, this is a known issue that can also happen in the mainnet and requires intervention from the operator. Were you able to recover from this state?

**Comment by olton** [comment]
> Hi @olton, as far as I know, this is a known issue that can also happen in the mainnet and requires intervention from the operator. Were you able to recover from this state?

I removed `.mina-config` folder and restarted node. This re-committed the blocks to the archive.

**Comment by psteckler** [comment]
The `testworld` blocks are being uploaded to Google Cloud. The names are of the form
```
testworld-2-0-<height>-<state-hash>.json
```
They're available at https://console.cloud.google.com/storage/browser/mina_network_block_data.

**Comment by vfrsilva** [comment]
There is an environment variable in the script that sets the network (testworld-2-0 in this case). The node should be able to automatically collect the correct blocks for its network due to this.

**Comment by amc-ie** [comment]
Hi Olton, did this resolve the issue you were having?

**Comment by amc-ie** [comment]
Closing this as part of triage, please reopen if you have been unable to resolve this or are seeing additional issues, thank you!

**Comment by olton** [comment]
> Hi Olton, did this resolve the issue you were having?

Yes, currently I use a modified version of download_missed_blocks.sh
