### ISSUE TITLE
Make documentation of sub libraries friendlier

### ISSUE THREAD

**Issue by dannywillems** [MinaProtocol/mina#14535]
Mina sublibraries should be documented and the documentation should be part of the Mina developer website.
The documentation can be built using [odoc](https://github.com/ocaml/odoc), and we can generate the HTML using `dune build @doc`. Integrating on the Mina developer portal should be straightforward, simply copying the generate HTML files.

The requirements would be to be able to run `dune build @doc` in each sublibraries of `src/lib`.

It generates documentation like [this](https://nomadic-labs.gitlab.io/cryptography/ocaml-bls12-381/bls12-381/).
Documentation can also be published on a subdomain of github, like `minaprotocol.github.io`.

**Comment by barriebyron** [comment]
@MartinMinkov are you a good person to start with, or who is the right person to weigh in on this initiative? I really like the way the API reference docs are auto-generated for o1js and IIRC you might have knowledge to share
