### ISSUE TITLE
bug: docker release 1.4.0 invalid

### ISSUE THREAD

**Issue by Nasfame** [MinaProtocol/mina#14545]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

got the docker image from: https://github.com/MinaProtocol/mina/releases/tag/1.4.0

```
docker run minaprotocol/mina-daemon:1.4.0-c980ba8-CODENAME-mainnet
Unable to find image 'minaprotocol/mina-daemon:1.4.0-c980ba8-CODENAME-mainnet' locally
docker: Error response from daemon: manifest for minaprotocol/mina-daemon:1.4.0-c980ba8-CODENAME-mainnet not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

### Steps to Reproduce

```
docker run minaprotocol/mina-daemon:1.4.0-c980ba8-CODENAME-mainnet
```
...

### Expected Result

No error

### Actual Result

Unable to find image 'minaprotocol/mina-daemon:1.4.0-c980ba8-CODENAME-mainnet' locally
docker: Error response from daemon: manifest for minaprotocol/mina-daemon:1.4.0-c980ba8-CODENAME-mainnet not found: manifest unknown: manifest unknown.
See 'docker run --help'.

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
`
 mina client status
mina aborted!
Don't know how to build task 'client' (See the list of available tasks with `mina --tasks`)
/usr/bin/mina:53:in `block (2 levels) in <main>'
/usr/bin/mina:26:in `block in <main>'
/usr/bin/mina:25:in `instance_eval'
/usr/bin/mina:25:in `<main>'
(See full trace by running task with --trace)

```
```


### Additional information

_No response_

**Comment by garethtdavies** [comment]
You need to replace `CODENAME` with the distro you want. So `focal`, `buster` or `bullseye`.

**Comment by Nasfame** [comment]
ok!
