### ISSUE TITLE
[Archive Migration testing] Integration with rosetta and daemon node

### ISSUE THREAD

**Issue by dkijania** [MinaProtocol/mina#14555]
Extenston of second stage of archive migration testing is integration with rosetta and mina deamon. Goal of this level is to assure correct behavior on real data along with correct integration with mentioned components.

#### Design

1. Import mainnet data from existing archives.
2. Perform migration with --end-global-slot  (it can be also randomized)
3. Pick up some addresses which balances should be verified:
     a) addresses defined in genesis ledger and not accessed later
     b) addresses not defined in genesis ledger but created later
     c) addresses defined in genesis ledger and updated later
4. Run mina daemon and mina-archive node on migrated data. Produce couple of block and send some transactions. There should be no errors

**Comment by deepthiskumar** [comment]
@dkijania please split this into two tickets- one for daemon test and one for rosetta
