### ISSUE TITLE
No snark work included on devnet

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#14572]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Devnet has empty blocks, with zero coinbase transactions for some time.

### Steps to Reproduce

N/A

### Expected Result

N/A

### Actual Result

N/A

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Low

### Status

```shell
Devnet
```

**Comment by amc-ie** [comment]
Hi Gareth, thank you for raising this! This should now be resolved; the issue was in relation to images used for our hosted snarkworkers which have since been redeployed with the 1.4.0 production images. Many thanks! :)
