### ISSUE TITLE
Unit test state export for HF

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#14709]
Implement a bash script that:

1. Takes two binaries as parameters: `mina-mainnet` and `mina-berkeley`
2. Launches a local single-node network with a mainnet-like ledger, with a single block-producer to which all of the stake is delegated (using `mina-mainnet` binary)
3. Some transactions are sent to the node
4. After two epochs node is restarted with slot parameters (to end tx inclusion and to end block production)
5. Some transactions are sent to the node (it's checked that they are accepted only before a certain slot)
6. It's checked that block production stops at some point
7. Transition root is extracted into a new runtime config
8. Runtime config is converted with a script (to have only ledger hashes in the config)
9. Node is shutdown and restarted with `mina-berkeley` and the config from previous step
10. Node runs for an epoch, some transactions are sent

To shorten the time which it would take for the script to run, it's suggested to configure the node with a very low `k` and a block window of 25s.

**Comment by georgeee** [comment]
TODO: test block creation with `k=3` and scan state size log equal to `2`
