### ISSUE TITLE
Archiving blocks with zkApp transactions is slow

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#14758]

**Comment by deepthiskumar** [comment]
Here’s an example block `3NKVK32pgy9h5nkmAGtHrRgmVEzKGsxWr5sgRPgvMPNyWhQ7Aq2E` that took ~17mins to archive on archive-1. This block has 20 zkApp transactions and 98 signed commands (payments).

**Comment by amc-ie** [comment]
Triage update: initial investigation has determined the root cause, working on a fix now.

**Comment by trevorbernard** [comment]
> Triage update: initial investigation has determined the root cause, working on a fix now.

@amc-ie What is the root cause?
