### ISSUE TITLE
Our Ocamlformat linter should automatically wrap doc comments

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#1476]
We use `ocamlformat` to lint our code. Normally, it would not wrap comments. However, since we are documenting our code more, we should have it. We just need to add the flag argument `--wrap-comments`. So the linting command that we should execute is `ocamlformat --wrap-comments`.

It would probably tedious to fix all comments in our codebase.

**Comment by mrmr1993** [comment]
`--wrap-comments` tries to wrap *everything* in a comment, including ocamldoc `{[ ... ]}` code blocks. We'll want that fixed before we turn this on :cry:
