### ISSUE TITLE
modernize or remove ensure_testnet_id_still_good

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#14807]
this is the code behind the `force_updates compile time config, which is always `false` (except for an unused profile). we can remove that too if we go that route.

it is unused since at least 2018-10-17.

alternatively, we could update this mechanism to do some much more robust check- perhaps accounting for emergency forks? currently it compares the commit ID to a file it polls from our infra over HTTP. it's unclear what this does that the chain ID doesn't, except some kind of liveness- ensuring node operators update on a minimum cadence.

**Comment by emberian** [comment]
additionally, the `force_updates` compile time config. 

it is unused since at least 2018-10-17.

alternatively, we could update this mechanism to do some much more robust check- perhaps accounting for emergency forks?

**Comment by mrmr1993** [comment]
This was fixed by https://github.com/MinaProtocol/mina/pull/15837. Closing.
