### ISSUE TITLE
Berkeley migration work flow

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#14820]
The berkeley archive data migration is done using 2 app: `berkeley_migration` and `replayer --zkapp-migration-mode`/`berkeley_account_tables`. 

The input for `berkeley_migration` app is mainnet db + migrated db, the output would be migrated db
The input for `replayer --zkapp-migration-mode`/`berkeley_account_tables` app is migrated db + checkpoint file, and the output would be some new checkpoint files + migrated db being patched (fill in the accounts_created and accounts_accessed table)

To migrate mainnet data, we first run the `berkeley_migration` app and then runs `replayer --zkapp-migration-mode`/`berkeley_account_tables` app.

The ideal way to do the migration is doing it incrementally:
1. do initial migration and upload the migrated db and checkpoint file to cloud server
2. setup a con job that pull from mainnet database everyday and migrate the new data and upload the db and checkpoint file
3. just before hard fork, we could migrate the last few blocks manually

Next` I would going into details for the above steps:

### Initial migration
-  download a mainnet archive dump, and loading it into PostgreSQL
-  create a new, empty database using archive schema
-  run `berkeley_migration` app against the mainnet and new databases (without `--end-global-slot` so that we only migrates canonical blocks)
-  run `replayer --zkapp-migration-mode`/`berkeley_account_tables` with the `--checkpoint-interval` set to some suitable value (perhaps 100), and starting with the original mainnet ledger (should we convert this into berkeley format?) in the input file
- setup 2 google buckets to store migration data
  - a bucket to store migrated-so-far database dumps
  - a bucket to store checkpoint files
-  use `pg_dump` to dump the migrated database, upload it
-  upload the most recent checkpoint file

### Create a cron job that incrementally migrate blocks on mainnet daily, the cron job would work as follows
- pull latest mainnet archive dump, load into PostgresQL
- pull latest migrated database, load into PostgreSQL
- pull latest checkpoint file
- run first `berkeley_migration` app against the two databases (without `--end-global-slot` so that we only migrates canonical blocks)
- run `replayer --zkapp-migration-mode`/`berkeley_account_tables`, using the downloaded checkpoint file; checkpoint interval should be smaller (perhaps 50), because there are typically only 200 or so blocks in a day
- upload migrated database dump to the bucket
- upload most recent checkpoint file to the bucket

### Just before fork, when we know what the hard fork block would be
- download the mainnet db dump, load it into PostgresQL
- download the most recent migrated database, load it into PostgresQL
- download the most recent checkpoint file
- run `berkeley_migration` app against the two database (with `--end-global-slot` to be the global-slot of hard fork block + 1)
- run the second migration application using the most recent checkpoint file (with `target_epoch_ledgers_state_hash` to be the state hash of direct children of the hard fork block, because the replayer would apply blocks up to that `state_hash`, not including that block)

**Comment by deepthiskumar** [comment]
Documented in HF runbooks
