### ISSUE TITLE
Maintain mainnet archive jobs 

### ISSUE THREAD

**Issue by dkijania** [MinaProtocol/mina#14890]
After trying to resolve issues with replayer and mainnet database i stumble on many not working things like:

- missing_blocks_auditor 
- replayer_transaction_service
- replayer
- failing inserts to db.

We need to first bring back all alerts and jobs which provides useful information about database before medling with db state using various updates. This issue is track maintenance work:
TODO:

- [ ] Fix missing block auditor job setup which cannot connect to mainnet db but falsely report no errors
- [ ] Fix replayer run on mainnet db
- [ ] Fix replayer transaction job setup which cannot connect to mainnet db

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [ ] **Scenario 1: Fix missing block auditor job setup**
  - Given that the missing block auditor job is not able to connect to the mainnet database
  - When the missing block auditor job is executed
  - Then it should be able to connect to the mainnet database without reporting any errors

- [ ] **Scenario 2: Fix replayer run on mainnet db**
  - Given that the replayer is not running properly on the mainnet database
  - When the replayer is executed on the mainnet database
  - Then it should run successfully without any issues

- [ ] **Scenario 3: Fix replayer transaction job setup**
  - Given that the replayer transaction job is not able to connect to the mainnet database
  - When the replayer transaction job is executed
  - Then it should be able to connect to the mainnet database without any errors

**Comment by deepthiskumar** [comment]
@stevenplatt to check if the replayer crashed due to large number of blocks/transactions. @stevenplatt to run it manually if that's the case

**Comment by ghost-not-in-the-shell** [comment]
See #15055 for suggested fix
