### ISSUE TITLE
Add o1js-stub compile job to CI to make sure o1js dependencies can compile in Mina repo

### ISSUE THREAD

**Issue by MartinMinkov** [MinaProtocol/mina#14906]
As part of finishing https://github.com/o1-labs/o1js/issues/1096, we need to make sure that the new [o1js-stub](https://github.com/MinaProtocol/mina/tree/develop/src/lib/o1js_stub) can always be compiled in the Mina repo. This gives o1js a level of confidence that all OCaml dependencies can be compiled upstream, before being consumed by o1js.

**Comment by mrmr1993** [comment]
The unit tests CI job includes building all targets in `src/lib`, so this is now checked automatically.
