### ISSUE TITLE
Investigate performance issues with Arkworks v0.4.0

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#14970]
After upgrading arkworks to the latest version, we found out it introduces a performance regression (e.g. proving Mina's snark work is ~2x slower, stats [here](https://github.com/o1-labs/proof-systems/pull/1670#issuecomment-1876221140)). Arkworks v0.4.0 is a dependency of the zkVM, so it is also needed beyond Mina's context.

In this task, we will do an investigation to figure out the root cause of the regression. Concretely, there are [218 git commits](https://github.com/arkworks-rs/algebra/compare/v0.3.0...v0.4.2) between the release we use and the latest, which an engineer could plausibly bisect through to find the source of the regression, and hopefully then fix. 

This investigation should be time-boxed to a 1 week.

**Comment by volhovm** [comment]
Regression addressed (fixed) here: https://github.com/MinaProtocol/mina/pull/15940
