### ISSUE TITLE
The output of state export is not consistent in "previous_state_hash" and "previous_height"

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#15070]
The generated fork state contains for the following field:
```
    "fork": {
      "previous_state_hash": "3NLiejEBoNuXjgC59Jt8PUvvqNbPxgNFZBU4a9ZgrpNzzdXPYPbb",
      "previous_length": 368,
      "previous_global_slot": 2326
    }
```
The length and global_slot of "previous_state_hash" is different from what we have here.
It turns out that the "previous_length" and "previous_global_slot" corresponds to next block's length and global_slot.

**Comment by deepthiskumar** [comment]
@ghost-not-in-the-shell I think this is due to incorrect state being forked off of. Is the new one as expected:
```
   "fork": {
      "previous_state_hash": "3NLKED8SDWLEa6aEZXvJ52EuZoUrhB3Hj9jTUpmjHuP6yes2PcWY",
      "previous_length": 366,
      "previous_global_slot": 2319
```

**Comment by ghost-not-in-the-shell** [comment]
No, the `previous_state_hash` is still from the previous block

**Comment by deepthiskumar** [comment]
So state hash is from previous block but rest is from block at slot 2319. @Sventimir was this the expectation?

**Comment by deepthiskumar** [comment]
Remove `previous` from all the fields and have the following -
```
  "fork": {
      "state_hash": "3NLiejEBoNuXjgC59Jt8PUvvqNbPxgNFZBU4a9ZgrpNzzdXPYPbb",
      "blockchain_length": 368,
      "global_slot_since_genesis": 2326
    }
```

**Comment by emberian** [comment]
@deepthiskumar so the new semantics is that `state_hash` is the state hash to evolve from, but `blockchain_length`and `global_slot_since_genesis` specify the _exact_ parameters for the fork, not to be incremented?

**Comment by mrmr1993** [comment]
> Remove `previous` from all the fields and have the following -

This is at odds with the change you asked for [here](https://github.com/MinaProtocol/mina/pull/15086). The global slot really is the `previous_global_slot_since_genesis`, and making this change is actively harmful.

**Comment by mrmr1993** [comment]
Fixed by https://github.com/MinaProtocol/mina/issues/15070 and https://github.com/MinaProtocol/mina/pull/15109.
