### ISSUE TITLE
Fix protocol constants 

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#15085]
https://github.com/MinaProtocol/mina/pull/14776#issuecomment-1939536688 pointed out that the protocol constants `to_input` function is missing the `grace_period_slots` field that was added in that PR. We should fix this. Luckily, this issue doesn't introduce a vulnerability in the snark from my understanding, but would cause the circuit to fail to compile if we were ever requesting the protocol constants as a private input.

**Comment by mrmr1993** [comment]
Fixed in https://github.com/MinaProtocol/mina/pull/15690.
