### ISSUE TITLE
Cron job for state dump

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#15099]
Cron job to start dumping HF state right after stop-transaction-slot
Need the following:
* Cron job requirements
    * Connect to a non-public seed in the cluster and check if it is synced 
    *  Query `fork_config` using GraphQL from the seed, save the json data in a file and upload it into a gcloud bucket
    *  The cron job needs to start uploading state dumps after stop-transaction slot and end after stop-network slot (the last one should be after stop-network slot). So this could an hourly recurring job

**Comment by SanabriaRusso** [comment]
Development of a testing prototype has been carried out in gitops-infrastructure repository: https://github.com/o1-labs/gitops-infrastructure/tree/lsanabria/bootstrap-demo/charts/mina-state-dump

The current implementation is already deployed on the `o1labs-hf-test-post-fork-run-3` namespace and produces dumps that are uploaded to corresponding GCP bucket/directory (latter changes with testnet name) Example: https://storage.googleapis.com/o1labs-gitops-infrastructure/o1labs-hf-test-post-fork-run-3/o1labs-hf-test-post-fork-run-3-state-dump-20240221_154425.json
