### ISSUE TITLE
Test mainnet configurations for berkeley

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#15102]
* Run a private network (with berkeley build) with mainnet configurations (mainnet.mlh), and an updated genesis timestamp (to not conflict with current mainnet) and replay a transaction from current mainnet (Not creating a new transaction in this network to avoid being replayed on current mainnet)
* Test ledger hardware?
* Test other signing libraries?

**Comment by shimkiv** [comment]
Hey @deepthiskumar, I'm picking it up. Can you please share if we already have the corresponding build (link to CI job if any) or I'll need to build it myself? And who I can contact with the replying questions?
Thank you.

**Comment by shimkiv** [comment]
The following configuration works well 🎉 
- Mina blockchain is formed using artefacts built with the `mainnet` Dune profile, `mainnet` genesis configuration is in use, `berkeley` Mina repository branch (rev:[85fc613](https://github.com/MinaProtocol/mina/commit/85fc61311b605f96ffc6d3440bf2b30dc584b06f))
- Ledger `Nano X` (firmware: `2.2.3`)
- Ledger `Nano S` (firmware: `2.1.0`)
- Ledger Mina App `v1.0.8`
- Auro Wallet `v2.2.13` (custom build to match the `networkID`)

**Comment by shimkiv** [comment]
Value transfers using latest [mina-signer](https://www.npmjs.com/package/mina-signer) `v3.0.0` work well 🎉

**Comment by shimkiv** [comment]
`o1js` also works 🎉 
Fixes required though:
- https://github.com/o1-labs/o1js/pull/1437
- https://github.com/o1-labs/o1js-bindings/pull/244
