### ISSUE TITLE
Implement detailed checks in the hard-fork unit test

### ISSUE THREAD

**Issue by georgeee** [MinaProtocol/mina#15127]
In its current implementation, unit test (issue #14709) is checking effect of tx/chain and that the generated runtime config is usable for running a berkeley-backed network

We want to make the following updates:

- Global slot in the fork config
- Height, state hash in the fork config
- Use exactly the scripts you use in your branch to make a new runtime genesis ledger

And whatever comes up on our mind (from analysis of the HF fork runs 1 and 2) as a useful check that an be put into unit test.

**Comment by georgeee** [comment]
In addition to what's currently being checked, also check that:

1. Fork config has correct height, slot and state hash (referring to the last block happening **before** slot-tx-end)
2. Newly launched network has first block having height +1 of height from the previous step

**Comment by deepthiskumar** [comment]
Some additional tests for edge cases re picking stop-transaction slot:
* Last slot of an epoch
* First slot of an epoch
* A slot within first slots-per-epoch/3 (within epoch seed update range)
* A slot after the first slots-per-epoch/3

**Comment by georgeee** [comment]
Tests described in this task were implemented as part of HF test that lives in nightly CI.
