### ISSUE TITLE
Figure out what to do with orphaned rosetta PRs

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#15146]
The PRs in question are:
* https://github.com/MinaProtocol/mina/pull/9544
* https://github.com/MinaProtocol/mina/pull/9748
* https://github.com/MinaProtocol/mina/pull/9758
* https://github.com/MinaProtocol/mina/pull/9760
* https://github.com/MinaProtocol/mina/pull/9800
* https://github.com/MinaProtocol/mina/pull/9836
* https://github.com/MinaProtocol/mina/pull/9879
* https://github.com/MinaProtocol/mina/pull/10184
* https://github.com/MinaProtocol/mina/pull/10667

This issue is resolved when we know:
* whether anything necessary for rosetta is sitting unmerged in these PRs
* when those things have been reworked and merged
* when the above PRs have been closed (either as a rework merge, or outright).

**Comment by joaosreis** [comment]
#9544 is still relevant and should be reworked and merged.
I've created an issue (#15154) to track the implementation of #9748 against the current Rosetta node version.
Everything else is either already present in the current main branches or not relevant anymore.

**Comment by joaosreis** [comment]
Correction to the above comment, #9544 is against `compatible` so it was closed as well and another issue (#15155) to track its implementation against current Rosetta node version was created.

**Comment by mrmr1993** [comment]
All PRs addressed. Closing.
