### ISSUE TITLE
Constraints between lookup columns and entry using as joint combiner

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#15168]
- Constraints between lookup columns and entry using as joint combiner the randomness hardcoded
- If we have a “grand witness”, this can be done inside the same constraints function, and afterwards collect only the corresponding ones.
- Maybe this requires a refactor in the `write/read_if` interface, to add dynamically the constraints depending on the type of step run; and later each of them is mapped to each instance type and the actual numerators are updated.

**Comment by querolita** [comment]
This probably is Folding work instead
