### ISSUE TITLE
Add the missing lookups

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#15176]
- On MIPS side, mainly about memory checks: This is a type of under-constraining. Detect them and include them.
- On MIPS side: check if range-check to check we are not time travelling is being performed or not. This requires to split the step number into 4 chunks of 16 bits.
- On Keccak side: check if inter-step channel needs to check also that the steps are subsequent (not a full range check, but just step + 1).

**Comment by mrmr1993** [comment]
Not an issue in this repo. Closing.
