### ISSUE TITLE
Assert the relationship between feature flags and verification key

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#15237]
In some circuits with inductive rules supporting different subsets of custom gates, a malicious prover could set the flags corresponding to the intersection of custom gates required, and effectively disable all of the others. To fix this problem we need to check that the feature flags given correspond to the commitments in the verification keys, ensuring that there is no flexibility in their choice while also maintaining soundness.

**Comment by mrmr1993** [comment]
Done in https://github.com/MinaProtocol/mina/pull/15233. Closing.
