### ISSUE TITLE
Release 1.4.1

### ISSUE THREAD

**Issue by canutodev** [MinaProtocol/mina#15336]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

after the update I get these errors:
● mina.service - Mina Daemon Service
     Loaded: loaded (/usr/lib/systemd/user/mina.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2024-03-16 01:42:41 UTC; 5s ago
    Process: 4811 ExecStart=/usr/local/bin/mina daemon --peer-list-url ${PEERS_LIST_URL} --log-level ${LOG_LEVEL} --file-log-level ${FILE_LOG_LEVEL} $EXTRA_FLAGS (code=exited, status=1/FAILURE)
   Main PID: 4811 (code=exited, status=1/FAILURE)

Mar 16 01:42:41 Ubu2004 systemd[871]: mina.service: Failed with result 'exit-code'.

it restarts continuously.

### Steps to Reproduce

I followed the official documentation for a snark-workers node, but after the update it no longer worked

### Expected Result

that it works normally

### Actual Result

it does not work

### Daemon version

Version 1.4.1

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
Error: Unable to connect to Mina daemon.
- The daemon might not be running. See logs (in `~/.mina-config/mina.log`) for details under the host:127.0.0.1.
  Run `mina daemon -help` to see how to start daemon.
- If you just started the daemon, wait a minute for the RPC server to start.
- Alternatively, the daemon may not be running the RPC server on (127.0.0.1 8301).
  If so, add flag `---daemon-port` with correct port when running this command.
```

### Additional information

result mina client export-logs:Error: Unable to connect to Mina daemon.
- The daemon might not be running. See logs (in `~/.mina-config/mina.log`) for details.
  Run `mina daemon -help` to see how to start daemon.
- If you just started the daemon, wait a minute for the GraphQL server to start.
- Alternatively, the daemon may not be running the GraphQL server on http://localhost:3085/graphql.
  If so, add flag --rest-server with correct port when running this command.
Error message: (Unix.Unix_error "Connection refused" connect 127.0.0.1:3085)

**Comment by canutodev** [comment]
> ### Preliminary Checks
> * [x]  This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
> * [x]  This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions
> 
> ### Description
> after the update I get these errors: ● mina.service - Mina Daemon Service Loaded: loaded (/usr/lib/systemd/user/mina.service; enabled; vendor preset: enabled) Active: activating (auto-restart) (Result: exit-code) since Sat 2024-03-16 01:42:41 UTC; 5s ago Process: 4811 ExecStart=/usr/local/bin/mina daemon --peer-list-url ${PEERS_LIST_URL} --log-level ${LOG_LEVEL} --file-log-level ${FILE_LOG_LEVEL} $EXTRA_FLAGS (code=exited, status=1/FAILURE) Main PID: 4811 (code=exited, status=1/FAILURE)
> 
> Mar 16 01:42:41 Ubu2004 systemd[871]: mina.service: Failed with result 'exit-code'.
> 
> it restarts continuously.
> 
> ### Steps to Reproduce
> I followed the official documentation for a snark-workers node, but after the update it no longer worked
> 
> ### Expected Result
> that it works normally
> 
> ### Actual Result
> it does not work
> 
> ### Daemon version
> Version 1.4.1
> 
> ### How frequently do you see this issue?
> Always
> 
> ### What is the impact of this issue on your ability to run a node?
> Blocker
> 
> ### Status
> ```shell
> Error: Unable to connect to Mina daemon.
> - The daemon might not be running. See logs (in `~/.mina-config/mina.log`) for details under the host:127.0.0.1.
>   Run `mina daemon -help` to see how to start daemon.
> - If you just started the daemon, wait a minute for the RPC server to start.
> - Alternatively, the daemon may not be running the RPC server on (127.0.0.1 8301).
>   If so, add flag `---daemon-port` with correct port when running this command.
> ```
> 
> ### Additional information
> result mina client export-logs:Error: Unable to connect to Mina daemon.
> 
> * The daemon might not be running. See logs (in `~/.mina-config/mina.log`) for details.
>   Run `mina daemon -help` to see how to start daemon.
> * If you just started the daemon, wait a minute for the GraphQL server to start.
> * Alternatively, the daemon may not be running the GraphQL server on http://localhost:3085/graphql.
>   If so, add flag --rest-server with correct port when running this command.
>   Error message: (Unix.Unix_error "Connection refused" connect 127.0.0.1:3085)

It wasn't a 1.4.1 issue

**Comment by amc-ie** [comment]
Thank you kindly for this, it is very much appreciated.
