### ISSUE TITLE
Mina 1.4.1 stable daemon repeatedly crashing 

### ISSUE THREAD

**Issue by lampardlamps** [MinaProtocol/mina#15391]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

journal output:
```Mar 27 10:44:43 ubuntu-32gb-hel1-1 mina[105131]: 2024-03-27 10:44:43 UTC [Warn] Shutdown before Coda instance was created, not saving a visualization
Mar 27 10:44:43 ubuntu-32gb-hel1-1 mina[105131]:   ☠  Mina Daemon crashed.
Mar 27 10:44:43 ubuntu-32gb-hel1-1 mina[105131]:    The Mina Protocol developers would like to know why!
Mar 27 10:44:43 ubuntu-32gb-hel1-1 mina[105131]:     Please:
Mar 27 10:44:43 ubuntu-32gb-hel1-1 mina[105131]:       Open an issue:
Mar 27 10:44:43 ubuntu-32gb-hel1-1 mina[105131]:         <https://github.com/MinaProtocol/mina/issues/new>
Mar 27 10:44:43 ubuntu-32gb-hel1-1 mina[105131]:       Briefly describe what you were doing and attach the crash report /root/.mina-config/coda_crash_report_2024-03-27_10-44-43.555968.tar.gz
Mar 27 10:44:43 ubuntu-32gb-hel1-1 mina[105131]:     
Mar 27 10:44:43 ubuntu-32gb-hel1-1 systemd[903]: mina.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 10:44:43 ubuntu-32gb-hel1-1 systemd[903]: mina.service: Failed with result 'exit-code'.
```

### Steps to Reproduce

These are what I did:
1. Set up a server on Hetzner with 8 vCPU (Intel) and 32 GB RAM
2. install the latest 1.4.1 stable build
3. for the past a few hours it's been continuously crashing
...

### Expected Result

daemon up and running

### Actual Result

crashing 

### Daemon version

mina-mainnet=1.4.1-e76fc1c

### How frequently do you see this issue?

Sometimes

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
no status
```

### Additional information

[coda_crash_report_2024-03-27_10-43-01.302830.tar.gz](https://github.com/MinaProtocol/mina/files/14772097/coda_crash_report_2024-03-27_10-43-01.302830.tar.gz)

**Comment by amc-ie** [comment]
Thank you @lampardlamps for raising this issue! Can you give us an idea of how frequently this occurs? Are you seeing any spikes in resource usage also? Thanks again! 🙏

**Comment by lampardlamps** [comment]
> Thank you @lampardlamps for raising this issue! Can you give us an idea of how frequently this occurs? Are you seeing any spikes in resource usage also? Thanks again! 🙏

Hello,
  The daemon never really got started on that server (an intel CPU), so after about a day I had to change to a new server (AMD CPU) and it worked.

**Comment by mrmr1993** [comment]
Closing as stale. If you're still seeing this issue on 3.0.0 or later, please open a new issue.
