### ISSUE TITLE
Ledger hash verification of incremental AN migration on mainnet

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#15586]
Automate to test twice a week or so

**Comment by ghost-not-in-the-shell** [comment]
I verified that my migration and dariusz migration all passes the `berkeley-migration-verifier final` checks. Currently working on a cronjob that verifies our mainnet incremental migration dumps on daily basis. Here's the basic steps:
1. We need a cronjob on mainnet to dump the fork config on seed-5 daily and then we need to generate the new genesis config using either the hard fork pipeline or just using the `generate-genesis-config.sh` to print it out using a mina-daemon docker image
2. Once we have the new genesis config, we could take the most recent mainnet dump and some increment migration dump and do the final migration on it. We need to make sure that the mainnet dump we choose have the fork block in it and we need to mark the blocks after the fork block to be "pending", another thing is that the incremental migration dump should not include the fork block. 

So for the input, the cron job would take a fork-genesis-config.json, a mainnet archive dump and an incremental migration dump, and it would just run the `berkeley-migration-script final` on those 3 input and report the result somewhere.
