### ISSUE TITLE
Devnet/Mainnet dry-run regression testing

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#15581]

**Comment by georgeee** [comment]
**Proposal of testing**

_Pipeline to use:_ https://buildkite.com/o-1-labs-2/hardfork-package-generation

One needs to trigger a custom build for this pipeline, specifying the branch and environment parameters.

For dry run (with PR #15591):

(We probably do not need `DUNE_PROFILE` and `FORKING_FROM_CONFIG_JSON`)

```
CONFIG_JSON_GZ_URL="https://storage.googleapis.com/tmp-hardfork-testing/fork-config-2024-04-25-1512.json.gz"
DUNE_PROFILE="mainnet"
FORKING_FROM_CONFIG_JSON="genesis_ledgers/mainnet.json"
GENESIS_TIMESTAMP="2024-04-25T21:00:00Z"
NETWORK_NAME="mainnet"
PRECOMPUTED_BLOCK_GS_PREFIX="gs://mina_network_block_data/mainnet-pre-hf-dry-run"
```

For devnet:
```
CONFIG_JSON_GZ_URL="https://storage.googleapis.com/tmp-hardfork-testing/devnet_fork_config_apr_09.json.gz"
GENESIS_TIMESTAMP="2024-04-09T21:00:00Z"
NETWORK_NAME="devnet"
```

For mainnet:

(I found this fork config on bucket, not sure who dumped it and if it is correct)

```
CONFIG_JSON_GZ_URL="https://storage.googleapis.com/tmp-hardfork-testing/mainnet-fork-config-4-26.json.gz"
GENESIS_TIMESTAMP="2024-04-27T21:00:00Z"
NETWORK_NAME="mainnet"
```

**Comment by georgeee** [comment]
* [ ] Mainnet (on #15591): https://buildkite.com/o-1-labs-2/hardfork-package-generation/builds/280
* [ ] Devnet (on #15591): https://buildkite.com/o-1-labs-2/hardfork-package-generation/builds/281
* [ ] Mainnet dry run (on #15591): TODO
