### ISSUE TITLE
Run package verification on Fork-pipeline-Test-1 data and update package verification docs

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#15645]

**Comment by svv232** [comment]
this was successfully run with no errors on debian 11. we also have a method for downloading the mina-create-legacy-genesis binary.

we are currently waiting for @dkijania to modify the version of this package so we can retest

**Comment by svv232** [comment]
Version has been modified and tested.

**Comment by deepthiskumar** [comment]
https://github.com/MinaProtocol/mina/pull/15681
