### ISSUE TITLE
Add deletion functionality in ledger implementations

### ISSUE THREAD

**Issue by rbonichon** [MinaProtocol/mina#15742]
Add a `remove` function in  ledger implementations. 

The actual implementation will need to keep track of removed locations that are available for further account allocations (aka creations) through a stack-based data structure.

The main technical subtlety lies in soundly updating hashes for data structures.

Acceptance criteria (basically testing)
- tests cover nominal behaviors and corner cases
- coverage is XX % (all the lines that use the new data structure are covered?)
- if there are no tests, this shouldn't be acceptable

**Comment by submarinec94** [comment]
<img width="1370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0hrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38d33fd77200a4109746c1bd43f694be53bca2c3/Screenshot%202024-07-16%20at%2011.45.56%E2%80%AFAM.png" alt="Screenshot 2024-07-16 at 11.45.56 AM.png" />
correspond to 1 st point - https://github.com/o1-labs/rfcs/pull/51/commits/6851b42c7ed0462b8f89ceb43f851374f13223d0

**Comment by submarinec94** [comment]
some issue --- ? not behaving properly and change needs to be made 

timeline - presumably 2 more days when Richard's back (currently park for now when he's back)

ledger implementation would be ready in august for review 

no dependencies for this task

**Comment by rbonichon** [comment]
Expected landing W32
