### ISSUE TITLE
Add `delete_account`field to `Account_update.Body.Stable.t`type definition

### ISSUE THREAD

**Issue by rbonichon** [MinaProtocol/mina#15829]
See  [this description in the RFC](https://github.com/o1-labs/rfcs/blob/6851b42c7ed0462b8f89ceb43f851374f13223d0/00xx-account-deletion.md#L388-L389)

**Comment by submarinec94** [comment]
related to archive nodes (supposed to be archived) --- other issues can fix this, can come later coz lower priority

**Comment by rbonichon** [comment]
One of the CI issues (namely replayer test not working) most probably depends on solving [this issue](https://github.com/MinaProtocol/mina/issues/15826)

**Comment by rbonichon** [comment]
All unit tests issues in #15832 (updating the expected result), minus the replayer issue above, will be resolved applying the method described in [this document](https://github.com/MinaProtocol/mina/blob/develop/src/lib/transaction_snark/test/README.md)
