### ISSUE TITLE
Correctness: Require Coinbase + k>=parallel scan

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#1730]
It’s important that transactions are proven in the snark before we drop history in the transition frontier or else you have to trust nodes.

We need to either make sure this happens or show me a proof that this isn’t actually an issue.

**Comment by deepthiskumar** [comment]
If we want coinbase in every block then coinbase should be >= prover fee for one `Transaction_snark_work`

**Comment by bkase** [comment]
We definitely should not crash in this situation as this means another user could denial-of-service attack by just offering an expensive snark
