### ISSUE TITLE
configurable number of cores per snark worker

### ISSUE THREAD

**Issue by jkrauska** [MinaProtocol/mina#1764]
When starting a daemon to behave as a 'snark-worker', we currently run 1 subprocess that calls 'coda internal snark-worker'.

The number of subprocesses should be configurable and also have the option to be 0.

In performance testing on machines with many CPUs, we have found that as we add cores to a snark-worker process, we get degrading results.

As a rule of thumb we currently tune openmp for a maximum of 8 cores for snark-workers.

Thus on a 24-core box, we run one 'snark-coordinator' which is a coda daemon which collects snark work to be processed -- it runs the single subprocess snark-worker.  Then we run 2 additional snark-worked processes which point the the daemon RPC port of the 'coordinator' process.

By having a configurable option at run time to specify the number of snark-worker sub-processes, we can have much more fine grained control.

eg. 
On a 24 core box, we could set to 3, and not have to spawn additional worker processes.
or
When we want to do testing of the snark-worker performance, we could maintain a coordinator process with 0 sub-processes and then spin up new workers as needed to A/B test code, etc.

**Comment by mrmr1993** [comment]
This is done, `RAYON_NUM_THREADS` controls this and is configurable in the helm charts. Closing.
