### ISSUE TITLE
bootstrapping - percentage complete / loading bar

### ISSUE THREAD

**Issue by jkrauska** [MinaProtocol/mina#1896]
During bootstrap, it would be helpful to let the client know how far along it is in the bootstrap process.

eg. If there are 400 things to 'learn', and we've collected 200, we are 50% complete.

We should include this sort of data in 'show client status' -- 'bootstrapping_completeness' ?

**Comment by jkrauska** [comment]
[=====----]

**Comment by imeckler** [comment]
Pursuant to a conversation in a protocol meeting -- bootstrapping takes 10s of seconds right now (according to @nholland94) after receiving a block. The thing that takes the longest waiting for the first block to happen. To remedy this situation

1. Request peers' best tip
2. (Less important) add a progress indicator for bootstrapping

**Comment by jkrauska** [comment]
@imeckler 10s of seconds isn't what I've seen.  @bkase any other data from your perspective? @mrmr1993 ?

**Comment by bkase** [comment]
I haven't been measuring too carefully, but I have been noticing it being faster these days. Is this something we can instrument with metrics (via prometheus?)

**Comment by mrmr1993** [comment]
I haven't been measuring closely either, I'm afraid. I'll try and catch the stats when I jump on the next net.

To support Joel's proposal, IMO It would be reassuring (and tell people when they have a problem) if we could show an estimate of how long it should take to bootstrap. It's very frustrating to wait for bootstrap with no feedback, and it doesn't seem like it would take much effort to show the expected maximum wait time in the CLI.

**Comment by jrwashburn** [comment]
I couldn't agree more. No idea if it will ever finish, or if I should abandon, etc.
Local uptime:               23h12m22s
Sync status:                Bootstrap

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
