### ISSUE TITLE
Optimize pushing a new coinbase in blockchain snark

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#2074]
In blockchain snark, we add coinbase to the collection of pending coinbases. We add two coinbases to handle the coinbase-splitting case. When doing so, we hash the two coinbases which has same public key (`Pending_coinbase.Checked.add_coinbase`). Hashing a public key is about 1000 constraints and that could be shared between the two pushes.

**Comment by mrmr1993** [comment]
Hashing is now much more efficient, this is no longer a major consideration. Closing.
