### ISSUE TITLE
prove/verify-payment ux is really clunky

### ISSUE THREAD

**Issue by enolan** [MinaProtocol/mina#2134]
I give instructions in #1853. You have to: make the payment, copy the receipt chain hash output, run `prove-payment`, put the json output in a file, extract the payment json from that output and put it in a separate file, then run `verify-payment`, passing the paths to the two files and the sender's public key. All of that information is in the Merkle proof already, though it doesn't know which of the payments in the list is the one you want to prove.

Proposed better process:
* Send the payment. There is an optional `--generate-proof` flag that will output a proof immediately. If you forget or decide you need to prove later on, `prove-payment` still exists.
* Verify the payment. Rather than passing three parameters, we use the sender public key that is already in the JSON object and we always check the last payment in the Merkle list, since the minimal proof of a payment is a list of the payments up to and including it, plus the hash of the rest of the list.

**Comment by Mixa84** [comment]
Can I ask will this improvement going to be done anytime soon?

**Comment by enolan** [comment]
Probably not, we are focused on getting ready for a public testnet for the
near/medium future.
