### ISSUE TITLE
include the state hash in payment merkle proofs

### ISSUE THREAD

**Issue by enolan** [MinaProtocol/mina#2135]
A proof becomes invalid as soon as the sender account's receipt chain hash changes. If new payments are sent by the sender and included in a block between when the proof is generated and when it's checked, the check will erroneously fail. We should include the state hash in the proofs, and check proofs relative to that state. This will extend the window of validity until the transition that the proof was associated with is removed from a node's frontier.

**Comment by wu-s-john** [comment]
This is addressed in the client storage PR: https://github.com/CodaProtocol/coda/pull/2901

For each transaction in a block in the blocks database will also be associated with its corresponding `receipt_chain_hash`.
