### ISSUE TITLE
Respect operating system filesystem standards

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#221]
We should use something like `$XDG_CONFIG_HOME/coda` on Linux, maybe `Library/Preferences/coda` on macOS, and maybe `FOLDERID_RoamingAppData` on Windows.

**Comment by cmr** [comment]
We should split up `~/.coda-config` into these locations

**Comment by A-Manning** [comment]
closing, see #6105 for an up-to-date discussion of this issue.
