### ISSUE TITLE
Create With_hash module within External_transition modules

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#2254]
In the transition_frontier code, we commonly use the type  `(( External_transition.XXX.t, State_hash.t ) With_hash.t)`. On top of that, we now compose the type with `Envelope.Incoming.t` and `Cached.t`. It makes the type unnecessarily verbose and hard to read.

It would be useful to have a module for the type `( External_transition.XXX.t, State_hash.t ) With_hash.t` within the `External_transition.XXX`. We can this module `With_hash`. As a result, the typed is aliased as `External_transition.XXX.With_hash.t`. `With_hash` should have all the getter functions that `External_transition.XXX` has. Also, there should be a function for getting the hash of the external transition. Additionally, there should be a function that transforms `External_transition.XXX` to `External_transition.With_hash.XXX`.

I suspect that the transition_frontier code would significantly be slimmer as a result of this refactor. We repeatedly, make the function calls `With_hash.data` and we would not have to do that after this refactoring.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
