### ISSUE TITLE
Broadcast_pipe, coda.transition_frontier, is never set to None for coda_bootstrap_test

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#2290]
I was extending the coda_bootstrap_test to have a check that the bootstrapping node's sync state eventually reaches to `Bootstrap. This never occurs for the test because the broadcast pipe in Coda is never set to `None`. This needs to be further investigated. At the same time, it might be worth to replace the broadcast pipe for coda.transition_frontier to be replaced by Jane Street's incremental.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
