### ISSUE TITLE
Better solution for preferred peer

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#2323]
`try_preferred_peer` had been connecting back to a peer contained in an envelope. We're changing envelopes to contain only IP addresses, so that strategy no longer works.

In #2317, the code maintains a map from IP addresses to peers. If the peer list is a singleton, we consider that a preferred peer.

Using libp2p may offer a better solution, by being able to query for the sender socket info.

**Comment by cmr** [comment]
In libp2p world, we will know the `PeerID` of the incoming connection, and will be able to dial that PeerID- libp2p will take care of looking up how to actually connect to that peer.

In our current code, we could also implement this by modifying membership to report NodeIDs. If they aren't already the hash of a public key, we would make them be the hash of a public key. We sign outgoing messages and include the public key in the message. The recipient can hash the key, look it up in the DHT, and use that information to connect back if it needs. Not worth it for now.

**Comment by psteckler** [comment]
Code no longer exists.
