### ISSUE TITLE
Replace the field status in coda_worker_testnet with subscriptions

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#2336]
`status` in `coda_worker_testnet` introduces duplicate state. We can technically get the status of a worker through subscriptions. Here is what needs to be done in order to achieve that:

1. Include `Catchup` in `sync_status` subscription
2. Create a subscription whenever we obtain a new root.

Doing this will simultaneously improve our graphql services

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
