### ISSUE TITLE
Graceful shutdown of active network connections

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#2348]
We should implement a graceful shutdown mode so that a node attempts to finish any active connections so that it doesn't incur any trust decreases from it's peers. There should also be a way to manually non-gracefully shutdown the node, either with a specific signal or perhaps 2 signals back to back (kind of how dune handles SIGINT).

**Comment by cmr** [comment]
Do we want to have a timeout on graceful disconnection, or hang until the signal?

**Comment by enolan** [comment]
There should be a timeout, since peers may be slow, or never finalize
requests, intentionally or unintentionally.

**Comment by cmr** [comment]
For the record: fixing this will should fix the holy grail flakes we see pretty frequently. That test exercises shutdowns a lot, which ends up with the restarted proposers being banned, and an eventual network fork when the banned proposer creates its own chain.

**Comment by mrmr1993** [comment]
Now that the trust system is simplified, this is no longer necessary. Closing.
