### ISSUE TITLE
Staged_ledger_diff.t.creator is susceptible to forgery.

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#2396]
The `Staged_ledger_diff.t.creator` field is disjoint from the public key that actually proposed the `Protocol_state.t` associated with the target `Staged_ledger_hash.t` of the `Staged_ledger_diff.t`. An adversary can generate a `Staged_ledger_diff.t` with a different creator public key than the actual winner of the current slot and no one on the network would be able to verify that they had done so. The solution is to expose the winning public key in the `Protocol_state.t` and to either put an equality constraint between that field and the `Staged_ledger_diff.t.creator`, or to have `Staged_ledger_diff.apply` look at the creator public key from `Protocol_state.t` when determining the receipt address for a `Coinbase.t`.

**Comment by imeckler** [comment]
Thanks for recording this. I vote for solution 2: illegal states shouldn't even be representable.

**Comment by psteckler** [comment]
@nholland94 a reasonable place to stuff the winner is in `Consensus_state.Poly.t`?

**Comment by nholland94** [comment]
@psteckler yes, that would be a good place to store the winner.

**Comment by psteckler** [comment]
In `Proof_of_stake`, `update` from the unchecked world, and `update_var` from the check world, work in different ways wrt the VRF evaluation.

Inside `update_var`, there's a call to `Vrf.Checked.check`, which returns a winning account. For `update`, the result of `Vrf.eval` is passed to it.

There's an available function `Vrf.check` that returns an account, but doesn't appear to computing the same thing as `Checked.check`; it takes different inputs.

Does there exist a way to compute the winning account in the unchecked world? /cc @nholland94

**Comment by nholland94** [comment]
@psteckler That's because the `update` out of the snark is essentially an "asserted" update: we tell it the information we want it to produce the block with. Comparatively, the `update_var` in the snark is proving that information to be correct. We actually compute the winner of the block when we call `next_producer_timing` to figure out which block we want. That's then passed back into the `update` function by the `Block_producer` module when it is actually time to produce that block. So the right thing to do here is pass in the information about the producer into the `update` function (just like we do for the vrf result, which we also compute from `next_producer_timing`).

**Comment by psteckler** [comment]
The `develop-until-4.1.hardfork` branch already adds `block_stake_winner` to `Consensus_data`, so I don't need to add it.

**Comment by mrmr1993** [comment]
@psteckler that's the pk which possesses the stake that won the block, which may be distinct from the block creator if the stake was delegated, so it's probably not relevant to this issue.

**Comment by psteckler** [comment]
@mrmr1993 right, the coinbase receiver will be either the block creator or an explicitly-given receiver from the CLI. If there's no delegation, the creator will be the same as the winner.

I think we can resolve the receiver when we create the protocol state.
