### ISSUE TITLE
Improve build reproducibility/consistency

### ISSUE THREAD

**Issue by enolan** [MinaProtocol/mina#2436]
I run into a lot of build system problems. For various reasons, builds are inconsistent. It'd save us a lot of time and aggravation if we put some effort into nixifying or partially nixifying the build.

**Comment by jkrauska** [comment]
@enolan let's enumerate more details of the issues:

 - dune/ocaml ? injects datestamps and other meta data in to binaries - cannot produce identical binary from same source code

- some code parameters (eg snark pv keys) are generated at compile time and thus not easy to reproduce. (a cached copy of re-usable keys is included in CI builds, but this breaks whenever the snark code is modified)

**Comment by enolan** [comment]
The things I'm thinking of:
* `opam switch import` doesn't seem to actually pin the dependencies versions. We see rebuilds in CI that should be cached, and what gets rebuilt changes when we haven't changed the `opam.export` file
* Vendored dependencies pinned with `opam pin add` are A) global to the current switch, so things may break if you have more than one checkout on your machine and B) not upgraded automatically. If one of the vendored dependencies changes, you won't see the change until you run `opam upgrade foo`. This leads to breakage.
* The docker toolchain images can get out of sync with the actual contents of the repo fairly easily. `coda-toolchain` contains a version of the kademlia executable that it pulls in from apt when the container is built. We also build all the opam dependencies when we build the image, so if they change and the image isn't updated the CI build will be incorrect.
* Build products are tossed whenever you change profiles, leading to excessive rebuilds
* You have to install our patched version of RocksDB globally.

Re Joel's points:
* Bit-for-bit reproducible builds is an admirable goal, especially if we want to convince people we're not sneaking backdoors into published binaries, but I don't think we should prioritize it highly if it's hard.
* I don't know how this works. Is the fix as simple as just fixing a random seed? Obviously for production we can't do that, but for CI that would be easy.

**Comment by enolan** [comment]
@bkase has a tentative plan to move to a Nix based system sometime after launch.
