### ISSUE TITLE
Make Staged-ledger best-case latency long enough for our security parameter (necessary to believe receipts)

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#245]

**Comment by bkase** [comment]
This has something to do with the fact that we handle transactions _after_ the block that introduced them, and if it takes us too many extra blocks to actually work through the transactions we'll lose some bit of security.

I think @es92 convinced me at one point that this wasn't a problem, and I also can no longer convince myself that there's a problem here as I'm trying to think about it further. Maybe @nholland94 has thought about this more recently than I have?

**Comment by enolan** [comment]
What was the original problem? The security of Merkle proofs doesn't depend on whether the account is up to date in the snarked ledger.
