### ISSUE TITLE
Staged_ledger_hash should compute the genesis Aux_hash correctly

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#2477]
Right now, we compute the genesis `Staged_ledger_hash` using `Aux_hash.dummy` which equals to `String.init length_in_bytes ~f:(fun _ -> '\000')`. However, this is not correct. So, we need to actually compute the hash of the actual genesis scan_state.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
