### ISSUE TITLE
Trust_system__Peer_trust dominates logs

### ISSUE THREAD

**Issue by jkrauska** [MinaProtocol/mina#2569]
On an active testnet, Trust_system__Peer_trust events account for > 30% of all log messages. (the most common log type)

eg.

```
{"timestamp":"2019-05-30 20:36:48.450857Z","level":"Debug","source":{"module":"Trust_system__Peer_trust","location":"File \"lib/trust_system/peer_trust.ml\", line 136, characters 60-67"},"message":"Decreasing trust for peer $peer due to action Trust_system.Actions.Connected. New trust is -0.001292.","metadata":{"peer":"1.2.3.4","pid":8218}}
```
Perhaps this particular log message should be suppressed?

**Comment by enolan** [comment]
Why is this a problem in the first place? This is what the log filtering is for. We should change the level to trace, but I don't think the message should be removed.
