### ISSUE TITLE
Pick the VRF that's most likely to win, not the first to win in stake-checking

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#2573]
Now that staking supports more than one key at once, sometimes you may win with more than one key. Rather than picking the first one that wins, pick the best one that wins. See #2567

**Comment by cmr** [comment]
Why? What does "best" mean? The one with the most stake? The issue title seems to imply changing the order that we check the VRFs, which makes sense to me, but the issue body seems to be about selecting between multiple winners, which doesn't make sense to me.

**Comment by bkase** [comment]
Best  is the one that is more likely to be accepted by all the nodes (based on our deterministic conflict resolution logic when we receive more than one block in a slot)
