### ISSUE TITLE
Daemon crash on second startup when first time didn't sync to network

### ISSUE THREAD

**Issue by Schmavery** [MinaProtocol/mina#2667]
The current understanding is that this is due to persistence:
- First startup creates transition frontier persistence db, but doesn't write to it
- Second startup sees a persistence db, tries to read from it, but it's empty, so it fails.

Maybe the daemon should throw away the persistence db and resync when it is corrupt?

Stacktrace:
```
  {"timestamp":"2019-06-17 22:05:28.899666Z","level":"Error","source":{"module":"Transition_frontier_persistence__Transition_storage","location":"File \"lib/transition_frontier_persistence/transition_stor
  (monitor.ml.Error (Failure "Could not retrieve root")    
   ("Raised at file \"stdlib.ml\", line 33, characters 17-33"    
    "Called from file \"lib/transition_frontier_persistence/transition_frontier_persistence.ml\", line 188, characters 6-60"    
    "Called from file \"lib/transition_frontier_persistence/transition_frontier_persistence.ml\", line 181, characters 21-41"    
    "Called from file \"lib/coda_lib/coda_lib.ml\", line 416, characters 24-342"    
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69"    
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"    
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"    
    "Caught by monitor coda"))  
```

cc: @johnwu93 @nholland94 
Note: the wallet is currently working around this by deleting the config/transition_frontier folder before starting the daemon

**Comment by ghost-not-in-the-shell** [comment]
I believe that persistence is not working at all. For the testnet, Joel has to delete the `config/transition_frontier` folder too.

**Comment by cmr** [comment]
Fixing #2670 will fix this, and is currently being worked on by @nholland94.
