### ISSUE TITLE
Consensus local state creation takes 6seconds of (synchronous) wall-clock time on my laptop

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#2714]
## Impact:

* Startup time is an extra 6seconds on my machine (and I believe this at least ~95% of the total startup time)
* If we attach our signal handler before this process happens, Ctrl-C doesn't actually shut down Coda for 6seconds (bad UX)

## More info:

With `dev` config (a genesis ledger containing 18 accounts at full ledger depth)

Specifically the bottleneck is in `Sparse_ledger.of_any_ledger` on the Genesis_ledger.t

As I recall, we no longer have any reason to have this Sparse_ledger here, we'll just need to rewrite snarky handlers for the generic ledger type and use those.

**Comment by mrmr1993** [comment]
This is fixed, we no longer use a `Sparse_ledger.t` to hold the genesis ledger
