### ISSUE TITLE
Compute Merkle hashes in mask ledgers lazily

### ISSUE THREAD

**Issue by enolan** [MinaProtocol/mina#2760]
When we apply a series of transactions to a ledger, we update all the changed Merkle hashes after every transaction. This wastes a bunch of work since many of them will change again when we apply later transactions. It also wastes work when we don't actually care about the hashes. We should defer the updates until the hashes are actually needed.

**Comment by cmr** [comment]
@bkase @nholland94  I feel like there was a reason we didn't do this from the start. Do you remember?

**Comment by nholland94** [comment]
We have to do this in order to compute intermediate witnesses for snark proofs in the staged ledger.
