### ISSUE TITLE
Use PoW token for peer identity and use that for bans

### ISSUE THREAD

**Issue by enolan** [MinaProtocol/mina#2782]
We currently ban based on IP address, and since NAT is pervasive there can be a lot of collateral damage. Banning based on an expensive to generate token would be better. Since we need this for Kademlia peer IDs anyway, we should be able to piggyback on that, after libp2p lands. Calibrate it to, say, 2 seconds of computation on a modern iPhone.

**Comment by psteckler** [comment]
The token accompanies every message?

**Comment by enolan** [comment]
They'd be signing the messages with it.
