### ISSUE TITLE
Revisit Logging UX

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#2800]
#2797 adds a new pattern for registering consumers of our logger. This pattern was put in place to allow us to both persist raw logs and process them for stdout. However, the implementation for this was done quickly for the beta testnet and we need to put more thought and design into our overall UX around logging. For example: should logs be on by default? what granularity of options should be provided to users? should old logs be overwritten or appended to? etc...

**Comment by aneesharaines** [comment]
Would be good to get user input here: 
@nholland94 to create a set of questions to give to Chris so he can gather feedback 

Next steps to revist and get reqs from the team on what will facilitate debugging

**Comment by nholland94** [comment]
Questions we came up with as a team:

```
  1) What are your thoughts on Mina's logs? Do you like/dislike them?
  2) What logs (if any) do you find the most/least useful?
  3) Is there anything that confuses you in the logs?
  4) What log levels do you consume? (Eg: Info, Debug, etc)
  5) Do you programmatically process Mina log output, or do you only manually read them?
    5.a) Do you get use out of the log data as it stands now? Why or why not?
  6) What does your ideal logging format look like?
  7) Do you want first-class documented tools for filtering and displaying Mina logs?
  8) Would you prefer a standardized but limited logging format to a fully-featured custom logging format?
```

**Comment by nholland94** [comment]
Survey to go out today.
