### ISSUE TITLE
Implement Daira's variable-base scalar multiplication

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#2806]
Savings: 6,000 constraints

Daira has [optimizations](https://github.com/zcash/zcash/issues/3924) for variable-base scalar multiplication which gets down to 6 constraints per bit.

In the blockchain SNARK we have scalar multiplications in the VRF evaluation and in the recursive SNARK verification. 

The recursive SNARK verification uses
- 1 full-width scalar multiplication

The VRF evaluation uses
- 1 private-key-sized scalar multiplication (let's say it's full-width for now, because it is in the implementation)

The existing implementation actually uses "safe" curve addition and so costs (4 + 4 + 2) = 10 constraints per bit. In total, that means for the two scalar multiplications above we go from

2*753*10 ~= 15,000 constraints

to

2*753*10 ~= 9,000 constraints

for a total savings of ~6000 constraints.

**Comment by daira** [comment]
> The existing implementation actually uses "safe" curve addition and so costs (4 + 4 + 2) = 10 constraints per bit. In total, that means for the two scalar multiplications above we go from
> 
> 2_753_10 ~= 15,000 constraints
> 
> to
> 
> 2_753_10 ~= 9,000 constraints
> 
> for a total savings of ~6000 constraints.

Do you mean from 2 \* 753 \* 10 to 2 \* 753 \* 6?

**Comment by imeckler** [comment]
Yes!

**Comment by daira** [comment]
You may also be interested in https://github.com/zcash/zcash/issues/3425#issuecomment-511240257 , concerning G<sub>2</sub> subgroup testing (and G<sub>1</sub> in the subsequent comment). They are written for BLS12-381, but I believe essentially the same technique is applicable to the MNT4/6 curves, if the LLL computation is redone for them.

**Comment by imeckler** [comment]
Thanks @daira -- will check it out :)

**Comment by imeckler** [comment]
@daira -- do you know if there is an implementation of the procedure to go from the curve to the polynomial in psi implementing the subgroup check? It's described on [page 5 of this paper](https://eprint.iacr.org/2017/419.pdf) but just curious if it is implemented already somewhere.

**Comment by daira** [comment]
I don't know of an implementation of that. @ebfull?
