### ISSUE TITLE
Arity 3 Merkle Tree

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#2808]
Savings: 4518 constraints

We do one Merkle lookup per blockchain snark to check the proof of stake. It has 2^30 leaves. The cost of doing a Merkle lookup in a depth d binary merkle tree is roughly d * (2*753 + (5/3) * (2 * 753)). In our case, with d = 30 it's 90,360. 

Switching to a trinary merkle tree, we could have roughly the same number of leaves with depth 19. The total cost would then be 19 * (3 * (753 + (5/3) * 753) ) = 85,842.

which is a savings of 4518 constraints. Probably not worth it for the additional complexity.

**Comment by psteckler** [comment]
FWIW, Ethereum's Merkle trees are 16-way.

**Comment by daira** [comment]
Using wide hashes like Rescue or Poseidon, it becomes *much* more efficient to use a larger-arity tree.
