### ISSUE TITLE
Replace validated_transitions_keyswaptest with the testing transition_frontier extension broadcast pipe

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#2836]
The validated_transitions_keyswaptest pipe for integration can be easily derived from the testing transition_frontier extension. This pipe is discussed in the transition_frontier_extensions refactoring RFC. https://github.com/CodaProtocol/coda/blob/master/rfcs/0018-transition-frontier-extensions.md

However, we are relying on the implementation of the RFC to get merged into our codebase.
https://github.com/CodaProtocol/coda/pull/2664 before implementing this.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
