### ISSUE TITLE
Compute transition frontier metrics in O(1)

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#2850]
In order to help validate the beta testnet, I added some simple metrics tracking to the transition frontier. However, some of these metrics are computed in O(n) time on every root transition. These metrics could instead be tracked a little more eagerly in O(1) time. We can't afford to pay O(n) on every root transition.

We need this before we make the ledger not small.

**Comment by nholland94** [comment]
If https://github.com/CodaProtocol/coda/pull/3634 closes, these metrics will be completely removed until this issue is addressed.

**Comment by imeckler** [comment]
@nholland94 says this only affects our ability to see the rate of creation of new accounts

**Comment by nholland94** [comment]
Closing this issue as these metrics have been out for quite a while. We will revisit this when we redo frontier metrics.
