### ISSUE TITLE
Log when catchup applies

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#2921]
Perhaps something wrong with gossip network?

Logs after such an event happened to me locally:
https://gist.github.com/bkase/3f5cf47ce807ee6d801570b243b0ac71

**Comment by cmr** [comment]
from discord: I can't piece together a full explanation from just that log, but one possible explanation is you bootstrapped to a fork that eventually lost. After bootstrapping you need to wait for the best_tip block height to increase by at least k to have a consistent TF.

**Comment by wu-s-john** [comment]
We now have a sync status that tells us if we are doing ledger catchup. So, its a good indication of whether we are ledger catching or not.
