### ISSUE TITLE
coda-kademlia  needs a fixed rpath/to be packaged for portability on Linux

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#2956]
```
$ patchelf --print-rpath $(which coda-kademlia
/nix/store/kbbiky87bsdndh63m7919sxkf3gsh5zq-libffi-3.2.1/lib:/nix/store/7mrq5v4nnqfkv1ka7a0kdw9mzvqs5w3c-gmp-6.1.2/lib:/nix/store/681354n3k44r8z90m35hm8945vsp95h1-glibc-2.27/lib
```

Unlike on mac, on Linux it falls back to searching for the libraries in system dirs. So it will work on systems that are Close Enough to our Debian builder to have matching SONAMEs (and hopefully these libraries have sane SONAME ABI policies...)

**Comment by cmr** [comment]
(This is the coda-kademlia from the deb)

**Comment by enolan** [comment]
nix-bundle is the "good" solution, as opposed to mucking about and linking
to something other than what it was actually built with.
https://github.com/matthewbauer/nix-bundle

**Comment by mrmr1993** [comment]
We're not using kademlia any more. Closing.
