### ISSUE TITLE
Show % of total stake staking locally

### ISSUE THREAD

**Issue by jkrauska** [MinaProtocol/mina#2960]
Showing current % of total stake being staked locally is a good indicator of propose-rate.

Please add either % of total or just Total_balance_being_staked to a status output.

**Comment by enolan** [comment]
proposal chance is probably better, most of the time that's what people care about. Easy enough to add expected blocks per hour/day/month as well.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
