### ISSUE TITLE
API support for setting nonce in graphql transaction

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#2975]
Not having this makes us have a bad workaround for the faucet/echo service problem of double-sends with the same nonce

**Comment by jkrauska** [comment]
++cli

**Comment by jkrauska** [comment]
Also: manually setting the same nonce is the supposed technique to cancel a txn.

**Comment by enolan** [comment]
Well, setting the same nonce lets you replace a pending command. You can
effectively "cancel" it by replacing it with sending $0 to yourself.

**Comment by robinbb** [comment]
@bkase Can you opine on what should happen with this issue? @wu-s-john do you intend to work on this?
