### ISSUE TITLE
Make more explicit where the statements are for proofs

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#298]
Right now statements are essentially included in proofs (in the transaction snarks). We could (and should) save on bandwidth by separating them

**Comment by cmr** [comment]
@imeckler 	We have separate `Statement` modules now-  is this done?

**Comment by imeckler** [comment]
This is not done. The statements are quite large (they contain at least 4 field elements) so I propose we do the following.

Instead of including the statement in the transaction SNARK when serializing it, just have the hash of the statement. The SNARK pool should maintain the list of relevant statements keyed by their hashes. So it's still easy to verify a proof when it is relevant, which is what we want anyway.
