### ISSUE TITLE
"Connection timed out" error doesn't remove peer from peer set

### ISSUE THREAD

**Issue by enolan** [MinaProtocol/mina#2986]
My testnet node has been trying to connect to a peer which appears to be offline for about an hour. I see:
```
2019-07-25 03:13:24 UTC [Error] RPC call raised an exception: $exn
	exn: "(Unix.Unix_error \"Connection timed out\" connect [REDACTED])"
```
repeatedly. My node is still connected to the network, it's just that specific IP that's a problem. We're supposed to be catching these exceptions and removing the peer from our set, but it's not working. I looked at `coda advanced get-trust-status-all` and that IP isn't listed, which is *really* weird. Also nobody is banned which makes me think maybe it's not printing everything it should.

**Comment by cmr** [comment]
This is the error path lacking a trust system action: https://github.com/CodaProtocol/coda/blob/master/src/lib/gossip_net/gossip_net.ml#L410.
