### ISSUE TITLE
error: coda client get-balance -address <public-key>

### ISSUE THREAD

**Issue by pkrasam** [MinaProtocol/mina#2987]
Getting this error when trying to lookup my balance

**Command**
`coda client get-balance -address <public-key>`

**Error**

> 2019-07-25 15:36:17.715840+10:00 Error ("Exception raised to [Monitor.try_with] that already returned.
> ""This error was captured by a default handler in [Async.Log]."(exn(monitor.ml.Error(
> Failure"traced task `R&Get_balance` failed, exception reported to parent monitor")
> ("Raised at file \"stdlib.ml\", line 33, characters 17-33
> ""Called from file \"src/result.ml\", line 96, characters 19-24
> ""Called from file \"src/monad.ml\" (inlined), line 37, characters 20-29
> ""Called from file \"src/implementations.ml\", line 493, characters 25-67
> ""Called from file \"src/result.ml\", line 151, characters 9-15"))))
>

**Comment by pkrasam** [comment]
`coda client get-balance -address tNci7bkTjL789PhtCG76r79C74uHfBC6WHQqcBMX8AVX125iaAhpBK36XYJhTXyg32bC24vbYvfMNgmsz51ZmaakZNCeUWA3ahEth6sancfxj4A2UzQrkqRfnsxnWrXfXwvqVv6YM7br6E`

**Comment by jkrauska** [comment]
@pkrasam is this still happening for you?

`
$ coda client get-balance -address tNci7bkTjL789PhtCG76r79C74uHfBC6WHQqcBMX8AVX125iaAhpBK36XYJhTXyg32bC24vbYvfMNgmsz51ZmaakZNCeUWA3ahEth6sancfxj4A2UzQrkqRfnsxnWrXfXwvqVv6YM7br6E
Balance: 100 coda
`

Perhaps it was only happening when the key wasn't in the block chain? (before the transfer?)

**Comment by jkrauska** [comment]
I also tried creating a new account and then using it before adding funds, and I could not reproduce.

> $ coda client generate-keypair -privkey-path joelkeytest
> Password for new private key file:
> Again to confirm:
> Keypair generated
> Public key: tNcic2STNYDRcHiHvzvVFUEZpovTTdoErm1aFS94w8ZXzUx43zfWMPzZPSS6sxUe6dgiVYeEXMiZMcTsESVLGJnvquckcesHoRJ3MscsZVHUdF1GdKMeAr2cik3f3ANusDdTEZNxkVoUrB

and then

> $ coda client get-balance -address tNcic2STNYDRcHiHvzvVFUEZpovTTdoErm1aFS94w8ZXzUx43zfWMPzZPSS6sxUe6dgiVYeEXMiZMcTsESVLGJnvquckcesHoRJ3MscsZVHUdF1GdKMeAr2cik3f3ANusDdTEZNxkVoUrB
> There are no funds in this account

So that's the expected behavior.  Not sure yet what you're seeing here.

**Comment by cmr** [comment]
We sometimes see this because the daemon was bootstrapping. #3025 will add better error handling around this condition- maybe it was some other exception, but probably not unless @pkrasam knows that the node wasn't in bootstrap.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
