### ISSUE TITLE
Daemon died upon run

### ISSUE THREAD

**Issue by pavrych** [MinaProtocol/mina#2992]
Log:
_{"timestamp":"2019-07-25 16:31:21.004533Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 291, characters 65-7$
{"timestamp":"2019-07-25 16:31:21.004684Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-7$
{"timestamp":"2019-07-25 16:31:21.004726Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-7$
{"timestamp":"2019-07-25 16:31:21.004771Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-7$
{"timestamp":"2019-07-25 16:31:21.004802Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-7$
{"timestamp":"2019-07-25 16:31:21.004838Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-7$
{"timestamp":"2019-07-25 16:31:21.004871Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-7$
{"timestamp":"2019-07-25 16:31:21.268232Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 486, characters 54-6$
{"timestamp":"2019-07-25 16:31:44.671681Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 500, characters 63-7$
{"timestamp":"2019-07-25 16:31:44.674323Z","level":"Debug","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 467, characters 63-7$
{"timestamp":"2019-07-25 16:31:44.698563Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 523, characters 64-7$
{"timestamp":"2019-07-25 16:31:44.729839Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 531, characters 62-6$
{"timestamp":"2019-07-25 16:31:50.211524Z","level":"Debug","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 467, characters 63-7$
{"timestamp":"2019-07-25 16:31:50.252984Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", li$
{"timestamp":"2019-07-25 16:31:50.256741Z","level":"Info","source":{"module":"Transition_router","location":"File \"lib/transition_router/transition_rou$
{"timestamp":"2019-07-25 16:31:50.257811Z","level":"Debug","source":{"module":"Network_pool__Transaction_pool","location":"File \"lib/network_pool/trans$
{"timestamp":"2019-07-25 16:31:50.257916Z","level":"Debug","source":{"module":"Network_pool__Transaction_pool","location":"File \"lib/network_pool/trans$
{"timestamp":"2019-07-25 16:31:50.258735Z","level":"Info","source":{"module":"Proposer","location":"File \"lib/proposer/proposer.ml\", line 212, charact$
{"timestamp":"2019-07-25 16:31:50.258867Z","level":"Trace","source":{"module":"Web_pipe","location":"File \"app/cli/src/web_pipe.ml\", line 122, charact$
{"timestamp":"2019-07-25 16:31:50.258966Z","level":"Info","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 590, characters 56-63$
{"timestamp":"2019-07-25 16:31:55.288246Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", li$
{"timestamp":"2019-07-25 16:31:55.288446Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", li$
{"timestamp":"2019-07-25 16:31:55.288529Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", li$
{"timestamp":"2019-07-25 16:31:55.288626Z","level":"Error","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", li$
{"timestamp":"2019-07-25 16:31:55.289535Z","level":"Fatal","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", li$
{"timestamp":"2019-07-25 16:31:55.289693Z","level":"Debug","source":{"module":"Coda_run","location":"File \"app/cli/src/coda_run.ml\", line 70, characte$
{"timestamp":"2019-07-25 16:31:55.298135Z","level":"Debug","source":{"module":"Coda_run","location":"File \"app/cli/src/coda_run.ml\", line 83, characte$

_   

    (monitor.ml.Error (Kademlia.Membership.Child_died)
  ("Raised at file \"lib/kademlia/membership.ml\", line 233, characters 18-34"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
    "Caught by monitor coda"))

**Comment by enolan** [comment]
You truncated the end of all the log messages. Can you open up `~/.coda-config/coda.log` and copy the last 50 or so lines?

**Comment by o1pranay** [comment]
@pavrych can you share some more info on this - eg. your logs?

**Comment by mrmr1993** [comment]
We no longer use kademlia, and the child process system has changed how it handles crashes. Closing as stale.
