### ISSUE TITLE
Give clear semantics and fix implementation of Interruptible monad

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#300]

**Comment by cmr** [comment]
To add some background to this issue, there has in the past been some confusion around exactly what the interruptible monad does. Also maybe there's a bug of some sort? @bkase do you remember what the story is here?

**Comment by bkase** [comment]
It's not very clear what happens when an interrupt fires, and bind is extremely complex. As far as I'm aware, this does "work" enough that we haven't needed to touch it in a while, but it's a bit too complicated to live without either (a) really nice documentation or (b) a simpler implementation (and probably both)
