### ISSUE TITLE
Warn or fail if logger called with no consumers

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#3000]
If the logger is called without registered consumers, it just drops the log messages. That was happening on daemon startup.

Should we warn or fail in that case? Maybe print the message to stdout, so it's not lost entirely?

**Comment by cmr** [comment]
Hm. I feel like we should throw an exception for this.

**Comment by psteckler** [comment]
In any case, it should not fail silently.

**Comment by mrmr1993** [comment]
We now use this feature to drop log messages during unit tests (via `Logger.null`). Closing.
