### ISSUE TITLE
Know when you're banned

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#3013]
If you see something from a banned person, tell them -- refusing to service, you are banned (something like that, ask @o1pranay for copy)

**Comment by enolan** [comment]
:1:, though we should only notify them once, and reject connections entirely afterward. We should give a time-to-expiry as well.

**Comment by psteckler** [comment]
How do we notify them?

**Comment by psteckler** [comment]
I'm working on this.

**Comment by psteckler** [comment]
Stale.
