### ISSUE TITLE
Resolve Verification Key issues for website

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#3052]
This is not a super high priority task since we do not have the testnet demo up and running. However, they could appear later. 

The tasks are the following:
[ ] #1109
[ ] #1084
[ ] #1069
[ ] #845 
[ ] #809

I closed them because I wanted to coalesce all these issues into one open issue.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
