### ISSUE TITLE
Notify banned peer with the reason for banning / trust score decreasing

### ISSUE THREAD

**Issue by o1pranay** [MinaProtocol/mina#3062]
This came up when discussing #3013 with @psteckler and @cmr. Currently, we don't store a ban reason in `peer_status`, but it would be helpful to notify the banned node as to why it happened.  Because the ban happens over time and due to cumulative negative behavior, we could surface the last action that decreased the trust score. In the case of an insta ban, it may be easier to surface the discrete reason.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
