### ISSUE TITLE
Produce an RFC for non-consensus node protocol

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#3116]
As part of the march to a mainnet release candidate, we want to support a less-bandwidth and resource intensive non-consensus full node protocol that works along side our consensus node one.

This is step one -- step two will be getting these non-consensus nodes running in the browser in some way.

An RFC should at least talk about the following:
1. What goes on the parallel quieter gossip net, what stays on the main one?
2. What sort of extra information do these nodes need to believe state given that they won't be keeping transition frontiers?
3. How can we refactor our codebase such that we can output both consensus and non-consensus binaries?

**Comment by enolan** [comment]
Author of this should address #1916.

**Comment by mrmr1993** [comment]
This is being approached in a different way now. Closing.
