### ISSUE TITLE
Coda daemon crashed on Ubuntu 18 on boot

### ISSUE THREAD

**Issue by bitcoinsSG** [MinaProtocol/mina#3138]
Log on terminal:
2019-08-08 09:29:45 UTC [Info] Coda daemon is booting up; built with commit "fd4fb3983fcc7d094ee84e305dd3bc6fc80e1c50" on branch "release/0.0.1-beta.2"
2019-08-08 09:30:08 UTC [Info] Starting Bootstrap Controller phase
2019-08-08 09:30:08 UTC [Info] Coda daemon is now connecting
2019-08-08 09:30:08 UTC [Info] Pausing block production while bootstrapping
2019-08-08 09:30:08 UTC [Info] Daemon ready. Clients can now connect
2019-08-08 09:30:13 UTC [Error] Kademlia stderr output: All peers failed 
2019-08-08 09:30:13 UTC [Error] Kademlia stderr output: to respond!

2019-08-08 09:30:13 UTC [Fatal] Kademlia process died: "exited with code 1"

Last 20 lines of .coda-config/coda.log

{"timestamp":"2019-08-08 09:29:54.267653Z","level":"Debug","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 477, characters 63-70"},"message":"Long async cycle: $span milliseconds","metadata":{"pid":21562,"span":"7.185243431s"}}
{"timestamp":"2019-08-08 09:29:54.326949Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 533, characters 64-71"},"message":"Creating database of type $typ in directory $directory","metadata":{"directory":"/home/grana/.coda-config/receipt_chain","pid":21562,"typ":"receipt_chain_database"}}
{"timestamp":"2019-08-08 09:29:54.363035Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 541, characters 62-69"},"message":"Creating database of type $typ in directory $directory","metadata":{"directory":"/home/grana/.coda-config/transaction","pid":21562,"typ":"transaction_database"}}
{"timestamp":"2019-08-08 09:30:07.991595Z","level":"Debug","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 477, characters 63-70"},"message":"Long async cycle: $span milliseconds","metadata":{"pid":21562,"span":"744.585253ms"}}
{"timestamp":"2019-08-08 09:30:08.002573Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 191, characters 56-63"},"message":"Kademlia command-line arguments: $argv","metadata":{"argv":["test","0.0.0.0","(\"196.52.34.12\", 8303)","(\"54.149.124.61\", 8303)"],"pid":21562}}
{"timestamp":"2019-08-08 09:30:08.032908Z","level":"Info","source":{"module":"Transition_router","location":"File \"lib/transition_router/transition_router.ml\", line 98, characters 53-60"},"message":"Starting Bootstrap Controller phase","metadata":{"pid":21562}}
{"timestamp":"2019-08-08 09:30:08.033088Z","level":"Debug","source":{"module":"Network_pool__Transaction_pool","location":"File \"lib/network_pool/transaction_pool.ml\", line 224, characters 69-76"},"message":"no frontier","metadata":{"pid":21562}}
{"timestamp":"2019-08-08 09:30:08.033128Z","level":"Debug","source":{"module":"Network_pool__Transaction_pool","location":"File \"lib/network_pool/transaction_pool.ml\", line 224, characters 69-76"},"message":"no frontier","metadata":{"pid":21562}}
{"timestamp":"2019-08-08 09:30:08.033757Z","level":"Info","source":{"module":"Coda_lib","location":"File \"lib/coda_lib/coda_lib.ml\", line 150, characters 63-70"},"message":"Coda daemon is now connecting","metadata":{"pid":21562}}
{"timestamp":"2019-08-08 09:30:08.033823Z","level":"Info","source":{"module":"Proposer","location":"File \"lib/proposer/proposer.ml\", line 224, characters 57-64"},"message":"Pausing block production while bootstrapping","metadata":{"pid":21562}}
{"timestamp":"2019-08-08 09:30:08.033857Z","level":"Trace","source":{"module":"Web_pipe","location":"File \"app/cli/src/web_pipe.ml\", line 122, characters 58-65"},"message":"Not running a web client pipe","metadata":{"pid":21562}}
{"timestamp":"2019-08-08 09:30:08.033903Z","level":"Info","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 600, characters 56-63"},"message":"Daemon ready. Clients can now connect","metadata":{"pid":21562}}
{"timestamp":"2019-08-08 09:30:13.045524Z","level":"Error","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 277, characters 65-72"},"message":"Kademlia stderr output: All peers failed ","metadata":{"pid":21562}}
{"timestamp":"2019-08-08 09:30:13.045747Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 303, characters 64-71"},"message":"Creating instance","metadata":{"kademlia_level":"DBUG","pid":21562}}
{"timestamp":"2019-08-08 09:30:13.045806Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 303, characters 64-71"},"message":"Attempting to connecting to peer: \\\"54.149.124.61\\\":8303, \\\"nvs0lNH8gOlIewTboq/+CA90mNp+UR6Hz0K0dERMxxY=\\\"","metadata":{"kademlia_level":"DBUG","pid":21562}}
{"timestamp":"2019-08-08 09:30:13.045874Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 303, characters 64-71"},"message":"Connection to peer failed NodeDown","metadata":{"kademlia_level":"EROR","pid":21562}}
{"timestamp":"2019-08-08 09:30:13.045959Z","level":"Error","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 277, characters 65-72"},"message":"Kademlia stderr output: to respond!\n","metadata":{"pid":21562}}
{"timestamp":"2019-08-08 09:30:13.046879Z","level":"Fatal","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 228, characters 68-75"},"message":"Kademlia process died: $exit_or_signal","metadata":{"exit_or_signal":"exited with code 1","pid":21562}}
{"timestamp":"2019-08-08 09:30:13.047031Z","level":"Debug","source":{"module":"Coda_run","location":"File \"app/cli/src/coda_run.ml\", line 70, characters 52-59"},"message":"Successfully wrote the visualization of the registered masks at location: /home/grana/.coda-config/registered_masks.dot.","metadata":{"coda_run":"Logging state before program ends","pid":21562}}
{"timestamp":"2019-08-08 09:30:13.048965Z","level":"Debug","source":{"module":"Coda_run","location":"File \"app/cli/src/coda_run.ml\", line 83, characters 58-65"},"message":"Could not visualize transition frontier since daemon is currently bootstrapping","metadata":{"coda_run":"Logging state before program ends","pid":21562}}

  Please:
    Open an issue:
      https://github.com/CodaProtocol/coda/issues/new

    Briefly describe what you were doing, and include the last 20 lines from .coda-config/coda.log.
    And then paste the following:

    (monitor.ml.Error (Kademlia.Membership.Child_died)
  ("Raised at file \"lib/kademlia/membership.ml\", line 233, characters 18-34"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"

**Comment by mrmr1993** [comment]
We're no longer using Kademlia, which caused this crash. Closing.
