### ISSUE TITLE
Daemon crash after restarting process on MacOS 10.14.5

### ISSUE THREAD

**Issue by paul-bison** [MinaProtocol/mina#3140]
Computer went to sleep when it woke up I restarted the daemon to continue sync and it crashed with the following 

{"timestamp":"2019-08-08 10:36:39.328278Z","level":"Debug","source":{"module":"Coda","location":"File \"src/app/cli/src/coda.ml\", line 477, characters 63-70"},"message":"Long async cycle: $span milliseconds","metadata":{"pid":39230,"span":"9.544557s"}}
{"timestamp":"2019-08-08 10:36:39.335695Z","level":"Trace","source":{"module":"Coda","location":"File \"src/app/cli/src/coda.ml\", line 533, characters 64-71"},"message":"Creating database of type $typ in directory $directory","metadata":{"directory":"/Users/paul/.coda-config/receipt_chain","pid":39230,"typ":"receipt_chain_database"}}
{"timestamp":"2019-08-08 10:36:39.342423Z","level":"Trace","source":{"module":"Coda","location":"File \"src/app/cli/src/coda.ml\", line 541, characters 62-69"},"message":"Creating database of type $typ in directory $directory","metadata":{"directory":"/Users/paul/.coda-config/transaction","pid":39230,"typ":"transaction_database"}}
{"timestamp":"2019-08-08 10:36:54.742969Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"src/lib/kademlia/membership.ml\", line 254, characters 64-71"},"message":"Process $process does not exist, won't kill","metadata":{"pid":39230,"process":"16276"}}
{"timestamp":"2019-08-08 10:36:54.743387Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"src/lib/kademlia/membership.ml\", line 191, characters 56-63"},"message":"Kademlia command-line arguments: $argv","metadata":{"argv":["test","0.0.0.0","(\"148.75.213.142\", 8303)","(\"54.149.124.61\", 8303)"],"pid":39230}}
{"timestamp":"2019-08-08 10:36:54.749179Z","level":"Info","source":{"module":"Transition_router","location":"File \"src/lib/transition_router/transition_router.ml\", line 98, characters 53-60"},"message":"Starting Bootstrap Controller phase","metadata":{"pid":39230}}
{"timestamp":"2019-08-08 10:36:54.749479Z","level":"Debug","source":{"module":"Network_pool__Transaction_pool","location":"File \"src/lib/network_pool/transaction_pool.ml\", line 224, characters 69-76"},"message":"no frontier","metadata":{"pid":39230}}
{"timestamp":"2019-08-08 10:36:54.749522Z","level":"Debug","source":{"module":"Network_pool__Transaction_pool","location":"File \"src/lib/network_pool/transaction_pool.ml\", line 224, characters 69-76"},"message":"no frontier","metadata":{"pid":39230}}
{"timestamp":"2019-08-08 10:36:54.750066Z","level":"Info","source":{"module":"Coda_lib","location":"File \"src/lib/coda_lib/coda_lib.ml\", line 150, characters 63-70"},"message":"Coda daemon is now connecting","metadata":{"pid":39230}}
{"timestamp":"2019-08-08 10:36:54.750151Z","level":"Info","source":{"module":"Proposer","location":"File \"src/lib/proposer/proposer.ml\", line 224, characters 57-64"},"message":"Pausing block production while bootstrapping","metadata":{"pid":39230}}
{"timestamp":"2019-08-08 10:36:54.750212Z","level":"Trace","source":{"module":"Web_pipe","location":"File \"src/app/cli/src/web_pipe.ml\", line 122, characters 58-65"},"message":"Not running a web client pipe","metadata":{"pid":39230}}
{"timestamp":"2019-08-08 10:36:54.750287Z","level":"Info","source":{"module":"Coda","location":"File \"src/app/cli/src/coda.ml\", line 600, characters 56-63"},"message":"Daemon ready. Clients can now connect","metadata":{"pid":39230}}
{"timestamp":"2019-08-08 10:36:59.780452Z","level":"Error","source":{"module":"Kademlia__Membership","location":"File \"src/lib/kademlia/membership.ml\", line 277, characters 65-72"},"message":"Kademlia stderr output: All peers failed to","metadata":{"pid":39230}}
{"timestamp":"2019-08-08 10:36:59.780555Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"src/lib/kademlia/membership.ml\", line 303, characters 64-71"},"message":"Creating instance","metadata":{"kademlia_level":"DBUG","pid":39230}}
{"timestamp":"2019-08-08 10:36:59.780577Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"src/lib/kademlia/membership.ml\", line 303, characters 64-71"},"message":"Attempting to connecting to peer: \\\"54.149.124.61\\\":8303, \\\"nvs0lNH8gOlIewTboq/+CA90mNp+UR6Hz0K0dERMxxY=\\\"","metadata":{"kademlia_level":"DBUG","pid":39230}}
{"timestamp":"2019-08-08 10:36:59.780599Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"src/lib/kademlia/membership.ml\", line 303, characters 64-71"},"message":"Connection to peer failed NodeDown","metadata":{"kademlia_level":"EROR","pid":39230}}
{"timestamp":"2019-08-08 10:36:59.780631Z","level":"Error","source":{"module":"Kademlia__Membership","location":"File \"src/lib/kademlia/membership.ml\", line 277, characters 65-72"},"message":"Kademlia stderr output:  respond!\n","metadata":{"pid":39230}}
{"timestamp":"2019-08-08 10:36:59.795688Z","level":"Fatal","source":{"module":"Kademlia__Membership","location":"File \"src/lib/kademlia/membership.ml\", line 228, characters 68-75"},"message":"Kademlia process died: $exit_or_signal","metadata":{"exit_or_signal":"exited with code 1","pid":39230}}
{"timestamp":"2019-08-08 10:36:59.795827Z","level":"Debug","source":{"module":"Coda_run","location":"File \"src/app/cli/src/coda_run.ml\", line 70, characters 52-59"},"message":"Successfully wrote the visualization of the registered masks at location: /Users/paul/.coda-config/registered_masks.dot.","metadata":{"coda_run":"Logging state before program ends","pid":39230}}
{"timestamp":"2019-08-08 10:36:59.797942Z","level":"Debug","source":{"module":"Coda_run","location":"File \"src/app/cli/src/coda_run.ml\", line 83, characters 58-65"},"message":"Could not visualize transition frontier since daemon is currently bootstrapping","metadata":{"coda_run":"Logging state before program ends","pid":39230}}

    (monitor.ml.Error (Kademlia.Membership.Child_died)
  ("Raised at file \"src/lib/kademlia/membership.ml\", line 233, characters 18-34"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
    "Caught by monitor coda"))

**Comment by jkrauska** [comment]
Thanks Paul.

Our seed nodes were offline at this time and I suspect that was the root cause of this failure.

Can you try reconnecting now? (we're back up.)

Please also be sure to grab the newest binary. (website should be updated soon)
@o1pranay

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
