### ISSUE TITLE
Coda daemon crashed

### ISSUE THREAD

**Issue by doronz2** [MinaProtocol/mina#3141]
I tried to start a node with "coda daemon -peer share-the-wealth.o1test.net:8303"

and got an error:
 (monitor.ml.Error
  (Failure
    "IO error: While lock file: /home/ubuntu/.coda-config/trust/LOCK: Resource temporarily unavailable")
  ("Raised at file \"stdlib.ml\", line 33, characters 17-33"
    "Called from file \"lib/rocksdb/database.ml\", line 16, characters 34-63"
    "Called from file \"lib/trust_system/peer_trust.ml\", line 50, characters 15-44"
    "Called from file \"app/cli/src/coda.ml\", line 485, characters 28-65"
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
    "Caught by monitor coda"))

with log:{"timestamp":"2019-08-08 08:59:01.905353Z","level":"Info","source":{"module":"Gossip_net","location":"File \"lib/gossip_net/gossip_net.ml\", line 155, characters 55-62"},"message":"Removing peer from peer set: [host : 54.149.124.61, discovery_port : 8303, communication_port : 8302]","metadata":{"peer":{"host":"54.149.124.61","discovery_port":8303,"communication_port":8302},"pid":9958}}
{"timestamp":"2019-08-08 13:40:19.428292Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 291, characters 65-72"},"message":"Error reading daemon.json: $error","metadata":{"error":"(Unix.Unix_error\"No such file or directory\"open\"((filename /home/ubuntu/.coda-config/daemon.json) (mode (O_RDONLY O_CLOEXEC)) (perm 0o0))\")","pid":20766}}
{"timestamp":"2019-08-08 13:40:19.428365Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"external-port","pid":20766}}
{"timestamp":"2019-08-08 13:40:19.428380Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"client-port","pid":20766}}
{"timestamp":"2019-08-08 13:40:19.428404Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"snark-worker-fee","pid":20766}}
{"timestamp":"2019-08-08 13:40:19.428414Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"max-concurrent-connections","pid":20766}}
{"timestamp":"2019-08-08 13:40:19.428423Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"work-selection","pid":20766}}
{"timestamp":"2019-08-08 13:40:19.428432Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"peers","pid":20766}}
{"timestamp":"2019-08-08 13:40:19.820787Z","level":"Debug","source":{"module":"Coda_run","location":"File \"app/cli/src/coda_run.ml\", line 70, characters 52-59"},"message":"Successfully wrote the visualization of the registered masks at location: /home/ubuntu/.coda-config/registered_masks.dot.","metadata":{"coda_run":"Logging state before program ends","pid":20766}}
{"timestamp":"2019-08-08 13:40:19.820941Z","level":"Trace","source":{"module":"Coda_run","location":"File \"app/cli/src/coda_run.ml\", line 75, characters 56-63"},"message":"Shutdown before Coda instance was created, not saving a visualization","metadata":{"coda_run":"Logging state before program ends","pid":20766}}
{"timestamp":"2019-08-08 13:46:22.621160Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 291, characters 65-72"},"message":"Error reading daemon.json: $error","metadata":{"error":"(Unix.Unix_error\"No such file or directory\"open\"((filename /home/ubuntu/.coda-config/daemon.json) (mode (O_RDONLY O_CLOEXEC)) (perm 0o0))\")","pid":20833}}
{"timestamp":"2019-08-08 13:46:22.621220Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"external-port","pid":20833}}
{"timestamp":"2019-08-08 13:46:22.621235Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"client-port","pid":20833}}
{"timestamp":"2019-08-08 13:46:22.621246Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"snark-worker-fee","pid":20833}}
{"timestamp":"2019-08-08 13:46:22.621256Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"max-concurrent-connections","pid":20833}}
{"timestamp":"2019-08-08 13:46:22.621266Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"work-selection","pid":20833}}
{"timestamp":"2019-08-08 13:46:22.621276Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"peers","pid":20833}}
{"timestamp":"2019-08-08 13:46:22.997005Z","level":"Debug","source":{"module":"Coda_run","location":"File \"app/cli/src/coda_run.ml\", line 70, characters 52-59"},"message":"Successfully wrote the visualization of the registered masks at location: /home/ubuntu/.coda-config/registered_masks.dot.","metadata":{"coda_run":"Logging state before program ends","pid":20833}}
{"timestamp":"2019-08-08 13:46:22.997153Z","level":"Trace","source":{"module":"Coda_run","location":"File \"app/cli/src/coda_run.ml\", line 75, characters 56-63"},"message":"Shutdown before Coda instance was created, not saving a visualization","metadata":{"coda_run":"Logging state before program ends","pid":20833}}

**Comment by wu-s-john** [comment]
Hi @doronz2, thanks for reporting it. At the meantime, you can should remove the folder `/home/ubuntu/.coda-config/` and you should be able to run the program normally.

**Comment by cmr** [comment]
@doronz2 	Have you seen this again? I think this only happens if there is already a daemon running... or maybe it failed to release the lock somehow.

**Comment by Mitsushima1** [comment]
@emberian I met the same issue, I remove the "--restart=always" option when starting the docker.

And I got the following error when it goes to the 41st line of entrypoint.sh.

+ INPUT_ARGS='daemon --block-producer-key /keys/my-wallet1 --peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt'

+ LOG_FILES=('mina.log')

+ declare -a LOG_FILES

+ VERBOSE_LOG_FILES=('.mina-config/mina-prover.log' '.mina-config/mina-verifier.log' '.mina-config/mina-best-tip.log')

+ declare -a VERBOSE_LOG_FILES

+ for script in /entrypoint.d/*

+ '[' -x /entrypoint.d/01-override-genesis-ledger.sh ']'

+ /entrypoint.d/01-override-genesis-ledger.sh daemon --block-producer-key /keys/my-wallet1 --peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt

+ for script in /entrypoint.d/*

+ '[' -x /entrypoint.d/01-override-peers-list.sh ']'

+ /entrypoint.d/01-override-peers-list.sh daemon --block-producer-key /keys/my-wallet1 --peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt

+ for script in /entrypoint.d/*

+ '[' -x /entrypoint.d/01-run-demo.sh ']'

+ /entrypoint.d/01-run-demo.sh daemon --block-producer-key /keys/my-wallet1 --peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt

+ mkdir -p .mina-config

+ touch .mina-config/mina-prover.log

+ touch .mina-config/mina-verifier.log

+ touch .mina-config/mina-best-tip.log

+ true

+ rm -f .mina-config/.mina-lock

+ mina_pid=17

+ mina daemon --block-producer-key /keys/my-wallet1 --peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt

+ tail_pid=18

+ wait 17

+ tail -q -f mina.log

2021-11-10 20:30:45 UTC [Info] Coda daemon is booting up; built with commit "fe51f1ef5cfbcb4d5f559af39080963cf28ff1af" on branch "master"

Using password from environment variable CODA_PRIVKEY_PASS

Using password from environment variable CODA_PRIVKEY_PASS

Using password from environment variable CODA_PRIVKEY_PASS

2021-11-10 20:30:45 UTC [Info] Created daemon lockfile "/root/.mina-config/.mina-lock"

2021-11-10 20:30:45 UTC [Info] Registering async shutdown handler: "Remove daemon lockfile"

2021-11-10 20:30:45 UTC [Info] Daemon will expire at "2024-12-10 14:00:00-07:00"

2021-11-10 20:30:45 UTC [Info] Booting may take several seconds, please wait

2021-11-10 20:30:45 UTC [Info] Reading configuration files $config_files

config_files: [ "/var/lib/coda/config_fe51f1ef.json", "/root/.mina-config/daemon.json" ]

2021-11-10 20:30:45 UTC [Warn] Could not read configuration from "/root/.mina-config/daemon.json"

2021-11-10 20:30:45 UTC [Info] Initializing with runtime configuration. Ledger name: "mainnet"

2021-11-10 20:30:45 UTC [Info] Using the compiled constraint constants

2021-11-10 20:30:45 UTC [Info] Loaded genesis ledger from $ledger_file

ledger_file: "/root/.mina-config/genesis/genesis_ledger_accounts_71d4f4a0e8c1f3e78760b989234760584969ea0144ed1a3057234f6f0e73621a.tar.gz"

2021-11-10 20:30:46 UTC [Info] Using block producer keypair private-key password from environment variable CODA_PRIVKEY_PASS

Transaction_snark.system: 46.248s

/entrypoint.sh: line 41:    17 Killed                  mina $INPUT_ARGS 2>&1 > mina.log

[It's the 41st line of entrypoint.sh]
![image](https://user-images.githubusercontent.com/68367198/141188521-14aafeb3-3739-49b6-973b-c70ffc09b74f.png)

**Comment by shimkiv** [comment]
Hey @doronz2, I will close this issue hoping that the most recent versions of the Mina Daemon are more stable for you.
Please feel free to report new issues should you face any.
Thank you.
