### ISSUE TITLE
After first catchup (after a bootstrap) succeeds, another catchup happens

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#3147]
```
𝝺 coda client status
Coda Daemon Status
-----------------------------------

Global Number of Accounts:  44
Block Height:               15
Max Observed Block Length:  18
Local Uptime:               4m50s
```

Is this expected? If so @ghost-not-in-the-shell or @nholland94 	can you explain why this is expected? If it's not expected, we can make it a bug.

**Comment by bkase** [comment]
Anecdotally, I've always seen this happen on my nodes and nodes of others based on their `coda client status`s they send to us on discord

**Comment by bkase** [comment]
When the second catchup finishes we get these log messages as well (I can make a separate issue)

```
2019-08-08 18:13:23 UTC [Warn] Not rebroadcasting block $state_hash because it was received "4 slots too late"
        state_hash: "8878914832792017659227522574908695222505480467347511753319755077795958537369428562776442379099421346993701650748222114255868595111765594809666419751376347790596084126005527631398788295258353066771030883288271678770331274905156"
2019-08-08 18:13:23 UTC [Warn] Not rebroadcasting block $state_hash because it was received "3 slots too late"
        state_hash: "40976439597702951160099063499839224051666421320065585503408786782033021454333875421560713183281124512355169606125034137486963002957173185510178779993685306040295138896121677119949426892418466774252504944506623870144061313667160"
2019-08-08 18:13:23 UTC [Warn] Not rebroadcasting block $state_hash because it was received "3 slots too late"
        state_hash: "17343073004873779570821685139170883943665238833443853534521223437867520314855459091534958329306870552623356944010806850206166355538664241907874565828118791220162721982344678094050779200721743581384347114639196288690968056760637"
2019-08-08 18:13:23 UTC [Warn] Not rebroadcasting block $state_hash because it was received "2 slots too late"
        state_hash: "38181228581199865329173941456858076893678669463410682185200529262149965898088565267238424512550694268886736362885757595833561781716297989038665897899751859970782450803653548977578658560951232561748611920594807250442773745356752"
```

**Comment by nholland94** [comment]
@bkase those log messages are expected -- they just shouldn't be warnings. There is already an open issue from @es92 on this, I commented the same thing there.

I'm not 100% sure why the double catchup thing happens. It might be because the catchup rules right now aren't properly accounting for catchup jobs that are currently being performed outside of the scheduler, so the scheduler logs new dependencies of that catchup job as their own jobs. But this is just an educated guess, would need to dive deeper to confirm that is the case.

**Comment by ghost-not-in-the-shell** [comment]
This is not a bug. Bootstrap just downloads the snarked ledger and the root transition. After bootstrap finishes the transition frontier only have the root breadcrumb so we would see a difference between the `current_block_height` and `max_observed_block_length`. Without eager catchup, catchup won't happen immediately after bootstrap, so there would be a 10 min window that @bkase observe where the `sync status` shows synced but we are actually waiting for catchup to happen.

Next release would include @wu-s-john's sync status PR which mitigates this by clearly showing the `catchup` status. So we would see that after bootstrap we would do a catchup and then we are finally synced.
