### ISSUE TITLE
Gracefully handle files corrupted files or files from a past run of Coda within the same version

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#3149]
@cmr has done this on 003

@jkrauska to validate

**Comment by jkrauska** [comment]
Be careful with this.

We need to populate client_whitelist file BEFORE starting daemon.

If you delete the directory, client_whitelist will go away. (this has happened before)

Real solution: Make client_whitelist dynamic (updatable via API or soft reload)
See also #988

**Comment by imeckler** [comment]
We will do this and 

1. add a `--keep-config-file` flag.
2. Whenever we wipe, keep the old config directory in the new one under `~/.coda-config/old-configs/`
