### ISSUE TITLE
Refactor duplicated code idiom to single function on Public_key

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#3150]
This idiom:

```
(Public_key.Compressed.to_base58_check (Public_key.compress public_key))
```

Is repeated too often in our codebase, we should go through and refactor to use `Public_key.to_base58_check_compressed`

**Comment by enolan** [comment]
The serialization for uncompressed public keys compresses them first
anyway, we can just use Public_key.to_base58_check and it'll do the same
thing.
