### ISSUE TITLE
Daemon should not throw unhandled exception for incorrect password

### ISSUE THREAD

**Issue by AlexanderYudin** [MinaProtocol/mina#3187]
Coda Daemon crashed. The Coda Protocol developers would like to know why!

  Please:
    Open an issue:
      https://github.com/CodaProtocol/coda/issues/new

    Briefly describe what you were doing and attach the crash report /root/.coda-config/coda_crash_report_2019-08-13_23-17-53.545343.tar.xz

coda_crash_report_2019-08-13_23-17-53.545343.tar.xz
https://drive.google.com/file/d/1GcOKD-4z0a1dpDB9O_ZD8f7ypFcVRLxl/view?usp=sharing

Perhaps the problem was in the wrong password

**Comment by cmr** [comment]
Yes it was: 

```
(monitor.ml.Error
   "Could not read privkey-path /root/keys/my-wallet\
  \nwhile decrypting /root/keys/my-wallet: password is wrong or ciphertext is corrupt\
  \n"
  ("Raised at file \"lib/secrets/keypair.ml\", line 16, characters 2-99"
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
    "Caught by monitor coda"))
```

**Comment by cmr** [comment]
Keeping this open so we can replace the crash with a good error message!
