### ISSUE TITLE
Finding Strongest State on Launch

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#3225]
Currently when a node starts up, it (I believe) chooses a random peer, and attempts to bootstrap to it.

This presents two issues:
* if the peer has also not bootstrapped, the new node is stuck with the genesis state until a block is gossiped
* if any neighboring peer sends the new node a block stronger than the genesis block, the peer will believe and attempt to bootstrap to this potentially malicious state

A solution (I believe as is implemented in Cardano and others) is as follows:
* when connecting to the network, ask all peers for their strongest states
* bootstrap to the strongest of these states

**Comment by enolan** [comment]
*all* of them is an efficiency problem. we can probably get away with a
heuristic based on how old the block is in terms of slot.

**Comment by jkrauska** [comment]
Quick Concerns:
- adds an rpc that can be attacked (poll for current state)

- by design 'all' peers are not divulged (I believe) - so you can't be assured you're seeing ALL

- Is 'state' just block height or something more complicated?

- Can a bad actor spoof a stronger than real state to break new nodes from sync'ing?

- We should make sure not to accept impossible states. (eg block height >> total slots)

**Comment by enolan** [comment]
he just means the "best" block. You can't lie because you wouldn't be able
to produce the blockchain SNARK.

**Comment by es92** [comment]
by "all" I just mean your neighbors. Should only be a few kb for the snark + protocol state you need to decide which one is strongest, so seems pretty effiient

**Comment by imeckler** [comment]
The code as implemented sort of should do this, it isn't working. Some theories:

- This happens at startup when the peers is small

@wu-s-john could you take a look?

https://github.com/CodaProtocol/coda/blob/develop/src/lib/bootstrap_controller/bootstrap_controller.ml

**Comment by ghost-not-in-the-shell** [comment]
When doing eager bootstrap, we wait a certain amount of time to accumulate enough peers. For example, we synchronously wait for 30s for 8 peers to appear. If 30s passed and we still didn't have enough peers, we would trigger eager bootstrap eventually.
