### ISSUE TITLE
Eager catchup part 2

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#3230]
This is part 2 of eager catchup.

In part 1, I added a new field to external transition which is called `delta_transition_chain_proof` which include a Merkle list of length `delta - 1`. This field acts as an indicator for eager catchup.

In part 2, I would change the definition of `delta_transition_chain_proof` to only include ancestor transitions happened within `delta` slot. This would be more accurate than include `delta` ancestor transitions since not every slot would produce a transition. Doing this would require us to add yet another validation phase: validating delta_transition_chain_proof do include all ancestor transitions that happened within delta_slot.

**Comment by bkase** [comment]
@nholland94 wait for persistence first

**Comment by nholland94** [comment]
Persistence is in. Moving this back to discuss.
