### ISSUE TITLE
Nodes using `coda client set-staking` command produce no blocks

### ISSUE THREAD

**Issue by o1pranay** [MinaProtocol/mina#3234]
Several users tried to stake using this command and were not able to produce blocks.  Discovered this when troubleshooting with @garethtdavies. As soon as we switched to starting the daemon with `coda daemon -peer medium-rare.o1test.net:8303 -propose-key keys/my-key`, and entered the correct pw, block production worked.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
