### ISSUE TITLE
Simplify sending feedback from CLI after crash

### ISSUE THREAD

**Issue by o1pranay** [MinaProtocol/mina#3240]
Make it so that users can just send feedback by responding affirmative in the CLI (instead of having to manually attach logs and sending / adding to a github issue.

Eg. "Coda daemon crashed - would you like to send feedback to Coda developers? No private information will be shared - only debug logs. Please respond with y/n."

**Comment by cmr** [comment]
S3 upload maybe? @yourbuddyconner / @jkrauska do you have ideas on how to put this in practice?

**Comment by yourbuddyconner** [comment]
Yeah, this could easily be implemented with a Serverless service via AWS Lambda or similar. An API with basic rate-limiting via API Gateway or similar that does simple verification on the POST contents and shoots it into S3.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
