### ISSUE TITLE
We can still have uncomsumed cache after ledger_catchup fails

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#3261]
While working on this PR https://github.com/CodaProtocol/coda/pull/3251, I had ledger catchup jobs fail. The job failed because I was catching up to a block that is a descendant of a root (which does not make sense at all and I prevent this from happening). When this happens, catchup would fail. As a result, these blocks have not been fully consumed by `Cached_lib.Impl.ml`. This results in the an thrown exception when the blocks are garbage collected.

**Comment by ghost-not-in-the-shell** [comment]
After I reviewed how `collected_transitions` are added to transition frontier, I didn't see how this could possibly happens.

`collected_transitions` are dumped into `primary_transition_pipe`, and then `Processor` would validate the frontier dependencies. During this validation, disconnected transitions would be thrown away. Those should not even be added to cache.

**Comment by ghost-not-in-the-shell** [comment]
After discussed with John, I am convinced that there still could be leaks.

I also find out the reason why those out-dated transitions got into the catchup-scheduler. It's because in `validat_frontier_dependencies`, the order of checks are wrong:

```
      let%bind () =
        Result.ok_if_true
          (Transition_frontier.find frontier parent_hash |> Option.is_some)
          ~error:`Parent_missing_from_frontier
      in
      let%map () =
        (* need pervasive (=) in scope for comparing polymorphic variant *)
        let ( = ) = Pervasives.( = ) in
        Result.ok_if_true
          ( `Take
          = Consensus.Hooks.select
              ~logger:
                (Logger.extend logger
                   [ ( "selection_context"
                     , `String
                         "External_transition.Transition_frontier_validation.validate_frontier_dependencies"
                     ) ])
              ~existing:(Protocol_state.consensus_state root_protocol_state)
              ~candidate:(Protocol_state.consensus_state protocol_state) )
          ~error:`Not_selected_over_frontier_root
      in
```

The above code is problematic.

**Comment by bkase** [comment]
@ghost-not-in-the-shell 	move the two lines around now, the cache leak we'll wait on for now

**Comment by ghost-not-in-the-shell** [comment]
`transition_handler.processor` is leaking cache. See #3436
