### ISSUE TITLE
Receipt Chain Database should create proofs using the Merkle_list_prover

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#3294]
When I created the `Receipt_chain_database.prove` method, it did not use the `Merkle_list_prover` module because it wasn't created at the time. To reduce the amount of duplication in our code base, we should replace the `Merkle_list` proving methods in `Receipt_chain_database` with `Merkle_list_prover`.

**Comment by mrmr1993** [comment]
Receipt chain database no longer exists. Closing.
