### ISSUE TITLE
Update CONTRIBUTING.md to reflect git hooks requirements

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#3308]
When branching off current `develop` and performing a trivial documentation update I get the following error on a pre-commit hook:

```
git commit -m "Tiny little documentation update"
INFO Not using Docker
cd src;  dune exec --profile=dev app/reformat/reformat.exe -- -path . -check
File: ./lib/coda_graphql/coda_graphql.ml has needs to be ocamlformat-ed
make: *** [Makefile:96: check-format] Error 1
** REFUSING TO COMMIT: "$ make check-format" failed
```

The CONTRIBUTING.md should detail any git hooks system requirements.

**Comment by mrmr1993** [comment]
Git hooks were removed in https://github.com/MinaProtocol/mina/pull/12612. Closing.
