### ISSUE TITLE
Coda release/0.0.5-beta crash

### ISSUE THREAD

**Issue by AlexanderYudin** [MinaProtocol/mina#3317]
Briefly describe what you were doing and include the last 20 lines from .coda-config/coda.log and then paste the following:
Summary:
{"num_accounts":60,"blockchain_length":325,"highest_block_length_received":336,"uptime_secs":327,"ledger_merkle_root":"6hrsj5VcQT4UESLgz6JZnXieUvt1xGcEzJXCmXK26AhH612QHd7jzGjWmUznKUuu5vpUyfLqET5VobRGgwr9QLht9jqZ5zsFAWv5Lcyw3LwJn9uoNscijMH4Dp6jrssTYQRdWWHpGQGpe","state_hash":"4ApWF1cMjmVD6R73GptrJRLXBYzm1nVvwg5FbaAoptrnzeLKw3pituAGeGbLYSxmgEeAMVeWekFg8KGjs9qwDtvRLT4ZssUP1cisqiUwpJDCXiH26X8iPatUGafZ8W1jVhJsev8QHMNdL","commit_id":"7a5ecfdf03eb5405af814021b35bd188484c0259","conf_dir":"/root/.coda-config","peers":["134.209.49.152:8303","134.209.219.85:8303","54.188.108.191:10102","34.220.116.186:8303","95.216.192.84:8303","45.77.184.231:8303","82.69.152.196:8303","64.190.204.69:8303","95.165.167.193:8303"],"user_commands_sent":0,"snark_worker":"tNciQfhx9aXvE6VXAvZ7i84S8gwP5bqZuHam2b5dNacGGz95wVpxkQ5msDPSUvh5VCu7r1UMQ7Dq6oM1LADuzyYKaBV3J2ZQqoe2NF8rEujNm4ivkNhyhYZNf5f4TKaM3M2W2QLyNydGZz","snark_work_fee":0,"sync_status":"Catchup","propose_pubkeys":["tNciQfhx9aXvE6VXAvZ7i84S8gwP5bqZuHam2b5dNacGGz95wVpxkQ5msDPSUvh5VCu7r1UMQ7Dq6oM1LADuzyYKaBV3J2ZQqoe2NF8rEujNm4ivkNhyhYZNf5f4TKaM3M2W2QLyNydGZz"],"histograms":{"rpc_timings":{"get_staged_ledger_aux":{"dispatch":null,"impl":null},"answer_sync_ledger_query":{"dispatch":{"values":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"intervals":[[1000.0000000000024,1120.8369124213475],[1120.8369124213475,1256.2753842462162],[1256.2753842462162,1408.0798228294673],[1408.0798228294673,1578.2278410629742],[1578.2278410629742,1768.9360204744287],[1768.9360204744287,1982.6887874594593],[1982.6887874594593,2222.270778828482],[2222.270778828482,2490.803118306293],[2490.803118306293,2791.7840765718825],[2791.7840765718825,3129.134644531904],[3129.134644531904,3507.249613527801],[3507.249613527801,3931.054827917455],[3931.054827917455,4406.071355882021],[4406.071355882021,4938.487414434932],[4938.487414434932,5535.238985626919],[5535.238985626919,6204.100174164331],[6204.100174164331,6953.784483563077],[6953.784483563077,7794.058330200293],[7794.058330200293,8735.868274053559],[8735.868274053559,9791.483623609773],[9791.483623609773,10974.656272710938],[10974.656272710938,12300.79985159087],[12300.79985159087,13787.190525970045],[13787.190525970045,15453.19206009308],[15453.19206009308,17320.50807568877],[17320.50807568877,19413.464793123963],[19413.464793123963,21759.327938125545],[21759.327938125545,24388.65794253214],[24388.65794253214,27335.708066408028],[27335.708066408028,30638.87062800402],[30638.87062800402,34341.17715476905],[34341.17715476905,38490.85897106576],[38490.85897106576,43141.975525574766],[43141.975525574766,48355.11864384253],[48355.11864384253,54198.20188053226],[54198.20188053226,60747.34525456439],[60747.34525456439,68087.8668929195],[68087.8668929195,76315.39450161539],[76315.39450161539,85537.11114340746],[85537.11114340746,95873.15155141821],[95873.15155141821,107458.16716899523],[107458.16716899523,120443.08030415332],[120443.08030415332,134997.0502506233],[134997.0502506233,151309.67698889773],[151309.67698889773,169593.47117570712],[169593.47117570712,190086.62259939787],[190086.62259939787,213056.10316691053],[213056.10316691053,238801.14484612347],[238801.14484612347,267657.13787201134],[267657.13787201134,299999.99999999936]],"underflow":6,"overflow":0},"impl":null},"get_ancestry":{"dispatch":null,"impl":null},"get_transition_chain_proof":{"dispatch":{"values":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"intervals":[[1000.0000000000024,1120.8369124213475],[1120.8369124213475,1256.2753842462162],[1256.2753842462162,1408.0798228294673],[1408.0798228294673,1578.2278410629742],[1578.2278410629742,1768.9360204744287],[1768.9360204744287,1982.6887874594593],[1982.6887874594593,2222.270778828482],[2222.270778828482,2490.803118306293],[2490.803118306293,2791.7840765718825],[2791.7840765718825,3129.134644531904],[3129.134644531904,3507.249613527801],[3507.249613527801,3931.054827917455],[3931.054827917455,4406.071355882021],[4406.071355882021,4938.487414434932],[4938.487414434932,5535.238985626919],[5535.238985626919,6204.100174164331],[6204.100174164331,6953.784483563077],[6953.784483563077,7794.058330200293],[7794.058330200293,8735.868274053559],[8735.868274053559,9791.483623609773],[9791.483623609773,10974.656272710938],[10974.656272710938,12300.79985159087],[12300.79985159087,13787.190525970045],[13787.190525970045,15453.19206009308],[15453.19206009308,17320.50807568877],[17320.50807568877,19413.464793123963],[19413.464793123963,21759.327938125545],[21759.327938125545,24388.65794253214],[24388.65794253214,27335.708066408028],[27335.708066408028,30638.87062800402],[30638.87062800402,34341.17715476905],[34341.17715476905,38490.85897106576],[38490.85897106576,43141.975525574766],[43141.975525574766,48355.11864384253],[48355.11864384253,54198.20188053226],[54198.20188053226,60747.34525456439],[60747.34525456439,68087.8668929195],[68087.8668929195,76315.39450161539],[76315.39450161539,85537.11114340746],[85537.11114340746,95873.15155141821],[95873.15155141821,107458.16716899523],[107458.16716899523,120443.08030415332],[120443.08030415332,134997.0502506233],[134997.0502506233,151309.67698889773],[151309.67698889773,169593.47117570712],[169593.47117570712,190086.62259939787],[190086.62259939787,213056.10316691053],[213056.10316691053,238801.14484612347],[238801.14484612347,267657.13787201134],[267657.13787201134,299999.99999999936]],"underflow":1,"overflow":0},"impl":null},"get_transition_chain":{"dispatch":{"values":[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"intervals":[[1000.0000000000024,1120.8369124213475],[1120.8369124213475,1256.2753842462162],[1256.2753842462162,1408.0798228294673],[1408.0798228294673,1578.2278410629742],[1578.2278410629742,1768.9360204744287],[1768.9360204744287,1982.6887874594593],[1982.6887874594593,2222.270778828482],[2222.270778828482,2490.803118306293],[2490.803118306293,2791.7840765718825],[2791.7840765718825,3129.134644531904],[3129.134644531904,3507.249613527801],[3507.249613527801,3931.054827917455],[3931.054827917455,4406.071355882021],[4406.071355882021,4938.487414434932],[4938.487414434932,5535.238985626919],[5535.238985626919,6204.100174164331],[6204.100174164331,6953.784483563077],[6953.784483563077,7794.058330200293],[7794.058330200293,8735.868274053559],[8735.868274053559,9791.483623609773],[9791.483623609773,10974.656272710938],[10974.656272710938,12300.79985159087],[12300.79985159087,13787.190525970045],[13787.190525970045,15453.19206009308],[15453.19206009308,17320.50807568877],[17320.50807568877,19413.464793123963],[19413.464793123963,21759.327938125545],[21759.327938125545,24388.65794253214],[24388.65794253214,27335.708066408028],[27335.708066408028,30638.87062800402],[30638.87062800402,34341.17715476905],[34341.17715476905,38490.85897106576],[38490.85897106576,43141.975525574766],[43141.975525574766,48355.11864384253],[48355.11864384253,54198.20188053226],[54198.20188053226,60747.34525456439],[60747.34525456439,68087.8668929195],[68087.8668929195,76315.39450161539],[76315.39450161539,85537.11114340746],[85537.11114340746,95873.15155141821],[95873.15155141821,107458.16716899523],[107458.16716899523,120443.08030415332],[120443.08030415332,134997.0502506233],[134997.0502506233,151309.67698889773],[151309.67698889773,169593.47117570712],[169593.47117570712,190086.62259939787],[190086.62259939787,213056.10316691053],[213056.10316691053,238801.14484612347],[238801.14484612347,267657.13787201134],[267657.13787201134,299999.99999999936]],"underflow":0,"overflow":0},"impl":null}},"external_transition_latency":{"values":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0],"intervals":[[1000.0000000000024,1120.8369124213475],[1120.8369124213475,1256.2753842462162],[1256.2753842462162,1408.0798228294673],[1408.0798228294673,1578.2278410629742],[1578.2278410629742,1768.9360204744287],[1768.9360204744287,1982.6887874594593],[1982.6887874594593,2222.270778828482],[2222.270778828482,2490.803118306293],[2490.803118306293,2791.7840765718825],[2791.7840765718825,3129.134644531904],[3129.134644531904,3507.249613527801],[3507.249613527801,3931.054827917455],[3931.054827917455,4406.071355882021],[4406.071355882021,4938.487414434932],[4938.487414434932,5535.238985626919],[5535.238985626919,6204.100174164331],[6204.100174164331,6953.784483563077],[6953.784483563077,7794.058330200293],[7794.058330200293,8735.868274053559],[8735.868274053559,9791.483623609773],[9791.483623609773,10974.656272710938],[10974.656272710938,12300.79985159087],[12300.79985159087,13787.190525970045],[13787.190525970045,15453.19206009308],[15453.19206009308,17320.50807568877],[17320.50807568877,19413.464793123963],[19413.464793123963,21759.327938125545],[21759.327938125545,24388.65794253214],[24388.65794253214,27335.708066408028],[27335.708066408028,30638.87062800402],[30638.87062800402,34341.17715476905],[34341.17715476905,38490.85897106576],[38490.85897106576,43141.975525574766],[43141.975525574766,48355.11864384253],[48355.11864384253,54198.20188053226],[54198.20188053226,60747.34525456439],[60747.34525456439,68087.8668929195],[68087.8668929195,76315.39450161539],[76315.39450161539,85537.11114340746],[85537.11114340746,95873.15155141821],[95873.15155141821,107458.16716899523],[107458.16716899523,120443.08030415332],[120443.08030415332,134997.0502506233],[134997.0502506233,151309.67698889773],[151309.67698889773,169593.47117570712],[169593.47117570712,190086.62259939787],[190086.62259939787,213056.10316691053],[213056.10316691053,238801.14484612347],[238801.14484612347,267657.13787201134],[267657.13787201134,299999.99999999936]],"underflow":0,"overflow":0},"accepted_transition_local_latency":null,"accepted_transition_remote_latency":null,"snark_worker_transition_time":null,"snark_worker_merge_time":null},"consensus_time_best_tip":"epoch=1, slot=187","consensus_time_now":"epoch=1, slot=200","consensus_mechanism":"proof_of_stake","consensus_configuration":{"delta":2,"k":10,"c":8,"c_times_k":80,"slots_per_epoch":240,"slot_duration":300000,"epoch_duration":72000000,"acceptable_network_delay":600000}}
Status:
{"OS_type":"Unix","Release":"4.15.0-55-generic","Machine":"x86_64","Sys_name":"Linux","Exception":"(\"Out of memory\")","Command":"Command: (coda daemon -peer something-snarky.o1test.net:8303 -run-snark-worker\n tNciQfhx9aXvE6VXAvZ7i84S8gwP5bqZuHam2b5dNacGGz95wVpxkQ5msDPSUvh5VCu7r1UMQ7Dq6oM1LADuzyYKaBV3J2ZQqoe2NF8rEujNm4ivkNhyhYZNf5f4TKaM3M2W2QLyNydGZz\n -snark-worker-fee 0 -propose-key /root/keys/my-wallet)"}

**Comment by mrmr1993** [comment]
This was an out-of-memory crash, but there's not enough info here to say anything further, and the time has passed to collect more info. Closing.
