### ISSUE TITLE
Decrease trust score if a peer sends you old best tip

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#3327]
During initialization, a node would collect best tips from peers. A peer can cheat on us by sending transitions that's older than best-tip. Although this kind of attack is mitigated by the fact that we would select the best one among all the `best tips` that we collected, this still leave some space for malicious users.

We should decrease the trust score of a peer if the best tip they send is much older than others'.

Also I believe `get_best_tip` should returns an option. For example, if a bootstrapping peer received this rpc request, it should not provide its old best_tip as an answer because, in this scenario, the best_tip itself is pretty old and of no use to other nodes in the network.

**Comment by bkase** [comment]
@nholland94 and @ghost-not-in-the-shell to discuss

**Comment by ghost-not-in-the-shell** [comment]
After discussed with @nholland94, we decided to do the following:

Allow a peer to reply `None` to the `get_best_tip` rpc call, but decrease a little amount of trust score off that peer. And decrease a larger amount of trust score of peers that reply with an older best_tip than everyone else.

The rationale behind this is that we should encourage peers to participate. Peers that refuse to provide `best_tip` info would eventually get banned by the network.

This is not urgent for now. In the future,  when we decide to implement this, we should pick the amount of `trust_score` to be deducted carefully because if a node is constantly on and off, then it would probably get banned.
