### ISSUE TITLE
CRASH - something snarky - Coinbase.create: fee transfer was too high

### ISSUE THREAD

**Issue by jkrauska** [MinaProtocol/mina#3347]
Observed on proposer nodes:
```jq
{
  "timestamp": "2019-09-02 02:10:00.020806Z",
  "level": "Fatal",
  "source": {
    "module": "Init__Coda_run",
    "location": "File \"app/cli/src/init/coda_run.ml\", line 411, characters 56-63"
  },
  "message": "Unhandled top-level exception: $exn\nGenerating crash report",
  "metadata": {
    "exn": "\"Coinbase error: Coinbase.create: fee transfer was too high \\n\"",
    "pid": 31656
  }
}
```

**Comment by jkrauska** [comment]
[test-coda-CRASH-2019-09-02_10-36-12-coda.log.gz](https://github.com/CodaProtocol/coda/files/3576018/test-coda-CRASH-2019-09-02_10-36-12-coda.log.gz)

**Comment by yourbuddyconner** [comment]
Relates to #1730

**Comment by deepthiskumar** [comment]
The fee for snark work is currently capped at coinbase amount because the work for adding a coinbase is being paid for by the coinbase amount. We should not have a coinbase in that case instead of crashing?

**Comment by jkrauska** [comment]
probably not crashing -- as I think this eventually can cascade and crash all proposer nodes.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
