### ISSUE TITLE
CRASH - something snarky - Unhandled top-level exception

### ISSUE THREAD

**Issue by jkrauska** [MinaProtocol/mina#3348]
Crash on proposers on something snarky (after previous condition of fee to high)
```
{
  "timestamp": "2019-09-03 18:08:38.513655Z",
  "level": "Fatal",
  "source": {
    "module": "Init__Coda_run",
    "location": "File \"app/cli/src/init/coda_run.ml\", line 411, characters 56-63"
  },
  "message": "Unhandled top-level exception: $exn\nGenerating crash report",
  "metadata": {
    "exn": "\"Assert_failure lib/proposer/proposer.ml:489:16\"",
    "pid": 5688
  }
}
```

[test-coda-CRASH-2019-09-03_18-10-25-coda.log.gz](https://github.com/CodaProtocol/coda/files/3576048/test-coda-CRASH-2019-09-03_18-10-25-coda.log.gz)

**Comment by imeckler** [comment]
This happened on the same system as https://github.com/CodaProtocol/coda/issues/3347 and the invalid proof.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
