### ISSUE TITLE
Memory Functor

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#3367]
I have some existing art for a functor pattern around tracking memory allocations. The idea around this pattern is that we have many resources which we are creating and freeing in OCaml implicitly (via GC + mutable accumulative data structures), and our current instrumentation for memory usage does not give us very granular detail as to where memory leaks are happening, or even what they are correlated with. The "memory functor" pattern consists of creating various functors which will wrap components in the system with create/delete cycles or mutable accumulative data structures, refcounting values and surfacing them through our prometheus metrics (the `Coda_metrics` module). So far, I have implemented a functor for singleton hash tables (hash tables for which only 1 value will ever be allocated at one time during runtime). This issue is to expand this for more use cases (non singleton hash tables, simple create/delete values via GC finalizers, any other mutable data structures we use), and then to wrap most of our system with calls to this functor. We would also want to add a new compile time config variable for disabling or enabling these metrics, so that we can turn this all off for release builds (though we would want it on for testnets, at least for now).

**Comment by imeckler** [comment]
Can we come up with a list of candidate instantiations and then sort them by likelihood of there being a leak there?

**Comment by nholland94** [comment]
Closed by #6719
