### ISSUE TITLE
Transaction fee to cancel absurdly high

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#3427]
After trying to cancel a transaction using `coda client cancel-transaction` the following was returned:

```
Fee to cancel transaction is 18446744073709551523 coda.
Failed to cancel transaction: Invalid user command: account balance is too low
```

I had 20 transactions in a pending state, nonces 80-100 respectively. I managed to cancel tx with nonce 80 with a fee of 5 and also tx with a nonce of 81 with a fee of 2. I then tried nonce 100 and this was the result...

I am able to replicate this trying again to repeat the same cancellation.

**Comment by mrmr1993** [comment]
Transaction replacement logic has since been rewritten. Closing.
