### ISSUE TITLE
Possible reason for partition test would fail

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#3438]
We are going to launch a Testnet that testing the merge of forked blockchains very soon. I think this test would probably fail.

image we have 2 long chains, and they have been diverged for more than two epoch. And Assuming their roots and best tips are in the same epoch.

Assuming 
the `min_epoch_length` of nodes in chain *A* is 30 and
the `min_epoch_length` of nodes in chain *B* is 40.

The following 2 scenarios would both prevent fork being merged:
1. Let's say nodes in chain *A* received a block from chain *B*, then nodes in chain *A* would take it, but bootstrap would not be trigger if the difference between `blockchain_length` of *A* and *B* is not great enough. The block would be added to the catchup scheduler because it has no parent in the frontier of *A* and catchup would fail. And thus the network would keep forking.

2. Let's say nodes in chain *B* received a block from chain *A*, then nodes in chain *B* would always ban the sender because that block would not be selected over the root of the nodes in chain *B*. Eventually every node in chain *B* would ban nodes in chain *A* and the network would keep forked.

We should at least modify the rule for bootstrap before doing this test because bootstrap would not happen if two chains are around the same length.

**Comment by jkrauska** [comment]
@ghost-not-in-the-shell if the nodes are diverged for less than an epoch, would it work?

I was only planning on being isolated for an hour or so. (way less than an epoch on testnet)

**Comment by ghost-not-in-the-shell** [comment]
> @ghost-not-in-the-shell if the nodes are diverged for less than an epoch, would it work?
> 
> I was only planning on being isolated for an hour or so. (way less than an epoch on testnet)

Things would be fine if nodes are diverged shortly. If they still have the same root, then bootstrap would not be required. But if the root is different (which means we really have two different chains on the network), then things would break.

**Comment by ghost-not-in-the-shell** [comment]
I give a more detailed analysis in #3445.

**Comment by imeckler** [comment]
Let's have a discussion about this?

**Comment by ghost-not-in-the-shell** [comment]
> Let's have a discussion about this?

Sure, we can schedule a short meeting on this.
