### ISSUE TITLE
(this is a bootstrap meeting #4028 )     (jiawei to make meeting for this) Current bootstrap rules doesn't work very well when network is forked

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#3445]
If we have two different chains of similar length on the testnet, the fork would not be merged unless the weaker chain bootstrap to the stronger one. But bootstrap would never be triggered if two chains have similar length.

Assuming chain A has 60% of stake and chain B has 40%.

chain B won't bootstrap to chain A until the blockchain length of A is `k + delta` greater than length of B. This would eventually happen because chain A has more stake and it would propose more often. But it would take a lot of time. For example, in this case, I can give an estimation for the time it takes:

Assuming the slot fill rate of chain A is 0.6 and slot fill rate of B is 0.4,
then the relative speed between A and B is 0.2 block/slot, which means it took 5 slot for A to produce 1 more block than B. And in order to gain enough advantage over B, A needs at least `k + delta` blocks, which take `5 slot/block * (k + delta) block = 5 * (k + delta) slot`, which in terms take `5 min / slot * 5 * (k + delta) slot = 25 * (k + delta) min = 300 min` using the value of k and delta in our current testnet.

If `k` is larger, this would take even longer. Using the same calculation, when k = 3000, the time for two chain to merge is about 52 days. Things would be better if block_window_duration is shorter. If block_window_duration is 20 times smaller, then it would only take 2 days to converge.

I would assuming chains would not appear very often when k is large. So this may not be a problem.

**Comment by cmr** [comment]
We discussed this in the bootstrap meeting and have put this off, this condition shouldn't occur.
