### ISSUE TITLE
Coda crashed on launch

### ISSUE THREAD

**Issue by blacksausage** [MinaProtocol/mina#3463]
subrosa:~ henryrobinson$ coda daemon -peer golden-hour.o1test.net:8303

2019-09-21 22:28:01 UTC [Info] Coda daemon is booting up; built with commit "92a3c1eaa0ebbd2d8403edf8ec58c3d77faa21cf" on branch "master"
2019-09-21 22:28:01 UTC [Info] Booting may take several seconds, please wait
2019-09-21 22:28:01 UTC [Info] OCaml memory statistics
2019-09-21 22:28:01 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: "(monitor.ml.Error\n  (Failure\n    \"IO error: While lock file: /Users/henryrobinson/.coda-config/trust/LOCK: Resource temporarily unavailable\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"lib/rocksdb/database.ml\\\", line 16, characters 34-63\"\n    \"Called from file \\\"lib/trust_system/peer_trust.ml\\\", line 52, characters 15-44\"\n    \"Called from file \\\"app/cli/src/coda.ml\\\", line 613, characters 28-65\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 170, characters 6-47\"\n    \"Caught by monitor coda\"))"

  ☠  Coda daemon crashed. The Coda Protocol developers would like to know why!

  Please:
    Open an issue:
      <https://github.com/CodaProtocol/coda/issues/new>

    Briefly describe what you were doing and attach the crash report /Users/henryrobinson/.coda-config/coda_crash_report_2019-09-21_22-28-01.733720.tar.gz
[coda_crash_report_2019-09-21_22-28-01.733720.tar.gz](https://github.com/CodaProtocol/coda/files/3639145/coda_crash_report_2019-09-21_22-28-01.733720.tar.gz)

**Comment by psteckler** [comment]
Were you able to reproduce the error by running the daemon a second time?

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
