### ISSUE TITLE
total currency is not increasing in transition frontier visualization, but coinbases are being paid

### ISSUE THREAD

**Issue by enolan** [MinaProtocol/mina#3482]
I can see the balance of the proposer I'm running increasing, but the Graphviz visualization says that every block has the same total currency.

**Comment by imeckler** [comment]
@nholland94 you saw total currency increasing?

**Comment by imeckler** [comment]
@enolan will look where the viz file is getting its state from

**Comment by imeckler** [comment]
@wu-s-john do you know where this discrepancy between what the visualization sees and what @enolan is seeing might be coming from?
