### ISSUE TITLE
In-memory Logger.t collection

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#3508]
Sometimes ([for example](https://github.com/CodaProtocol/coda/pull/3328#discussion_r328265193)) you want to collect logs but don't want to bother printing them unless something unusual happens. Logger.t currently doesn't support this, but I don't think it'd be too  hard to add an in-memory transport.

**Comment by mrmr1993** [comment]
This now exists and is used for the integration tests. Closing.
