### ISSUE TITLE
Spending coinbase shortly after producing block

### ISSUE THREAD

**Issue by o1pranay** [MinaProtocol/mina#3533]
Talked to @deepthiskumar and @ghost-not-in-the-shell about an edge case where a block producer issues a transaction spending coinbase funds immediately after winning a block and applying the transition to their ledger. 

In the worst case, they gossip the txn, but nobody else will have applied the block to their states (due to latency, time it takes to apply block, etc), and the transaction is rejected by everyone else and trust score goes down.

Do we need to do anything to ensure that block producers don't get punished for trying to spend tokens that they legitimately think they've won?

**Comment by enolan** [comment]
The periodic transaction rebroadcast should make this work fine.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
