### ISSUE TITLE
Coda Daemon is crashed

### ISSUE THREAD

**Issue by StarLI-Trapdoor** [MinaProtocol/mina#3534]
The following command is used to run one snark worker:

coda daemon  -peer filet-mignon.o1test.net:8303 -run-snark-worker tNci4dpqGY9UsWrCNPJEua6FdGyk2KFqBC8ovC5EdGZ8gUiVQcKw8tdVEBma86yGiXY4gDFdwHJSJuCnzn4ZyH9CEuz8FoGnRgpzUj5UVjMR62GDB2UJNo1B5qC2gLZKK4bXRc9XU1wkqT -snark-worker-fee 1

And the crash log is attached.
[coda_crash_report_2019-09-27_03-08-11.384908.tar.gz](https://github.com/CodaProtocol/coda/files/3674586/coda_crash_report_2019-09-27_03-08-11.384908.tar.gz)

**Comment by StarLI-Trapdoor** [comment]
I just followed the link to launch the testnet: 

https://codaprotocol.com/docs/getting-started/

My cloud machine configuration is: 

CPU - 4 core, 2.5G
Memeory - 8G

**Comment by o1pranay** [comment]
Thanks @StarLI-Trapdoor we're looking into this issue!

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
