### ISSUE TITLE
CLI logging nits

### ISSUE THREAD

**Issue by o1pranay** [MinaProtocol/mina#3546]
Several minor CLI suggestions:

1.
```
SNARK worker:               None
SNARK work fee:             1
```
Suggestion: don't show snark worker fee if no snark worker running. Reason being, don't want user to think there is a fee being levied on them, if there is some misunderstanding on what this is

2. `[Info] Generated transition $state_hash was accepted into transition frontier`
Suggestion: `[Info] Newly produced block $state_hash was accepted into transition frontier`

3. `[Error] Broadcasting message "new state" to $peer failed: $error`
Suggestion: `[Error] Broadcasting new block to $peer failed: $error`

4. `Waiting for transition $state_hash to be inserted into frontier`
Suggestion: `Waiting for block $state_hash to be inserted into transition frontier`

5. remove `Next proposal:              None this epoch… checking at in 20.729h`
when block producer is not running

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
