### ISSUE TITLE
Wrap remaining instances of `Process.wait`

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#3570]
`Process.wait` can raise, so it should be wrapped in `Monitor.try_with`.

#3568 wrapped a couple of uses of that, one of which could affect the testnet.

There are some others in `Coda_net2` and `testone` which also should be wrapped.

There are a couple in `Kademlia`, but since that's going away, probably not a concern.

I can do these, but maybe @cmr wants to do the `Coda_net2` bits.

**Comment by mrmr1993** [comment]
This is done, all of our `Process.wait`s are wrapped with `try_with`s of some form or another.
