### ISSUE TITLE
make macos-setup fails without submodules

### ISSUE THREAD

**Issue by vitaliel** [MinaProtocol/mina#3574]
Hi, 

`make macos-setup` command fails because of ocaml-extlib. If submodules were not updated, It starts the editor with a package template.

Can we add in README-dev.md about submodule init
```
git submodule init
git submodule update
```

**Comment by o1pranay** [comment]
Thanks for reporting @vitaliel, we'll update the readme. Do you have a discord username we can use to add you to the leaderboard (https://codaprotocol.com/testnet.html)?

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
