### ISSUE TITLE
Remove duplicate signatures that appear in code implementations and their .mli counterparts

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#3603]
There are several parts of our codebase that have their module type signatures written in their .ml file and is duplicated across to their .mli file.

This is a bad reuse of code. What we can do instead is have these files share the type signatures from an "Intf" file. This has been done throughout the codebase in several places. For example, `external_transition.ml` and `external_transition_intf.ml`.

If you see any duplicated interfaces, please try to deduplicate them or note them in this issue

Duplicated Interfaces:
- [ ] currency.ml

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
