### ISSUE TITLE
libp2p security and trust system tasks

### ISSUE THREAD

**Issue by enolan** [MinaProtocol/mina#3652]
Mostly copy pasting from my comment in #2450:

# Security issues
OK, here is a - probably incomplete - list of trust system/security issues with libp2p that need to be resolved.

* #2782 
* When we ban someone, that needs to be reflected in libp2p land. They should be removed from our routing table so we don't contact them again or introduce them to other peers, we should reject gossip messages from them, and reject incoming streams from them. Not sure what the design for this should be, it'd be best if we didn't have two ban lists, so maybe the libp2p helper should do an upcall for every incoming message/stream initiation to check if the sender is banned.
* libp2p version of #3084 
* There are various things you can do at the libp2p level that should be punishable: connecting to a service that doesn't exist, making tons of streams, overgossipping, anything that violates the protocol design in terms of connection management, gossip or peer discovery, probably more. If a peer does one of those things that information should be transmitted to the coda daemon so it can update the trust database.
* Disconnecting streams at invalid times should be punishable as well

**Comment by aneesharaines** [comment]
Out of date for current arch
