### ISSUE TITLE
RFC for reducindg RAM usage of scan-state

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#3676]
@nholland94 and @deepthiskumar calculated this and it is bad

**Comment by enolan** [comment]
Where does the theoretical ram usage come from? If it's mostly from the hashes in the sparse ledgers then adding the sharing described in #3109 should help quite a bit.

**Comment by imeckler** [comment]
@deepthiskumar can you put the usage on a forum post and link it here?
