### ISSUE TITLE
Coda daemon crashed (WNOHANG)

### ISSUE THREAD

**Issue by UbikCapital** [MinaProtocol/mina#3706]
2019-10-20 22:54:23 UTC [Info] Restarting Kademlia
2019-10-20 22:54:24 UTC [Info] Daemon child process 28754 terminated with exit code 0
2019-10-20 22:54:24 UTC [Info] Daemon child process 28364 terminated after receiving signal "sigterm"
2019-10-20 22:54:24 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error\n  (Unix.Unix_error \"No child processes\" waitpid\n    \"((mode (WNOHANG)) (pid 28364))\")\n  (\"Raised at file \\\"src/result.ml\\\", line 158, characters 17-26\"\n    \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 170, characters 6-47\"\n    \"Caught by monitor coda\"))"

  ☠  Coda daemon crashed. The Coda Protocol developers would like to know why!

  Please:
    Open an issue:
      <https://github.com/CodaProtocol/coda/issues/new>

**Comment by o1pranay** [comment]
hey @UbikCapital thanks for reporting this -- we're tracking this issue here: https://github.com/CodaProtocol/coda/issues/3520

Could you kindly share the steps to reproduce this?

**Comment by mrmr1993** [comment]
Fixed by #7611, closing.
