### ISSUE TITLE
Integrate Persistent_frontier.Database with versioning system

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#3736]
https://github.com/CodaProtocol/coda/pull/3439 added `Persistent_frontier.Database`, which is currently unversioned. The database already has the concept of a version baked into it (storing a version in the db so that migrations can be performed in the future), but this version is just hard coded to 1 right now. This should be integrated into the ppx versioning system we are using, if possible.l

**Comment by nholland94** [comment]
We *need* to do this if we ever do any changes to the database representation, but this can wait until that day comes.

**Comment by psteckler** [comment]
The change proposed in #8372 should make this simple.

**Comment by mrmr1993** [comment]
Done in c42aaf6689c. Closing.
