### ISSUE TITLE
getpeername "Invalid argument"/"Transport endpoint is not connected" exception

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#3751]
We've seen several of these, on both macOS ("Invalid argument") and Linux ("Transport endpoint not connected"). 

from macOS: #3747 [crashlog](https://github.com/CodaProtocol/coda/files/3764766/coda_crash_report_2019-10-23_19-21-26.908569.tar.gz), #3730 [crashlog](https://github.com/CodaProtocol/coda/files/3762996/coda_crash_report_2019-10-23_10-51-19.776228.tar.gz)

from linux: [crashlog from discord DM](https://github.com/CodaProtocol/coda/files/3765017/coda_crash_report_2019-10-23_10-51-25.652084.tar.gz), #3749 [crashlog](https://github.com/CodaProtocol/coda/files/3764954/coda_crash_report_2019-10-23_18-48-59.479740.tar.gz)

Reportedly, having a SNARK worker makes this worse.

**Comment by cmr** [comment]
The only call to `getpeername` I see in our deps is in rpc (big surprise) but inside a function that we don't call. rpc_parallel, however, DOES. but those connections should only be to localhost? are they getting closed? more to investigate...

**Comment by yourbuddyconner** [comment]
Had a Snark Coordinator crash with this error in `rising-phoenix`

https://gist.github.com/yourbuddyconner/c08694ccf215592386ed888c8b0ca8d1

**Comment by mrmr1993** [comment]
Folding this into #4276, which appeared in a more recent version. We lose the mac version in the title by doing this, but we're not currently supporting mac builds at the moment.
