### ISSUE TITLE
Coda node crash report

### ISSUE THREAD

**Issue by victorxu0411** [MinaProtocol/mina#3756]
[coda_crash_report_2019-10-24_14-41-01.201982.tar.gz](https://github.com/CodaProtocol/coda/files/3768142/coda_crash_report_2019-10-24_14-41-01.201982.tar.gz)

it crashed when I try to staking coda.

**Comment by love-choco** [comment]
Hey victor, what is your Discord ID? (You're one of the bug bounty winners of release 2.3!)

**Comment by victorxu0411** [comment]
Hi,

Great to hear that. my Discord ID is: Viktor#0766
________________________________
发件人: love-choco <notifications@github.com>
发送时间: 2019年11月16日 4:45
收件人: CodaProtocol/coda <coda@noreply.github.com>
抄送: victorxu0411 <volvos609@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [CodaProtocol/coda] Coda node crash report (#3756)


Hey victor, what is your Discord ID? (You're one of the bug bounty winners of release 2.3!)

―

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
