### ISSUE TITLE
Versioning of Binable.Of_binable

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#3757]
Most versioned types use `deriving bin_io`. A few use `include Binable.Of_Binable (M) (...)`, where the serialization depends on existing code in `M`. If the serialization of `M` changes, then the serialization of the containing module changes.

Therefore, we should 
  - check that `M` is a specific versioned module
  - detect changes where `Of_binable` is applied

Specifically, we need to detect changes to the version of `M`, and the `to_binable` function.

**Comment by mrmr1993** [comment]
This was completed by #4534. Closing.
