### ISSUE TITLE
Seed peers should be lower friction to set

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#3761]

**Comment by imeckler** [comment]
The issue is we have different testnets and the names of seed nodes may change.

We can set default list of seed peers which we ship with the binary or in a separate with the binary, or on a server somewhere which @bkase believes in.

**Comment by cmr** [comment]
we want to put seed peers in a daemon.json that we ship with the binary. We need:

1. To load `/etc/coda.json` or something
2. Peers in the json at all
