### ISSUE TITLE
Node don't produce blcok ( no crash\tx no coinbase)

### ISSUE THREAD

**Issue by wjdfx** [MinaProtocol/mina#3776]
AWS: c5.4xlarge
Some mistakes happened when it was my turn to produce block. I already run svever 3 days, no crash, but only produce 2 block.

Mypublic key info:
https://codaexplorer.garethtdavies.com/wallet/tdNDowo9QyHT1KnkQP4173GMona8MdrQ7UbG1E1BxdUgyxAMh9KK2w9tfcBcfxWgQzH29JtZpFZ7MekRtytfR5no6RjdnKdgrx5PByfEXhtZzX3HX74qVEL33qnDfdf6gqMpCxjjgLHECY

jkrauskaToday at 12:20 PM :
we might be able to learn something about why no coinbase or txns based on your logs
please zip them up and send in an issue.. ?

LOG：
[coda.tar.gz](https://github.com/CodaProtocol/coda/files/3770370/coda.tar.gz)

Fri Oct 25 9:00 UTC 2019(about), The problem Still miss a prodece block.

discord: niuniu#9001

**Comment by o1pranay** [comment]
@cmr @wu-s-john seems like this is the same error from #3162 -- any idea if this is fixed? saw the other issue was closed out 

```
"Exception":"(monitor.ml.Error\n  (Unix.Unix_error \"Transport endpoint is not connected\" getpeername\n    \"((fd 64))\")\n  (\"Raised at file \\\"src/core_unix.ml\\\", line 50, characters 4-43\"\n    \"Called from file \\\"src/unix_syscalls.ml\\\", line 1075, characters 6-49\"\n    \"Called from file \\\"src/rpc.ml\\\", line 236, characters 26-49\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\")
```

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
