### ISSUE TITLE
Snark-worker node crash

### ISSUE THREAD

**Issue by wjdfx** [MinaProtocol/mina#3785]
AWS: c5.4xlarge
Host only 1 service

Run command:
coda daemon -discovery-port 8303 -peer /ip4/52.39.56.50/tcp/8303/ipfs/12D3KooWHMmfuS9DmmK9eH4GC31arDhbtHEBQzX6PwPtQftxzwJs -peer /ip4/18.212.230.102/tcp/8303/ipfs/12D3KooWAux9MAW1yAdD8gsDbYHmgVjRvdfYkpkfX7AnyGvQaRPF -peer /ip4/52.13.17.206/tcp/8303/ipfs/12D3KooWCZA4pPWmDAkQf6riDQ3XMRN5k99tCsiRhBAPZCkA8re7 -run-snark-worker tdNDowo9QyHT1KnkQP4173GMona8MdrQ7UbG1E1BxdUgyxAMh9KK2w9tfcBcfxWgQzH29JtZpFZ7MekRtytfR5no6RjdnKdgrx5PByfEXhtZzX3HX74qVEL33qnDfdf6gqMpCxjjgLHECY -snark-worker-fee 20

[coda_crash_report_2019-10-25_12-54-36.484096.tar.gz](https://github.com/CodaProtocol/coda/files/3774968/coda_crash_report_2019-10-25_12-54-36.484096.tar.gz)

discord: niuniu#9001

**Comment by o1pranay** [comment]
@cmr @wu-s-john seems like this is the same error from #3162 -- any idea if this is fixed? saw the other issue was closed out 

```
"Exception":"(monitor.ml.Error\n  (Unix.Unix_error \"Transport endpoint is not connected\" getpeername\n    \"((fd 64))\")\n  (\"Raised at file \\\"src/core_unix.ml\\\", line 50, characters 4-43\"\n    \"Called from file \\\"src/unix_syscalls.ml\\\", line 1075, characters 6-49\"\n    \"Called from file \\\"src/rpc.ml\\\", line 236, characters 26-49\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\")
```

**Comment by mrmr1993** [comment]
Closing this as a dup of #4276. which appeared in a more recent version.
