### ISSUE TITLE
Coda daemon crash, happened overnight, no user input at the time

### ISSUE THREAD

**Issue by byrongibson** [MinaProtocol/mina#3787]
This crash happened when I wasn't interacting with Coda, was either asleep or doing other stuff.  Crash report attached.

[coda_crash_report_2019-10-26_06-21-11.228574.tar.gz](https://github.com/CodaProtocol/coda/files/3775465/coda_crash_report_2019-10-26_06-21-11.228574.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
