### ISSUE TITLE
Coda daemon crashed, network seems to have gone down before GH

### ISSUE THREAD

**Issue by Cris-F** [MinaProtocol/mina#3788]
Daemon crashed without any user input.
This was after GH should have finished.
Other users reported daemons crashing at the same time.
[coda_crash_report_2019-10-27_05-30-00.344728.tar.gz](https://github.com/CodaProtocol/coda/files/3775599/coda_crash_report_2019-10-27_05-30-00.344728.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
