### ISSUE TITLE
 Coda daemon crashed

### ISSUE THREAD

**Issue by AlexanderYudin** [MinaProtocol/mina#3848]
[coda_crash_report_2019-11-06_18-02-37.445105.tar.gz](https://github.com/CodaProtocol/coda/files/3816109/coda_crash_report_2019-11-06_18-02-37.445105.tar.gz)

**Comment by AlexanderYudin** [comment]
forgot to forward ports

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
