### ISSUE TITLE
Update the consensus selection rule to use protocol state hash as a tie breaker

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#3866]

**Comment by es92** [comment]
Quick note on this: if multiple blocks from the same block producer can be broadcasted, there could be a potential attack to DDOS the network. The adversary just creates a ton of blocks, sorts them by weakest -> strongest, and then sends out the blocks, from the weakest to strongest. Nodes will see the blocks in order, and rebroadcast all of them, DDOSing the network.

I think it would be fine if each node just keeps the first from each block producer; Then an adversary could create a short fork, but should be quickly resolved with Ouroboros and a large fraction honest.

**Comment by imeckler** [comment]
@cmr @nholland94 propose broadcasting all blocks even if they are duplicated.

**Comment by emberian** [comment]
Nathan and I re-discussed this recently. First, a quick breakdown on some of the possibilities for duplicate blocks:

- accept both into TF, broadcast both
- accept both, only broadcast best
- accept one, reject other, broadcast one
- accept one, reject other, broadcast both
- accept neither

Last time we talked, we had convinced ourselves that "accept first, reject others" would lead to unacceptable short forks. However, the short fork scenario exists in our current daemon: if you broadcast a block very near to the end of the slot+delta window, some daemons will accept the block and others will not based on propagation delay. The situation will repair itself in the next slot. There is possibly an attack here, but we think only if a single party wins k slots in a row.

**Comment by bijanshahrokhi** [comment]
Given the low probability nature of the attack scenario, I suggest we postpone this for later. 
@vanishreerao can you provide the probability of the attack happening?

**Comment by vanishreerao** [comment]
I would go with "accept first, reject others, broadcast first", there is no reason why you should entertain deviation from the protocol. Single party with say 1/100th total stake will have a negligible probability of winning k slots in a row, so nothing to worry about.

**Comment by es92** [comment]
Duplicated in #756

**Comment by aneesharaines** [comment]
Need to have a discussion about this

**Comment by nholland94** [comment]
Scheduled a meeting for 12/7/2020.

**Comment by imeckler** [comment]
AFAICT from reading [this](https://github.com/input-output-hk/cardano-node/issues/1132), Cardano's solution has been

- use the deterministic chain selection rule (e.g., hashing the vrf evaluation and comparing or some such, not sure what rule they have but it's probably similar) to pick which block to keep so that hopefully not too many different adversarial blocks in the same slot can be spread widely through the network 
- ignore (for now) the fact that block producers can still grind on that and have no further mitigations for now

**Comment by nholland94** [comment]
We decided to go with Cardano's solution. This will involve updating our consensus selection rule to use a deterministic selection rule in the case that the blocks are of equal strength. We currently have a rule like this, but it compares vrf evaluations, which are the same in the case of duplicate proposals. Instead, we can additionally compare the protocol state hashes (or hash of hashes) to break the tie when the vrf evaluations are equal.
