### ISSUE TITLE
RFC for minimum balance or fee

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#3867]
@o1pranay might have insights here.

The idea here is to prevent people from

- filling the ledger
- making a bunch of garbage transactions

Per @cmr 's suggestion, we could also maybe "charge rent" in some way.

**Comment by o1pranay** [comment]
Will dig into it, and find out what other networks do.

From talking to Luke, Tezos has a 0.257ꜩ origination burn fee, or roughly ~$0.30
