### ISSUE TITLE
Clean up consensusTime and nextProposal fields in graphql.

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#3882]
Those fields should now be a `ConsensusTime` type. The `ConsensusTime` type would be have the following schema:

```
type ConsensusTime {
epoch: uint32
slot: uint32
startTime: string
endTime: string
}
```

BKASE TO FOLLOW UP

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
