### ISSUE TITLE
daemon crash report

### ISSUE THREAD

**Issue by victorxu0411** [MinaProtocol/mina#3950]
[coda_crash_report_2019-11-19_13-16-34.339017.tar.gz](https://github.com/CodaProtocol/coda/files/3863895/coda_crash_report_2019-11-19_13-16-34.339017.tar.gz)

The daemon crashed when I start up my node by running:
coda daemon \
    -discovery-port 8303 \
    -peer /dns4/peer1-rising-phoenix.o1test.net/tcp/8303/ipfs/12D3KooWHMmfuS9DmmK9eH4GC31arDhbtHEBQzX6PwPtQftxzwJs \
    -peer /dns4/peer2-rising-phoenix.o1test.net/tcp/8303/ipfs/12D3KooWAux9MAW1yAdD8gsDbYHmgVjRvdfYkpkfX7AnyGvQaRPF \
    -peer /dns4/peer3-rising-phoenix.o1test.net/tcp/8303/ipfs/12D3KooWCZA4pPWmDAkQf6riDQ3XMRN5k99tCsiRhBAPZCkA8re7

**Comment by gregbostrom** [comment]
From crash_summary.json
```
{"OS_type":"Unix","Release":"5.0.0-36-generic","Machine":"x86_64","Sys_name":"Linux","Exception":"(monitor.ml.Error
  (Unix.Unix_error \"Address already in use\" bind
    \"((fd 44) (addr (ADDR_INET 0.0.0.0 8302)))\")
  (\"Raised at file \\\"src/core_unix.ml\\\", line 50, characters 4-43\"
    \"Called from file \\\"src/syscall.ml\\\", line 18, characters 12-16\"
    \"Re-raised at file \\\"src/fd.ml\\\", line 272, characters 18-27\"
    \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"
    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"
    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"
    \"Caught by monitor Tcp.close_sock_on_error\")
```

**Comment by psteckler** [comment]
Could it be you already had a daemon running using the same port?

Try:
```
  ps aux | grep coda
```
to see relevant processes.

**Comment by o1pranay** [comment]
hey @victorxu0411 can you let us know if this was because you were already running a daemon?

**Comment by victorxu0411** [comment]
Seems it’s not, I have rebooted the machine and still get the crashed. But I was able to get it run on a GCP instance.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
