### ISSUE TITLE
The GUI wallet on Ubuntu 18.04 can NOT work (hanging on "Create" step)

### ISSUE THREAD

**Issue by StarLI-Trapdoor** [MinaProtocol/mina#3958]
The gui wallet (Coda.Wallet.0.1.1.AppImage) is used. It seems that the daemon is crashed. Logs and screen captures are attached.
<img width="1238" alt="屏幕快照 2019-11-20 下午5 24 58" src="https://user-images.githubusercontent.com/55707687/69226484-3093bd80-0bbb-11ea-8166-37d13b33a9ba.png">
[coda-wallet.log](https://github.com/CodaProtocol/coda/files/3868341/coda-wallet.log)

**Comment by bkase** [comment]
Can you share what OS version you're using? Thanks!

**Comment by StarLI-Trapdoor** [comment]
Ubuntu 18.04.2 LTS \n \l

**Comment by bkase** [comment]
Thanks @StarLI-Trapdoor we'll play with this to see if we can reproduce and make a fix!

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
