### ISSUE TITLE
The coda 2.4 is crashed

### ISSUE THREAD

**Issue by StarLI-Trapdoor** [MinaProtocol/mina#3967]
The log is attached. Please help check.
[coda_crash_report_2019-11-20_09-48-36.978194.tar.gz](https://github.com/CodaProtocol/coda/files/3872348/coda_crash_report_2019-11-20_09-48-36.978194.tar.gz)

**Comment by bkase** [comment]
`Transition_frontier.Parent_not_found` exception. Interesting! I bet the visualizations will help us here. Thanks for the report!
