### ISSUE TITLE
[Bug] -log-level is ignored when -log-json is passed

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#3970]
When running `coda daemon` passing `-log-level Info` works as expected. It breaks when `-log-json` is also passed. 

I worked with @bkase a little and traced it to here: 
https://github.com/CodaProtocol/coda/blob/develop/src/lib/logger/impl.ml#L121-L127

Should be an easy fix, but it affects many spots in the codebase where `Processor.raw` is called.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
