### ISSUE TITLE
Ledger support in daemon

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#4013]
me to sync w @rbkhmrcr 

Update by @ghost-not-in-the-shell, 12/17/2019
This issue is about having hardware wallet support in daemon.
The idea is that public/private key pairs are generated and managed by the hardware wallet and we want use the hardware wallet to create signature for transactions.

Currently, @rbkhmrcr has a python script that takes a transaction in hex format and a nonce(?) that corresponding to the public_key in the hardware wallet, and it would return a signature for that transaction.

In order to integrate it with coda daemon, @ghost-not-in-the-shell requested the following changes:
1. Instead of having the transaction in hex format, the python script should also accept a transaction in json format.

Once this is done, @ghost-not-in-the-shell can integrate this python script with coda-daemon by adding 2 new cli-commands. The new cli-commands would be created:
1. send-payment-hardware-wallet -receiver RECEIVER_PUBLICKEY -wallet-nonce NONCE_FOR_WALLET -amount AMOUNT
2. delegate-stake-hardware-wallet -delegate DELEGATEE_PUBLICKEY -wallet-nonce NONCE_FOR_WALLET

Those two cli-commands works similar with the original `send-payment` and `delegate-stake` commands. The only difference is that signing is done by the hardware wallet instead.

**Comment by imeckler** [comment]
I will talk to @rbkhmrcr about interfacing with the ledger from python, then I think we shell out

**Comment by ghost-not-in-the-shell** [comment]
The json format I would like to have:
```
{
  "sendPayment": {
    "is_delegation": "False",
    "nonce": 37,
    "from": "tNciczxpMfZ4eW1ZPP9NVK2vxcm9cCHvTBWMe8Nskn2A25P1YqcdvFCD5LvgngraiCmAsnC8zWAiv5pwMYjrUwpMNYDePMQYiXX7HVMjrnB1JkEckyayvsAm2Bo4EQBWbHXD5Cxp65PZy5",
    "to": "tNci9iZe1p3KK4MCcqDa52mpxBTveEm3kqZMm7vwJF9uKzGGt1pCHVNa2oMevDb1HDAs4bNdMQLNbD8N3tkCtKNGM53obE9qFkkhmqMnKRLNLiSfPJuLGsSwqnL3HxSqciJoqJJJmq5Cfb",
    "amount": 1000,
    "fee": 8,
    "valid_until": 1600,
    "memo": "2pmu64f2x97tNiDXMycnLwBSECDKbX77MTXVWVsG8hcRFsedhXDWWq"
    }
}
```

**Comment by bkase** [comment]
Are we going to be locked into this format? It would be nice to unify this JSON payload with our client SDK one that we're working on in JavaScript.

**Comment by rbkhmrcr** [comment]
@bkase we don't think so but this currently is from the graphql API but we have `from` as a nonce for the Ledger device instead of the public key, we can speak to you in person about it!

Next steps are to change the python script to read and write from standard in/out, return the public key to standard out in base58, and take the transaction, nonce, etc, as named arguments to the python script.

**Comment by imeckler** [comment]
The python script should return a json object with the following shape:

```json
{ field : string, scalar: string }
```
where each string is the base58 encoding of a byte array of length 96.

On the ocaml side, e.g., the field element can be decoded like
```ocaml
field |> B58.decode_exn |> String.fold ~init:Bigint.zero ~f:(fun acc byte -> ...) |> Tick.Bigint.of_bignum_bigint |> Tick.Bigint.to_field
```

**Comment by rbkhmrcr** [comment]
@ghost-not-in-the-shell the commands are the following:

To get the app version: 
```
python3 cli/sign.py --request='version'
```
To generate and return the public key generated with nonce 11: 
```
python3 sign.py --request=publickey --nonce=11
```
To sign a transaction, with pk `1234` (`"nonce":37` in the JSON gives the signature/account nonce, `--nonce=1234` gives the nonce with which the Ledger device will generate the sender private/public keypair):
```
python3 sign.py --request=transaction --nonce=1234 --transaction='{"sendPayment": {"is_delegation": "False","nonce": 37,"from": 1234,"to": "tNci9iZe1p3KK4MCcqDa52mpxBTveEm3kqZMm7vwJF9uKzGGt1pCHVNa2oMevDb1HDAs4bNdMQLNbD8N3tkCtKNGM53obE9qFkkhmqMnKRLNLiSfPJuLGsSwqnL3HxSqciJoqJJJmq5Cfb","amount": 1000,"fee": 8,"valid_until": 1600,"memo": "2pmu64f2x97tNiDXMycnLwBSECDKbX77MTXVWVsG8hcRFsedhXDWWq"}}'
```

The `"from":` field in the json is ignored, because the nonce is fed in separately, but if it’s easier on the ocaml end if it’s parsed out of the json instead of this command having a `--nonce` argument then it’s a fairly easy change on my end :) 

The signature is returned in the form in @imeckler's comment above.

**Comment by ghost-not-in-the-shell** [comment]
I think it's cleaner to have the json input for the hardware wallet to only have 1 layer:
```
{
  "sendPayment": {
    "is_delegation": "False",
    "nonce": 37,
    "toAccount": "tNci9iZe1p3KK4MCcqDa52mpxBTveEm3kqZMm7vwJF9uKzGGt1pCHVNa2oMevDb1HDAs4bNdMQLNbD8N3tkCtKNGM53obE9qFkkhmqMnKRLNLiSfPJuLGsSwqnL3HxSqciJoqJJJmq5Cfb",
    "amount": 1000,
    "fee": 8,
    "valid_until": 1600,
    "memo": "2pmu64f2x97tNiDXMycnLwBSECDKbX77MTXVWVsG8hcRFsedhXDWWq"
    }
}
```

**Comment by ghost-not-in-the-shell** [comment]
Since we can't use Base58 representation of public_key to communicate between OCaml and Python, I need to change the json input format for the hardware wallet again:
```
{
    "isDelegation": "False",
    "nonce": 37,
    "toAccount": { 
       x: "115LFY15j2xqcFJXLYvScasi93wyTdmeKPiVgsfzfiBRctYgps77to5Mq4GobohnqQyHxPC7TRMjNL6L4zY259o1SpJPXZYrNARJm7iN9M9rUya6UQJkuf46SosRdEQJwdx"
       is_odd: true},
    "amount": 1000,
    "fee": 8,
    "valid_until": 1600,
    "memo": "2pmu64f2x97tNiDXMycnLwBSECDKbX77MTXVWVsG8hcRFsedhXDWWq"
}

**Comment by rbkhmrcr** [comment]
the public key request looks like this :
```
python3 cli/sign.py --request=publickey--nonce=11
```

and the signature request like this :

```
python3 cli/sign.py --request=sign --msgx=firstint --msgm=secondint --nonce=11
```

**Comment by rbkhmrcr** [comment]
the public key reply looks like
```
{ x : string, y: string }
```
the signature reply looks like
```
{ field : string, scalar: string }
```

**Comment by ghost-not-in-the-shell** [comment]
the public key reply looks like
```
{ "status" : Ok | Hardware_wallet_not_found | Computation_aborted , "x" : string , "y" : string }
```
the signature reply would also have the status field:
```
{"status" : Ok | Hardware_wallet_not_found | Computation_aborted , "field" : string , "scalar" : string }

**Comment by rbkhmrcr** [comment]
the python dependencies are:
```
argparse, base58, binascii, collections, hashlib, json, ledgerblue, os, random, sys, struct
```

**Comment by aneesharaines** [comment]
Need to remove the python 3 dependency.  plus update instructions.  And testing on Izzy's machine
