### ISSUE TITLE
Make core types listed in https://github.com/CodaProtocol/coda/issues/3762#issuecomment-558303802 independent of snarky so we can compile to js_of_of_caml

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#4014]

**Comment by imeckler** [comment]
paul is creating coda_base non-consensus, @psteckler has been putting in conditional compilation of snarky related things and currently working through getting all that to compile.

**Comment by imeckler** [comment]
Sub-issue: https://github.com/CodaProtocol/coda/issues/4146

**Comment by bkase** [comment]
Tock.Field.t
