### ISSUE TITLE
[Crash] Assert_failure lib/proposer/proposer.ml:539

### ISSUE THREAD

**Issue by gregbostrom** [MinaProtocol/mina#4057]
* G1 elements in proof: 4
* G2 elements in proof: 2
* Proof size in bits: 7536
* Elements of w skipped: 17968 (7.22%)
* Elements of w processed with special addition: 10870 (4.37%)
* Elements of w remaining: 220089 (88.42%)
* Elements of w skipped: 17541 (14.96%)
* Elements of w processed with special addition: 10625 (9.06%)
* Elements of w remaining: 89062 (75.97%)
* Elements of w skipped: 17968 (7.22%)
* Elements of w processed with special addition: 10869 (4.37%)
* Elements of w remaining: 220088 (88.42%)
* G1 elements in proof: 2
* G2 elements in proof: 1
* Proof size in bits: 3015
* Elements of w skipped: 1898 (5.43%)
* Elements of w processed with special addition: 364 (1.04%)
* Elements of w remaining: 32697 (93.53%)
* Elements of w skipped: 777 (4.55%)
* Elements of w processed with special addition: 364 (2.13%)
* Elements of w remaining: 15925 (93.31%)
* Elements of w skipped: 1897 (5.43%)
* Elements of w processed with special addition: 363 (1.04%)
* Elements of w remaining: 32696 (93.53%)
* G1 elements in proof: 4
* G2 elements in proof: 2
* Proof size in bits: 7536
* Elements of w skipped: 21499 (26.14%)
* Elements of w processed with special addition: 9872 (12.00%)
* Elements of w remaining: 50885 (61.86%)
* Elements of w skipped: 21013 (35.83%)
* Elements of w processed with special addition: 9679 (16.51%)
* Elements of w remaining: 27948 (47.66%)
* Elements of w skipped: 21499 (26.14%)
* Elements of w processed with special addition: 9871 (12.00%)
* Elements of w remaining: 50884 (61.86%)
* G1 elements in proof: 2
* G2 elements in proof: 1
* Proof size in bits: 3015
* Elements of w skipped: 1922 (5.50%)
* Elements of w processed with special addition: 340 (0.97%)
* Elements of w remaining: 32697 (93.53%)
* Elements of w skipped: 801 (4.69%)
* Elements of w processed with special addition: 340 (1.99%)
* Elements of w remaining: 15925 (93.31%)
* Elements of w skipped: 1922 (5.50%)
* Elements of w processed with special addition: 338 (0.97%)
* Elements of w r2019-12-11 12:00:00 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error \"Assert_failure lib/proposer/proposer.ml:539:16\"\n  (\"Raised at file \\\"lib/proposer/proposer.ml\\\", line 539, characters 16-183\"\n    \"Called from fil
e \\\"src/result.ml\\\", line 151, characters 9-15\"\n    \"Caught by monitor coda\"))"
[coda_crash_report_2019-12-11_12-00-00.240329.tar.gz](https://github.com/CodaProtocol/coda/files/3951666/coda_crash_report_2019-12-11_12-00-00.240329.tar.gz)

**Comment by gregbostrom** [comment]
assert (
                  Consensus.Hooks.required_local_state_sync ~consensus_state
                    ~local_state:consensus_local_state
                  = None ) ;

**Comment by gregbostrom** [comment]
From the coda.log
```
[2019-12-11 11:59:58.478028]Network_pool__Snark_pool: Verification of work 649814937 took 1.3508796691894531 ms
[2019-12-11 11:59:58.949732]Network_pool__Snark_pool: Verification of work 967336483 took 1.35040283203125 ms
[2019-12-11 11:59:59.035133]Trust_system__Peer_trust: Decreasing trust for peer "54.212.217.79" due to Trust_system.Actions.Connected. New trust is -0.032471.
[2019-12-11 11:59:59.385570]Network_pool__Network_pool_base: Broadcasting Snark_pool_diff for work [649814937,967336483] added with fee-prover {\"fee\":1,\"prover\":\"tdNEDdTE3BdcmopBvBGwdAB
XHySBvd2GqQruriNqK4qxLdBsu2xJqQ9wR3PRAthSFDopgHzmQJtr9TmShDZdQoJCLC4mhQ8EGFi1KwYnjBFYvATwijUN5UzSrgmHJ87M6Fx3tbu87QAMTr\"}
[2019-12-11 11:59:59.622957]Coda_networking: Broadcasting snark pool diff over gossip net
[2019-12-11 11:59:59.623999]Gossip_net: broadcasting message: "snark pool diff"
[2019-12-11 11:59:59.624095]Network_pool__Network_pool_base: Pool diff apply feedback: fee equal to cheapest work we have
[2019-12-11 12:00:00.000897]Init__Coda_run: Unhandled top-level exception: $exn
Generating crash report
$exn = "(monitor.ml.Error \"Assert_failure lib/proposer/proposer.ml:539:16\"\n  (\"Raised at file \\\"lib/proposer/proposer.ml\\\", line 539, characters 16-183\"\n    \"Called from file \\\"
src/result.ml\\\", line 151, characters 9-15\"\n    \"Caught by monitor coda\"))"
```

**Comment by bkase** [comment]
Thank you @gregbostrom ! I don't believe we've seen this before -- cc @nholland94

**Comment by gregbostrom** [comment]
Had another occurrence.
```
$ cat coda.version
bd5715a3f00754869498083b2506db776a7047e2
```
```
[2019-12-14 00:00:00.000936]Init__Coda_run: Unhandled top-level exception: $exn
Generating crash report
$exn = "(monitor.ml.Error \"Assert_failure lib/proposer/proposer.ml:539:16\"\n  (\"Raised at file \\\"lib/proposer/proposer.ml\\\", line 539, characters 16-
183\"\n    \"Called from file \\\"src/result.ml\\\", line 151, characters 9-15\"\n    \"Caught by monitor coda\"))"
```
[coda_crash_report_2019-12-14_00-00-00.240337.tar.gz](https://github.com/CodaProtocol/coda/files/3963368/coda_crash_report_2019-12-14_00-00-00.240337.tar.gz)

**Comment by gregbostrom** [comment]
Yet another occurrence.
[coda_crash_report_2020-01-11_12-00-00.520219.tar.gz](https://github.com/CodaProtocol/coda/files/4049819/coda_crash_report_2020-01-11_12-00-00.520219.tar.gz)

```
$ cat .coda-config/coda.version 
bd5715a3f00754869498083b2506db776a7047e2
```

```
[2020-1-11 12:00:00.000281]Init__Coda_run: Unhandled top-level exception: $exn
Generating crash report
$exn = "(monitor.ml.Error \"Assert_failure lib/proposer/proposer.ml:539:16\"\n  (\"Raised at file \\\"lib/proposer/proposer.ml\\\", line 539, characters 16-183\"\n    \"Called from file \\
\"src/result.ml\\\", line 151, characters 9-15\"\n    \"Caught by monitor coda\"))"
```

**Comment by nholland94** [comment]
Possibly related to #4028. I will write up some more details (including a diagram) of the the edge case documented in that issue. Unfortunately, our current logging around this situation isn't robust enough to easily determine whether or not this error is caused by #4028, but I think that's a good spot to start. Do you happen to know, for these crashes, if they happened relatively close to performing a Bootstrap (as in, did they happen within an hour or so of starting), or did these crashes happen after your nodes were running for an extended period of time?

**Comment by gregbostrom** [comment]
The last crash definitely happened close to a bootstrap.  I just don't remember about the first two but it's certainly possibly.

**Comment by gregbostrom** [comment]
Another crash after almost six hours running.  Included the full output from the coda daemon.

[log.2020-01-14_18:08:41.gz](https://github.com/CodaProtocol/coda/files/4068594/log.2020-01-14_18.08.41.gz)
[coda_crash_report_2020-01-14_03-30-44.260259.tar.gz](https://github.com/CodaProtocol/coda/files/4068596/coda_crash_report_2020-01-14_03-30-44.260259.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
