### ISSUE TITLE
Daemon crashed/stopped

### ISSUE THREAD

**Issue by victorxu0411** [MinaProtocol/mina#4075]
2019-12-13 01:36:35 UTC [Error] RPC call raised an exception: $exn
        exn: "(src/connection.ml.Handshake_error.Handshake_error\n  (Timeout (\"Client connected via TCP\" (134.209.49.152 8302))))"
2019-12-13 01:36:35 UTC [Error] Broadcasting message "snark pool diff" to $peer failed: $error
        peer: {
  "host": "134.209.49.152",
  "discovery_port": 8303,
  "communication_port": 8302
}
        error: "(src/connection.ml.Handshake_error.Handshake_error\n (Timeout (\"Client connected via TCP\" (134.209.49.152 8302))))"
2019-12-13 01:36:53 UTC [Error] RPC call raised an exception: $exn
        exn: "(src/connection.ml.Handshake_error.Handshake_error\n  (Timeout (\"Client connected via TCP\" (134.209.49.152 8302))))"
2019-12-13 01:36:53 UTC [Error] Broadcasting message "snark pool diff" to $peer failed: $error
        peer: {
  "host": "134.209.49.152",
  "discovery_port": 8303,
  "communication_port": 8302
}
        error: "(src/connection.ml.Handshake_error.Handshake_error\n (Timeout (\"Client connected via TCP\" (134.209.49.152 8302))))"
2019-12-13 01:36:57 UTC [Error] RPC call raised an exception: $exn
        exn: "(src/connection.ml.Handshake_error.Handshake_error\n  (Timeout (\"Client connected via TCP\" (134.209.49.152 8302))))"
2019-12-13 01:36:57 UTC [Error] Broadcasting message "snark pool diff" to $peer failed: $error
        peer: {
  "host": "134.209.49.152",
  "discovery_port": 8303,
  "communication_port": 8302
}
        error: "(src/connection.ml.Handshake_error.Handshake_error\n (Timeout (\"Client connected via TCP\" (134.209.49.152 8302))))"
{"timestamp":"2019-12-13 01:37:42.589066Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"lib/snark_worker/functor.ml\", line 92, characters 61-68"},"message":"Base SNARK generated in $time","metadata":{"pid":8334,"process":"Snark Worker","time":"1.389m"}}
{"timestamp":"2019-12-13 01:37:42.589176Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"lib/snark_worker/functor.ml\", line 92, characters 61-68"},"message":"Base SNARK generated in $time","metadata":{"pid":8334,"process":"Snark Worker","time":"1.323m"}}
{"timestamp":"2019-12-13 01:37:42.589188Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"lib/snark_worker/functor.ml\", line 147, characters 63-70"},"message":"Submitted completed SNARK work to $address","metadata":{"address":"127.0.0.1:8301","pid":8334,"process":"Snark Worker"}}
2019-12-13 01:37:42 UTC [Warn] Rejecting locally generated snark work [ 966811560, 1048474469 ], fee equal to cheapest work we have
{"timestamp":"2019-12-13 01:37:44.670024Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"lib/snark_worker/functor.ml\", line 136, characters 59-66"},"message":"SNARK work received from $address. Starting proof generation","metadata":{"address":"127.0.0.1:8301","pid":8334,"process":"Snark Worker"}}

both my block producer and snark worker are keeping crash several times per day.

**Comment by bkase** [comment]
@victorxu0411 can you attach the crash tar.gz file?

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
