### ISSUE TITLE
Pipe overflow crash

### ISSUE THREAD

**Issue by Igor-Tselkovskiy** [MinaProtocol/mina#4079]
{"timestamp":"2019-12-13 14:56:58.046409Z","level":"Debug","source":{"module":"Consensus__Proof_of_stake","location":"File \"lib/consensus/proof_of_stake.ml\", line 2560, characters 56-63"},"message":"Select result: $choice -- $message","metadata":{"choice":"Take","message":"(last epoch lock checkpoints are equal) && (candidate is longer than existing)","pid":8477,"selection_context":"Transition_router.is_transition_for_bootstrap"}}
{"timestamp":"2019-12-13 14:56:58.046478Z","level":"Fatal","source":{"module":"Init__Coda_run","location":"File \"app/cli/src/init/coda_run.ml\", line 419, characters 56-63"},"message":"Unhandled top-level exception: $exn\nGenerating crash report","metadata":{"exn":"(monitor.ml.Error\n  (\"Pipe_lib.Strict_pipe.Overflow(\\\"transition frontier controller pipe\\\")\")\n  (\"Raised at file \\\"lib/pipe_lib/strict_pipe.ml\\\", line 211, characters 8-53\"\n    \"Called from file \\\"src/pipe.ml\\\", line 873, characters 10-13\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))","pid":8477}}
{"timestamp":"2019-12-13 14:56:58.140139Z","level":"Debug","source":{"module":"Init__Coda_run","location":"File \"app/cli/src/init/coda_run.ml\", line 76, characters 52-59"},"message":"Successfully wrote the visualization of the registered masks at location: /root/.coda-config/coda_crash_report_2019-12-13_14-56-58.140044
[coda_crash_report_2019-12-13_14-56-58.140044.tar.gz](https://github.com/CodaProtocol/coda/files/3962481/coda_crash_report_2019-12-13_14-56-58.140044.tar.gz)
/registered_masks.dot.","metadata":{"coda_run":"Logging state before program ends","pid":8477}}
{"timestamp":"2019-12-13 14:57:01.895804Z","level":"Debug","source":{"module":"Init__Coda_run","location":"File \"app/cli/src/init/coda_run.ml\", line 87, characters 58-65"},"message":"Successfully wrote the visualization of the transition frontier at location: /root/.coda-config/coda_crash_report_2019-12-13_14-56-58.140044/frontier.dot.","metadata":{"coda_run":"Logging state before program ends","pid":8477}}

**Comment by Igor-Tselkovskiy** [comment]
[coda_crash_report_2019-12-13_14-56-58.140044.tar.gz](https://github.com/CodaProtocol/coda/files/3962491/coda_crash_report_2019-12-13_14-56-58.140044.tar.gz)

**Comment by bkase** [comment]
A pipe overflow! We haven't seen that recently, cc @nholland94

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
