### ISSUE TITLE
Document choices for number of Poseidon rounds

### ISSUE THREAD

**Issue by ValarDragon** [MinaProtocol/mina#4144]
Could the choices for the number of rounds used in Poseidon be documented?

I was looking at https://github.com/CodaProtocol/coda/blob/develop/src/lib/random_oracle/random_oracle.ml#L35, and the number of rounds is notably less than the number of rounds the paper describes for alpha=5. 

I presume this is due to using alpha=11, and the paper only describes parameterization up to alpha=5. Needing fewer rounds makes sense to me intuitively, since the interpolation attack becomes prohibitive much more quickly. (I assume something similar holds for the Grobner basis attack)

As a second question, this also seems like something interesting to optimize over if true. Could you further raise alpha, and lower the number of rounds (and potentially lower overall #constraints in Marlin / amount of time due to fewer MDS's). I think that it should work, and roughly estimating, I think it would be useful to switch from alpha=11 to alpha=17. 
This keeps the same number of multiplications per S-Box, but saves 5 or 6 rounds.

**Comment by ValarDragon** [comment]
I was looking at the equations in Poseidon with higher alpha, and I got a different answer for soundness at 128 bits of security. I also get that this parameterization has a soundness of 119 bits. 

I am looking at soundness against the interpolation attack, equation (1) of section 3 (https://eprint.iacr.org/2019/458.pdf). I am assuming that this implementation is doing the recommended round padding suggested in the paper. 

Coda uses 8 full rounds, and 33 partial rounds. Accounting for the suggested padding, this has `R_f = floor(8 / 1.25) = 6`, and `R_p = floor(33 / 1.075) = 30`.

To be sound against interpolation attacks per the paper, the following must be true:
`R_f + R_p > log_11(2) * min(M, N) + log_2(t)`

For 128 bits of soundness, and state size 3 (the minimum possible for a 2->1 hash)
`min(M, N) = min(128, log_2(field_size)) = 128`.

`log_11(2) * 128 + log_2(3) = 38.585260269410796`. Since the number of rounds must be an integer, we need `R_f + R_p = 39`. Since `R_f` is set to 6, we need 33 partial rounds. This means we need `ceil(R_f * 1.25) = 8` full rounds, and `ceil(R_p * 1.075) = 36` partial rounds.

I get that at `R_p = 30`, you have security parameter 119.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
