### ISSUE TITLE
Stop producing blocks in certain catchup scenarios

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#4150]
It's dangerous for block producers to propose in the following catchup scenarios:
1. We just finished bootstrap and didn't finish catchup. In this scenario, we might got the wrong epoch ledger since we are using peer's best tip to do the `required_local_state_sync`. This is related to #4028. In this scenario, the node would crash.
2. If we are offline for a long time and back online later. If the network advanced by `x` blocks where `k <= x < 2k + delta` which means we need to do catchup. In this scenario, if we produce a block off our best tip, then we would produce a block that is disconnected to other peers' frontier and we would be punished or banned which is also pretty bad.

Nathan proposes that our system should set up a signal that informs the proposer to stop producing blocks if there is a potential catchup job that makes our frontier advance more than `k - 1` blocks. Once the catchup job finishes, the proposer could continue working.

Since this would lead to crashes of proposers, I suggest we should fix this soon.

**Comment by bijanshahrokhi** [comment]
since banning is turned off, what's the risk in not addressing item #2 above? 
Can we address this for now by just communicating to the users that they shouldn't produce a block until they are synced?

**Comment by garethtdavies** [comment]
> Can we address this for now by just communicating to the users that they shouldn't produce a block until they are synced?

Isn't this a problem given most(?) would be starting via the flag `--block-producer-key` and not interactively i.e. coda client set-staking? Given block production is "paused during bootstrap" it seems a similar mechanism to handle catchup would be the most appropriate.
