### ISSUE TITLE
Distance based Catchup status logic

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#4165]
We need to add an internal status for whether or not we are in a state of "significant catchup" during participation. More specifically, what "significant catchup" means is that there is at least one ongoing Catchup job which will move the frontier forward a large amount. We can define some threshold `T` to represent what a large amount is (we will determine this later when the issue is worked on, but I would tentatively propose something like `K/2`). There are 2 reasons why we need to do this:

1) We need to provide a better high-level status to our end-users which does not constantly flip back and forth between "Synced" and "Catchup" for short lived Catchup jobs. (medium work, low risk)
2) We need to pause proposing new blocks if there is a large Catchup job. (medium work, medium to low risk)

The purpose behind 1 is obvious, though 2 may not be. There is an issue right now where a proposer can propose blocks which are seen as invalid by other nodes if they are still performing a large Catchup job. This happens primarily after Bootstrap yields into the Participation phase, since Bootstrap listens to disjoint blocks and submits them all as Catchup jobs immediately after entering Participation. If the Catchup job is large enough, that means that other nodes in the network are at a state where their local Transition Frontier's root is far ahead of ours. If we proposer blocks in this state, we could be proposing on branches of the Transition Frontier which have already been pruned from our peer's Transition Frontiers due to {finalizations/root transitions} they have performed that we have not. Doing so has the side effect that other nodes will punish (and quite possible ban) us.

**Comment by aneesharaines** [comment]
If we turn on banning, then this becomes more important
