### ISSUE TITLE
Activate consensus with sliding windows

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#4198]
make the bool negated

**Comment by ghost-not-in-the-shell** [comment]
In order to using the sliding window, we first need to pick the constants for it (shift_per_window, and slots_per_shift). When I implemented the sliding window, I made an arbitrary choice for those constants in order to do the testing.

**Comment by imeckler** [comment]
@vanishreerao have we determined what the parameters should look like here -- is it a function of f and k?

**Comment by imeckler** [comment]
@ghost-not-in-the-shell to discuss with @yourbuddyconner about running this in a small network

**Comment by imeckler** [comment]
@vanishreerao should have parameters by next Wednesday and we can activate it once that happens

**Comment by imeckler** [comment]
We need to understand

1. What these parameters will look like on a testnet, and then QA that on a small network before deploying it
2. What these parameters will look like for mainnet and then we need a plan for testing that
