### ISSUE TITLE
Debian package depends on libprocps6 

### ISSUE THREAD

**Issue by arj03** [MinaProtocol/mina#4225]
Debian 10.0 was released on July 6th, 2019 and doesn't have libprocps6 (instead has 7). This means that it is not super easy to install on a recent debian stable system.

**Comment by bkase** [comment]
Thanks for reporting this! Hmm maybe we'll need to make a build with libprocps7

**Comment by jkrauska** [comment]
Currently coda is built and support Debian9/Ubuntu 18.04 (LTS).

I was able to manually dpkg install Ubuntu 18 libprocsps6 and libjmalloc to get the stock coda deb working in Ubuntu 19.10.   You can probably do something similar as stop gap in Debian 10.

**Comment by arj03** [comment]
It just makes it harder to join the genesis program

**Comment by jkrauska** [comment]
@arj03 understood.  The docs are pretty clear about only supporting Debian9/U18 now.
https://codaprotocol.com/docs/getting-started#requirements

It's always tricky deciding which OS to target. When the toolchain was created Debian 10 wasn't out yet.

The toolchain used to build coda:
https://github.com/CodaProtocol/coda/blob/develop/dockerfiles/Dockerfile-toolchain
Uses this as a base:
FROM ocaml/opam2:debian-9-ocaml-4.08

It looks like there's a variant of this based on debian 10.
https://hub.docker.com/layers/ocaml/opam2/debian-10-ocaml-4.08/images/sha256-9c25e6e57c2068b38dfbbc21cd0b614497e29a53cce083e91ce03a81e756c31b

I think a concern is that a majority of the current testnet users are running Ubuntu 18.04 or Debian 9.

I think that once Ubuntu 20.0X (LTS) comes out in a few months and there's a paired new Ubuntu to line up with Debian 10 that it's a stronger case to support the newer releases.

Alternatively procps and libmalloc could be statically linked, which would increase the binary size a lot, but might support both platforms now.

**Comment by arj03** [comment]
Maybe they are because there is no package for debian 10 :P

I think statically linking would be a good option for now. Seems like other people are bitten by the malloc thing as well: https://forums.codaprotocol.com/t/testnet-beta-phase-3-staking-signups/225/4
