### ISSUE TITLE
problem with start coda daemon

### ISSUE THREAD

**Issue by illlefr4u** [MinaProtocol/mina#4250]
Trying to start my coda daemon at new testnet. Using the comand:
coda daemon -discovery-port 8303 -peer /dns4/seed-one.genesis.o1test.net/tcp/10002/ipfs/12D3KooWP7fTKbyiUcYJGajQDpCFo2rDexgTHFJTxCH8jvcL1eAH -peer /dns4/seed-two.genesis.o1test.net/tcp/10002/ipfs/12D3KooWL9ywbiXNfMBqnUKHSB1Q1BaHFNUzppu6JLMVn9TTPFSA -propose-key /home/root//genesis -run-snark-worker 4vsR...bLZ -snark-worker-fee 1

crush-file in the attach
[coda_crash_report_2020-01-24_22-30-56.739673.tar.gz](https://github.com/CodaProtocol/coda/files/4111014/coda_crash_report_2020-01-24_22-30-56.739673.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
