### ISSUE TITLE
The daemon of stage3 is crashed.

### ISSUE THREAD

**Issue by StarLI-Trapdoor** [MinaProtocol/mina#4251]
Please help check the attached log.

**Comment by StarLI-Trapdoor** [comment]
[coda_crash_report_2020-01-25_02-18-21.695205.tar.gz](https://github.com/CodaProtocol/coda/files/4111538/coda_crash_report_2020-01-25_02-18-21.695205.tar.gz)

**Comment by StarLI-Trapdoor** [comment]
[coda_crash_report_2020-02-02_07-43-08.913892.tar.gz](https://github.com/CodaProtocol/coda/files/4143678/coda_crash_report_2020-02-02_07-43-08.913892.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
