### ISSUE TITLE
Crash 0.0.12-beta3 1dffa7c 

### ISSUE THREAD

**Issue by spdd** [MinaProtocol/mina#4256]
Hi, i'm trying to run a coda node but after 10-15 minutes it crashed.

`coda daemon \
    -discovery-port 8303 \
    -peer /dns4/seed-one.genesis.o1test.net/tcp/10002/ipfs/12D3KooWP7fTKbyiUcYJGajQDpCFo2rDexgTHFJTxCH8jvcL1eAH \
    -peer /dns4/seed-two.genesis.o1test.net/tcp/10002/ipfs/12D3KooWL9ywbiXNfMBqnUKHSB1Q1BaHFNUzppu6JLMVn9TTPFSA \
    -propose-key keys/my-wallet \
    -run-snark-worker 4vsRCVzBeSxp3iBQ1C3ahHyKjKVbPd93JLSAsqtRtmjB9Xhn29NBdnzT4o6Hb3iNwaFECrh18YsxhAkqMY8nZQrN8jRX5LfbB9h4p5csrRe8xza4VWToXnFaHtGx6gB9FKAr1eKebSiPyH5c \
    -snark-worker-fee 1`

[coda_crash_report_2020-01-25_10-47-40.069277.tar.gz](https://github.com/CodaProtocol/coda/files/4111954/coda_crash_report_2020-01-25_10-47-40.069277.tar.gz)

**Comment by mrmr1993** [comment]
This was a bug in the old transaction replacement logic. This was fixed by #7346. Closing.
