### ISSUE TITLE
[Fatal] Unhandled top-level exception: $exn

### ISSUE THREAD

**Issue by mattharrop** [MinaProtocol/mina#4259]
Both my block producer and snark worker node crashed at the same time.   
Here's the crash report from the block producer:
[coda_crash_report_2020-01-25_13-49-38.346094.tar.gz](https://github.com/CodaProtocol/coda/files/4112092/coda_crash_report_2020-01-25_13-49-38.346094.tar.gz)

And here's the crash report from the snark worker:
[coda_crash_report_2020-01-25_13-49-21.968956.tar.gz](https://github.com/CodaProtocol/coda/files/4112108/coda_crash_report_2020-01-25_13-49-21.968956.tar.gz)

**Comment by mrmr1993** [comment]
This was likely caused by a race between multiple threads updating the transaction pool. We haven't seen this class of error since #7759. Closing.
