### ISSUE TITLE
Coda Daemon crashed: Tried to handle a committed transaction in the pool but its nonce doesn't match the head of the queue for that sender

### ISSUE THREAD

**Issue by fmarcoz** [MinaProtocol/mina#4260]
"(monitor.ml.Error\n  (Failure\n    \"Tried to handle a committed transaction in the pool but its nonce doesn't match the head of the queue for that sender.\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/lib/network_pool/transaction_pool.ml\\\", line 257, characters 14-107\"\n    \"Called from file \\\"list.ml\\\", line 117, characters 24-34\"\n    \"Called from file \\\"src/list0.ml\\\" (inlined), line 22, characters 40-81\"\n    \"Called from file \\\"src/lib/network_pool/transaction_pool.ml\\\", line 229, characters 8-1023\"\n    \"Called from file \\\"src/lib/pipe_lib/broadcast_pipe.ml\\\", line 89, characters 25-28\"\n    \"Called from file \\\"src/pipe.ml\\\", line 827, characters 4-56\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"

**Comment by mrmr1993** [comment]
Dup of #4298. Closing.
