### ISSUE TITLE
Tried to handle a committed transaction in the pool but its nonce doesn't match the head of the queue for that sender

### ISSUE THREAD

**Issue by mawi13** [MinaProtocol/mina#4262]
Client was just running, I did nothing. 
[coda_crash_report_2020-01-25_14-25-59.143175.tar.gz](https://github.com/CodaProtocol/coda/files/4112226/coda_crash_report_2020-01-25_14-25-59.143175.tar.gz)

**Comment by jrwashburn** [comment]
I had a similar issue and was about to create a new case but noticed 4 pre-existing, including https://github.com/CodaProtocol/coda/issues/4272 and https://github.com/CodaProtocol/coda/issues/4260 and
https://github.com/CodaProtocol/coda/issues/4258.

In my case, running MacOS 10.15.2, installed coda via brew. Daemon stuck bootstrapping, stopped (client stop command) and restarted daemon a few times, finally left it running overnight. Came  back to a crash report requesting to open a ticket.

[coda_crash_report_2020-01-27_09-58-11.402285.tar.gz](https://github.com/CodaProtocol/coda/files/4120060/coda_crash_report_2020-01-27_09-58-11.402285.tar.gz)

**Comment by mrmr1993** [comment]
Dup of #4298. Closing.
