### ISSUE TITLE
Coda Daemon crashed: Coda_lib.Snark_worker_signal_interrupt(-10)

### ISSUE THREAD

**Issue by fmarcoz** [MinaProtocol/mina#4263]
Generating crash report
        exn: "(monitor.ml.Error (\"Coda_lib.Snark_worker_signal_interrupt(-10)\")\n  (\"Raised at file \\\"src/lib/coda_lib/coda_lib.ml\\\", line 124, characters 12-56\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"

**Comment by mrmr1993** [comment]
There's not enough information here to investigate this, and we now handle unexpected child process exits better anyway. Closing.
