### ISSUE TITLE
status showing as 'catchup' while at latest block

### ISSUE THREAD

**Issue by nikmit** [MinaProtocol/mina#4267]
My daemon was running with 'catchup' status for may be 2 hours, blocks were periodically incrementing. I restarted node after deleting coda-config folder to see if that will help, now it is catching up for real, and showing block 128, max seen 138. People are reporting that their nodes are showing 'catchup' status at 138 blocks.

**Comment by mrmr1993** [comment]
The 'super catchup' changes seem to have improved this in general, and there's not enough information here to investigate further. Closing.
