### ISSUE TITLE
Wrong balance received

### ISSUE THREAD

**Issue by shaimo** [MinaProtocol/mina#4269]
I made a payment transaction of 5 CODA between two of my accounts. For some reason the TX went through but the balance at the receiving party shows only 4 CODA. Not sure if this is a bug or what's going on.

Receiving account: https://codaexplorer.garethtdavies.com/wallet/4vsRCVyaDJ7jbTbKuqWqqZPyCZi2QzAjLGofcMwQqbo5v9UJWJeEoNTx16JZ9yx8rR4T6TW8hYgVC3Ln3cW6nyUvnXMKUt9vgoKzBgQNJefo22ZNfJRyXdJcMZdGuGVXEZGwiP4Wwqb8ua83

TX: https://codaexplorer.garethtdavies.com/payment/2pFDgkzFz1H4HuEjyWA7NPabqTeDGCJPyGgEFTvWK1gPjcyC5FPCSxWyzqt2A8y89hpiAL5ue4Fiss8stEjVuLHh1oF5ieM4yayhhfuTRvYTRr7rmKVAL2f3eQGChiJgzWaEDCui8GyMZSUSEuxCwHtqZGJozyNXp22Tt4q9UrtSLRfq38FyrVd3NC8xUDxWT7pVEtDfBGybB6VLacHbhftWG9dCzb5zBSzo1E7ri8TSCnxbLFM6FtskVTZTECQVQBbMXePSyJQGTwB6StA2Zob7fcDcfWMz74nGHJAbD1oTEgYkgyzkTDixVNQxkjnDTYpBqB6tBX35cvUAE299CR3RiCrDh88ihqVBLCdLgK4iLXs8294CtMHfTGPic2SpxhYRa9JJsfwhTcysGu9Y3xA8ryrVDVkPWTTzhcYfbezWu2UY87Ac2JcsAJaKNRvWvU2yFy1cFkvsLptChEoJa3AnZtSXCyB9Lgfj98WdaiNXou71tmybENN4QCptwEN2nM4SCUjjbxW9GSRTngrQkhdghVBWrzbFDHhinYqvSTZywsQpgR54m5njrNkmfcFBkYwbmg7BtAXd2hfMFN4MxwdqaFiJ3fBDoDrSsLK1i2yn7jY

**Comment by mrmr1993** [comment]
That testnet is no longer running, so we don't have any way to investigate this. Closing.
