### ISSUE TITLE
Tried to handle a committed transaction in the pool but its nonce doesn't match the head of the queue for that sender

### ISSUE THREAD

**Issue by bidulemachin** [MinaProtocol/mina#4272]
[coda_crash_report_2020-01-25_21-30-42.387177.tar.zip](https://github.com/CodaProtocol/coda/files/4113010/coda_crash_report_2020-01-25_21-30-42.387177.tar.zip)

**Comment by mrmr1993** [comment]
Dup of #4298. Closing.
