### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by Igor-Tselkovskiy** [MinaProtocol/mina#4276]
{"timestamp":"2020-01-26 05:09:38.483862Z","level":"Debug","source":{"module":"Coda","location":"File \"src/app/cli/src/coda.ml\", line 532, characters 63-70"},"message":"Long async cycle, $long_async_cycle seconds","metadata":{"long_async_cycle":1.034232081,"pid":2726}}
{"timestamp":"2020-01-26 05:09:38.606542Z","level":"Debug","source":{"module":"Trust_system__Peer_trust","location":"File \"src/lib/trust_system/peer_trust.ml\", line 133, characters 56-63"},"message":"Decreasing trust for peer $peer_id due to Trust_system.Actions.Connected. New trust is -0.048831.","metadata":{"peer_id":"62.171.131.202","pid":2726}}
{"timestamp":"2020-01-26 05:09:38.606719Z","level":"Trace","source":{"module":"Child_processes","location":"File \"src/lib/child_processes/child_processes.ml\", line 190, characters 72-79"},"message":"Output from process libp2p_helper-stdout: {\\\"upcall\\\":\\\"incomingStreamMsg\\\",\\\"stream_idx\\\":2358,\\\"data\\\":\\\"92HBvWshBzsH4vU1WfsNs6vX2gKs3ZwDcE8bCKbeXSCs4t7hcfczwUDaxfQYi6ZF7kZ5dmiLH4W1oxe1hmya9JC51TZtJBSHE6Ep\\\"}","metadata":{"handle":"stdout","pid":2726,"process":"libp2p_helper"}}
{"timestamp":"2020-01-26 05:09:38.606836Z","level":"Debug","source":{"module":"Child_processes","location":"File \"src/lib/child_processes/child_processes.ml\", line 190, characters 72-79"},"message":"Output from process libp2p_helper-stderr: {\\\"id\\\":1789,\\\"level\\\":4,\\\"message\\\":\\\"got error on dial: dial tcp4 0.0.0.0:8303-\\u003e172.17.0.2:8303: i/o timeout\\\",\\\"module\\\":\\\"swarm2\\\",\\\"time\\\":\\\"2020-01-26T08:09:34.527338778+03:00\\\"}","metadata":{"handle":"stderr","pid":2726,"process":"libp2p_helper"}}
{"timestamp":"2020-01-26 05:09:38.711443Z","level":"Fatal","source":{"module":"Init__Coda_run","location":"File \"src/app/cli/src/init/coda_run.ml\", line 474, characters 56-63"},"message":"Unhandled top-level exception: $exn\nGenerating crash report","metadata":{"exn":"(monitor.ml.Error\n  (Unix.Unix_error \"Transport endpoint is not connected\" getpeername\n    \"((fd 76))\")\n  (\"Raised at file \\\"src/core_unix.ml\\\", line 50, characters 4-43\"\n    \"Called from file \\\"src/unix_syscalls.ml\\\", line 1075, characters 6-49\"\n    \"Called from file \\\"src/rpc.ml\\\", line 236, characters 26-49\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))","pid":2726}}
{"timestamp":"2020-01-26 05:09:39.331755Z","level":"Debug","source":{"module":"Init__Coda_run","location":"File \"src/app/cli/src/init/coda_run.ml\", line 76, characters 52-59"},"message":"Successfully wrote the visualization of the registered masks at location: /root/.coda-config/coda_crash_report_2020-01-26_05-09-39.331007/registered_masks.dot.","metadata":{"coda_run":"Logging state before program ends","pid":2726}}
{"timestamp":"2020-01-26 05:11:24.660211Z","level":"Debug","source":{"module":"Init__Coda_run","location":"File \"src/app/cli/src/init/coda_run.ml\", line 87, characters 58-65"},"message":"Successfully wrote the visualization of the transition frontier at location: /root/.coda-config/coda_crash_report_2020-01-26_05-09-39.331007/frontier.dot.","metadata":{"coda_run":"Logging state before program ends","pid":2726}}

**Comment by Igor-Tselkovskiy** [comment]
[coda_crash_report_2020-01-26_05-09-39.331007.tar.gz](https://github.com/CodaProtocol/coda/files/4113180/coda_crash_report_2020-01-26_05-09-39.331007.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue because of being inactive for long time.
Please feel free to open another ticket should you experience any further issues.
