### ISSUE TITLE
node fails to get any peers, restarts and fails again

### ISSUE THREAD

**Issue by nikmit** [MinaProtocol/mina#4277]
While running node through systemd, I found it fails to get peers and shuts down, systemd brings it up again and then it dies again. Removing coda-config fixed the peers issue, node has peers now and is bootstrapping.
At least one other user (@inv0ke) reported the same, i think others had it too.
Coda-config folder too big to attach here, even after archiving - let me know if you want it and I'll send it in another way, I have it saved.

Running daemon with these options:
DAEMON_OPTIONS="-discovery-port 8303 -propose-key /home/nik/keys/my-wallet -run-snark-worker 4vsRCVxL7t27LsPU54SYwfWBjA8UrgdRH2QVyXQZCZJdWMXr5kFJ4yTDbfaXjqphVPKUXWZvzougae6YX6icbngH2DLUvfAFvkp8NzWPoW2GMqZCJ3aZKEZDjB5tG9bnZmM7AuhZN6L6tDZZ"

DAEMON_PEERS="-peer /dns4/seed-one.genesis.o1test.net/tcp/10002/ipfs/12D3KooWP7fTKbyiUcYJGajQDpCFo2rDexgTHFJTxCH8jvcL1eAH -peer /dns4/seed-two.genesis.o1test.net/tcp/10002/ipfs/12D3KooWL9ywbiXNfMBqnUKHSB1Q1BaHFNUzppu6JLMVn9TTPFSA"

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
