### ISSUE TITLE
Crash report 0.0.12-beta3 1dffa7c

### ISSUE THREAD

**Issue by spdd** [MinaProtocol/mina#4278]
Another crash report
[coda_crash_report_2020-01-26_04-21-43.479998.tar.gz](https://github.com/CodaProtocol/coda/files/4113268/coda_crash_report_2020-01-26_04-21-43.479998.tar.gz)

**Comment by spdd** [comment]
[coda_crash_report_2020-01-26_12-57-29.543533.tar.gz](https://github.com/CodaProtocol/coda/files/4113675/coda_crash_report_2020-01-26_12-57-29.543533.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
