### ISSUE TITLE
Node Stacking Crash Report

### ISSUE THREAD

**Issue by ENDER71** [MinaProtocol/mina#4279]
[coda_short.log](https://github.com/CodaProtocol/coda/files/4113365/coda_short.log)

**Comment by ENDER71** [comment]
[coda_crash_report_2020-01-26_09-07-15.653749.tar.gz](https://github.com/CodaProtocol/coda/files/4113374/coda_crash_report_2020-01-26_09-07-15.653749.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
