### ISSUE TITLE
coda daemon crash

### ISSUE THREAD

**Issue by gbuchukuri** [MinaProtocol/mina#4280]
2020-01-26 13:47:24 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error\n   \"Corrupted_privkey: insecure permissions on `/home/noderunner2020`. They should be 0700, they are 755\\\n  \\nHint: 
chmod 700 /home/noderunner2020\\\n  \\n\"\n  (\"Raised at file \\\"src/error.ml\\\" (inlined), line 9, characters 14-30\"\n    \"Called from file \\\"src
/lib/secrets/privkey_error.ml\\\", line 23, characters 14-57\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Calle
d from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\

after running command  coda daemon \
    -discovery-port 8303 \
    -peer /dns4/seed-one.genesis.o1test.net/tcp/10002/ipfs/12D3KooWP7fTKbyiUcYJGajQDpCFo2rDexgTHFJTxCH8jvcL1eAH \
    -peer /dns4/seed-two.genesis.o1test.net/tcp/10002/ipfs/12D3KooWL9ywbiXNfMBqnUKHSB1Q1BaHFNUzppu6JLMVn9TTPFSA -propose-key /home/noderunner2020/keys/ -run-snark-worker 4vsRCVq3nEjZeRDTM8MBfSU7dNZtumsDU8BggYMiUCLDQCsTasxuYRGEdu7GXsFP6ERWodAFMCTZKhatg4rG9bp1PNgsjcMQwQ84kAiDFR1QevAxmY6g5axYSo9GV6eMoGbRcEH5LjPfXkDs -snark-worker-fee 1                                                                                                                                      
    \"Caught by monitor coda\"))"
  ☠  Coda Daemon crashed.
   The Coda Protocol developers would like to know why!
    Please:
      Open an issue:
        <https://github.com/CodaProtocol/coda/issues/new>
      Briefly describe what you were doing and attach the crash report /home/noderunner2020/.coda-config/coda_crash_report_2020-01-26_13-47-24.720453.tar
.gz

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
