### ISSUE TITLE
Coda Daemon crashed: Assert_failure src/lib/network_pool/indexed_pool.ml:529:8

### ISSUE THREAD

**Issue by fmarcoz** [MinaProtocol/mina#4282]
"(monitor.ml.Error \"Assert_failure src/lib/network_pool/indexed_pool.ml:529:8\"\n  (\"Raised at file \\\"src/lib/network_pool/indexed_pool.ml\\\", line 529, characters 8-69\"\n    \"Called from file \\\"src/lib/network_pool/transaction_pool.ml\\\", line 531, characters 30-193\"\n    \"Called from file \\\"src/lib/network_pool/network_pool_base.ml\\\", line 26, characters 15-65\"\n    \"Called from file \\\"src/pipe.ml\\\", line 827, characters 4-56\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"

**Comment by nikmit** [comment]
Same issue crashed my node today at 14:36 GMT, attaching crash report.
[coda_crash_report_2020-01-27_14-36-28.189584.tar.gz](https://github.com/CodaProtocol/coda/files/4118468/coda_crash_report_2020-01-27_14-36-28.189584.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
