### ISSUE TITLE
Coda Daemon crashed: writer buffer has data older than\" (maximum_age 2m)

### ISSUE THREAD

**Issue by fmarcoz** [MinaProtocol/mina#4283]

**Comment by fmarcoz** [comment]
[coda_crash_report_2020-01-26_12-30-34.968748.tar.gz](https://github.com/CodaProtocol/coda/files/4113718/coda_crash_report_2020-01-26_12-30-34.968748.tar.gz)

**Comment by fmarcoz** [comment]
[coda_crash_report_2020-01-26_12-30-34.968748.tar.gz](https://github.com/CodaProtocol/coda/files/4113720/coda_crash_report_2020-01-26_12-30-34.968748.tar.gz)

**Comment by fmarcoz** [comment]
{"OS_type":"Unix","Release":"4.9.0-11-amd64","Machine":"x86_64","Sys_name":"Linux","Exception":"(monitor.ml.Error\n  (\"writer buffer has data older than\" (maximum_age 2m)\n    (beginning_of_buffer\n       \"\\1455\\235\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000\\000ry\\001\\012get_best_tip\\001\\012get_ancestry\\001\\020get_transition_chain\\001\\026get_transition_chain_proof\\001\\\n      \\nban_notify\\001\\016get_epoch_ledger\\001\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\")\n    (writer\n      ((id 8444)\n        (fd\n          ((file_descr 61)\n            (info\n              (socket\n                ((listening_on\n                   ((type_ ((family PF_INET) (socket_type SOCK_STREAM)))\n                     (fd\n                       ((file_descr 43)\n                         (info\n                           (replaced\n                             (listening\n                               (previously_was\n                                 (replaced\n                                   ((socket (bound_on 0.0.0.0:8302))\n                                     (previously_was\n                                       (socket\n                                         ((family PF_INET)\n                                           (socket_type SOCK_STREAM))))))))))\n                         (kind (Socket Passive)) (supports_nonblock true)\n                         (have_set_nonblock true) (state (Open Empty))\n                         (watching\n                           ((read (Watch_once Empty)) (write Not_watching)))\n                         (watching_has_changed false) (num_active_syscalls 1)\n                         (close_finished Empty)))))\n                  (client 78.15.174.5:42781))))\n            (kind (Socket Active)) (supports_nonblock true)\n            (have_set_nonblock true) (state (Open Empty))\n            (watching ((read (Watch_once Empty)) (write Stop_requested)))\n            (watching_has_changed true) (num_active_syscalls 2)\n            (close_finished Empty)))\n        (monitor\n          (((name (id 119599)) (here ()) (id 119599) (has_seen_error false)\n             (is_detached true))\n            ((name coda) (here ()) (id 11) (has_seen_error false)\n              (is_detached true))\n            ((name \"\") (here ()) (id 2) (has_seen_error false)\n              (is_detached true))))\n        (inner_monitor\n          (((name (id 119600)) (here ()) (id 119600) (has_seen_error false)\n             (is_detached true))\n            ((name coda) (here ()) (id 11) (has_seen_error false)\n              (is_detached true))\n            ((name \"\") (here ()) (id 2) (has_seen_error false)\n              (is_detached true))))\n        (background_writer_state Running) (background_writer_stopped Empty)\n        (syscall Per_cycle) (bytes_received 15415040) (bytes_written 3923857)\n        (scheduled_bytes 11491183) (scheduled_back 116) (back 116)\n        (close_state Open) (close_finished Empty) (close_started Empty)\n        (num_producers_to_flush_at_close 0)\n        (flush_at_shutdown_elt (<opaque>))\n        (check_buffer_age\n          (((writer <opaque>) (maximum_age 2m)\n             (bytes_received_at_now_minus_maximum_age 15414932)\n             (bytes_received_queue\n               (15414941 15414950 15414959 15414968 15414977 15414986\n                 15414995 15415004 15415013 15415022 15415031 15415040))\n             (times_received_queue\n               ((2020-01-26 13:28:40.343738993+01:00)\n                 (2020-01-26 13:28:50.565217107+01:00)\n                 (2020-01-26 13:29:01.044565209+01:00)\n                 (2020-01-26 13:29:11.045355115+01:00)\n                 (2020-01-26 13:29:21.172501437+01:00)\n                 (2020-01-26 13:29:30.560274193+01:00)\n                 (2020-01-26 13:29:40.561060493+01:00)\n                 (2020-01-26 13:29:50.561854658+01:00)\n                 (2020-01-26 13:30:00.564213801+01:00)\n                 (2020-01-26 13:30:10.565010625+01:00)\n                 (2020-01-26 13:30:20.752873215+01:00)\n                 (2020-01-26 13:30:30.786277634+01:00)))\n             (bytes_seen 15415040) (too_old (Full ())))))\n        (consumer_left Empty) (raise_when_consumer_leaves false)\n        (open_flags (Full (Ok (rdwr)))) (line_ending Unix))))\n  (\"Caught by monitor (id 119599)\"))","Command":"Command: (coda daemon -discovery-port 8303 -peer\n /dns4/seed-one.genesis.o1test.net/tcp/10002/ipfs/12D3KooWP7fTKbyiUcYJGajQDpCFo2rDexgTHFJTxCH8jvcL1eAH\n -peer\n /dns4/seed-two.genesis.o1test.net/tcp/10002/ipfs/12D3KooWL9ywbiXNfMBqnUKHSB1Q1BaHFNUzppu6JLMVn9TTPFSA\n -peer\n /dns4/peer1-rising-phoenix.o1test.net/tcp/8303/ipfs/12D3KooWHMmfuS9DmmK9eH4GC31arDhbtHEBQzX6PwPtQftxzwJs\n -peer\n /dns4/peer2-rising-phoenix.o1test.net/tcp/8303/ipfs/12D3KooWAux9MAW1yAdD8gsDbYHmgVjRvdfYkpkfX7AnyGvQaRPF\n -peer\n /dns4/peer3-rising-phoenix.o1test.net/tcp/8303/ipfs/12D3KooWCZA4pPWmDAkQf6riDQ3XMRN5k99tCsiRhBAPZCkA8re7\n -propose-key keys_staking/my-wallet -run-snark-worker\n 4vsRCVXacrc1i1fPADHR9rkyHAzHbjUF4XA1bnJESDpYrNbsWCGHXTMnuTzVwZetvZJqVa4BBPcmePkSzKyGodD43UVzgfeyza7aNQusybqJwF99rZ6J9NZ6T8S4GNRKShfaaSpbiwyyxxSo\n -snark-worker-fee 1)","Coda_branch":"master","Coda_commit":"1dffa7cc1438d3e39eb7182b812e882e4a94a7d7"}

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
