### ISSUE TITLE
Spontaneous crash

### ISSUE THREAD

**Issue by daveydoo123** [MinaProtocol/mina#4284]
I did/took no action. The daemon crashed spontaneously.

[coda_crash_report_2020-01-26_12-28-27.374089.tar.gz](https://github.com/CodaProtocol/coda/files/4114972/coda_crash_report_2020-01-26_12-28-27.374089.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
