### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by argonau7** [MinaProtocol/mina#4286]
[coda_crash_report_2020-01-27_12-41-58.115676.tar.gz](https://github.com/CodaProtocol/coda/files/4117524/coda_crash_report_2020-01-27_12-41-58.115676.tar.gz)
Ran Testnet Daemon from VPS. Normal behaviour until crash. snark fee = 101.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
