### ISSUE TITLE
Unhandled top-level exception: $exn

### ISSUE THREAD

**Issue by UbikCapital** [MinaProtocol/mina#4287]
2020-01-27 10:15:54 UTC [Info] Moving peer $peer to disconnected peer set
        peer: {
  "host": "35.235.118.191",
  "discovery_port": 8303,
  "communication_port": 8302
}
2020-01-27 10:16:55 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error\n  (Failure\n    \"Tried to handle a committed transaction in the pool but its nonce doesn't match the head of the queue for that sender.\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/lib/network_pool/transaction_pool.ml\\\", line 257, characters 14-107\"\n    \"Called from file \\\"list.ml\\\", line 117, characters 24-34\"\n    \"Called from file \\\"src/list0.ml\\\" (inlined), line 22, characters 40-81\"\n    \"Called from file \\\"src/lib/network_pool/transaction_pool.ml\\\", line 229, characters 8-1023\"\n
\"Called from file \\\"src/lib/pipe_lib/broadcast_pipe.ml\\\", line 89, characters 25-28\"\n    \"Called from file \\\"src/pipe.ml\\\", line 827, characters 4-56\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"

  ☠  Coda Daemon crashed.
   The Coda Protocol developers would like to know why!

    Please:
      Open an issue:
        <https://github.com/CodaProtocol/coda/issues/new>

      Briefly describe what you were doing and attach the crash report /root/.coda-config/coda_crash_report_2020-01-27_10-16-55.131751.tar.gz

**Comment by mrmr1993** [comment]
Dup of #4298. Closing.
