### ISSUE TITLE
Daemon Crash

### ISSUE THREAD

**Issue by asood123** [MinaProtocol/mina#4289]
Filing this issue per the instructions in the daemon: I ran the daemon on Friday night when phase3 launched and left it running after sending it a few transactions to process (mostly to the echo service).

Attaching crash report.
[coda_crash_report_2020-01-25_02-18-23.345579.tar.gz](https://github.com/CodaProtocol/coda/files/4119304/coda_crash_report_2020-01-25_02-18-23.345579.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
