### ISSUE TITLE
Don't produce block 

### ISSUE THREAD

**Issue by Igor-Tselkovskiy** [MinaProtocol/mina#4293]
{
  "timestamp": "2020-01-28 01:39:00.001744Z",
  "level": "Trace",
  "source": {
    "module": "Proposer",
    "location": "File \"src/lib/proposer/proposer.ml\", line 274, characters 62-69"
  },
  "message": "Producing new block with parent $breadcrumb",
  "metadata": {
    "breadcrumb": {
      "validated_transition": {
        "data": {
          "protocol_state": {
            "previous_state_hash": "1558667389004794029386482183976209771224460967950552772654841654021837611134144602498960724973277175418001750297366925136697584441062923655865852761284495451927300061047190967886467416391267562829900284988944730113843846022536",
            "body": {
              "genesis_state_hash": "27166934135868217083503012196409918270801033312053055416444824008932965230189576758484939585295493751394254942055324643457298450940139018358338099512176186700844599519062686267799363240684165999623970062904971637258940048931480",
              "blockchain_state": {
                "staged_ledger_hash": {
                  "non_snark": {
                    "ledger_hash": "7513295636659188180309969817617419485311250465161263505831025840477369634082012850598232374275513650321866875350316625505659546563671260347979980463318391248313511227167959251957801821206761743642608486798885796002249225550321",
                    "aux_hash": "PUd2jq3yuWHou7hcpV7fewE7AYpNs5aovizQH5uwSJj437KWrw",
                    "pending_coinbase_aux": "5MQVDauPiwve22rUjCcevuyV8iqBp7aHxjgYbqLSXHFYLxBCc7r"
                  },
                  "pending_coinbase_hash": "20597210436353746347568781020880411017753361830452119446654927979441620679255662206667609705084850906907996441710564971622055994603765599891808946625999769380717577900098259508099482923649834759970803487439556792787141751832826"
                },
                "snarked_ledger_hash": "38408163980858560561056833327113900697218999579361402623435381340514200340222799871111187027129935207214137578081266081748443679378103853949149609208948202621028790676352094509515831613769393238412389537042476325151300177266330",
                "timestamp": "1580167440000"
              },
              "consensus_state": {
                "blockchain_length": "278",
                "epoch_count": "7",
                "min_window_density": "80",
                "sub_window_densities": [
                  "0",
                  "10",
                  "10",
                  "10",
                  "10",
                  "10",
                  "10",
                  "10"
                ],
                "last_vrf_output": "<opaque>",
                "total_currency": 14857638,
                "curr_global_slot": "1778",
                "staking_epoch_data": {
                  "ledger": {
                    "hash": "20815815934682412584327015903709209070609740326725548567443314409212381038770506976572722713477754607895257304443421809192976712561533072144117970021958298531693673333887047500286773599631917855257610644593599879861721206771677",
                    "total_currency": "14856478"
                  },
                  "seed": "35285441019470920679707051058171681712187242805158712628080708148544192651129479484938113522715684276980851506374852696819793075298955187309231473837638349921466681361868125704306003343471931180775249646384787690091138131948855",
                  "start_checkpoint": "32204184764920354877886681512371796082135637696556153144423165541036287856856673009129857009226953384861713126082982036349898841730099753340575682203916129707157984677825822381422794294681208162479753688423629553406985192423961",
                  "lock_checkpoint": "6704155030732363494940995880456937025063004359656235065344508729245651550238670602085673644455244299599546497149032129887475504875507395560105149898633674968012456440764522659481723619740450456936535305083322998019268857821014",
                  "epoch_length": "44"
                },
                "next_epoch_data": {
                  "ledger": {
                    "hash": "38408163980858560561056833327113900697218999579361402623435381340514200340222799871111187027129935207214137578081266081748443679378103853949149609208948202621028790676352094509515831613769393238412389537042476325151300177266330",
                    "total_currency": "14857638"
                  },
                  "seed": "2071893303198007985737678972190309212568452221625132024511988170095494148670997278812694070338313361389889122280160253462982652030041813566301365289695187505618174204273471887226695702458395861269694368663558765191107385382142",
                  "start_checkpoint": "26954827052926501839388921034762138400903678792287503030667684119146804167734735863378268534892455706202878190051501476784472619992692651481737306459192355553383831897621405403427970339209155175090404379366713389396422203697166",
                  "lock_checkpoint": "2071893303198007985737678972190309212568452221625132024511988170095494148670997278812694070338313361389889122280160253462982652030041813566301365289695187505618174204273471887226695702458395861269694368663558765191107385382142",
                  "epoch_length": "6"
                },
                "has_ancestor_in_same_checkpoint_window": true
              }
            }
          },
          "protocol_state_proof": "<opaque>",
          "staged_ledger_diff": "<opaque>",
          "delta_transition_chain_proof": "<opaque>"
        },
        "hash": "6051350470176091050743254951564018253028719964454735481241325268816169513558572500318157892577742908116402349860943085278518110499489290647713223937313241096756957415413958161850061388761371026244699145487496354680111656891853"
      },
      "staged_ledger": "<opaque>",
      "just_emitted_a_proof": false
    },
    "pid": 20191
  }
}

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
