### ISSUE TITLE
[bug] having to be root user for import function to work correctly

### ISSUE THREAD

**Issue by cbrown330** [MinaProtocol/mina#4307]
this bug showed the following results
1, if it was your first time importing then it would ask for the password and finish off correctly however it would not be in your accounts list and would not allow you to unlock the key
2. if you attempted to re-import then it would tell you the key already present but still would not show up in accounts to unlock.
3. only when you switched to the root user would it allow you to rerun the import function and would step through all the steps correctly, but then would it only show up in the accounts list.  also i confirmed that if you logged back in under normal user the key would stay active 

![image](https://user-images.githubusercontent.com/2511877/73405481-9edeb580-42b9-11ea-904d-71477dd5e2bd.png)

**Comment by garethtdavies** [comment]
Seems to be similar behavior exhibited here: https://discord.com/channels/484437221055922177/746316198806814760/783763691560501258

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
