### ISSUE TITLE
Using Syncable_ledger to handle epoch_ledger synchronization

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#4317]
As mentioned in https://github.com/CodaProtocol/coda/pull/4115, the `sync_local_state` needs a major rewrite in order to be performant in a more realistic testnet. Currently `sync_local_state` still download entire sparse ledger using the `Get_epoch_ledger` RPC. A better solution would be using `Syncable_ledger` to do the update of epoch ledgers incrementally. But it couldn't be done in a straight forward way for the following reasoning:

While doing update for epoch_ledger, we would always delete the old ledger and create a new RocksDb checkpoint out of the relevant ledger. This means epoch ledgers would not be readable while we are doing updating. (i.e. an epoch ledger update could happen in between the period when our daemon is trying to respond to other peers' sync_ledger request).

Possible solution would be introduce a read/write lock to epoch ledgers.
- Epoch ledger update should wait for all read to be finished first.
- When epoch ledger update is happening, syncable_ledger must not start new read from epoch ledger and syncable_ledger must also abandon any request relevant to the old epoch ledger.

@nholland94 suggested using an interruptible monad would achieve similar effect, but I have to understand interruptible monad first.

Another thing is that syncable_ledger depends on coda_networking, while coda_networking depends on consensus_mechanism itself. There's a dependency issue here, @nholland94 said there's an example in `proof_of_stake.ml` where he did similar thing.

**Comment by aneesharaines** [comment]
Will make sure to test this specifically in the 300k account network

**Comment by aneesharaines** [comment]
Bootstrap time was 11s for 300k accounts for a node that was restarted after k in epoch 2

**Comment by mrmr1993** [comment]
Done in https://github.com/MinaProtocol/mina/pull/11971.
