### ISSUE TITLE
Crash 0.0.13-beta 9116312

### ISSUE THREAD

**Issue by spdd** [MinaProtocol/mina#4319]
Crash 2:
[coda_crash_report_2020-01-31_14-41-52.643595.tar.gz](https://github.com/CodaProtocol/coda/files/4139986/coda_crash_report_2020-01-31_14-41-52.643595.tar.gz)
Crash 1:
[coda.log](https://github.com/CodaProtocol/coda/files/4139875/coda.log)
[coda-prover.log](https://github.com/CodaProtocol/coda/files/4139876/coda-prover.log)
[coda-verifier.log](https://github.com/CodaProtocol/coda/files/4139877/coda-verifier.log)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
