### ISSUE TITLE
"Next proposal:" should use raw units in json/grapql mode

### ISSUE THREAD

**Issue by jkrauska** [MinaProtocol/mina#4331]
The "Next proposal:" field in 'coda client status' is in human readable format with minutes, hours, etc, but in json mode it should be in a standard unit (eg seconds)

This will facilitate easier automated interactions depending on BP state.

Current:
$ coda client status -j | jq .next_proposal
"in 1.076m" 

Desired:
$ coda client status -j | jq .next_proposal
"62s" | "233124s"

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
