### ISSUE TITLE
Require block reward in every block?

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#4334]
Currently it is up to block producers whether they want to include a block reward or not. I think faithfully implementing the [economics whitepaper](https://codaprotocol.com/static/pdf/economicsWP.pdf) demands that block producers not have the power to stop inflation independently of on-chain governance. I think it also weakens consensus? I believe that if the main chain inflates slower than adversarial side chains can, the side chain stake distribution might become favorable (although I don't see how to execute this attack without triggering the epoch density comparison).

**Comment by aneesharaines** [comment]
Have the proposer refuse to propose a block if it can't (doesn't?) include the block reward?

**Comment by aneesharaines** [comment]
@bkase  to write script to monitor blks produced w/o coinbase

**Comment by bkase** [comment]
Ran the script during our meeting but didn't post updates on this issue.

~50 out of 400 blocks recorded had no coinbase when I check 11 days ago.
