### ISSUE TITLE
Fix "disabled bans" so that trust scores are still logged

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#4340]
The recent hotfix to turn off bans made changing trust scores a no-op. We should use the proper mechanism that still tracks the trust scores.

**Comment by psteckler** [comment]
The old `-no-bans` flag and implementation were removed in `0b698ce92e771bc8fe9ad79302a10690d1fedee1`.

We could undo that change to turn off banning that still tracks and logs the trust scores.
