### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Y0Y0jojo** [MinaProtocol/mina#4346]
Hi there.
This error occurred at 5am pst. 2/7/2020.  Unfortunately i was not awake yet, so I'm uncertain why it happened. I have been testing out the daemon on my home computer and a satellite connection before I decide to upgrade to a more reliable cloud service. Most of the time daemon works fine. I am low on my allowable bandwidth for the month, so sometimes service drops. I blame this on my internet connection. However, this error code is new and different.
take a look. 
2020-02-07 13:00:00 UTC [Fatal] Unhandled top-level exception: $exn

Generating crash report

exn: "(monitor.ml.Error \"Assert_failure lib/proposer/proposer.ml:539:16\"\n  (\"Raised at file \\\"lib/proposer/proposer.ml\\\", line 539, characters 16-183\"\n    \"Called from file \\\"src/result.ml\\\", line 151, characters 9-15\"\n    \"Caught by monitor coda\"))"

  ☠  Coda daemon crashed. The Coda Protocol developers would like to know why!

  Please:

    Open an issue:

      <https://github.com/CodaProtocol/coda/issues/new>

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
