### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by mtwebb** [MinaProtocol/mina#4349]
came home to find daemon crashed.   Have been testing remote access to home computer, so recently set up port forwarding. 
[coda_crash_report_2020-02-08_20-49-17.639772.tar.gz](https://github.com/CodaProtocol/coda/files/4175330/coda_crash_report_2020-02-08_20-49-17.639772.tar.gz)

**Comment by mtwebb** [comment]
Happened again. Give a shout with any tests you would like me to run. 

[coda_crash_report_2020-02-09_03-53-34.605138.tar.gz](https://github.com/CodaProtocol/coda/files/4176510/coda_crash_report_2020-02-09_03-53-34.605138.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
