### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Y0Y0jojo** [MinaProtocol/mina#4350]
Hi, 
Ive been trying to log onto daemon all day to try out staking. i had one successful attempt, but hours later it crash. i just tried to log on one more time before i go to bed. most of the times during the day my attempts to log on failed  and said <too many anonymous arguments>. this last time tonight i appeared to be starting up bu then generated this error response. 
Generating crash report
	exn: "(monitor.ml.Error\n  \"Parent directory Volumes/HOME/yoyo/.coda-config/wallets/store does not exist Hint: mkdir -p Volumes/HOME/yoyo/.coda-config/wallets/store; chmod 700 Volumes/HOME/yoyo/.coda-config/wallets/store\\n\"\n  (\"Raised at file \\\"src/error.ml\\\" (inlined), line 9, characters 14-30\"\n    \"Called from file \\\"lib/secrets/privkey_error.ml\\\", line 23, characters 14-57\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"

  ☠  Coda daemon crashed. The Coda Protocol developers would like to know why!

  Please:
    Open an issue:
      <https://github.com/CodaProtocol/coda/issues/new>

    Briefly describe what you were doing and attach the crash report /Volumes/HOME/yoyo/.coda-config/coda_crash_report_2020-02-09_06-58-02.122053.tar.gz
FYI i know my internet connection is not the greatest right now. i have limited satellite service at the moment. could this be part of the problem? is there some thing wrong with my private key or the path to it? thanks. yoyo

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
