### ISSUE TITLE
[Crash] Cached item has already been finalized (lib/cache_lib/impl.ml, line 190)

### ISSUE THREAD

**Issue by jpbriquet** [MinaProtocol/mina#4351]
The coda daemon has crashed randomly after a failure in the cache_lib module.
Full crash report : [coda_crash_report_2020-02-09_01-54-34.834492.tar.gz](https://github.com/CodaProtocol/coda/files/4176599/coda_crash_report_2020-02-09_01-54-34.834492.tar.gz)

**Crash summary :**
{"OS_type":"Unix",
"Release":"4.15.0-45-generic",
"Machine":"x86_64",
"Sys_name":"Linux",
"Exception":"(monitor.ml.Error \"Cached item has already been finalized\"\n  (\"Raised at file \\\"src/error.ml\\\" (inlined), line 9, characters 14-30\"\n    \"Called from file \\\"lib/cache_lib/impl.ml\\\", line 164, characters 30-51\"\n    \"Called from file \\\"lib/cache_lib/impl.ml\\\", line 190, characters 6-69\"\n    \"Called from file \\\"lib/transition_handler/processor.ml\\\", line 164, characters 18-106\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))",
"Command":"Command: (/usr/local/bin/coda daemon -discovery-port 8303 -run-snark-worker\n 
4vsRCVp3ZyeC1YYqfi4gTN8WH2JTo9aypkGrEmmcMeNK9dGLBN6SAaH1WAKsjwoWtiku8Zj1s4UemYzmMN2z9arZPMVAyYxSWQLjA7DjnS3nVaCivtdtqjcj1tBFEKeVwQ5r6M22BRWdMTAE\n -snark-worker-fee 1 -propose-key\n /root/.coda-config/wallets/store/4vsRCVp3ZyeC1YYqfi4gTN8WH2JTo9aypkGrEmmcMeNK9dGLBN6SAaH1WAKsjwoWtiku8Zj1s4UemYzmMN2z9arZPMVAyYxSWQLjA7DjnS3nVaCivtdtqjcj1tBFEKeVwQ5r6M22BRWdMTAE\n -peer\n /dns4/seed-one.genesis-redux.o1test.net/tcp/10002/ipfs/12D3KooWP7fTKbyiUcYJGajQDpCFo2rDexgTHFJTxCH8jvcL1eAH\n -peer\n /dns4/seed-two.genesis-redux.o1test.net/tcp/10002/ipfs/12D3KooWL9ywbiXNfMBqnUKHSB1Q1BaHFNUzppu6JLMVn9TTPFSA)"}

**Possible root cause found just above in logs:**
{"timestamp":"2020-02-09 01:54:34.642855Z","level":"Error","source":{"module":"Cache_lib__Impl","location":"File \"lib/cache_lib/impl.ml\", line 213, characters 53-60"},"message":"Cached.sequence_result called on an already consumed Cached.t","metadata":{"cache":"Transition_handler__Unprocessed_transition_cache","pid":31192}}
{"timestamp":"2020-02-09 01:54:34.643239Z","level":"Error","source":{"module":"Transition_handler__Processor","location":"File \"lib/transition_handler/processor.ml\", line 155, characters 66-73"},"message":"Error while building breadcrumb in the transition handler processor: $error","metadata":{"error":"Verification failed for proof with statement: ((source\n  40512907069065024710161538684335885809087346534344829722611970710280858977934147356838213956869431434868954968546340472283344835979535908612698077635296463467378741529344532390556886007968031971848032442966311067779367399733673)\n (target\n  4527825017576445781109019587541261383726232476150840272731429109482605016586144755605096240325456538091631712606707655018399976826867899781072180162585956184736122791969842602900988930472932563855335889377538376058186210602856)\n (supply_increase 20)\n (pending_coinbase_stack_state\n  ((source\n    ((data\n      10086188713194086394970645500858342522677752033793013672600110814084388463087596088379605573942566552124523272630869543881080724779444223300009306200285511256533857737046896334723171399591596528790397361817699909078612343299214)\n     (state_hash 1)))\n   (target\n    ((data\n      10086188713194086394970645500858342522677752033793013672600110814084388463087596088379605573942566552124523272630869543881080724779444223300009306200285511256533857737046896334723171399591596528790397361817699909078612343299214)\n     (state_hash 1)))))\n (fee_excess ((magnitude 2) (sgn Pos))) (proof_type Merge)) work_id: 645205885 Prover:\"4vsRCVRNqXqPhWEEaDsRtTSCgNgixYRmLDTmK4EHsU7nanc745Ky99j4mG8VH8G7rWrTfwHLhwyHtFu2d5ijydhH41ifLJQr8rnBs6HV3Y3MdGiRduk8aGgjA9fZM3hCkLUCXy1v8zVPafrn\"}\n","pid":31192,"state_hash":"14219138631398759139054927648700594668896649859539114588328405003014762981351822638010103745370360722972789964970029470925518230242724528208709327690967826666432694338470186347853977664922472711603162523266620664804182998325945"}}

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
