### ISSUE TITLE
Crash in proposer.ml

### ISSUE THREAD

**Issue by wkarshat** [MinaProtocol/mina#4352]
size /usr/local/bin/coda
   text	   data	    bss	    dec	    hex
50931094	246787593	 206864	297925551	11c1fbaf

Simply running the node as directed in https://codaprotocol.com/docs/my-first-transaction

`coda daemon -external-port 8302 -discovery-port 8303 -peer /dns4/seed-one.genesis-redux.o1test.net/tcp/10002/ipfs/12D3KooWP7fTKbyiUcYJGajQDpCFo2rDexgTHFJTxCH8jvcL1eAH -peer /dns4/seed-two.genesis-redux.o1test.net/tcp/10002/ipfs/12D3KooWL9ywbiXNfMBqnUKHSB1Q1BaHFNUzppu6JLMVn9TTPFSA

````
2020-02-08 19:30:00 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report exn: "(monitor.ml.Error \"Assert_failure lib/proposer/proposer.ml:539:16\"\n  (\"Raised at file \\\"lib/proposer/proposer.ml\\\", line 539, characters 16-183\"\n    \"Called from file \\\"src/result.ml\\\", line 151, characters 9-15\"\n    \"Caught by monitor coda\"))"
```

[coda_crash_report_2020-02-08_19-30-00.069648.tar.gz](https://github.com/CodaProtocol/coda/files/4179812/coda_crash_report_2020-02-08_19-30-00.069648.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
