### ISSUE TITLE
Coda crashes when trying to stake but works as simple node

### ISSUE THREAD

**Issue by ENDER71** [MinaProtocol/mina#4353]
I am trying to stake again. It worked fine until I decided to do a TX. After that node is not starting stacking anymore. It starts as node, it syncs but no way to start in staking mode.

[coda_crash_report_2020-02-10_20-19-39.166502.tar.gz](https://github.com/CodaProtocol/coda/files/4182869/coda_crash_report_2020-02-10_20-19-39.166502.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
