### ISSUE TITLE
Telemetry: Part 1

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#4361]
### Goal:

- diagnose bugs in Q/A net (part 1, part 2 will make easier)
- know whether the network is working (for when we launch 3.2, part 1, part 2 will make easier)

Need some service that checks (for part 1, periodically checks a bunch of checks, for part 2, collects data + live checks)

### Part 1:

1. Crawl network for peer list

    GraphQL endpoints for

    - asking node for its peers
    - asking node for the publickey it is staking with
    - asking node for the hash of the block it is on

    Logic to crawl the network, compile list of all the nodes and staking public keys

https://www.notion.so/codaprotocol/Telemetry-f27c2ac59d0c463f8c61feda8ba87253

**Comment by psteckler** [comment]
#4461 implements the RPC part of this.

**Comment by psteckler** [comment]
#4461 uses RPC, rather than GraphQL. The RPC uses the `advanced` mode of the executable.

How do we plan to use the telemetry results?
