### ISSUE TITLE
Coda daemon crashed. 

### ISSUE THREAD

**Issue by jerzybrzoska** [MinaProtocol/mina#4392]
[coda_crash_report_2020-02-15_08-35-52.659850.tar.gz](https://github.com/CodaProtocol/coda/files/4208256/coda_crash_report_2020-02-15_08-35-52.659850.tar.gz)
Crashed when run on my VPS from Linode.com. Other daemons than coda have not crashed. I was not doing anything during the time of the crash.

**Comment by jerzybrzoska** [comment]
Crashed again today. My other daemons intact. 
[coda_crash_report_2020-02-15_19-30-00.059104.tar.gz](https://github.com/CodaProtocol/coda/files/4209005/coda_crash_report_2020-02-15_19-30-00.059104.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
