### ISSUE TITLE
test_postake_three_producers:coda-txns-and-restart-non-producers sometimes forks

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#4411]
I think this didn't happen before the libp2p PR was merged? I'm not sure what's up with these. TODO: link to some failed runs

**Comment by deepthiskumar** [comment]
saw it on the bootstrap test 
https://circleci.com/gh/CodaProtocol/coda/337734?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by deepthiskumar** [comment]
test_postake_five_even_snarkless:coda-shared-prefix-multiproducer-test -num-block-producers 5
https://circleci.com/gh/CodaProtocol/coda/338679?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
