### ISSUE TITLE
Write to closed pipe in CI

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#4413]
Is the helper dying? What pipe is getting closed? I only saw this once, as a flake. https://app.circleci.com/jobs/github/CodaProtocol/coda/332190

**Comment by deepthiskumar** [comment]
Here's the log when I saw this error locally. Unfortunately I lost coda.log. This is from stdout that has info ,warn and error logs 
[closed_pipe_error_local.txt](https://github.com/CodaProtocol/coda/files/4233012/closed_pipe_error_local.txt)

**Comment by psteckler** [comment]
Saw this in the bootstrap test in CI:
```
[2020-3-9 21:38:05.157692]Coda_net2: error sending message on stream 2: $error
$error = "RPC #65 failed: \"only wrote 0 out of 9 bytes error: libp2p error error: cannot write to closed stream\""
[2020-3-9 21:38:06.074972]Coda_net2: error sending message on stream 4: $error
$error = "RPC #68 failed: \"only wrote 0 out of 9 bytes error: libp2p error error: cannot write to closed stream\""
[2020-3-9 21:38:06.332569]Coda_net2: error sending message on stream 5: $error
$error = "RPC #70 failed: \"only wrote 0 out of 9 bytes error: libp2p error error: cannot write to closed stream\""
```
