### ISSUE TITLE
Telemetry - Part II

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#4421]
### Part 2:

1. nodes send back to us when they get a block / produce a block
    1. can figure out diameter of the network / gossip time
    2. comparable visualization: [https://telemetry.polkadot.io/#map/Kusama CC3](https://telemetry.polkadot.io/#map/Kusama%20CC3)
    3. Do something lightweight to build, like a lambda

**Comment by psteckler** [comment]
What are the nodes contacting, an RPC or GraphQL endpoint on a dedicated telemetry endpoint?

Should that be opt-in or opt-out?
