### ISSUE TITLE
Telemetry: measure per-hop gossip latency

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#4422]
Into the `Message.msg` type, include a list of timestamps/peerid and track how long the block took the propagate and the path it took.

**Comment by psteckler** [comment]
#4461 implements the RPC part of this.

**Comment by aneesharaines** [comment]
Currently massively increases gossip traffic, need to talk about this with the Telemetry gang to see if there is a better solution

**Comment by aneesharaines** [comment]
Let's take this after the open tracing work is done so it can be utilized here
