### ISSUE TITLE
Coda daemon crashed

### ISSUE THREAD

**Issue by jerzybrzoska** [MinaProtocol/mina#4436]
[coda_crash_report_2020-02-21_07-22-18.568627.tar.gz](https://github.com/CodaProtocol/coda/files/4235252/coda_crash_report_2020-02-21_07-22-18.568627.tar.gz)
Other services that I've been running at this time were unaffected.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
