### ISSUE TITLE
Fix FAQ question headers

### ISSUE THREAD

**Issue by o1pranay** [MinaProtocol/mina#4456]
<img width="738" alt="Screen Shot 2020-02-24 at 4 41 22 PM" src="https://user-images.githubusercontent.com/50593560/75204026-9e083a80-5724-11ea-9b8b-dfaa65d063ce.png">

Multiple issues:
- multi line text gets center aligned, should be left align
- hovering on header causes link icon to appear, causing header to overflow, perhaps ellipses is better treatment
- link icon gets cut off

Suggest fix:
- change font to be more akin to the "answer" font -- the all caps and wide typeface is difficult to parse
- address issues above

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
