### ISSUE TITLE
Integers.Unsigned string serialization is broken

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#4462]
Recently found this when going down a rabbithole debugging decimal point support. `Integers.Unsigned.*.of_string` has incorrect behavior when handling strings of an invalid format. Below is an example snippet from utop that shows the issue.

```
utop # Unsigned.UInt64.of_string "1e-060000000";;
- : Unsigned.uint64 = <uint64 1>
```

**Comment by psteckler** [comment]
Under the hood, `ocaml-integers` uses `sscanf` for the `of_string` conversions.

This C program:
```c
#include <stdio.h>

int main (int argc, char **argv) {
  unsigned int x;

  sscanf ("1e-060000000","%u",&x);

  printf ("x: %u\n",x);

}
```
prints `1`.

**Comment by daira** [comment]
Good C programmers don't use `sscanf` for this very reason.

**Comment by mrmr1993** [comment]
Mitigated in https://github.com/MinaProtocol/mina/pull/8532. Closing.
