### ISSUE TITLE
QA-net crashes

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#4480]
All the crashes on QA-net so far

1.```("Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference(\"db626a53-65d7-36cd-f818-07337ef1ed7c\")")
  ("Raised at file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 111, characters 10-50"
    "Called from file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 367, characters 6-26"
    "Called from file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 369, characters 8-41"
    "Called from file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 638, characters 26-48"
    "Called from file \"src/lib/merkle_mask/maskable_merkle_tree.ml\", line 136, characters 24-46"
    "Called from file \"src/lib/coda_base/ledger.ml\" (inlined), line 194, characters 29-67"
    "Called from file \"src/lib/staged_ledger/staged_ledger.ml\", line 630, characters 21-59"
    "Called from file \"src/lib/staged_ledger/staged_ledger.ml\", line 746, characters 6-51"
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
    "Caught by monitor coda"))"```

2.```exn:  "(monitor.ml.Error
  (Failure
    "traced task `R&check next block timing` failed, exception reported to parent monitor")
  ("Raised at file \"stdlib.ml\", line 33, characters 17-33"
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
    "Caught by monitor coda"))"```

3.```exn:  "(monitor.ml.Error
  (Failure
    "Failed to apply transiton frontier diffs to persistent database correctly: target hash was 9939ce584b566209750aec1e57aedf9d9dca255b21570749a78ae69d1c0da0dd, resulting hash was 6b640bb46f31f941440f2d6047fb8a3de8fae88045c32e58f52bb91abbff8c80")
  ("Raised at file \"stdlib.ml\", line 33, characters 17-33"
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
    "Caught by monitor coda"))" ```

4.```exn:  "(monitor.ml.Error
  ("write to closed pipe"
    (pipe
      ((id 104) (buffer ()) (size_budget 0) (pushback (Full ()))
        (num_values_read 0) (blocked_flushes ()) (blocked_reads ())
        (closed (Full ())) (read_closed Empty) (consumers ())
        (upstream_flusheds ()))))
  ("Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30"
    "Called from file \"src/error.ml\", line 11, characters 19-40"
    "Called from file \"src/pipe.ml\", line 510, characters 2-15"
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
    "Caught by monitor coda"))" ```

5.```exn:  "(monitor.ml.Error
  "Assert_failure src/lib/block_producer/block_producer.ml:586:16"
  ("Raised at file \"src/lib/block_producer/block_producer.ml\", line 586, characters 16-183"
    "Called from file \"src/result.ml\", line 151, characters 9-15"
    "Caught by monitor coda"))"     ```

6.```exn:  "(monitor.ml.Error
  (Unix.Unix_error "No child processes" waitpid
    "((mode (WNOHANG)) (pid 151))")
  ("Raised at file \"src/core_unix.ml\", line 50, characters 4-43"
    "Called from file \"src/core_unix.ml\", line 930, characters 4-246"
    "Called from file \"src/unix_syscalls.ml\", line 596, characters 10-39"
    "Called from file \"src/unix_syscalls.ml\" (inlined), line 602, characters 21-55"
    "Called from file \"src/unix_syscalls.ml\", line 610, characters 33-48"
    "Called from file \"camlinternalLazy.ml\", line 27, characters 17-27"
    "Re-raised at file \"camlinternalLazy.ml\", line 34, characters 4-11"
    "Called from file \"src/process.ml\" (inlined), line 142, characters 13-25"
    "Called from file \"src/process.ml\", line 148, characters 25-31"
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
    "Caught by monitor coda"))"```

**Comment by ghost-not-in-the-shell** [comment]
For 5, if it happens to a block producer that just got restarted, then chances are it is the bug that described in https://github.com/CodaProtocol/coda/issues/4150

**Comment by ghost-not-in-the-shell** [comment]
After reading more logs, I found that sometimes the daemon would crash without a crash log.

For example, if you scan through all the logs for fish-block-producer-5 during 11:51-12:00  02/26/2020, you would find that the daemon restarted once without crash logs.

**Comment by ghost-not-in-the-shell** [comment]
Sometimes, nodes would restart without doing bootstrap. This is possible if there're not enough peers when the node requests best tip. If the node gets no response at all, then it would just start transition frontier controller. It could be the reason for the fork.
In the current implementation, we wait 60s to accumulate at least 4 peers. In most cases when bootstrap was not triggered, coda daemon failed to collect any peer in 60s.

**Comment by ghost-not-in-the-shell** [comment]
I just found out that the reason why we don't get crash report for some nodes. If the following scenario happens, there would be no crash report:
1. the prover process got terminated for some reason;
2. the daemon would be down after the child process is down
`Child process of kind $process_kind with pid $child_pid has terminated; terminating parent process $pid`

Usually the prover process is killed by a sigkill. We suspect that this is because the underlying system is out of memory, so it send a sigkill to the prover process.

**Comment by ghost-not-in-the-shell** [comment]
For 1, I saw this once with fish-block-producer-1 around 02-27 22:24:27.
According to the log, the node was about to produce a new block. Before it can finish producing the block, the node entered bootstrap mode. And the old frontier got destroyed, so the parent_staged_ledger in the parent_breadcrumb was lost.

Btw, I saw 4 happens around the same time. I am not sure if those were related. There's too little information in the log message for me to diagnose what happened there.

**Comment by garethtdavies** [comment]
I am experiencing 4 on the current testnet:

```
root@90d7798fdfe3:~# coda version
Commit 4395e91 on branch master
```

This is a node that is stuck at a blockheight of 1 but says it is synced:

```
Coda daemon status
-----------------------------------

Global number of accounts:       1017
Block height:                    1
Max observed block length:       1
Local uptime:                    40m38s
Ledger Merkle root:              jxH4Qmdt5jFUoVupEihNvVBpSh2oiN4cSjDqgpS7oq9Bsdat4U2
Protocol state hash:             3NLwBcsoZBdUGtndj14Cts5SRDwx3xvk4jEYAqBNRJ87BVzKuesM
Chain id:                        b90b8b744074d8cc9d864925b58d1f882b1c2e89a46245be3e0a969d39de43a0
Git SHA-1:                       4395e9162b55323e76141c174ed585a0bf8cce81
Configuration directory:         /root/.coda-config
Peers:                           6 (104.196.56.76:10008 34.74.99.242:10001 34.74.157.233:10005 34.75.134.50:10007 104.196.122.249:10009 35.237.255.71:10400)
User_commands sent:              0
SNARK worker:                    None
SNARK work fee:                  25000000
Sync status:                     Synced
```

Error:

```
Sept 19 06:01:38 1c5a83fe214c explorer_coda.1.kic412axyuofcgzpyj8xyij9v Generating crash report
Sept 19 06:01:38 1c5a83fe214c explorer_coda.1.kic412axyuofcgzpyj8xyij9v exn: "(monitor.ml.Error\n (\"write to closed pipe\"\n (pipe\n ((id 87) (buffer ()) (size_budget 0) (pushback (Full ()))\n (num_values_read 0) (blocked_flushes ()) (blocked_reads ())\n (closed (Full ())) (read_closed Empty) (consumers ())\n (upstream_flusheds ()))))\n (\"Raised at file \\\"src/error.ml\\\" (inlined), line 9, characters 14-30\"\n \"Called from file \\\"src/error.ml\\\", line 11, characters 19-40\"\n \"Called from file \\\"src/pipe.ml\\\", line 510, characters 2-15\"\n \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n \"Caught by monitor coda\"))"
Sept 19 06:01:38 1c5a83fe214c explorer_coda.1.kic412axyuofcgzpyj8xyij9v 2020-09-19 13:01:38 UTC [Info] Starting Bootstrap Controller phase
```

**Comment by deepthiskumar** [comment]
These are super old and most of them were addressed in various fixes
