### ISSUE TITLE
Automatically discover initial peers from s3 when starting daemon

### ISSUE THREAD

**Issue by Schmavery** [MinaProtocol/mina#4488]
Proposal:
`coda daemon` will pull a json file from s3 with the seed node peer addresses in it and try to connect to them.

`coda daemon -no-default-peers` will not pull the peers from s3

`coda daemon -peer ...` will add whatever extra peers as usual

This is a breaking change because it changes how `coda daemon` works (connects to the network by default), but seems like it could be worth it because of how much easier it makes connecting to the network.

**Comment by emberian** [comment]
Works for me. Should we sign the file?

**Comment by bkase** [comment]
cc @yourbuddyconner -- shouldn't be too easy to adjust tooling to support this right?

**Comment by yourbuddyconner** [comment]
Perhaps the initial seeds should be included in the daemon `config.json` and there should be a mechanism for fetching this file from S3?

My feeling is we should avoid a S3 dependency but it could also be written in such a way that an S3 failure doesn't affect functionality.

**Comment by Schmavery** [comment]
@yourbuddyconner ah right, I didn't mean to make the dependency explicitly on s3, I just said that because I think we have something uploaded there already that the wallet is using.
Is there an existing config.json that gets uploaded somewhere that I should check out? The important part is just to be able to pull the seed addresses from some static address when starting up the daemon.

**Comment by yourbuddyconner** [comment]
We currently don't have any tooling around config.json as I have been defaulting on passing runtime arguments via the CLI. If this config download process happens essentially transparent from the user's experience I don't really mind the ultimate solution as long as the download happens at runtime and not at build time. 

> If there's a way to statically determine the libp2p seed node multiaddr strings at build time and include them in a config file with the deb/brew package, then I'd be ok with that too, but I don't know as much about the details there.

Like I said above, it's my preference to not bake in the seed peers with the executable, so as long as we're not doing that I'm square.

**Comment by Schmavery** [comment]
Ok sounds like we're more or less on the same page, I also figured it would be simpler to pull this info at runtime. I don't think there will be any breaking change unless someone is explicitly running `coda daemon` with no peers specified anywhere.

**Comment by Schmavery** [comment]
We can work around this for now using daemon.json

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
