### ISSUE TITLE
Add systemd definition to deb package (to run coda as a service on linux)

### ISSUE THREAD

**Issue by Schmavery** [MinaProtocol/mina#4493]
People have already done work to
- Create a deb for coda ([here](https://github.com/CodaProtocol/coda/blob/develop/scripts/rebuild-deb.sh))
- Create a systemd definition for coda ([here](https://github.com/jkrauska/coda-systemd) and [here](https://forums.codaprotocol.com/t/autodeploy-kinda-coda-node-and-systemd-integration-script/284))

...but they haven't been put together yet.

I recently merged some work to get this running on MacOS with https://github.com/CodaProtocol/homebrew-coda/pull/3 (so people can run `brew services start coda`) but it would be great to get something similar working on Ubuntu/etc too.

We've recently added support in the daemon.json file for all the configuration used in the systemd definitions above, so we should be able to make a service that just launches `coda daemon` with no flags, and have it configured by the daemon.json file. Much simpler!

Searching for `systemd` and `deb package` together brings up some potentially relevant results but I'm not very familiar with this. If someone is interested in making Coda easier to use on Linux, this would be a great first issue to work on :)

**Comment by Schmavery** [comment]
Actually `daemon.json` might be a better way of handling configuration of these services

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
