### ISSUE TITLE
Epoch Ledger Persistence

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#4504]

**Comment by imeckler** [comment]
@ghost-not-in-the-shell says merging the epoch ledger persistence will make coda less stable.

Once you change the epoch ledger you need to switch the last and two-ago epoch ledger, we delete one and replace it with the other.

It could be that when we delete the two-back epoch ledger, some existing bootstrap could depends on it which could make the bootstrap fail.

Basically the main issue for the serving node is:

- it will have a handle open to the two-back rocksDB
- we delete the DB from under the handle
- the sync-ledger serving node tries to read from the now invalid handle.

@ghost-not-in-the-shell is not sure how likely this is to actually happen

**Comment by aneesharaines** [comment]
Need to fix tests and update pr from develop

**Comment by aneesharaines** [comment]
Should test in the next QA net where persistence is enabled.
