### ISSUE TITLE
Close out Non-Consensus node RFC

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#4505]
There are still some open questions that need to be resolved. Mainly implementing to gossip layer and routing mechanism and the staged ledger validity.

**Comment by aneesharaines** [comment]
There are still some open questions that need to be resolved.  Mainly implementing to gossip layer and routing mechanism and the staged ledger validity.

**Comment by zmanian** [comment]
Seems to referencing the PR in https://github.com/CodaProtocol/coda/pull/3537

**Comment by mrmr1993** [comment]
RFC (https://github.com/MinaProtocol/mina/pull/3537) has been closed out.
