### ISSUE TITLE
Significantly improved footer on website

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#4519]
This is really important for us because when folks don't find what they're looking for on whichever page they're on on the website, they'll be able to go directly to somewhere they need to! We think this will make it much easier for people to learn and use Coda!

See design spec here:
https://www.figma.com/file/Xu9Yx2O7c6qXabesAdS0HyPH/Coda-Website?node-id=1341%3A0

See `frontend/website/src/components/Page.re` to where the footer is currently -- to build out this newly improved footer we should definitely create a new `components/Footer.re` file.

**Comment by LukasGerm** [comment]
Hey, I would love to tackle this one. I will get on it soon!

**Comment by idkjs** [comment]
Hey folks. Is there a style guide for this project? Preference for `css-grid` vs `flex`? Etc?

**Comment by Schmavery** [comment]
@idkjs Sorry, didn't see this.
We tend to use flexbox unless the component would be much easier to write with grid.
That bs-css update looks cool, feel free to make a separate PR for that (it will be easier to review if it's not combined with the footer change).
Thanks :)
