### ISSUE TITLE
Coda daemon crashed

### ISSUE THREAD

**Issue by aquariusluo** [MinaProtocol/mina#4520]
coda daemon \
>     -external-port 8302 \
>     -discovery-port 8303 \
>     -peer /dns4/seed-one.genesis-redux.o1test.net/tcp/10002/ipfs/12D3KooWP7fTKbyiUcYJGajQDpCFo2rDexgTHFJTxCH8jvcL1eAH \
>     -peer /dns4/seed-two.genesis-redux.o1test.net/tcp/10002/ipfs/12D3KooWL9ywbiXNfMBqnUKHSB1Q1BaHFNUzppu6JLMVn9TTPFSA
2020-03-08 03:14:19 UTC [Info] Coda daemon is booting up; built with commit "911631273ee694596407d1a181064ca6174cd8a3" on branch "master"
2020-03-08 03:14:19 UTC [Info] Daemon will expire at "2024-01-15 14:00:00-07:00"
2020-03-08 03:14:19 UTC [Info] Booting may take several seconds, please wait
2020-03-08 03:14:39 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error\n  (\"Writer error from inner_monitor\"\n    (Unix.Unix_error \"Broken pipe\" writev_assume_fd_is_nonblocking \"\")\n    (writer\n      ((id 2)\n        (fd\n          ((file_descr 34)\n            (info\n              (\"child process\"\n                (stdin (pid 2524) (prog /proc/2427/exe)\n                  (args (parallel-worker)))\n                src/process.ml:62:17))\n            (kind Fifo) (supports_nonblock true) (have_set_nonblock true)\n            (state (Open Empty))\n            (watching ((read Not_watching) (write Not_watching)))\n            (watching_has_changed false) (num_active_syscalls 0)\n            (close_finished Empty)))\n        (monitor\n          (((name (id 56)) (here ()) (id 56) (has_seen_error false)\n             (is_detached false))\n            ((name \"\") (here ()) (id 41) (has_seen_error false)\n              (is_detached true))))\n        (inner_monitor\n          (((name (id 57)) (here ()) (id 57) (has_seen_error true)\n             (is_detached true))\n            ((name \"\") (here ()) (id 41) (has_seen_error false)\n              (is_detached true))))\n        (background_writer_state Stopped_permanently)\n        (background_writer_stopped (Full ())) (syscall Per_cycle)\n        (bytes_received 349) (bytes_written 0) (scheduled_bytes 0)\n        (scheduled_back 0) (back 0) (close_state Open) (close_finished Empty)\n        (close_started Empty) (num_producers_to_flush_at_close 0)\n        (flush_at_shutdown_elt (<opaque>))\n        (check_buffer_age\n          (((writer <opaque>) (maximum_age 2m)\n             (bytes_received_at_now_minus_maximum_age 0)\n             (bytes_received_queue ()) (times_received_queue ())\n             (bytes_seen 0) (too_old Empty))))\n        (consumer_left (Full ())) (raise_when_consumer_leaves true)\n        (open_flags (Full (Ok (wronly)))) (line_ending Unix))))\n  (\"Caught by monitor (id 56)\"))"
2020-03-08 03:14:39 UTC [Fatal] Exception when generating crash report: $exn
        exn: "(Sys_error\n \"rm -rf /home/ubuntu/.coda-config/coda_crash_report*: Cannot allocate memory\")"

  ☠  Coda daemon crashed. The Coda Protocol developers would like to know why!

  Please:
    Open an issue:
      <https://github.com/CodaProtocol/coda/issues/new>

    Briefly describe what you were doing and include the last 20 lines from .coda-config/coda.log and then paste the following:
Summary:
"Shutdown before Coda instance was created"
Status:
{"OS_type":"Unix","Release":"4.15.0-1057-aws","Machine":"x86_64","Sys_name":"Linux","Exception":"(monitor.ml.Error\n  (\"Writer error from inner_monitor\"\n    (Unix.Unix_error \"Broken pipe\" writev_assume_fd_is_nonblocking \"\")\n    (writer\n      ((id 2)\n        (fd\n          ((file_descr 34)\n            (info\n              (\"child process\"\n                (stdin (pid 2524) (prog /proc/2427/exe)\n                  (args (parallel-worker)))\n                src/process.ml:62:17))\n            (kind Fifo) (supports_nonblock true) (have_set_nonblock true)\n            (state (Open Empty))\n            (watching ((read Not_watching) (write Not_watching)))\n            (watching_has_changed false) (num_active_syscalls 0)\n            (close_finished Empty)))\n        (monitor\n          (((name (id 56)) (here ()) (id 56) (has_seen_error false)\n             (is_detached false))\n            ((name \"\") (here ()) (id 41) (has_seen_error false)\n              (is_detached true))))\n        (inner_monitor\n          (((name (id 57)) (here ()) (id 57) (has_seen_error true)\n             (is_detached true))\n            ((name \"\") (here ()) (id 41) (has_seen_error false)\n              (is_detached true))))\n        (background_writer_state Stopped_permanently)\n        (background_writer_stopped (Full ())) (syscall Per_cycle)\n        (bytes_received 349) (bytes_written 0) (scheduled_bytes 0)\n        (scheduled_back 0) (back 0) (close_state Open) (close_finished Empty)\n        (close_started Empty) (num_producers_to_flush_at_close 0)\n        (flush_at_shutdown_elt (<opaque>))\n        (check_buffer_age\n          (((writer <opaque>) (maximum_age 2m)\n             (bytes_received_at_now_minus_maximum_age 0)\n             (bytes_received_queue ()) (times_received_queue ())\n             (bytes_seen 0) (too_old Empty))))\n        (consumer_left (Full ())) (raise_when_consumer_leaves true)\n        (open_flags (Full (Ok (wronly)))) (line_ending Unix))))\n  (\"Caught by monitor (id 56)\"))","Command":"Command: (coda daemon -external-port 8302 -discovery-port 8303 -peer\n /dns4/seed-one.genesis-redux.o1test.net/tcp/10002/ipfs/12D3KooWP7fTKbyiUcYJGajQDpCFo2rDexgTHFJTxCH8jvcL1eAH\n -peer\n /dns4/seed-two.genesis-redux.o1test.net/tcp/10002/ipfs/12D3KooWL9ywbiXNfMBqnUKHSB1Q1BaHFNUzppu6JLMVn9TTPFSA)"}

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
