### ISSUE TITLE
Update deb to use libjemalloc2

### ISSUE THREAD

**Issue by Schmavery** [MinaProtocol/mina#4601]
As reported by a couple of community members, looks like we need to swap libjemalloc1 to libjemalloc2 below, and then try it out and see if it works:

https://github.com/CodaProtocol/coda/blob/6b056ed364e661eb40b21338f7f55ba2feca1bcc/scripts/rebuild-deb.sh#L42

More info here: https://askubuntu.com/questions/1092417/mssql-server-depends-on-libjemalloc1-which-is-a-virtual-package-and-is-not-prov

Edit with more info:
It seems like libjemalloc2 doesn't exist in ubuntu 18.04, which is what most of our build infrastructure depends on.
In the short term the solution is probably to ask people to use 18.04 (LTS).

**Comment by emberian** [comment]
It isn't too hard to publish an extra deb for newer Ubuntus as long as this is the only problem. Seems like it's probably worthwhile to me? I can do this.

**Comment by emberian** [comment]
It's not too hard to publish a new deb, but it is hard to build a working coda against these new libraries without wholesale swapping to a newer distro.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
