### ISSUE TITLE
Make archive node installable

### ISSUE THREAD

**Issue by Schmavery** [MinaProtocol/mina#4606]
Add a package to deb build and brew to install the archive node 

Also remove postgres from the dependencies of the main coda package:
- https://github.com/CodaProtocol/coda/blob/63c1bea24a37aaa51e02206e436f674804a48097/scripts/rebuild-deb.sh#L42
- Coda_lib depends on the archive_lib library, which depends on postgres through the caqti driver. archive_lib might need to be split into one part that talks to postgres (used by the archive executable) and one part for the communication between coda and archive.

#4577 should be updated to reflect the new way of installing the archive node and we should go through the flow to verify that it works.

**Comment by shimkiv** [comment]
I think it was implemented already:
```
> sudo apt install mina-
mina-archive                 mina-berkeley                mina-bp-stats-sidecar        mina-devnet                  mina-generate-keypair        mina-mainnet                 mina-snapp-test-transaction  mina-zkapp-test-transaction  mina-zkarchive
```
