### ISSUE TITLE
Product QA 3.2 

### ISSUE THREAD

**Issue by michellewong793** [MinaProtocol/mina#4613]
Going through the docs... 

1. Docs should not have external and discovery ports anymore 
2. Peers list on the CLI is too long, visually unappealing 
3. Faucet bot need to be up for requesting funds 
4. Will we have echo service up for this release? 
5. In Creating an Account, we should specify that you will need to specify a password for the account. We need to remind people to save this password so they can unlock in the next step. 
6. Participating in Consensus: are we going to have a list of accounts that people can delegate to if they want to?
7.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
