### ISSUE TITLE
Genesis proof download for nonconsensus

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#4693]
This is one of the nonconsensus node tasks mentioned in #4674.

**Comment by aneesharaines** [comment]
Plan to resume when Izzy's PR is in.

**Comment by mrmr1993** [comment]
When #4922 merges, genesis proofs will be uploaded separately to the `snark-keys.o1test.net` S3 bucket. For example, the current compile-time genesis proof is [here](https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/genesis_proof_178ee55a5f56e5cdb3c9d1fdaeba38b10b334107659118cd42b0fce921fb317b).

**Comment by psteckler** [comment]
Nonconsensus node plans have changed, obsolete.
