### ISSUE TITLE
Migrate to dune 2.5, use enabled_if instead of optcomp

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#4710]
Dune 2.5 has now been released. As part of the changes, ocaml/dune#3344 landed, which allows us to disable libraries based on the build profile.

In practical terms, this allows us to
* generate a mapping from build profile to 'config libraries'
  - we can generate dune files from our `config.mlh` files so that each config library is enabled only for the profiles that set it
  - e.g. the library `coda_config_medium_curves` should be enabled for all medium curve profiles, disabled otherwise
* use separate libraries for different configurations
  - the build artefacts for these will then be preserved, so changing build configuration will only involve re-linking the final binary, and no recompilation
  - we can use either virtual modules or the library dependency `(select ... from ...)` stanza to minimise rebuilds where only parts of modules change, using the config libraries to select the correct implementation
* block valid artefacts from some build profiles (e.g. consensus builds) from being invalidated by unrelated builds (e.g. nonconsensus)

This will remove most of the pain and friction from switching build profiles locally, and allow CI to build different versions of the coda binary with minimum duplicated work.

**Comment by psteckler** [comment]
I think dune 2.5 will allow using `dune build` again, because we can enable nonconsensus libraries only for specific profiles. Currently, we must use `make build` to build for `dev`, for instance.
