### ISSUE TITLE
Smoke Tests

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#4724]
- [ ] Produce a tool (Codename SMOKE) which launches a testnet on a schedule.
- [ ] Produce a tool (Codename MONSTER) that can be used to run the integration test suite against a live network

Exit Criteria
- Basic framework exists with a subset of testing functionality implemented.

**Comment by aneesharaines** [comment]
@yourbuddyconner - can you add the exit criteria to the description?
