### ISSUE TITLE
Gossip Analysis (Network Partition)

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#4732]
Add functionality to the Gossip Analysis CLI which outputs a DAG showing which nodes are gossiping blocks. 

Acceptance: 
- Allows the user to visually verify a network partition
- Outputs an image for visual verification
- Optionally outputs a JSON representation which can be processed by testing tools

**Comment by yourbuddyconner** [comment]
Blocked pending #4816

**Comment by aneesharaines** [comment]
Just output is still oustanding, moving to infra board

**Comment by emberian** [comment]
https://github.com/openmina/mina-network-debugger is the new solution
