### ISSUE TITLE
Gossip Analysis (Blockchain Forks)

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#4733]
Extend the Gossip Analysis CLI and add functionality that enables the user to visually verify if the blockchain is forked. 

Acceptance:
- Allows the user to visually verify a fork in the chain
- Outputs an image for visual verification
- Optionally outputs a JSON representation which can be processed by testing tools

**Comment by yourbuddyconner** [comment]
Currently blocked on #4810

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
