### ISSUE TITLE
RFC Process Improvements

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#4738]
The RFC documents in our project have proven themselves to be a successful way to communicate designs for larger projects. When feedback is given, we're able to adjust and iterate.

However, there has been some friction.

Friction Points:
* Marking RFCs as "reviewed" in one way or another from relevant stakeholders takes too long
* Criteria for approving RFCs is outdated -- Originally it was set up in such a way that newer folks to the team would have someone who has more context to verify that all the context was considered. This needs to be revisited.
* Criteria for landing RFCs has always been nebulous -- Should it land when it's approved? When it's implemented?
* CI runs on RFC and documentation changes
* TODO

Action Items:
- [ ] Propose a new process - Aneesha
	(use "request changes" / "approve" buttons)
- [ ] Explore technical solutions to prevent friction (bots? ci fixes?)

Exit Criteria:
1. Change required reviewers to a relevant set of folks (tech leads?)
2. CI shouldn't run unrelated jobs (only markdown linting or something)
3. Institute culture of new process via shared in eng group (async or meeting)

**Comment by psteckler** [comment]
@bkase we do skip some CI steps for RFCs via the script `skip_if_only_frontend_or_rfcs.sh`

**Comment by aneesharaines** [comment]
Draft - https://www.notion.so/codaprotocol/Revisiting-the-RFC-Process-c556bea42cbe472a9985f1f97d628285
