### ISSUE TITLE
Disable snark_pool logs in integration tests with proof level none

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#4742]
Currently our integration test logs are huge. Usually over 1 GB. Downloading a log from CI usually takes 2-4 min.

For the integration tests that use proof-level none, we don't need logs from the snark_pool or network_pool. We can disable or even trim the logs before we upload them to CI. Usually it help us cut the log size in half.

**Comment by ghost-not-in-the-shell** [comment]
I personally also chunk off the logs from libp2p if I believe the network layer is functioning correctly.

If we chunk off  the logs from network_pool and libp2p, then usually the logs would be reduced from 1.X GB to 1X megabytes.

We could consider both the original log and the processed log to CI, so developers won't spend a long time downloading the logs.

**Comment by aneesharaines** [comment]
@ghost-not-in-the-shell  to follow up with @yourbuddyconner - may be a good itme for the taskforce

**Comment by yourbuddyconner** [comment]
Talking with @ghost-not-in-the-shell, this is a pretty simple change. 

We would add this extra log parsing logic to the `artifacts.sh` script: https://github.com/CodaProtocol/coda/blob/develop/scripts/artifacts.sh

**Comment by imeckler** [comment]
@ghost-not-in-the-shell suggests uploading 2 versions of the long

- the full version
- the version with snark-pool logs filtered out

**Comment by aneesharaines** [comment]
Need to modify testui.py
