### ISSUE TITLE
3.2a prover crashes and blocks delayed

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#4746]
For prover crashes in the container for 3.2a .
The container has a block producer and a snarkworker running. 
Issues currently observed:
1. block generation taking too long
2. prover process crashing

**Comment by nat8552** [comment]
The logs attached:

[coda.log](https://github.com/CodaProtocol/coda/files/4519292/coda.log)
[coda-prover.log](https://github.com/CodaProtocol/coda/files/4519253/coda-prover.log)
