### ISSUE TITLE
CI Refactor

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#4762]
Friction:
- CircleCI is expensive because it's hosted (P1)
- Slow builds (P2)
    - Our configuration is not scheduled optimally — this leads to slower builds than are actually possible (P2.1)
        - Parallelism is not granular but rather just at the outskirts (P2.1.1)
        - Test execution doesn't share artifacts before fanning out (P2.1.2)
    - Instances are not as large as we'd want them to be (even at the "largest" size) (P2.2)
    - Test execution is not granular (P2.3)
- Requires a manual template expansion step (test.py) (P3)
- Iterating on builds is requires running things on our existing build infrastructure (P4)
- Flaky tests don't have a good story ;; It isn't clear which tests are truly "flaky and we want to ignore the flake" and this failure is important to look at (P5)

Exit Criteria:
* Framework in place enabling build pipelines to be written to solve the above friction points
* Framework successfully used to build-artifacts-medium-curves + the new integration tests (everything else can stay as is for now)

**Comment by robinbb** [comment]
@bkase Over the last many months, work on the CI may have made this issue redundant. Given that it mentions CircleCI, is this issue now deprecated? I grant that some of the problems identified above remain, however. Should this issue be closed? Or, should it pass on to the Mina Foundation engineering team, @bkase ? Or, something else?
