### ISSUE TITLE
BuildKite CI: New integration tests pipeline(s)

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#4807]
Depends on us finishing the first integration test.

This entails adding a new pipeline for the test and possibly dhall infrastructure for helping to define future integration tests (for example a function that takes the name of the test and sets up all the boilerplate for you). 
This will become more clear after we have a few integration tests implemented.

Epic: #4762

**Comment by ghost-not-in-the-shell** [comment]
1) generate/obtain a docker image for the current build pipeline
2) build `test_executive.exe`
3) load secret key json file for a service account with permissions to deploy
4) authenticate service account using gcloud cli (e.g. `gcloud auth activate-service-account`
5) set `export GCLOUD_API_KEY="..."` to a valid gcloud api key with permissions to pub/sub and logging
6) execute test like so `./_build/default/src/app/test_executive/test_executive.exe --coda-image <docker-image-id> <test-name>` for each test

--nholland94
