### ISSUE TITLE
GraphQL delegation inconsistencies

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#4825]
I am trying to test stake delegation and getting inconsistent results from the GraphQL endpoint. Previously [raised this issue in Discord](https://discordapp.com/channels/484437221055922177/601215883939020852/699288425257500672) but adding an issue to track more easily.

I'm testing a pseudo staking pool on the sandbox node (`Commit 9babcbd on branch docker-uses-runtime-genesis`) by sending funds from the default account `4vsRCVMNTrCx4NpN6kKTkFKLcFN4vXUP5RB9PqSZe1qsyDs4AW5XeNgAf16WUPRBCakaPiXcxjp6JUpGNQ6fdU977x5LntvxrSg11xrmK6ZDaGSMEGj12dkeEpyKcEpkzcKwYWZ2Yf2vpwQP` to a second account `4vsRCVzKDJk7MuHTgHTQxXBn1rz2EksNFba1frLJVB7ErZzbRKNgtHWvfqQcb8kmL1B63rrgwgGiKp32DsZ4jjJNXnwQndqBVWVb1w51MueBaTk4vpLAXMReH5EuTyKKkwTLzG4pepW6pFV1` and then a delegation transaction. The initial transaction and delegation transaction have been included in a block and snarked in the **prior** epoch. The output of `coda advanced dump-ledger` is correct and shows the correct balances and the delegation. However, the output from GraphQL shows both an incorrect balance for the public key (which is still the initial value) and also does not show the additional delegator.

So, unless it takes several epochs for this to be detected(?) I don't think this is working correctly.

```
query MyQuery {
  account(publicKey: "4vsRCVMNTrCx4NpN6kKTkFKLcFN4vXUP5RB9PqSZe1qsyDs4AW5XeNgAf16WUPRBCakaPiXcxjp6JUpGNQ6fdU977x5LntvxrSg11xrmK6ZDaGSMEGj12dkeEpyKcEpkzcKwYWZ2Yf2vpwQP") {
    delegators {
      publicKey
      balance {
        total
      }
    }
    lastEpochDelegators {
      balance {
        total
      }
      publicKey
    }
  }
}
```

This outputs:

```
{
  "data": {
    "account": {
      "delegators": [
        {
          "publicKey": "4vsRCVMNTrCx4NpN6kKTkFKLcFN4vXUP5RB9PqSZe1qsyDs4AW5XeNgAf16WUPRBCakaPiXcxjp6JUpGNQ6fdU977x5LntvxrSg11xrmK6ZDaGSMEGj12dkeEpyKcEpkzcKwYWZ2Yf2vpwQP",
          "balance": {
            "total": "66000000000000"
          }
        }
      ],
      "lastEpochDelegators": [
        {
          "balance": {
            "total": "66000000000000"
          },
          "publicKey": "4vsRCVMNTrCx4NpN6kKTkFKLcFN4vXUP5RB9PqSZe1qsyDs4AW5XeNgAf16WUPRBCakaPiXcxjp6JUpGNQ6fdU977x5LntvxrSg11xrmK6ZDaGSMEGj12dkeEpyKcEpkzcKwYWZ2Yf2vpwQP"
        }
      ]
    }
  }
}
```

However, the output of `coda advanced dump-ledger` shows the correct balances and delegation:

```
root@ecfe62b46bf8:/# coda advanced dump-ledger
(((public_key
   4vsRCVw9P7XQFJWS4FsAsiXRSJyEKiVLCnVw2mRreE7iWout75RvZnm9q46sed2GvBF9Rh972AJrnuhrpPfCDGyhgsJm6kxZGhP5x9CTdty4cpFA8FmxNL8gB2UPTweGnQ1svjTVgUAbb8qB)
  (token_id 1) (balance 1000) (nonce 0)
  (receipt_chain_hash
   19757019489039323524424303724366016758468486304200637067838030177567350995449555421612580512590173989953432411241939510263538481232324542773081401021435907797080676902782230551702743986493561570935684268031608232026593554653121)
  (delegate
   4vsRCVw9P7XQFJWS4FsAsiXRSJyEKiVLCnVw2mRreE7iWout75RvZnm9q46sed2GvBF9Rh972AJrnuhrpPfCDGyhgsJm6kxZGhP5x9CTdty4cpFA8FmxNL8gB2UPTweGnQ1svjTVgUAbb8qB)
  (voting_for 1) (timing Untimed))
 ((public_key
   4vsRCVMNTrCx4NpN6kKTkFKLcFN4vXUP5RB9PqSZe1qsyDs4AW5XeNgAf16WUPRBCakaPiXcxjp6JUpGNQ6fdU977x5LntvxrSg11xrmK6ZDaGSMEGj12dkeEpyKcEpkzcKwYWZ2Yf2vpwQP)
  (token_id 1) (balance 84000100000000) (nonce 7)
  (receipt_chain_hash
   19679611803693893750443829138425134950306793653611566109368511041589740344586910323784837991578148576768507335289855016605182849181845673902314435798938975525021057435580192935011769308141295787457771053489577742095324566260492)
  (delegate
   4vsRCVMNTrCx4NpN6kKTkFKLcFN4vXUP5RB9PqSZe1qsyDs4AW5XeNgAf16WUPRBCakaPiXcxjp6JUpGNQ6fdU977x5LntvxrSg11xrmK6ZDaGSMEGj12dkeEpyKcEpkzcKwYWZ2Yf2vpwQP)
  (voting_for 1) (timing Untimed))
 ((public_key
   4vsRCVzKDJk7MuHTgHTQxXBn1rz2EksNFba1frLJVB7ErZzbRKNgtHWvfqQcb8kmL1B63rrgwgGiKp32DsZ4jjJNXnwQndqBVWVb1w51MueBaTk4vpLAXMReH5EuTyKKkwTLzG4pepW6pFV1)
  (token_id 1) (balance 84999899000000) (nonce 1)
  (receipt_chain_hash
   19229141115039970121949382118395679509058064070012467677096996465590179824050855357975483654690207958215205105824546834786198846273242853375820989162297925403779190114984619719389085030886951254879072818312564483940137644604382)
  (delegate
   4vsRCVMNTrCx4NpN6kKTkFKLcFN4vXUP5RB9PqSZe1qsyDs4AW5XeNgAf16WUPRBCakaPiXcxjp6JUpGNQ6fdU977x5LntvxrSg11xrmK6ZDaGSMEGj12dkeEpyKcEpkzcKwYWZ2Yf2vpwQP)
  (voting_for 1) (timing Untimed)))
```

**Comment by bkase** [comment]
Thank you for raising this here!

> unless it takes several epochs for this to be detected

I think this raises a UX issue that we need to address; namely, tracking the current state of a delegation from the moment it is sent until the moment it is included for staking purposes.

It isn't as simple as "one epoch afterward". It's actually "time it takes for the delegation transaction to emit from the parallel scan state -- aka emitting through the top proof https://codaprotocol.com/blog/scanning-for-scans " + 1-2 epochs (depending on when in the epoch you sent the transaction)

Originally, I was quite confused by the error that you raised, but after thinking about it more carefully, here's what I think is going on:

We have seen delegations post-genesis ledger take effect in testnets in the past. This is how we "re-delegate" stake to move stake from folks that didn't show up who signed up for the genesis ledger to those that are joining in the middle. And I believe those who joined in the middle have managed to successfully produce blocks off of that stake, but it is probably worth double checking.

In a live testnet (or mainnet), there will be enough snark workers available and txn volume (at least this is what we've observed in testnets) to push things through the scan state relatively quickly. In a sandbox environment, there is only one snark worker and also fewer transactions flowing through the network. What is usually, let's say an 10 block latency, is now a 2^10 block latency for the delegation change to be witnessed by consensus.

Regardless if this is the real reason or something else is; I think this issue should generate the following extra tasks:

1. Document this process more thoroughly and in more detail. At least have some very detailed technical documentation we can point more technical folks to and let blog posts emerge from there naturally.
2. Build UX around understanding where the delegation transaction is in its lifecycle
3. Come up with some way to force things through in a sandbox or similar testing environment so folks can test delegations properly.

**Comment by garethtdavies** [comment]
> We have seen delegations post-genesis ledger take effect in testnets in the past. This is how we "re-delegate" stake to move stake from folks that didn't show up who signed up for the genesis ledger to those that are joining in the middle. And I believe those who joined in the middle have managed to successfully produce blocks off of that stake, but it is probably worth double checking.

I'm pretty certain that is true, which is why I initially thought this was _just_ a case of the GraphQL API returning the "wrong" data. Clearly it's a little more involved... :)

I was also confused by the fact the staking balance of the one key didn't change during epochs (again, need to read up on the consensus stuff) regardless of the lack of the other delegated stake.

Either way, I'll continue to experiment, and run this for a while so as to have something to run later on a functional testnet to validate!

**Comment by bkase** [comment]
@garethtdavies thanks! Definitely seems more like an API bug now for sure

**Comment by garethtdavies** [comment]
Testing this on the current testnet and the GraphQL API still does not return delegators correctly. Looking at the ledger here https://codaexplorer.garethtdavies.com/ledger and choosing a key that has a delegate such as `4vsRCVV4YJFHehvTT45GN4afHQVCe89xCEcbGXSiu3py8KMjY9rNBd89Bk5RU2qgcNFyAsAo3Tqkfkp2PBFDvEauPUmCypwkoS8Uont17MLYnJeUzy9uh3utKGoajSqJLorvDZBgeFgRk2Lg` which is delegating to `4vsRCVXhABx36W2fNRzMHaSZiRicUgKkd5eQeZujg6gsE7PZVMZj544n56zCpeM8dXy6MCjMaGJrrSP9HBVvqxHdKAF4sBeuCeMi1QbZrBGLqALXyBiXiRYvPqr5rpEKAQteV1t8MWwAm4jW` the resulting GraphQL response does not return the delegator:

```
query MyQuery {
  account(publicKey: "4vsRCVXhABx36W2fNRzMHaSZiRicUgKkd5eQeZujg6gsE7PZVMZj544n56zCpeM8dXy6MCjMaGJrrSP9HBVvqxHdKAF4sBeuCeMi1QbZrBGLqALXyBiXiRYvPqr5rpEKAQteV1t8MWwAm4jW") {
    delegators {
      publicKey
    }
    balance {
      blockHeight
      total
    }
    lastEpochDelegators {
      publicKey
    }
  }
}
```

from 

```
query MyQuery {
  account(publicKey: "4vsRCVXhABx36W2fNRzMHaSZiRicUgKkd5eQeZujg6gsE7PZVMZj544n56zCpeM8dXy6MCjMaGJrrSP9HBVvqxHdKAF4sBeuCeMi1QbZrBGLqALXyBiXiRYvPqr5rpEKAQteV1t8MWwAm4jW") {
    delegators {
      publicKey
    }
    balance {
      blockHeight
      total
    }
    lastEpochDelegators {
      publicKey
    }
  }
}
```

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
