### ISSUE TITLE
Error in GraphiQL Code Exporter

### ISSUE THREAD

**Issue by togran** [MinaProtocol/mina#4831]
### Overview
Code Exporter provides sample code to be included in your software. However, if you use fetch option, this code will not work and will produce an error 400 "Bad Request"

### Steps to reproduce:

1. Open http://localhost/graphql
2. Copy the code from Code Exporter (right side of the screen)
3. Press F12 to open developers' console (assuming you are using Google Chrome)
4. Paste the code and press Enter

**Expected:** Object with result
**Actual:** Error 400 "Bad Request" with body "Must provide query string"

### Propose
Simply add the line
`headers: { 'Content-Type': 'application/json' },`
after the line
`method: "POST",`
to fix this issue

`# coda -version`
`Commit 9babcbd on branch docker-uses-runtime-genesis`

Discord: Max S (P2P.ORG)#6559

**Comment by Schmavery** [comment]
Thanks for reporting this @togran, I haven't had a chance to fix it yet but your proposed workaround looks right in the meantime :)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
