### ISSUE TITLE
Add ability to prune data in archive node

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#4885]
For Rosetta API support:
https://www.notion.so/codaprotocol/Rosetta-RFC-14fcd118cdb14ab6a210d65e8c471861

We need to add a configuration option to the archive node to prune data that relates to blocks that are more than 1000 blocks old (for example — block number is configurable).

**Comment by aneesharaines** [comment]
The archive process should manage the pruning.    Please write a comment in the Rosetta spec to make sure Product team is aligned with the proposed implementation.

**Comment by robinbb** [comment]
@aneesharaines I can't see the pointed-to Notion document. Can you paste its content, here, if this issue is still applicable.

**Comment by kantp** [comment]
Thanks, I can access the page now.

**Comment by kantp** [comment]
To add context: the "best practices" section in the rosetta documentation says that it should be possible to configure nodes in a way that they prune historic data, to make a deployment more manageable. See https://www.rosetta-api.org/docs/storage_pruning.html

**Comment by kantp** [comment]
I did some looking at old documents, and talked to @nholland94. It looks like historically, the abiility to prune at one point was about to become a hard requirement, but then ended up being a recommended best practice (we have not implemented it yet).

We should plan to implement this, but at a priority that is lower than the changes needed to support the hardfork, and also lower than ensuring that the rosetta-api test suite passes.

**Comment by ejMina226** [comment]
It looks like there might already be some functionality to achieve this. In archive_cli.ml there is a command_prune that might be helpful. I will investigate this further.

**Comment by ejMina226** [comment]
The code should be callable from the archive executable using the "prune" command an argument that is either "--height", "--num-blocks", or "--timestamp". I haven't tried it out yet, but will do.

**Comment by kantp** [comment]
Coinbase confirms that dropping old data is not a requirement, so I'm removing this from the rosetta project.
