### ISSUE TITLE
Enable SPF, DKIM and DMARC mail security features for O(1) Labs Domains 

### ISSUE THREAD

**Issue by O1ahmad** [MinaProtocol/mina#4905]
**Overview:**

In order to protect the integrity of O(1) Labs' mail correspondence and delivery pipeline from spammers who might attempt to spoof or send emails that only appear to come from O(1)'s trusted domain, it makes sense to ensure our mail and DNS host providers are properly configured for and make use of the following key anti-spoofing techniques available:
- **Sender Policy Framework (SPF)** : lists the mail servers that can send email from your domain.

- **DomainKeys Identified Mail (DKIM)**: adds an encrypted signature to the header of all outgoing messages. Email servers that get signed messages use DKIM to decrypt the message header,  and verify the message was not changed after it was sent.

- **Domain-based Message Authentication, Reporting, and Conformance (DMARC)** : ensures Incoming messages must be authenticated by SPF, DKIM, or both in addition to the authenticated domain aligning with the domain in the message *From: header address*.

**Goals:**

Ensure *o1labs.org* and *codaprotocol.com* DNS bindings are configured with the following: 
* [x] [SPF]( https://support.google.com/a/answer/33786?hl=en&ref_topic=7556597) TXT records
* [x] [DKIM](https://support.google.com/a/answer/174124?hl=en&ref_topic=7564555&visit_id=637248466829436640-1020806530&rd=1) TXT records
* [ ] [DMARC](https://support.google.com/a/answer/2466580) TXT records

**Comment by 0x0I** [comment]
**Mail Provider:**
- G-Suite

**DNS host providers:**
- o1labs.org: [Namecheap](https://www.namecheap.com/)
- codaprotocol.com: [Netlify](https://app.netlify.com/sites/o1website2/overview)

**Comment by 0x0I** [comment]
Hey @o1brad: appears as though I'll require *admin* privileges in order to generate the pub/priv key-pair for DKIM configuration+

```
Generate the domain key for outgoing email
You must be signed in as a super administrator for this task.

Your current account, ahmad@o1labs.org, doesn't have permission to perform these steps. To continue, switch to a super administrator account. This will open the Google Admin console.

Switch to super administrator account or Learn more.
.
.
.
```

**Comment by 0x0I** [comment]
@o1brad @bkase @yourbuddyconner Seems as though both Domains were previously setup with SPF configs -- maybe some details about that setup would be appreciated...

**Comment by emberian** [comment]
@0x0I do you already have a DMARC policy in mind? who will be receiving the reports?

**Comment by yourbuddyconner** [comment]
@emberian I would imagine we'd set up a security@o1labs.org address and receive them there if the generic contact@ email is insufficient.

**Comment by 0x0I** [comment]
Hey @emberian: I do for the most part though figured a discussion makes sense (in some channel) to source ideas and synchronize on a plan going forward.

Meant to link to support documentation which provides a recommended plan (e.g. including gradual deploys, limiting initial policy set, etc).

**Comment by 0x0I** [comment]
**Updates:**
- [SPF TXT record](https://discord.com/channels/@me/710968384656900109/713787200092766208) has been added for **o1labs.org** (via Namecheap)
- [DKIM TXT record](https://discord.com/channels/@me/710968384656900109/713787200092766208) added for **o1labs.org** domain (via Namecheap)
- DKIM TXT record NOT added for **codaprotocol.com** domain (not believed to receive mail traffic)

**Comment by 0x0I** [comment]
**Next Steps:**
1. @o1brad + Ahmad to follow-up w/ [enabling DKIM signing](https://support.google.com/a/answer/180504?hl=en&ref_topic=2752442) for o1labs.org GSuite mail traffic (via GSuite admin console)
2. validation steps **[6-9]** (from signing support doc) to be performed by @o1brad + Ahmad following signing with messaging to org **re:** success of activation
3. work with *operations/infra* to create a *mailto* email address to serve as a **Reporting URI(s) for aggregate data (rua)** -- necessary for DMARC setup.
4. Discuss and sync on DMARC policy with *operations/infra - policy notes:*
    - (v)DMARC protocol version is **required** (must == *DMARC1*)
    - (p)suspicious message policy handler is **required** (may make sense to start with *none/log*)
    - (sp) policy handler for subdomains (seems like it should currently match *p*)
    - (pct)percentage of suspicious messge above (p)olicy applies to (100% seems reasonable...)
    - (rua) violations reporting address (set to product of **step #3**)
    - remaining defaults appear reasonable

**Comment by 0x0I** [comment]
**Example DMARC TXT Record for o1labs.org:**

Name: dmarc.o1labs.org
Value:v=DMARC1; *p=none*; rua=mailto:security-reports@o1labs.org; pct=100; sp=none

**Comment by 0x0I** [comment]
DKIM TXT record for *o1labs.orgs*:

```
$ dig google._domainkey.o1labs.org TXT

; <<>> DiG 9.11.18-RedHat-9.11.18-1.fc32 <<>> google._domainkey.o1labs.org TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4265
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google._domainkey.o1labs.org.  IN      TXT

;; ANSWER SECTION:
google._domainkey.o1labs.org. 1799 IN   TXT     "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhjEaLC6UEoDoJEzNc5jCCco6rxzpOlx7M8ru1+KGvSvCT1GL+zCT1rcmSqJvyWlbNcMAG+J+IcTJCH+S05EiZIfdgt2fDFveoLJJYhTNuOhsL+x5sWcKI4VmcLkklGvaZzpCew1nuhJLwMOpzgdZTUeROViXNPiNRJagbsTyXCm+dv4+yGunBTiw4Lu9wmodJ" "1bzFhAeSYKjfN3XyRzYD9NjL1oPOgZPvWPMzoXoVnr5uJON0xyNHVrzT6xGX8yJ4oPYxpdaG2sjlera8rifQydikrMS5piZEN3DUDziRucSKOBscAjvYQ+uz6WiabLYoI062e7tkS0rhtYFncVa1QIDAQAB"

;; Query time: 81 msec
;; SERVER: 192.168.1.254#53(192.168.1.254)
;; WHEN: Tue Jun 02 18:18:19 EDT 2020
;; MSG SIZE  rcvd: 481```

**Comment by 0x0I** [comment]
@o1brad @bkase  blocked due to upcoming changes?

**Comment by o1brad** [comment]
DKIM and SPF are enabled. I don't think we need to prioritize enabling DMARC.
