### ISSUE TITLE
GraphQL: totalCurrency doesn't increase

### ISSUE THREAD

**Issue by Schmavery** [MinaProtocol/mina#4913]
Breaking this out into its own issue from https://github.com/CodaProtocol/coda/issues/4825 

> I also notice that the GraphQL response for totalCurrency is always 66000000001000 despite 1800+ blocks and I'd expect that to be increasing? -- @garethtdavies 

This was also reported by other community members. I was able to repro fairly easily in the sandbox node and attempted to track down what's going on, but no luck yet.

After a few blocks are mined in the sandbox node, the totalCurrency remains 66000000001000 even though the account that receives the coinbases has a balance of 67400000000000. So the totalCurrency should be increasing but isn't.  It also seems somewhat strange that the totalCurrency is 1000 more than the starting balance of 66000000000000.

**Comment by garethtdavies** [comment]
Presumably that 1000 extra is from the account `4vsRCVw9P7XQFJWS4FsAsiXRSJyEKiVLCnVw2mRreE7iWout75RvZnm9q46sed2GvBF9Rh972AJrnuhrpPfCDGyhgsJm6kxZGhP5x9CTdty4cpFA8FmxNL8gB2UPTweGnQ1svjTVgUAbb8qB` which is present on the sandbox node and has a balance of 1000.

**Comment by aneesharaines** [comment]
@MartinMinkov  to verify this only happens in sandbox
