### ISSUE TITLE
Ensure Telemetry script is included in the deployment

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#4950]
Follow up from #4587 - need to make sure this in is included in network deploys.

**Comment by aneesharaines** [comment]
So that we can tell if our users are forked

**Comment by aneesharaines** [comment]
Need to have a larger discussion with the infra SMEs

**Comment by yourbuddyconner** [comment]
Utility of this: 
- We can use an on-chain mechanism to figure out if all nodes (not just the ones we control) are forked

Form: 
- This will likely be formatted as a Kubernetes Job that is scheduled to run on a periodic schedule
