### ISSUE TITLE
Coda daemon fails to exit after libp2p_helper died

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#4981]
Deepthi brought up a new testnet on 5/29 called bugspray. In this new testnet, we saw on several nodes that the libp2p_helper died and it didn't bring the node itself down.

I am suspecting that this behavior is caused by a bug in `Coda_commands.get_status` function.

`Coda_run.handle_shutdown` is responsible for killing the node once for various reasons. It would in turn call `Coda_run.handle_crash` for reporting the crash log and the daemon status before crashing.

Here's the `Coda_run.handle_crash` is defined:
```
let handle_crash e ~time_controller ~conf_dir ~top_logger coda_ref =
  let exn_str = Exn.to_string e in
  Logger.fatal top_logger ~module_:__MODULE__ ~location:__LOC__
    "Unhandled top-level exception: $exn\nGenerating crash report"
    ~metadata:[("exn", `String exn_str)] ;
  let%bind status = coda_status !coda_ref in
  (* TEMP MAKE REPORT TRACE *)
  Logger.trace top_logger ~module_:__MODULE__ ~location:__LOC__
    "handle_crash: acquired coda status" ;
...
```

If everything is successful, we would first saw the "Unhandled top-level exception" log and then the"handle_crash" log. But I didn't the "handle_crash" one, that leads me to believe that `coda_status` never returns and this blocks the dying of the node forever.

**Comment by ghost-not-in-the-shell** [comment]
A quick fix would be just remove the status part from the report.

**Comment by imeckler** [comment]
I think we can for now let users know they should restart and get this in for next release

**Comment by aneesharaines** [comment]
@emberian is working on the fix for this
