### ISSUE TITLE
Transition frontier debug assert failure -- local state desynced

### ISSUE THREAD

**Issue by Igor-Tselkovskiy** [MinaProtocol/mina#5059]
Edit by @yourbuddyconner: 

Related to this crash: 
```
(monitor.ml.Error\n  (Failure \"local state desynced after applying diffs to full frontier\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/lib/debug_assert/debug_assert.ml\\\" (inlined), line 1, characters 25-33\"\n    \"Called from file \\\"src/lib/transition_frontier/full_frontier/full_frontier.ml\\\", line 606, characters 4-1023\"\n    \"Called from file \\\"src/lib/transition_frontier/transition_frontier.ml\\\", line 292, characters 4-93\"\n    \"Called from file \\\"src/lib/transition_handler/processor.ml\\\", line 57, characters 10-68\"\n    \"Called from file \\\"src/lib/rose_tree/rose_tree.ml\\\", line 79, characters 18-24\"\n    \"Called from file \\\"src/deferred_or_error.ml\\\", line 101, characters 23-33\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))
```

[coda_crash_report_2020-06-10_00-40-20.819931.tar.gz](https://github.com/CodaProtocol/coda/files/4755559/coda_crash_report_2020-06-10_00-40-20.819931.tar.gz)

**Comment by Cris-F** [comment]
Crashed a few minutes after start with ```
2020-06-10 01:27:26 UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
```
[coda_crash_report_2020-06-10_01-33-18.973349.tar.gz](https://github.com/CodaProtocol/coda/files/4755679/coda_crash_report_2020-06-10_01-33-18.973349.tar.gz)

**Comment by garethtdavies** [comment]
```
2020-06-10 01:18:55 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error\n  (Failure \"local state desynced after applying diffs to full frontier\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/lib/debug_assert/debug_assert.ml\\\" (inlined), line 1, characters 25-33\"\n    \"Called from file \\\"src/lib/transition_frontier/full_frontier/full_frontier.ml\\\", line 606, characters 4-1023\"\n    \"Called from file \\\"src/lib/transition_frontier/transition_frontier.ml\\\", line 292, characters 4-93\"\n    \"Called from file \\\"src/lib/transition_handler/processor.ml\\\", line 57, characters 10-68\"\n    \"Called from file \\\"src/lib/rose_tree/rose_tree.ml\\\", line 79, characters 18-24\"\n    \"Called from file \\\"src/deferred_or_error.ml\\\", line 101, characters 23-33\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"
2020-06-10 01:18:55 UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
```

**Comment by Cris-F** [comment]
`2020-06-10 01:43:56 UTC [Error] Unconsumed item in cache: $cache`
[coda_crash_report_2020-06-10_01-43-55.125789.tar.gz](https://github.com/CodaProtocol/coda/files/4755730/coda_crash_report_2020-06-10_01-43-55.125789.tar.gz)

**Comment by billyharvey** [comment]
[coda_crash_report_2020-06-10_01-35-53.525361.tar.gz](https://github.com/CodaProtocol/coda/files/4755733/coda_crash_report_2020-06-10_01-35-53.525361.tar.gz)

**Comment by Igor-Tselkovskiy** [comment]
2020-06-10 01:49:36 UTC [Info] Coda daemon is now doing ledger catchup
2020-06-10 01:49:36 UTC [Info] Sending transition_chain_proof to peer with IP 204.48.21.124
2020-06-10 01:50:06 UTC [Info] failed to reset stream (this means it was probably closed successfully): $error
	error: "RPC #83 failed: \"internal RPC error error: unknown stream_idx\""
2020-06-10 01:51:13 UTC [Fatal] after lock transition, the best tip consensus state is out of sync with the local state -- bug in either required_local_state_sync or frontier_root_transition.
2020-06-10 01:51:13 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: "(monitor.ml.Error\n  (Failure \"local state desynced after applying diffs to full frontier\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/lib/debug_assert/debug_assert.ml\\\" (inlined), line 1, characters 25-33\"\n    \"Called from file \\\"src/lib/transition_frontier/full_frontier/full_frontier.ml\\\", line 606, characters 4-1023\"\n    \"Called from file \\\"src/lib/transition_frontier/transition_frontier.ml\\\", line 292, characters 4-93\"\n    \"Called from file \\\"src/lib/transition_handler/processor.ml\\\", line 57, characters 10-68\"\n    \"Called from file \\\"src/lib/rose_tree/rose_tree.ml\\\", line 79, characters 18-24\"\n    \"Called from file \\\"src/deferred_or_error.ml\\\", line 101, characters 23-33\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"
2020-06-10 01:51:14 UTC [Error] Unconsumed item in cache: $cache
	cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
2020-06-10 01:51:14 UTC [Error] Unconsumed item in cache: $cache
	cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
2020-06-10 01:51:14 UTC [Error] Unconsumed item in cache: $cache
	cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
2020-06-10 01:51:14 UTC [Error] Unconsumed item in cache: $cache
	cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
[coda_crash_report_2020-06-10_01-51-14.647416.tar.gz](https://github.com/CodaProtocol/coda/files/4755750/coda_crash_report_2020-06-10_01-51-14.647416.tar.gz)

**Comment by Cris-F** [comment]
[coda_crash_report_2020-06-10_01-55-08.816213.tar.gz](https://github.com/CodaProtocol/coda/files/4755753/coda_crash_report_2020-06-10_01-55-08.816213.tar.gz)

**Comment by Cris-F** [comment]
[coda_crash_report_2020-06-10_02-08-09.780844.tar.gz](https://github.com/CodaProtocol/coda/files/4755797/coda_crash_report_2020-06-10_02-08-09.780844.tar.gz)

**Comment by nat8552** [comment]
Same issue with Unconsumed item in cache:

[coda_crash_report_2020-06-10_01-45-54.705615.tar.gz](https://github.com/CodaProtocol/coda/files/4755796/coda_crash_report_2020-06-10_01-45-54.705615.tar.gz)

**Comment by pkrasam** [comment]
2020-06-10 02:05:16 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: "(monitor.ml.Error\n  (Failure \"local state desynced after applying diffs to full frontier\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/lib/debug_assert/debug_assert.ml\\\" (inlined), line 1, characters 25-33\"\n    \"Called from file \\\"src/lib/transition_frontier/full_frontier/full_frontier.ml\\\", line 606, characters 4-1023\"\n    \"Called from file \\\"src/lib/transition_frontier/transition_frontier.ml\\\", line 292, characters 4-93\"\n    \"Called from file \\\"src/lib/transition_handler/processor.ml\\\", line 57, characters 10-68\"\n    \"Called from file \\\"src/lib/rose_tree/rose_tree.ml\\\", line 79, characters 18-24\"\n    \"Called from file \\\"src/deferred_or_error.ml\\\", line 101, characters 23-33\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"
2020-06-10 02:05:16 UTC [Error] Unconsumed item in cache: $cache
	cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"

**Comment by Igor-Tselkovskiy** [comment]
Again on stage Catchup 
2020-06-10 02:18:38 UTC [Info] Coda daemon is now doing ledger catchup
2020-06-10 02:19:13 UTC [Fatal] after lock transition, the best tip consensus state is out of sync with the local state -- bug in either required_local_state_sync or frontier_root_transition.
2020-06-10 02:19:13 UTC [Fatal] Unhandled top-level exception: $exn
[coda_crash_report_2020-06-10_02-19-14.177339.tar.gz](https://github.com/CodaProtocol/coda/files/4755841/coda_crash_report_2020-06-10_02-19-14.177339.tar.gz)

**Comment by jjangg96** [comment]
same

**Comment by aquariusluo** [comment]
Related to this crash:
UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = 
[coda_crash_report_2020-06-10_02-23-18.455018.tar.gz](https://github.com/CodaProtocol/coda/files/4755896/coda_crash_report_2020-06-10_02-23-18.455018.tar.gz)
\"Transition_handler__Unprocessed_transition_cache\")"

**Comment by Cris-F** [comment]
[coda_crash_report_2020-06-10_02-40-30.246996.tar.gz](https://github.com/CodaProtocol/coda/files/4755900/coda_crash_report_2020-06-10_02-40-30.246996.tar.gz)

**Comment by crackerli** [comment]
Same issue, this happened to a lot of member
Even the error log is the same

**Comment by NAKsir-melody** [comment]
.coda_config1, .coda_config2
too big to upload directly.

refer below.
https://drive.google.com/file/d/13SeWGqihQT43Y_Qfdvj5tLiCV1qFGfoL/view?usp=sharing

**Comment by rhvall** [comment]
Had the same problem:
[coda_crash_report_2020-06-10_03-10-03.546959.zip](https://github.com/CodaProtocol/coda/files/4756057/coda_crash_report_2020-06-10_03-10-03.546959.zip)

- inv0ke -

**Comment by StarLI-Trapdoor** [comment]
I think the crash is related with "root" account on Ubuntu. 

With root account, the following warning shows up when installing: 

syncing data to disk ... ok

Success. You can now start the database server using:

    /usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/10/main -l logfile start

Ver Cluster Port Status Owner    Data directory              Log file
10  main    5432 down   postgres /var/lib/postgresql/10/main /var/log/postgresql/postgresql-10-main.log
update-alternatives: using /usr/share/postgresql/10/man/man1/postmaster.1.gz to provide /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) in auto mode
Setting up postgresql (10+190ubuntu0.1) ...
Setting up coda-testnet-postake-medium-curves (0.0.12-beta+406048-feature-bump-genesis-timestamp-3e9b174-PV48525e92) ...
Processing triggers for systemd (237-3ubuntu10.38) ...
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...

**Comment by StarLI-Trapdoor** [comment]
If switching to normal user, the node can be started smoothly :)

**Comment by garethtdavies** [comment]
This issue just popped up again and can be reliably reproduced by different testnet participants when attempting to sync a new node https://discordapp.com/channels/484437221055922177/583400552487059546/720773819437940758

**Comment by nholland94** [comment]
I scanned through the log and extracted the transition frontier visualization at the point that the local state sync invariant broke (after applying the diffs that broke it). The visualization doesn't make sense. Seems to indicate to me that, either, the frontier is very malformed, or the visualization code is really messed up. Visualization code hasn't been touched in a while, so it's worth spot checking it, but it should be pretty straight forward. Not sure how the frontier could ever look like this.
![graph](https://user-images.githubusercontent.com/5352803/84540683-c81d4280-acaa-11ea-9749-d12233df7a28.png)

**Comment by nholland94** [comment]
> Crashed a few minutes after start with ` 2020-06-10 01:27:26 UTC [Error] Unconsumed item in cache: $cache cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"`
> [coda_crash_report_2020-06-10_01-33-18.973349.tar.gz](https://github.com/CodaProtocol/coda/files/4755679/coda_crash_report_2020-06-10_01-33-18.973349.tar.gz)

The unconsumed item in cache errors are non-fatal, and they actually are triggered by the root cause of this issue, the required_local_state_sync assertion failing. These errors often trigger on a graceful crash since they are essential just saying "you didn't finish using this object yet", which is true since we are crashing.

**Comment by nholland94** [comment]
> If switching to normal user, the node can be started smoothly :)

I believe this problem is temporal in nature. By that, I mean, this bug can trigger depending on *when* you join the network. If that's the case, it may have started working for you due to time passing, and not by switching users. If you see this bug again, please let me know. In the meantime, we will continue investigating.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
