### ISSUE TITLE
Trying to connect to private IP addresses

### ISSUE THREAD

**Issue by koen84** [MinaProtocol/mina#5060]
From .coda-config/coda.log :

{"timestamp":"2020-06-10 00:38:34.603187Z","level":"Spam","message":"Output from process $child_name: $line","metadata":{"child_name":"libp2p_helper-stderr","handle":"stderr","line":"{\"id\":1045,\"level\":2,\"message\":\"couldn't connect to dht peer map[addrs:[/ip4/64.227.111.170/tcp/8302 /ip4/64.227.111.170/tcp/8302 /ip4/127.0.0.1/tcp/8302 /ip4/10.48.0.6/tcp/8302] peerID:12D3KooWBoUzBKdvJ4Nx8hyRQTFeTuouEa7P24H652YXJR4P8xGx] (maybe the network ID mismatched?): failed to dial : all dials failed\\n  * [/ip4/64.227.111.170/tcp/8302] failed to negotiate security protocol: connected to wrong peer\\n  * [/ip4/64.227.111.170/tcp/8302] failed to negotiate security protocol: connected to wrong peer\\n  * [/ip4/10.48.0.6/tcp/8302] dial tcp4 0.0.0.0:8302-\\u003e10.48.0.6:8302: i/o timeout\",\"module\":\"codanet.Helper\",\"time\":\"2020-06-10T02:38:29.361426487+02:00\"}","pid":12753,"process":"libp2p_helper"}}
{"timestamp":"2020-06-10 00:38:34.603251Z","level":"Spam","message":"Output from process $child_name: $line","metadata":{"child_name":"libp2p_helper-stderr","handle":"stderr","line":"{\"id\":1046,\"level\":4,\"message\":\"error reading rpc from 12D3KooWBFkd5LeJdoKs7aV2yRBBSXaSN6hqZByCQCo2oyPucuVi: stream reset\",\"module\":\"pubsub\",\"time\":\"2020-06-10T02:38:32.47751189+02:00\"}","pid":12753,"process":"libp2p_helper"}}
{"timestamp":"2020-06-10 00:38:34.603319Z","level":"Spam","message":"sending line to libp2p_helper: $line","metadata":{"host":"62.171.165.157","line":"{\"seqno\":378,\"method\":\"listPeers\",\"body\":{}}","peer_id":"12D3KooWPpStBnkyf6trfGuQYc7YDEMMuJk6G6d7M3ACfjbUEy2e","pid":12753,"port":8302}}
{"timestamp":"2020-06-10 00:38:34.603372Z","level":"Spam","message":"Output from process $child_name: $line","metadata":{"child_name":"libp2p_helper-stderr","handle":"stderr","line":"{\"id\":1047,\"level\":4,\"message\":\"got error on dial: dial tcp4 0.0.0.0:8302-\\u003e10.128.0.2:8302: i/o timeout\",\"module\":\"swarm2\",\"time\":\"2020-06-10T02:38:34.369179794+02:00\"}","pid":12753,"process":"libp2p_helper"}}

The 10.0.0.0/8 address range is marked privated (i.e. used in LAN).

**WARNING : some hosting providers might flag this as abussive behaviour, a programme trying to compromise their internal network.**

**Comment by yourbuddyconner** [comment]
Interesting, this looks like the Libp2p peer discovery behavior, @emberian any thoughts about this?

**Comment by aneesharaines** [comment]
Believe this is libp2p always checking on local first to give preference to local peers but need to double check with @emberian

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
