### ISSUE TITLE
Coda crash after reboot the server

### ISSUE THREAD

**Issue by icohigh** [MinaProtocol/mina#5061]
After restarting the server and restarting the code, it crashes. Ports are open.
[coda_crash_report_2020-06-10_00-47-07.491198.tar.gz](https://github.com/CodaProtocol/coda/files/4755575/coda_crash_report_2020-06-10_00-47-07.491198.tar.gz)

Then I created a new server and set it all up again. After the first run I got a crash again! 
[coda_crash_report_2020-06-10_00-53-44.345464.tar.gz](https://github.com/CodaProtocol/coda/files/4755596/coda_crash_report_2020-06-10_00-53-44.345464.tar.gz)

My Discord - Ducca#5707

**Comment by aneesharaines** [comment]
`{"timestamp":"2020-06-10 00:47:04.992841Z","level":"Fatal","source":{"module":"Init__Coda_run","location":"File \"src/app/cli/src/init/coda_run.ml\", line 621, characters 56-63"},"message":"Unhandled top-level exception: $exn\nGenerating crash report","metadata":{"exn":"(monitor.ml.Error\n  (Failure\n    \"traced task `R&check next block timing` failed, exception reported to parent monitor\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\")`

**Comment by aneesharaines** [comment]
Second crash covered by #5059

**Comment by aneesharaines** [comment]
Thanks for reporting @icohigh !

**Comment by aneesharaines** [comment]
Looks like this happened 30+ times in 3.2b.  

Also in #4480 and #4934 .

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
