### ISSUE TITLE
Account import / list mismatch

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#5066]
Accounts created by manually sticking files into `wallets/store` do not show up via `accounts list`. Moreover, `accounts import` will fail saying the account already exists. This is very frustrating and confusing.

Perhaps we should add an `accounts refresh` to re-poll the filesystem?

**Comment by mtwebb** [comment]
Yep.  I hit this and took a couple minutes of head scratching to sort out.

**Comment by Schmavery** [comment]
why not import the account normally?

**Comment by jkrauska** [comment]
I had this when using a non-standard config-dir.

Somewhere in the wallet work, you are using the stock config dir (.coda-config/wallets/store/) and ignoring  runtime overrides.

Import put files in stock, but not where I needed them.

👋

**Comment by Schmavery** [comment]
Hmm, we should support a custom config dir in the import command but maybe something is going wrong.

https://github.com/CodaProtocol/coda/blob/f018b247a7e7b9be25512282567363f12deacb65/src/app/cli/src/init/client.ml#L922
