### ISSUE TITLE
Node crashed with Rocks__Rocks_common.OperationOnInvalidObject

### ISSUE THREAD

**Issue by sl-he** [MinaProtocol/mina#5069]
Jun 10 11:25:37 systemd[1]: coda.service: Failed with result 'exit-code'.
Jun 10 11:25:42 systemd[1]: coda.service: Service hold-off time over, scheduling restart.
Jun 10 11:25:42 systemd[1]: coda.service: Scheduled restart job, restart counter is at 38.
Jun 10 11:25:42 systemd[1]: Stopped Coda Daemon Service.
Jun 10 11:25:42 systemd[1]: Started Coda Daemon Service.
Jun 10 11:25:43 coda[6869]: 2020-06-10 11:25:43 UTC [Info] Coda daemon is booting up; built with commit "3e9b1748183e653a7891adea1fef07c8e1a7dfcd" on branch "feature/bump-genesis-timestamp"
Jun 10 11:25:43 coda[6869]: 2020-06-10 11:25:43 UTC [Info] Daemon will expire at "2024-12-10 14:00:00-07:00"
Jun 10 11:25:43 coda[6869]: 2020-06-10 11:25:43 UTC [Info] Booting may take several seconds, please wait
Jun 10 11:25:43 coda[6869]: 2020-06-10 11:25:43 UTC [Info] Looking for the genesis tar file "coda_genesis_3e9b1748_5e70c20db27df299.tar.gz"
Jun 10 11:25:44 coda[6869]: 2020-06-10 11:25:44 UTC [Info] Successfully retrieved genesis ledger and genesis proof from "/tmp/coda_cache_dir"
Jun 10 11:26:45 coda[6869]: 2020-06-10 11:26:45 UTC [Info] Initializing with genesis constants $genesis_constants
Jun 10 11:26:45 coda[6869]:         genesis_constants: {
Jun 10 11:26:45 coda[6869]:   "protocol": {
Jun 10 11:26:45 coda[6869]:     "k": 20,
Jun 10 11:26:45 coda[6869]:     "delta": 3,
Jun 10 11:26:45 coda[6869]:     "genesis_state_timestamp": "2020-06-08 19:30:00.000000Z"
Jun 10 11:26:45 coda[6869]:   },
Jun 10 11:26:45 coda[6869]:   "txpool_max_size": 3000,
Jun 10 11:26:45 coda[6869]:   "num_accounts": 10000
Jun 10 11:26:45 coda[6869]: }
Jun 10 11:29:14 coda[6869]: 2020-06-10 11:29:14 UTC [Info] Setting current protocol version to "0.1.0" from compile-time config
Jun 10 11:29:15 coda[6869]: 2020-06-10 11:29:15 UTC [Info] Daemon started process of kind "Prover" with pid 9857
Jun 10 11:29:18 coda[6869]: 2020-06-10 11:29:18 UTC [Info] Daemon started process of kind "Verifier" with pid 9873
Jun 10 11:29:18 coda[6869]: 2020-06-10 11:29:18 UTC [Info] Registering async shutdown handler: "Close transition frontier, if exists"
Jun 10 11:29:19 coda[6869]: 2020-06-10 11:29:19 UTC [Info] libp2p peer ID this session is $peer_id
Jun 10 11:29:19 coda[6869]:         peer_id: "12D3KooWPzjzsVWNHJ758jCRx7VsvL631kTYsxsojoP8KaA1yofC"
Jun 10 11:29:32 coda[6869]: 2020-06-10 11:29:32 UTC [Info] Coda daemon is now connecting
Jun 10 11:29:32 coda[6869]: 2020-06-10 11:29:32 UTC [Info] Pausing block production while bootstrapping
Jun 10 11:29:32 coda[6869]: 2020-06-10 11:29:32 UTC [Info] Attempted to turn on snark worker, but snark worker key is set to none
Jun 10 11:29:32 coda[6869]: 2020-06-10 11:29:32 UTC [Info] Daemon ready. Clients can now connect
Jun 10 11:29:32 coda[6869]: 2020-06-10 11:29:32 UTC [Info] Created GraphQL server at: http://localhost:3085/graphql
Jun 10 11:30:16 coda[6869]: 2020-06-10 11:30:16 UTC [Info] Coda daemon is now connecting
Jun 10 11:30:16 coda[6869]: 2020-06-10 11:30:16 UTC [Info] Coda daemon is now bootstrapping
Jun 10 11:30:32 coda[6869]: 2020-06-10 11:30:32 UTC [Info] Will start initialization without connecting with too many peers
Jun 10 11:30:32 coda[6869]: 2020-06-10 11:30:32 UTC [Fatal] Unhandled top-level exception: $exn
Jun 10 11:30:32 coda[6869]: Generating crash report
Jun 10 11:30:32 coda[6869]:         exn: "(monitor.ml.Error\n  (Failure\n    \"failed to initialize transition frontier: Staged_ledger.of_scan_state_and_ledger : did not connect with snarked ledger hash\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"
Jun 10 11:30:32 coda[6869]: 2020-06-10 11:30:32 UTC [Info] Requesting peers for their best tip to do initialization
Jun 10 11:30:35 coda[6869]: 2020-06-10 11:30:35 UTC [Fatal] Exception when generating crash report: "(Rocks__Rocks_common.OperationOnInvalidObject)"
Jun 10 11:30:35 coda[6869]:   ?  Coda Daemon crashed.
Jun 10 11:30:35 coda[6869]:    The Coda Protocol developers would like to know why!
Jun 10 11:30:35 coda[6869]:     Please:
Jun 10 11:30:35 coda[6869]:       Open an issue:
Jun 10 11:30:35 coda[6869]:         <https://github.com/CodaProtocol/coda/issues/new>
Jun 10 11:30:35 coda[6869]:       Briefly describe what you were doing and include the last 20 lines from .coda-config/coda.log and then paste the following:
Jun 10 11:30:35 coda[6869]: Summary:
Jun 10 11:30:35 coda[6869]: {"num_accounts":null,"blockchain_length":null,"highest_block_length_received":1,"uptime_secs":288,"ledger_merkle_root":null,"state_hash":null,"commit_id":"3e9b1748183e653a7891adea1fef07c8e1a7dfcd","conf_dir":"/home/user/.coda-config","peers":["213.183.48.193:8302","142.44.139.163:8302","64.227.111.170:8302","95.216.152.25:8302","82.202.253.69:8302","34.107.51.14:8302","159.89.127.140:8302","18.223.15.17:8302","142.93.32.97:8302","116.202.216.248:8302","64.225.126.99:8302","104.248.126.224:8302","159.89.155.126:8302","35.204.13.108:8302","95.217.204.49:8302","35.246.224.149:8302","3.94.116.250:8302","213.211.79.68:8302","46.232.251.94:8302","62.171.139.53:8302","3.17.37.61:8302","51.15.246.57:8302","122.115.61.107:8302","178.140.11.249:8302","50.116.46.176:8302","3.13.202.98:8302","95.111.251.106:8302","165.22.73.222:8302","140.238.210.230:8302","159.89.84.150:8302","95.217.203.62:8302","35.196.202.161:10004","164.68.116.122:8302","35.197.96.64:8302","35.203.179.141:8302","52.186.151.174:8302","139.162.132.135:8302","161.35.121.212:8302","167.172.203.143:8302","161.97.66.151:8302","173.249.38.94:8302","78.193.188.67:20780","94.16.116.35:8302","144.91.127.224:8302","47.157.157.224:8302","95.217.160.158:8302","207.180.202.86:8302","62.171.148.56:8302","162.245.23.134:48590","62.171.131.108:8302","82.69.152.196:8302","165.227.27.76:8302","34.74.183.100:10001","146.0.138.136:8302","208.123.119.115:8302","161.35.93.158:8302","213.211.79.68:7310","64.225.107.37:8302","178.132.207.35:8302","142.93.149.94:8302","167.99.111.179:8302","18.222.186.77:8302","68.183.134.20:8302","34.74.30.44:8302","194.19.235.83:8302","62.171.139.152:8302","193.30.121.61:8302","144.91.97.85:8302","62.171.140.121:8302","95.216.192.84:8302","34.91.73.182:8302","167.99.85.10:8302","109.234.159.18:8302","40.69.86.64:8302","34.82.5.66:8302","35.196.202.161:10005","193.30.123.172:8302","3.21.166.159:8302","35.196.202.161:10002","24.5.137.84:8302","35.196.202.161:10400","142.93.62.181:8302","144.91.127.223:8302","204.48.21.124:8302","35.231.128.243:10001","35.239.173.164:8302","35.185.73.134:10003","23.16.197.222:40509","95.217.197.115:8302","85.112.96.18:8302","64.227.104.218:8302","35.196.202.161:10001"],"user_commands_sent":0,"snark_worker":null,"snark_work_fee":25000000,"sync_status":"Bootstrap","block_production_keys":[],"histograms":{"rpc_timings":{"get_staged_ledger_aux":{"dispatch":null,"impl":null},"answer_sync_ledger_query":{"dispatch":null,"impl":null},"get_ancestry":{"dispatch":null,"impl":null},"get_transition_chain_proof":{"dispatch":null,"impl":null},"get_transition_chain":{"dispatch":null,"impl":null}},"external_transition_latency":null,"accepted_transition_local_latency":null,"accepted_transition_remote_latency":null,"snark_worker_transition_time":null,"snark_worker_merge_time":null},"consensus_time_best_tip":null,"next_block_production":null,"consensus_time_now":{"slot_number":"800","slots_per_epoch":"480"},"consensus_mechanism":"proof_of_stake","consensus_configuration":{"delta":3,"k":20,"c":8,"c_times_k":160,"slots_per_epoch":480,"slot_duration":180000,"epoch_duration":86400000,"genesis_state_timestamp":"1591644600000","acceptable_network_delay":540000},"addrs_and_ports":{"external_ip":"167.86.111.247","bind_ip":"0.0.0.0","peer":{"host":"0.0.0.0","libp2p_port":8302,"peer_id":"12D3KooWPzjzsVWNHJ758jCRx7VsvL631kTYsxsojoP8KaA1yofC"},"libp2p_port":8302,"client_port":8301}}
Jun 10 11:30:35 coda[6869]: Status:
Jun 10 11:30:35 coda[6869]: {"OS_type":"Unix","Release":"4.15.0-101-generic","Machine":"x86_64","Sys_name":"Linux","Exception":"(monitor.ml.Error\n  (Failure\n    \"failed to initialize transition frontier: Staged_ledger.of_scan_state_and_ledger : did not connect with snarked ledger hash\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))","Command":"Command: (/usr/local/bin/coda daemon -peer\n /ip4/34.74.183.100/tcp/10001/ipfs/12D3KooWAFFq2yEQFFzhU5dt64AWqawRuomG9hL8rSmm5vxhAsgr\n -peer\n /ip4/35.231.128.243/tcp/10001/ipfs/12D3KooWB79AmjiywL1kMGeKHizFNQE9naThM2ooHgwFcUzt6Yt1)","Coda_branch":"feature/bump-genesis-timestamp","Coda_commit":"3e9b1748183e653a7891adea1fef07c8e1a7dfcd"}
Jun 10 11:30:35 coda[6869]:
Jun 10 11:30:35 systemd[1]: coda.service: Main process exited, code=exited, status=1/FAILURE
Jun 10 11:30:35 systemd[1]: coda.service: Failed with result 'exit-code'.
Jun 10 11:30:40 systemd[1]: coda.service: Service hold-off time over, scheduling restart.
Jun 10 11:30:40 systemd[1]: coda.service: Scheduled restart job, restart counter is at 39.

**Comment by gnosed** [comment]
I have the same issue. What is your setting?

**Comment by gnosed** [comment]
The following steps solved the issue on my machine:
- clean up all the data related to coda (all binaries, all blocks)
- reinstall the package
