### ISSUE TITLE
required_local_state_sync failure during initial catchup

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#5079]
`required_local_state_sync` function is  assuming that the frontier is of full length. This might not be true at initial catchup phase. This would cause the node to crash if it tries to produce a block during the initial  catchup.

**Comment by bkase** [comment]
If you see `Assert_failure src/lib/block_producer/block_producer.ml:598:16` . This is the bug that it is duplicating
