### ISSUE TITLE
Fix the throughput of the snark coordinator

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5100]

**Comment by nholland94** [comment]
Easy optimizations we can do:

- add a flag to conditionally run the local snark worker with the coordinator (right now, a worker always runs on the same box; this wastes resources that the coordinator could be using to manage more remote workers)
- adjust the snark worker pull intervals to get work from the coordinator
- time the coordinator get work RPC call and adjust expensive parts

**Comment by pkrasam** [comment]
What is maximum number of threads a snark coordinator can accomodate atm?

**Comment by aneesharaines** [comment]
Haven't been able to retest for 3.3.  Will recheck once we have a stable QA net
