### ISSUE TITLE
telemetry command: Exception while handling RPC server request

### ISSUE THREAD

**Issue by utgarda** [MinaProtocol/mina#5107]
running
`coda advanced telemetry -daemon-peers`
hangs for a while before producing output and gives this in daemon logs:
```
2020-06-11 23:07:18 UTC [Error] Exception while handling RPC server request from "127.0.0.1": $error
        error: "(src/connection.ml.Handshake_error.Handshake_error(Eof <created-directly>))"
2020-06-11 23:08:36 UTC [Error] Exception while handling RPC server request from "127.0.0.1": $error
        error: "(src/connection.ml.Handshake_error.Handshake_error(Eof <created-directly>))"
2020-06-11 23:10:39 UTC [Error] RPC call error: "handshake error"
```

```
$ uname -a
Linux coda-testnet 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64 GNU/Linux
$ coda -version
Commit 3e9b174 on branch feature/bump-genesis-timestamp
```
maybe a coincidence, but first I spotted it while running telemetry.

**Comment by bkase** [comment]
This is due to the hanging of the process which cause rspc connections to hangup. Everything under `advanced` we treat as "unstable", so fixing this is low priority for now! Thanks for the report!

**Comment by psteckler** [comment]
Did you see anything similar for other client commands, like `client status`?

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
