### ISSUE TITLE
Unexpected crash in 3.2b

### ISSUE THREAD

**Issue by lyoungblood** [MinaProtocol/mina#5144]
The daemon was very stable for about a week, but it finally crashed with the following crash report:
```
2020-06-15 16:00:55 UTC [Info] failed to reset stream (this means it was probably closed successfully): $error
	error: "RPC #709468 failed: \"internal RPC error error: unknown stream_idx\""
2020-06-15 16:01:59 UTC [Info] failed to reset stream (this means it was probably closed successfully): $error
	error: "RPC #709687 failed: \"internal RPC error error: unknown stream_idx\""
2020-06-15 16:11:01 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: "(monitor.ml.Error\n  (\"writer buffer has data older than\" (maximum_age 2m)\n    (beginning_of_buffer\n       \"{\\\"seqno\\\":711124,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584095,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711125,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584096,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711126,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584097,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711127,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584098,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711128,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584099,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711129,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584100,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711130,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584101,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711131,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584102,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711132,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584103,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711133,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584104,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711134,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584105,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711135,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"s\")\n    (writer\n      ((id 14)\n        (fd\n          ((file_descr 55)\n            (info\n              (\"child process\"\n                (stdin (pid 28544) (prog coda-libp2p_helper) (args ()))\n                src/process.ml:62:17))\n            (kind Fifo) (supports_nonblock true) (have_set_nonblock true)\n            (state (Open Empty))\n            (watching ((read Not_watching) (write (Watch_once Empty))))\n            (watching_has_changed false) (num_active_syscalls 1)\n            (close_finished Empty)))\n        (monitor\n          (((name (id 248)) (here ()) (id 248) (has_seen_error false)\n             (is_detached false))\n            ((name \"\") (here ()) (id 228) (has_seen_error false)\n              (is_detached true))))\n        (inner_monitor\n          (((name (id 249)) (here ()) (id 249) (has_seen_error false)\n             (is_detached true))\n            ((name \"\") (here ()) (id 228) (has_seen_error false)\n              (is_detached true))))\n        (background_writer_state Running) (background_writer_stopped Empty)\n        (syscall Per_cycle) (bytes_received 672416539)\n        (bytes_written 672316817) (scheduled_bytes 264) (scheduled_back 264)\n        (back 99722) (close_state Open) (close_finished Empty)\n        (close_started Empty) (num_producers_to_flush_at_close 0)\n        (flush_at_shutdown_elt (<opaque>))\n        (check_buffer_age\n          (((writer <opaque>) (maximum_age 2m)\n             (bytes_received_at_now_minus_maximum_age 672317521)\n             (bytes_received_queue\n               (672317961 672318577 672318841 672318929 672319369 672319897\n                 672321683 672322827 672333189 672344003 672354085 672354525\n                 672355229 672355669 672356109 672358159 672358775 672359655\n                 672360095 672370817 672373395 672373747 672374451 672374715\n                 672375331 672376035 672378085 672379405 672379933 672380813\n                 672380989 672381253 672382863 672384007 672394277 672395157\n                 672395509 672396565 672406631 672407247 672410001 672410089\n                 672410617 672411145 672411761 672412201 672415131 672415219\n                 672416011 672416451 672416539))\n             (times_received_queue\n               ((2020-06-15 09:09:02.222426000-07:00)\n                 (2020-06-15 09:09:06.043597000-07:00)\n                 (2020-06-15 09:09:08.047991000-07:00)\n                 (2020-06-15 09:09:09.048483000-07:00)\n                 (2020-06-15 09:09:12.057494000-07:00)\n                 (2020-06-15 09:09:16.079104000-07:00)\n                 (2020-06-15 09:09:17.081425000-07:00)\n                 (2020-06-15 09:09:20.092527000-07:00)\n                 (2020-06-15 09:09:25.831544000-07:00)\n                 (2020-06-15 09:09:26.837571000-07:00)\n                 (2020-06-15 09:09:27.844615000-07:00)\n                 (2020-06-15 09:09:28.854799000-07:00)\n                 (2020-06-15 09:09:29.856786000-07:00)\n                 (2020-06-15 09:09:30.875843000-07:00)\n                 (2020-06-15 09:09:31.876259000-07:00)\n                 (2020-06-15 09:09:32.876660000-07:00)\n                 (2020-06-15 09:09:34.881631000-07:00)\n                 (2020-06-15 09:09:38.899038000-07:00)\n                 (2020-06-15 09:09:42.904821000-07:00)\n                 (2020-06-15 09:09:45.990195000-07:00)\n                 (2020-06-15 09:09:47.000096000-07:00)\n                 (2020-06-15 09:09:50.507250000-07:00)\n                 (2020-06-15 09:09:54.517261000-07:00)\n                 (2020-06-15 09:09:57.557865000-07:00)\n                 (2020-06-15 09:09:58.558850000-07:00)\n                 (2020-06-15 09:10:01.626516000-07:00)\n                 (2020-06-15 09:10:04.642490000-07:00)\n                 (2020-06-15 09:10:05.757633000-07:00)\n                 (2020-06-15 09:10:09.515714000-07:00)\n                 (2020-06-15 09:10:13.532847000-07:00)\n                 (2020-06-15 09:10:16.576910000-07:00)\n                 (2020-06-15 09:10:17.579646000-07:00)\n                 (2020-06-15 09:10:19.645320000-07:00)\n                 (2020-06-15 09:10:20.650648000-07:00)\n                 (2020-06-15 09:10:23.827351000-07:00)\n                 (2020-06-15 09:10:24.831569000-07:00)\n                 (2020-06-15 09:10:30.841109000-07:00)\n                 (2020-06-15 09:10:31.848250000-07:00)\n                 (2020-06-15 09:10:33.860126000-07:00)\n                 (2020-06-15 09:10:34.865542000-07:00)\n                 (2020-06-15 09:10:35.870771000-07:00)\n                 (2020-06-15 09:10:36.873692000-07:00)\n                 (2020-06-15 09:10:39.900398000-07:00)\n                 (2020-06-15 09:10:40.902828000-07:00)\n                 (2020-06-15 09:10:43.915067000-07:00)\n                 (2020-06-15 09:10:47.939906000-07:00)\n                 (2020-06-15 09:10:52.170006000-07:00)\n                 (2020-06-15 09:10:55.191436000-07:00)\n                 (2020-06-15 09:10:56.196771000-07:00)\n                 (2020-06-15 09:10:59.224958000-07:00)\n                 (2020-06-15 09:11:00.228352000-07:00)))\n             (bytes_seen 672416539) (too_old (Full ())))))\n        (consumer_left Empty) (raise_when_consumer_leaves true)\n        (open_flags (Full (Ok (wronly)))) (line_ending Unix))))\n  (\"Caught by monitor (id 248)\"))"
2020-06-15 16:11:44 UTC [Info] failed to reset stream (this means it was probably closed successfully): $error
	error: "RPC #711025 failed: \"internal RPC error error: unknown stream_idx\""
```

**Comment by lyoungblood** [comment]
Restarting produced this crash:
```
2020-06-16 16:16:40 UTC [Info] Setting current protocol version to "0.1.0" from compile-time config
2020-06-16 16:16:40 UTC [Info] Daemon started process of kind "Prover" with pid 31715
2020-06-16 16:16:41 UTC [Info] Daemon started process of kind "Verifier" with pid 31734
2020-06-16 16:16:41 UTC [Info] Registering async shutdown handler: "Close transition frontier, if exists"
2020-06-16 16:16:41 UTC [Info] libp2p peer ID this session is $peer_id
	peer_id: "12D3KooWDV2Ry7tUpG3vMHgb5hpFQzB2TcSttM6eWgmMHRoDyztx"
2020-06-16 16:16:42 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: "(monitor.ml.Error\n  (Failure\n    \"Failed to connect to libp2p_helper process: RPC #2 failed: \\\"initializing helper error: failed to read value pointer from vlog file: {Fid:42 Len:581 Offset:16049153}: Unable to find log file. Please retry\\\"\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"
```

**Comment by lyoungblood** [comment]
It seems like the first crash report file got erased when the new ones were created. Sorry I don't have the first crash report file, but here is another one.
[coda_crash_report_2020-06-16_16-18-31.949259.tar.gz](https://github.com/CodaProtocol/coda/files/4787794/coda_crash_report_2020-06-16_16-18-31.949259.tar.gz)

**Comment by jkrauska** [comment]
> The daemon was very stable for about a week, but it finally crashed with the following crash report:
> 
> ```
> 2020-06-15 16:00:55 UTC [Info] failed to reset stream (this means it was probably closed successfully): $error
> 	error: "RPC #709468 failed: \"internal RPC error error: unknown stream_idx\""
> 2020-06-15 16:01:59 UTC [Info] failed to reset stream (this means it was probably closed successfully): $error
> 	error: "RPC #709687 failed: \"internal RPC error error: unknown stream_idx\""
> 2020-06-15 16:11:01 UTC [Fatal] Unhandled top-level exception: $exn
> Generating crash report
> 	exn: "(monitor.ml.Error\n  (\"writer buffer has data older than\" (maximum_age 2m)\n    (beginning_of_buffer\n       \"{\\\"seqno\\\":711124,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584095,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711125,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584096,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711126,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584097,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711127,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584098,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711128,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584099,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711129,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584100,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711130,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584101,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711131,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584102,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711132,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584103,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711133,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584104,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711134,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"seqno\\\":584105,\\\"is_valid\\\":false}}\\\n      \\n{\\\"seqno\\\":711135,\\\"method\\\":\\\"validationComplete\\\",\\\"body\\\":{\\\"s\")\n    (writer\n      ((id 14)\n        (fd\n          ((file_descr 55)\n            (info\n              (\"child process\"\n                (stdin (pid 28544) (prog coda-libp2p_helper) (args ()))\n                src/process.ml:62:17))\n            (kind Fifo) (supports_nonblock true) (have_set_nonblock true)\n            (state (Open Empty))\n            (watching ((read Not_watching) (write (Watch_once Empty))))\n            (watching_has_changed false) (num_active_syscalls 1)\n            (close_finished Empty)))\n        (monitor\n          (((name (id 248)) (here ()) (id 248) (has_seen_error false)\n             (is_detached false))\n            ((name \"\") (here ()) (id 228) (has_seen_error false)\n              (is_detached true))))\n        (inner_monitor\n          (((name (id 249)) (here ()) (id 249) (has_seen_error false)\n             (is_detached true))\n            ((name \"\") (here ()) (id 228) (has_seen_error false)\n              (is_detached true))))\n        (background_writer_state Running) (background_writer_stopped Empty)\n        (syscall Per_cycle) (bytes_received 672416539)\n        (bytes_written 672316817) (scheduled_bytes 264) (scheduled_back 264)\n        (back 99722) (close_state Open) (close_finished Empty)\n        (close_started Empty) (num_producers_to_flush_at_close 0)\n        (flush_at_shutdown_elt (<opaque>))\n        (check_buffer_age\n          (((writer <opaque>) (maximum_age 2m)\n             (bytes_received_at_now_minus_maximum_age 672317521)\n             (bytes_received_queue\n               (672317961 672318577 672318841 672318929 672319369 672319897\n                 672321683 672322827 672333189 672344003 672354085 672354525\n                 672355229 672355669 672356109 672358159 672358775 672359655\n                 672360095 672370817 672373395 672373747 672374451 672374715\n                 672375331 672376035 672378085 672379405 672379933 672380813\n                 672380989 672381253 672382863 672384007 672394277 672395157\n                 672395509 672396565 672406631 672407247 672410001 672410089\n                 672410617 672411145 672411761 672412201 672415131 672415219\n                 672416011 672416451 672416539))\n             (times_received_queue\n               ((2020-06-15 09:09:02.222426000-07:00)\n                 (2020-06-15 09:09:06.043597000-07:00)\n                 (2020-06-15 09:09:08.047991000-07:00)\n                 (2020-06-15 09:09:09.048483000-07:00)\n                 (2020-06-15 09:09:12.057494000-07:00)\n                 (2020-06-15 09:09:16.079104000-07:00)\n                 (2020-06-15 09:09:17.081425000-07:00)\n                 (2020-06-15 09:09:20.092527000-07:00)\n                 (2020-06-15 09:09:25.831544000-07:00)\n                 (2020-06-15 09:09:26.837571000-07:00)\n                 (2020-06-15 09:09:27.844615000-07:00)\n                 (2020-06-15 09:09:28.854799000-07:00)\n                 (2020-06-15 09:09:29.856786000-07:00)\n                 (2020-06-15 09:09:30.875843000-07:00)\n                 (2020-06-15 09:09:31.876259000-07:00)\n                 (2020-06-15 09:09:32.876660000-07:00)\n                 (2020-06-15 09:09:34.881631000-07:00)\n                 (2020-06-15 09:09:38.899038000-07:00)\n                 (2020-06-15 09:09:42.904821000-07:00)\n                 (2020-06-15 09:09:45.990195000-07:00)\n                 (2020-06-15 09:09:47.000096000-07:00)\n                 (2020-06-15 09:09:50.507250000-07:00)\n                 (2020-06-15 09:09:54.517261000-07:00)\n                 (2020-06-15 09:09:57.557865000-07:00)\n                 (2020-06-15 09:09:58.558850000-07:00)\n                 (2020-06-15 09:10:01.626516000-07:00)\n                 (2020-06-15 09:10:04.642490000-07:00)\n                 (2020-06-15 09:10:05.757633000-07:00)\n                 (2020-06-15 09:10:09.515714000-07:00)\n                 (2020-06-15 09:10:13.532847000-07:00)\n                 (2020-06-15 09:10:16.576910000-07:00)\n                 (2020-06-15 09:10:17.579646000-07:00)\n                 (2020-06-15 09:10:19.645320000-07:00)\n                 (2020-06-15 09:10:20.650648000-07:00)\n                 (2020-06-15 09:10:23.827351000-07:00)\n                 (2020-06-15 09:10:24.831569000-07:00)\n                 (2020-06-15 09:10:30.841109000-07:00)\n                 (2020-06-15 09:10:31.848250000-07:00)\n                 (2020-06-15 09:10:33.860126000-07:00)\n                 (2020-06-15 09:10:34.865542000-07:00)\n                 (2020-06-15 09:10:35.870771000-07:00)\n                 (2020-06-15 09:10:36.873692000-07:00)\n                 (2020-06-15 09:10:39.900398000-07:00)\n                 (2020-06-15 09:10:40.902828000-07:00)\n                 (2020-06-15 09:10:43.915067000-07:00)\n                 (2020-06-15 09:10:47.939906000-07:00)\n                 (2020-06-15 09:10:52.170006000-07:00)\n                 (2020-06-15 09:10:55.191436000-07:00)\n                 (2020-06-15 09:10:56.196771000-07:00)\n                 (2020-06-15 09:10:59.224958000-07:00)\n                 (2020-06-15 09:11:00.228352000-07:00)))\n             (bytes_seen 672416539) (too_old (Full ())))))\n        (consumer_left Empty) (raise_when_consumer_leaves true)\n        (open_flags (Full (Ok (wronly)))) (line_ending Unix))))\n  (\"Caught by monitor (id 248)\"))"
> 2020-06-15 16:11:44 UTC [Info] failed to reset stream (this means it was probably closed successfully): $error
> 	error: "RPC #711025 failed: \"internal RPC error error: unknown stream_idx\""
> ```

I had this same crash

**Comment by bkase** [comment]
Luke is uploading the coda-config associated with not being able to restart. The `writer buffer has data older than\" (maximum_age 2m`-bug is notorious for being hard to find. Given that it only happens after the node is up for a long time, we won't prioritize fixing it -- but we do want to prioritize fixing the ability restart when this bug happens. 

We should open a new issue to track the restart problem

**Comment by ZoltarSeven** [comment]
I had the same issue after 6 days on my google cloud vm. Has there been any auto restart recommendation yet that would mitigate this problem? Seems that people are using different scripts to auto restart. Is there any recommended way?

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
