### ISSUE TITLE
Coda client updated to older version.

### ISSUE THREAD

**Issue by ilhanu** [MinaProtocol/mina#5149]
I'm on version `Commit 3e9b174 on branch feature/bump-genesis-timestamp` and when I do the following steps: 

1. `sudo apt update`
2. `sudo apt list --upgradable`
3. Following output : `coda-testnet-postake-medium-curves/unknown 321486-feature-snark-fuzzing-f10adcaf-PV85d7d9be amd64 [upgradable from: 0.0.12-beta+406048-feature-bump-genesis-timestamp-3e9b174-PV48525e92]`

According to @bkase this is an older version, shouldn't be showing up in the update.  I'm back on the current release, so problem solved for me.

**Comment by garethtdavies** [comment]
Related to this discussion: https://discordapp.com/channels/484437221055922177/583400552487059546/722563172262871092

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
