### ISSUE TITLE
Daemon crash: internal RPC error error: unknown stream_idx

### ISSUE THREAD

**Issue by utgarda** [MinaProtocol/mina#5176]
`coda daemon -peer $SEED1 -peer $SEED2 -snark-worker-parallelism 7 &> ./daemon.log`
```
etsvigun@coda-testnet:~$ uname -a
Linux coda-testnet 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64 GNU/Linux
```
[coda_crash_report_2020-06-20_17-47-59.419125.tar.gz](https://github.com/CodaProtocol/coda/files/4808653/coda_crash_report_2020-06-20_17-47-59.419125.tar.gz)

**Comment by utgarda** [comment]
[coda_crash_report_2020-06-20_22-31-24.308855.tar.gz](https://github.com/CodaProtocol/coda/files/4809300/coda_crash_report_2020-06-20_22-31-24.308855.tar.gz)

**Comment by bkase** [comment]
```
{"timestamp":"2020-06-20 22:31:22.158644Z","level":"Fatal","source":{"module":"Init__Coda_run","location":"File \"src/app/cli/src/init/coda_run.ml\", line 621, characters 56-63"},"message":"Unhandled top-level exception: $exn\nGenerating crash report","metadata":{"exn":"(monitor.ml.Error\n  \"Assert_failure src/lib/block_producer/block_producer.ml:598:16\"\n  (\"Raised at file \\\"src/lib/block_producer/block_producer.ml\\\", line 598, characters 16-234\"\n    \"Called from file \\\"src/result.ml\\\", line 151, characters 9-15\"\n    \"Caught by monitor coda\"))","host":"206.189.18.180","peer_id":"12D3KooW9yPsm97oVpt73aK47uzciJ8fmbmtLkPHuV6k82HhXSi2","pid":31312,"port":8302}}
```

**Comment by bkase** [comment]
Thanks for reporting!

**Comment by hsq125** [comment]
Hi!

I think we should not considering closing this issue. I have ~500 occurences of this error per day in the logs of an healthy node running for weeks now.

Either it is a normal situation, and then it should not be logged as an error, or it is a problem and it should be solved.

Environment
- Daemon version is `1.1.5-a42bdee`
- OS is `Linux cs3 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Docker version 20.10.7, build f0df350

Best regards,
O

**Comment by shimkiv** [comment]
@hsq125 do you still experience this issue?

**Comment by shimkiv** [comment]
Closing this issue because of being inactive for long time.
Please feel free to open another ticket should you experience any further issues.
