### ISSUE TITLE
 Can we always have a stable testnet up for partners? Name = "devnet"

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5206]
What would it take in terms of cloud computing cost, keeping it up to date, support and maintenance

**Comment by aneesharaines** [comment]
Proposal:
Have a mini network running with less resources that we keep up and update with the latest release 2 wks after a testNet release.  2 seeds, 2 bps, 2 sws

Need to double check the cost with @yourbuddyconner

**Comment by bkase** [comment]
Important: We need a way for rosetta to distinguish between devnet and main testnet (and later mainnet). For now, can I assume `dev.o1test.net` is in the multiaddr? Is there something we can stick in the peer multiaddr that I can look for to detect this? cc @yourbuddyconner

**Comment by lk86** [comment]
Up to date peering info for the devnet as it exists now is here: https://www.notion.so/codaprotocol/Devnet-Peering-Info-9954e11074d14e2d9663281ca86ae0d5

When we have more specific stable releases/tags to deploy, this network should certainly be updated to leverage those tags and i've noted the plan for that in notion so partners can see as well that this information will change as soon as we cut a 3.3 testnet release.
