### ISSUE TITLE
Running duplicate block producers does not mark both blocks as invalid

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#5236]
[This section](https://codaprotocol.com/docs/faq#can-i-run-multiple-block-producers-with-the-same-private-key) of the FAQ states:

> CAN I RUN MULTIPLE BLOCK PRODUCERS WITH THE SAME PRIVATE KEY?
> No. It is important to only run one Block Producer process against a particular private key. In the event the Coda daemon receives two different blocks from the same Block Producer, both blocks would be discarded.

This doesn't appear to be the case on the current testnet (3e9b1748183e653a7891adea1fef07c8e1a7dfcd). 

In the case where both producers produce the same block, the first is accepted and the second not:

**Block Producer 1**

```
Jun 26 11:34:53 d0ab405600ac coda 2020-06-26 18:34:52 UTC [Info] Generated transition $state_hash was accepted into transition frontier
Jun 26 11:34:53 d0ab405600ac coda 	state_hash: "D2rcXVQYbPk3NpVDj62RybBhqranhWLkLELc3GigShuvsyJ8bZ4qaHHFNwuaCkNuE5W5NVw5j4Zcg1cbQgTUPQDNwrB9eTiXTjgL7QEjnpz3ph9uJeY2pTdCLCuejL3AbdehMxcHEHwyhmtsNH1EsLE8BiL9RNxwopo7VkFaUnEpedEC4zPZZW3ZrofJ1BKvHKHZjR4G7gMkBeznBBatJMsDLksciBfigdryRJP1B8kFLDrRXyZRyiWH9dc2JP1gMPY3za4NAvh4qYTBgihVYJ6Xn2R161UVpgxF4T3YNdA1axXLGRxYcc5WjtH6WURnJT"
```

**Block Producer 2**

```
Jun 26 11:35:40 d51882fd06a3 coda 2020-06-26 18:35:40 UTC [Error] Validation failed: produced transition is already in frontier
```

However, in some instances, different state hashes are produced and they are both accepted for the same slot:

**[Block producer 1](https://codaexplorer.garethtdavies.com/block/D2rcXVQbc9BEL6q5MZ8TxffeJnWP1iN5ckX3NEVbernRVrn3WQcUGJPSvEcU25kxp9zMY7fgET7EEDfSwmyxKy2APMTA9rAGawmxX5jGajX5ao2q5FJmz5M7U53ebo9D1y9BBi5yGpZe9JT29d6p3vJfvdEvS8KjqTfw9LQsq2DYgDLLwTFmKVk5h8s6bLbG5dnej5D5DgVvWEEpiAN7wo5RHUNS7mxjfYdZF5JAumq2AStZxQdkHfGxxTg2PTHgGyMgzZQdAprS542K7asqgxzRe9HpGKPGiJGTQ78tA2puAN2ZZtuxUqivptJs9M4BxY)**

```
Jun 22 08:55:58 d0ab405600ac coda 2020-06-22 15:55:57 UTC [Info] Generated transition $state_hash was accepted into transition frontier
Jun 22 08:55:58 d0ab405600ac coda 	state_hash: "D2rcXVQbc9BEL6q5MZ8TxffeJnWP1iN5ckX3NEVbernRVrn3WQcUGJPSvEcU25kxp9zMY7fgET7EEDfSwmyxKy2APMTA9rAGawmxX5jGajX5ao2q5FJmz5M7U53ebo9D1y9BBi5yGpZe9JT29d6p3vJfvdEvS8KjqTfw9LQsq2DYgDLLwTFmKVk5h8s6bLbG5dnej5D5DgVvWEEpiAN7wo5RHUNS7mxjfYdZF5JAumq2AStZxQdkHfGxxTg2PTHgGyMgzZQdAprS542K7asqgxzRe9HpGKPGiJGTQ78tA2puAN2ZZtuxUqivptJs9M4BxY"
```

**[Block producer 2](https://codaexplorer.garethtdavies.com/block/D2rcXVQbesTrFsPRzgBuynM8zY7G4Sf8D8TP5weLevRH9K6Q93Y6SwED4P2Q8HcctoNdAiLiUaCZxPEXJJynaqtcwyaED6n7J3pFgHMACtkkAnQiChxuW8hKU1UF4heZjTS2YgDZ2TfjYcxkS8Qo1dZy7YrwMyTtNtFNqRkLZoNj1kbF5ePqmRUMKgQru2Ugb1X3ARviwjkNiTxdBfmNqBfizsUCccaSXjSSCK7FkNZ4TsyrgeirMP4vSmsaJM6MyKY7Rh5iRLtxZx1BADTfjUoJQC65XmiBRwwdRf69oewE6rFprTnDcUYhbewHdJFmDL)**

```
Jun 22 08:57:08 d51882fd06a3 coda 2020-06-22 15:57:08 UTC [Info] Generated transition $state_hash was accepted into transition frontier
Jun 22 08:57:08 d51882fd06a3 coda 	state_hash: "D2rcXVQbesTrFsPRzgBuynM8zY7G4Sf8D8TP5weLevRH9K6Q93Y6SwED4P2Q8HcctoNdAiLiUaCZxPEXJJynaqtcwyaED6n7J3pFgHMACtkkAnQiChxuW8hKU1UF4heZjTS2YgDZ2TfjYcxkS8Qo1dZy7YrwMyTtNtFNqRkLZoNj1kbF5ePqmRUMKgQru2Ugb1X3ARviwjkNiTxdBfmNqBfizsUCccaSXjSSCK7FkNZ4TsyrgeirMP4vSmsaJM6MyKY7Rh5iRLtxZx1BADTfjUoJQC65XmiBRwwdRf69oewE6rFprTnDcUYhbewHdJFmDL"
```

In this instance, the first block was seemingly included in the canonical chain. For these examples where different blocks are produced there is a corresponding log entry:

```
Jun 22 08:57:18 b0a803b3e8a5 explorer_coda.1.1agnukm774a1jxnsny0tp0xqh 2020-06-22 15:57:17 UTC [Error] Duplicate producer and slot: producer = $block_producer, consensus_time = $consensus_time, previous protocol state hash = $hash, current protocol state hash = $current_protocol_state_hash
Jun 22 08:57:18 b0a803b3e8a5 explorer_coda.1.1agnukm774a1jxnsny0tp0xqh 	block_producer: "4vsRCVGPNFDmHvuCctawApbyUg8J6iWzdHvJ2bNP8AL1GtMeaLwC6P8ZNTavKmAD4mMGbDq8H6DYramtiQP5fcf5xhdqAfYibt7Am9syUUU91oSf7HhLKrA26RPutsoyQSmZiMjPZoe1vDXW"
Jun 22 08:57:18 b0a803b3e8a5 explorer_coda.1.1agnukm774a1jxnsny0tp0xqh 	consensus_time: 
{
  "slot_number": "6648",
  "slots_per_epoch": "480"
}
Jun 22 08:57:18 b0a803b3e8a5 explorer_coda.1.1agnukm774a1jxnsny0tp0xqh 	hash: "D2rcXVQbc9BEL6q5MZ8TxffeJnWP1iN5ckX3NEVbernRVrn3WQcUGJPSvEcU25kxp9zMY7fgET7EEDfSwmyxKy2APMTA9rAGawmxX5jGajX5ao2q5FJmz5M7U53ebo9D1y9BBi5yGpZe9JT29d6p3vJfvdEvS8KjqTfw9LQsq2DYgDLLwTFmKVk5h8s6bLbG5dnej5D5DgVvWEEpiAN7wo5RHUNS7mxjfYdZF5JAumq2AStZxQdkHfGxxTg2PTHgGyMgzZQdAprS542K7asqgxzRe9HpGKPGiJGTQ78tA2puAN2ZZtuxUqivptJs9M4BxY"
```

This may be working as intended but is seemingly inconsistent with the FAQ as both blocks are not seen as invalid.

**Comment by bkase** [comment]
Thanks for reporting! It's possible at one point (or even still? but it doesn't seem that way from my quick looking through the code) we tied this into the trust system which is currently turned off.

**Comment by aneesharaines** [comment]
We should update the readme to be accurate.  @deepthiskumar  is going to check if there is a rule that should be applied in this scenario.

**Comment by deepthiskumar** [comment]
The behavior right now is that when we see duplicate blocks we simply discard it (we don't reduce the trust score either; multiple nodes might send you the same block ). 
But if they are two different blocks (different state hashes) for the same slot and same parent hash then we compare the VRF outputs and keep the bigger one as the best tip and the other as a fork.
in the case the two blocks are from the same block producer and if the first one we saw  was the best tip, it would continue to be so after receiving the second one. This is because VRF outputs of the blocks for a slot from one producer key are the same and so the `Consensus.select` function would simply keep the existing one. This can cause mismatch between best tips of different nodes based on what they see first. 
I'm not sure discarding an accepted block in this scenario is a good idea because then we would be creating empty slots and probably reducing the chain strength. Also, say, some nodes don't discard them and instead proposed on top of one of those blocks, that chain will be stronger than the chain that discarded the blocks. 
We need a deterministic tie breaking rule for this case (something that involves the staged ledger). Also, be able to say a chain with the block that won the tie is better than the chain with the block that did not win? This might tackle the nothing's at stake problem as well

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.

**Comment by emberian** [comment]
not sure this was ever changed...

**Comment by emberian** [comment]
https://github.com/MinaProtocol/mina/issues/3866#issuecomment-740060460

**Comment by EmrePiconbello** [comment]
@emberian Sharing this for some context. This is not changed and part of the core operation for block production. Also network is not stable to just run single block producer so not doings so put you in to significant disadvantage and miss value you can capture.
