### ISSUE TITLE
SNARK jobs from orphaned blocks are not evicted from the SNARK pool

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#5237]
It appears that SNARK jobs that have been produced for orphaned blocks are never evicted from the SNARK pool and as a result, the SNARK pool continues to grow. After running a node for over 2 weeks the current SNARK pool is over 27,000 jobs. However, only a tiny fraction of these `work_ids` can be found in the output of `coda advanced snark-job-list`.

There is seemingly no way to clear the node's SNARK pool short of restarting the daemon and so it seems this will grow indefinitely?

<img width="1794" alt="CleanShot 2020-06-27 at 09 40 04@2x" src="https://user-images.githubusercontent.com/135382/85927424-ccc12980-b85a-11ea-8548-a1832ff0fc2b.png">

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
