### ISSUE TITLE
Dhall: Write a Daemon.json Dhall Module 

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#5259]
Now that the `daemon.json` has received some much-needed love (thanks @mrmr1993!), it's time to start building on top of the interface. I am currently working on finishing up a runtime genesis PR in coda-automation that utilizes this JSON file. 

After talking to @nholland94 and @0x0I, we came to the conclusion that it would be both useful and super rad to have a type-safe way to generate this file, likely via Dhall. 

In order to complete this, we'd need to do the following: 
- [x] Generate a Dhall `dameon.json` type based on the OCaml codebase
- Build types for inputs, that can be passed from TF -> Dhall 
- Write a Dhall module that transforms the inputs into Dhall and outputs JSON

We believe that it's probably a good idea to co-locate these "interface types" with the OCaml code, allowing them to be regenerated on a change and having unit tests that verify their safety. It would then be trivial to then consume this module downstream in things like our Dhall helm charts or Terraform deployments. 

Couple questions that came up: 
- @mrmr1993, would it be possible to write a PPX that can generate this `daemon.json` Dhall type from the OCaml Types? 
- How much time/effort would this task be?

**Comment by mrmr1993** [comment]
> Couple questions that came up:
> 
> * @mrmr1993, would it be possible to write a PPX that can generate this `daemon.json` Dhall type from the OCaml Types?
> * How much time/effort would this task be?

This should be pretty easy. I'm not very familiar with Dhall, but I imagine I could pick it up and spin something out in a couple of hours or so.

**Comment by bkase** [comment]
> would it be possible to write a PPX that can generate this daemon.json Dhall type from the OCaml Types?

This would be awesome

**Comment by psteckler** [comment]
The ppx would generate a string to represent the Dhall type, yes?

**Comment by yourbuddyconner** [comment]
@psteckler Yeah, I think we'd then commit that to a Dhall module somewhere in the codebase such that we are then able to import that in downstream Dhall code.

**Comment by psteckler** [comment]
this is the type `Runtime_config.t`, then?

**Comment by yourbuddyconner** [comment]
@psteckler could you link to the spot in the codebase you're referring to?

**Comment by psteckler** [comment]
@yourbuddyconner https://github.com/CodaProtocol/coda/blob/develop/src/lib/runtime_config/runtime_config.ml#L351

**Comment by yourbuddyconner** [comment]
@psteckler Yeah, that's it!

**Comment by psteckler** [comment]
@yourbuddyconner I think we could add to that type something like `[@@deriving dhall_type]`, which would generate a string which we could print out and save to a file.

All the types that feed into that type would need a similar annotation, like we do for versions, and we'd paste together the parts into one string.

@mrmr1993 Is that what you had in mind?

**Comment by psteckler** [comment]
Alternatively, define an OCaml type like `dhall_type`, build it via `deriving`, and create a printer for it.

**Comment by mrmr1993** [comment]
> Alternatively, define an OCaml type like `dhall_type`, build it via `deriving`, and create a printer for it.

This is exactly what I had in mind, thanks @psteckler

**Comment by psteckler** [comment]
I can take this on, if needed.

**Comment by psteckler** [comment]
The ppx to generate the type for the runtime config is done, in #5299 (merged).

**Comment by aneesharaines** [comment]
Moving this to done for protocol for now, looks like the rest of the work is on infra

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
