### ISSUE TITLE
Buildkite CI: Fix race condition exfiltration

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#5273]
An adversarial contributor could sneak in evil exfiltration information between a core contributor saying it's "okay" via `!ci-build-me` comment

**Comment by robinbb** [comment]
Is `!ci-build-me` still active?

**Comment by balsoft** [comment]
There seems to still be a relevant piece of code: https://github.com/MinaProtocol/mina/blob/develop/frontend/ci-build-me/src/index.js#L170

Not sure if it's used, though.

**Comment by robinbb** [comment]
I think it's safe to take this, @balsoft

**Comment by dkijania** [comment]
Currently only public members of mina protocol members can trigger builds. I think we can close it
