### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by jkrauska** [MinaProtocol/mina#530]
Each fresh build outputs exe files with slightly different sha1 signatures.

Ideally we should have a way to confirm/guarantee that for a given source tree input, we can get out a consistent set of executables as output

Things to review: 
- debug symbols
- embedded build timestamps
- lib/nanobit_base/insecure.ml
  -  change values from key_generation to extend_blockchain to false
  -  change with_snark to true
- dune build ordering

**Comment by shimkiv** [comment]
By now, reproducible builds are achieved with the help of [Nix](https://github.com/MinaProtocol/mina/blob/develop/nix/README.md). 
Closing.
