### ISSUE TITLE
[Little RFC] Encoding token identifiers into addresses

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#5377]
## Problem

In our network, we've been using public keys interchangeably with account addresses. Other than being a little long, this works fine until we introduce custom tokens.

Now, accounts are identified by both a `token_id` and a `public_key`.

The problem is: When communicating an address, as a user, I just want to send one string, I don't want to have to think about sending two pieces of information. It also would be nice if the address easily was recognizable as a specific token.

## Proposal

From the user's perspective, an account is just a public key and it holds all different kinds of tokens. We may later adopt a mechanism for reflecting the token I wish to receive in an address, but it is unnecessary for now. TODO provide a mechanism for retrieving balances from all tokens from graphql /cli.

## Proposal

Public keys are addresses for the main CODA token.

Other tokens use the following address:
`TOK<token_id>|<public_key>`

Example of CODA Address:
`4vsRCVMNTrCx4NpN6kKTkFKLcFN4vXUP5RB9PqSZe1qsyDs4AW5XeNgAf16WUPRBCakaPiXcxjp6JUpGNQ6fdU977x5LntvxrSg11xrmK6ZDaGSMEGj12dkeEpyKcEpkzcKwYWZ2Yf2vpwQP`

Example of custom token 783 address:
`TOK783|4vsRCVMNTrCx4NpN6kKTkFKLcFN4vXUP5RB9PqSZe1qsyDs4AW5XeNgAf16WUPRBCakaPiXcxjp6JUpGNQ6fdU977x5LntvxrSg11xrmK6ZDaGSMEGj12dkeEpyKcEpkzcKwYWZ2Yf2vpwQP`

This encoding is nice because:
1. It's one piece of information I need to share
2. I can easily tell if an address specifies a custom token by looking at the prefix
3. I am somewhat protected against typos because I'll know the id of the token I'm trying to send / receive
4. It is trivial to decode this token address into a token_id and a public_key so the rest of the system can understand it.
5. It is backwards compatible with our existing format for the main token

## Deadline

Thursday 7/16 is the deadline on a decision; we need to decide fast because it's going to be baked into Rosetta integration.

## Changelog

* 7/17 Moved details to `OLD`, changed proposal to reflect latest plans (locked in for the purposes of the current rosetta integration)

**Comment by lk86** [comment]
Is there a checksum of any sort built into the address scheme? And if so, can this checksum also include the token prefix?

**Comment by bkase** [comment]
@lk86 the public key has a checksum baked into it (base58 encoded) -- token prefix doesn't.

Maybe it makes sense to concatenate the token id bytes to the public key bytes and then base58 encode? We lose the human readable bit at the front, but maybe the checksum is better.

**Comment by mrmr1993** [comment]
> Maybe it makes sense to concatenate the token id bytes to the public key bytes and then base58 encode?

I like that the proposed format is human-readable. My ideal would be if we could
* add an optional checksum to the end `|CHKxx`
* always emit the checksum from APIs
* parse with or without the checksum, but rejecting if the checksum is present but incorrect
* add a couple of tiny API endpoints for adding or checking the checksum

**Comment by figitaki** [comment]
Can the token ID only be 3 bytes?

**Comment by Schmavery** [comment]
This seems like slightly funny semantics. In the original proposal I made for the GraphQL support for tokens, I was proposing semantics where an account has 1 pubkey, and an account can have multiple different tokens associated with it.

Then you just decide when sending tokens to the account which token id to use, and don't need to remember a separate address for each one. If a token doesn't get specified, assume the default token.

**Comment by jspada** [comment]
If you're going to introduce an encoding, which is a great idea, then please consider bech32 because is a lot better than base58.  

https://en.bitcoin.it/wiki/BIP_0173

Among other advantages, bech32 gives you better typo detection and more efficient QR codes.

In terms of the proposed scheme for changing the address prefix for different tokens; putting my user hat on, I actually don't like this idea.  I would prefer to always have the same address with the ability to send different tokens to it transparently (as in Ethereum).  This way, as a user, I do not need to worry about changing my address prefix depending on what I'm receiving.  I can just use my address and always know that my account will hold whatever tokens I send to it.  The type of token type being transferred can be encoded elsewhere in the transaction, rather than in my address.

**Comment by lk86** [comment]
Regardless of how we think about accounts, addresses are still addresses and should remain one address per "user"/owner. The idea that the token type is a property of the transaction more than the account is mostly true, but users need a way to check on their own accounts and there will be a distinct account for each type of received currency (we can model it as one account with many currencies but I don't think that is any easier to understand, and exchanges very consistently consider these multiple accounts).

This means that for the purposes of sending/receiving transactions, we need the sender address, receiver address, and the token type that you are transacting in, with no concept of accounts. This also makes it possible for addresses to be "smarter" and automatically convert between tokens when they are received, or really any abstraction around incoming deposits not directly resulting in a new account balance for that token. For checking balances, I think a human-readable token ID prepended to the address is very reasonable (together forming an account ID) and we do not care about any special check/verify encoding for validating the token ID.

Speaking to the point about check encodings, I also support the proposal of moving towards bech32 but I also expect that its a much harder change to make at this point. It should be possible to add a conversion layer only in the Rosetta API to start, or to accept both bech32 + base58 versions of the same address for compatibility.

**Comment by bkase** [comment]
@figitaki : TokenId is 32bit int, so if we encode token id as a decimal number it's up to 9 bytes

My current thoughts:

I do think @Schmavery 's suggestion makes a lot of sense to me. It also seems like most folks agree that it's simpler and easier to use and it's consistent with Eth's behavior.

If we want a way to get all token balances for a given public key, we'll need to add another index on ledgers, but I think that's worth doing (and also something we can do later). But it's easy to lookup a balance for a publickey;token-id pair.

Given all this, I think we can add an optional extension later (as in not now) that supports the token-id prepended to the pk. But for now, you just can be explicit when doing a lookup or a send and default to the main token like ethereum. I skimmed our public API and I think this is possible, but I'm not 100% sure -- @mrmr1993 can you confirm?

And yes @lk86 is right, changing to bech32 right now is out-of-scope (though I do wish we used it).

**Comment by mrmr1993** [comment]
> TokenId is 32bit int

It's 64-bit at the moment (~4 million seemed like a number that a global counter could plausibly hit eventually), so <= 20 decimal digits :sweat_smile: 

> If we want a way to get all token balances for a given public key, we'll need to add another index on ledgers, but I think that's worth doing (and also something we can do later)

[Already done](https://github.com/CodaProtocol/coda/blob/edba1b7bb8938fdfd44efe29d89fdbfe7483b51c/src/lib/merkle_ledger/base_ledger_intf.ml#L77), routing it through GraphQL to look up all of the accounts should be fairly straightforward.

> But for now, you just can be explicit when doing a lookup or a send and default to the main token like ethereum.

The GraphQL API is already doing this for back-compat reasons. I think it's plausible to do similar in any other APIs we expose, especially if they are routed through GraphQL.

**Comment by psteckler** [comment]
@bkase Was a decision taken on this issue?

**Comment by bkase** [comment]
@psteckler updated

**Comment by bkase** [comment]
The proposal in the original post was adopted
