### ISSUE TITLE
Automated Validation - validation request dependency solving

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#5388]
The automated validation service is currently manually configured with all of the providers, statistics, and validations we want to perform on the network. However, what we actually want is to solve for all of these given some input request of resources and validations to perform against those resources. 

https://github.com/CodaProtocol/coda/blob/develop/rfcs/0032-automated-validation.md lightly describes how request dependency solving should work, but to summarize, the inputs to the validation service are:

1) A `ResourceSet.t`, which will be derived from a deployment.
2) A set of validation requests.

https://github.com/CodaProtocol/coda/blob/develop/src/app/validation/lib/coda/application.ex#L35 shows an ad-hoc example of how this could work. Given the top level request to perform `Validation.GlobalBlockAcceptanceRate` (a validation that does not currently exist atm, but provides an example of a relatively complex, high level validation), the solver continuously crawls the through dependencies for that validation to expand more dependencies. In this example, each nested `>` is a nested dependency which was realized by looking at the parent module (be it validation, statistics, or provider). An important not here is that, in the process of solving, there are 2 kinds of statistics: global statistics (which are not scoped to a specific resource), and individual statistics (which are scoped to a specific resource). In order to express resource dependencies in a succinct tree structure, some form of resource quantification should be introduced in the description of dependencies. Note that log providers are always scoped to a specific resource.

Please reach out to me for more details if this doesn't fully make sense. Ultimately, this shouldn't be too complex to implement, but I'm not sure if I did the best job at describing it in a way that is obvious to implement.

**Comment by mrmr1993** [comment]
Retired app; closing.
