### ISSUE TITLE
Add full block field to annotated balance in GraphQL

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#5396]
For Rosetta, we need to at least partially support accessing the block that was used to compute the account balance. At the moment, some of the fields in block are not implemented.

A good design for this API would be to recursively expose "block" on annotated balance.

This is a good "easy" graphql API task in that you just have to follow the compile errors and the code will work. It's not easy in that you'll need to juggle a bunch of code to make the mutual recursion work out.

**Comment by Schmavery** [comment]
We worked around some previous requirements for this at one point by exposing the block height (I think) on the balance object, if that's not enough anymore then exposing the block probably makes sense.

**Comment by bkase** [comment]
Yeah the new Rosetta spec asked for the state hash too @Schmavery
