### ISSUE TITLE
Block Latency Numbers for Vanishree

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5411]

**Comment by aneesharaines** [comment]
Unblocked by network fork, script is updated.  Just need to run on various

**Comment by aneesharaines** [comment]
Need to run on a network with txns to get realistic numbers.

**Comment by aneesharaines** [comment]
Still need to run on a 400 node network will do now that compute is unblocked

**Comment by aneesharaines** [comment]
waiting until the new fast snark lands to get new numbers

**Comment by deepthiskumar** [comment]
Generated numbers for small network size and extrapolated it for bigger network size. I don't think we need anything more on this. Closing it, let's open a new one if we need to perform a similar task again
