### ISSUE TITLE
Debug_assert should log if it fails in prod

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#5414]
https://github.com/CodaProtocol/coda/issues/5354 disabled an assertion that failed sometimes but we still really want to make sure it doesn't happen in tests etc. If it were instead replaced with a debug_assert, and debug_assert _logged its failure_ when in prod (instead of not running at all), we could use the Automated Validation Service (or just a grep through a json file at the end of CI) to ensure no such asserts failed. This blends both worlds: we get the signalling etc of the debug assert information without the reliability hit in weird but nonfatal situations. We currently don't have the infrastructure in place to reliably fail CI etc when it happens. This would be a good telemetry candidate too.

**Comment by nholland94** [comment]
If we still want to do this, we do need to take care as some of the `debug_assert` calls are wrapping expensive code that is checking a lot of invariants. We don't want to run these checks in production at all. So we will need to have 2 kinds of debug asserts: ones which run in "check" mode in prod, and ones which do not run at all in prod.

**Comment by emberian** [comment]
We don't want to do this
