### ISSUE TITLE
Potential integer overflow in archive node processor

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#5419]
in `archive_lib/processor.ml` there is are a few `to_int` conversions on uint64s that can overflow.

**Comment by aneesharaines** [comment]
Fork and fix the SQL lib to support unsigned 64s  - optimal solution.

**Comment by psteckler** [comment]
The Postgres `bigint` type is a signed 64-bit value, so we'd have to use a different data type to store such values if we wanted to guarantee no data loss.

I'm changing the archive lib code to use `int64`, which is slightly better than `int`, which is a signed 63-bit value in OCaml.

**Comment by robinbb** [comment]
@psteckler Is your merged PR sufficient to close this issue?

**Comment by psteckler** [comment]
> @psteckler Is your merged PR sufficient to close this issue?

Yes.
