### ISSUE TITLE
Simplify account-creation-fee behavior

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#5428]
Exchanges and other parties that are very careful to keep a ledger of balance transfer changes off-chain desire the property that every transaction deterministically produces the same N balance transfers or fails. If we allow implicit account creation, then it's not clear just by looking at a transaction how funds move between accounts. It is also impossible to implement the rosetta spec properly without this.

We should add a field to txns in the relevant places to opt-in to account creation explicit, and add this to GraphQL and CLI wherever necessary. When this bit is missing, account creation should unconditionally fail with an error even if enough funds are moved that an account creation fee would be covered.

**Comment by mrmr1993** [comment]
My preferred solution to this is:
* always show the account creation fee as charged to the receiver (when TID=1)
* show this sub-transaction as failed if the account already existed.

**Comment by aneesharaines** [comment]
Brandon to see which of the 3 possible solutions is best for auditing

**Comment by bkase** [comment]
According to some third parties, what is preferred from an integration perspective is actually pulling the account creation-fee implicitly from the `fee` field of the transaction. This way if you are uncertain an account exists you can just fudge your fee a bit, but don't have to rely on wallet balances.

**Comment by mrmr1993** [comment]
To bring our OOB discussion into the open:

> Changing fees to include account creation is a big switch, it means block producers can never look at a transaction and know whether it will be worth including or not.

> There's now an explicit create account command, so they should be able to always set that flag and not worry about fees, if that helps with any tensions
