### ISSUE TITLE
O(1) Key Database

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#5434]
At O(1), we have several requirements around Testnets: 
- We have a desire to run multiple testnets at once. 
- We would like developers to be able to "allocate" keys with stake for use with development. (Gets around the epoch ledger staking requirements) 
- Integration Tests need a way to retrieve keys for use with its own managed testnets. 
- With public testnets, it is useful to be able to retrieve keys for a particular block producer without logging into the pod
- We would like to be able to generate keys on-demand, remotely

Essentially, we need a service that can manage metadata for a set of key-pairs. It should allow for corresponding public keys to be downloaded for inclusion in the genesis ledger. It should also allow for retrieval of the private keys for use with deployments and integration tests. 

Extra credit: 
- Is "testnet-aware", i.e. keys can be marked as being included in a particular testnet
- Allow for storage of singleton public keys for community members and other "known keys" for a particular testnet
- Allow for automated sending of delegation transactions on a particular testnet

Options: 
- Web service backed by Secrets Manager or S3 
- Script that acts against a Database like DynamoDB or object store like S3

Alternatives: 
- We could just generate all the keys for every deploy at deploy-time, however this wouldn't solve the collaboration/sharing aspect for public networks.

**Comment by lk86** [comment]
To what degree does the db portion of SKS keyserver (the software behind pgp.mit.edu) serve our needs? https://github.com/SKS-Keyserver/sks-keyserver/wiki

We would still need a permissioned system for handling private keys but as a way for community members to publish metadata around their public keys it seems ideal.

**Comment by yourbuddyconner** [comment]
@lk86 Yeah, the idea for this particular thing would be for it to only be used in a non-secure *development* context, so I was thinking originally that the security of the database is somewhat orthogonal to the requirements. That said, there's no reason not to use something more secure if it's got accessible APIs.

**Comment by lk86** [comment]
yeah, my main point is that SKS is really well put together for people who control keypairs  to publish the public key + metadata, but it does not handle the private keys in any way. I feel like AWS Secrets Manager is a very reasonable solution for sharing private keys to the degree that we need to. SKS really only solves the "extra credit 2" of publicizing well-known public keys of community members or testnet nodes (and we could just encourage folks to publish to pgp.mit.edu and not run anything internally for that use case anyway).

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
