### ISSUE TITLE
Hard fork scenarios

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#5443]
Disaster recovery

| | Cases | Examples|
|-----|------------------|-----------------------------------------------|
| 1. | Nodes failing |Non-snark errors such as crashes, gossip issues, transaction errors(like the invalid nonce issue) etc |
| 2. | Prover/verifier failures| Blockchain or transaction snark|
| 3. | Security flaws | broken hash function|
||| consensus related errors|
||| Weakened chain strength because of insufficient nodes online or because of an attack|

Planned hard forks

| | Cases | Examples|
|-----|------------------|-----------------------------------------------|
| 1. | Tuning consensus parameters | see #5473 |

**Comment by psteckler** [comment]
Should we add a case for tuning the consensus parameters (see #5473)?
