### ISSUE TITLE
Automated Validation Autogenerated Log Providers

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#5479]
Now that structured logging is in (and #5223 adds support to dump the available structured logs), we can auto generate log providers for these structured logs inside of the automated validation service. See https://github.com/CodaProtocol/coda/blob/ec4f7811e32b40955655b29127f38c87d80a2ba3/src/app/validation/lib/coda/providers/block_produced.ex#L1 for an example of how a `LogProvider` is defined. From an individual record exported by the structured log dump, we can generate a log filter and named `LogProvider` module. Note that, for now, the `resource_class` of all structured logs can just be set to `CodaNode` (we do not need to add extra classification for `BlockProducer` and other roles for the time being).

You can set up this information to be imported at compile time by implementing a macro in elixir and calling it inside of the `Coda` module definition. A config flag can be provided to specify a coda image to pull the structured logs from, and the macro can (during compile time) execute a command in this container to get the structure log dump as JSON. It can then iterate over that JSON, and emit new module definitions for each of the log providers as AST.

In order to close this issue, we should have a test which does not depend on a coda daemon image to pull JSON from, and just has some hard coded inputs which it expects to generate some specific modules.

**Comment by mrmr1993** [comment]
Automated validation app has been long retired. Closing.
