### ISSUE TITLE
Automated Validation Spot Providers

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#5481]
#5137 added the initial implementation for the automated validation service, but it only contains log providers. Another important type of provider (which is necessary for effectively implementing a number of core statistics) is a spot provider. A spot provider is a provider which, on demand, will provide some information. Specifically, for now, we are interested only in GraphQL spot providers, so we do not need to worry about other types of spot providers for the time being.

A spot provider has the following semantics:

- information from a spot provider is not "subscribed to" in the same way that a information from a log provider is subscribed to
- information from a spot provider is requested by calling some kind of `get` function, which can accept a arguments (example: `BestTipPathProvider.get my_resource` would request and return the best tip path for the coda node associated with that resource)
- spot providers should have an internal cache, such that they do not continuously request information over and over again from the same resources
  - expect spot providers to constantly receive lots of requests from lots of statistics, but don't let them spam nodes
  - the lifetime of this cache should be configurable by each spot provider definition

Each spot provider definition should have a single server associated with it to handle requests, but that server should spawn multiple workers (asynchronously to handling requests) which will actually make the GraphQL requests. In more detail, a `Architecture.SpotProvider.Server` should be a `GenServer` which implements `handle_call({:get, args}, _, _)`. If the requested information exists in the servers cache, and the cached value hasn't expired yet, then it immediately replies to the caller by returning `{:reply, response, _}`. If the requested information needs to be fetched, then the server should not reply immediately, and should instead spawn a new `Task` to get that information. The `Task` process should send a message back to the server when it completes, and the server will update its cache and finally respond to any pending clients which are waiting for that information. Importantly, that means that the server needs to track what information is still being requested, and handle duplicate requests to `{:get, args}` accordingly.

**Comment by mrmr1993** [comment]
Retired app; closing.
