### ISSUE TITLE
Limit length of read RPC responses

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#5498]
For RPC `response` types, design a mechanism to limit the length of lists that are read, to prevent DOS attacks using extra-long responses.

Possibilities:

- a list-with-max-length type, with a `bin_read` that checks the length; a linter
   could verify this type is used with all RPCs
- an annotation on list types that specifies the max length, which would guide the `bin_io` 
   generation

**Comment by psteckler** [comment]
`bin_read_t` takes a buffer of serialized data, so if we do the length check there, we've already taken the time to download the data

Also, if we do a `failwith` when the list is too long, we had better handle that, otherwise we have a DOS attack that crashes the node

**Comment by psteckler** [comment]
I can think of a solution where you'd write something like:
```ocaml
type response = M.Stable.V1.t [%%list_with_length 42]
```
and the `bin_read_t` would fail if the length exceeded the specified limit.

**Comment by imeckler** [comment]
I vote for forking the RPC library and just checking that the length of a message is less than some bound (4MB? I don't know).

This has several advantages:
1. It's very easy to implement.
2. It will apply to every message automatically, we don't have to separately do it for lists, arrays, etc.
