### ISSUE TITLE
Archive node Docs 

### ISSUE THREAD

**Issue by michellewong793** [MinaProtocol/mina#5508]
Plan: 

1) Draft docs page 
2) Review with respective engineers and iterate on copy + instructions 
3) Add cool queries 
4) Add instructions on how to start archive node 
5) Add prereqs

**Comment by aneesharaines** [comment]
Waiting on the archive node deb package and the name.  Package needs to be created and docs updated with the name.

**Comment by robinbb** [comment]
@michellewong793 are you still working on this issue? Can the Mina Foundation engineering team take it from you?
