### ISSUE TITLE
Batch Snark work to be broadcasted

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5567]
A snark coordinator adds completed snark work to the pool and broadcasts as soon as it receives from a snark worker process. Each completed work is  verified and broadcasted separately. When many snark workers are sending completed work to the coordinator at once, it is causing long async cycles of 90-140 seconds (seen in a testnet with 64 snark workers connecting to a coordinator). Waiting for some time to collect as many completed work before adding it to the pool will help leverage batch verification and will result in less messages to be gossiped.

**Comment by deepthiskumar** [comment]
Currently, all the snark workers use the public key and fee set by the snark coordinator. When that changes to allow snark workers to have their own fee and public key, this would require the solution proposed in #4882

**Comment by aneesharaines** [comment]
Will revisit for work outside of the verification if it seems like this is still a bottleneck

**Comment by emberian** [comment]
done by 2fa079d8d220efe3b871f21fc1a205cb1ee591f3
