### ISSUE TITLE
Simplified Banning

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5637]
- Fix #5638 
- Come up with a min list of Insta Bans
- Turn on banning w/ only Insta Bans enabled

Simple testing

**Comment by imeckler** [comment]
Looks like this is where Cardano implements banning:

- https://github.com/input-output-hk/ouroboros-network/blob/141a4c1eee1426a7e480c847998c4f3be073fc50/ouroboros-network/src/Ouroboros/Network/NodeToNode.hs#L620
- https://github.com/input-output-hk/ouroboros-network/blob/3331ffc0dfbc165e4899eab2056859333e24c948/ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs

I believe `theyBuggyOrEvil` is where it responds with an instant ban.
