### ISSUE TITLE
Refactor Helm/Terraform Versioning 

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#5641]
We have a requirement to better couple our `coda` and `coda-automation` repositories. This can be achieved by refactoring the structure of `coda-automation` and changing the way we version/release our helm charts. 

Tasks that need to be done to achieve this: 
- Move helm charts to Coda Repo, with Coda Daemon helm charts in one folder and the remainder of the charts co-located with the source code in the Monorepo 
- Individually version/build helm charts with [A Docker Registry like GCR](https://helm.sh/docs/topics/registries/) 
- Refactor TF Testnet module to support pinned Helm Chart versions as opposed to relative paths (via variables) 
- Cut a release `0.0.1` for the testnet terraform module in `coda-automation`
- Write up Documentation of versioning Scheme for all this

Results: 
- Integration tests can pin to a specific version of the testnet module 
- Services can be iterated on individually, at different versions

**Comment by deepthiskumar** [comment]
We also should to include the testnet guardian runbook in this so that it is updated accordingly
