### ISSUE TITLE
[website] job descriptions look clunky/don't wrap in the team section

### ISSUE THREAD

**Issue by paul-schaaf** [MinaProtocol/mina#5649]
See Title. Examples:
<img width="402" alt="Screenshot 2020-08-14 at 15 01 06" src="https://user-images.githubusercontent.com/29666990/90252025-154e9980-de3f-11ea-8430-d2853163e8a3.png">
<img width="392" alt="Screenshot 2020-08-14 at 15 01 11" src="https://user-images.githubusercontent.com/29666990/90252033-1a134d80-de3f-11ea-982c-8de5e16aa261.png">

Specs:
Chrome Version 84.0.4147.105 (Official Build) (64-bit)
MacOS Version 10.15.6 (19G73)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
