### ISSUE TITLE
Add Hubspot tracking code to current website

### ISSUE THREAD

**Issue by sherrylin13** [MinaProtocol/mina#5702]
Add Hubspot tracking code to our website so we can begin tracking lead activities.

Copy and paste this tracking code into every page of the Coda site, just before the </body> tag:

<script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/8298093.js"></script>

More details/instructions: https://knowledge.hubspot.com/reports/install-the-hubspot-tracking-code#copy-your-hubspot-tracking-code

Timing: Ideally would like to set this up by Monday, August 24th, since we have some campaigns planned for Testnet Release 3.3.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
