### ISSUE TITLE
Daily `develop` CI tests still fail.

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5716]
https://app.circleci.com/pipelines/github/CodaProtocol/coda/26166/workflows/105f3171-5752-4938-b402-3dea7f33a397/jobs/484181

**Comment by aneesharaines** [comment]
@deepthiskumar  to find the issue for this.  Maybe there is an issue here that needs to be addressed as full snarks are run on the daily CI runs?

**Comment by deepthiskumar** [comment]
Couldn't find an issue but here's another link to the test, we were seeing the `local state desync` error before: https://app.circleci.com/pipelines/github/CodaProtocol/coda/21935/workflows/f5c712eb-9a46-4a6e-a9cf-c662db328d59/jobs/413657
IIRC @ghost-not-in-the-shell was investigating a similar issue on the 3.2 testnet
