### ISSUE TITLE
coda client mint-tokens does not validate token account exists

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#5764]
I inadvertently minted tokens for a token that does not exist. Surprisingly this results in a valid transaction that is submitted but of course is not reflected in the ledger as the token has yet to be created. It seem there should be an extra validation step here that you are able to mint tokens before a transaction is submitted?

This is tested on `codaprotocol/coda-demo:0.0.15-beta-fix-token-fix-8752f21` with the command, where the token id of `100` does not exist.

`coda client mint-tokens -sender B62qrPN5Y5yq8kGE3FbVKbGTdTAJNdtNtB5sNVpxyRwWGcDEhpMzc8g -token 100 -amount 100`

This results in: 

```
Dispatched mint token command with TRANSACTION_ID G8k9HJXpug4J4thR9me9Ft7CfHwAma7dN7xJyRSJvmuR7C2wmgXHyZP3NVjTbZr38YXNenZkDMaYpGREi17b2q9Ev6ew88q4RZj9xtSRJMMhEADakjCAMcfD6Pzjk1wessBBD8W4oRvNKjKwCt2S8dgy1kkeutPYVggvnuSTMvvfuZPThYsvVeGhGsgnAPuZHW7HackkN4rMz8xEZkHNwY2bb5f3bGa3TBAojwHHvAhxUAoqpGLrP98FZUC6L3Uhbexq3o4wHaXxnMgLuycUwYDMv8iGRLr3vYQS5CV3YeqjXZwmWDXoHsSkhe7Q6e1qcfrx1MNi7MawH5TqZEinkgz1boUmS2FAkbektHKoWryVh5b1h451XVJQUyxq5SSKSDVvLHnQD
```

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
