### ISSUE TITLE
Deployment CLI

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#5768]
As more and more people onboard to Coda, it's become apparent that the deployment process is incredibly opaque and hard to grok for someone with little to no context. It would be really great to produce a deployment CLI that encapsulates the *hard stuff* like ledger creation and deployment. 

Thoughts: 
- Might be prudent to re-implement the terraform deployment in a script 
- Much more modular
- probably easier to iterate quickly on
- More accessible for community members

Time Estimate: 
- ? (Needs more thought, probably a Medium-sized project)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
