### ISSUE TITLE
Infra Cost and Architecture

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#5774]
With the advent of huge QA nets and the Pickles SNARK sucking up resources, it's become important to be able to reduce our costs by taking advantage of credits provided by various cloud providers.

The MVP QA Network is designed to deploy testnets to a single k8s cluster, in a single region in GCP, to facilitate this we need we need to rearchitect the deployment. 

Requirements: 
- Able to deploy bulk of resources to Azure Kubernetes Service (easy multi-cloud deployment)
- Able to deploy core services/Whales to GCP 

Implementation Options: 
- Couple Infra and Application Deployment more closely 
- Standardize on `kubectl` as the deployment interface, abstract away Terraform and write a script 
- Keep the Terraform as-is, extend to be able to dynamically retrieve credentials from any cloud provider 

Time Estimate: 
- 5-9 days

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
