### ISSUE TITLE
Start to test Delta = 0

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5782]
Looking at catch up and bootstrap

Start with running networks with highslot time (12min slot + delta=0) and high f

* Set f=0.75
* Reduce slot time as we determine validation time isn't too bad
* Reduce slot time as faster snark gets in

**Comment by aneesharaines** [comment]
(current) network parameters for mainNet 
k = 225
Active slots co-efficient f = 0.75
Slot duration = 2.5 minutes
Epoch duration = 5539 slots

**Comment by mrmr1993** [comment]
Mainnet has been successfully running with `delta=0`. Closing.
