### ISSUE TITLE
Boot the network from the new ledger

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5855]
The ability to start from the network from this new ledger - change the genesis block such that its aware of the n-1 block (prev state hash)

**Comment by bkase** [comment]
We will still start at slot=0 and epoch=0, just that `previous-state-hash=hash(block_forking_from)` and `height=height(block_forking_from)+1`

**Comment by imeckler** [comment]
Will we want the network ID to change? I think it may be problematic if the network ID does not change and people on the old chain try to interact with transitions from this chain.

**Comment by imeckler** [comment]
Oh I guess it will change since we'll be resetting the genesis timestamp.

**Comment by imeckler** [comment]
Implemented here https://github.com/CodaProtocol/coda/pull/6141

**Comment by imeckler** [comment]
Implemented here https://github.com/CodaProtocol/coda/pull/6141
