### ISSUE TITLE
Add Rosetta CLI tests to CI

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5886]
Make the CLI tests soft fail until all the test are fully integrated

**Comment by robinbb** [comment]
@lk86 Is it safe to take this issue from you and assign to Mina Foundation engineers? Is there indeed more work to do?

**Comment by kantp** [comment]
@kaozenn is already working on this in #12099. @kaozenn, would you see this ticket as the next step after #12099, or as a duplicate?

**Comment by kaozenn** [comment]
@kantp, You are right. This ticket is about implementing the integration tests described in https://github.com/MinaProtocol/mina/issues/12099 in the CI

**Comment by kantp** [comment]
Ok, so is this a duplicate that we should close, or the next step after #12099?

**Comment by kaozenn** [comment]
This ticket is the next step after https://github.com/MinaProtocol/mina/issues/12099. We should not close it.

**Comment by kantp** [comment]
Thanks for the clarification!
