### ISSUE TITLE
Docker container crash

### ISSUE THREAD

**Issue by sm1ck** [MinaProtocol/mina#5891]
I took part in Pickles Sandbox Release Challenges and after some successful work, the container just broke.
I'll just attach the crash log.
[coda_crash_report_2020-09-09_10-22-49.719159.tar.gz](https://github.com/CodaProtocol/coda/files/5194597/coda_crash_report_2020-09-09_10-22-49.719159.tar.gz)

**Comment by sm1ck** [comment]
And after 12h work new docker container was crashed.
Dedicated server hardware/software:
- Intel Core i7-4770
- 2x HDD SATA 2,0 TB Enterprise
- 4x RAM 8192 MB DDR3
- Linux Debian-913-stretch-64-minimal 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 GNU/Linux

Also just attach crash report and latest log message:
`2020-09-09 20:09:06 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: "(monitor.ml.Error\n  (Failure\n    \"Failed to apply transiton frontier diffs to persistent database correctly: target hash was 57191d662e216ab48a91f9403f676aab63b3e4b6cefe063ea3973fb9faa1f5da, resulting hash was 3061fafd725636199ca68a73e5717ceac651a1dabdf93b79fa3103e36951ce76\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"
2020-09-09 20:09:06 UTC [Info] would have validated but it's from us!`
[coda_crash_report_2020-09-09_20-09-06.744206.tar.gz](https://github.com/CodaProtocol/coda/files/5200584/coda_crash_report_2020-09-09_20-09-06.744206.tar.gz)

**Comment by garethtdavies** [comment]
This was duplicated here by NNoperator#3835 https://discordapp.com/channels/484437221055922177/583400552487059546/754179615953649747

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
