### ISSUE TITLE
Implement the more complex stake threshold function

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#591]
If `a` is the relative stake of an account, the ouroboros paper has the holder of that account win a slot with probability `p(a) = 1- (1-f)^a`. The reason they do this is so that if `a = sum_i a_i` then

```
1 - p(a) = prod_i (1 - p(a_i))
```
so it doesn't matter if stake is split amongst many accounts or concentrated in one account. This is because the LHS is the probability of losing with all `a` stake in one account while the RHS is the probability of losing with the stake split amongst many accounts.

We probably want the property that `1 - p(a) <= prod_i (1 - p(a_i))`. One way of interpreting this would be that you don't gain any advantage by splitting your stake up into multiple accounts. Unfortunately, this also says that a group of people voting together with stake `a` do worse than one person with stake `a`. 

For now we chose to implement the threshold function `p(a) = a`, because it is easier and satisfies that inequality (strictly) but it would be better to implement the other function as it is less biased toward large stake-holders.

**Comment by enolan** [comment]
Spotted this today. I was all ready to call Nathan out. It's worth noting that under the current implementation the probability of a given slot having at least one eligible leader is a function of the stake distribution where in the paper's version it's fixed at `f`. There's an asymptote at `(1-e)/e` though, so it doesn't go to zero thankfully.

**Comment by cmr** [comment]
https://github.com/CodaProtocol/coda/pull/1855

**Comment by enolan** [comment]
The new threshold function is in, but there is a hack in there to double
the probability which should be removed, and we need to figure out what to
set f to and how to deal with ties.
