### ISSUE TITLE
Coda Daemon crashed

### ISSUE THREAD

**Issue by everuner** [MinaProtocol/mina#5927]
![Screenshot_17](https://user-images.githubusercontent.com/47457161/93015237-7b564a00-f5c0-11ea-9db2-9d6ea333f305.png)

2020-09-13 05:47:49 UTC [Info] Producing block in 0 slots
2020-09-13 05:47:49 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error\n  (Failure\n    \"Failed to apply transiton frontier diffs to persistent database correctly: target hash was 777775fa5615b44143b5b5ba56f15893dc03140c95c57789514b41242b22b5e0, resulting hash was b6e1645e5e028b2e83f98ecee30b6c6b05d9a9f6b524d26abd32c92f25c59afe\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"
2020-09-13 05:47:49 UTC [Info] would have validated but it's from us!

  ☠  Coda Daemon crashed.
   The Coda Protocol developers would like to know why!

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
