### ISSUE TITLE
GraphQL does not indicate transaction failure

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#5960]
When sending a token transaction without creating an account first for the receiver, the archive node reports this as a status of `failed` and a `failure_reason` of `Cannot_pay_creation_fee_in_token`. 

However, as the GraphQL `newBlock` subscription endpoint does not include the `failed` status (unless I'm missing something obvious) it looks like a normal transaction. Is it possible to determine that this transaction has failed from GraphQL?

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
