### ISSUE TITLE
Posix CLI parameters

### ISSUE THREAD

**Issue by mobileink** [MinaProtocol/mina#5962]
Most CLI programs these days use POSIX conventions with GNU long options (double hyphen).  Long options with a single hyphen are an annoyance - e.g. `coda client --help` fails, and I routinely use '--help' on the command line.

Strong recommendation is to use double hyphens for all long options.  POSIX options (single hyphen, single char) would also be nice to have.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
