### ISSUE TITLE
Crash Coda Daemon Testnet 3.3

### ISSUE THREAD

**Issue by Montiipilat** [MinaProtocol/mina#5968]
I used guide for stard testnet Coda 3.3 https://icohigh.gitbook.io/coda-node-testnet/russian/varianty-zapuska-nody/zapusk-coda-s-docker  and used command for Alternative log output (3.1):
 sudo docker exec coda coda client status | grep "Block producers"

Generating crash report
exn: "(monitor.ml.Error Incorrect_password_or_corrupted_privkey\n  (\"Raised at file \\\"src/error.ml\\\" (inlined), line 9, characters 14-30\"\n    \"Called from file \\\"src/lib/secrets/privkey_error.ml\\\", line 23, characters 14-57\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"
+ echo 'Coda process exited with status code 1'
+ sleep 10
Coda process exited with status code 1

**Comment by garethtdavies** [comment]
@Montiipilat the guide hasn't been updated to use the image for 3.3 yet (as not yet released) so it is using an old image and trying to import a new key format. You'll have to wait until the current testnet is active.

**Comment by Montiipilat** [comment]
Thanks! I also understood why it doesn't work, SEED1 and SEED2 didn't come to my email, and I probably wasn't included in the list of participants

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
