### ISSUE TITLE
mac build lacks libp2p_helper?

### ISSUE THREAD

**Issue by edsphinx** [MinaProtocol/mina#5979]
I trying to run the Coda Daemon on:
Macbook Pro with macOS 10.15.4
I installed with brew the latest version, and got in the console the error:
[Fatal] Could not retrieve genesis ledger and genesis proof from paths $paths
paths: "https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz,/tmp/coda_cache_dir,/var/lib/coda,/usr/local/var/coda,/tmp/s3_cache_dir"

.coda-config/coda.log content:

{"timestamp":"2020-09-17 04:32:55.325613Z","level":"Info","source":{"module":"Coda","location":"File \"src/app/cli/src/coda.ml\", line 272, characters 49-56"},"message":"Coda daemon is booting up; built with commit $commit on branch $branch","metadata":{"branch":"mac-bump-brew-deps","commit":"ef22dae964e2b7323ad578cfabc1e8040c9aec29","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.326145Z","level":"Info","source":{"module":"Coda","location":"File \"src/app/cli/src/coda.ml\", line 279, characters 51-58"},"message":"Daemon will expire at $exp","metadata":{"exp":"2024-12-10 14:00:00-07:00","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.326205Z","level":"Info","source":{"module":"Coda","location":"File \"src/app/cli/src/coda.ml\", line 294, characters 49-56"},"message":"Booting may take several seconds, please wait","metadata":{"pid":22346}}
{"timestamp":"2020-09-17 04:32:55.331165Z","level":"Debug","source":{"module":"Memory_stats","location":"File \"src/lib/memory_stats/memory_stats.ml\", line 43, characters 57-64"},"message":"OCaml memory statistics, before major gc","metadata":{"heap_chunks":13,"heap_size":21090304,"live_blocks":562834,"live_size":16853152,"max_heap_size":21090304,"pid":22346,"process":"daemon"}}
{"timestamp":"2020-09-17 04:32:55.331386Z","level":"Debug","source":{"module":"Memory_stats","location":"File \"src/lib/memory_stats/memory_stats.ml\", line 55, characters 57-64"},"message":"Jemalloc memory statistics (in bytes)","metadata":{"active":56303616,"allocated":55784360,"mapped":67661824,"pid":22346,"process":"daemon","resident":60850176}}
{"timestamp":"2020-09-17 04:32:55.338196Z","level":"Debug","source":{"module":"Memory_stats","location":"File \"src/lib/memory_stats/memory_stats.ml\", line 43, characters 57-64"},"message":"OCaml memory statistics, after major gc","metadata":{"heap_chunks":13,"heap_size":21090304,"live_blocks":571903,"live_size":17207464,"max_heap_size":21090304,"pid":22346,"process":"daemon"}}
{"timestamp":"2020-09-17 04:32:55.338265Z","level":"Debug","source":{"module":"Memory_stats","location":"File \"src/lib/memory_stats/memory_stats.ml\", line 55, characters 57-64"},"message":"Jemalloc memory statistics (in bytes)","metadata":{"active":56303616,"allocated":55784360,"mapped":67661824,"pid":22346,"process":"daemon","resident":60850176}}
{"timestamp":"2020-09-17 04:32:55.338332Z","level":"Info","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 211, characters 51-58"},"message":"Looking for the genesis tar file $filename","metadata":{"filename":"coda_genesis_ef22dae9_5e70c20db27df299.tar.gz","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.338380Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 240, characters 47-54"},"message":"Retrieving genesis ledger and genesis proof from $path","metadata":{"path":"/tmp/coda_cache_dir","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.345506Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 235, characters 51-58"},"message":"Error extracting genesis ledger and proof : $error","metadata":{"error":"Error extracting tar file /tmp/coda_cache_dir/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz. (\"Process.run failed\"\n ((prog tar)\n  (args\n   (-C /Users/fonseca/.coda-config -xzf\n    /tmp/coda_cache_dir/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz))\n  (exit_status (Exit_non_zero 1)) (stdout \"\")\n  (stderr\n   (\"tar: Error opening archive: Failed to open '/tmp/coda_cache_dir/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz'\"\n    \"\"))))","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.345592Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 291, characters 49-56"},"message":"Error retrieving genesis ledger and genesis proof from $path","metadata":{"path":"/tmp/coda_cache_dir","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.345635Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 240, characters 47-54"},"message":"Retrieving genesis ledger and genesis proof from $path","metadata":{"path":"/var/lib/coda","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.350270Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 235, characters 51-58"},"message":"Error extracting genesis ledger and proof : $error","metadata":{"error":"Error extracting tar file /var/lib/coda/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz. (\"Process.run failed\"\n ((prog tar)\n  (args\n   (-C /Users/fonseca/.coda-config -xzf\n    /var/lib/coda/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz))\n  (exit_status (Exit_non_zero 1)) (stdout \"\")\n  (stderr\n   (\"tar: Error opening archive: Failed to open '/var/lib/coda/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz'\"\n    \"\"))))","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.350346Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 291, characters 49-56"},"message":"Error retrieving genesis ledger and genesis proof from $path","metadata":{"path":"/var/lib/coda","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.350365Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 240, characters 47-54"},"message":"Retrieving genesis ledger and genesis proof from $path","metadata":{"path":"/usr/local/var/coda","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.354361Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 235, characters 51-58"},"message":"Error extracting genesis ledger and proof : $error","metadata":{"error":"Error extracting tar file /usr/local/var/coda/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz. (\"Process.run failed\"\n ((prog tar)\n  (args\n   (-C /Users/fonseca/.coda-config -xzf\n    /usr/local/var/coda/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz))\n  (exit_status (Exit_non_zero 1)) (stdout \"\")\n  (stderr\n   (\"tar: Error opening archive: Failed to open '/usr/local/var/coda/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz'\"\n    \"\"))))","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.354407Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 291, characters 49-56"},"message":"Error retrieving genesis ledger and genesis proof from $path","metadata":{"path":"/usr/local/var/coda","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.354423Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 240, characters 47-54"},"message":"Retrieving genesis ledger and genesis proof from $path","metadata":{"path":"/tmp/s3_cache_dir","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.358757Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 235, characters 51-58"},"message":"Error extracting genesis ledger and proof : $error","metadata":{"error":"Error extracting tar file /tmp/s3_cache_dir/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz. (\"Process.run failed\"\n ((prog tar)\n  (args\n   (-C /Users/fonseca/.coda-config -xzf\n    /tmp/s3_cache_dir/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz))\n  (exit_status (Exit_non_zero 1)) (stdout \"\")\n  (stderr\n   (\"tar: Error opening archive: Failed to open '/tmp/s3_cache_dir/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz'\"\n    \"\"))))","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.358841Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 291, characters 49-56"},"message":"Error retrieving genesis ledger and genesis proof from $path","metadata":{"path":"/tmp/s3_cache_dir","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.976516Z","level":"Fatal","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 346, characters 59-66"},"message":"Could not curl genesis ledger and genesis proof from $uri: $error","metadata":{"error":"(monitor.ml.Error\n (\"Process.run failed\"\n  ((prog curl)\n   (args\n    (-o /tmp/s3_cache_dir/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz\n     https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz))\n   (exit_status (Exit_non_zero 23)) (stdout \"\")\n   (stderr\n    (\"  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\"\n     \"                                 Dload  Upload   Total   Spent    Left  Speed\"\n     \"\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\\r  0 5177k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file \"\n     \"Warning: /tmp/s3_cache_dir/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz: No \"\n     \"Warning: such file or directory\"\n     \"\\r  0 5177k    0 16360    0     0  27086      0  0:03:15 --:--:--  0:03:15 27041\"\n     \"curl: (23) Failed writing body (0 != 16360)\" \"\"))))\n (\"Raised at file \\\"src/error.ml\\\" (inlined), line 9, characters 14-30\"\n  \"Called from file \\\"src/or_error.ml\\\", line 72, characters 17-32\"\n  \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n  \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n  \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"))","pid":22346,"uri":"https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz"}}
{"timestamp":"2020-09-17 04:32:55.976797Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 240, characters 47-54"},"message":"Retrieving genesis ledger and genesis proof from $path","metadata":{"path":"/tmp/s3_cache_dir","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.982418Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 235, characters 51-58"},"message":"Error extracting genesis ledger and proof : $error","metadata":{"error":"Error extracting tar file /tmp/s3_cache_dir/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz. (\"Process.run failed\"\n ((prog tar)\n  (args\n   (-C /Users/fonseca/.coda-config -xzf\n    /tmp/s3_cache_dir/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz))\n  (exit_status (Exit_non_zero 1)) (stdout \"\")\n  (stderr\n   (\"tar: Error opening archive: Failed to open '/tmp/s3_cache_dir/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz'\"\n    \"\"))))","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.982485Z","level":"Debug","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 291, characters 49-56"},"message":"Error retrieving genesis ledger and genesis proof from $path","metadata":{"path":"/tmp/s3_cache_dir","pid":22346}}
{"timestamp":"2020-09-17 04:32:55.982503Z","level":"Fatal","source":{"module":"Genesis_ledger_helper","location":"File \"src/lib/genesis_ledger_helper/genesis_ledger_helper.ml\", line 307, characters 51-58"},"message":"Could not retrieve genesis ledger and genesis proof from paths $paths","metadata":{"paths":"https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/coda_genesis_ef22dae9_5e70c20db27df299.tar.gz,/tmp/coda_cache_dir,/var/lib/coda,/usr/local/var/coda,/tmp/s3_cache_dir","pid":22346}}

**Comment by edsphinx** [comment]
I was able to solve this initial problem deleting everything and installing again, I noticed that this install was using the branch "mac-bump-brew-deps" and now with fresh install is using the master branch and started to work fine but crashed and generated a crash report, with the error:

2020-09-17 05:07:29 UTC [Info] Setting current protocol version to "0.1.0" from compile-time config
2020-09-17 05:18:48 UTC [Info] Daemon started process of kind "Prover" with pid 27301
2020-09-17 05:18:48 UTC [Error] Prover stderr: $stderr

2020-09-17 05:18:49 UTC [Info] Daemon started process of kind "Verifier" with pid 27766
2020-09-17 05:18:49 UTC [Info] Registering async shutdown handler: "Close transition frontier, if exists"
2020-09-17 05:18:49 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: "(monitor.ml.Error\n  (Failure\n     \"Failed to connect to libp2p_helper process: Could not start libp2p_helper. If you are a dev, did you forget to `make libp2p_helper` and set CODA_LIBP2P_HELPER_PATH? Try CODA_LIBP2P_HELPER_PATH=$PWD/src/app/libp2p_helper/result/bin/libp2p_helper (Unix.Unix_error \\\"No such file or directory\\\" Core.Unix.create_process\\\n    \\n \\\"((prog coda-libp2p_helper) (args ()) (env (Extend ())))\\\")\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))

Crash report generated:
[coda_crash_report_2020-09-17_05-18-49.470332.tar.gz](https://github.com/CodaProtocol/coda/files/5236524/coda_crash_report_2020-09-17_05-18-49.470332.tar.gz)

**Comment by edsphinx** [comment]
I tried adding daemon.json from https://github.com/CodaProtocol/coda/blob/master/genesis_ledgers/phase_three/config.json and run again, but crashed one more time and uploading latest crash report
[coda_crash_report_2020-09-17_05-46-48.036529.tar.gz](https://github.com/CodaProtocol/coda/files/5236617/coda_crash_report_2020-09-17_05-46-48.036529.tar.gz)

**Comment by dguess** [comment]
I am also getting the same issue - Macbook Pro with macOS 10.15.2

> "Failed to connect to libp2p_helper process: Could not start libp2p_helper. If you are a dev, did you forget to `make libp2p_helper` and set CODA_LIBP2P_HELPER_PATH? Try CODA_LIBP2P_HELPER_PATH=$PWD/src/app/libp2p_helper/result/bin/libp2p_helper (Unix.Unix_error \\\"No such file or directory\\\"

**Comment by lyoungblood** [comment]
I have this same issue.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
