### ISSUE TITLE
Coda daemon crash

### ISSUE THREAD

**Issue by jihwan97-hash** [MinaProtocol/mina#5980]
<img width="1440" alt="스크린샷 2020-09-17 오후 1 40 30" src="https://user-images.githubusercontent.com/71423307/93421069-5bd65e80-f8eb-11ea-8b85-66ea2d154980.png">

I had problem starting coda daemon, it keeps crashing :(
In Start up a node section, I tried the code with the seed quote I got from email.
The code is this
 coda daemon -peer /dns4/pickles.o1test.net/tcp/10001/p2p/12D3KooWAFFq2yEQFFzhU5dt64AWqawRuomG9hL8rSmm5vxhAsgr

**Comment by garethtdavies** [comment]
@jihwan97-hash you already have something listening on port `3085`. Whatever it is (`lsof -i tcp:[3085]`, kill it and then try again

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
