### ISSUE TITLE
Minted tokens' number is not match the original input if the number is huge

### ISSUE THREAD

**Issue by crackerli** [MinaProtocol/mina#5986]
How to produce:
1. set the minted token number to be very huge.
coda client mint-tokens -sender $PUBLIC_KEY -token 9 -amount 100000000000000

2. After some minutes, run command to check the result:
coda client get-balance -token 9 -public-key $PUBLIC_KEY

ouput: Balance: 18446744073.709551615 tokens

![image](https://user-images.githubusercontent.com/10629416/93453064-c6979200-f90b-11ea-9a8a-b8eb8cd2e1d9.png)

3. If set the minted token to low, 10000 for example, the command produce the right result

**Comment by garethtdavies** [comment]
This is because it is limited to 2^64 -1 which is 18446744073709551615.

**Comment by crackerli** [comment]
Thank you, garethtdavies, maybe we can supply some prompt string to user?

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
