### ISSUE TITLE
Crash report - Snark worker process died with a nonzero error

### ISSUE THREAD

**Issue by LexPrime** [MinaProtocol/mina#5988]
For two hours a snark worker in docker image worked normally and issued the snark jobs and then began to crash with an error
![coda crash2 2020-09-17 102535](https://user-images.githubusercontent.com/17300737/93468888-5af7f980-f8f8-11ea-8f91-73092042c3d8.png)
[coda-crash-report.tar.gz](https://github.com/CodaProtocol/coda/files/5239030/coda-crash-report.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
