### ISSUE TITLE
The transaction disappeared if the fee is too low

### ISSUE THREAD

**Issue by crackerli** [MinaProtocol/mina#5989]
I have not reproduced it, it happened to me once.

Steps to produce:

1. start a transaction with low fee, 0.1 or lower, remember the payment id.
2. the transaction did not show in explorer, but with 'coda advanced pooled-user-commands | grep payment id', the payment id can be grep out.
3. Wait for some time, re-execute 'coda advanced pooled-user-commands | grep payment id', the payment id can not grep out anymore.
4. Check in the explorer, no transaction recorded, and the balance of sender and receiver did not change.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
