### ISSUE TITLE
Peer lists are not growing as they should and seem to only contain the o1 k8s nodes

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#6000]
The current testnet is improperly peering, everyone seems to peer only with our kubernetes nodes.

**Comment by 0x0I** [comment]
Hmmm...with visibility/observability in mind in regards to this, just wondering how much effort is needed to fix the **Coda_Net_seed_peers** metric (and maybe add an ordered, perhaps comma-separated list of peers as a tag).

**Comment by emberian** [comment]
Still trying to reproduce this. I was able to manually peer with some testnet participants, but it doesn't seem that this extended to my own peer list growing beyond those few `-peer` arguments. However I also discovered that some of the participant nodes are not actually reachable on their libp2p ports, for example one in Digital Ocean was unreachable.

**Comment by Cris-F** [comment]
fyi, I was able to peer to another node I had running yesterday.
