### ISSUE TITLE
SNARK Coordinator Crashing loses completed snark work

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#6002]
?) Is this causing empty blocks?

**Comment by 0x0I** [comment]
Possible to attach crash log/error?

**Comment by emberian** [comment]
Implementing https://github.com/CodaProtocol/coda/issues/3044 would have this be less of an issue.

**Comment by mrmr1993** [comment]
Snark pool persistence [is implemented](https://github.com/MinaProtocol/mina/blob/19d731785fa81f405525e129c23ce590c33cb557/src/lib/network_pool/snark_pool.ml#L533). Closing.
