### ISSUE TITLE
Testnet 3.3 : Coda metric's peer value is always zero.

### ISSUE THREAD

**Issue by jongkwang** [MinaProtocol/mina#6022]
## Version
- Testnet 3.3

## Coda Metrics
- My Metrics : http://34.64.106.211:6060/metrics

## Problem
- The metric's <code>Coda_Network_peers</code> is always zero. (I checked for 12 hours, but it was always zero.)
- But, <code>coda client status</code> display as 4.

## Screenshot
![스크린샷_2020-09-18_오전_11_45_49](https://user-images.githubusercontent.com/897510/93550122-b8964f80-f9a5-11ea-86e0-2e2cea4e8ad8.png)

**Comment by garethtdavies** [comment]
I can replicate this. Here it is in Prometheus.

<img width="1908" alt="CleanShot 2020-09-18 at 11 29 35@2x" src="https://user-images.githubusercontent.com/135382/93632512-4b34ef80-f9a2-11ea-97ec-878894fa7a35.png">

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
