### ISSUE TITLE
Crashing report - Testnet 3.3 - Start block producing - alexvanguet#4878

### ISSUE THREAD

**Issue by greencicle** [MinaProtocol/mina#6026]
Start block producing

coda daemon \
-peer $SEED1 \
-block-producer-pubkey $CODA_PUBLIC_KEY

[coda_crash_report_2020-09-18_13-03-57.495972.tar.gz](https://github.com/CodaProtocol/coda/files/5245689/coda_crash_report_2020-09-18_13-03-57.495972.tar.gz)

**Comment by garethtdavies** [comment]
@greencicle the relevant line from the crash is here:

```
Cannot open file: /root/.coda-config/wallets/store/B62qknuf42eB65EdAaRiCuZhhUoSEeKrVavVg4CGMPhaJeez2Bqigsn\
```

So, the key hasn't been imported. It's probably a better idea to start a block producer like this, where you pass the location of the private key (update to match your system), as this will save you the step of importing.

```
coda daemon \
-background \
-peer $SEED1 \
-block-producer-key /root/keys/my-wallet
```

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
