### ISSUE TITLE
Configuration protocol inventory

### ISSUE THREAD

**Issue by mobileink** [MinaProtocol/mina#6030]
It would be useful to have a complete list of:

- environment variables
- config files
- build-time parameters
- runtime data file dependencies
- etc.

Basically, anything involved in build-/compile-/run-time configuration.  Such a list would be very useful for

- ensuring the Bazel build covers all the bases
- ensuring the manpages are complete
- general QA

Here's what I have so far:

Env. vars.  Which of these are used by the daemon, and which only by CLI tools?

- CODA_PRIVKEY_PASS - used by some CLI commands
- CODA_CONFIG_FILE - default:  <config_dir>/daemon.json
- OMP_NUM_THREADS - number of threads to use for snark workers
- RAYON_NUM_THREADS - ???  (Surely this should be RAYON_THREAD_COUNT - fabric, get it?)

Config files:
- config dir:  ~/.coda-config, overridable by CLI arg, no env var?
- config file:  <config_dir>/daemon.json, overridable by CLI arg, env var CODA_CONFIG_FILE (daemon?)

Runtime file dependencies:

- genesis ledger dir default: <config_dir>, overrideable by CLI arg. Env var?
- genesis ledger file - ?
- genesis block?
- etc.

Buildtime params

- config.h macros
  -- account_creation_fee_int
  -- default_transaction_fee
  -- default_snark_worker_fee
  -- minimum_user_command_fee
  -- etc (from src/config)

Comm config:

- Graphql rest server addr default:  http://localhost:3085/graphql (CLI param -rest-server should be renamed to -graphql-addr?)
-  local RPC server port default: 8301.  Overrideable by CLI arg; how is it set at compile time? env var?
-  libp2p port default: 8302.  Overrideable by CLI arg; how set at compile time? env. var?
- `-rest-port` - port on local REST-server for daemon interaction, default 3085 (coda daemon param)

Logging:

- log output format default plaintext, overrideable by CLI arg, no env. var
- log level default Info, overrideable by CLI arg, no env. var.
- log received blocks default false, overrideable by CLI, no env. var
- log txn pool gossip default false, overrideable by CLI, no env. var
- log snark work gossip default false
- tracing output file default <config_dir>/$pid.trace

Other:  etc.

I can go through the CLI help screens to get a list of stuff, but if anybody can add info on env. vars and the rest that would be helpful.

Related #6013

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
