### ISSUE TITLE
Daemon crash on startup, first time with config in daemon.json instead of commandline

### ISSUE THREAD

**Issue by byrongibson** [MinaProtocol/mina#6044]
Hi all, just going through the setup instructions.  I got coda daemon working with no trouble by calling the daemon plus config flags from the commandline, specifically:

```
coda daemon \
    -peer $SEED1 \
    -block-producer-pubkey $CODA_PUBLIC_KEY
```

That works reliably.

However, when I move the commandline flags to daemon.json and run "coda daemon" it crashes on startup.  I copy-pasted the daemon.json file from the docs:  https://codaprotocol.com/docs/node-operator

I tried several versions of daemon.json:

- block producer enabled, run-snark-worker enabled, and log-block-creation logging enabled (no other logging enabled), using "peers": ["seed-one.o1test.net", "seed-two.o1test.net"]

- with block producer enabled, snark-worker disabled (commented out), log-block-creation disabled (all other logging also disabled), using "peers": ["seed-one.o1test.net", "seed-two.o1test.net"]

- with block producer enabled, snark-worker disabled, all logging disabled, and "peer": "/dns4/pickles.o1test.net/tcp/10001/p2p/12D3KooWAFFq2yEQFFzhU5dt64AWqawRuomG9hL8rSmm5vxhAsgr"

- with block producer enabled, snark-worker disabled, all logging disabled, all port specifications disabled, and "peer": "/dns4/pickles.o1test.net/tcp/10001/p2p/12D3KooWAFFq2yEQFFzhU5dt64AWqawRuomG9hL8rSmm5vxhAsgr"

All fail, client crashes.  Error report attached.

[coda_crash_report_2020-09-18_23-29-26.301636.tar.gz](https://github.com/CodaProtocol/coda/files/5248659/coda_crash_report_2020-09-18_23-29-26.301636.tar.gz)

**Comment by emberian** [comment]
@byrongibson that daemon.json is completely invalid, comments are not permitted in json.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
