### ISSUE TITLE
Slightly useful docstrings?

### ISSUE THREAD

**Issue by mobileink** [MinaProtocol/mina#6045]
The help screens are borderline useless. Trying to figure out what the CLI commands and parameters actually mean is a huge and completely unnecessary time suck - many of the issues arising in the discord channels would be completely eliminated if the help screens were clear.

**Comment by emberian** [comment]
:+1: I wonder if we can (partially?) generate this from the graphql descriptions.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
