### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by mobileink** [MinaProtocol/mina#6047]
Lots of user-exposed docstrings scattered about the source.  Since Coda is intended for worldwide domination, er. deployment, it would be good to internationalize these.  [ocaml-gettext](https://github.com/gildor478/ocaml-gettext) looks promising.

Issue #6045 could be partially addressed simultaneously.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
