### ISSUE TITLE
daemon crash Boston Mike#0643

### ISSUE THREAD

**Issue by BostonMike0643** [MinaProtocol/mina#6052]
home/mike/ .coda-config/coda_crash_report_2020-09-19_21-07-34.610023.tar.gz

my node was running essesntially non stop (alternating between catchup and sync)most of the day.    Just came back to check on it and saw it had crashed.

**Comment by garethtdavies** [comment]
Can you add the crash log?

**Comment by BostonMike0643** [comment]
![image](https://user-images.githubusercontent.com/71574080/93714647-cffe4580-fb29-11ea-800c-8cdca36c4339.png)

**Comment by BostonMike0643** [comment]
says access denied (note this is from the most recent crash as it crashed again)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
