### ISSUE TITLE
coda crash

### ISSUE THREAD

**Issue by bonsfi** [MinaProtocol/mina#6056]
just validating normally and crash happened.
discord user:bonsfi#5752
[coda_crash_report_2020-09-19_23-32-56.902568.tar.gz](https://github.com/CodaProtocol/coda/files/5251367/coda_crash_report_2020-09-19_23-32-56.902568.tar.gz)

**Comment by garethtdavies** [comment]
`write to closed pipe` which is #6049

**Comment by mrmr1993** [comment]
Closing, this was fixed in #6357.
