### ISSUE TITLE
Daemon crach on GCP

### ISSUE THREAD

**Issue by clayop** [MinaProtocol/mina#6057]
Instance: GCP c2-standard-4 (Cascade Lake)
OS: Ubuntu 18.04.5 LTS

Followed `Getting Started` and `My First Transaction` pages. Opened 8202, 8203 TCP ports, both ingress and engress.

When run `coda daemon -peer $SEED1` I got this error as attached.

[coda_crash_report_2020-09-20_09-31-51.964221.tar.gz](https://github.com/CodaProtocol/coda/files/5251398/coda_crash_report_2020-09-20_09-31-51.964221.tar.gz)

**Comment by garethtdavies** [comment]
`rpc_error (Connection_closed (\"EOF or connection closed\")` which was tracked via #6001

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
