### ISSUE TITLE
Daemon Crash Report

### ISSUE THREAD

**Issue by oknerasinSD** [MinaProtocol/mina#6058]
- Configuration: GCP c2-standard-8 (8 CPU, 32 GB RAM).
- Block Producer and Snark Worker are launched on the same machine.
- Using a script for stopping Snark Worker 3 minutes before producing a new block and running it again 10 minutes after. The script and Coda Daemon work in different tmux sessions.

Report:
[coda_crash_report_2020-09-20_05-56-52.900857.tar.gz](https://github.com/CodaProtocol/coda/files/5251400/coda_crash_report_2020-09-20_05-56-52.900857.tar.gz)

Discord username: Denis S#7360

**Comment by garethtdavies** [comment]
`write to closed pipe` see #6049

**Comment by mrmr1993** [comment]
Closing, this was fixed in #6357.
