### ISSUE TITLE
YieldWallet-Gautam#4458: Coda daemon crashes after running for about 35-40 minutes. Attached crash log

### ISSUE THREAD

**Issue by gsampathkumar** [MinaProtocol/mina#6059]
[coda_crash_report_2020-09-20_09-35-42.361085.tar.gz](https://github.com/CodaProtocol/coda/files/5251431/coda_crash_report_2020-09-20_09-35-42.361085.tar.gz)

**Comment by garethtdavies** [comment]
`write to closed pipe` see #6049

**Comment by mrmr1993** [comment]
Closing, this was fixed in #6357.
