### ISSUE TITLE
Daemon crash report

### ISSUE THREAD

**Issue by Syd-ai** [MinaProtocol/mina#6060]
Hello,

Here's my crash report

Syd#9907

[coda_crash_report_2020-09-17_12-40-45.357405.tar.gz](https://github.com/CodaProtocol/coda/files/5251701/coda_crash_report_2020-09-17_12-40-45.357405.tar.gz)

**Comment by garethtdavies** [comment]
@Syd-ai `got EOF while reading password`. This means it couldn't read the password for the wallet. You can set this via an environment variable of `CODA_PRIVKEY_PASS`.

**Comment by mrmr1993** [comment]
We've updated the handling of these errors, what has gone wrong and the way to fix it should now be clearer. Closing.
