### ISSUE TITLE
Daemon is crashed.

### ISSUE THREAD

**Issue by StarLI-Trapdoor** [MinaProtocol/mina#6061]
[coda_crash_report_2020-09-19_20-31-02.018917.tar.gz](https://github.com/CodaProtocol/coda/files/5252085/coda_crash_report_2020-09-19_20-31-02.018917.tar.gz)

**Comment by garethtdavies** [comment]
Another `write to closed pipe` error see #6049

**Comment by mrmr1993** [comment]
Closing, this was fixed in #6357.
