### ISSUE TITLE
"coda client" command to add a new peer - Feature Request

### ISSUE THREAD

**Issue by Cris-F** [MinaProtocol/mina#6064]
Having to restart to add a new peer is cumbersome and causing downtime.
Request feature to add peers in "coda client".
"add-peer" would provide great benefit to the network as a standard feature.

**Comment by koen84** [comment]
Agreed, this would help to resolve connection issues by manually adding a peer.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
