### ISSUE TITLE
doc suggestion - ports, 8303 removed if obsolete, 8301 has security note

### ISSUE THREAD

**Issue by Cris-F** [MinaProtocol/mina#6065]
Suggest removing 8303 from docs if it isn't being used.  Causing confusion among new users when they see 8302 & 8303 to be allowed but 8302 and 8301 in output of `coda client status`, with no mention of 8303.

Suggest adding note about not opening 8301 without fully understanding the security implications. Questions raised in Discord about this.  Likely many more haven't asked and opened this port.

CrisF#3405

**Comment by garethtdavies** [comment]
Related to https://github.com/CodaProtocol/coda/issues/5461

**Comment by Cris-F** [comment]
Thanks, should have checked.

**Comment by 5325833510** [comment]
Fatma

**Comment by 5325833510** [comment]
> Thanks, should have checked.

Alooo

**Comment by 5325833510** [comment]
Fatma

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
