### ISSUE TITLE
doc suggestion - security - new users running as root (non-docker), basic server issues

### ISSUE THREAD

**Issue by Cris-F** [MinaProtocol/mina#6066]
Suggest adding info on, or refer to basic server setup info. (eg, https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-18-04) (various OSes)
There have been cases of new testnet user are running Coda as root on linux (non-docker), likely not aware of the security implications. 
Basic server setup info or `Create new user account` may be enough to minimize this.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
