### ISSUE TITLE
Coda Daemon crashed

### ISSUE THREAD

**Issue by ncsolar** [MinaProtocol/mina#6067]
Crash when starting, running:  coda daemon -peer $SEED1
Version:  Commit 4395e91 on branch master

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Comment by garethtdavies** [comment]
Can you add the crash log @ncsolar

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
