### ISSUE TITLE
Configuration Model

### ISSUE THREAD

**Issue by mobileink** [MinaProtocol/mina#6073]
Currently Coda embeds conditional compilation logic using PPX mechanisms.

For example: src/lib/consensus/consensus.ml:

```
[%%import
"/src/config.mlh"]
module Intf = Intf
[%%if
consensus_mechanism = "proof_of_stake"]
include Proof_of_stake
[%%else]
[%%show
consesus_mechanism]
[%%error
"invalid value for \"consensus_mechanism\""]
[%%endif]
module Proof_of_stake = Proof_of_stake
```

Bazel allows us to eliminate much of this, or rather to move it out of program logic and into build logic, which (IMO) is where it belongs.  In this example, consensus.ml could look like this:

```
module Intf = Intf
include Proof_of_stake
module Proof_of_stake = Proof_of_stake
```

The build logic would compile this only if `consensus_mechanism` - a build-time constant - were set to `proof_of_stake`.

A related example: src/lib/consensus/global_slot.mli, which contains:

```
[%%import "/src/config.mlh"]
...
[%%ifdef consensus_mechanism]
...some self-contained code defining module Checked...
[%%endif]
```

Here the conditional code could be moved to a module, say `global_slot_consensus.ml`.  The %ifdef would be replaced with `include global_slot_checked`. The build logic would generate `global_slot_checked.ml`, copying `global_slot_consensus.ml` if the build-time var `consensus_mechanism` is non-null, otherwise generating and compiling an empty file.

Completely eliminating `[%%ifdef consensus_mechanism]` in this manner would involve substantial effort, but would have the effect of expressing the consensus/nonconsensus structure of the code on the surface, in the organization of the files (and the build code) rather than the organization of OCaml code within the files.

Other uses of `%%ifdef` would be simpler.  In some cases, in which the conditional code is embedded in a complex expression, replacement may be less feasible.

Other PPX constructs can also be eliminated.  For example, src/lib/genesis_constants/genesis_constants.ml contains a bunch of `%%inject` directives.  They could easily be eliminated by having the build logic generate the file during the precompilation (bootstrap) phase of the build.  The result in this case would be simpler code, and possibly faster compilation, since the PPX processing step would be eliminated (albeit replaced with more bootstrap processing).

Also, where conditional logic is unavoidable, `config.mlh` could be replaced by a Configuration module generated by the build system.  So instead of `[%%ifdef foo ...]` we would have `if Configuration.foo` or something like that.  An optimizing compiler could presumably see that Configuration.foo is a constant and optimize out the conditional, but I don't know if the OCaml compiler could do that.

Related: #6013

**Comment by bkase** [comment]
Unrelatedly, we've been talking about trying to remove a lot of our conditional compilation anyway -- for example, at this point, we should just stick with Proof_of_stake as our one and only consensus mechanism.

**Comment by mrmr1993** [comment]
Now that we depend on `Snarky_base`, which has no native dependencies, we should change the checked modules into functors that take a snarky interface, and then that optcomp can be removed too.

**Comment by nholland94** [comment]
The compile config for selecting a consensus mechanism should probably just be removed now. It existed for historical reasons to remain abstract over consensus entirely, but as development progressed and we officially settled on our consensus mechanism, this is essentially a noop in our build configuration. Every build profile always to have this set to `proof_of_stake` for a successful build right now.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
