### ISSUE TITLE
Augment trace_task with monitors/exception handling

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#6083]
Right now many of our exceptions are reported without useful context. We already annotate many top-level asynchronous processes with `trace_task`. We should extend it to handle the exceptions via the `Monitor` API and include the task name. Non-scoped, unhandled top-level exceptions should become an error.

**Comment by shimkiv** [comment]
@deepthiskumar can you please make a proper assignment when time allows

**Comment by emberian** [comment]
this is done with Nathan's refactor
