### ISSUE TITLE
doc suggestion - add info about backing up 'password' in addition to keys

### ISSUE THREAD

**Issue by Cris-F** [MinaProtocol/mina#6092]
In addition to `IMPORTANT: Do not lose this file! You’ll need it again when you start your node when Phase 3.3 begins.` (https://forums.codaprotocol.com/t/testnet-beta-phase-3-staking-signups/225) suggest adding `"and password"` so it reads something like `IMPORTANT: Do not lose this file and password!` in all relevant docs.

There were cases in 3.3 of users not being able to participate in tech challenges due to not having the password they used to generate their keys.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
