### ISSUE TITLE
Standardize CLI Flags according to POSIX

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#6106]
POSIX spec for long and short command line options:

https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

**Comment by aneesharaines** [comment]
@figitaki how much work would this be, how much risk does it introduce and how much would we have to update in docs?

**Comment by figitaki** [comment]
I believe this is well worth doing before main net. The main risk here might actually come from the infrastructure lift of updating the flags we're passing into the daemon, however we've done lots of work to make these sorts of migrations easier so @lk86 might have some more context there.

In terms of engineering work I'd probably break it down as follows:

1. Approx. 1 week to update the flags format to be POSIX compatible.
2. Approx. 2 days to audit the docs and update instances of CLI flags.
3. Approx. 1 week to test and roll out changes to a public testnet (less hands on)

Of course these are rough estimates and I'd definitely need to understand the infrastructure implications better.

**Comment by aneesharaines** [comment]
Need a project plan of we want to take this fully, along w env var renames and exe renames, inc RFC and coordinating with partners and members this may break.

**Comment by aneesharaines** [comment]
A couple hours more to have if flushed out into a full plan.

**Comment by figitaki** [comment]
Please review the attached product plan https://www.notion.so/minaprotocol/CLI-Flag-Standardization-71860534547148e1bbc2db8079be00e2
