### ISSUE TITLE
Improperly running jobs on frontend changes

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#6117]
Slow backend jobs are triggered when only `frontend/` files were touched. See https://github.com/CodaProtocol/coda/pull/6114

<img width="1170" alt="Screen Shot 2020-09-23 at 10 28 20 PM" src="https://user-images.githubusercontent.com/515445/94060413-efa79f00-fdb1-11ea-8ee7-1466e81f2dc8.png">

**Comment by 0x0I** [comment]
Unable to access example branch though the triggered job list appears correct with a [replicated changeset](https://buildkite.com/o-1-labs-2/coda/builds?branch=frontend_change_bk_test) (note: Fast Lints run on [changes to everything](https://github.com/CodaProtocol/coda/blob/develop/buildkite/src/Jobs/Lint/Fast.dhall#L32)).

Observed buggy behavior could have been the result of testing on a separate branch like Release...?
