### ISSUE TITLE
Create health and readiness checks for all of our helm charts including archive node and bots 

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#6121]
- Define what are the checks first 

Automate validation of archive node + bots (even a script which needs to be manually invoked would suffice for now).

**Plan for Kubernetes Healthcheck Types:**
- `startup-probe` : similar use to *liveness checks* though used to measure container liveness during initialization
- `liveness`: verify container network accessibility on regular cadence (e.g. check Mina daemon is listening on its *libp2p/client* port every 30s)
- `readiness`: technically verifies container readiness for receiving traffic (e.g. daemon ready to be queried by public Mina testnetX daemon GraphQL DNS/endpoint) though intended/planned use is for measuring container synchronization with chain expectations

#### **Implementation Design:**
1. Leverage Helm's [Named Templates](https://helm.sh/docs/chart_template_guide/named_templates/) as it seems like an appropriate tool to use here based on the following:
    - enables single healthcheck definition and re-use throughout source chart and all others (external dependency charts, subcharts) within a Helm operation runtime
    - single and consistent source of truth for healthchecks throughout Mina's Helm charts in terms of location and naming conventions (e.g. `_healthchecks.tpl` located at */chart-path/templates/*)
    - allows for added variability in definitions with sane/common defaults as template embedded variables can be scoped to template rendering arguments.
    - template definitions can be and are recommended to be namespaced by source chart (though namespace collisions are handled with last to load taking precedence) 
2. Specify container port defaults within `values.yaml` with sane/common settings to allow for variability when necessary and DRY'er code.
3. Define and name all container ports (of interest) within container specifications so that checks can rely on this metadata rather than specific port numbers.

#### Helm Chart/Pod Healthcheck Ideas:
- `archive-node`
  - containers
    - daemon
       - ports: [ *client/libp2p* : 8301-83xx, *graphql* : 3085, *metrics* : 10000, *external* : xxxx/variable ]
       - startupProbe (*failureThreshold x periodSeconds for daemon to listen on libp2p port*):
         - **port**: client/libp2p
         - **protocol**: TCP
         - **failureThreshold**: 60
         - **periodSeconds**: 5
       - liveness:
         - **port**: client/libp2p
         - **protocol**: TCP
         < see **CommonCheckConfig template**>         
       - readiness:
         - **exec cmd**:
             - network status: `status=$(curl localhost:3085/graphql -d'{<sync-status-query>}'); [[ status == "synced" ]] && return 0 || return 1`
             - peer-count: script to check local daemon peer count against seed-nodes
         < see **CommonCheckConfig template**>
    - archive
       - ports: [ *archive-daemon* : 3086, *archive-postgres* : 5432 ]
       - startupProbe:
         - **port**: archive-postgres
         - **protocol**: TCP
         - **periodSeconds**: 5
         - **failureThreshold**: 60
       - liveness:
         - **port**: archive-daemon
         - **protocol**: TCP
         < see **CommonCheckConfig template**>
       - readiness:
         - **exec cmd**: `script to check archive observed blocks == daemon block height`, can store in archive-node image
         < see **CommonCheckConfig template**>
- `block-producer`
  - containers
    - daemon
       - **see archive-node :: daemon && think template re-use**
    - user-agent
       - ports: [ *metrics* : 8000 ]
       - startupProbe:
         - < **see block-producer :: daemon** >
       - liveness:
         - **port**: metrics
         - **protocol**: TCP
         < see **CommonCheckConfig template**>         
       - readiness:
         - **exec cmd**:
             - agent_sent_txns: `curl localhost:8000/metrics | check-count-against-graphql`
    - bots (faucet + echo SVCs)
       - ports: [ *graphql* : 3085 ]
       - startupProbe:
         - < **see block-producer :: daemon** >
       - liveness:
         - **port**: graphql
         - **protocol**: TCP
         < see **CommonCheckConfig template**>         
       - readiness:
         - **exec cmd**:
             - faucet-balance: `CMD == balance > 0/??`
- `seed-node`
  - containers
    - daemon
      - **see archive :: daemon**
- `snark-worker`
  - containers
    - daemon/coordinator
    - snark-worker
- `o1-bot`
  - containers
    - bot
      - due to variability of container application, either:
         - allow specification of startup, liveness and readiness checks as variables (similar to how other resources - e.g. ports, volumes - are specified)
         - define named template which allows all or a set of checks to be rendered based on input scope/variables
         - provide single exec check CMD to be customized by applications
- `leaderboard`
  - containers
    - leaderboard [cronjob]
      - ports: [ *archive-postgres* : 5432 ]
       - startupProbe:
         - ***see archive :: startupProbe**
       - liveness:
         - **exec cmd**: `postgres query to access/read archive database`
         < see **CommonCheckConfig template**>
       - readiness:
         - **exec cmd**: `script to ensure postgres state is in sync with testnet seed-node(s)`
         < see **CommonCheckConfig template**>
- `buildkite-exporter`
  - containers
    - exporter
       - ports: [ *metrics-collection* : 8000 ]
       - startupProbe:
         - **port**: metrics-collection
         - **protocol**: HTTP
         - **path**: */metrics*
         - **failureThreshold**: 3
         - **periodSeconds**: 10
       - liveness:
         - **port**: metrics-collection
         - **protocol**: HTTP
         - **path**: */metrics*
         < see **CommonCheckConfig template**>
       - readiness:
         - **exec cmd**: `curl localhost:8000/metrics`
         < see **CommonCheckConfig template**>

*CommonCheckConfig template:*
         - **initialDelaySeconds**: 30
         - **periodSeconds**: 10
         - **failureThreshold**: 3

**Note:**
- *k8s* healthcheck (liveness + readiness) [docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
- *k8s* healthcheck [best practices](https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-setting-up-health-checks-with-readiness-and-liveness-probes)

**Comment by 0x0I** [comment]
**Note:**
- *k8s* healthcheck (liveness + readiness) [docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
- *k8s* healthcheck [best practices](https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-setting-up-health-checks-with-readiness-and-liveness-probes)

**Comment by 0x0I** [comment]
#### Monitoring Solutions:
- service or cronjob script which queries kubernetes API for all failed containers within `namespace` and broadcasts to configured Discord channel(s), email address(es) or desired monitoring/alerting channels

_Example CMD:_
`kubectl get pods --field-selector=status.phase!=Running --namespace <testnet> -o json`

_Example STATUS output to parse and push to alerting channel:_
```
...
            "status": {
                "message": "Pod ephemeral local storage usage exceeds the total limit of containers 50Gi. ",
                "phase": "Failed",
                "reason": "Evicted",
                "startTime": "2020-10-11T17:12:57Z"
            }
```

**Comment by bkase** [comment]
Some questions:

1. Is there a good mechanism for specifying health checks in such a way that we can reuse them for (a) alerting at runtime if things go wrong / automating behavior (b) running nightly networks and making sure they stay healthy . Maybe this is what you're thinking already, but could you explain how this could work?

This is a great list for startup-probe, liveness, and readiness for individual services. Two more questions here:
1. Is there a nice way we can support health checks that need to span across services? For example, "the network" is healthy if "a block is received to all parties within one slot".
2. I bet many folks on the protocol team will have more ideas for application-specific health checks of different components (example: proofs take longer than X seconds, snark pool response time too slow, transition frontier size too large, etc). Could you prepare something that makes it easier to gather this information from folks? I think maybe a table in a Notion doc could work?

I like the idea of pushing everything into GraphQL, but I wonder if it may not be easy enough to instrument. Is there a way we can connect the integration testing system into the health checks too?

**Comment by 0x0I** [comment]
> 1. Is there a good mechanism for specifying health checks in such a way that we can reuse them for (a) alerting at runtime if things go wrong / automating behavior (b) running nightly networks and making sure they stay healthy . Maybe this is what you're thinking already, but could you explain how this could work?

For sure and right, that's where the (monitoring solution) *k8s* `Service` or `Cronjob` script mentioned above comes into play. The original thinking was that:
1. a *"Watchdog"* pod would be deployed within each testnet/namespace containing a single container with the necessary tooling and service-account privileges to monitor all pod/container health within its testnet/namespace. The healthchecks implemented for each container would then be collected by this *Watchdog* when in violation using some form of the `kubectl get pods ...` CMD referenced.
2. Rather than only pushing healthcheck violations to a designated Discord channel or group of channels on some cadence (using something like a *k8s* cronjob), the *Watchdog* would also be implemented as a Discord bot capable of responding to Discord commands (e.g. `!brain healthcheck qa-net`) **note:** the name "brain" comes from the name of Inspector Gadget's dog, Brain. The bot/watchdog would then respond with a list of pods in violations (based on and populated with the details from the individual checks) and perhaps further guidance (think links to runbooks, howtos etc).

**Comment by 0x0I** [comment]
>     1. Is there a nice way we can support health checks that need to span across services? For example, "the network" is healthy if "a block is received to all parties within one slot".

Good question and my thinking around this has centered around expanding the *Watchdog* pod mentioned above. Kubernetes healthchecks themselves are only scoped to individual containers by design and implementation and not meant to provide status checks outside of this scope (e.g. network, role or some defined group wide). Based on this, it seems like more group based checks could be provided by an additional script+container solution included within the *Watchdog* pod. This script could be implemented in any language (e.g. something like OCaml) with really no constraints on what it could check. Since it would be deployed alongside the *Watchdog* in the same namespace, all of its healthcheck violations would also be captured and reported accordingly.

**Comment by 0x0I** [comment]
>     2. I bet many folks on the protocol team will have more ideas for application-specific health checks of different components (example: proofs take longer than X seconds, snark pool response time too slow, transition frontier size too large, etc). Could you prepare something that makes it easier to gather this information from folks? I think maybe a table in a Notion doc could work? I think in the table we should include a section for a sketch of implementation details for each check and maybe also a rough estimate on scope to get it to work. (does the graphql endpoint already exist? do we need to also create it? etc)

Sure, a [Notion doc]( https://www.notion.so/codaprotocol/Mina-Testnet-Role-and-Network-Healthcheck-Ideas-59dff2748ca74383afc68382d4383b9d) sounds good.

**Comment by bkase** [comment]
Great, thank you! It sounds like we'll be able to throw many engineers in to help parallelize building different checks as well once the infrastructure is in place.

> it may be worth discussing whether the current healthchecks implemented in bash are better served written in another language - like Python

Personally, I think it's okay if it starts in bash and evolves into something better as scope grows. Especially as some of the existing ones are more or less one-liners right now, right?

**Comment by 0x0I** [comment]
Cool and yep, right.
