### ISSUE TITLE
Verify that the regenerated ledger represents the merkle root of the network it was replayed from

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#6231]

**Comment by psteckler** [comment]
#6256 adds the target ledger hash to the replayer input. The replayer will fail (exit 1) if the final ledger hash doesn't match that hash.

Still need to add a CI job to run the replayer with a particular archive db and input.

**Comment by psteckler** [comment]
We're checking ledger hashes for each block in the replayer, not sure what else this issue contemplates.
