### ISSUE TITLE
config directory gets deleted when mina version changes

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#6246]
Any persisted data is lost when restarting a node with a new binary (perhaps after a hotfix). If we plan on doing a hard fork for every new binary then this probably is not an issue.

**Comment by aneesharaines** [comment]
Decouple parts of the config that we should delete vs those that should persist (keys)

Change version to x.y.z
Hotfixes change z - don't delete config
Releases change y - deletes the config
Major releases change x

**Comment by aneesharaines** [comment]
Do not delete anything for now.

**Comment by deepthiskumar** [comment]
What we may want to do for each of the config dir contents

| content | Delete | Cleanup |
|----------|-------|----------|
| coda-version (commit sha of the binary running) | Yes, if the commit changes | |
| daemon.json | Yes (runtime config is packaged in the deb) | |
| wallet | No (except when the key format changes?)| |
| logs (coda.log, coda-prover.log, coda-verifier.log) | No | |
| genesis ledger and proof | OK to delete because it can be copied from /var/lib/coda | |
| client trustlist | No | |
| trust db | Yes, if it is a new network starting at slot 0? |  |
| trace logs | No | yes |
| receipt chain database | Yes, if it is a new network, also I think it is broken because we always get the receipt from account and not the latest receipt from transaction pool? | |
| transaction database (for graphql) | Yes, if it is a new network | |
| external transition database (for graphql) | Yes, if it is a new network | |
| Current protocol version | No, unless we ask them to delete/change it explicitly? | |
| Persistence (snark pool, transition frontier, frontier root) | Yes, if it is a new network starting at slot 0| |
| crash log | No | yes |
| coda net2 (dht, peerstore, helper.lock) | Yes, because it should load new ones on restart? | |
| child processes .lock files | Yes, on restart | |

**Comment by deepthiskumar** [comment]
Updated the above table with action for each item. Also, identified the issue with frontier persistence when we don't clean it up and fixed it in #6553
For 4.1 we just don't delete the config directory. External transition database, transaction database, and receipt chain database are either obsolete or broken (check the table above) and can be left as is until they are fixed or removed.

**Comment by deepthiskumar** [comment]
Added these to track the TODOs  #6556  #6555
