### ISSUE TITLE
Homepage QA Items - Desktop or All

### ISSUE THREAD

**Issue by sherrylin13** [MinaProtocol/mina#6281]
_1. Replace background with animation - 2_
_2. Excess space around the hero statement and too much space between hero statement and blockchain comparison animations - 2_
_**3. In the News section - Article title font is too thick. Please check weight. - 2**_
_4. In the News section - Increase the spacing between "Read more" and arrow. Refer to link within the user benefits section above._
_**5. All illustrations should reduce to 50% of current size - 1**_
_6. In the "Truly Decentralized, with Full Nodes like Never Before" section, capitalize "node" in the CTA text - 3_

**Comment by michellewong793** [comment]
for number 6: is that still necessary? 
![image](https://user-images.githubusercontent.com/12700801/96293292-5f6b0d00-0f9f-11eb-84df-1eb819ec56cf.png)

**Comment by sherrylin13** [comment]
Yes, please still update capitalization to "Run a Node -->", thanks!

**Comment by michellewong793** [comment]
these weights are the same 
![image](https://user-images.githubusercontent.com/12700801/96303430-36527880-0faf-11eb-9e81-7542c696d6a6.png)
![image](https://user-images.githubusercontent.com/12700801/96303446-3c485980-0faf-11eb-825c-426a984b4209.png)
