### ISSUE TITLE
About Page QA Items 

### ISSUE THREAD

**Issue by sherrylin13** [MinaProtocol/mina#6284]
-- Desktop --

1. Throughout page - horizontal rules appear too thick. Should be 1px (see homepage for guidance) - screenshot for example: https://www.dropbox.com/s/2onc7fpfzl1ex7b/Screen%20Shot%202020-09-25%20at%205.04.59%20PM.png?dl=0 - 2
2. Secured by Participants - update copy to "The Mina network is secured by an uncapped number of block producers via proof-of-stake consensus. A uniquely decentralized blockchain, Mina gets even more secure and resilient as it grows." - 1
3. That's why we created Mina section - Add back in the link for "powerful applications" to link to Snapps in the docs; also orange color seems different from design, see screenshot: https://www.dropbox.com/s/ozbs7kistpxbwnc/Screen%20Shot%202020-09-25%20at%205.12.04%20PM.png?dl=0 - 2
4. You can run a node section - body copy leading needs to open up - screenshot: https://www.dropbox.com/s/j6kgryxqtbr9sr7/Screen%20Shot%202020-09-25%20at%206.03.43%20PM.png?dl=0 - 2
5. Naval quote - Hang the apostrophe around his quote - 2
5. Team bios - ship the bios opening functionality (the + signs) - 2
6. Investors - background image looks blown up, refer to design - 2
7. Most sections don't appear to be center within the browser, right margin appears wider - 1
8. Team - Update Bijan's job title to "Head of Product" - 1

-- Mobile --

1. Header - headline type size is incorrect, see screenshot: https://www.dropbox.com/s/133pux7grwerr0a/IMG_2036.PNG?dl=0 - 2
2. It's time to own our future - headline type size is incorrect, see screenshot: https://www.dropbox.com/s/ua059ieerwccchj/IMG_2037.PNG?dl=0
3. It's time to own our future - link in body copy is hard to see against orange background, maybe move the gradient out from center a bit, see screenshot: https://www.dropbox.com/s/v2mndykagdaz9rk/IMG_2038.PNG?dl=0 - 2
4. You can run a node & secure the network section - "Get Started" CTA button is outside the container, see screenshot: https://www.dropbox.com/s/amtmy33uw8sal8l/IMG_2042.PNG?dl=0 - 2
5. Secured by participants section - too much space between illustrations and rule that is below, see screenshot: https://photos.app.goo.gl/oNynfUgvAGupbP1F9 - 2
6. Genesis Members section - too much space between the subhead and the photos of the GFMs, see screenshot: https://photos.app.goo.gl/cC6YTqZ5ukw1M6bB7 - 2
7. Secured by Participants section - update both "XXXX"s to "100s" and change "SNARK Workers" to "SNARK Producers"

**Comment by michellewong793** [comment]
> -- Desktop --
> 
> 1. Throughout page - horizontal rules appear too thick. Should be 1px (see homepage for guidance) - screenshot for example: https://www.dropbox.com/s/2onc7fpfzl1ex7b/Screen%20Shot%202020-09-25%20at%205.04.59%20PM.png?dl=0 - 2
> 2. Secured by Participants - update copy to "The Mina network is secured by an uncapped number of block producers via proof-of-stake consensus. A uniquely decentralized blockchain, Mina gets even more secure and resilient as it grows." - 1
> 3. That's why we created Mina section - Add back in the link for "powerful applications" to link to Snapps in the docs; also orange color seems different from design, see screenshot: https://www.dropbox.com/s/ozbs7kistpxbwnc/Screen%20Shot%202020-09-25%20at%205.12.04%20PM.png?dl=0 - 2
> 4. You can run a node section - body copy leading needs to open up - screenshot: https://www.dropbox.com/s/j6kgryxqtbr9sr7/Screen%20Shot%202020-09-25%20at%206.03.43%20PM.png?dl=0 - 2
> 5. Naval quote - Hang the apostrophe around his quote - 2
> 6. Team bios - ship the bios opening functionality (the + signs) - 2
> 7. Investors - background image looks blown up, refer to design - 2
> 8. Most sections don't appear to be center within the browser, right margin appears wider - 1
> 9. Team - Update Bijan's job title to "Head of Product" - 1
> 
> -- Mobile --
> 
> 1. Header - headline type size is incorrect, see screenshot: https://www.dropbox.com/s/133pux7grwerr0a/IMG_2036.PNG?dl=0 - 2
> 2. It's time to own our future - headline type size is incorrect, see screenshot: https://www.dropbox.com/s/ua059ieerwccchj/IMG_2037.PNG?dl=0
> 3. It's time to own our future - link in body copy is hard to see against orange background, maybe move the gradient out from center a bit, see screenshot: https://www.dropbox.com/s/v2mndykagdaz9rk/IMG_2038.PNG?dl=0 - 2
> 4. You can run a node & secure the network section - "Get Started" CTA button is outside the container, see screenshot: https://www.dropbox.com/s/amtmy33uw8sal8l/IMG_2042.PNG?dl=0 - 2
> 5. Secured by participants section - too much space between illustrations and rule that is below, see screenshot: https://photos.app.goo.gl/oNynfUgvAGupbP1F9 - 2
> 6. Genesis Members section - too much space between the subhead and the photos of the GFMs, see screenshot: https://photos.app.goo.gl/cC6YTqZ5ukw1M6bB7 - 2
> 7. Secured by Participants section - update both "XXXX"s to "100s" and change "SNARK Workers" to "SNARK Producers"

1. it is 1px. unfortunately can't go further down than that 
![image](https://user-images.githubusercontent.com/12700801/96306153-f641c480-0fb3-11eb-8249-a1da5d291851.png)
