### ISSUE TITLE
Check Max buffer size in libp2p; could mean we're dropping stdin/stdout messages

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#6291]
Figure out the max and verify that we are not hitting it.  Check with @deepthiskumar  may have information about current size?

**Comment by deepthiskumar** [comment]
It is currently 1GB 
https://github.com/MinaProtocol/mina/blob/ecc4afbad2ab8ec3d85c4e9eaaa3c2762cd3f6b6/src/app/libp2p_helper/src/libp2p_helper/main.go#L1103
