### ISSUE TITLE
debug and fix "block receipt latency" metric

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#6299]

**Comment by deepthiskumar** [comment]
Looked at this a bit. Here's my observation:

1. For each update, we add the metric value to a "bucket" and we a have a fixed number of buckets. Also, for every `tick_interval` which is `block_window_duration/2` we add a new bucket with 0 sec(maybe there are too many of those making the average small?)

2. When we update it with block latency value, we simply add it to the top most bucket (update the time and count) and every 1.5mins (tick_interval) we create a new bucket. Also, when we compute the average we don't include the count in each bucket and that seems incorrect? This is in the function `render_average` when defining the module `Moving_time_average` in `metric_generators.ml`
Further, we divide the sum (of times in all buckets) by rolling_interval which is 60 mins. Shouldn't we be dividing it by the number of entries?

**Comment by psteckler** [comment]
There are 3 `Block_latency` metrics:

 - `Gossip_slot`
 - `Gossip_time`
 - `Inclusion_time`

Which one is broken and in need of debugging, and what is the evidence for that?
