### ISSUE TITLE
Docs QA Items

### ISSUE THREAD

**Issue by sherrylin13** [MinaProtocol/mina#6300]
1. Add padding between the copy and the subnav bar throughout - 2
2. SideNav spacing is too close to the content - 2
3. Horizontal rules are all missing - see design mocks - 3
4. Subhead copy links are not in monospace typeface - 2
5. Edit link is in wrong style (should be like orange arrow link) - 1
6. Typesafe Invariants is in the wrong typeface, wrong size - 1
7. GraphQL API section - number indents should align with bullet indents - 2
8. Mina Protocol Architecture > Lifecycle of a Payment, Consensus - 
Note is in the wrong format (should be in a purple-headed box) - 1
9. Mina Protocol Architecture > Consensus - 
Under Local_State paragraph needs a period - 3
10. SNARKs > Which SNARK is right for me? - Illustration for Overview of the Landscape has not been placed - 1
11. Where there's a purple note with "See" below it, add more space between these 2 elements - 2

-- Mobile --
There is no sticky nav on mobile at all - 1

**Comment by aneesharaines** [comment]
Combining with #6301
