### ISSUE TITLE
Header/Footer QA Items - Mobile/Tablet

### ISSUE THREAD

**Issue by sherrylin13** [MinaProtocol/mina#6310]
1. Footer is just the "enter email" field and a bunch of blank space - 1
2. Announcement bar 'Mina is growing fast' & 'Subscribe to stay updated' are both breaking onto a second line - 2

**Comment by michellewong793** [comment]
can't reproduce the first one, and the second one here

**Comment by michellewong793** [comment]
![image](https://user-images.githubusercontent.com/12700801/96649699-7898f400-12e6-11eb-85a3-cc23d7f0fd90.png)

![image](https://user-images.githubusercontent.com/12700801/96649712-7d5da800-12e6-11eb-88b0-d1e447c883a8.png)
