### ISSUE TITLE
Leaderboard QA Items - Mobile/Tablet

### ISSUE THREAD

**Issue by sherrylin13** [MinaProtocol/mina#6313]
1. Headline numbers (participants/genesis members/blocks produced) are too small - 2
2. Black line is missing next top 'top 10', should look just like the black line next to 'top 50' - 2
3. Breadcrumbs (testnet > Leaderboard > Participant Details) and Username are overlapping Mina logo. Should be below logo. - 2

**Comment by aneesharaines** [comment]
Taken care of by other pr
