### ISSUE TITLE
Use real mainnet parameters

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#6351]
k 290 slots
alpha 0.65
f 0.75
slots_per_window 77 
slots_per_sub_window 7 
sub_windows_per_window 11
No. of shifts in a window 11
Epoch duration R 7140 slots
Delta 0

**Comment by aneesharaines** [comment]
After chatting with Evan, about whether we want to optimize for testing epoch transitions or network load, felt that network load is the right area to focus for 4.1.

So current proposal is 
4.1 with real consensus parameters (k=290, epoch length of 14.86 days), engaging users for 1 full epoch
Adversarial is also with real parameters 

Community QA net can adjust depending on what we need to test for for now is small k
