### ISSUE TITLE
Nodes report "synced" at height 1 until the network produces a block

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#6354]

**Comment by es92** [comment]
traced to line 102 of transition_router.ml, get_best_tip returns "Peer x doesn't have the requested best tip" for all peers

**Comment by es92** [comment]
Believe found bug; line 51 of best_tip_prover.ml checks if the transition frontier has at least k blocks. However, this is not true when nodes are starting up. This check should be changed to transition_frontier_path = k slots OR current global slot < k slots

**Comment by nholland94** [comment]
@es92 :+1: nice find. That fix makes sense to me.
