### ISSUE TITLE
daemon crashed in the qa testnet

### ISSUE THREAD

**Issue by woodstock-xkx** [MinaProtocol/mina#6404]
I have runned the coda daemon twice. Both of them failed to continue after a not-very-long time(about 40min). 
The crash report is attached here.
[coda_crash_report_2020-10-16_13-54-07.844216.tar.gz](https://github.com/MinaProtocol/mina/files/5392316/coda_crash_report_2020-10-16_13-54-07.844216.tar.gz)

**Comment by mrmr1993** [comment]
This JSON parse error should be caught by #6362. There's not enough info in the log to work out what the actual error is, but once a release including #6362 is out we should see the problematic line in the logs.

**Comment by aneesharaines** [comment]
Can we close this?  I think we will capture it in future test nets with better information
