### ISSUE TITLE
Verifier error when checking transaction snark for statement  - crash 

### ISSUE THREAD

**Issue by Igor-Tselkovskiy** [MinaProtocol/mina#6423]
[2020-10-18 04:25:29.699240]Staged_ledger: Verifier error when checking transaction snark for statement []: $error
$error = "((rpc_error\n  (Connection_closed\n   ((\"exn raised in RPC connection Writer.t\"\n     (monitor.ml.Error\n      (\"writer buffer has data older than\" (maximum_age 2m)\n       (beginning_of_buffer\n        \"\\001\\020rpc_parallel_plain_1\\000\\254\\127\\015\\2541P\\002\\001\\001\\001\\001\\207\\186\\147\\218\\007\\014\\134\\011,\\128&\\239X\\003\\129\\195\\185Xz\\165\\024\\171j\\007irQ\\154\\220\\207C\\027\\001\\217\\251\\004\\180\\233\\236v\\014\\189rGr3\\203\\140\\180\\168s\\240\\193\\001g\\190\\163\\180x\\236k\\171\\199|.\\001\\001\\252\\000\\160\\219!]\\000\\000\\000\\001\\001\\001\\001\\001\\178cI4\\137f_\\025A0\\139\\213\\146\\151\\169]\\231`$\\155\\159Xa\\174\\134c\\208\\219\\128\\137b2\\001\\001\\001\\163\\241\\003m\\199Q\\172\\r\\177\\139{\\221\\230\\129\\187F[\\193\\189\\141U\\188\\141hI\\029\\179\\149\\144Z\\171<\\001\\135\\189\\000\\146\\169\\228&\\029}^\\030z\\146\\206L\\242.\\128\\159I\\149\\202\\220\\005gi4\\182\\020\\239\\020 \\001\\001\\001#pb\\174\\028\\128\\001q\\017IxUu\\025F>o\\149\\031P1\\196b7\\198\\228,B\\170yD3\\001\\001\\001\\163\\241\\003m\\199Q\\172\\r\\177\\139{\\221\\230\\129\\187F[\\193\\189\\141U\\188\\141hI\\029\\179\\149\\144Z\\171<\\001b\\143\\031\\167o\\019\\160\\201-m\\202\\191\\000\\133\\016\\030Z\\229*\\189\\192Gr\\171H+\\227\\171\\144$V4\\001\\001\\001\\001\\001\\001\\001\\001\\000\\001\\000\\001\\001\\001\\001\\001\\001\\000\\001\\000\\001\\001\\002\\001\\001\\002\\001 \\169^\\127y\\172\\151\\177\\169V\\131v\\206\\022j%\\203J]9\\228\\210^D\\235u\\192\\226\\131o\\243d\\246\\001\\227\\241wDa-\\023c\\194\\196\\145=\\015\\254K\\192\\229DB<\\213a\\225\\002\\154\\178\\231\\235mZ\\149\\031\\233\\199&\\229gj#\\234\\253\\237\\029\\139\\207</g\\127]D\\253\\230WE\\158l\\\"\\206{\\198\\246\\176:\\252\\182\\150~\\171\\2166\\025\\217\\252e'\\155\\005\\209\\137\\1794\\000\\252\\188\\024\\006\\250\\242flV\\252d\\166\\r\\192\\216\\233\\217\\\\\\000\\252\\240\\224\\204D\\229Z\\172\\140\\252\\219\\187Z\\213Z\\228\\232\\158\\000\\252\\154\\243o\\191\\174U\\219\\t\\252T[\\244m\\235\\232\\176/\\000\\001\\000\\252r\\212oN\\1852\\156\\244\\252f\\176\\r\\173R\\199\\187\\161\\000\\001\\000\\252+\\165\\132$\\132\\r6\\179\\252\\195\\132\\148\\0038\\006\\172c\\000\\001\\000\\252'rm\\193\\205\\227\\176\\216\\252\\199(\\2353\\159:\\245\\243\\000\\250\\144\\232)\\0128\\175\\222N\\159B\\178\\183`\\242\\024\\223\\172p\\199\\209\\155\\231[\\174\\234\\131\\254\\189PL3\\027\\159w\\214\\144\\237\\223\\208@\\174\\019\\203\\016-\\012W\\212\\153\\b\\173j5_.\\167\\129r:Pw\\173\\007\\001\\000\\252\\253r\\181\\140\\211\\252\\2204\\252\\176wNz\\157\\147HN\\000\\001\\000\\252+\\195~2*P\\147`\\252\\218P\\1893,+\\128\\198\\000\\001\\001\\000\\252\\003\\164\\176C \\206\\004v\\252\\029\\194\\031\\204\\252\\127\\199\\235\\000\\001\\001\\000\\252%\\139\\191m6k\\000\\220\\252W\\1501\\1819\\247\\233&\\000\\000\\001\\000\\252H+\\167\\2523\\248\\006\\228\\252'g\\004\\150\\139\\238\\255\\247\\000\\001\\001\\000\\252~\\168\\224\\233]\\241~\\002\\2524\\252\\004L\\138]Xw\\000\\001\\001\\000\\252~\\147\\154\\189\\232C\\r\\011\\252\\198#\\181\\003\\185\\149\\220\\015\\000\\001\\001\\000\\252\\164\\213\\238\\175X\\199\\176K\\252\\155!|\\209\\137\\129\\209}\\000\\001\\001\\000\\252\\237Y\\251}2\\164\\2407\\252\\227\\212\\006\\238\\143\\232\\220&\\000\\001\\001\\000\\252\\241\\230p\\024\\194^\\rC\\252\\16123l\\172Fe\\176\\000\\000\\001\\000\\252\\213\\160\\003:E\\250~)\\252q\\022\\203mup\\232\\147\\000\\000\\001\\000\\252m\\1362\\250\\210/n\\031\\252d\\151*\\003\\159\\2024x\\000\\001\\001\\000\\252_\\004KNw\\242-\\021\\252\\248`\\174q\\174\\181\\217\\219\\000\\000\\001\\000\\252\\251\\192\\243;hd`E\\252\\247\\029:\\228\\164D\\001_\\000\\001\\001\\000\\252\\157\\169\\138\\012\\141H$\\247\\252\\189\\133n*\\0166\\167\\169\\000\\001\\001\\000\\252e\\210DY\\164=\\186X\\252\\245\\193\\t\\190\\2330\\186\\014\\000\\001\\001\\000\\2524\\185r0\\237v\\022/\\252\\179\\136\\138\\012L\\226x\\145\\000\\000\\001\\000\\252KE\")\n       (writer\n        ((id 65)\n         (fd\n          ((file_descr 37)\n           (info\n            (replaced\n             ((\"connected to\" 127.0.0.1:39051)\n              (previously_was\n               (replaced\n                ((socket (bound_on 0.0.0.0:0))\n                 (previously_was\n                  (socket ((family PF_INET) (socket_type SOCK_STREAM))))))))))\n           (kind (Socket Active)) (supports_nonblock true)\n           (have_set_nonblock true) (state (Open Empty))\n           (watching ((read (Watch_once Empty)) (write (Watch_once Empty))))\n           (watching_has_changed false) (num_active_syscalls 2)\n           (close_finished Empty)))\n         (monitor\n          (((name (id 2118)) (here ()) (id 2118) (has_seen_error false)\n            (is_detached true))\n           ((name \"\") (here ()) (id 167) (has_seen_error false)\n            (is_detached true))))\n         (inner_monitor\n          (((name (id 2119)) (here ()) (id 2119) (has_seen_error false)\n            (is_detached true))\n           ((name \"\") (here ()) (id 167) (has_seen_error false)\n            (is_detached true))))\n         (background_writer_state Running) (background_writer_stopped Empty)\n         (syscall Per_cycle) (bytes_received 13509978)\n         (bytes_written 11895598) (scheduled_bytes 1552706)\n         (scheduled_back 0) (back 61674) (close_state Open)\n         (close_finished Empty) (close_started Empty)\n         (num_producers_to_flush_at_close 0)\n         (flush_at_shutdown_elt (<opaque>))\n         (check_buffer_age\n          (((writer <opaque>) (maximum_age 2m)\n            (bytes_received_at_now_minus_maximum_age 11941099)\n            (bytes_received_queue\n             (11944557 11944566 11965132 12006256 12026827 12029430 12076233\n              12139853 12222097 12242655 12274480 12275126 12275135 12316259\n              12357387 12443366 12444021 12487645 12595476 12682724 12746914\n              12808596 12808605 12829167 12870291 12931981 12931990 12933282\n              12953844 12994977 13097783 13138899 13159457 13180032 13221160\n              13323966 13324935 13345493 13407176 13509978))\n            (times_received_queue\n             ((2020-10-18 04:22:57.932969985+02:00)\n              (2020-10-18 04:22:58.943618259+02:00)\n              (2020-10-18 04:23:02.084664968+02:00)\n              (2020-10-18 04:23:04.065858293+02:00)\n              (2020-10-18 04:23:08.068261294+02:00)\n              (2020-10-18 04:23:18.001134464+02:00)\n              (2020-10-18 04:23:19.468416643+02:00)\n              (2020-10-18 04:23:21.839796048+02:00)\n              (2020-10-18 04:23:24.724220693+02:00)\n              (2020-10-18 04:23:26.251275168+02:00)\n              (2020-10-18 04:23:27.251550998+02:00)\n              (2020-10-18 04:23:29.251837665+02:00)\n              (2020-10-18 04:23:30.252041435+02:00)\n              (2020-10-18 04:23:35.904217487+02:00)\n              (2020-10-18 04:23:37.112656027+02:00)\n              (2020-10-18 04:23:40.790497637+02:00)\n              (2020-10-18 04:23:41.790944146+02:00)\n              (2020-10-18 04:23:50.214326556+02:00)\n              (2020-10-18 04:23:54.599130092+02:00)\n              (2020-10-18 04:23:57.778037996+02:00)\n              (2020-10-18 04:24:00.522781403+02:00)\n              (2020-10-18 04:24:03.302153758+02:00)\n              (2020-10-18 04:24:05.429702192+02:00)\n              (2020-10-18 04:24:07.351809520+02:00)\n              (2020-10-18 04:24:08.505753730+02:00)\n              (2020-10-18 04:24:10.898523462+02:00)\n              (2020-10-18 04:24:20.097503827+02:00)\n              (2020-10-18 04:24:21.097779343+02:00)\n              (2020-10-18 04:24:24.194892457+02:00)\n              (2020-10-18 04:24:25.490939498+02:00)\n              (2020-10-18 04:24:29.833647736+02:00)\n              (2020-10-18 04:24:31.933502765+02:00)\n              (2020-10-18 04:24:35.402277679+02:00)\n              (2020-10-18 04:24:36.862358529+02:00)\n              (2020-10-18 04:24:38.149976471+02:00)\n              (2020-10-18 04:24:42.176000278+02:00)\n              (2020-10-18 04:24:43.176188362+02:00)\n              (2020-10-18 04:24:45.202549408+02:00)\n              (2020-10-18 04:24:52.754946837+02:00)\n              (2020-10-18 04:24:57.015275282+02:00)))\n            (bytes_seen 13509978) (too_old (Full ())))))\n         (consumer_left Empty) (raise_when_consumer_leaves false)\n         (open_flags (Full (Ok (rdwr nonblock)))) (line_ending Unix))))\n      (\"Caught by monitor (id 2118)\"))))))\n (connection_description (\"Client connected via TCP\" (localhost 39051)))\n (rpc_tag rpc_parallel_plain_1) (rpc_version 0))"

Send status and coda-log on email from igor#4065

**Comment by nholland94** [comment]
This is the same error as https://github.com/MinaProtocol/mina/issues/6424. I will close this in favor of the other issue, as that issue has more logs associated with it for us to dive into.
