### ISSUE TITLE
Add investor logos to the About page on Wednesday (10/21) morning 6AM PST

### ISSUE THREAD

**Issue by sherrylin13** [MinaProtocol/mina#6432]
With the launch of the press release announcing our strategic round, which is going live Wed (10/21) morning, we need the new investor logos to be added to https://minaprotocol.com/about sometime on Wed (10/21) during the day. 

Logos can be found here: https://www.figma.com/file/dQy2CndYFvp9zLJXANVfqd/Visual-Design?node-id=3166%3A0

Also, please update the Dragonfly Capital logo (new logo is in same Figma folder above).

Kate is also reformatting the existing logos, as some of their aspect ratios are off.

**Comment by michellewong793** [comment]
closing bc new one does it in alphabetical order
