### ISSUE TITLE
Possible missing blocks in archive database

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#6435]
We currently add to the archive db only those blocks that are added to the transition frontier and so if any of the following events occur then the archive db may not have some blocks.
1. archive process crashes and misses a block before restart (could be mitigated by having multiple archive process connect to the same archive db?)
2. The daemon that an archive process connects goes offline and bootstraps to a new root on restart. since bootstrap is triggered only if the diff is `2*k` we may miss some blocks (the daemon has to be offline for a considerable period for this to happen)
3. possibly during a catchup triggered by a reorg? If the chain is longer than `k` then we'll not add blocks older than the first `k` to the transition frontier and therefore those blocks wouldn't make it to the archive db

Having a complete archive db is necessary for hardfork because the ledger for a fork is generated from the blocks stored in the archive db

**Comment by aneesharaines** [comment]
Need a mini RFC for this

**Comment by bkase** [comment]
We (o1labs) need to be able to recover from some secondary source data, for example from our google cloud logs.

**Comment by psteckler** [comment]
See #6912, tool to report these gaps.

**Comment by deepthiskumar** [comment]
Recovery and redundancy implemented
