### ISSUE TITLE
I get an error during run

### ISSUE THREAD

**Issue by StakingShop** [MinaProtocol/mina#6437]
i runned this command and getting error: 

`coda daemon -peer /dns4/seed-two.pickles-public.o1test.net/tcp/10001/p2p/12D3KooWFcGGeUmbmCNq51NBdGvCWjiyefdNZbDXADMK5CDwNRm5/ -peer /dns4/35.237.193.100/tcp/10001/p2p/12D3KooWAFFq2yEQFFzhU5dt64AWqawRuomG9hL8rSmm5vxhAsgr -config-file ~/daemon.json -generate-genesis-proof true -log-json -log-level Trace -block-producer-key "${KEYPATH}" | coda-logproc | tee ~/coda-log.txt`

Briefly describe what you were doing and attach the crash report /root/.coda-config/coda_crash_report_2020-10-20_13-37-14.958699.tar.gz

i shared this file here: https://drive.google.com/drive/folders/1u7LuJ0blBPlMGdawpG-ql1fTmU7w7W-Q?usp=sharing

**Comment by nholland94** [comment]
The actual error here is:
```
(monitor.ml.Error
  "Parent directory ~/.coda-config/wallets/store does not exist Hint: mkdir -p ~/.coda-config/wallets/store; chmod 700 ~/.coda-config/wallets/store\
"
  ("Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30"
    "Called from file \"src/lib/secrets/privkey_error.ml\", line 23, characters 14-57"
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
    "Caught by monitor coda"))
```

This appears to indicate that something was incorrect on your local filesystem. I would follow the instructions in the error message and try again. It's also possible that the value you are passing as `$KEYPATH` is invalid as well, but I can't be certain without knowing what that was set to.
