### ISSUE TITLE
Coda Daemon crashed at startup

### ISSUE THREAD

**Issue by bidulemachin** [MinaProtocol/mina#6438]
I reinstalled my node for qa-task-force.
I started mina daemon an provided logs 1 hours later.
Because I had to close the terminal, I put the process in background (Ctrl+D and bg command)

Then I came back later (about 2 hours later) and I saw that process was not running anymore.
I restarted it (using screen) but I got the daemon crash at startup

[coda_crash_report_2020-10-20_14-48-34.894207.tar.gz](https://github.com/MinaProtocol/mina/files/5409533/coda_crash_report_2020-10-20_14-48-34.894207.tar.gz)

**Comment by garethtdavies** [comment]
It can't find your private key as you didn't provide a key path. Likely you didn't export the private key path to the screen session (or persist the environment variable).

**Comment by bidulemachin** [comment]
Tks Gareth for the idea.
Key path is set on .profile file I just tried to display it after "screen" with echo comand : it works.
Also, I launched the process again to check : "ps -ef | grep -coda" display process with option path details => it is ok.

May be I made a mistake when launching it previously (for example using an old terminal openned before .profile setting) ?!

**Comment by bidulemachin** [comment]
Issue not reproduced at second attemps
