### ISSUE TITLE
Daemon crash after Validation error: external transition with state hash...was rejected for reason "invalid time"

### ISSUE THREAD

**Issue by jrwashburn** [MinaProtocol/mina#6484]
Running coda daemon per QATF instructions 

coda daemon -peer /dns4/seed-two.pickles-public.o1test.net/tcp/10001/p2p/12D3Koo... -peer /dns4/seed-one.pickles-public.o1test.net/tcp/10001/p2p/12D3Koo... -peer /ip4/35.243.238.16/tcp/10001/p2p/12D3Koo... -config-file ~/daemon.json -generate-genesis-proof true -log-json -log-level Trace -block-producer-key "${KEYPATH}" | coda-logproc | tee ~/coda-log.txt

Daemon crashed after ~1.5h 
[coda_crash_report_2020-10-22_17-47-57.290784.tar.gz](https://github.com/MinaProtocol/mina/files/5425744/coda_crash_report_2020-10-22_17-47-57.290784.tar.gz)
[coda-log.txt.zip](https://github.com/MinaProtocol/mina/files/5425745/coda-log.txt.zip)

**Comment by nholland94** [comment]
The "invalid time" log is unrelated to the crash. The crash summary points to the same error as https://github.com/MinaProtocol/mina/issues/6492, and this bug has been addressed and will be in the next release of the software. See https://github.com/MinaProtocol/mina/issues/6492 for more details.
