### ISSUE TITLE
Snark coordinator is still incredibly leaky

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#6488]
When running with limited memory it only stays up for a few minutes before crashing again, but in the last network with unlimited memory it was using 100GB and climbing to stay up and stable.

**Comment by lk86** [comment]
![image](https://user-images.githubusercontent.com/5480925/96935833-ea15a580-1492-11eb-83e2-9e62d1d2c7ea.png)

**Comment by aneesharaines** [comment]
Looks good on the new network, closing.
