### ISSUE TITLE
The SNARK pool appears to grow without bound

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#6512]
On the current community QA net, the SNARK pool seems to be growing without bound. Currently it is at around 4k SNARKs. I would expect it to be smaller than that.

**Comment by garethtdavies** [comment]
From Deepthi on [Discord](https://discord.com/channels/484437221055922177/685189315352854624/763119242211229758):

> They don't get removed from the pool immediately after purchasing. Each block updates the scan state with the work that needs to be purchased by future blocks. SNARKs for any work referenced in the scan state for the last k (the finality parameter) blocks including any forks will be stored in the pool. So, if some SNARKs were added before the last k blocks they'll still be in the pool if the work is referenced in the last k blocks and removed  otherwise

with `k` on this testnet being 290 nothing should have been evicted yet?

Related to this issue: https://github.com/MinaProtocol/mina/issues/5237

**Comment by imeckler** [comment]
Aha... thanks @deepthiskumar and @garethtdavies. Yeah I guess that's what's going on. This shouldn't be too much of an issue but we may have to serialize the SNARK pool in a more sophisticated way than we're doing right now.

**Comment by aneesharaines** [comment]
@deepthiskumar  - going to check that it levels out on a new network

**Comment by bijanshahrokhi** [comment]
Do we have any information on the growth velocity? Hoping we can look into this after the memory leakage fixes.
