### ISSUE TITLE
When you try to create a token, your daemon crashes

### ISSUE THREAD

**Issue by bijanshahrokhi** [MinaProtocol/mina#6514]
Daemon crashed on create-token

Error: Unable to connect to Coda daemon.
- The daemon might not be running. See logs (in `~/.coda-config/coda.log`) for details.
  Run `coda daemon -help` to see how to start daemon.
- If you just started the daemon, wait a minute for the GraphQL server to start.
- Alternatively, the daemon may not be running the GraphQL server on http://localhost:3085/graphql.
  If so, add flag rest-server with correct port when running this command.
Error message: (Failure "Connection closed by remote host")

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
