### ISSUE TITLE
Update bisect_ppx again

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#6534]
The latest release of `bisect_ppx` reportedly supports using a flag to dune to instrument code. (It didn't work for the last release; I tried it.)

If that's so, we can remove this library from all our dune files and the accompanying `--conditional` flag. We can also remove the check from the script that checks for required ppxs in dune files.

**Comment by psteckler** [comment]
The `dune` files need to add:
```
(instrumentation (backend bisect_ppx))
```

**Comment by mrmr1993** [comment]
This landed in #6648. Closing.
