### ISSUE TITLE
Consistent naming for "gen" packages

### ISSUE THREAD

**Issue by mobileink** [MinaProtocol/mina#6544]
The following packages compile an executable and then use it to generate source code.  The naming is inconsistent.

* `src//lib/crypto_params/gen` - gen.exe
* `src//lib/snark_keys/gen_keys` - gen_keys.exe
* `src//lib/pickles/precomputed/gen_values` - gen_values.exe
* `src//lib/dummy_values/gen_values` - gen_values.exe
* `src//lib/coda_base/gen` - gen.exe
* `src//lib/precomputed_values/gen_values` - gen_values.exe

A single naming convention should be followed.  Since these all generate source files, I suggest `gen_srcs`.

**Comment by aneesharaines** [comment]
Thanks for suggesting this @mobileink

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
