### ISSUE TITLE
Testnet SDK: Fix Genesis JSON Format

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#6551]

**Comment by lk86** [comment]
The current solution for genesis json is the following script: https://github.com/MinaProtocol/coda-automation/blob/coda-network-integration/scripts/generate-keys-and-ledger.sh

The jq commands near the end add timing information to existing accounts and the final jq command decorates the ledger with other genesis/daemon.json required fields. The num_accounts is hard-coded to 100 here but obviously it should be a count of the accounts in the ledger. Most of the rest of the script + key/dir manipulation is either for replacing coda-network-generated keys with daemon-generated ones or generating the keys in the first place.

**Comment by mrmr1993** [comment]
> The num_accounts is hard-coded to 100 here but obviously it should be a count of the accounts in the ledger.

`num_accounts` is only used to pad the ledger with random accounts, it's fine to not set or set to zero. Should we rename it in the interest of usability?
