### ISSUE TITLE
fix/remove external transition, transaction, and receipt chain databases

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#6555]
1. Receipt chain database is broken: receipt chain hash of a transaction is always computed using the one in account and this will not work when there are multiple transactions from the same account )
2. Transaction and External transition database are not in use anymore? (@bkase) 

Specifically, we should remove receipt chain, because it's busted. But deprecate and not yet remove transaction and external transition db because people use it.

**Comment by mrmr1993** [comment]
> Transaction and External transition database are not in use anymore?

If they're not, they probably should be. This would help with some of the high memory usage we've been seeing.

**Comment by aneesharaines** [comment]
Communicate that we are deprecating the dbs in 4.1 
Remove the receipt chain if it's not being used...
