### ISSUE TITLE
QA Net node never reporting sycned

### ISSUE THREAD

**Issue by EmrePiconbello** [MinaProtocol/mina#6567]
Node never report synced state and stuck at startup even after a long time getting the last block and report synced

For example in this status spend around 15 min at block 102 never report synced 

Global number of accounts:       93
Block height:                    102
Max observed block length:       102
Local uptime:                    1h4m29s

LOGS
**https://drive.google.com/file/d/1xWldpKlvPSSXX3JRpqUWGfLYSJECJmIJ/view?usp=sharing**

**Comment by garethtdavies** [comment]
Probably related to #6559
