### ISSUE TITLE
Mina-QA: Crash after start

### ISSUE THREAD

**Issue by c29r3** [MinaProtocol/mina#6568]
## Description  
Full node crash after start  

## Environment  
```
Git SHA-1: [DIRTY]6dc573d304cf05e3d0107b61901b3b816ab06b15
Host OS: Ubuntu 20.04  
Using containerization: docker  
CPU: i5 6400  
RAM: 16 GB  
```  

## LOGS  
[coda_crash_report_2020-10-31_21-05-24.634340.tar.gz](https://github.com/MinaProtocol/mina/files/5469815/coda_crash_report_2020-10-31_21-05-24.634340.tar.gz)

**Comment by aneesharaines** [comment]
{"timestamp":"2020-10-31 21:05:24.628778Z","level":"Fatal","source":{"module":"Init__Coda_run","location":"File \"src/app/cli/src/init/coda_run.ml\", line 575, characters 2-26"},"message":"Unhandled top-level exception: $exn\nGenerating crash report","metadata":{"exn":"(monitor.ml.Error\n  ((rpc_error (Connection_closed (\"EOF or connection closed\")))\n

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
