### ISSUE TITLE
Persist/backup archive database for hardfork

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#6576]
In our current infra configuration, archive database is  not persisted. For hardforks, we want to be able to 
Start an archive db from a previous state (using persistence volume claims)
OR 
Export the database and pass the file to helm to import it

@0x0I has an RFC to address persistence in general https://github.com/MinaProtocol/mina/pull/6569.

**Comment by 0x0I** [comment]
Partially resolved by https://github.com/MinaProtocol/coda-automation/pull/486. Seems that we are expecting archive data to be persisted beyond the lifetime of an associated testnet? (if so, requires updating setup to Retain data vs. Delete on claim deletion)
