### ISSUE TITLE
Add the concept of cliff amount to Time Locked Accounts 

### ISSUE THREAD

**Issue by bijanshahrokhi** [MinaProtocol/mina#6603]
We need to enable a time locked account to have a cliff amount that represents the number of tokens that get vested at a particular slot number.

**Comment by psteckler** [comment]
How does that interact with the minimum balance, vesting amount, and vesting period?

**Comment by bijanshahrokhi** [comment]
e.g.  
Imagine the following: 
initial_minimum_balance = 90,000 
cliff time = 1,000
cliff amount = 20,000
vesting_period time = 5
a vesting_increment = 250
Here will be sequence of events: 
- at slots 0 to 1,000, user balance cannot go below 90,000
- at slot 1,000, 20,000 tokens get unlocked and user's new min balance becomes 70,000. 
- starting slot 1,001, the min balance starts decreasing at the ratio of 250/5=50 tokens per slot. So, min at 1,001 will be 69,950. at 1,002, it will be 69,900.

**Comment by psteckler** [comment]
Done, long ago.
