### ISSUE TITLE
Build enhancement: sanity checking

### ISSUE THREAD

**Issue by mobileink** [MinaProtocol/mina#6625]
The current build system depends on a local opam installation, which leaves it vulnerable to at least two kinds of misconfiguration:

* permissions
* package versions

A little sanity checking can reduce the cost of both by detecting the conditions and issuing a user-understandable error message.

Legacy: update `scripts/setup-opam.sh`, or maybe better, create `scripts/sanity-check.sh`.
Bazel: add sanity checking the bootstrap code.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
