### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by gretzke** [MinaProtocol/mina#6627]
I was following these instructions: https://gist.github.com/lk86/cff55a960262de9173741c4c49c4e250

When starting the daemon it crashes directly again. I'm on ubuntu 18.04.

[crash_report.tar.gz](https://github.com/MinaProtocol/mina/files/5512740/crash_report.tar.gz)

**Comment by aneesharaines** [comment]
{"timestamp":"2020-11-09 18:44:42.377378Z","level":"Fatal","source":{"module":"Init__Coda_run","location":"File \"src/app/cli/src/init/coda_run.ml\", line 575, characters 2-26"},"message":"Unhandled top-level exception: $exn\nGenerating crash report","metadata":{"exn":"(monitor.ml.Error\n  (Failure\n    \"Could not read the URS from disk; its format did not match the expected format\")\n

**Comment by gretzke** [comment]
removing `/tmp/s3_cache_dir` directory seems to have fixed the problem. The source of the issue seems to be that I aborted some downloads on the first run of the daemon.

**Comment by gretzke** [comment]
`KEYPATH` was not exported in my screen path
