### ISSUE TITLE
Node reports "synced" to block height 431 despite network being on block height 488

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#6628]
After bootstrapping for one hour, node marked itself as "synced" to block height 431, instead of 488, where the network actually is.

When another block was produced, the state changed to "Catchup" to 490. However its odd that it was in status Synced until a new block was produced.

[status synced at height 431](https://www.dropbox.com/s/mzqb9ph4s81qa9e/status-after.txt?dl=0)
[status after, syncing to 490](https://www.dropbox.com/s/5mbmvnz2skf1lnm/status.txt?dl=0)
[coda log](https://www.dropbox.com/s/dnsoi4so4t9avln/coda-log.txt?dl=0)

**Comment by aneesharaines** [comment]
Sync status is currently not accurate.

There have been a few ways proposed to fixed this... distance based catchup and a staleness check.

**Comment by aneesharaines** [comment]
I think we can close this, we've take a couple of fixes to improve sync status.  Can you reopen if you see this again?
