### ISSUE TITLE
Coda Daemon crashed

### ISSUE THREAD

**Issue by erknfe** [MinaProtocol/mina#6632]
The Coda Protocol developers would like to know why!
(Details are in the log file)

[coda_crash_report_2020-11-10_00-25-05.714688.tar.gz](https://github.com/MinaProtocol/mina/files/5514044/coda_crash_report_2020-11-10_00-25-05.714688.tar.gz)

**Comment by mrmr1993** [comment]
The daemon is crashing because it can't open `/home/erknfe/keys/my-wallet`. Can you check that the file exists and has the right permissions?

**Comment by erknfe** [comment]
Hi, yes the file is exist. What shoul be the permission? Currently 700.

**Comment by mrmr1993** [comment]
700 seems right.

Are you running the daemon in a docker image or on a remote server? If so, you will have to use the `account import` command to add the keys, and then use the `client set-staking` command to set the public key you want to use.

**Comment by erknfe** [comment]
@mrmr1993 I imported an existing account:

![c1](https://user-images.githubusercontent.com/7534459/98670783-466a3780-2364-11eb-9c0c-99c27afa1889.PNG)

then I trying to run daemon with the command on qa-steps-11-07-2020.md document:

![c2](https://user-images.githubusercontent.com/7534459/98670996-a365ed80-2364-11eb-8368-10c502fa5f74.PNG)

then I getting this error:

![c3](https://user-images.githubusercontent.com/7534459/98671034-b5e02700-2364-11eb-814a-c6273980812b.PNG)


Currently, I think solved permission issue but the problem is ongoing.

**Comment by mrmr1993** [comment]
Sorry, it seems that `accounts import` only works locally too. I'll adjust the command to allow for uploading keys to a remote daemon, but for now you may have to upload the keys manually, and then pass that path to the daemon.

**Comment by erknfe** [comment]
SOLVED!

After rebooting the system, the KEYPATH and CODA_PRIVKEY_PASS variables are reset. I tried again by defining them. Until now, it did not give any error. I'm waiting for it to catchup.

**Comment by mrmr1993** [comment]
We've improved the error messages around this, and this appears to be a configuration error rather than a logic error. Closing.
