### ISSUE TITLE
Set rotate limit for coda log

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#6645]

**Comment by deepthiskumar** [comment]
Currently we rotate between two log files coda.log and coda.log.0 where each has a max size of ~500MB
If we reduce the max size per log then we'll have to increase the number of log files as well.
Should we do a max size of 50MB and 20 log files for the same amount of log data?

**Comment by lk86** [comment]
50MB max size sounds good and should be much easier to share than the pair of 500MB files, but I worry about the .0, .1, etc. as a naming scheme.

For rotation i'm used to seeing a timestamp or datestamp on the filenames, but that's cleaner for daily rotation as opposed to max file size. If we generate a new file every time the daemon starts + every time the max size is reached, plus a date+time for when the file was created, it would more easily allow for unlimited logfiles and the code would not have to monitor how many files have been created so far or what all of the filenames are.

**Comment by bkase** [comment]
> but that's cleaner for daily rotation as opposed to max file size
we should just be careful that we don't accidentally fill the disk of our users if we accidentally have extra noisy logs. I think we need to catch max-size too
