### ISSUE TITLE
Problem running qa-test

### ISSUE THREAD

**Issue by edsphinx** [MinaProtocol/mina#6651]
discord user: edsphinx#9404

Running this docker image:
codaprotocol/coda-daemon:0.0.16-beta7-4.1-pre-release-78f7aaa

with the following string:
docker run -d --name mina-qa-test -p 8302:8302 -p 8303:8303 --restart always codaprotocol/coda-daemon:0.0.16-beta7-4.1-pre-release-78f7aaa daemon -peer-list ~/pickles-public-peers.txt -config-file ~/daemon.json -generate-genesis-proof true -log-json -log-level Debug -block-producer-key "${KEYPATH}" | coda-logproc | tee ~/coda-log.txt

The container starts but keep crashing and the crash report is changing every few seconds.

I including attached the coda-log.txt and the coda_crash_report

[coda-log.txt](https://github.com/MinaProtocol/mina/files/5521249/coda-log.txt)

[coda_crash_report_2020-11-11_02-02-35.131613.tar.gz](https://github.com/MinaProtocol/mina/files/5521232/coda_crash_report_2020-11-11_02-02-35.131613.tar.gz)

**Comment by garethtdavies** [comment]
```"Exception":"(monitor.ml.Error\n  (Unix.Unix_error \"No such file or directory\" open\n    \"((filename /Users/fonseca/daemon.json)```

`daemon.json` and `pickles-public-peers.txt` do not exist within this container. You should download and mount them in. For example assuming they are in the current directory adding something like `--mount type=bind,source="$(pwd)"/pickles-public-peers.txt,target=/root/pickles-public-peers.txt` will work.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
