### ISSUE TITLE
Invalid Keypair Permissions Crash

### ISSUE THREAD

**Issue by sandhao** [MinaProtocol/mina#6654]
[coda_crash_report_2020-11-11_13-00-05.457919.tar.gz](https://github.com/MinaProtocol/mina/files/5524128/coda_crash_report_2020-11-11_13-00-05.457919.tar.gz)

**Comment by garethtdavies** [comment]
@sandhao you need to set the permissions correctly on the private keyfile.

```
Corrupted coda keypair: insecure permissions on `/usr/local/bin/my-wallet`. They should be 0600, they are 777\\\n  \\nHint: chmod 600 /usr/local/bin/my-wallet\\\
```

**Comment by gnosed** [comment]
[coda_crash_report_2020-11-11_18-25-43.776950.tar.gz](https://github.com/MinaProtocol/mina/files/5526018/coda_crash_report_2020-11-11_18-25-43.776950.tar.gz)

**Comment by garethtdavies** [comment]
@gnosed this is a seperate issue can you open a new one. 

```
"level":"Fatal","source":{"module":"Init__Coda_run","location":"File \"src/app/cli/src/init/coda_run.ml\", line 575, characters 2-26"},"message":"Unhandled top-level exception: $exn\nGenerating crash report","metadata":{"exn":"(monitor.ml.Error\n  (Failure \"bin_read_t: version read 2 does not match expected version 1\")\n
```

**Comment by garethtdavies** [comment]
@gnosed looks like yours is covered here https://github.com/MinaProtocol/mina/issues/6623

**Comment by gnosed** [comment]
@garethtdavies Yes, removing the .coda-config, fixed the problem. Thanks!

**Comment by mrmr1993** [comment]
The error message and instructions should be much clearer in the next network due to #6741. Will close this once that PR has merged into the develop branch.
