### ISSUE TITLE
QA. Crash with "Segmentation fault" error

### ISSUE THREAD

**Issue by icohigh** [MinaProtocol/mina#6718]
I have run a node in docker. 
After 2 days of continuous work, the node crashed with an `Segmentation Fault` error. 
Restart did not help to launch the node again. Crashed immediately with various errors.

It was possible to restart only after deleting the folder `.coda-config`. 

Full logs including errors from the start of the node below.
[Logs in Google Drive](https://drive.google.com/drive/folders/1BepHR9VRKnLWtE7QwvZiPVL1QRkVrE2A?usp=sharing)

Work of a node in ~4 days.
Link to [My wallet](https://minaexplorer.com/wallet/B62qpSphT9prqYrJFio82WmV3u29DkbzGprLAM3pZQM2ZEaiiBmyY82).

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
