### ISSUE TITLE
[Fatal] Unhandled top-level exception: $exn

### ISSUE THREAD

**Issue by guillaumecote** [MinaProtocol/mina#6761]
Received this Fatal Error (see attached logs) when attempting to build docker image.

Os: Ubuntu 20.10
Docker: 19.03.13

[mina-log.txt](https://github.com/MinaProtocol/mina/files/5564249/mina-log.txt)

**Comment by garethtdavies** [comment]
What image are you using is it `minaprotocol/mina-daemon-baked:4.1-turbo-pickles-mina757342b-auto811bf26`?

**Comment by guillaumecote** [comment]
Yes, I followed the steps found [here](https://minaprotocol.com/docs/connecting). Only issue I had in the process is that I had to manually create the coda-config folder with `mkdir $HOME/.coda-config
`

**Comment by evstigneeff** [comment]
Same problem here with docker image:

2020-11-19 04:16:34 UTC [Info] Using the compiled constraint constants
2020-11-19 04:16:34 UTC [Info] Genesis proof file $path does not exist
        path: "/root/.coda-config/genesis/genesis_proof_c752a00ff08ecbaaf49f82b48a3d856e0e6a25236f1cf9c068207962b219885d"
2020-11-19 04:16:34 UTC [Info] Found genesis proof file at $path
        path: "/var/lib/coda/genesis_proof_c752a00ff08ecbaaf49f82b48a3d856e0e6a25236f1cf9c068207962b219885d"
2020-11-19 04:16:34 UTC [Info] Loaded ledger from $ledger_file and genesis proof from $proof_file
        ledger_file: "/tmp/s3_cache_dir/genesis_ledger_accounts_75ebbd77fc96398b9446729c297bbf40ecb60566c405ba0d30b21be8ceef0757_c5315f18a67b81e9b804768ef8311b6455ee7822584ff385adf0b41
694c32745.tar.gz"
        proof_file: "/var/lib/coda/genesis_proof_c752a00ff08ecbaaf49f82b48a3d856e0e6a25236f1cf9c068207962b219885d"
+ echo 'Coda process exited with status code 1'
+ sleep 10
Coda process exited with status code 1
2020-11-19 04:16:53 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: {
  "sexp": [ "Failure", "Non-default tokens are disabled" ],
  "backtrace": [
    "Raised at file \"stdlib.ml\", line 33, characters 17-33",
    "Called from file \"src/lib/coda_base/token_id.ml\", line 52, characters 4-71",
    "Called from file \"src/lib/coda_base/token_id.ml\", line 52, characters 4-71",
    "Called from file \"src/lib/coda_state/blockchain_state.ml\", line 13, characters 10-59",
    "Called from file \"src/lib/coda_state/blockchain_state.ml\" (inlined), line 9, characters 6-375",
    "Called from file \"src/lib/coda_state/blockchain_state.ml\", line 9, characters 6-375",
    "Called from file \"src/lib/coda_state/blockchain_state.ml\", line 9, characters 6-375",
    "Called from file \"src/lib/coda_state/blockchain_state.ml\", line 34, characters 6-238",
    "Called from file \"src/lib/coda_state/blockchain_state.ml\", line 34, characters 6-238",
    "Called from file \"src/lib/auxiliary_database/filtered_external_transition.ml\", line 31, characters 10-83",
    "Called from file \"src/lib/auxiliary_database/filtered_external_transition.ml\", line 29, characters 6-220",
    "Called from file \"src/lib/auxiliary_database/filtered_external_transition.ml\", line 29, characters 6-220",
    "Called from file \"src/lib/auxiliary_database/filtered_external_transition.ml\", line 44, characters 8-58",
    "Called from file \"src/lib/auxiliary_database/filtered_external_transition.ml\", line 42, characters 4-261",
    "Called from file \"src/lib/auxiliary_database/filtered_external_transition.ml\", line 42, characters 4-261",
    "Called from file \"src/lib/auxiliary_database/external_transition_database.ml\", line 11, characters 10-75",
    "Called from file \"src/lib/auxiliary_database/external_transition_database.ml\", line 10, characters 8-92",
    "Called from file \"src/lib/auxiliary_database/external_transition_database.ml\", line 10, characters 8-92",
    "Called from file \"src/binable0.ml\", line 108, characters 10-41",
    "Called from file \"src/lib/rocksdb/serializable.ml\", line 44, characters 10-51",
    "Called from file \"src/list.ml\", line 351, characters 13-17",
    "Called from file \"src/lib/auxiliary_database/external_transition_database.ml\", line 72, characters 12-40",
    "Called from file \"src/app/cli/src/coda.ml\", line 922, characters 8-113",
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}
  ]
}


  ☠  Coda Daemon crashed.
   The Coda Protocol developers would like to know why!

    Please:
      Open an issue:
        <https://github.com/CodaProtocol/coda/issues/new>

      Briefly describe what you were doing and attach the crash report /root/.coda-config/coda_crash_report_2020-11-19_04-16-53.710322.tar.gz

    
+ kill 13
+ '[' '!' -f stay_alive ']'
+ exit 0

**Comment by guillaumecote** [comment]
Turns out key files hadn't transferred over properly. I retransferred and it fixed the issue.
