### ISSUE TITLE
Send-payment command is holding and doesn't output any payment ID 

### ISSUE THREAD

**Issue by gnosed** [MinaProtocol/mina#6764]
After executing the following command:
```bash
coda client send-payment -amount 10 -fee 0.1 -receiver $RECEIVER -sender $SENDER
```
The command just stays on hold and doesn't output any payment ID.

Git SHA-1: [DIRTY]757342b6cef510f13cb5ad2fbad97518d6df45df

**Comment by jnuno98** [comment]
I have the same problem!

**Comment by nholland94** [comment]
@gnosed or @jnuno98:

If either of you are still able to recreate this bug, it would be really great if you can recreate this condition, let your node run for a few seconds, and then run `coda advanced export-logs` and attach the tar file it generates to this issue. I'm trying to recreate this locally, but so far I haven't been able to get into the state where the command does not return. With the logs, I may be able to figure out what is going on internally in your daemons.

Thanks in advance.

**Comment by jnuno98** [comment]
I will do it tomorrow morning and send it to you.
London timezone

**Comment by nholland94** [comment]
I think this is the likely culprit https://github.com/MinaProtocol/mina/blob/develop/src/lib/network_pool/network_pool_base.ml#L106.

If this pipe is already full when you submit your transaction, the pipe would drop the transaction (as well as the callback that the client is listening to for transaction status, thus the hang). Will need to think on the best way to resolve this, as making this pipe crash or sync on overwrites seems dangerous as well. We may be able to do something smarter for internally submitted transactions at least, giving them some priority if the network is over saturated with transaction broadcasts.

**Comment by gnosed** [comment]
My node crashed in between and didn't output any crash report  -_- but this is another isssue

@nholland94 No way, to reproduce the bug. 
I tried again, now the command is holding for some minutes and dispatches the payment correctly.
It is certainly due to the saturated network?

**Comment by jnuno98** [comment]
that command `coda advanced export-logs` doesn't work.

I've made a new transactions and it just doesn't do anything after 15 minutes...

Also, my node is running for 9 hours and is still in "catchup"
`Global number of accounts:       1029
Block height:                    2
Max observed block length:       324
Local uptime:                    9h58m50s
Ledger Merkle root:              jwbsTYmyYdNkCbZ5n31bwXFsFQtrE5GCwahayT879TFLV9QbqtL
Protocol state hash:             3NKvH5ETQXZDaVbCFiYPzqcSNaWygADLnLRFnvFAsonBEvAKA3X2
Chain id:                        ef95774fb2ed657da61bfc40a8a148a9c9a202476b539aaf915e6cd81d1ef268
Git SHA-1:                       [DIRTY]757342b6cef510f13cb5ad2fbad97518d6df45df
Configuration directory:         /root/.coda-config
Peers:                           36 (122.115.59.79:8302 47.253.14.41:8302 44.234.88.25:8302 35.237.148.187:10507 5.
188.159.227:8302 88.99.249.251:8302 173.249.16.19:8302 44.233.153.54:8302 35.243.211.158:10001 122.115.59.115:8302 
34.121.64.188:8302 34.222.179.83:8302 149.28.220.31:8302 34.73.206.59:10503 35.178.173.65:8302 142.44.139.163:8302 
35.227.13.96:10001 5.9.9.30:8302 3.137.170.80:8302 173.249.2.99:8302 95.216.223.106:8302 36.189.234.172:8302 195.20
1.82.50:8302 168.119.242.237:8302 47.253.14.99:8302 44.235.91.67:8302 213.136.79.175:8302 161.97.99.82:8302 108.61.
217.20:8302 140.82.10.147:8302 185.186.142.120:8302 13.229.139.95:8302 35.238.79.1:8302 47.254.85.57:8302 168.119.2
45.252:8302 34.75.103.6:10401)
User_commands sent:              0
SNARK worker:                    None
SNARK work fee:                  25000000
Sync status:                     Catchup
Block producers running:         1 (B62qkGWTdjfFP4PmHpp5EjNgZXXJrDxH3t2B5rdYbSAeS1k5au8ZjKK)
Best tip consensus time:         epoch=0, slot=915
Next block will be produced in:  in 1.053d
Consensus time now:              epoch=0, slot=1052
Consensus mechanism:             proof_of_stake
Consensus configuration:         
        Delta:                     0
        k:                         290
        Slots per epoch:           7140
        Slot duration:             3m
        Epoch duration:            14d21h
        Genesis state timestamp:   2020-11-18 07:11:20.000000Z
        Acceptable network delay:  3m
`

**Comment by jnuno98** [comment]
<img width="881" alt="image" src="https://user-images.githubusercontent.com/36737208/99798141-5e8e4380-2b28-11eb-93b7-ab073e274e66.png">

**Comment by nholland94** [comment]
#6852 being merged should mitigate this issue. I'm logging #6900 as a followup to actually prioritize locally submitted txns, but with #6852, the cli should no longer hang indefinitely, and it should give feedback to the user about the issue. Closing this for now, please log a new issue if this occurs again in the next release we do.
