### ISSUE TITLE
Coda Daemon crashed

### ISSUE THREAD

**Issue by Claudi6020** [MinaProtocol/mina#6765]
First, I entered command number 1, then number 2, and after the command number 3, an error occurred.
![Screenshot (10)](https://user-images.githubusercontent.com/72910800/99654163-c33f9480-2a7b-11eb-8ba8-7d266ea48044.png)

[coda_crash_report_2020-11-19_10-05-12.129069.tar.gz](https://github.com/MinaProtocol/mina/files/5566173/coda_crash_report_2020-11-19_10-05-12.129069.tar.gz)

**Comment by bkase** [comment]
Hey @Claudi6020 , this error is occurring because you're already running mina somewhere in the background. Having said that we can better (1) update the docs and (2) make the error message clearer

**Comment by bkase** [comment]
Closing in favor of #6770
