### ISSUE TITLE
Buffer data too old crashes Verifier or Prover (OOM ?)

### ISSUE THREAD

**Issue by jnuno98** [MinaProtocol/mina#6766]
2020-11-19 11:14:06 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: {
  "sexp": [
    "Failure",
    "invalid log call \"Refusing to rebroadcast Transaction diff of length 1. Verification error: ((rpc_error\\n  (Connection_closed\\n   ((\\\"exn raised in RPC connection Writer.t\\\"\\n     (monitor.ml.Error\\n      (\\\"writer buffer has data older than\\\" (maximum_age 2m)\\n       (beginning_of_buffer\\n         \\\"\\\\001\\\\020rpc_parallel_plain_1\\\\000\\\\254i\\\\012\\\\254\\\\1391\\\\002\\\\001\\\\001\\\\001\\\\001N\\\\003f:+\\\\191\\\\206(\\\\245\\\\253B\\\\127\\\\1302\\\\186\\\\171\\\\240@\\\\161?\\\\143\\\\203\\\\2282\\\\225\\\\128P\\\\217\\\\232\\\\147.\\\\016\\\\001\\\\229\\\\207\\\\188\\\\229\\\\133\\\\021\\\\029EO\\\\210\\\\191Y\\\\001\\\\219\\\\1895+\\\\241^\\\\255:\\\\152\\\\0193m;\\\\207@\\\\253>\\\\2122\\\\001\\\\001\\\\000\\\\001\\\\001\\\\001\\\\001\\\\001\\\\022\\\\237AG0\\\\236\\\\197\\\\148dX\\\\243\\\\169\\\\249\\\\234k\\\\177\\\\tu]\\\\152\\\\252\\\\220\\\\192\\\\207\\\\166\\\\187\\\\166\\\\168\\\\220\\\\174\\\\206\\\\001\\\\001\\\\001\\\\001\\\\159?_\\\\183\\\\240\\\\017\\\\006\\\\\\\\?!\\\\190g\\\\\\n        \\\\np\\\\027\\\\187b\\\\025\\\\017\\\\149\\\\250\\\\231\\\\207\\\\252\\\\017\\\\232C-S\\\\246U\\\\\\\"\\\\001\\\\190(\\\\230\\\\1940\\\\174|\\\\142(VW\\\\148Sx\\\\234\\\\027@\\\\179^\\\\1775\\\\128Bt,R\\\\132\\\\170\\\\179\\\\012K7\\\\001\\\\001\\\\001\\\\022\\\\237AG0\\\\236\\\\197\\\\148dX\\\\243\\\\169\\\\249\\\\234k\\\\177\\\\tu]\\\\152\\\\252\\\\220\\\\192\\\\207\\\\166\\\\187\\\\166\\\\168\\\\220\\\\174\\\\206\\\\001\\\\001\\\\001\\\\001\\\\159?_\\\\183\\\\240\\\\017\\\\006\\\\\\\\?!\\\\190g\\\\\\n        \\\\np\\\\027\\\\187b\\\\025\\\\017\\\\149\\\\250\\\\231\\\\207\\\\252\\\\017\\\\232C-S\\\\246U\\\\\\\"\\\\001\\\\190(\\\\230\\\\1940\\\\174|\\\\142(VW\\\\148Sx\\\\234\\\\027@\\\\179^\\\\1775\\\\128Bt,R\\\\132\\\\170\\\\179\\\\012K7\\\\001\\\\001\\\\001\\\\001\\\\001\\\\001\\\\001\\\\001\\\\001\\\\253P\\\\245\\\\200\\\\000\\\\001\\\\000\\\\001\\\\001\\\\001\\\\001\\\\001\\\\001\\\\001\\\\000\\\\001\\\\000\\\\001\\\\001\\\\001\\\\002\\\\001\\\\001\\\\001\\\\002\\\\001 \\\\169^\\\\127y\\\\172\\\\151\\\\177\\\\169V\\\\131v\\\\206\\\\022j%\\\\203J]9\\\\228\\\\210^D\\\\235u\\\\192\\\\226\\\\131o\\\\243d\\\\246\\\\001\\\\001\\\\001\\\\001\\\\000\\\\252\\\\221\\\\135\\\\217\\\\148a[\\\\176c\\\\252N\\\\195\\\\030\\\\129j31\\\\250\\\\000\\\\252\\\\021\\\\138q\\\\197\\\\221'\\\\136$\\\\252<\\\\210\\\\214wr\\\\163\\\\229Y\\\\000\\\\252j\\\\201\\\\014\\\\212\\\\159\\\\242\\\\030|\\\\252\\\\202\\\\163\\\\144qG\\\\183!\\\\219\\\\000\\\\001\\\\000\\\\252\\\\249\\\\024E\\\\157\\\\245\\\\162\\\\152\\\\198\\\\252\\\\191_h\\\\195\\\\185\\\\186\\\\182\\\\201\\\\000\\\\001\\\\000\\\\139\\\\230\\\\215\\\\165\\\\025 \\\\146\\\\236\\\\184\\\\138\\\\220\\\\167nld\\\\225_\\\\144\\\\234\\\\228*c\\\\0238YF(\\\\233\\\\153\\\\22686\\\\001\\\\0004\\\\016L\\\\172Uy\\\\245\\\\228\\\\225\\\\187\\\\188\\\\187\\\\005\\\\168\\\\211\\\\217=Qr+\\\\027\\\\228\\\\153\\\\244\\\\184i\\\\202\\\\129L\\\\004\\\\003*\\\\001\\\\000\\\\252#\\\\130\\\\t\\\\001\\\\155\\\\1474\\\\197\\\\252U8\\\\167)\\\\149\\\\018~\\\\143\\\\000\\\\001\\\\001\\\\000\\\\252Sm\\\\215r\\\\204\\\\133\\\\020\\\\215\\\\252\\\\173\\\\181\\\\232,\\\\153U\\\\218\\\\224\\\\000\\\\001\\\\001\\\\000\\\\252Q\\\\198\\\\200\\\\232\\\\171<&\\\\242\\\\252\\\\184\\\\017KA*\\\\255\\\\136e\\\\000\\\\001\\\\001\\\\000\\\\252\\\\173\\\\163\\\\216\\\\128\\\\212\\\\227\\\\233\\\\140\\\\252\\\\239Wfk$\\\\245Yq\\\\000\\\\001\\\\001\\\\000\\\\252\\\\145\\\\222>\\\\179<\\\\027mM\\\\252\\\\015\\\\177\\\\242\\\\130\\\\242G\\\\192\\\\t\\\\000\\\\001\\\\001\\\\000\\\\252\\\\136\\\\145\\\\243\\\\163\\\\b\\\\2046\\\\177\\\\252\\\\017\\\\199\\\\023\\\\160\\\\027\\\\214\\\\152\\\\t\\\\000\\\\001\\\\001\\\\000\\\\252G\\\\214\\\\167\\\\188\\\\216\\\\\\\"0J\\\\252\\\\239\\\\186\\\\024xP|]n\\\\000\\\\001\\\\001\\\\000\\\\252\\\\215\\\\024\\\\006T\\\\248v\\\\224l\\\\252\\\\170\\\\178\\\\158\\\\211\\\\250`xj\\\\000\\\\001\\\\001\\\\000\\\\252FDd\\\\139\\\\181\\\\158\\\\248\\\\155\\\\252iv=\\\\247YE\\\\143\\\\142\\\\000\\\\001\\\\001\\\\000\\\\252\\\\167\\\\223\\\\228*\\\\166C\\\\229\\\\195\\\\252\\\\237\\\\244\\\\239\\\\209B\\\\142\\\\182`\\\\000\\\\001\\\\001\\\\000\\\\252\\\\127\\\\137\\\\253\\\\193\\\\245\\\\225f\\\\004\\\\252\\\\237\\\\228e\\\\023K\\\\227S\\\\241\\\\000\\\\001\\\\001\\\\000\\\\252an\\\\165J\\\\\\n        \\\\n\\\\136\\\\153O\\\\2521\\\\165\\\\236\\\\027\\\\232\\\\243\\\\154\\\\174\\\\000\\\\001\\\\001\\\\000\\\\252\\\\012\\\\031\\\\236^`e\\\\145\\\\203\\\\252h|L\\\\002|\\\\228\\\\223p\\\\000\\\\001\\\\001\\\\000\\\\252\\\\211\\\\186\\\\215\\\\004a\\\\2195\\\\209\\\\252\\\\153Yj\\\\03059U\\\\014\\\\000\\\\001\\\\001\\\\000\\\\252\\\\155r,\\\\200\\\\182\\\\237\\\\187\\\\027\\\\252\\\\001OO\\\\214\\\\207\\\\198\\\\020\\\\215\\\\000\\\\001\\\\001\\\\000\\\\252\\\\133\\\\001\\\\219\\\\139d\\\\024<\\\\019\\\\252\\\\0114\\\\226\\\\006~L\\\\026R\\\\000\\\\001\\\\001\\\\000\\\\252=\\\\201R\\\\235\\\\224\\\\233FA\\\\252\\\\168\\\\224wh\\\\207+\\\\129 \\\\000\\\\001\\\\001\\\\000\\\\252eX)\\\\200\\\\020\\\\222`\\\\014\\\\252\\\\238j\\\\026\\\\226\\\\206\\\\031\\\\241<\\\\000\\\\001\\\\001\\\\000\\\\252-\\\\160\\\\174\\\\030\\\\029\\\\141\\\\198\\\\172\\\\252\\\\212\\\\151\\\\0162\\\\245\\\\180\\\\239\\\\198\\\\000\\\\000\\\\001\\\\000\\\\001\\\\252\\\\019\\\\187\\\\172\\\\177\\\\175\\\\\\\"\\\\175\\\\184\\\\252P8\\\\241\\\\160$\\\\214\\\\245\\\\189\\\\252\\\\\\\\\\\\140\\\\137\\\\011\\\\2167\\\\021c\\\\252\\\\226\\\\179/\\\\141)F\\\\017\\\\023\\\\000\\\\\\\"\\\\154\\\\170\\\\230\\\\249\\\\012\\\\025F\\\\019q\\\\164\\\\251[\\\\020\\\\225\\\\239\\\\018'\\\\252\\\\181J\\\\232B\\\\189kv\\\\156\\\\245M4A*-\\\\168\\\\1472r\\\")\\n       (writer\\n        ((id 76)\\n         (fd\\n          ((file_descr 41)\\n           (info\\n            (replaced\\n             ((\\\"connected to\\\" 127.0.0.1:42575)\\n              (previously_was\\n               (replaced\\n                ((socket (bound_on 0.0.0.0:0))\\n                 (previously_was\\n                  (socket ((family PF_INET) (socket_type SOCK_STREAM))))))))))\\n           (kind (Socket Active)) (supports_nonblock true)\\n           (have_set_nonblock true) (state (Open Empty))\\n           (watching ((read (Watch_once Empty)) (write (Watch_once Empty))))\\n           (watching_has_changed false) (num_active_syscalls 2)\\n           (close_finished Empty)))\\n         (monitor\\n          (((name (id 1827)) (here ()) (id 1827) (has_seen_error false)\\n            (is_detached true))\\n           ((name \\\"\\\") (here ()) (id 178) (has_seen_error false)\\n            (is_detached true))))\\n         (inner_monitor\\n          (((name (id 1828)) (here ()) (id 1828) (has_seen_error false)\\n            (is_detached true))\\n           ((name \\\"\\\") (here ()) (id 178) (has_seen_error false)\\n            (is_detached true))))\\n         (background_writer_state Running) (background_writer_stopped Empty)\\n         (syscall Per_cycle) (bytes_received 15165952)\\n         (bytes_written 13234949) (scheduled_bytes 1864848)\\n         (scheduled_back 0) (back 66155) (close_state Open)\\n         (close_finished Empty) (close_started Empty)\\n         (num_producers_to_flush_at_close 0)\\n         (flush_at_shutdown_elt (<opaque>))\\n         (check_buffer_age\\n          (((writer <opaque>) (maximum_age 2m)\\n            (bytes_received_at_now_minus_maximum_age 13764466)\\n            (bytes_received_queue\\n             (13780714 13793434 13793443 13793452 13821120 13836076 13919406\\n              13949637 14007535 14080055 14095027 14095355 14095681 14095690\\n              14110654 14125602 14125926 14125935 14151379 14206715 14221663\\n              14234383 14283386 14296115 14296441 14296450 14309170 14361511\\n              14446751 14534211 14594012 14677032 14763266 14864588 14909782\\n              14922502 14922511 14922837 14935561 14950509 14950518 14953148\\n              14965868 14991308 15046677 15061625 15087069 15125229 15137949\\n              15165626 15165952))\\n            (times_received_queue\\n             ((2020-11-19 11:09:20.754313668Z)\\n              (2020-11-19 11:09:23.523024043Z)\\n              (2020-11-19 11:09:24.523078351Z)\\n              (2020-11-19 11:09:34.179563027Z)\\n              (2020-11-19 11:09:40.364487209Z)\\n              (2020-11-19 11:09:41.364658227Z)\\n              (2020-11-19 11:09:44.683111508Z)\\n              (2020-11-19 11:09:47.581881197Z)\\n              (2020-11-19 11:09:48.690596191Z)\\n              (2020-11-19 11:09:50.038057675Z)\\n              (2020-11-19 11:09:52.038538440Z)\\n              (2020-11-19 11:09:53.038921289Z)\\n              (2020-11-19 11:09:54.039087307Z)\\n              (2020-11-19 11:09:55.039392215Z)\\n              (2020-11-19 11:09:56.249593695Z)\\n              (2020-11-19 11:10:01.484764305Z)\\n              (2020-11-19 11:10:02.485040064Z)\\n              (2020-11-19 11:10:05.485594199Z)\\n              (2020-11-19 11:10:07.804823572Z)\\n              (2020-11-19 11:10:08.974974483Z)\\n              (2020-11-19 11:10:09.975200781Z)\\n              (2020-11-19 11:10:10.975286659Z)\\n              (2020-11-19 11:10:13.258114274Z)\\n              (2020-11-19 11:10:16.715707529Z)\\n              (2020-11-19 11:10:21.716763660Z)\\n              (2020-11-19 11:10:25.717372403Z)\\n              (2020-11-19 11:10:28.791656544Z)\\n              (2020-11-19 11:10:32.456387851Z)\\n              (2020-11-19 11:10:34.245978176Z)\\n              (2020-11-19 11:10:35.845344909Z)\\n              (2020-11-19 11:10:38.160864352Z)\\n              (2020-11-19 11:10:39.886562940Z)\\n              (2020-11-19 11:10:41.418236166Z)\\n              (2020-11-19 11:10:43.195595792Z)\\n              (2020-11-19 11:10:44.195802810Z)\\n              (2020-11-19 11:10:45.380222330Z)\\n              (2020-11-19 11:10:46.380313438Z)\\n              (2020-11-19 11:10:48.380887675Z)\\n              (2020-11-19 11:10:49.381158353Z)\\n              (2020-11-19 11:10:54.863045914Z)\\n              (2020-11-19 11:10:55.863259882Z)\\n              (2020-11-19 11:10:59.864787694Z)\\n              (2020-11-19 11:11:02.316322462Z)\\n              (2020-11-19 11:11:04.877730654Z)\\n              (2020-11-19 11:11:06.071327084Z)\\n              (2020-11-19 11:11:07.071596362Z)\\n              (2020-11-19 11:11:12.072789404Z)\\n              (2020-11-19 11:11:13.512197784Z)\\n              (2020-11-19 11:11:14.512452882Z)\\n              (2020-11-19 11:11:16.815240485Z)\\n              (2020-11-19 11:11:17.815428553Z)))\\n            (bytes_seen 15165952) (too_old (Full ())))))\\n         (consumer_left Empty) (raise_when_consumer_leaves false)\\n         (open_flags (Full (Ok (rdwr nonblock)))) (line_ending Unix))))\\n      (\\\"Caught by monitor (id 1827)\\\"))))))\\n (connection_description (\\\"Client connected via TCP\\\" (localhost 42575)))\\n (rpc_tag rpc_parallel_plain_0) (rpc_version 0))\""
  ],
  "backtrace": [
    "Raised at file \"format.ml\" (inlined), line 242, characters 35-52",
    "Called from file \"format.ml\", line 469, characters 8-33",
    "Called from file \"format.ml\", line 484, characters 6-24"
  ]
}
2020-11-19 11:14:06 UTC [Info] Daemon child process 4205 terminated with exit code 0
2020-11-19 11:14:06 UTC [Error] Child process of kind "Verifier" with pid 4205 has terminated

**Comment by evstigneeff** [comment]
I checked logs and can confirm sometimes "Verifier" process causes node to crash but sometimes it's "Prover"

```
2020-11-19 19:54:01 UTC [Info] Daemon child process 91 terminated after receiving signal "sigkill"
2020-11-19 19:54:01 UTC [Error] Child process of kind "Prover" with pid 91 has terminated
+ kill 12
+ '[' '!' -f stay_alive ']'
+ exit 0
```
AND
```
+ echo 'Coda process exited with status code 99'
+ sleep 10
Coda process exited with status code 99
2020-11-19 20:21:36 UTC [Info] Daemon child process 172 terminated with exit code 0
2020-11-19 20:21:36 UTC [Error] Child process of kind "Verifier" with pid 172 has terminated
+ kill 13
+ '[' '!' -f stay_alive ']'
+ exit 0
```

**Comment by evstigneeff** [comment]
Attaching full log for one of the crashes
[coda.log](https://github.com/MinaProtocol/mina/files/5569859/coda.log)

**Comment by evstigneeff** [comment]
Attaching full log for another one crash ("Child process of kind "Prover" with pid 92 has terminated")
[coda.log](https://github.com/MinaProtocol/mina/files/5570189/coda.log)

**Comment by bkase** [comment]
Thoughts from a small discussion with a handful of folks:
1. Should we remove the auto-killing of the verifier and prover? We seemed to have fix the leaks there.
2. It seems like folks don't see this issue when they have a 32gigs of RAM box. Are there low-hanging fruit performance improvements? Can we capture profiling data from our users in the wild?
3. Are we missing reports of this because of the auto-restarting?

**Comment by jnuno98** [comment]
Actually I am using a 32gb Google cloud machine
Of the general type

**Comment by evstigneeff** [comment]
I also use 8CPU/32GB Google Cloud VPS. But it's worth mentioning that my node has stopped crashing today and it's in-sync now.

**Comment by Cris-F** [comment]
Re: `3. Are we missing reports of this because of the auto-restarting?`
Probably so.  With a quick check to see that node status generally check for `sync`, `Catchup` and time till next block.  Without more detailed check of uptime not easy to see if node when down overnight or while away for a few hours.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
