### ISSUE TITLE
Make it very clear when you're trying to start a mina daemon when one is already running with the same config location

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#6770]
Currently, you get a scary error about a locking issue with a trust database.

We should instead print a clear message to stderr: "You are trying to run the Mina daemon more than once on the same machine with the same config! You probably want to stop the running Mina before running it again" and then exit with a non-zero code.

**Comment by deepthiskumar** [comment]
@mrmr1993 suggests adding a lock file to identify this state
