### ISSUE TITLE
Logging too much Spam for upcalls in libp2p helper

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#6792]
We log 1MB of base64 garbage on validate upcalls (and probably more in some cases). Could this be contributing to performance issues? In any case, it makes our logs too noisy.

**Comment by aneesharaines** [comment]
@bkase  - do you know what exactly we should remove from the logging in this case?

**Comment by nholland94** [comment]
Remaining work: make sure upcalls are going to spam and not trace.
