### ISSUE TITLE
Create time locked accounts

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#6805]
Basic task spec (disabled implementation, minimum possible to avoid hard-fork):
* multiple account timings
  - linked list of timings
  - represent the current timing as a hash in the snark, open it for fee-payer and sender to check timing
  - if timing has expired, open its child hash and store that when updating the ledger
  - unit tests
  - ~1 day
* expose multiple timings to GraphQL, config format for accounts
  - < 1 day
* add a field for the timing+hash to transaction_union, expose the hash in the snarked version
  - < 1 day
* update transaction snark logic for `create_token_account` (and send payment, perhaps?) to set the timing to the hash value provided
  - < 1 day
* unit tests for txn snark
  - < 1 day
* testing
  - ~1 day

Total estimate: 0.5 wks

Finish feature, to enable for release:
* update `create_token_account` (and send payment?) commands to add an optional timing field
  - updating the sparse ledger and transaction logic
  - tests
  - ~1 day
* update transaction pool logic to handle these transactions correctly
  - < 1 day
* GrahpQL endpoint, update CLI
  - < 1 day
* archive node update + testing
  - ~1 day
* rosetta update + testing
  - ~ 1 day
* testing
  - ~ 1 day

Total estimate: 1 wk

**Comment by psteckler** [comment]
Mentioning the constraints I broached on Discord:
- the timings are in cliff-sorted order
- they're disjoint, a timing should fully vest by the cliff time of its successor

**Comment by bkase** [comment]
The tasks look great, I think we should consider the timings for the eng work, but we’ll need to buffer for testing, bug fixing, doing a formal release of Rosetta, etc on top of it

**Comment by bkase** [comment]
We currently have the nice property for mainnet launch that no transactions that can fail are included in blocks (because custom tokens, and snapp transactions are disabled).
 
We still don't need to break this invariant right? We can validate the timing information before it gets added to txn pools right?

**Comment by mrmr1993** [comment]
Yes, we need the invariant that the fee payer can pay to apply for both the txn pool and the txn snark, which implies the no-fail invariant for currently-enabled commands.
