### ISSUE TITLE
Mina 4.1 Daemon is crashed.

### ISSUE THREAD

**Issue by StarLI-Trapdoor** [MinaProtocol/mina#6818]
[coda_crash_report_2020-11-19_13-25-20.278709.tar.gz](https://github.com/MinaProtocol/mina/files/5579201/coda_crash_report_2020-11-19_13-25-20.278709.tar.gz)

The issue is found on machine with the following configuration:
56 core, 128G memory.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
