### ISSUE TITLE
Sync status:  Offline, i cant find snarks and blocks 

### ISSUE THREAD

**Issue by heretikkk** [MinaProtocol/mina#6819]
![2020-11-22_20-47-53](https://user-images.githubusercontent.com/69644077/99911390-10826700-2d05-11eb-8900-da0085588373.png)

i cant find snarks and blocks! 

My VPS have 10 CPU cores, 60 GB RAM, 1 Gbit/s port. its more then required for testnet. but my node os crashed. 

what me need to do? i wait more 1 day. i reinstall my node and not result. i do only many many transaction :)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
