### ISSUE TITLE
coda crashed by Segmentation fault

### ISSUE THREAD

**Issue by celiafxm** [MinaProtocol/mina#6824]
Launch coda testnet4.1 via sudo coda daemon -peer-list-file ~/peers.txt  -external-port 8302. logs are following and attached.

      "target": {
        "data": "4QPZsQhASbc625XJja38Erev7Pw1xjqZ7d5SLFRpz8DE9aR1EBgn",
        "state": {
          "init": "4YxcUuNNDFupnN8vhq6sb7kZasw5xnRdG8RCvjseAEJ389ZL2NiG",
          "curr": "4YyMpDH7GU64mPauDjsNqWyXQ5csapbDRHnYZbJrPrgDSiQMNqrP"
        }
      }
    },
    "fee_excess": [
      { "token": "1", "amount": { "magnitude": "0.3", "sgn": [ "Pos" ] } },
      { "token": "1", "amount": { "magnitude": "0", "sgn": [ "Pos" ] } }
    ],
    "next_available_token_before": "2",
    "next_available_token_after": "2",
    "sok_digest": null
  },
  {
    "source": "jx4y1UUpxr1T5sSbny3WztVSA4JVXp5asw5Hah1SDawQZUaJNeB",
    "target": "jxWEd4FtakY2Ta94fN8syHU11pcu25T7mbDrSqYYd8FLgXGPpX8",
    "supply_increase": "0",
    "pending_coinbase_stack_state": {
      "source": {
        "data": "4QPZsQhASbc625XJja38Erev7Pw1xjqZ7d5SLFRpz8DE9aR1EBgn",
        "state": {
          "init": "4YxcUuNNDFupnN8vhq6sb7kZasw5xnRdG8RCvjseAEJ389ZL2NiG",
          "curr": "4YyMpDH7GU64mPauDjsNqWyXQ5csapbDRHnYZbJrPrgDSiQMNqrP"
        }
      },
      "target": {
        "data": "4QPZsQhASbc625XJja38Erev7Pw1xjqZ7d5SLFRpz8DE9aR1EBgn",
        "state": {
          "init": "4YxcUuNNDFupnN8vhq6sb7kZasw5xnRdG8RCvjseAEJ389ZL2NiG",
          "curr": "4YyMpDH7GU64mPauDjsNqWyXQ5csapbDRHnYZbJrPrgDSiQMNqrP"
        }
      }
    },
    "fee_excess": [
      { "token": "1", "amount": { "magnitude": "0.3", "sgn": [ "Pos" ] } },
      { "token": "1", "amount": { "magnitude": "0", "sgn": [ "Pos" ] } }
    ],
    "next_available_token_before": "2",
    "next_available_token_after": "2",
    "sok_digest": null
  }
]
{"timestamp":"2020-11-20 15:10:20.404672Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 134, characters 12-27"},"message":"Base SNARK generated in $time","metadata":{"pid":4113,"process":"Snark Worker","time":"26.284s"},"event_id":"885328f9dca84fa1cfb99089080613d6"}
{"timestamp":"2020-11-20 15:10:20.404707Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 134, characters 12-27"},"message":"Base SNARK generated in $time","metadata":{"pid":4113,"process":"Snark Worker","time":"27.717s"},"event_id":"885328f9dca84fa1cfb99089080613d6"}
{"timestamp":"2020-11-20 15:10:20.404944Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 217, characters 14-25"},"message":"Submitted completed SNARK work
$work_ids to $address","metadata":{"address":"127.0.0.1:8301","pid":4113,"process":"Snark Worker","work_ids":[157125340,395574298]}}
{"timestamp":"2020-11-20 15:10:20.914288Z","level":"Debug","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 169, characters 8-20"},"message":"Snark worker working directory
$dir","metadata":{"dir":"/home/mina","pid":4113,"process":"Snark Worker"}}
{"timestamp":"2020-11-20 15:10:20.914365Z","level":"Debug","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 181, characters 6-18"},"message":"Snark worker using daemon $addr","metadata":{"addr":"127.0.0.1:8301","pid":4113,"process":"Snark Worker"}}
{"timestamp":"2020-11-20 15:10:21.364365Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 201, characters 10-21"},"message":"SNARK work $work_ids received from $address. Starting proof generation","metadata":{"address":"127.0.0.1:8301","pid":4113,"process":"Snark Worker","work_ids":[1006141948,276626342]}}
Segmentation fault

[coda.log](https://github.com/MinaProtocol/mina/files/5581413/coda.log)

**Comment by mrmr1993** [comment]
Thanks for reporting! I've opened PR #6833 to fix this; I've included a brief write-up of the underlying bug there.
