### ISSUE TITLE
'coda client status' appears to hang at times

### ISSUE THREAD

**Issue by gregbostrom** [MinaProtocol/mina#6828]
coda client status' appears to hang at times.  So I started timing it with the time command.

Here is an instance when it appeared to hang but did finish.
```
real	1m18.501s
user	0m0.216s
sys	0m0.080s
```

And here is an instance where the response was snappy.
```
real	0m0.336s
user	0m0.180s
sys	0m0.040s
```

**Comment by gregbostrom** [comment]
Another example of untimely response.
```
real	1m5.110s
user	0m0.208s
sys	0m0.072s
```

**Comment by gregbostrom** [comment]
With version
```
[DIRTY]7f0440c609bfd1e2bc4130f06d09f72763c25b67
```
just witnessed
```
real	33m45.537s
user	0m1.864s
sys	0m1.060s
```

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
