### ISSUE TITLE
QATF Crash no warning / no unusual errors [DIRTY]8245234f4bd578b7659ea9e193c417cf9d62ef86 

### ISSUE THREAD

**Issue by jrwashburn** [MinaProtocol/mina#6840]
Crash while (I think) still in catchup on new build ef86.

Running with 
coda daemon -peer-list-file /root/peers.txt -generate-genesis-proof true -log-level Info -work-selection seq -run-snark-coordinator B62qp...

[coda_crash_report_2020-11-24_01-27-50.451959.tar.gz](https://github.com/MinaProtocol/mina/files/5586838/coda_crash_report_2020-11-24_01-27-50.451959.tar.gz)

[2020-11-24_01-30-12.tar.gz](https://github.com/MinaProtocol/mina/files/5586840/2020-11-24_01-30-12.tar.gz)

**Comment by jrwashburn** [comment]
From another (32c/64G) node- crashed this am. Did not finish creating crash files.
[jrwashburn-qatf-crash-202011240848.tar.gz](https://github.com/MinaProtocol/mina/files/5590123/jrwashburn-qatf-crash-202011240848.tar.gz)

**Comment by jflowers1974** [comment]
Also crashed, in Block producer only ( was sync'ed for a couple of hours ).  Same'ish issue - running then crashed sometime last night...


[coda_crash_report_2020-11-24_10-31-50.086135.tar.gz](https://github.com/MinaProtocol/mina/files/5590957/coda_crash_report_2020-11-24_10-31-50.086135.tar.gz)

**Comment by jrwashburn** [comment]
Updated logs from crash on [DIRTY]4a053a4fba333c61ec4e278f8430f581a439630f - similar symptoms, crash without error. Archived logs immediately prior to crash manually. (Screenshot timeline is EST.)
Digital Ocean dedicated 32vcpu/64GB

[mina_4-1_jrwashburn_crash_202012010950.tar.gz](https://github.com/MinaProtocol/mina/files/5622904/mina_4-1_jrwashburn_crash_202012010950.tar.gz)
[mina-best-tip.0.log](https://github.com/MinaProtocol/mina/files/5622907/mina-best-tip.0.log)
<img width="866" alt="Screen Shot 2020-12-01 at 8 35 20 AM" src="https://user-images.githubusercontent.com/891888/100747768-78454b80-33b0-11eb-9ddc-1a847a9d04dc.png">

**Comment by jrwashburn** [comment]
Presumably resolved - has not reoccurred post qatf for 4.1.
