### ISSUE TITLE
Crash report: Unhandled top-level exception: $exn

### ISSUE THREAD

**Issue by jimcase** [MinaProtocol/mina#6869]
<img width="897" alt="Captura de pantalla 2020-11-28 a las 18 49 26" src="https://user-images.githubusercontent.com/9588549/100522786-c2a9ab00-31ab-11eb-9e0e-cd7aac53b598.png">

[View logs](https://drive.google.com/file/d/1Usl7clUtqMegcxCV8aNJuodHPgdpTDDQ/view?usp=sharing)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
