### ISSUE TITLE
Expose timestamp start index via GraphQL and consume in Rosetta

### ISSUE THREAD

**Issue by omerzach** [MinaProtocol/mina#6872]
Version 1.4.7 of Rosetta adds a `timestamp_start_index` option. This isn't exposed via GraphQL yet so we'll leave it as `None` for now, but should return and set it correctly (In `network.ml`) when possible.

> "If populated, `timestamp_start_index` indicates the first block index where block timestamps are considered valid (i.e. all blocks less than `timestamp_start_index` could have invalid timestamps). This is useful when the genesis block (or blocks) of a network have timestamp 0. If not populated, block timestamps are assumed to be valid for all available blocks."

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
