### ISSUE TITLE
Coda Daemon crashed multiple times: error: could not lock config file /home/ubuntu/.gitconfig: File exists

### ISSUE THREAD

**Issue by Laxsuperrich** [MinaProtocol/mina#6886]
I just tried newly updated one to run, but resulted in crashing-roop.

There were some types of error messages like below.
```
mina.service: Main process exited, code=exited, status=1/FAILURE
mina.service: Failed with result 'exit-code'.
could not lock config file /home/ubuntu/.gitconfig: File exists

```
Here is the crashing-report.
[crash.zip](https://github.com/MinaProtocol/mina/files/5620528/crash.zip)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
