### ISSUE TITLE
Bootstrap even in epoch1 (remove edge case)

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#6898]

**Comment by aneesharaines** [comment]
@imeckler  and @bkase  - can you and more information on what you discussed here?

**Comment by bkase** [comment]
The discussion here was that we thought it would be faster to avoid bootstrap when possible and just catchup -- so we special cased epoch1. Our new hypothesis is that it would be better to just remove the special case.

I'm updating the title to reflect this

**Comment by nholland94** [comment]
Can happen after a hard fork, which seems undesirable. We should think about a better way to encode this rule. Shrinking from `2k` to `k` seems like it might suffice before mainnet.

**Comment by ghost-not-in-the-shell** [comment]
I don't remember there is a special rule for the genesis epoch. Bootstrap would only be triggered if we received a block that is more than 2k away from us. There's no special case for the first epoch.
