### ISSUE TITLE
Archive node needs to support storing blocks with missing parents (replace with state_hash)

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#6907]
From deepthi:

> If the parent of a block is not in it already then it'll fail. So adding blocks after bootstrap will fail. We need the parent_id to successfully get the chain from the current best tip to genesis
> Having the parent state hash alongside the parent id (and removing the non null constraint on parent_id) would help a bit. So there's always a statehash to look up when we want to make that link. The missing blocks will still have to be added separately from another database

However, we should support this and allow patching up the missing bits later. Otherwise, if you're disconnected only for a short while you'll never be able to store data until you get those missing bloocks.

**Comment by psteckler** [comment]
Closed by #6926.
