### ISSUE TITLE
Transition_router.load_frontier fails with an unhelpful error message

### ISSUE THREAD

**Issue by zhong5434161** [MinaProtocol/mina#6908]
Summary:
{"num_accounts":null,"blockchain_length":null,"highest_block_length_received":1,"uptime_secs":52,"ledger_merkle_root":null,"state_hash":null,"chain_id":"ef95774fb2ed657da61bfc40a8a148a9c9a202476b539aaf915e6cd81d1ef268","commit_id":"[DIRTY]757342b6cef510f13cb5ad2fbad97518d6df45df","conf_dir":"/root/.coda-config","peers":["34.73.199.61:10501","34.73.254.106:10001","34.75.104.31:10508","34.75.117.40:10516","34.74.76.116:10512","34.75.117.19:10511"],"user_commands_sent":0,"snark_worker":null,"snark_work_fee":25000000,"sync_status":"Bootstrap","block_production_keys":["B62qqcdqR6wKpqgobgzniZ7f891bRgWDw36WMpfg1yQ7ARYxYiyCfZR"],"histograms":{"rpc_timings":{"get_staged_ledger_aux":{"dispatch":null,"impl":null},"answer_sync_ledger_query":{"dispatch":null,"impl":null},"get_ancestry":{"dispatch":null,"impl":null},"get_transition_chain_proof":{"dispatch":null,"impl":null},"get_transition_chain":{"dispatch":null,"impl":null}},"external_transition_latency":null,"accepted_transition_local_latency":null,"accepted_transition_remote_latency":null,"snark_worker_transition_time":null,"snark_worker_merge_time":null},"consensus_time_best_tip":null,"next_block_production":null,"consensus_time_now":{"slot_number":"6676","slots_per_epoch":"7140"},"consensus_mechanism":"proof_of_stake","consensus_configuration":{"delta":0,"k":290,"slots_per_epoch":7140,"slot_duration":180000,"epoch_duration":1285200000,"genesis_state_timestamp":"1605683480000","acceptable_network_delay":180000},"addrs_and_ports":{"external_ip":"35.233.253.169","bind_ip":"0.0.0.0","peer":{"host":"0.0.0.0","libp2p_port":8302,"peer_id":"12D3KooWPyfoP8WMvHryW5evf3Zae8Lkks9RSJAbdmWHBFCgDBF2"},"libp2p_port":8302,"client_port":8301}}
Status:
{"OS_type":"Unix","Release":"5.4.0-1030-gcp","Machine":"x86_64","Sys_name":"Linux","Exception":{"sexp":["Failure","failed to initialize transition frontier: Staged_ledger.of_scan_state_and_ledger : did not connect with snarked ledger hash"],"backtrace":["Raised at file \"stdlib.ml\", line 33, characters 17-33","Called from file \"src/deferred1.ml\", line 17, characters 40-45","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47"]},"Command":"Command: (coda daemon -peer-list-file /root/peers.txt -block-producer-key\n /root/keys/my-wallet -block-producer-password tang5434\n -generate-genesis-proof true)","Coda_branch":"HEAD","Coda_commit":"[DIRTY]757342b6cef510f13cb5ad2fbad97518d6df45df"}

**Comment by TheUnity** [comment]
Remove .coda-config directory and restart daemon

**Comment by mrmr1993** [comment]
The potential solutions here are
* make the error messages user readable, add a suggestion to clear out persisted data
* attempt to recover automatically by deleting the persisted data and trying again
* both (in case clearing the persisted data didn't fix the issue, or it didn't exist)
