### ISSUE TITLE
0 transfers are made.

### ISSUE THREAD

**Issue by donadel01** [MinaProtocol/mina#6938]
code : 

coda client send-payment \
>   -amount 0 \
>   -receiver B62qkSLRRLB4smdHYDvkxmBXnuRVdThr9a8ZihU7RYrEg5T8VMwHxyB \
>   -fee 0.1 \
>   -sender B62qkSLRRLB4smdHYDvkxmBXnuRVdThr9a8ZihU7RYrEg5T8VMwHxyB
Dispatched payment with ID 3K8w9fHFeLZZaDxWiF9vGFEXmq8NcXVUN1RQgAJZu32ECY6HhyZHVrCFxPVAGs2NLaaj5UDhfQ8LDgTw7iWiM3MLZcHGyGpaBptzPc3f3HTyUvfYRU9yoAWnjxRsDKiYjbR3JC8291iZGj5GnL4Gq9GfrXZxEG17u4rXFuNaKeb9rprVW8VXZ89A82ks9fVtg1rbBWPqMbeProvnQL7ua9nU3FaE5TLqWvjwpHkiSopeHQ8qodoJdWxUxB2HBcAoa5BwCAxXm8tB3us15e5C1muV2o9RDwMPMXMrL33PofgV2v2mTMd3FZrBVNRsARaDFeCL3SLwbSgfgJqEmnCWrh37VcEsCU4JNWgRxy1a6ergS4jgmR7DKZPVs2yyzAk9EKK4

0 transfers are made. this is subject to commission fees.

**Comment by mrmr1993** [comment]
This is as intended. See comment on #6937. Closing.
