### ISSUE TITLE
We need a mechanism to stop the async jobs of created by the transaction_pool and its attached transition frontier is outdated

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#6946]
In #6935, the seed nodes first enters transition_frontier_controller mode and started the transaction_pool with the old transition frontier. After a while it entered bootstrap mode, and threw away the old transition frontier. But the async jobs of transaction_pool is not terminated correctly and still using the old transition frontier best-tip. And hence we got the dangling mask exception.

We could wrap the computation using Deferred.Or_error.try_with to catch the dangling_mask_exception. This could be one possible solution. We could do this exception handling in transaction_pool.ml itself and wrap every call to the base_ledger with exception-handling code. Or we could only do the exception-handling when calling the transaction_pool functions.

**Comment by mrmr1993** [comment]
We can use `Interruptible.t` for this. See `src/lib/interruptible/interruptible.mli`.
