### ISSUE TITLE
Enable min window density for long fork selection

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#6948]
Additionally, ensure the window size and slide constants are up-to-date and correct.

**Comment by imeckler** [comment]
The code is currently "if'd out". We need to reenable it and make sure it works.

**Comment by imeckler** [comment]
We have a quickcheck generator for consensus states. By putting a "failwith" in in the part of select we want to hit, we should be able to get quickcheck to spit out a pair of states that hit that part of the code, and then we can use those to write a unit test that this has the expected behavior.
