### ISSUE TITLE
Coda daemon crashed

### ISSUE THREAD

**Issue by Rick11rick** [MinaProtocol/mina#6954]
my node vesion is 0.0.17-beta8-9652f8e.  the node worked and was synced today. I stopped the daemon to install screen. After that, the demon crashes
[coda_crash_report_2020-12-05_13-44-34.289366.tar.gz](https://github.com/MinaProtocol/mina/files/5647162/coda_crash_report_2020-12-05_13-44-34.289366.tar.gz)

**Comment by garethtdavies** [comment]
This is `failed to synchronize epoch ledger` which is https://github.com/MinaProtocol/mina/issues/6952 and resolved by https://github.com/MinaProtocol/mina/issues/6952

**Comment by mrmr1993** [comment]
This was fixed in #6959. Closing.
