### ISSUE TITLE
☠  Coda Daemon crashed

### ISSUE THREAD

**Issue by nicholas-mwaura** [MinaProtocol/mina#6955]
2020-12-05 17:59:09 UTC [Faulty_peer] Peer $peer failed to serve requested epoch ledger: "refusing to serve genesis ledger"
        peer: {
  "host": "34.90.90.158",
  "peer_id": "12D3KooWA4kaMsCeY15mL8L5ZT949SSkDFwPhrBp1kcBHTB6Vyq1",
  "libp2p_port": 8302
}
2020-12-05 17:59:09 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: {
  "string": "failed to synchronize epoch ledger",
  "tags": [ { "tag": "Local state sync failed" } ],
  "backtrace": [
    "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
    "Called from file \"src/lib/transition_router/transition_router.ml\", line 350, characters 18-75",
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}
[coda_crash_report_2020-12-05_17-59-09.071145.tar.gz](https://github.com/MinaProtocol/mina/files/5647693/coda_crash_report_2020-12-05_17-59-09.071145.tar.gz)

**Comment by garethtdavies** [comment]
This is `failed to synchronize epoch ledger` which is https://github.com/MinaProtocol/mina/issues/6952 and resolved by https://github.com/MinaProtocol/mina/pull/6959

**Comment by mrmr1993** [comment]
This was fixed in #6959. Closing.
