### ISSUE TITLE
Weird client status after bootstrap

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#6958]
Processing genesis transition after bootstrapping to a new root and/or after catching up to the best tip causes this weird status even though the node is synced: 
```
Block height:                    2410
Max observed block length:       1
...
Sync status:                     Catchup
```
This gets corrected as soon the node gets a new block though

**Comment by aneesharaines** [comment]
Need to investigate why the genesis block written to subscrition

**Comment by ghost-not-in-the-shell** [comment]
The max_block_height is calculated by extracting the height of most_recent_valid_transition, we could add a local count to store the max height and compare with the height of most_recent_valid_transition, update the height if it's greater.
