### ISSUE TITLE
☠  Coda Daemon crashed.

### ISSUE THREAD

**Issue by cheoa** [MinaProtocol/mina#6960]
[summary.txt](https://github.com/MinaProtocol/mina/files/5648564/summary.txt)

**Comment by garethtdavies** [comment]
`Failure","failed to initialize transition frontier: Staged_ledger.of_scan_state_and_ledger : did not connect with snarked ledger hash"`

This is a duplicate of https://github.com/MinaProtocol/mina/issues/6950

**Comment by mrmr1993** [comment]
Closing in favour of #6950, which includes more logs.
