### ISSUE TITLE
Block producing problem and than Coda Daemon crashed.

### ISSUE THREAD

**Issue by EmreNOP** [MinaProtocol/mina#6961]
My node missed to produce block around "2020-12-06 00:03:13 UTC"

Here is the error log.

2020-12-06 00:03:13 UTC [Info] Producing block in 3576 slots
2020-12-06 00:03:13 UTC [Error] Internally generated block $state_hash cannot be rebroadcast because it's not a valid time to do so ("1 slots too late")

around 6 hours later; daemon crashed like below.

Git SHA-1:                  [DIRTY]9652f8ee092ea77e29f5ab49fa0a295e36743e8b

Generating crash report
  exn: {
  "string": "failed to synchronize epoch ledger",
  "tags": [ { "tag": "Local state sync failed" } ],
  "backtrace": [
    "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
    "Called from file \"src/lib/transition_router/transition_router.ml\", line 350, characters 18-75",
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}

  ☠️  Coda Daemon crashed.
   The Coda Protocol developers would like to know why!

    Please:
      Open an issue:
        <https://github.com/CodaProtocol/coda/issues/new>

      Briefly describe what you were doing and attach the crash report /root/.coda-config/coda_crash_report_2020-12-06_11-31-12.367017.tar.gz
[coda_crash_report_2020-12-06_11-41-09.650771.tar.gz](https://github.com/MinaProtocol/mina/files/5648688/coda_crash_report_2020-12-06_11-41-09.650771.tar.gz)
[coda_crash_report_2020-12-06_11-41-09.650771.tar.gz](https://github.com/MinaProtocol/mina/files/5648689/coda_crash_report_2020-12-06_11-41-09.650771.tar.gz)

**Comment by garethtdavies** [comment]
This is `failed to synchronize epoch ledger` which is https://github.com/MinaProtocol/mina/issues/6952 and resolved by https://github.com/MinaProtocol/mina/pull/6959
