### ISSUE TITLE
Coda daemon crashed

### ISSUE THREAD

**Issue by kunalpat25** [MinaProtocol/mina#6967]
I downloaded docker image in Windows 10 using commands given in documentation and found this error in log file

`Generating crash report
	exn: {
  "string":
    "Couldn't determine our IP from the internet, use -external-ip flag",
  "backtrace": [
    "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
    "Called from file \"src/option.ml\", line 69, characters 4-21",
    "Called from file \"src/app/cli/src/init/find_ip.ml\", line 39, characters 5-136",
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}
`
[coda_crash_report_2020-12-07_14-57-49.020355.tar.gz](https://github.com/MinaProtocol/mina/files/5653459/coda_crash_report_2020-12-07_14-57-49.020355.tar.gz)

**Comment by mrmr1993** [comment]
@kunalpat25 the error message has the relevant information: `Couldn't determine our IP from the internet, use -external-ip flag`

You can use a service to work out your external IP (e.g. search for 'what's my ip' on Google) and then pass `-external-ip YOUR.IP.ADDR.HERE` in the arguments to `coda daemon`
