### ISSUE TITLE
Add additional telemetry info

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#6970]
-The Coda node’s git version hash (so we know what nodes are on what versions)
-Receipt time of last k blocks (so we know how quickly community nodes are receiving blocks to stay within one slot)
-Uptime (so we know how frequently nodes are crashing)
-State (synced, catchup, … so we can confirm nodes are only saying Synced if they’re up to date)

**Comment by psteckler** [comment]
@aneesharaines  Receipt time of last k blocks

Can you clarify what this means?

**Comment by aneesharaines** [comment]
@psteckler  for that one, reporting for each of the last k blocks, the time that block was received.  so there should be k individual timestamps

**Comment by psteckler** [comment]
Closed by #7018.
