### ISSUE TITLE
[Faulty_peer] Peer $peer failed to serve requested epoch ledger: "refusing to serve genesis ledger"

### ISSUE THREAD

**Issue by UbikCapital** [MinaProtocol/mina#6994]
2020-12-09 08:16:52 UTC [Warn] failed to reset stream (this means it was probably closed successfully): $error
        error: {
  "string":
    "RPC #1074 failed: \"internal RPC error error: unknown stream_idx\""
}
2020-12-09 08:17:02 UTC [Warn] RPC call error for "get_epoch_ledger"
2020-12-09 08:17:02 UTC [Faulty_peer] Peer $peer failed to serve requested epoch ledger: "\"handshake error\""
        peer: {
  "host": "34.75.104.31",
  "peer_id": "12D3KooWHDkjip89o1He1ofQ8bK1JkymHUvhasLv7Bc4uryRuv95",
  "libp2p_port": 10401
}
2020-12-09 08:17:02 UTC [Faulty_peer] Peer $peer failed to serve requested epoch ledger: "refusing to serve genesis ledger"
        peer: {
  "host": "95.217.201.34",
  "peer_id": "12D3KooWE3nDGbJ4qwCpVbtjxUUcvADuo8nYEtdeB8x1udbG8def",
  "libp2p_port": 8302
}
2020-12-09 08:17:02 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: {
  "string": "failed to synchronize epoch ledger",
  "tags": [ { "tag": "Local state sync failed" } ],
  "backtrace": [
    "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
    "Called from file \"src/lib/transition_router/transition_router.ml\", line 350, characters 18-75",
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
[coda_crash_report_2020-12-09_08-17-02.538573.tar.gz](https://github.com/MinaProtocol/mina/files/5664432/coda_crash_report_2020-12-09_08-17-02.538573.tar.gz)

**Comment by garethtdavies** [comment]
@UbikCapital this issue was resolved by a new release. You need to ensure you are running the version listed in the docs here: https://minaprotocol.com/docs/connecting

```
Check that daemon installed correctly by running coda version. The output should read Commit [DIRTY]880882e45e48aaf987aca191f488c7f65609c305 on branch HEAD.
```

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
