### ISSUE TITLE
coda crash report 

### ISSUE THREAD

**Issue by tolon** [MinaProtocol/mina#6995]
[coda_crash_report_2020-12-09_10-55-00.189717.tar.gz](https://github.com/MinaProtocol/mina/files/5665663/coda_crash_report_2020-12-09_10-55-00.189717.tar.gz)

**Comment by garethtdavies** [comment]
This is `Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference(\"7c4dd792-651d-305b-00dc-73be30ec1ce5\` which is resolved by https://github.com/MinaProtocol/mina/pull/6861

**Comment by mrmr1993** [comment]
Closing as a duplicate of #6949.
