### ISSUE TITLE
Audit OCaml dependencies

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#7003]
Go over our Ocaml dependencies & see if there are any security vulnerabilities with using the older version

https://www.notion.so/minaprotocol/Opam-Dependency-Audit-95c685d4c4c3417cbaa4342d6d4c9736

**Comment by nholland94** [comment]
https://www.notion.so/minaprotocol/Opam-Dependency-Audit-95c685d4c4c3417cbaa4342d6d4c9736
