### ISSUE TITLE
`coda client set-snark-work-fee` Cost setting does not take effect

### ISSUE THREAD

**Issue by sundafa** [MinaProtocol/mina#7015]
Start with `coda daemon`, then execute the command `coda client set-snark-work-fee 0.1` to adjust the cost online
After an hour, check the browser and find that `snark Jobs  Fees Earned` is still 0.01
`coda daemon -generate-genesis-proof true -peer-list ~/peers.txt -run-snark-worker "pubkey" -snark-worker-fee 0.01`

This should not happen, this value is less than 0.1, my node should not do this work

**Comment by garethtdavies** [comment]
@sundafa this is not a bug and is related to how snark work is selected, added to the snark pool, and then purchased.

By default, pending snark work is chosen at random (you may also set `-work-selection seq`). You are competing with others and only the cheapest snark work is added to the snark pool, and that work is later purchased by block producers. So it's possible your fee is too expensive to even make it into the pool.

Also, there is a specific order of work to be included by the block producer so there can be a significant delay between getting your work into the snark pool and it is purchased.

**Comment by garethtdavies** [comment]
Or maybe I misread and you are saying that the "old" fee was used for new jobs. If so, the work was completed and added to the pool and then included much later (after you had changed the fee).

**Comment by sundafa** [comment]
@garethtdavies
addr https://minaexplorer.com/wallet/B62qs2kyJGgHFpxCapwudYFa8Beu2pKUNTKzDtYj3psYStmdqhn9FD2
name windows | Nodeasy#4629
Transaction link:
https://minaexplorer.com/block/3NKREhxnsN3NrTqQv7ca3YiPGU6wqhSRKJjq5wuQEKtyFhxHxwsD
https://minaexplorer.com/block/3NKdWajXA7StH4wfmNZCBeHRrhfdoptAKCUdvRaEsHwgSL9PXrnN

I set up 3 snark nodes this time, After I changed the snark fees to 1, I waited a few minutes before sending the transaction
I set the starting transaction fee to 1, and then 1.01, but I found that my snark node did not mine these fees and only mine other transactions of 0.01

**Comment by garethtdavies** [comment]
@sundafa this isn't how it works. Block producers add transactions to a transaction queue known as the scan state and then purchase an offsetting amount of snark work from the snark pool. This work from the snark pool corresponds to transactions added by **prior** block producers. You do not snark your own transactions.

**Comment by sundafa** [comment]
I understand what you mean, but all my transactions have been robbed by official nodes, which makes me feel strange
You can look at the snark part of this transaction
https://minaexplorer.com/block/3NKLnD2RLXD1GsrsFtndxP9vzMNbAGmDu31kdpt12bWdEQ51CC69

**Comment by garethtdavies** [comment]
I don't understand, what is wrong with this block? You paid a fee of 1.01 and most of that went to the block producer?

**Comment by sundafa** [comment]
Can i talk to you on discord, my addr `windows | Nodeasy#4629`

**Comment by sundafa** [comment]
@garethtdavies I still have some problems. I got 12 fees at this address, But the SNARK Jobs on the left does not have this address, this address is not working
Where did this fee go?
![image](https://user-images.githubusercontent.com/24621599/101855801-084c7780-3b9f-11eb-9d7f-7f6f37c5e856.png)

**Comment by garethtdavies** [comment]
@sundafa that address created the block. The block producer gets the coinbase plus any difference between transaction fees minus the fees paid to snark workers.

**Comment by sundafa** [comment]
@garethtdavies Seems to understand.
Block producers will choose Snarkers themselves to maximize their own profits.
1. But I still don’t know whether the 12 fee in the above figure is to choose official node snark to reduce costs or not to execute snark.  Because there is no snark work record on the official address.
2. Will block producers choose their own snarkers, no matter how much the cost is, because the cost to snark will be returned to themselves?

**Comment by sundafa** [comment]
The first question guess:  In other words, because there are workers with the lowest snark, they use low fees to process transactions with high fees, which leads to more benefits for themselves
