### ISSUE TITLE
No coinbase tx for produced blocks

### ISSUE THREAD

**Issue by sanchopansa** [MinaProtocol/mina#7016]
According to the Mina explorer, I did not receive the coinbase tx for a block my node just produced: https://minaexplorer.com/wallet/B62qoeGtw6SzaRahbprfy1RUgQBGHv7cRbzpPn5tLXdTxLSsL5R5q5o

Not sure if that's a glitch in the explorer, or something went wrong during the block production. I am attaching the logs during block production here.

[logs.txt](https://github.com/MinaProtocol/mina/files/5672272/logs.txt)

**Comment by mrmr1993** [comment]
The 'block production' section at the bottom of that page indicates that the block was seen but isn't part of the canonical chain.
![Screenshot from 2020-12-10 14-25-42](https://user-images.githubusercontent.com/1847343/101785158-53f61700-3af4-11eb-898b-b4a453fcda8a.png)

**Comment by sanchopansa** [comment]
Yes, I'm wondering why that was the case? Is this expected to occur occasionally (so not a consensus bug, e.g.) and what is the underlying reason?

**Comment by garethtdavies** [comment]
@sanchopansa Yes it is expected and not a bug. You can read some more here https://minaprotocol.com/docs/troubleshooting#block-producer - quoting a relevant section:

```Why was my block orphaned / why did I not get a block reward?
There can be more than one block producer per slot due to the way block producers are selected. So if two (or more) blocks are produced for the same slot, it will cause a short fork, and only one will be chosen - the winner in this instance is random. If you consistently see orphaned blocks, then you may be producing blocks slowly, and so other block producers may not see your block before building atop the current longest chain.

It is also possible to produce a block in catchup, and this block will also be quickly orphaned as it is not building on the correct height.```

**Comment by sanchopansa** [comment]
Thanks for the pointer!
