### ISSUE TITLE
Make the blocks and newBlock queries/subscriptions work with transition frontier instead in graphql

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#7035]
In 4.1-hardfork net, we remove external transition rocksdb database

Please add the missing bits of external transitions as well wherever it's simple and create issues for the bits that are missing that aren't simple (which we can follow up on)

**Comment by psteckler** [comment]
@bkase The `newBlock` subscription was not removed in `until-4.1-hardfork`, I believe. Does it no longer work?

**Comment by bkase** [comment]
@psteckler the external transition database no longer exists (afaik) so I think it won't work

**Comment by psteckler** [comment]
@bkase the external transition db doesn't exist, but the `newBlock` subscription is for new blocks, not for historical data. The subscription relies on data pushed through a pipe. I'm not sure where the original entry point is, though.

Do you know where in the code the block is entered into the pipe? 

In `Coda_subscriptions`, there was a call to `update_external_transition_database`, that's removed; there's still a call to `update_block_subscriptions`.

**Comment by bkase** [comment]
I'm not 100% sure but I think the pipe was connected to the external transition database updates. But if not, I wonder if you can reuse that logic for the queries as well

**Comment by psteckler** [comment]
To me, it looks like the db and block subscription were updated simultaneously, by using the same block read from a pipe. It doesn't look like the block subscription depended on the db.

**Comment by psteckler** [comment]
`bestChain` seems to already rely on the frontier, so no need to resurrect `blocks`.

/cc @bkase

**Comment by psteckler** [comment]
Not needed.
