### ISSUE TITLE
Show "No block producer running" in coda client status output next block produced in

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#7054]
Per this conversation on Discord: https://discord.com/channels/484437221055922177/601215883939020852/787348528224534549

It can be confusing that when not running a block producer the user sees "None this epoch... checking at xxx"

If "Block producers running" is 0 could it display "No block producers running" or similar?

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
