### ISSUE TITLE
Cleanup tasks for mainnet

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#7058]
No pending public keys in spreadsheet genesis ledger
Remove telemetry (or make opt-in)
Eliminate compile warnings
Uniform failure exit (no Core.exit)
Disallow version errors as warnings
Enforce version linting
Enforce banning (see `tmp_bans_are_disabled`)
Any other temp code

**Comment by aneesharaines** [comment]
@psteckler  - Could you split these out?

**Comment by psteckler** [comment]
Replaced by #7995, #7996, #7997, #7998, #7999, #8000.
