### ISSUE TITLE
Failed to produce a block and next block produced in stuck at Producing a block for over 30 mins

### ISSUE THREAD

**Issue by kaanci** [MinaProtocol/mina#7061]
Hi,

My node had been in "Producing a block" status (output of coda client status). But it could not produce block. All day my node had crashed four times. Before 2 hours from block production time it had been in synchzed status and it reached the block production time with "sysnched" status. Durind more than 30 minutes it had been in "Production block status". But it failed to produce block.

My node has 8xCPU and 16 GB RAM, 40GB boot disk (cloud service from Kamatera working on Ubuntu 18.04). It had produced 2 blocks before. My public address is B62qjLT5nikj5tNfkc9nwz7uLoVDnfTvWsUai5dLNtMjJhx3qYAWFhs

Please find coda logs attached.

Regards.

Kaan CINKIR 
[coda.log](https://github.com/MinaProtocol/mina/files/5691492/coda.log)

[coda.log](https://github.com/MinaProtocol/mina/files/5691577/coda.log)
[codalogs2.zip](https://github.com/MinaProtocol/mina/files/5691578/codalogs2.zip)
[codalogs3.zip](https://github.com/MinaProtocol/mina/files/5691580/codalogs3.zip)
[codalogs4.zip](https://github.com/MinaProtocol/mina/files/5691582/codalogs4.zip)
[codalogs5.zip](https://github.com/MinaProtocol/mina/files/5691585/codalogs5.zip)
[codalogs6.zip](https://github.com/MinaProtocol/mina/files/5691587/codalogs6.zip)
[coda-prover.log](https://github.com/MinaProtocol/mina/files/5691588/coda-prover.log)
[coda-verifier.log](https://github.com/MinaProtocol/mina/files/5691589/coda-verifier.log)

**Comment by garethtdavies** [comment]
Adding a couple screenshots to save sifting through the logs to find the right location. Looks like it produced a block just fine and then there are no logs for ~14 mins after being inserted into the local transition frontier.

<img width="1665" alt="CleanShot 2020-12-14 at 13 26 14@2x" src="https://user-images.githubusercontent.com/135382/102137640-ff161180-3e0f-11eb-88f5-28c855c44f31.png">

<img width="1663" alt="CleanShot 2020-12-14 at 13 23 42@2x" src="https://user-images.githubusercontent.com/135382/102137440-b0687780-3e0f-11eb-8c78-23097503e825.png">

**Comment by kaanci** [comment]
My node is in synched status, # of peers is 37 and "Next block will be produced in:   Producing a block now..." stage.  In last production time it had been again "Producing a block now.." for 30 minutes and it did not produce block. To report this bug I opened this issue.  After I had waited 2.9 days for this block production time, I faced  with the same problem. If this bug will not be fixed I will not be able to complete block production challenge. (I produced 2 blocks. I need to produce at least one more block). Please find the logs in zipped form (coda logs for 19.12.2020)
[coda.log](https://github.com/MinaProtocol/mina/files/5719741/coda.log)
[Codalog_20201219_1.zip](https://github.com/MinaProtocol/mina/files/5719743/Codalog_20201219_1.zip)
[Codalog_20201219_2.zip](https://github.com/MinaProtocol/mina/files/5719744/Codalog_20201219_2.zip)
[Codalog_20201219_3.zip](https://github.com/MinaProtocol/mina/files/5719746/Codalog_20201219_3.zip)
[Codalog_20201219_4.zip](https://github.com/MinaProtocol/mina/files/5719757/Codalog_20201219_4.zip)
[coda-prover.log](https://github.com/MinaProtocol/mina/files/5719758/coda-prover.log)
[coda-verifier.log](https://github.com/MinaProtocol/mina/files/5719759/coda-verifier.log)

**Comment by kaanci** [comment]
The logs uploaded above are new logs (coda logs for 19.12.2020).

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
