### ISSUE TITLE
coda client status error

### ISSUE THREAD

**Issue by Rookie23** [MinaProtocol/mina#7064]
I get such an error when I type coda client status.

Error: Unable to connect to Coda daemon.
- The daemon might not be running. See logs (in `~/.coda-config/coda.log`) for details under the host:127.0.0.1.
  Run `coda daemon -help` to see how to start daemon.
- If you just started the daemon, wait a minute for the RPC server to start.
- Alternatively, the daemon may not be running the RPC server on (127.0.0.1 8301).
  If so, add flag `-daemon-port` with correct port when running this command.

**Comment by garethtdavies** [comment]
As per #7065 likely your container is restarting very shortly after starting up due to a configuration issue and so the GraphQL server never starts. Follow the logs with `docker logs --follow mina` to see why it is crashing.

**Comment by mrmr1993** [comment]
This would need more info to investigate, and the time to collect that has probably passed. Closing.
