### ISSUE TITLE
docker exec -it mina bash error

### ISSUE THREAD

**Issue by Rookie23** [MinaProtocol/mina#7065]
When I type the docker exec -it mina bash command, it doesn't stay in root, it immediately starts

**Comment by garethtdavies** [comment]
I imagine the container is restarting. Try following the logs to see the reason for the crash - if it is very quick it is likely a configuration issue like an incorrect password or a permission issue with your keypair. `docker logs --follow mina`

**Comment by mrmr1993** [comment]
This would need more info to investigate, and the time to collect that has probably passed. Closing.
