### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by lyubo-damyanov** [MinaProtocol/mina#7112]
Hello

I stepped away from the computer and when I returned (computer was continuously on) I found that one of my nodes on Google Cloud had crashed with the following output:

numerous lines of:
"Called from file \"list.ml\", line 117, characters 24-34"," 

followed by 

"Called from file \"src/lib/transition_frontier/transition_frontier.ml\", line 199, characters 4-157",
"Called from file \"src/lib/transition_router/transition_router.ml\", line 192, characters 4-136",
"Called from file \"src/lib/transition_router/transition_router.ml\", line 261, characters 6-129",
"Called from file \"src/deferred0.ml\", line 56, characters 64-69",
"Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
"Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}

**Comment by lyubo-damyanov** [comment]
[coda_crash_report_2020-12-18_11-56-53.921016.tar.gz](https://github.com/MinaProtocol/mina/files/5717388/coda_crash_report_2020-12-18_11-56-53.921016.tar.gz)

**Comment by mrmr1993** [comment]
I've opened PR #7115 to detect and handle this error.

I suspect this is a result of a 'dirty' shutdown, which corrupted one of the databases; you should be able to work around this error by manually clearing `~/.coda-config` until that fix is merged and released.
