### ISSUE TITLE
Error when exporting logs: file changed as we read it

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#7113]
From denysk#5292 on discord:
> ```
> (monitor.ml.Error
>  (Failure
>   "Error when exporting logs: {\"sexp\":[[\"prog\",\"tar\"],[\"args\",[\"-C\",\"/home/denysk/.coda-config\",\"-czf\",\"/home/denysk/.coda-config/exported_logs/2020-12-18_07-47-02.tar.gz\",\"hardware.info\",\"coda.version\",\"coda.log.8\",\"coda.log.38\",\"coda.log\",\"coda.log.6\",\"mina-best-tip.log\",\"coda.log.18\",\"coda.log.12\",\"coda.log.7\",\"coda.log.22\",\"coda.log.3\",\"coda.log.27\",\"coda.log.46\",\"coda.log.10\",\"coda.log.42\",\"coda.log.47\",\"coda.log.25\",\"coda.log.5\",\"coda.log.26\",\"coda.log.23\",\"coda.log.14\",\"coda.log.33\",\"coda.log.28\",\"coda.log.35\",\"coda.log.32\",\"coda.log.13\",\"coda.log.29\",\"coda.log.30\",\"coda.log.41\",\"coda.log.24\",\"coda.log.21\",\"coda.log.48\",\"coda.log.16\",\"coda.log.9\",\"coda.log.0\",\"coda.log.19\",\"coda.log.2\",\"coda-prover.log\",\"coda.log.4\",\"coda.log.15\",\"coda-verifier.log\",\"coda.log.50\",\"coda.log.43\",\"coda.log.45\",\"coda.log.44\",\"coda.log.34\",\"coda.log.49\",\"coda.log.40\",\"coda.log.31\",\"coda.log.11\",\"coda.log.36\",\"coda.log.37\",\"coda.log.39\",\"coda.log.17\",\"coda.log.1\",\"coda.log.20\"]],[\"exit_status\",[\"Exit_non_zero\",\"1\"]],[\"stdout\",\"\"],[\"stderr\",[\"tar: coda.log: file changed as we read it\",\"\"]]],\"tags\":[{\"tag\":\"Process.run failed\"}]}")
>  ("Raised at file \"stdlib.ml\", line 33, characters 17-33"
>   "Called from file \"src/deferred1.ml\", line 17, characters 40-45"
>   "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
>   "Called from file \"src/job_queue.ml\", line 171, characters 6-47"))
> ```

Specifically, from the stderr of the tar process:
`[\"stderr\",[\"tar: coda.log: file changed as we read it\",\"\"]]`. This seems expected: we are able to emit new log messages while the archive is being created, and may even rotate logs.

Options:
* It seems that we [may be able to suppress this warning](https://www.gnu.org/software/tar/manual/html_section/tar_27.html) with `--warning=no-file-changed`, although we should verify that this works and is supported across platforms.
* We could consider forcing a log rotation immediately before dumping, and exclude `coda.log` (the currently-active log file) from the archive.

**Comment by psteckler** [comment]
The linked-to doc page says that the warning does not affect the exit code of `tar`, which is belied by the error we get.

We can just make temporary copies of the logs and archive those.

**Comment by mrmr1993** [comment]
This was done in #7183. Closing.
