### ISSUE TITLE
Node crash report

### ISSUE THREAD

**Issue by Vgk88** [MinaProtocol/mina#7120]
I am trying to complete Testnet 4.1 Flash Challenge and have problem with starting node. 
[coda_crash_report_2020-12-18_19-09-30.783821.tar.gz](https://github.com/MinaProtocol/mina/files/5717884/coda_crash_report_2020-12-18_19-09-30.783821.tar.gz)

**Comment by garethtdavies** [comment]
```Failure","IO error: While lock file: /root/.coda-config/trust/LOCK: Resource temporarily unavailable"```

Duplicate of #4328 and https://github.com/MinaProtocol/mina/issues/3463

@Vgk88 see the comment here https://github.com/MinaProtocol/mina/issues/3463#issuecomment-534288291

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
