### ISSUE TITLE
convert ocaml-rocksdb to external repo and revise

### ISSUE THREAD

**Issue by mobileink** [MinaProtocol/mina#7121]
Currently ocaml-rocksdb is "vendored" in src/external/ocaml-rocksdb.  Recommendation is to convert this to an external repo.  This would make it easier to ingest upstream changes and would better fit a Bazel workflow.

The code to support this is at [obazl/orocksdb](https://github.com/obazl/orocksdb).  This repo is derived from what I believe is the source of Mina's vendored version.  The `mina` branch matches the code in `src/external/ocaml-rocksdb`.  Note the comments in `WORKSPACE.bzl`; the build has been tested with various versions.  If we wanted to I think we could parameterize the build to select a version of the librocksdb c++ lib at build time.

The Bazel code for Mina (to be submitted soon) uses this bazelized version.  So we should probably transfer the repo to o1-labs.

Second recommendation:  revise the mina version to make it a conservative extension of the upstream lib.  I believe currently it changes the semantics (haven't looked at it for a week or so) of at least one function.  It would be better IMHO to create a new function thereby extending the lib and leave the upstream functionality unchanged. That way integrating upstream changes would be easier.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
