### ISSUE TITLE
Coda Daemon Crashed

### ISSUE THREAD

**Issue by meirbank** [MinaProtocol/mina#7142]
Coda Daemon Crashed
Running Ubuntu, log obtained after following steps in this tutorial: https://minaprotocol.com/docs/connecting

![download (7)](https://user-images.githubusercontent.com/10442269/102699016-a085d480-420f-11eb-93a1-82f01e4e29db.png)

**Comment by garethtdavies** [comment]
This error is usually caused by a lack of resources. What are the specs of this machine?

**Comment by meirbank** [comment]
It was on an AWS t2.small instance. Is that not good enough?

**Comment by garethtdavies** [comment]
No, recommended specs are 8 vCPU and 16GB of RAM.

**Comment by meirbank** [comment]
Ok, thanks
