### ISSUE TITLE
[BAZEL]  linkmode for C/C++ dependencies

### ISSUE THREAD

**Issue by mobileink** [MinaProtocol/mina#7155]
The OBazl rules support linking of c/c++ libraries using attributes like `cc_deps`.  **This code is not full cooked.**  What is there currently is sufficient to build Mina, but more work is needed to finalize complete support:

* "stickiness" - currently cc deps must be explicitly added to executables that depend on them indirectly. The final version of the rules will eliminate this requirement, so that such deps will only need to be attached to modules that directly depend on them, and the executables will pull them out of their transitive dep graph.
* link options. The means of  expressing link options needs to be developed further. For example, the current version supports  a `cc_linkall` attribute that generates `-force_load` for MacOS and `-whole-archive` for Linux, but that interface will probably change. There are tons of link options and we will probably want to use some of them, especially those involving optimization like LTO.
* link mode. The OBazl rules support both static and shared linking. The `cc_deps` attribute takes a dictionary whose keys are labels of libs to link, and whose values are linkmode constants "static", "shared", or "default", the last of which resolves to static for Linux and shared/dynamic for MacOS.  There are two tasks here:
  * go through all the rules and make sure the linkmode is correctly set
  * support command-line configuration of linkmodes
* integrated model supporting c/c++, rust, go, etc. link modes and options

Related topic:  support for deployment packages (e.g. debian, mac bundles)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
