### ISSUE TITLE
'coda daemon -snark-worker-parallelism 8' caused crash

### ISSUE THREAD

**Issue by lampardlamps** [MinaProtocol/mina#7159]
I'm a new starter following the instructions on [node operator](https://minaprotocol.com/docs/node-operator) until the section 'Compressing data in the Mina network'. After I've set
`coda client set-snark-work-fee <FEE>`
`coda client set-snark-worker -address $MINA_PUBLIC_KEY`
I also would like to set the parallelism to 8 since I am running on a 8 core processer. so I typed in the command 
`coda daemon -snark-worker-parallelism 8`
and then the daemon crashed. I was told by the output to attach the crash report, which I've done [here](https://github.com/MinaProtocol/mina/files/5722065/coda_crash_report_2020-12-21_02-41-39.153583.tar.gz).

Btw, on the page [connect to the network](https://minaprotocol.com/docs/connecting), it is intructed to save the public key as $CODA_PUBLIC_KEY (`coda accounts unlock -public-key $CODA_PUBLIC_KEY`), but on [node operator](https://minaprotocol.com/docs/node-operator), $MINA_PUBLIC_KEY is used: `coda client set-snark-worker -address $MINA_PUBLIC_KEY`, you might want to change the inconsistency. 

Thanks!

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
