### ISSUE TITLE
[BAZEL] Binary stamping

### ISSUE THREAD

**Issue by mobileink** [MinaProtocol/mina#7163]
Bazel has some built-in support for stamping binaries. See https://bazelbuild.github.io/rules_nodejs/stamping.html

The initial Bazel code for mina includes a first stab at using this mechanism; see  the code in `src/lib/coda_version`, `bzl/tools/stamp.sh`, and `.bazelrc`.

A major difference from the way coda_version currently works is that Bazel stamping is only intended for distributable artifacts, since stamping every time would invalidate caching and cause unnecessary rebuilds.  So to stamp a binary you must pass a command line arg.

Task: thoroughly review this to make sure we're using Bazel stamping properly, and that it fits the needs of Mina; in particular that it accomodates metadata for zexe and marlin, and that it will work even if git submodules are removed.  This may involve some way of getting the commit pins from the repository bootstrap code, maybe by parameterization.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
