### ISSUE TITLE
Convert dump block json to archive sql

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#7176]

**Comment by es92** [comment]
You'll need
- a gcloud service key (ask me for it)

Running the following commands should get you the data
```
$ gcloud auth activate-service-account --key-file=<keyfile path>
$ gcloud cp gsutil cp gs://mina_network_block_data/$testnet-* .
```

**Comment by mrmr1993** [comment]
Once you have downloaded the blocks with the commands above, you can ingest them using
```bash
coda.exe advanced archive-precomputed-blocks path/to/downloaded/blocks/*
```
The tool talks to a daemon connected to an archive database over its GraphQL connection, so you may need to pass `-rest-server http://daemon-address:port/graphql` if it is not local on the default port.
