### ISSUE TITLE
Mina daemon portscanning network

### ISSUE THREAD

**Issue by dakk** [MinaProtocol/mina#7223]
I'm running mina on a dedicated server on hetzner; today they blocked the ip/server where mina runs, since they detected portscanning activities. After initial investigation, I figure out that mina software was scanning local networks ip address searching for peers (I guess):

```
##########################################################################
#               Netscan detected from host    *.*.*.*               #
##########################################################################

time                protocol src_ip src_port          dest_ip dest_port
---------------------------------------------------------------------------
Mon Dec 21 13:24:43 2020 TCP    *.*.*.* 8302  =>    *.*.32.219 8302 
Mon Dec 21 13:24:44 2020 TCP    *.*.*.* 8302  =>    *.*.32.219 8302 
Mon Dec 21 13:24:46 2020 TCP    *.*.*.* 8302  =>    *.*.32.219 8302 
Mon Dec 21 13:25:26 2020 TCP    *.*.*.* 8302  =>     *.*.33.42 8302 
Mon Dec 21 13:25:27 2020 TCP    *.*.*.* 8302  =>     *.*.33.42 8302 
Mon Dec 21 13:24:27 2020 TCP    *.*.*.* 8302  =>    *.*.33.181 8302 
Mon Dec 21 13:24:26 2020 TCP    *.*.*.* 8302  =>   *.*.149.149 8302 
Mon Dec 21 13:24:14 2020 TCP    *.*.*.* 8302  =>   *.*.150.129 8302 
Mon Dec 21 13:24:33 2020 TCP    *.*.*.* 8302  =>    *.*.152.21 8302 
Mon Dec 21 13:24:34 2020 TCP    *.*.*.* 8302  =>    *.*.152.21 8302 
Mon Dec 21 13:26:00 2020 TCP    *.*.*.* 8302  =>   *.*.152.180 8302 
Mon Dec 21 13:24:22 2020 TCP    *.*.*.* 8302  =>   *.*.154.170 8302 
Mon Dec 21 13:24:24 2020 TCP    *.*.*.* 8302  =>   *.*.154.170 8302 
Mon Dec 21 13:24:26 2020 TCP    *.*.*.* 8302  =>   *.*.154.170 8302 
Mon Dec 21 13:25:51 2020 TCP    *.*.*.* 8302  =>   *.*.154.213 8302 
An many more lines...
```

That's not a good behavior since many server providers detects these activities blocking interested servers.

**Comment by crypto-guys** [comment]
Hetzner has emailed me several times. This is the fix I came up with.

This should allow your private network to continue to function. Nothing should change except the mina service will no longer be able to send requests to private ip addresses. I think this might help without totally isolating your server.

This assumes eth0 is the internet interface and enp7s0 is for the private network.

# Permit the Default Gateway FIRST RULE
-I OUTPUT -d 172.31.1.1/32 -j ACCEPT

# Block all outbound from port 8302 on the private network interface
-A OUTPUT -o enp7s0 -p tcp -m tcp --sport 8302 -j DROP

# Block the 192 private network on the internet facing interface eth0
-A OUTPUT -d 192.168.0.0/16 -o eth0 -j DROP

# Block the 10. private network on eth0
-A OUTPUT -d 10.0.0.0/8 -o eth0 -j DROP

# Block the 192 private network on eth0
-A OUTPUT -d 192.168.0.0/16 -o eth0 -j DROP

# Now block the 172 network outbound. This should hurt nothing as we permitted the gateway in rule 1..
-A OUTPUT -d 172.16.0.0/12 -j DROP

**Comment by dakk** [comment]
Already fixed using ufw to block outgoing communication to local networks (I don't care of them); but I don't understand why it was trying to reach local subnets.

**Comment by garethtdavies** [comment]
Also see https://github.com/MinaProtocol/mina/issues/7053

**Comment by dakk** [comment]
Oh god, I only searched on opened issues, sorry.

Duplicate of #7053
