### ISSUE TITLE
Detect invalid arguments to -peer, give a better error message

### ISSUE THREAD

**Issue by ilhamm24** [MinaProtocol/mina#7267]
[coda_crash_report_2020-12-29_15-26-40.478367.tar.gz](https://github.com/MinaProtocol/mina/files/5751192/coda_crash_report_2020-12-29_15-26-40.478367.tar.gz)

**Comment by mrmr1993** [comment]
The error message is:
```json
{
  "timestamp": "2020-12-29 15:26:40.465191Z",
  "level": "Fatal",
  "source": {
    "module": "Init__Coda_run",
    "location": "File \"src/app/cli/src/init/coda_run.ml\", line 564, characters 2-26"
  },
  "message": "Unhandled top-level exception: $exn\nGenerating crash report",
  "metadata": {
    "exn": {
      "string": "RPC #2 failed: \"internal RPC error error: failed to parse multiaddr \\\"/root/peers.txt\\\": unknown protocol root\"",
      "tags": [
        {
          "tag": "Failed to connect to libp2p_helper process"
        }
      ],
      "backtrace": [
        "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
        "Called from file \"src/lib/gossip_net/libp2p.ml\", line 124, characters 8-94",
        "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
        "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
        "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
      ]
    },
    "host": "62.171.140.49",
    "peer_id": "12D3KooWD7XvUZ1r8jsX7veGTALxdj4HDvhTHTXYgsqNe1JcGoGp",
    "pid": 779681,
    "port": 8302
  }
}
```

@ilhamm24 can you share the flags you passed to the daemon? It seems that the path to the peers file may have been passed to the `-peer` flag instead of the `-peer-list-file`.

**Comment by ilhamm24** [comment]
first, im running daemon with 
1. `coda daemon -peer /root/peers.txt -run-snark-worker B62**kwy -snark-worker-fee 1 -generate-genesis-proof true -block-producer-key /root/wallet-mina`
2. `coda daemon -peer-list-file /root/peers.txt -run-snark-worker B62**kwy -snark-worker-fee 1 -generate-genesis-proof true -block-producer-key /root/wallet-mina`,
3. `coda daemon -peer /root/peers.txt`

All commands got crashed.
And i just trying new command `coda daemon -peer-list-file /root/peers.txt`, the daemon looks like running

**Comment by garethtdavies** [comment]
@ilhamm24 of your examples only 2 should be expected to work. It's possible/probable there is an issue with your wallet file permissions and/or the password provided (assuming you have set the environment variable). The syntax to pass a peers file as noted above is `-peer-list-file`.

The final command you tried removes the keys and so hence it is running. If it is not finding peers then you are likely using an outdated peers list. Which file have you downloaded to `peers.txt`?

**Comment by mrmr1993** [comment]
> i just trying new command `coda daemon -peer-list-file /root/peers.txt`, the daemon looks like running

Great news. I've added this issue to the board for us to try and improve the error message here.

> 2. `coda daemon -peer-list-file /root/peers.txt -run-snark-worker B62**kwy -snark-worker-fee 1 -generate-genesis-proof true -block-producer-key /root/wallet-mina`,

The format of this command seems valid. Can you post the logs and error you see from it?

**Comment by ilhamm24** [comment]
got it, thanks for help me. my bad, wallet-mina is directory, should using wallet file. about peers, i downloaded it from https://raw.githubusercontent.com/MinaProtocol/coda-automation/master/terraform/testnets/turbo-pickles/peers.txt

**Comment by garethtdavies** [comment]
> got it, thanks for help me. my bad, wallet-mina is directory, should using wallet file. about peers, i downloaded it from https://raw.githubusercontent.com/MinaProtocol/coda-automation/master/terraform/testnets/turbo-pickles/peers.txt

Those peers are outdated as refer to the last testnet 4.1 which has now ended. If you are joining Testworld, the latest testnet (that hasn't started yet) you should get the peers and updated daemon from https://minaprotocol.com/docs/connecting

**Comment by ilhamm24** [comment]
ah, ok thanks @garethtdavies and @mrmr1993

**Comment by mrmr1993** [comment]
Leaving this open for discussion about the error message.

**Comment by psteckler** [comment]
The error message in the crash report says "failed to parse multiaddr", and "unknown protocol root", which is what I'd expect for (1) and (3).

Maybe the crash report or log should display the complete command line, which would make it easier to track down these sorts of errors.

**Comment by psteckler** [comment]
Closing because of #7519.
