### ISSUE TITLE
Coda account already imported but cant list

### ISSUE THREAD

**Issue by WayneWayner** [MinaProtocol/mina#7273]
How to reproduce:

- On host: Start coda with docker and wait for sync.
- On host: coda accounts import -privkey-path ~/keys/my-wallet
- On docker: coda  accounts list
```
😢 You have no tracked accounts!
 You can make a new one using `coda accounts create`
```

- On docker:Try to import again inside docker gives following situation. 

```
root@71969f04cbc4:~# coda accounts import -privkey-path /keys/my-wallet
Key already present, no need to import : B62qpMeanu57n1RFXh2ADkzcezBNCbspmQYJHGpBQvuC1XLEYDrTs5b
root@71969f04cbc4:~# coda accounts list
😢 You have no tracked accounts!
You can make a new one using `coda accounts create`
```

**Comment by WayneWayner** [comment]
Hotfix: 
Maybe team should write something whether this wont have any unwanted side effects:

Go to `/home/<yourUser>/.coda-config/wallets/store`
Backup what is inside and delete it. 
Now on docker: 
```
coda accounts import -privkey-path /keys/my-wallet
coda accounts list
```

**Comment by mrmr1993** [comment]
This is a dup of #6110

**Comment by bkase** [comment]
Please comment on #6110 if you want to discuss further. Thanks!
