### ISSUE TITLE
https://forums.minaprotocol.com/t/testworld-community-challenges/763

### ISSUE THREAD

**Issue by H4XOFFICIAL** [MinaProtocol/mina#7279]
Regarding: "Level 5: Telegram Referrals"
Issues: 2

1.
![1](https://user-images.githubusercontent.com/34755197/103379295-7cff3b80-4ae5-11eb-865a-f8d3f640fbc1.jpg)

2. 
a) The generated referral "custom referral link" doesn´t create a link that redirects the referred person to Minas main Telegram group, but instead it directs the referred person to @minacommunitybot. 
b) Then the referred person have to click the "SEND MESSAGE" button in order to get to the "MinaBot".
c) Next up is this dialogue (including own thoughts):
![2](https://user-images.githubusercontent.com/34755197/103380635-c3ef3000-4ae9-11eb-8c47-566540d8cca2.jpg)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
