### ISSUE TITLE
Daemon.json REQUIRED to run -- use it by default

### ISSUE THREAD

**Issue by Fible1** [MinaProtocol/mina#7284]
Daemon.json is required for node to boot. Tested on several fresh installs and same behaviour, could only get it working by creating file and populating it.

I may be missing something but I had to create file to get my node to boot.

No logs as several fresh installs.

**Comment by fumpierrez** [comment]
having same issue, what should be the contents?

**Comment by Fible1** [comment]
Please see the bottom of this page:

https://minaprotocol.com/docs/node-operator

Pablo.

**Comment by aneesharaines** [comment]
Looks like this fixed?

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
