### ISSUE TITLE
coda_status.json: No such file or directory

### ISSUE THREAD

**Issue by nkiki** [MinaProtocol/mina#7288]
![image](https://user-images.githubusercontent.com/61766044/103403527-70352300-4b8b-11eb-8d2e-4b33edd4f915.png)

**Comment by mrmr1993** [comment]
According to the error message, you already have something listening on port 8301. You can run `sudo netstat -lntp | grep -w ':8301'` to find out which process it is.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
