### ISSUE TITLE
Many single-block forks (from nodes making blocks during their initial catch up?)

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#7290]
See for example,

https://media.discordapp.net/attachments/774112816017571841/794267758820196382/block_tree.gv.png?width=150&height=1335

**Comment by aneesharaines** [comment]
Latest:  https://cdn.discordapp.com/attachments/774112816017571841/798292793323159552/block_tree.gv.png

**Comment by aneesharaines** [comment]
Will check once the super catchup fix is in

**Comment by aneesharaines** [comment]
Telemetry is broken.  Haven't seen this raised as an issue recently but want to double check.  Moving backlog for the moment.
