### ISSUE TITLE
A few of our nodes are having far more than 50 peers (like hundreds) and are in the "connecting" state

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#7291]
Coda daemon status
-----------------------------------

Global number of accounts:                     2407
Block height:                                  64
Max observed block length:                     1
Local uptime:                                  7h27m14s
Ledger Merkle root:                            jwTKnk1qaDVe9o9sja17wP8jxGYKena8G5aznvNioBxyMfQshyP
Protocol state hash:                           3NLAHvA6HHfKhK7dKZns6kKRT8CHsar1yE1HaLj4gVA8U6oUUGwd
Chain id:                                      2dbac725ebb5c6c8b1daf21cda9e3694951ab72afe9be99ff7ca47574112f43b
Git SHA-1:                                     [DIRTY]b7eff8e5c966b12bdc298160297c716eae7a35af
Configuration directory:                       /root/.coda-config
Peers:                                         479 (95.217.191.53:8302 95.217.208.210:8302 34.68.139.113:8302 34.70.80.142:8302 158.51.121.127:8302 104.198.231.190:8302 87.26.237.237:8304 159.69.245.211:8302 209.97.183.252:8302 135.181.139.155:8302 35.188.105.63:8302 172.104.239.102:8302 135.181.162.16:8302 167.86.124.50:8302 167.86.124.50:8302 95.217.135.134:8302 116.202.48.187:8302 34.65.164.179:8302 161.97.132.91:8302 135.181.112.78:8302 162.0.226.122:8302 47.253.7.228:8302 47.88.12.169:8302 135.181.176.185:8302 159.65.202.47:45820 47.253.2.210:8302 64.225.61.49:8302 114.232.96.20:8302 161.35.128.22:8302 10.6.91.2:10518 10.6.86.3:10519 135.181.119.49:1024 116.203.140.123:8302 3.233.240.103:8302 35.223.3.193:8302 95.217.113.122:8302 152.89.216.44:8302 168.119.225.11:8302 95.217.73.216:8302 152.89.217.151:8302 34.72.161.230:8302 10.6.85.3:43514 10.6.85.3:10515 34.76.223.104:8302 188.166.56.38:8302 94.130.18.146:8302 35.228.80.34:53666 64.225.57.42:8302 10.6.80.2:10513 34.69.3.98:8302 167.86.121.139:1024 35.184.43.159:8302 35.222.176.113:8302 144.91.126.3:8302 36.189.234.173:8302 20.55.103.72:8302 138.68.26.205:8302 221.8.63.141:38387 135.181.88.87:8302 188.40.132.240:8302 18.183.128.208:8302 34.101.69.173:8302 104.199.21.253:8302 47.253.40.83:8302 168.119.0.204:8302 178.128.170.82:8302 95.217.221.218:8302 95.217.135.136:8302 135.181.116.81:8302 35.226.66.233:8302 10.6.77.3:10504 192.46.235.21:8302 34.71.14.219:8302 95.179.242.74:8302 5.9.109.84:8302 95.217.220.126:8302 35.246.237.214:8302 144.76.3.17:8302 34.83.95.83:8302 62.171.134.37:8302 34.123.114.140:8302 89.136.131.141:8302 173.212.200.158:8302 135.181.149.120:41158 95.217.228.160:8302 78.47.245.183:8302 161.97.115.125:8302 104.158.25.106:8302 136.243.1.97:8302 221.8.63.138:38392 10.6.84.3:10506 95.217.94.83:8302 47.253.12.177:8302 135.181.134.53:8302 35.226.28.109:8302 188.40.103.246:8302 104.197.206.5:8302 95.111.241.215:8302 101.36.122.90:8302 47.253.12.126:8302 34.67.7.203:8302 44.242.138.128:13175 10.6.94.2:10517 158.51.121.97:8302 95.217.192.210:8302 45.76.54.227:8302 158.51.121.67:8302 168.119.140.226:8302 47.253.5.225:8302 79.135.88.179:8269 144.76.183.115:8302 88.198.200.113:8302 34.96.149.53:8302 135.181.138.130:8302 45.63.127.15:8302 18.188.103.246:8302 168.119.1.25:8302 135.181.134.164:8302 34.91.12.128:8302 168.119.149.229:8302 34.66.42.123:8302 161.97.116.241:8302 135.181.74.82:8302 47.91.18.226:8302 47.251.7.81:8302 91.66.174.105:8302 108.61.179.19:8302 188.34.153.55:8302 35.202.187.189:8302 88.218.28.106:8302 52.167.171.111:8302 76.186.212.44:8302 167.172.129.33:8302 161.97.121.158:8302 35.228.76.215:8302 34.207.210.135:8302 136.243.83.68:8302 95.216.218.6:8302 221.8.63.138:38396 35.232.211.221:8302 168.119.1.114:8302 213.133.99.209:8302 34.125.236.245:8302 178.170.39.198:8302 138.201.1.133:8302 134.122.13.5:8302 135.181.79.176:1031 95.217.218.36:8302 95.111.255.70:8302 95.217.226.226:8302 34.96.247.18:8302 95.216.38.229:8302 95.217.122.162:8302 18.217.50.158:8302 10.6.92.2:10505 34.71.86.90:10505 34.123.0.103:8302 35.223.141.32:8302 10.6.101.2:10503 161.97.110.159:8302 35.227.143.224:8302 84.38.188.20:8302 135.181.152.57:8302 34.69.253.105:8302 35.194.0.195:8302 158.51.121.68:8302 135.181.35.158:8302 104.198.202.120:8302 78.47.39.86:8302 10.6.82.5:10510 135.181.38.31:8302 62.171.133.104:8302 35.192.178.150:8302 176.9.65.239:59868 20.46.225.66:8302 173.212.194.34:8302 95.217.202.60:8302 110.234.31.128:32360 161.97.119.242:8302 144.76.111.74:8302 221.8.63.141:38373 95.111.241.221:8302 5.39.222.38:8302 135.181.130.109:8302 35.199.169.67:8302 35.224.44.80:8302 104.196.249.34:8302 49.12.132.105:8302 78.47.250.202:8302 3.238.87.111:8302 135.181.34.225:8302 95.216.226.23:8302 47.253.47.40:8302 68.183.225.80:8302 138.201.129.248:8302 10.6.106.2:10509 138.201.129.249:8302 188.238.234.194:7686 146.148.68.87:8302 135.181.17.60:8302 217.69.7.143:8302 35.226.203.105:8302 35.202.70.155:8302 135.181.157.121:8302 95.217.204.49:8302 152.32.128.231:8302 192.46.216.157:8302 188.40.97.117:8302 34.73.129.203:8302 95.217.134.63:8302 95.179.184.48:38662 103.112.166.197:8302 221.8.63.139:8302 159.89.93.167:8302 207.244.236.172:8302 95.217.187.72:8302 95.216.144.51:8302 34.123.174.53:8302 34.123.218.129:8302 134.17.189.35:1038 85.114.132.73:8302 34.70.104.23:8302 95.217.202.102:8302 218.30.91.94:8302 51.222.105.96:8302 158.51.121.133:8302 104.198.227.169:8302 35.170.64.217:8302 161.97.150.234:8302 135.181.149.39:8302 95.216.165.122:8302 52.173.29.24:8302 135.181.180.103:8302 10.6.88.3:10508 35.223.59.114:10508 45.32.130.232:8302 172.104.19.237:8302 172.104.203.121:8302 158.51.121.134:8302 95.216.218.73:8302 34.70.140.225:8302 149.7.16.101:8302 35.193.149.133:8302 47.253.13.72:8302 10.6.74.2:10909 94.130.111.249:36376 10.6.87.2:10502 34.72.209.171:8302 135.181.192.221:8302 194.19.235.74:8702 185.177.93.9:1042 35.235.39.166:8302 161.97.121.159:8302 149.28.207.165:8302 158.247.223.103:8302 93.170.247.103:8302 95.216.242.148:8302 138.201.132.240:1024 135.181.2.224:8302 135.181.164.252:8302 149.28.40.125:8302 144.76.198.48:8302 45.125.239.157:49856 34.67.98.182:8302 49.50.163.98:8302 35.220.224.198:8302 34.121.159.75:8302 35.246.206.154:8302 135.181.157.169:8302 34.70.233.155:8302 34.65.200.0:8302 221.8.63.139:38395 88.198.207.213:8302 213.52.129.24:8302 161.97.83.116:8302 135.181.162.100:8302 195.201.160.253:8302 116.202.99.18:8302 95.216.166.217:8302 34.87.41.248:8302 164.68.109.225:8302 47.253.8.229:8302 164.68.109.48:8302 8.9.30.47:8302 49.12.99.117:8302 88.99.5.71:8302 35.226.223.46:8302 135.181.151.195:8302 62.171.171.52:8302 70.119.133.208:8302 49.12.134.102:8302 34.101.112.218:8302 47.88.9.215:8302 135.181.30.235:8302 35.187.53.109:8302 95.217.152.6:8302 158.51.121.83:8302 116.203.239.110:8302 95.217.201.34:8302 10.6.75.3:10516 47.253.11.111:8302 116.203.138.189:8302 35.239.102.119:10507 206.189.146.87:8302 135.181.73.26:8302 104.196.71.194:8302 35.188.183.79:8302 135.181.0.61:1024 161.97.116.13:8302 178.128.166.53:8302 34.89.251.63:8302 95.217.21.121:8302 35.226.229.27:8302 35.184.169.201:8302 78.141.209.148:8302 47.253.41.11:8302 10.6.83.3:10514 178.128.166.170:8302 58.20.12.167:3574 148.251.124.238:8302 159.69.242.205:8302 34.65.234.88:8302 10.6.70.5:10909 135.181.80.122:8302 135.181.163.79:8302 194.19.235.76:8302 14.52.147.51:14588 135.181.33.89:8302 135.181.151.35:8302 34.66.91.75:8302 34.72.71.72:8302 35.193.232.146:8302 221.8.63.138:38387 95.217.230.43:8302 207.180.254.170:8302 168.119.32.8:8302 135.181.176.188:8302 35.188.95.167:8302 35.242.202.94:8302 144.76.106.5:8302 34.122.191.98:8302 34.121.7.125:8302 47.253.14.188:8302 34.70.204.133:8302 158.51.121.131:8302 159.69.191.188:8302 35.193.201.169:8302 158.51.121.246:8302 95.217.195.219:8302 34.92.179.53:8302 51.89.98.42:8302 192.248.186.217:8302 54.237.159.252:8302 34.107.75.20:8302 161.97.121.160:8302 104.154.17.18:8302 34.92.247.112:8302 45.157.177.64:8302 35.233.253.169:8302 176.9.8.11:8302 35.243.156.159:36664 135.181.152.29:8302 5.9.120.58:8302 95.217.232.107:8302 10.6.108.2:10511 81.227.252.213:58626 34.70.202.196:8302 95.217.105.93:8302 94.74.103.105:8302 62.171.141.32:8302 34.234.164.65:8302 135.181.45.76:57582 94.237.97.201:8302 35.239.224.188:8302 88.149.141.201:8302 35.222.58.49:8302 185.151.240.123:46982 135.181.133.98:8302 35.223.46.218:8302 195.9.221.210:8302 138.201.242.187:8302 213.136.79.175:8302 34.122.253.136:8302 161.97.141.4:8302 104.197.235.227:8302 34.121.99.253:8302 104.36.231.42:8302 135.181.5.16:8302 35.192.185.78:8302 78.46.110.85:8302 95.217.194.239:39988 178.128.185.170:8302 88.99.212.118:8302 62.171.185.75:8302 178.154.229.43:8302 221.8.63.138:38395 88.198.33.25:8302 10.4.119.144:10909 199.223.234.218:8302 161.97.150.228:8302 68.183.67.246:8302 62.171.177.43:8302 159.69.64.35:8302 135.181.158.53:8302 34.72.216.53:8302 10.6.81.3:10520 107.152.46.145:8302 34.68.249.126:8302 95.217.152.34:8302 95.217.236.175:8302 168.119.69.6:8302 157.90.20.14:8302 110.234.16.96:40681 161.97.95.246:8302 114.84.67.11:8302 35.192.204.69:8302 135.181.100.222:8302 161.97.121.162:8302 39.98.250.124:8302 34.121.182.166:8302 159.65.195.146:8302 104.243.45.202:42925 138.201.30.88:8302 161.97.121.164:8302 35.226.220.214:8302 35.192.122.106:8302 95.216.45.39:8302 138.201.132.50:8302 95.217.154.200:8302 167.99.212.148:8302 10.6.76.2:10512 35.226.246.112:8302 47.253.10.28:8302 47.241.120.55:8302 161.97.82.98:8302 158.51.121.47:8302 34.123.70.223:8302 95.217.229.70:8302 176.9.157.247:8302 158.51.121.98:8302 62.171.164.158:8302 34.122.188.184:8302 34.87.161.62:8302 85.114.132.70:8302 149.28.48.124:8302 35.240.51.185:8302 45.67.56.45:8302 49.67.171.210:8302 168.119.137.216:8302 34.70.1.152:8302 34.123.194.152:8302 34.105.115.130:8302 35.202.5.223:8302 47.253.3.152:8302 94.130.200.218:8302 206.189.50.115:8302 34.123.54.55:8302 158.51.121.119:8302 138.201.132.38:8302 8.210.9.99:8302 35.226.70.143:8302 34.67.180.15:8302 34.66.230.115:8302 168.119.156.19:8302 95.216.118.123:8302 178.128.35.253:8302 68.183.56.106:8302 185.239.203.219:8302 162.222.181.175:8302 213.136.74.60:8302 62.171.140.49:8302 34.66.157.200:10001 34.105.244.197:8302 158.51.121.122:8302 35.236.227.41:8302 34.87.175.129:8302 45.79.115.226:8302 158.51.121.163:8302 135.181.109.9:8302)
User_commands sent:                            0
SNARK worker:                                  None
SNARK work fee:                                25000000
Sync status:                                   Connecting
Block producers running:                       1 (B62qj7HaX7dX75yusvPXfJ7nM3vJqwajENaBXKeTaKotGBzMgnbXDeu)
Best tip consensus time:                       epoch=0, slot=458
Best tip global slot (across all hard-forks):  458
Next block will be produced in:                in 7.501h
Consensus time now:                            epoch=0, slot=468
Consensus mechanism:                           proof_of_stake
Consensus configuration:
	Delta:                     0
	k:                         290
	Slots per epoch:           7140
	Slot duration:             3m
	Epoch duration:            14d21h
	Chain start timestamp:     2020-12-30 19:14:30.000000Z
	Acceptable network delay:  3m

Addresses and ports:
	External IP:    35.222.164.254
	Bind IP:        0.0.0.0
	Libp2p PeerID:  12D3KooWSwodEHWardajgAwvvZvSAanyac2V3vUDegz4PGCWm6dy
	Libp2p port:    10501
	Client port:    8301

**Comment by bkase** [comment]
This is because these nodes are in our peer list and we have a known issue where nodes that are in the initial-peers list end up with more than the max-connection cap.

**Comment by es92** [comment]
I split this into two issues: 
https://github.com/MinaProtocol/mina/issues/7294
https://github.com/MinaProtocol/mina/issues/7295
