### ISSUE TITLE
Some of our nodes have restarted many times

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#7292]
archive-db-bootstrap-58wz6                  0/2     Completed   0          20h
archive-db-bootstrap-c8lgw                  0/2     Error       0          20h
archive-node-6f84b99548-xs57s               2/2     Running     3          20h
fish-block-producer-1-56974487c6-xzwjr      2/2     Running     6          19h
fish-block-producer-2-576df88b5b-l48bk      0/2     Running     1          19h
fish-block-producer-3-644598d59b-ftxs9      2/2     Running     1          19h
fish-block-producer-4-fcf765d5b-67m8v       2/2     Running     15         19h
fish-block-producer-5-5579dcd5cc-8bznm      0/2     Running     8          19h
seed-node-7b459c9998-tb8t8                  1/2     Running     1          20h
snark-coordinator-jwpmmu-5d5b596458-jh8fm   1/1     Running     9          20h
snark-worker-jwpmmu-687bb9968f-549km        1/1     Running     6          3h11m
snark-worker-jwpmmu-687bb9968f-5lgrv        1/1     Running     7          5h43m
snark-worker-jwpmmu-687bb9968f-6bfnx        1/1     Running     12         20h
snark-worker-jwpmmu-687bb9968f-6f77l        1/1     Running     12         20h
snark-worker-jwpmmu-687bb9968f-7j2kd        1/1     Running     13         20h
snark-worker-jwpmmu-687bb9968f-8k8z8        1/1     Running     8          20h
snark-worker-jwpmmu-687bb9968f-dxtzn        1/1     Running     5          3h11m
snark-worker-jwpmmu-687bb9968f-ggk9c        1/1     Running     5          20h
snark-worker-jwpmmu-687bb9968f-gx9d4        1/1     Running     11         20h
snark-worker-jwpmmu-687bb9968f-jq6st        1/1     Running     3          3h11m
snark-worker-jwpmmu-687bb9968f-lvh4l        1/1     Running     4          20h
snark-worker-jwpmmu-687bb9968f-m2lzs        1/1     Running     11         20h
snark-worker-jwpmmu-687bb9968f-pbbx9        1/1     Running     0          20h
snark-worker-jwpmmu-687bb9968f-pmpgv        1/1     Running     11         20h
snark-worker-jwpmmu-687bb9968f-pxmtm        1/1     Running     12         20h
snark-worker-jwpmmu-687bb9968f-q5cpt        1/1     Running     2          83m
snark-worker-jwpmmu-687bb9968f-rmclw        1/1     Running     0          20h
snark-worker-jwpmmu-687bb9968f-rvwhg        1/1     Running     4          20h
snark-worker-jwpmmu-687bb9968f-szktj        1/1     Running     12         20h
snark-worker-jwpmmu-687bb9968f-wlzwm        1/1     Running     10         20h
testworld-archive-node-postgresql-0         1/1     Running     0          20h
whale-block-producer-1-7454fd65b9-dxb8z     0/1     Running     1          4m31s
whale-block-producer-10-d8747f78f-4r9js     0/1     Evicted     0          19h
whale-block-producer-10-d8747f78f-bvlcb     0/1     Running     5          12h
whale-block-producer-11-7bcf6ff8c6-z5f2d    0/1     Running     2          83m
whale-block-producer-12-69df566975-26d45    1/1     Running     4          19h
whale-block-producer-13-564cd47fbb-rhkqs    1/1     Running     0          19h
whale-block-producer-14-55dcf47d77-65zkw    0/1     Running     5          19h
whale-block-producer-15-77fb858bb4-qz75p    1/1     Running     8          19h
whale-block-producer-2-76594b96c6-6n5pb     0/1     Running     13         19h
whale-block-producer-3-fffcb984c-84mlg      1/1     Running     0          18h
whale-block-producer-4-6d577c4cf8-wf9r9     1/1     Running     6          19h
whale-block-producer-5-5479c96cbf-rd2xg     1/1     Running     3          19h
whale-block-producer-6-59c7f57568-fjmls     1/1     Running     11         19h
whale-block-producer-7-75d77d4855-k8s7m     1/1     Running     1          19h
whale-block-producer-8-6fc8b65c78-7bnx4     1/1     Running     11         19h
whale-block-producer-9-c5fcf59b9-4m2gl      1/1     Running     2          3h12m

**Comment by aneesharaines** [comment]
Closing because we haven't seen this recently and have made alot of fixes around uptime.  @es92 - please reopen if this happens again

**Comment by es92** [comment]
From a chance conversation with Deepthi thinking this is likely from #7606. Keeping closed for now, hopefully when that's fixed our nodes will stop crashing too
