### ISSUE TITLE
Mina Metrics: Peers is always zero.

### ISSUE THREAD

**Issue by jongkwang** [MinaProtocol/mina#7293]
## Environment
- Version : Testnet 5.0 (mina-testnet-postake-medium-curves=0.2.2-b7eff8e)
- OS : Ubuntu 18.04
- 10 nodes were operated in the same environment, but occurred in two.

## Issue
- Mina Metrics : 0 peers
- Mina GraphQL(3085 port) : 43 peers
- <code>coda client status</code> : 43 peers 

Only this node has a Mina Metrics value always zero.

![스크린샷_2021-01-01_오전_10_36_18](https://user-images.githubusercontent.com/897510/103432586-d5892280-4c24-11eb-8642-8088d634bbb5.png)

**Comment by garethtdavies** [comment]
Duplicate of https://github.com/MinaProtocol/mina/issues/6022

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
