### ISSUE TITLE
Nodes that are peered directly with collect peers above the 50 cap (hundreds)

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#7295]

**Comment by es92** [comment]
This may be related to the other issue seen here, as we're noticing that issue only on our nodes but not the community nodes: https://github.com/MinaProtocol/mina/issues/7294

**Comment by aneesharaines** [comment]
Elizabeth is investigating why we aren't respecting the max.  Also need another set of eyes.

**Comment by bkase** [comment]
I'm closing this as a dupe of the (slightly more detailed) #7421
