### ISSUE TITLE
Nodes initially "offline" and not catching up until a block is gossiped?

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#7297]

**Comment by ghost-not-in-the-shell** [comment]
The description is a little bit vague.

Node would be `offline` in two situations:

1. when it was just created;
2. when it hadn't received any message for 8 slots.

For 1, when the node was just created, it should ask its peers for their best tip and use that to trigger catchup. Only in situations that it fails to collect peers' best tip, then it needs to do wait for network transitions to trigger catchup manually.

For 2, it probably means there's something wrong with the network?

**Comment by ghost-not-in-the-shell** [comment]
After looking into #7294, it seems like the online status could be broken.
