### ISSUE TITLE
GraphQL API bug in Testworld: 

### ISSUE THREAD

**Issue by jasongitmail** [MinaProtocol/mina#7299]
I successfully connected to my Testworld node's GraphQL API (using [apollo-boost](https://www.npmjs.com/package/apollo-boost)). The node `Sync status` is `Synced`.

I can receive successful responses for `syncStatus`:
```js
{
  data: { syncStatus: 'SYNCED' },
  loading: false,
  networkStatus: 7,
  stale: false
}
```

and `version`:

```js
{
  data: { version: '[DIRTY]b7eff8e5c966b12bdc298160297c716eae7a35af' },
  loading: false,
  networkStatus: 7,
  stale: false
}
```

But other queries return no data:
```js
{
  data: { genesisBlock: {} },
  loading: false,
  networkStatus: 7,
  stale: false
}
```

```js
{
  data: { daemonStatus: {} },
  loading: false,
  networkStatus: 7,
  stale: false
}
```

```js
{
  data: { trackedAccounts: [ {} ] },
  loading: false,
  networkStatus: 7,
  stale: false
}
```
`snarkPool` is interesting because the array has a realistic length but each individual item is empty:
```js
{
  data: {
    snarkPool: [
      {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {},
      {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {},
      {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {},
      {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {},
      {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {},
      {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {},
      {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {},
      {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {},
      {}, {}, {}, {},
      ... 8919 more items
    ]
  },
  loading: false,
  networkStatus: 7,
  stale: false
}

{} // data.snarkPool[0]
```

**Comment by garethtdavies** [comment]
@jasongitmail I am not familiar with apollo boost but judging on the queries that are returning successfully I suspect you are not specifying the fields you want returned?

For example, a query for `daemonStatus` could look like this:

```
query {
  daemonStatus {
    blockchainLength
    chainId
    consensusTimeNow {
      globalSlot
    }
  }
}
```

The examples you listed as working only return a single field, so I imagine the issue is with your requests.

**Comment by jasongitmail** [comment]
That may be it. I saw the list of [query types in the docs](https://minaprotocol.com/graphql-docs/query.doc.html) and based my queries off that. But will dig it into the API docs further. Thanks.
