### ISSUE TITLE
docker logs mina

### ISSUE THREAD

**Issue by ibrahimarslann59** [MinaProtocol/mina#7300]
docker exec -it mina coda client stop-daemon script does not work and the process ends. what is the reason?
![1](https://user-images.githubusercontent.com/38531647/103446934-11a89b80-4c96-11eb-94fb-a78e8de0b7fb.png)

**Comment by ibrahimarslann59** [comment]
my output
![2](https://user-images.githubusercontent.com/38531647/103446940-1ff6b780-4c96-11eb-87c6-6ba833816643.png)

**Comment by ibrahimarslann59** [comment]
![d3](https://user-images.githubusercontent.com/38531647/103446978-7a901380-4c96-11eb-81b9-2ca662fd6728.png)
![d2](https://user-images.githubusercontent.com/38531647/103446979-7bc14080-4c96-11eb-85bd-d0a72545187e.png)
![d1](https://user-images.githubusercontent.com/38531647/103446982-7c59d700-4c96-11eb-9258-75c447320cc3.png)
![21](https://user-images.githubusercontent.com/38531647/103446983-7d8b0400-4c96-11eb-9fe0-ed8fe325b6dc.png)

**Comment by erfan007p** [comment]
stop coda, remove and recreate .coda-config folder, restart it.
