### ISSUE TITLE
[FEATURE] @o1labs/client-sdk - Allow mapping from private key to public key

### ISSUE THREAD

**Issue by jason-james** [MinaProtocol/mina#7302]
I have a half finished web wallet for Mina which I haven't been able to complete due to a some missing features in the SDK. The features required are:

* A way to go from privateKey -> address. 

Currently, we can use `genKeys()` to generate am address and private key pair, however, after giving that to a user, there is no way for us to retrieve their address if they give us **only** their private key. I would like there to be a function such as `getAddress(string privateKey)`, which returns the Mina address associated with a private key. After that, we can query the daemon with the address to get its balance details, nonce, etc, which then allows a login functionality to the wallet.

* A way to go from privateKey -> wallet.json and vice versa.

A function such as `createWallet(string privateKey)` which creates a wallet JSON that can be written to a file and used with the daemon. Ideally the `getAddress` function above would also accept a wallet JSON, so that users would not need to enter their plaintext privatekey on the website, but can provide the wallet file instead. This would also mean users could use the wallets generated by the daemon and given to users for testworld (because we don't have the plain private keys associated with those). We also need a way to go from wallet.json -> privateKey then, so that we are able to sign transactions using the private key with the `signPayment` method that already exists in the SDK.

**Comment by bkase** [comment]
> A way to go from privateKey -> address

This is very easy for us to add and we should definitely do this

> A way to go from privateKey -> wallet.json and vice versa

This one will be a bit more difficult so we may not get to it as quickly as this encryption code depends on C

**Comment by jason-james** [comment]
What kind of timeframe should I expect for each one to be implemented?
