### ISSUE TITLE
In sync nodes periodically go Offline and restart - with connected peers

### ISSUE THREAD

**Issue by jrwashburn** [MinaProtocol/mina#7307]
It seems to be fairly widespread and persistent - I have nodes that are in sync and running fine, then go offline. Several others also experiencing per discord. Logs from two nodes and 5 incidents shared to logs@o1labs in google drive:
https://drive.google.com/drive/folders/1QAy7hQV7h_cUNgIJD5Ug3uS-qtttS8Sv?usp=sharing

I have also 1) captured netstat to show connections are open, and 2) started capturing coda client status every 5 mins just to see that nodes are going offline and restarting as expected (they are.) 

Node 1 was 16vcpu/64G dedicated digital ocean (cpu peaks around 80%)
Node 2 was 32vcpu/64G dedicated digital ocean running only snark worker (cpu never about ~45%)

I have tried upping -max-connections to 100, and also -enable-peer-exchange true -- to no effect.

Other Issues that are about Nodes offline, but do not seem to be the same, listed in case related. Both are from prior testnet.
https://github.com/MinaProtocol/mina/issues/6882 - seems different because there is not a syncing problem.
https://github.com/MinaProtocol/mina/issues/6819 - may be related but insufficient information provided.

**Comment by Syd-ai** [comment]
![image](https://user-images.githubusercontent.com/58671114/103482041-c057f380-4dde-11eb-9097-fdee6785fabe.png)

**Comment by jrwashburn** [comment]
Likely related to https://github.com/MinaProtocol/mina/issues/7293

**Comment by aasolhjou** [comment]
I am also experiencing this issue on all of my nodes

**Comment by deni64k** [comment]
The same.

**Comment by deni64k** [comment]
One of node thinks it is `Synced` at height 2.
![image](https://user-images.githubusercontent.com/107541/103484365-4b73c200-4dbc-11eb-9880-5c53823f4b0c.png)

**Comment by jrwashburn** [comment]
New logs captured with: attempt to proactively add peers when offline detected, and netstat while offline

Logs created using exported-logs here (shared w/ logs@o1labs.) The folder also includes 1) watchdog.txt generated by https://github.com/jrwashburn/mina-utils/blob/main/status-watchdog.sh which is what attempted to add new peers, 2) coda client status logged every 5 minutes, 3) netstat captured while in offline state.

https://drive.google.com/drive/folders/1YROXKQTyLd-BPNLRgHY04fJn5p3geSws?usp=sharing

**Comment by ArtemBernatskyy** [comment]
Same here, we've tried a bunch of scenarios for BP nodes (8CPU/ 32 RAM, 4 CPU / 64RAM etc), also a couple of flags such as `-enable-flooding true -enable-peer-exchange true -max-connections 100`.
We were thinking of running a bunch of BP nodes, then selecting those who will be in sync, then using `isolate-network` flag to connect to such sync nodes (ideally via internal cloud provider IP to minimize network overhead). But it won't be a blockchain then ...

I'm not an expert in blockchains but my gut feeling is that the more stable nodes will be present in blockchain the easier for new nodes to sync. In our case, lots of people have issues with syncing right now thus keeping the network in a shaken state.

**Comment by nkiki** [comment]
same....
![image](https://user-images.githubusercontent.com/61766044/103791527-835d5c80-507d-11eb-8ffb-508b2bc5b8b5.png)
![image](https://user-images.githubusercontent.com/61766044/103791538-87897a00-507d-11eb-9212-2179e44bb26d.png)

**Comment by jrwashburn** [comment]
This can be closed; new versions are stable and this is not occurring.
