### ISSUE TITLE
Sync still in "Catchup" & Block Height to 1

### ISSUE THREAD

**Issue by justin-lacroix** [MinaProtocol/mina#7308]
Hello, it seems that I have a problem during the synchronization. The status has remained on "Catchup" for a while, impossible to switch to "Synced" status.

I tried to restart several times but same results.

In the logs, I get several RPC errors: 

**2021-01-03 20:52:07 UTC [Warn] failed to reset stream (this means it was probably closed successfully): $ error
error: {
  "string":
    "RPC # 5601 failed: \" internal RPC error error: unknown stream_idx \ ""**

Someone can help me ? Thank you so much :)

**Comment by garethtdavies** [comment]
@justin-lacroix this is a common issue struggling to catchup and getting synced, particularly recently on this testnet. Those log errors are "normal" and expected. You would likely be better off asking this question in #mentor-nodes in Discord for some more direct help. There's a bit more here too https://minaprotocol.com/docs/troubleshooting#my-node-is-stuck-in-catchup--the-block-height-does-not-update but machine specs also play a very large role so ensure you meet the minimum specifications.

**Comment by mrmr1993** [comment]
Closing: this would need more info to debug, and the time to collect that info has likely long passed.
