### ISSUE TITLE
[FEATURE] Please allow to pass trustlist as a parameter during Daemon startup

### ISSUE THREAD

**Issue by dheeraj07** [MinaProtocol/mina#7310]
It's good that we have an option to add/delete the ip's from trust-list on the go. But every-time daemon restarts, existing trust-list is getting reset. 

If possible, please allow trust-list as a parameter during the daemon startup.

Thanks.

**Comment by garethtdavies** [comment]
With the caveat I have never tried this, what about setting this environment variable? `CODA_CLIENT_TRUSTLIST` ref https://github.com/MinaProtocol/mina/blob/22bf35b6e09a31dc6cebf90841c59d85a4a9869c/docs/daemon.md#environment-variables

**Comment by aneesharaines** [comment]
Need to update env var from coda to mina as well as make consistent.

**Comment by dheeraj07** [comment]
> With the caveat I have never tried this, what about setting this environment variable? `CODA_CLIENT_TRUSTLIST` ref https://github.com/MinaProtocol/mina/blob/22bf35b6e09a31dc6cebf90841c59d85a4a9869c/docs/daemon.md#environment-variables

Sure, will try this!

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
