### ISSUE TITLE
Integration Test Core: Improved wait_for

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#7317]
The `wait_for` function is one of the key functions for writing tests in the new integration test framework. It allows a test to wait for a condition to happen, with both a soft and hard timeout (defaults for which can be automatically derived from the condition we specify). In the current implementation, `wait_for` is a large function that accepts a variety of optional arguments on what to wait for, and will wait for all conditions specified to be true before continuing. This makes it annoying to add new conditions to `wait_for`. We can instead design `wait_for` define an type of a "condition", and conditions can be passed in directly, separating the core `wait_for` logic from the description of each condition. We can also define combinators for these conditions to still allow multiple conditions to be combined into one `wait_for` step.

Here is an example of how such a `wait_for` function could be setup. This example is somewhat naive (which will be explained below) but should server as a basis we can use to provide extended functionality later.

```
(* network state is all of the data collected and derived from stack driver subscriptions *)
type network_state = { ... }

(* timeout representation, abstracted over network parameters *)
type timeout =
  | Slots of int
  | Epochs of int
  | ...
  | Span of Time.Span.t

type condition =
  { condition_subscription: network_state -> bool
  ; soft_timeout: timeout
  ; hard_timeout: timeout }

val wait_for : condition -> unit Malleable_error.t
```

The notion of a timeout is explicitly abstracted over any network parameters required to compute a concrete time span so that conditions do not need to be written in a scope that is aware of network parameters.

There are a couple of limitations to this specific design. Notably, there is no way for a condition to specify what portion of network state it is interested in consuming. Instead, network_state needs to be statically declared, and any update to network_state needs to be checked by the condition. This is probably ok for now, but as we scale upwards, will not be ok. Another issue of this particular approach is that there isn't any way for a condition to block on any state that needs to be pulled from GraphQL (unless we globally pull from GraphQL on an interval in our network state update logic, which is potentially expensive). Still, this abstraction brings us in the write direction long term, and we can address those issues by updating the type definition for a `condition`.

With this interface, we can now separate the definition of each condition from the remote network integration test engine, moving it up into a layer that is common across engines (ie they can be reused for local network tests later down the road). Below is an example of what a new condition module might contain.

```
val initialization : node -> condition
val blocks_produced : int -> condition
...

(* combine a list of conditions into a single condition *)
val combine : condition list -> condition

(* override default condition timeouts *)
val with_timeouts : ?soft_timeout:timeout -> ?hard_timeout:timeout -> condition -> condition
```

These functions for construction conditions would be responsible for computing a sane soft_timeout and hard_timeout for the condition based off of the arguments provided to the function. A user can then manually override these timeouts using `with_timeouts` function.

**Comment by imeckler** [comment]
@nholland94 in the future, we could use incremental and have the condition be `Network_state.t Incr.t -> bool Incr.t`. Then we can project out components of the network state to avoid recomputing the condition on every update
