### ISSUE TITLE
Integration Test Core: CI

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#7319]
We need to get the integration test framework running in buildkite. For now, we should only enable the cheap, stable integration tests for every build (block-production, send-payment), but long term, we want to have the ability to run more expensive tests as nightlies.

## What has been done so far

Currently, credentials for deploying networks over kubernetes are setup for buildkite agents.

## What still needs to be done

Setup buildkite agent to configure kubectl to the correct context for the integration test cluster. Enable the jobs in dhall for running the integration tests, and get at least the block-production and send-payment tests passing through those jobs.

**Comment by QuiteStochastic** [comment]
https://github.com/MinaProtocol/mina/pull/5603/files

**Comment by QuiteStochastic** [comment]
we have a minimal viable implementation up with just the block production test.  the rest will be put in when graphql ingress is properly set up, see this ticket https://github.com/MinaProtocol/mina/issues/7316

**Comment by QuiteStochastic** [comment]
This ticket is done for just the block production test, but for all the other tests see https://github.com/MinaProtocol/mina/pull/8088

**Comment by QuiteStochastic** [comment]
Everything except pmt-timed-accts is now in CI! the last one is slightly bugged, it'll get in when it's fixed, but in general integration tests are now good for CI
