### ISSUE TITLE
integration test timeout while waiting for initialization

### ISSUE THREAD

**Issue by QuiteStochastic** [MinaProtocol/mina#7320]
The seed node, snark coordinator, and all the block producers generated by the integration test are crash looping, causing the call `Log_engine.wait_for_init` to time out.

This is happening for every integration test

**Comment by nholland94** [comment]
Sounds like the seed node did not come online successfully. I would try again and check the stackdriver logs for the seed node to see if there is any useful information there. Only logproc compatible logs are subscribed to by the test executive, so if the daemon failed to startup with some kind of top-level fatal error (which gets printed as a multiline sexp or plain text sometimes), then it doesn't show up in the test executives errors.

**Comment by 0x0I** [comment]
Also re: the `Readiness probe failed: Daemon is out of sync with status: /healthcheck/utilities.sh: line 9: jq: command not found` error, looks like the image(s) being used need to be updated to capture changes or include network utilities like `jq` directly.

Mind including the image details?

**Comment by QuiteStochastic** [comment]
> Also re: the `Readiness probe failed: Daemon is out of sync with status: /healthcheck/utilities.sh: line 9: jq: command not found` error, looks like the image(s) being used need to be updated to capture changes or include network utilities like `jq` directly. Thinking just a case of a daemon image update but mind including the image details?

the image being used was `codaprotocol/coda-daemon-puppeteered:0.0.16-beta7-develop`

**Comment by 0x0I** [comment]
> codaprotocol/coda-daemon-puppeteered:0.0.16-beta7-develop

Makes sense @QuiteStochastic -- that image doesn't contain recent changes to add tooling like `jq`.
```
docker run --entrypoint /bin/bash -it codaprotocol/coda-daemon-puppeteered:0.0.16-beta7-develop
root@b35b7c364ec2:~# which jq
root@b35b7c364ec2:~# jq
bash: jq: command not found```

You'll probably want to update the image to something more recent like `codaprotocol/coda-daemon-puppeteered:0.2.0-develop`.

**Comment by QuiteStochastic** [comment]
@0x0I now that we're using the 0.2.0-develop image, nodes are crash looping, which similarly leads to the initialization timeout but probably for a different reason

**Comment by QuiteStochastic** [comment]
this was fixed by https://github.com/MinaProtocol/mina/pull/7561
