### ISSUE TITLE
lost block reward

### ISSUE THREAD

**Issue by bakarapara** [MinaProtocol/mina#7330]
i generated block (481) and got rewards for it, literally, block was green and i received about 17k tokens to my wallet. 
but then, in 30 minutes(!!), someone else generated same block again, with much less snarks and transactions and i lost my reward. is it expected behaviour? what happened with all snarks and transactions that were included in my block? how its possible to generare same block in different spot 30 min's later? and rollback all fees for that block? 
<img width="1375" alt="Mina Block Explorer 2021-01-05 11-08-46" src="https://user-images.githubusercontent.com/16775625/103617729-32981780-4f48-11eb-88a4-99e4cf3f88b2.png">

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
