### ISSUE TITLE
Investigate if Max-connections flag is connected properly

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#7331]
There are reports from community members that this parameter seems to have absolutely no effect, but I recall that we did see it having an effect in older testnets. Did this regress?

**Comment by garethtdavies** [comment]
As some evidence, this chart is the historical peer count of a node (hourly snapshot) with no flag set so using defaults https://minaexplorer.com/stats#peer-count

It's clear the first few days running the node the peer count was always higher than that max value and as high as 133.

**Comment by bkase** [comment]
Closing as duplicate of #7421
