### ISSUE TITLE
Segfault crashes

### ISSUE THREAD

**Issue by smartass111** [MinaProtocol/mina#7333]
noticed crash ~20 hours ago in dmesg (should be UTC+3 timestamp)

[Tue Jan  5 00:10:26 2021] show_signal_msg: 20 callbacks suppressed
[Tue Jan  5 00:10:26 2021] coda[1363500]: segfault at b ip 0000562d82bb5b8e sp 00007ffcc485c7a0 error 4 in coda[562d7f851000+3b52000]
[Tue Jan  5 00:10:26 2021] Code: 1e a1 00 48 8d 44 24 20 48 89 44 24 40 0f 28 05 a8 2e 26 00 0f 11 44 24 30 be 01 00 00 00 4c 89 ff ff 15 cd 33 a1 00 49 89 c1 <48> 8b 28 49 bf ff ff ff ff ec 30 2d 99 48 89 eb 49 0f af df 48 b9

here are 275M logs https://www.dropbox.com/s/z3vk9l5b9fehw11/2021-01-05_17-10-59.tar.gz?dl=0
crash report 
[coda_crash_report_2021-01-05_01-00-40.724909.tar.gz](https://github.com/MinaProtocol/mina/files/5771723/coda_crash_report_2021-01-05_01-00-40.724909.tar.gz)

**Comment by smartass111** [comment]
one more segfault observed

[Wed Jan  6 19:40:44 2021] coda[1601722]: segfault at 408 ip 00005579237a9b8e sp 00007ffd55ec6900 error 4 in coda[557920445000+3b52000]
[Wed Jan  6 19:40:44 2021] Code: 1e a1 00 48 8d 44 24 20 48 89 44 24 40 0f 28 05 a8 2e 26 00 0f 11 44 24 30 be 01 00 00 00 4c 89 ff ff 15 cd 33 a1 00 49 89 c1 <48> 8b 28 49 bf ff ff ff ff ec 30 2d 99 48 89 eb 49 0f af df 48 b9

logs - https://www.dropbox.com/s/bfgmzqha77t15lr/2021-01-07_00-52-21.tar.gz?dl=0
[coda_crash_report_2021-01-06_16-31-59.574695.tar.gz](https://github.com/MinaProtocol/mina/files/5778900/coda_crash_report_2021-01-06_16-31-59.574695.tar.gz)

**Comment by dheeraj07** [comment]
crashed because of segmentation fault.
Please take a look at the attached logs 
<img width="1081" alt="Screen Shot 2021-01-07 at 10 27 30 PM" src="https://user-images.githubusercontent.com/22843503/103922080-4a82bd80-5139-11eb-9488-23872a97fbad.png">


https://drive.google.com/file/d/1x3VJN10WcOOPclPunN1VsNxJTA6EOnE0/view?usp=sharing

**Comment by mrmr1993** [comment]
@dheeraj07 can you upload the core dump file? They're usually stored in `/var/lib/systemd/coredump`

**Comment by dheeraj07** [comment]
but 'coredump' folder is empty! @mrmr1993

**Comment by mrmr1993** [comment]
It may also be in `/var/crash`?

**Comment by dheeraj07** [comment]
no, it is also empty :(
fyi, I'm running through docker

**Comment by mrmr1993** [comment]
I've been investigating the coredump from our node.

The backtrace is
```
#0  marlin_plonk_stubs::pasta_fp::caml_pasta_fp_to_bigint::{{closure}}::inner (x=...) at src/pasta_fp.rs:148
#1  marlin_plonk_stubs::pasta_fp::caml_pasta_fp_to_bigint::{{closure}} () at src/pasta_fp.rs:146
#2  caml_pasta_fp_to_bigint (x=...) at src/pasta_fp.rs:146
#3  0x0000559a860ed023 in camlPasta__Basic__fun_9359 ()
    at src/lib/marlin_plonk_bindings/pasta_fp/marlin_plonk_bindings_pasta_fp.ml:53
#4  0x0000559a85bdf7dd in camlNon_zero_curve_point__parity_1039 ()
    at src/lib/non_zero_curve_point/non_zero_curve_point.ml:11
#5  0x0000559a85be0760 in camlNon_zero_curve_point__compress_41682 ()
    at src/lib/non_zero_curve_point/non_zero_curve_point.ml:118
#6  0x0000559a867681fd in camlBin_prot__Utils__bin_size_t_2627 () at src/utils.ml:101
#7  0x0000559a85be12fe in camlNon_zero_curve_point__bin_size_t_80658 ()
    at src/lib/non_zero_curve_point/non_zero_curve_point.ml:184
#8  0x0000559a859a0cc7 in camlMina_base__Signed_command__bin_size_t_2001 () at src/lib/mina_base/signed_command.ml:24
#9  0x0000559a859a192e in camlMina_base__Signed_command__bin_size_t_2837 () at src/lib/mina_base/signed_command.ml:24
#10 0x0000559a859a2d90 in camlMina_base__Signed_command__bin_size_t_18148 () at src/lib/mina_base/signed_command.ml:34
#11 0x0000559a85a7768f in camlMina_base__User_command__bin_size_t_1981 () at src/lib/mina_base/user_command.ml:7
#12 0x0000559a85a78164 in camlMina_base__User_command__bin_size_t_2743 () at src/lib/mina_base/user_command.ml:7
#13 0x0000559a85a7a0e0 in camlMina_base__User_command__bin_size_t_17706 () at src/lib/mina_base/user_command.ml:74
#14 0x0000559a8593cf16 in camlMina_base__With_status__bin_size_t_2538 () at src/lib/mina_base/with_status.ml:6
#15 0x0000559a8593d88d in camlMina_base__With_status__bin_size_t_3335 () at src/lib/mina_base/with_status.ml:6
#16 0x0000559a86763c9b in camlBin_prot__Size__loop_2096 () at src/size.ml:174
#17 0x0000559a856ee2dc in camlStaged_ledger_diff__bin_size_t_8442 () at src/list0.ml:6
#18 0x0000559a856ef354 in camlStaged_ledger_diff__bin_size_t_8649 ()
    at src/lib/staged_ledger_diff/staged_ledger_diff.ml:107
#19 0x0000559a856f1da0 in camlStaged_ledger_diff__bin_size_t_15296 ()
    at src/lib/staged_ledger_diff/staged_ledger_diff.ml:152
#20 0x0000559a86763b18 in camlBin_prot__Size__bin_size_option_2075 () at src/size.ml:164
#21 0x0000559a856f24b3 in camlStaged_ledger_diff__bin_size_t_15470 () at src/option.ml:3
#22 0x0000559a856f299e in camlStaged_ledger_diff__bin_size_t_15549 ()
    at src/lib/staged_ledger_diff/staged_ledger_diff.ml:171
#23 0x0000559a856f367f in camlStaged_ledger_diff__bin_size_t_15807 ()
    at src/lib/staged_ledger_diff/staged_ledger_diff.ml:188
#24 0x0000559a856af1eb in camlCoda_transition__External_transition__bin_size_t_7849 ()
    at src/lib/coda_transition/external_transition.ml:31
#25 0x0000559a856b0050 in camlCoda_transition__External_transition__bin_size_t_9976 ()
    at src/lib/coda_transition/external_transition.ml:31
#26 0x0000559a86763c9b in camlBin_prot__Size__loop_2096 () at src/size.ml:174
#27 0x0000559a86763b18 in camlBin_prot__Size__bin_size_option_2075 () at src/size.ml:164
#28 0x0000559a858d0565 in camlPerf_histograms__Rpc__bin_read_response_17691 () at src/lib/perf_histograms/rpc.ml:83
#29 0x0000559a86521c4b in camlAsync_rpc_kernel__Util__bin_read_from_bigstring_1055 () at src/util.ml:8
#30 0x0000559a8652b451 in camlAsync_rpc_kernel__Rpc__response_handler_12704 () at src/monad.ml:36
#31 0x0000559a865287d9 in camlAsync_rpc_kernel__Connection__handle_response_23125 () at src/connection.ml:152
#32 0x0000559a86528ed5 in camlAsync_rpc_kernel__Connection__f_24734 () at src/connection.ml:236
#33 0x0000559a8653e908 in camlAsync_rpc_kernel__Pipe_transport__process_data_2867 () at src/pipe_transport.ml:88
#34 0x0000559a8653edbb in camlAsync_rpc_kernel__Pipe_transport__fun_11974 () at src/pipe_transport.ml:140
#35 0x0000559a86571b21 in camlAsync_kernel__Deferred0__fun_1493 () at src/deferred0.ml:56
#36 0x0000559a865581b0 in camlAsync_kernel__Job_queue__run_jobs_4139 () at src/job_queue.ml:131
#37 0x0000559a8656dfe4 in camlAsync_kernel__Scheduler1__run_jobs_13227 () at src/scheduler1.ml:334
#38 0x0000559a8658877e in camlAsync_kernel__Scheduler__run_jobs_15236 () at src/scheduler.ml:178
#39 0x0000559a865885c9 in camlAsync_kernel__Scheduler__run_cycle_14642 () at src/scheduler.ml:186
#40 0x0000559a863f50c4 in camlAsync_unix__Raw_scheduler__have_lock_do_cycle_43223 () at src/raw_scheduler.ml:676
#41 0x0000559a863f659d in camlAsync_unix__Raw_scheduler__loop_47098 () at src/raw_scheduler.ml:920
#42 0x0000559a863f6359 in camlAsync_unix__Raw_scheduler__be_the_scheduler_inner_53408 () at src/raw_scheduler.ml:924
#43 0x0000559a863d7630 in camlAsync_extra__Command__fun_16455 () at src/command.ml:75
#44 0x0000559a866da9ed in camlCore_kernel__Command__fun_42621 () at src/command.ml:2817
#45 0x0000559a86788e9d in camlBase__Exn__handle_uncaught_aux_2602 () at src/exn.ml:107
#46 0x0000559a8550f8f4 in camlDune__exe__Coda__entry () at src/app/cli/src/coda.ml:1440
#47 0x0000559a854f1129 in caml_program ()
#48 0x0000559a870e6780 in caml_start_program ()
#49 0x0000559a870ca995 in caml_startup_common (argv=0x7ffc2fdddd08, pooling=<optimized out>, pooling@entry=0)
    at startup.c:157
#50 0x0000559a870ca9eb in caml_startup_exn (argv=<optimized out>) at startup.c:162
#51 caml_startup (argv=<optimized out>) at startup.c:167
#52 0x0000559a854eabac in main (argc=<optimized out>, argv=<optimized out>) at main.c:44
```
and we have
```
print (x)
$7 = ocaml::value::Value (0x0)
```

As best I can tell, the possible causes are:
* the rust compiler re-ordered the allocation of the return value in `caml_pasta_fp_to_bigint` to happen before the memory access
  - this is unlikely, but hard to check with the current disassembly due to dynamic dispatch
  - I will try putting explicit copies in this and related bindings, to see whether/how the disassembly changes
* the function that created the value allocated it but it was moved before it was filled
  - this is far more likely, I will audit the bindings to check whether this may be happening
* unrelated corruption that happened to overwrite this memory
  - there is no way to detect this from the current core dump; if we see a crash during a minor GC then this will be easy to identify

The value didn't appear come from the minor heap, so it's highly unlikely that the value is overlapping with another value at the snapshotted time.

Beyond these checks, we should look for further segfaults and collect core dumps for them.

**Comment by dheeraj07** [comment]
Crashed with segmentation fault. Please find the attached logs

<img width="1067" alt="Screen Shot 2021-01-20 at 10 03 17 PM" src="https://user-images.githubusercontent.com/22843503/105214200-b3c0f280-5b75-11eb-8115-f6f5169b319c.png">

https://drive.google.com/file/d/16GJ-cUQpkLBS3URJ1j6l4cZD4upl5bK0/view?usp=sharing

**Comment by mrmr1993** [comment]
@Igor-Tselkovskiy also reported seeing this in in #7572

> https://drive.google.com/file/d/1EHBkXsgyjhd7lwEXpbC1n2W8klCu3K74/view?usp=sharing
> 
> {"timestamp":"2021-01-20 22:07:36.352926Z","level":"Debug","source":{"module":"Snark_worker__Functor","location":"File "src/lib/snark_worker/functor.ml", line 169, characters 8-20"},"message":"Snark worker working directory $dir","metadata":{"dir":"/root","pid":359,"process":"Snark Worker"}}
> {"timestamp":"2021-01-20 22:07:36.353004Z","level":"Debug","source":{"module":"Snark_worker__Functor","location":"File "src/lib/snark_worker/functor.ml", line 181, characters 6-18"},"message":"Snark worker using daemon $addr","metadata":{"addr":"127.0.0.1:8301","pid":359,"process":"Snark Worker"}}
> {"timestamp":"2021-01-20 22:07:36.727423Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File "src/lib/snark_worker/functor.ml", line 201, characters 10-21"},"message":"SNARK work $work_ids received from $address. Starting proof generation","metadata":{"address":"127.0.0.1:8301","pid":359,"process":"Snark Worker","work_ids":[727884389,658267815]}}
> 2021-01-20 22:08:29 UTC [Info] verifier successfully got sigkill
> 2021-01-20 22:08:29 UTC [Info] verifier successfully stopped
> 2021-01-20 22:08:29 UTC [Info] Daemon started process of kind "Verifier" with pid 568
> /root/init_coda_baked.sh: line 14: 12 Segmentation fault (core dumped) coda "$command" -config-file "/root/daemon.json" "$@" 2>&1 > coda.log
> 
>     * echo 'Coda process exited with status code 139'
> 
>     * sleep 10
>       Coda process exited with status code 139
> 
>     * kill 13
> 
>     * '[' '!' -f stay_alive ']'
> 
>     * exit 0

**Comment by mrmr1993** [comment]
Tentatively closing this now that #7669 has landed. Will re-open if we are still seeing segfaults after the next release.
