### ISSUE TITLE
Potential memory leakage

### ISSUE THREAD

**Issue by ru-errorist** [MinaProtocol/mina#7335]
After implementing a monitoring system, I figured out that coda process shows signs of RAM leakage:
![2021-01-05_18-17-39-972_brave](https://user-images.githubusercontent.com/7092693/103686485-f1cbed00-4f9f-11eb-907e-5877e587092e.png)

Memory allocation on a server looks like this:
![2021-01-05_18-17-01-290_brave](https://user-images.githubusercontent.com/7092693/103686595-1de76e00-4fa0-11eb-9ae1-6b293e40ce17.png)

I'm running `Commit [DIRTY]b7eff8e5c966b12bdc298160297c716eae7a35af on branch HEAD` for testnet 5.1. The node server is a dedicated 'AX51-NVME' instance at Hetzner. I moved there from c5.2xlarge instance at AWS on which I experienced 'Bootstrap' and 'Catchup' states all the time.

I assume coda process hits a memory limit then falls with an error so 'Bootstrap' and 'Catchup' phases begin but on a underperformed hardware it might never get to 'Synced' state cause as for now syncing takes a bit of time. As it could be seen, current requirements do not meet the actual RAM consumption. Nevertheless a stable process should not use memory in a saw-like pattern.

Logs from `coda client export-logs` are [here](https://www.mediafire.com/file/r9liyapgj8gdzpe/logs.txt.tar.gz/file).

**Comment by ghost-not-in-the-shell** [comment]
Nodes from O1labs also have spikes of 35 GB ram usage:

https://console.cloud.google.com/kubernetes/deployment/us-central1/coda-infra-central1/testworld/whale-block-producer-8/overview?authuser=0&project=o1labs-192920&pageState=(%22savedViews%22:(%22i%22:%220c7f333508864ca4940da74aa1d15606%22,%22c%22:%5B%5D,%22n%22:%5B%22testworld%22%5D),%22deployment_overview_active_revisions_table%22:(%22r%22:50)

**Comment by ru-errorist** [comment]
![2021-01-06_15-20-44-070_brave](https://user-images.githubusercontent.com/7092693/103768057-d3630180-5032-11eb-8b7c-203baa76305e.png)
Seeing this right now

**Comment by ru-errorist** [comment]
![2021-01-06_16-39-45-359_brave](https://user-images.githubusercontent.com/7092693/103774565-d7e0e780-503d-11eb-987f-453f681e8604.png)
After a bit of time I detected 'Offline' status of the node and restarted it. I've attached logs [here](https://www.mediafire.com/file/dspivlc27i8c4e3/2021-01-06_13-08-43.tar.gz/file).

**Comment by bkase** [comment]
Are you running with snark working enabled on the same machine as you are doing block production? Could you try running with snarking disabled and see if that improves your memory usage or if you still see these spikes?

**Comment by ru-errorist** [comment]
@bkase Yes I'm running SW+BP on the same machine together.

Here is a data before SW disabling:
```
Global number of accounts:                     2698
Block height:                                  598
Max observed block length:                     598
Local uptime:                                  4h37m52s
Ledger Merkle root:                            jxM6vtaJZLtVGYdiSku27gVAKxf8ZrS8qDYde7VQz82mEZwunvg
Protocol state hash:                           3NKrfvDZE1hjXPnoJseJxQrKbSBzT7g9qJx8AiBDZVSqZYDN3F7c
Chain id:                                      2dbac725ebb5c6c8b1daf21cda9e3694951ab72afe9be99ff7ca47574112f43b
Git SHA-1:                                     [DIRTY]b7eff8e5c966b12bdc298160297c716eae7a35af
Configuration directory:                       /root/.coda-config
Peers:                                         47 (5.188.158.80:8302 135.181.5.22:8302 161.35.53.50:8302 110.234.31.118:38799 135.181.134.222:8302 168.119.1.188:8302 34.66.157.200:10001 35.223.31.24:8302 42.60.69.66:45821 34.122.129.116:47692 34.242.206.79:8302 95.217.73.216:8302 135.181.130.109:8302 116.203.138.189:8302 172.105.76.103:8302 135.181.78.173:8302 95.217.228.160:8302 173.212.251.32:8302 168.119.11.202:8302 116.202.169.136:8302 35.239.73.155:8302 207.180.212.167:8302 45.115.107.124:8302 204.12.195.74:8302 135.181.137.68:8302 135.181.192.221:55004 35.192.7.49:10515 95.217.76.181:8302 144.76.98.162:8302 75.43.129.209:8302 5.189.164.204:8302 34.121.44.30:8302 34.70.183.242:10501 134.122.2.150:8302 34.70.109.231:8302 116.203.109.220:8302 34.94.107.142:8302 135.181.38.31:8302 35.196.160.28:8302 34.83.65.169:60126 94.198.51.37:8302 35.202.134.142:8302 116.202.85.179:8302 144.76.116.15:8302 135.181.134.47:8302 168.119.0.204:8302 194.19.235.76:8302)
User_commands sent:                            0
SNARK worker:                                  B62qmo7wZEAZPZoao5AKRVJox9B9fgpvYAsPvYevSH7tWdTS7ny93Uu
SNARK work fee:                                500000000
Sync status:                                   Synced
Block producers running:                       1 (B62qmo7wZEAZPZoao5AKRVJox9B9fgpvYAsPvYevSH7tWdTS7ny93Uu)
Best tip consensus time:                       epoch=0, slot=3319
Best tip global slot (across all hard-forks):  3319
Next block will be produced in:                in 5.529d
Consensus time now:                            epoch=0, slot=3328
Consensus mechanism:                           proof_of_stake
Consensus configuration:
        Delta:                     0
        k:                         290
        Slots per epoch:           7140
        Slot duration:             3m
        Epoch duration:            14d21h
        Chain start timestamp:     2020-12-30 19:14:30.000000Z
        Acceptable network delay:  3m
```
![2021-01-06_20-41-35-680_brave](https://user-images.githubusercontent.com/7092693/103802087-b09b1200-505f-11eb-8d2b-1f2094f66963.png)
![2021-01-06_20-42-06-687_brave](https://user-images.githubusercontent.com/7092693/103802100-b42e9900-505f-11eb-9c3a-a4899b984ec4.png)

And now SW is disabled:
```
root@Ubuntu-1804-bionic-64-minimal ~ # coda client set-snark-worker
Will stop doing snark work
Previous snark worker public key : B62qmo7wZEAZPZoao5AKRVJox9B9fgpvYAsPvYevSH7tWdTS7ny93Uu
```
```
Coda daemon status
-----------------------------------

Global number of accounts:                     2698
Block height:                                  598
Max observed block length:                     598
Local uptime:                                  4h42m23s
Ledger Merkle root:                            jxM6vtaJZLtVGYdiSku27gVAKxf8ZrS8qDYde7VQz82mEZwunvg
Protocol state hash:                           3NKrfvDZE1hjXPnoJseJxQrKbSBzT7g9qJx8AiBDZVSqZYDN3F7c
Chain id:                                      2dbac725ebb5c6c8b1daf21cda9e3694951ab72afe9be99ff7ca47574112f43b
Git SHA-1:                                     [DIRTY]b7eff8e5c966b12bdc298160297c716eae7a35af
Configuration directory:                       /root/.coda-config
Peers:                                         44 (168.119.11.202:8302 116.202.169.136:8302 35.239.73.155:8302 207.180.212.167:8302 45.115.107.124:8302 204.12.195.74:8302 135.181.137.68:8302 135.181.192.221:55004 35.192.7.49:10515 95.217.76.181:8302 144.76.98.162:8302 75.43.129.209:8302 34.70.183.242:10501 134.122.2.150:8302 5.189.164.204:8302 34.121.44.30:8302 116.203.109.220:8302 34.94.107.142:8302 135.181.38.31:8302 34.70.109.231:8302 94.198.51.37:8302 35.202.134.142:8302 116.202.85.179:8302 35.196.160.28:8302 135.181.176.103:8302 135.181.134.47:8302 168.119.0.204:8302 194.19.235.76:8302 5.188.158.80:8302 135.181.5.22:8302 161.35.53.50:8302 110.234.31.118:38799 135.181.134.222:8302 168.119.1.188:8302 35.223.31.24:8302 42.60.69.66:45821 34.242.206.79:8302 95.217.73.216:8302 34.122.129.116:47692 172.105.76.103:8302 135.181.78.173:8302 116.203.138.189:8302 95.217.228.160:8302 173.212.251.32:8302)
User_commands sent:                            0
SNARK worker:                                  None
SNARK work fee:                                500000000
Sync status:                                   Synced
Block producers running:                       1 (B62qmo7wZEAZPZoao5AKRVJox9B9fgpvYAsPvYevSH7tWdTS7ny93Uu)
Best tip consensus time:                       epoch=0, slot=3319
Best tip global slot (across all hard-forks):  3319
Next block will be produced in:                in 5.526d
Consensus time now:                            epoch=0, slot=3329
Consensus mechanism:                           proof_of_stake
Consensus configuration:
        Delta:                     0
        k:                         290
        Slots per epoch:           7140
        Slot duration:             3m
        Epoch duration:            14d21h
        Chain start timestamp:     2020-12-30 19:14:30.000000Z
        Acceptable network delay:  3m
```

**Comment by ru-errorist** [comment]
Actually SW was disabled near 9 p.m. based on a GraphQL utilization:
![2021-01-07_11-03-23-647_brave](https://user-images.githubusercontent.com/7092693/103867201-03181500-50d8-11eb-93d1-9fff1d13ca0e.png)

Number of threads dropped:
![2021-01-07_10-34-15-856_brave](https://user-images.githubusercontent.com/7092693/103866177-699c3380-50d6-11eb-815d-7e2f65974ea3.png)

So did CPU usage by a proccess:
![2021-01-07_10-34-47-715_brave](https://user-images.githubusercontent.com/7092693/103866225-7d479a00-50d6-11eb-99bd-ad3ea912a409.png)

But not for memory:
Proccess:
![2021-01-07_10-35-06-225_brave](https://user-images.githubusercontent.com/7092693/103866340-ac5e0b80-50d6-11eb-88cf-db21d42e3ff6.png)
Altogether:
![2021-01-07_10-49-36-468_brave](https://user-images.githubusercontent.com/7092693/103867047-c3e9c400-50d7-11eb-9210-f09165b7671f.png)

The logs are [here](https://www.mediafire.com/file/uh3xqm8vbrz0h7r/2021-01-07_07-36-34.tar.gz/file).

**Comment by ru-errorist** [comment]
On `Commit [DIRTY]b14e32415b15af04865ca069af31cea7716be251 on branch HEAD` the bug is still persistent:
![2021-01-11_09-29-49-458_brave](https://user-images.githubusercontent.com/7092693/104152102-b5f5b500-53ef-11eb-91e7-1eaf29192952.png)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
