### ISSUE TITLE
Tool to patch archive db from blocks log *or* missing subchains tool

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#7341]
The blocks log contains block information in JSON (or sexp) format. The missing subchains tool, once #7336 is merged, outputs block information in a compatible JSON format, with some information elided, and adding a state hash and ledger hash for blocks.

Write a tool that can patch an archive db from either source. When ingesting the blocks log, the state hash can be calculated. 

Issue: what about the ledger hash? Should the archive db make that a NULLable column? Can we take the output of the replayer to get a ledger just preceding the ingested blocks?

**Comment by psteckler** [comment]
Do we need this, or is `advanced archive-precomputed-blocks` enough? 

That command could be made to accept the output of the missing subchains tool, as well.

**Comment by psteckler** [comment]
Change the output of the missing subchains tool to be the logged blocks format, using dummy values for missing fields.

**Comment by aneesharaines** [comment]
Closing because plans have chaned
