### ISSUE TITLE
Cache some telemetry data in libp2p_helper

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#7342]
We're seeing errors when collecting telemetry data from some nodes.

If we can store/use some of the data in the libp2p_helper process, this would allow us to respond to these requests with some useful data even when the request would time out on the OCaml side (e.g. when the daemon is overwhelmed, not responding, etc.).

**Comment by psteckler** [comment]
Note that there are considerably more libp2p errors than errors on the OCaml side:
```
  "telemetry_handshake_errors": 39,
  "telemetry_heartbeat_errors": 0,
  "telemetry_transport_stopped_errors": 50,
  "telemetry_libp2p_errors": 664,
  "telemetry_other_errors": 0,
```
