### ISSUE TITLE
Handle internal command balance data in missing subchains and replayer tools

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#7344]
The code in #7336 uses dummy balance data.

Once that's there, we can also combine fee-transfer-via-coinbases with coinbases.

**Comment by aneesharaines** [comment]
Blocked on Omer's pr?

**Comment by psteckler** [comment]
The replayer already validates that ledger hash after every transaction.

It could also validate the calculated account balances.

**Comment by psteckler** [comment]
> Blocked on Omer's pr?

Yes, #7680 not yet merged.
