### ISSUE TITLE
Crashes from testworld

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#7368]
There're a total of 10 crashes reported by users on github issues for testworld:

2 dangling_parent_reference:
https://github.com/MinaProtocol/mina/issues/7350
https://github.com/MinaProtocol/mina/issues/7349
#7481

To be specific, in transaction pool when apply the diff, the ledger has already been detached.
https://github.com/MinaProtocol/mina/blob/7228f2e0078ba9cabb35b0b1cfb946414863b6c5/src/lib/network_pool/transaction_pool.ml#L1189
The `Interruptible` monad failed to catch this exception somehow.

1 segment_fault:
https://github.com/MinaProtocol/mina/issues/7333

2 crash due to peer_trust file lock:
https://github.com/MinaProtocol/mina/issues/7322
https://github.com/MinaProtocol/mina/issues/7275

It's possible that we somehow forget to close the rocksdb connection that caused this error

1 crash due to multiaddr parsing failure:
https://github.com/MinaProtocol/mina/issues/7309

```json
{"OS_type":"Unix","Release":"5.4.0-1029-gcp","Machine":"x86_64","Sys_name":"Linux","Exception":{"string":"RPC #2 failed: \"internal RPC error error: failed to parse multiaddr \\\" docker exec mina coda advanced add-peers /ip4/104.197.206.5/tcp/8302/p2p/12D3KooWCgo5Dv9D8LwSUdpEBRLUwTsyBEZn775QMKpjXq2M1RqW\\\": must begin with /\"","tags":[{"tag":"Failed to connect to libp2p_helper process"}],"backtrace":["Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30","Called from file \"src/lib/gossip_net/libp2p.ml\", line 124, characters 8-94","Called from file \"src/deferred1.ml\", line 17, characters 40-45","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47"]},"Command":"Command: (coda daemon -config-file /root/daemon.json -peer-list-file /root/peers.txt\n -insecure-rest-server -run-snark-worker\n B62qq1K7MDw8pKGRxe6VHbm8Yj3zfUGM4jTJ23tCtjn3ahbiiZz2J14 -snark-worker-fee\n 0.48 -file-log-level Info -log-level Info -work-selection seq)","Coda_branch":"HEAD","Coda_commit":"[DIRTY]b7eff8e5c966b12bdc298160297c716eae7a35af"}
```

1 crash due to cached_item has already been finalized
https://github.com/MinaProtocol/mina/issues/7285 This one is probably related to ledger catch because the crash happened just after the catchup failed.

1 crash due to memory leak:
https://github.com/MinaProtocol/mina/issues/7305

1 crash for unknown reason:
https://github.com/MinaProtocol/mina/issues/7306
I failed to find where code would exit 137 in the codebase.

**Comment by ghost-not-in-the-shell** [comment]
I scanned through all the crash logs in gcloud from 2021-01-07 17:00 - 2021-01-08 8:00. There's a total of 85 crashes.

there are
1 "write to closed pipe" error
7 "connection attempt timeout" on archive node
11 dangling_parent_reference
20 Hashtbl.add_exn got key already present
26 super_catchup failure with the error message "someone was bad:)"
30 WNOHANG

details can be find here:
https://docs.google.com/spreadsheets/d/1bgSQWL-_0u5O5GpeRSJ-9eEMjB5kebT3z99Ub7sFxPQ/edit?usp=sharing

**Comment by aneesharaines** [comment]
Crashes for 
11 dangling_parent_reference
20 Hashtbl.add_exn got key already present
26 super_catchup failure with the error message "someone was bad:)"

Should be fixed in the next hotfix

**Comment by aneesharaines** [comment]
Focus on ivar crash

**Comment by aneesharaines** [comment]
Added logs for ivar

**Comment by ghost-not-in-the-shell** [comment]
PRs for Ivar.fill:
https://github.com/MinaProtocol/mina/pull/7483
https://github.com/MinaProtocol/mina/pull/7476
Issue for analysis of use case of Ivar.fill:
https://github.com/MinaProtocol/mina/issues/7463
