### ISSUE TITLE
if local hostname not in /etc/hosts, daemon doesn't start

### ISSUE THREAD

**Issue by jkrauska** [MinaProtocol/mina#737]
repro

change your hostname

sudo hostnamectl set-hostname mynewhostname

start daemon

just stalls.

fix/hack:
add host name to /etc/hosts

**Comment by cmr** [comment]
@jkrauska did we figure this out the other day?

**Comment by cmr** [comment]
We hit this on macOS on @wu-s-john's and @bkase's machine. Resolving gethostname sometimes fails.

**Comment by cmr** [comment]
We keep hitting this. not sure any testnet participants have reported it though.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
