### ISSUE TITLE
Coda can't start after hard reboot: Unhandled top-level exception: $exn 

### ISSUE THREAD

**Issue by cipixul** [MinaProtocol/mina#7377]
I had a power failure and my node restarted along with the vm. After that, the daemon shows me this error:
Jan 08 15:07:04 mina-validator coda[941]: 2021-01-08 15:07:04 UTC [Fatal] Unhandled top-level exception: $exn
Jan 08 15:07:04 mina-validator coda[941]: Generating crash report
Jan 08 15:07:04 mina-validator coda[941]:         exn: {
Jan 08 15:07:04 mina-validator coda[941]:   "sexp": [
Jan 08 15:07:04 mina-validator coda[941]:     [
Jan 08 15:07:04 mina-validator coda[941]:       "rpc_error",
Jan 08 15:07:04 mina-validator coda[941]:       [ "Connection_closed", [ "No heartbeats received for 15m." ] ]
Jan 08 15:07:04 mina-validator coda[941]:     ],
Jan 08 15:07:04 mina-validator coda[941]:     [
Jan 08 15:07:04 mina-validator coda[941]:       "connection_description",
Jan 08 15:07:04 mina-validator coda[941]:       [ "Client connected via TCP", [ "localhost", "38383" ] ]
Jan 08 15:07:04 mina-validator coda[941]:     ],
Jan 08 15:07:04 mina-validator coda[941]:     [ "rpc_tag", "worker_init_rpc_1" ],
Jan 08 15:07:04 mina-validator coda[941]:     [ "rpc_version", "0" ]
Jan 08 15:07:04 mina-validator coda[941]:   ],
Jan 08 15:07:04 mina-validator coda[941]:   "backtrace": [
Jan 08 15:07:04 mina-validator coda[941]:     "Raised at file \"src/result.ml\", line 158, characters 17-26",
Jan 08 15:07:04 mina-validator coda[941]:     "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
Jan 08 15:07:04 mina-validator coda[941]:     "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
Jan 08 15:07:04 mina-validator coda[941]:     "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
Jan 08 15:07:04 mina-validator coda[941]:   ]
Jan 08 15:07:04 mina-validator coda[941]: }

I am attaching the crash report, hope it helps.

[coda_crash_report_2021-01-08_15-07-04.184860.tar.gz](https://github.com/MinaProtocol/mina/files/5787938/coda_crash_report_2021-01-08_15-07-04.184860.tar.gz)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
