### ISSUE TITLE
Telemetry is failing with message too big

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#7400]
Error:
```
"{'error': {'sexp': [['rpc_error', ['Write_error', ['Message_too_big', [['size', '147437769'], ['max_message_size', '104857600']]]]], ['connection_description', '<created-directly>'], ['rpc_tag', 'Get_telemetry_data'], ['rpc_version', '0']]}}"
```

**Comment by psteckler** [comment]
It's the large number of peers that contributes to the message size.

We could either 1) limit the number of peers in the telemetry response, or 2) increase the message size limit in Async.

**Comment by es92** [comment]
I'd be for (2), we still use the peers to crawl the network effectively (and it'll be even more important once we have max peer counts working effectively)

**Comment by psteckler** [comment]
Looks like the max message size can be set via `Async_extra.Rpc.Connection.create`.

That would replace the call at: https://github.com/MinaProtocol/mina/blob/develop/src/lib/gossip_net/libp2p.ml#L268

**Comment by psteckler** [comment]
If we cap the number of peers, we shouldn't need to change anything.

**Comment by aneesharaines** [comment]
We should make sure that we don't break telemtery with large number of peers / alt that telemetry is very robust
