### ISSUE TITLE
GraphQL query for a specific block (within transition frontier)

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#7404]
We currently have a bestChain query that returns blocks on the best chain within the transition frontier but we don’t have a way to query for individual blocks via hash or height from this interface.

This is very very simple to add from an implementation perspective and is useful.

**Comment by bkase** [comment]
implementation cost is 5min + overhead of landing a PR

Near zero risk of introducing any regressions

**Comment by crackerli** [comment]
**Please don't forget to add the following input:**
before: (block number)
after: (block number)
relatedTo: (publicKey)
first: first n elements
last: last n elements

**and following output**
pageInfo {
    firstCursor
    hasNextPage,
    hasPreviousPage,
    lastCursor
}

totalCount

these fields would help front-end work easily.

**Comment by bkase** [comment]
@crackerli this endpoint is always limited to returning a list of at most size 290 (pending small  changes to consensus constants). As such I think the paging system isn’t necessary. Before/after doesn’t add anything on top of height.

relatedTo, first n, last n in bestChain. Should be easy enough to add though

**Comment by crackerli** [comment]
> @crackerli this endpoint is always limited to returning a list of at most size 290 (pending small changes to consensus constants). As such I think the paging system isn’t necessary. Before/after doesn’t add anything on top of height.
> 
> relatedTo, first n, last n in bestChain. Should be easy enough to add though

So, if the user has 291 transactions, he may can not see the earliest transaction?

**Comment by garethtdavies** [comment]
> So, if the user has 291 transactions, he may can not see the earliest transaction?

@crackerli it's 290 blocks. If the user's transactions happened outside of those 290 blocks you would have to get from somewhere else e.g. archive node.

**Comment by crackerli** [comment]
> > So, if the user has 291 transactions, he may can not see the earliest transaction?
> 
> @crackerli it's 290 blocks. If the user's transactions happened outside of those 290 blocks you would have to get from somewhere else e.g. archive node.

Thank you much, I understood

**Comment by robinbb** [comment]
@psteckler I perceive that this issue should be closed. Is that right?

**Comment by psteckler** [comment]
Yes, closing.
