### ISSUE TITLE
Catchup status

### ISSUE THREAD

**Issue by CyberAlex14** [MinaProtocol/mina#7415]
Block actual. Usually when synced, Finished > 0, other = 0. There were some problems with the production of snarks, then we went.
![image](https://user-images.githubusercontent.com/70861928/104188790-da22b780-542a-11eb-9eb1-394951574cb8.png)
![image](https://user-images.githubusercontent.com/70861928/104188821-e27af280-542a-11eb-9bbd-c55cb94ac338.png)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
