### ISSUE TITLE
Less CPU base clock requirement but more cores.

### ISSUE THREAD

**Issue by WayneWayner** [MinaProtocol/mina#7419]
As it turns out, it is currently recommended to use CPUs that have a base clock of at least 3.2 GHz. 
However, most server products do not have such a high base clock. An AMD EPYC™ 7502P 32 core CPU only has a base clock of 2.5 GHz. However, we should agree that it should be able to handle all the operations of the Mina Node with ease. 
I see an urgent need for optimization here.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
