### ISSUE TITLE
Zero balance

### ISSUE THREAD

**Issue by WayneWayner** [MinaProtocol/mina#7420]
Suddenly my balance went to zero. 

```
coda accounts list
Account #1:
  Public key: B62qkCf7QM2bQsuP8CE1Cuyq6TyqnPj5K8Fx5UgJuEcvHEJWoSCwp2Z
  Balance: 0
  Locked: false
```
[codalogs.zip](https://github.com/MinaProtocol/mina/files/5797380/codalogs.zip)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
