### ISSUE TITLE
snark worker reports many snarks generated in 0ns

### ISSUE THREAD

**Issue by jrwashburn** [MinaProtocol/mina#7437]
I'm not really sure what this is doing, and don't have great information. I'm just capturing stdout because there are no logs generated when running from command coda internal snark-worker. I see lots of messages for snark generated in 0ns - which I assume means something is not right. It occurs 40-50% of the time.

```
jw@mina-5:~# grep 'SNARK generated in' logs/*.log | awk '{print $12}' | wc -l
19645
jw@mina-5:~# grep 'SNARK generated in' logs/*.log | awk '{print $12}' | grep '0ns' | wc -l
10172

jw@mina-3:~#  grep 'SNARK generated in' logs/*.log | awk '{print $12}' | wc -l
24241
jw@mina-3:~# grep 'SNARK generated in' logs/*.log | awk '{print $12}' | grep '0ns' | wc -l
9838

logs/snarkworker1.log:{"timestamp":"2021-01-10 09:58:25.015359Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 129, characters 12-27"},"message":"Merge SNARK generated in $time","metadata":{"pid":21113,"process":"Snark Worker","time":"0ns"},"event_id":"bcc5cf56ab582a129736e0906dea7cfa"}
```

![](https://cdn.discordapp.com/attachments/754653322845356103/797774253243367494/Screen_Shot_2021-01-10_at_5.28.56_AM.png)

**Comment by mrworksome** [comment]
I think that something related to zero blocks, but i don't sure.
Snark worker create work for time 0ns and i think thats error.
 
<img width="705" alt="ccc" src="https://user-images.githubusercontent.com/46965627/104354814-d79f8b00-551a-11eb-9893-d57b65330c8c.png">

**Comment by psteckler** [comment]
While I don't know this part of the codebase so well, there are cases when the 0-time seems legitimate:

https://github.com/MinaProtocol/mina/blob/develop/src/lib/snark_worker/prod.ml#L87

**Comment by deepthiskumar** [comment]
These are for the work that is already done. Snark workers cache snarks and when the same work appears they simply fetch it from the cache.

**Comment by jrwashburn** [comment]
I don't think this should explain the situation - or if it does, I would consider this a problem for the snark coordinator. I don't think this issue should be closed.

My setup is: 4 nodes just running snark worker via "coda internal snark-worker -daemon-address [remote coordinator] -proof-level full -shutdown on disconnect false". These nodes do not run the daemon. If the work is cached locally, how did it get there on that machine? Does this mean the snark coordinator is re-distributing redundant work that the worker has already computed? Or is the snark worker actually running a daemon and keeping up with what other workers have done beyond itself? (I'm pretty certain that is not the case. The only network connection from my snark worker nodes is to the coordinator on port 8301. So unless in addition to the get snark work command, they are gossiping all the snark work to each other over that same port...? That would seem very strange to me.)

**Comment by icohigh** [comment]
I've tested very different options. And if you look at my snark history, a couple of days ago I had 15-20+ in the block. Now from 1 to 15. Avg about 5, I would say. With 0.5 fee.
The usual way of launching a Snark will not achieve this.
I have a very powerful spec from many dedicated servers. But nevertheless, many people overtake me very much.
The only thing I noticed is that you need to have a server that quickly processes information.

I have 10+ dedicated + epic. And I know that some people are selling more snarks than me with much fewer servers and this is very strange.

2 coordinators (0.5 fee) on the same 2 dedicated servers  i9-9900K Octa-Core. And each of them has 18 internal workers connected, also on dedicated servers.
I think my decrease in snark jobs is due to increased competition. When I started and had 30+ jobs in the block, there were 3 times fewer competitors for 0.5 fee.
Below in the file I highlighted the main "snarkjobers" with fee 0.5 
[https://gist.github.com/icohigh/85e3f8840a7e57023bc53dc5cec6951c](https://gist.github.com/icohigh/85e3f8840a7e57023bc53dc5cec6951c)

```
{"timestamp":"2021-01-12 21:28:14.210507Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 201, characters 10-21"},"message":"SNARK work $work_ids received from $address. Starting proof generation","metadata":{"address":"135.181.177.187:8301","pid":32528,"process":"Snark Worker","work_ids":[381368327,536385958]}}
{"timestamp":"2021-01-12 21:28:14.711679Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 134, characters 12-27"},"message":"Base SNARK generated in $time","metadata":{"pid":32528,"process":"Snark Worker","time":"0ns"},"event_id":"885328f9dca84fa1cfb99089080613d6"}
{"timestamp":"2021-01-12 21:28:14.711732Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 134, characters 12-27"},"message":"Base SNARK generated in $time","metadata":{"pid":32528,"process":"Snark Worker","time":"0ns"},"event_id":"885328f9dca84fa1cfb99089080613d6"}
{"timestamp":"2021-01-12 21:28:14.712098Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 217, characters 14-25"},"message":"Submitted completed SNARK work $work_ids to $address","metadata":{"address":"135.181.177.187:8301","pid":32528,"process":"Snark Worker","work_ids":[381368327,536385958]}}
```

[coordinator-logs-1.tar.gz](https://github.com/MinaProtocol/mina/files/5804891/coordinator-logs-1.tar.gz)
[coordinator-logs-2.tar.gz](https://github.com/MinaProtocol/mina/files/5804892/coordinator-logs-2.tar.gz)
[cpu-info.txt](https://github.com/MinaProtocol/mina/files/5804894/cpu-info.txt)

**Comment by jrwashburn** [comment]
Logs requested attached here: 
https://drive.google.com/drive/folders/1u3vz2xRVx7IgE58VhbFchVwYNjbptNgg?usp=sharing

**Comment by jrwashburn** [comment]
https://drive.google.com/file/d/1uKntmyafgPKu5sXHU5RYODEYykBMghcU/view?usp=sharing

New logs from the coordinator node with -file-log-level Trace

**Comment by mrworksome** [comment]
logs from my daemon with -file-log-level Trace
[logs_snark_trace.txt](https://github.com/MinaProtocol/mina/files/5812489/logs_snark_trace.txt)

**Comment by deepthiskumar** [comment]
There is an issue with the criteria for adding snarks to the pool. This here https://github.com/MinaProtocol/mina/blob/fa26a0e18c7eadb1eb4300b911122de1a520eb13/src/lib/network_pool/snark_pool_diff.ml#L108
adds snarks only if the fee difference between the existing snark and the new snark is >= 0.5. Local snarks that are not significantly low are not added to the pool. However the work selection doesn't take this into account and distributes the same work again thinking it can undercut the one in snark pool.

**Comment by deepthiskumar** [comment]
There is a valid reason why work could be reassigned in general- If snark generation takes long then the daemon reassigns it again. There is a daemon flag that can be used to specify the wait time `work-reassignment-wait` (default is 7 mins).

**Comment by jrwashburn** [comment]
This also explains the mystery of why 0.50 fees perform so much better than 0.49 or 0.3, etc. For all the 0.5 snarks, they cannot really be replaced unless you go to 0.

**Comment by mrmr1993** [comment]
@jrwashburn have you seen this in more recent versions?

**Comment by jrwashburn** [comment]
Yes, this continues to occur - not nearly as often, but several times each day. for 2021-02-03, I see entries like this on 14 occurrences across 3 snark workers on one VM. 

{"timestamp":"2021-02-03 20:45:27.313823Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 129, characters 12-27"},"message":"Merge SNARK generated in $time","metadata":{"pid":22034,"process":"Snark Worker","time":"0ns"},"event_id":"bcc5cf56ab582a129736e0906dea7cfa"}

I am running logs in info on the coordinator daemon, so not seeing anything there; however, last time I looked on 1/15 (https://discord.com/channels/484437221055922177/754653322845356103/799623274795237386) there was an error on the coordinator side:
Error verifying transaction snark from $sender: $error","metadata":{"error":{"string":"Invalid proof"}

**Comment by jrwashburn** [comment]
Still seeing these on Zenith.

{"timestamp":"2021-02-18 13:02:32.466726Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 134, characters 12-27"},"message":"Base SNARK generated in $time","metadata":{"pid":42034,"process":"Snark Worker","time":"0ns"},"event_id":"885328f9dca84fa1cfb99089080613d6"}

{"timestamp":"2021-02-18 13:02:32.466799Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 134, characters 12-27"},"message":"Base SNARK generated in $time","metadata":{"pid":42034,"process":"Snark Worker","time":"0ns"},"event_id":"885328f9dca84fa1cfb99089080613d6"}

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
