### ISSUE TITLE
Block produced with 0 trx and 0 snarks

### ISSUE THREAD

**Issue by rashidovich** [MinaProtocol/mina#7438]
Two running BPs with same public key  produced 2 blocks for same slot. One block is red with included trx/snarks the other one is **green but with 0 trx/snarks inside**.

both have Error: 'Duplicate producer and slot.' Where they referencing each other.

There're also examples with one block per slot with same 0 trx/snarks included.

[coda2.log](https://github.com/MinaProtocol/mina/files/5803946/coda2.log)
[coda1.log](https://github.com/MinaProtocol/mina/files/5803948/coda1.log)

Red block hash: 3NLAnzCyWAfovbwfL1aQC54hyCkdSprUYnuUgCkLUFYPufHG4UCe (coda1.log)
Green block hash: 3NKWnXLwUc7Xg7MypiB4dDZtHxPZ5ncpBBW9rRXmUmGKGKKeqnw3 (coda2.log)

Testnet: _Testworld_
Git sha-1: [DIRTY]_b14e32415b15af04865ca069af31cea7716be251_ 
User pub-key: B62qkaTjpwYmE3tX2KumDxTcBMbAQSyzKGqJArX3HWFjY6dsqryLeVj

**Comment by ghost-not-in-the-shell** [comment]
Thanks for report that.

The error of "duplicate producer and slot" is just saying one should not run two block producers with the same key.

But I think this has nothing to do with blocks with no snarks and txns. We would look into those.

**Comment by dewrin** [comment]
same

**Comment by dewrin** [comment]
```![Screenshot_2021-01-13-16-42-43-311_com.sonelli.juicessh.jpg](https://user-images.githubusercontent.com/4558899/104435620-2b63b000-55bf-11eb-9fea-052bf0d87768.jpg)

**Comment by dewrin** [comment]
![Uploading Screenshot_2021-01-13-17-00-32-815_com.sonelli.juicessh.jpg…]()

**Comment by dewrin** [comment]
![Screenshot_2021-01-13-17-00-32-815_com sonelli juicessh](https://user-images.githubusercontent.com/4558899/104437236-1c7dfd00-55c1-11eb-933b-e5036d44622a.jpg)

**Comment by dewrin** [comment]
2021-01-13 10:32:25 UTC [Error] Duplicate producer and slot: producer = $block_producer, consensus_time = $consensus_time, previous protocol state hash = $hash, current protocol state hash = $current_protocol_state_hash
        block_producer: "B62qpt6cDbhR93x9mTp4eMzSKqDuc2zUmyX5qzMuoMNp9FogjfhPEdE"
        consensus_time: { "slot_number": "6545", "slots_per_epoch": "7140" }
        hash: "3NKVtxTN3G4VGpc3cCy87tLQSMQyDoyFwLu92tgPHtRe9k27ZNCz"
        current_protocol_state_hash: "3NLMya8rXtt2QPP93uqrPkkk4LbNvthhQpS1WwNmX31L8Aw4HcqK"
2021-01-13 10:32:34 UTC [Warn] Not rebroadcasting block $state_hash because it was received "1 slots too late"        state_hash: "3NLMya8rXtt2QPP93uqrPkkk4LbNvthhQpS1WwNmX31L8Aw4HcqK"

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
