### ISSUE TITLE
Block height > Max observed block length

### ISSUE THREAD

**Issue by 1winning1** [MinaProtocol/mina#7439]
My block height is higher then the max observedf block length.
After that the sync status changed to connecting and everything freezed.

coda client status:
-----------------------------------

Global number of accounts:                     2867
Block height:                                  1019
Max observed block length:                     1017
Local uptime:                                  2d10h35m2s
Ledger Merkle root:                            jx1jMj4AqyrgzEcDMCFgJU6eVx5vHTPU3RahnjM5iwk5FZ3HGMi
Protocol state hash:                           3NLxFQFu2M7PjzNVnca4jFnCavfJ5XtkzpCZfYZR9Fn9abfPBVCq
Chain id:                                      2dbac725ebb5c6c8b1daf21cda9e3694951ab72afe9be99ff7ca47574112f43b
Git SHA-1:                                     [DIRTY]b7eff8e5c966b12bdc298160297c716eae7a35af
Configuration directory:                       /home/winning/.coda-config
Peers:                                         42 (35.223.254.82:10517 62.171.133.104:8302 35.228.208.204:8302 116.203.50.65:8302 159.69.194.60:8302 95.216.189.251:8302 116.202.171.151:8302 34.72.209.171:48380 95.217.196.244:8302 213.133.97.240:8302 34.66.157.200:10001 135.181.136.109:8302 49.12.121.132:8302 135.181.73.100:8302 135.181.140.225:56534 34.66.152.94:8302 35.202.78.107:8302 159.69.70.209:8302 76.220.59.4:8302 159.69.56.79:8302 34.67.152.180:10518 35.222.246.91:41006 3.6.175.231:8302 45.63.62.120:48338 119.39.3.52:29188 136.243.1.37:47100 35.199.152.248:8302 34.70.222.216:10512 35.188.115.199:10511 113.110.167.214:11003 135.181.19.233:8302 95.217.182.248:8302 35.228.231.213:59224 207.148.82.100:8302 139.64.165.224:8302 172.104.219.221:8302 76.186.212.44:8302 35.188.1.222:10909 95.216.43.169:8302 34.123.174.31:10001 62.171.154.207:47624 34.123.97.140:8302)
User_commands sent:                            0
SNARK worker:                                  B62qkNSyk5nXoy45pCckV9hcFm528b8BomA6iqX55tZLhEbuQf3QfRw
SNARK work fee:                                498000000
Sync status:                                   Connecting
Block producers running:                       1 (B62qkNSyk5nXoy45pCckV9hcFm528b8BomA6iqX55tZLhEbuQf3QfRw)
Best tip consensus time:                       epoch=0, slot=6086
Best tip global slot (across all hard-forks):  6086
Next block will be produced in:                None this epoch… checking at in 1.85d
Consensus time now:                            epoch=0, slot=6251
Consensus mechanism:                           proof_of_stake
Consensus configuration:
        Delta:                     0
        k:                         290
        Slots per epoch:           7140
        Slot duration:             3m
        Epoch duration:            14d21h
        Chain start timestamp:     2020-12-30 19:14:30.000000Z
        Acceptable network delay:  3m

Addresses and ports:
        External IP:    135.181.132.188
        Bind IP:        0.0.0.0
        Libp2p PeerID:  12D3KooWK7aVtdeKzdYrFbkvSgAJABnMRFpPWdynmZDL3sFJ22DN
        Libp2p port:    8302
        Client port:    8301

**Comment by WayneWayner** [comment]
I have encountered this problem sometimes as well. Good catch.

**Comment by deepthiskumar** [comment]
This should be resolved after this https://github.com/MinaProtocol/mina/pull/7500 (also in the testnet release)
