### ISSUE TITLE
Inappropriate wording coda client status

### ISSUE THREAD

**Issue by WayneWayner** [MinaProtocol/mina#7440]
For my understanding in the coda client status the wording should be adjusted for **Block height** and **Max observed block length**. 
I understood that **Block height** shows the current block height of my node and **Max observed block length** shows the block height of the network. 

My suggestion would be to change **Max observed block length** to **Max observed block height**.

```
coda client status
{"timestamp":"2021-01-12 19:58:30.967644Z","level":"Debug","source":{"module":"Block_time","location":"File \"src/lib/block_time/block_time.ml\", line 76, characters 18-30"},"message":"Environment variable CODA_TIME_OFFSET not found, using default of 0","metadata":{"pid":13703}}
Coda daemon status
-----------------------------------

Global number of accounts:                     2876
Block height:                                  1133
Max observed block length:                     1423
Local uptime:                                  25m46s


```

**Comment by psteckler** [comment]
Changed in PR #7441.

**Comment by mrmr1993** [comment]
This is fixed. Closing.
