### ISSUE TITLE
re-enable the google data studio to collect all crashes on our testnet

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#7443]
We used to has google data studio page that collects the crash report for qa-net. I think this helps to determine severity of crashes and let us have a general view of different crashes over our nodes.
https://datastudio.google.com/u/0/reporting/1y_0-BzISi8OQEVa36_E4fqCG7VeNuaQw/page/Qe4EB

**Comment by aneesharaines** [comment]
First step is to collect the crashes to help with the current investigation.
