### ISSUE TITLE
GraphQL: Add timed balance

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#7450]
Currently, it is not possible to get timing information via GraphQL - it needs to be derived from a ledger. It would be useful to get the current timed balance as well as returning the timed data (i.e. initial minimum balance etc...)

I would imagine this would be important also for determining super-charged coinbase eligible delegates.

**Comment by aneesharaines** [comment]
Needs to be spec'd out.  @psteckler could you spec out the data that needs to be exposed

**Comment by psteckler** [comment]
I suggest that the existing `account` query return the timing associated with the account. The existing fields are given at line c.700 of `Mina_graphql`. It's an oversight that it's not already included.

In addition, I'd suggest adding a field like `availableBalance`, that can be computed using the account timing and the current global slot. The function `Account.min_balance_at_slot` gives a min balance, so the available balance is the current balance, less that min balance. If the current balance is less than the min balance, the available balance is 0.
