### ISSUE TITLE
Issues with restarting node after update to [DIRTY]16ebdd6597ab050fdaf8a075cc39d9b7be1233cf

### ISSUE THREAD

**Issue by StakingShop** [MinaProtocol/mina#7452]
[2021-01-13_07-43-53.tar.gz](https://github.com/MinaProtocol/mina/files/5807127/2021-01-13_07-43-53.tar.gz)

**Comment by ghost-not-in-the-shell** [comment]
This is another instance of `Ivar.fill` crash.

**Comment by ghost-not-in-the-shell** [comment]
It seems like the user is using normal catchup.

**Comment by mrmr1993** [comment]
This is a dup of #7463, which is now fixed.
