### ISSUE TITLE
Crash : Failed to query our own IP from

### ISSUE THREAD

**Issue by EmreNOP** [MinaProtocol/mina#7454]
report attached
[coda_crash_report_2021-01-13_14-48-05.279476.tar.gz](https://github.com/MinaProtocol/mina/files/5809302/coda_crash_report_2021-01-13_14-48-05.279476.tar.gz)

**Comment by Kakashi010** [comment]
Same for me..

[coda_crash_report_2021-01-12_06-17-23.846208.tar.gz](https://github.com/MinaProtocol/mina/files/5810241/coda_crash_report_2021-01-12_06-17-23.846208.tar.gz)

**Comment by EmreNOP** [comment]
btw, if node cannot query dns server somehow, crashing

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
