### ISSUE TITLE
New/fresh instance of mina-archive fails to archive

### ISSUE THREAD

**Issue by mnguyen-io** [MinaProtocol/mina#7455]
Hi there, I'm trying to get an Archive node up and running, but am running into some problems. When I run the coda-archive daemon it appears that coda is able to communicate find with coda-archive, but it's failing to actually archive anything and a lot of these errors are produced:

2021-01-13 15:17:09 UTC [Warn] Failed to archive block: $block, see $error
        block: "3NKYZb5kmeZDh7ANschgRivSHHLit5FDgcRnsGV3JNrxjWZ9pxZy"
        error: "Unexpected result from <postgres://psql_mina:_@172.17.0.1:5432/archive>: Received 0 tuples, expected one. Query: \"SELECT id FROM snarked_ledger_hashes WHERE value = $1\"."
2021-01-13 15:17:10 UTC [Warn] Failed to archive block: $block, see $error
        block: "3NK7kGFbMe6xUHvnNqZv7C7Fv6f4S6XS9tH9GpUn5PfMeNnTjt6E"
        error: "Unexpected result from <postgres://psql_mina:_@172.17.0.1:5432/archive>: Received 0 tuples, expected one. Query: \"SELECT id FROM snarked_ledger_hashes WHERE value = $1\"."
2021-01-13 15:17:43 UTC [Warn] Failed to archive block: $block, see $error
        block: "3NLRy7M1U54WriMRvCap5x5pEvgAZcbJ2pxK1QaSaiWQfg7jHiDW"
        error: "Unexpected result from <postgres://psql_mina:_@172.17.0.1:5432/archive>: Received 0 tuples, expected one. Query: \"SELECT id FROM snarked_ledger_hashes WHERE value = $1\"."
2021-01-13 15:19:34 UTC [Warn] Failed to archive block: $block, see $error
        block: "3NKfQiyAFkZ8iWMUy2rUQz5LLLi4uYv2uj1swLfRkfgNkTL3YtWc"
        error: "Unexpected result from <postgres://psql_mina:_@172.17.0.1:5432/archive>: Received 0 tuples, expected one. Query: \"SELECT id FROM snarked_ledger_hashes WHERE value = $1\"."
2021-01-13 15:19:53 UTC [Warn] Failed to archive block: $block, see $error
        block: "3NKDRx6QLVxFkfmzhwiDACbtB1jUZ4tyNsLSi3Kac7ny3Pf9iA8L"
        error: "Unexpected result from <postgres://psql_mina:_@172.17.0.1:5432/archive>: Received 0 tuples, expected one. Query: \"SELECT id FROM snarked_ledger_hashes WHERE value = $1\"."
2021-01-13 15:19:57 UTC [Warn] Failed to archive block: $block, see $error
        block: "3NKpxYBUDHUybHYdJ1hG4uH7TtMNGiEhHdhyDYjuMiPE9JpU56P7"
        error: "Unexpected result from <postgres://psql_mina:_@172.17.0.1:5432/archive>: Received 0 tuples, expected one. Query: \"SELECT id FROM snarked_ledger_hashes WHERE value = $1\"."

I assume the issue is that it's unable to pull up any past snarked_ledger_hashes (which is right since it has no data at the moment), so I attempted to add a list of snarked_ledger_hashes values that I gathered from https://minaexplorer.com/.

For some odd reason, it then gave me errors of a duplicate key for snarked_ledger_hashes which I believe would only be caused if it were trying to do an insert, but as pasted above - on a new database there were no snarked_ledger_hashes being inserted.

coda-archive version:
coda-archive:0.2.4-develop

schema:
https://raw.githubusercontent.com/MinaProtocol/mina/master/src/app/archive/create_schema.sql

coda/mina version:

Coda daemon status
-----------------------------------

Global number of accounts:                     3277
Block height:                                  1579
Max observed block length:                     1579
Local uptime:                                  2h6m35s
Ledger Merkle root:                            jx7Wwcigy3n5RfHoMoAmEtncTARPbAW7Q7PADZpVz33eGgF8V6U
Protocol state hash:                           3NKC2M26iVUvwhic7vobQngwrsJEktJMTK6gHBkbMh7CpmAD3eaT
Chain id:                                      2dbac725ebb5c6c8b1daf21cda9e3694951ab72afe9be99ff7ca47574112f43b
Git SHA-1:                                     [DIRTY]b14e32415b15af04865ca069af31cea7716be251
..
User_commands sent:                            0
SNARK worker:                                  None
SNARK work fee:                                25000000
Sync status:                                   Synced
Catchup status:                                
        To build breadcrumb:           0
        To initial validate:           0
        Finished:                      311
        To verify:                     0
        To download:                   0
        Waiting for parent to finish:  0

Block producers running:                       0
Best tip consensus time:                       epoch=0, slot=6649
Best tip global slot (across all hard-forks):  6649
Next block will be produced in:                None this epoch… checking at in 1.009d
Consensus time now:                            epoch=0, slot=6655
Consensus mechanism:                           proof_of_stake

**Comment by mrmr1993** [comment]
I've opened #7456 to fix this

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
