### ISSUE TITLE
Node stalls in 'Synced' state

### ISSUE THREAD

**Issue by ru-errorist** [MinaProtocol/mina#7460]
Hello team.

I had some issues with a release version of the node. While being in a 'Synced' state it stalls and freezes on a specific block.
![2021-01-13_165943](https://user-images.githubusercontent.com/7092693/104488925-177c7600-55e0-11eb-972c-376005c25baa.png)

I have a monitoring system that indicates it to me:
![2021-01-13_125723](https://user-images.githubusercontent.com/7092693/104489480-be611200-55e0-11eb-95b2-c7598001e690.png)

At the same time memory consumption keeps growing:
![2021-01-13_125739](https://user-images.githubusercontent.com/7092693/104489703-fcf6cc80-55e0-11eb-915a-ad7de4949808.png)
![2021-01-13_125709](https://user-images.githubusercontent.com/7092693/104489712-fff1bd00-55e0-11eb-90f3-069eafa53473.png)

Maybe it's somehow corresponded to this issue: #7335

**Comment by jrwashburn** [comment]
I have seen the same symptoms where node stays in sync, but does not progress past a given block height for a few hours.

**Comment by garethtdavies** [comment]
FWIW the explorer node was in this state last night for several hours. Always synced but block height didn't increase until a restart.

**Comment by EmrePiconbello** [comment]
Same happened at block 2604 with 32 gm ram server 
This is an empty memory chart for 24 hours. Restart happened around 8 hours ago.
![image](https://user-images.githubusercontent.com/54602437/105175891-68c6c100-5b1c-11eb-9a1d-e58b8eed4bae.png)
This is the logs I export
https://drive.google.com/file/d/1fF7BubkyO-XgJfK5g2pzZ32nT5adxOKW/view?usp=sharing

**Comment by EmrePiconbello** [comment]
Another example this time node is aware of the new block but not getting synced 
**
![image](https://user-images.githubusercontent.com/54602437/105226640-2cb15180-5b58-11eb-85a0-572a587638dd.png)
**
https://drive.google.com/file/d/1jQrOhShFGbpLRQvt1LNEgdZjxyhelU3U/view?usp=sharing

**Comment by EmrePiconbello** [comment]
Another example from latest version
![image](https://user-images.githubusercontent.com/54602437/106374952-a844a700-637f-11eb-8794-b4696b72a37a.png)
**https://drive.google.com/file/d/1OCw1sty6QzHK-LRqsouucaD1EXOGUHfi/view?usp=sharing**

**Comment by mrmr1993** [comment]
This is the same as #7555, closing in favour of that.
