### ISSUE TITLE
Audit min window density - looks possibly wrong?

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#7472]
Sample for a block:

  'consensus_state': {'blockchain_length': '800',
   'epoch_count': '0',
   'min_window_density': '1',
   'sub_window_densities': ['1',
    '1',
    '2',
    '0',
    '2',
    '2',
    '1',
    '1',
    '1',
    '2',
    '3'],

**Comment by aneesharaines** [comment]
https://github.com/MinaProtocol/mina/pull/7504
