### ISSUE TITLE
New block not in explorer

### ISSUE THREAD

**Issue by hdesanctis** [MinaProtocol/mina#7474]
Server setup: 12 cores, 64 Gb RAM
My node successfully produced a new block, but I cannot see the new block in the explorer.  I noticed the memory load was over 24 Gb while producing the block. The log attached
[2021-01-13_15-27-43.rar.gz](https://github.com/MinaProtocol/mina/files/5812151/2021-01-13_15-27-43.rar.gz)

**Comment by garethtdavies** [comment]
Duplicate of #7338

**Comment by BostonMike0643** [comment]
i think I had this happen............my new node through DSRV was sync'd throughout my last block production (within last hour) and no sign of it on Explorer and I remain sync'd.    what's the command to pull the info to show what occured on my node?

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
