### ISSUE TITLE
Error sending payment due to "Ledger was detatched"

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#7481]
Not experienced this myself but lots of reports in Discord of this error (a search for "Ledger was detatched" gives 17 results). 

```Error: Couldn't send user_command: (Transaction_pool.apply "Ledger was detatched") (in ["sendPayment"])```

I couldn't find an existing issue that covered this.

**Comment by garethtdavies** [comment]
The issue with finding an issue was due to the typo in the error message :) Searching for "detached" rather than "detatched" turns up a mention of it here https://github.com/MinaProtocol/mina/issues/7368.

**Comment by WilliamGuozi** [comment]
```
root@pos-test-hk-02:~# docker exec mina coda client send-payment \
>  -sender B62qpUCAhAmPTCZLo8MxZoD4Hg2AB6bYFA1pPpRPe91tPshuPyY9HA4  -receiver B62qj6TAuc1ZxMyRmoARGRhx4s9h5mcPc3RXVJshPr9JQZhb6FXgCYy -fee 200 \
>   -amount 500
❌ Error: Couldn't send user_command: already saw this (in ["sendPayment"])
```

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
