### ISSUE TITLE
Improve error message for incorrect password to encourage using `CODA_PRIVKEY_PASS`

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#7491]

**Comment by aneesharaines** [comment]
@MartinMinkov  to test

**Comment by MartinMinkov** [comment]
I am unsure what to be testing against exactly. Currently, with version `Commit [DIRTY]2dc1b9ba7793f82ef0350845f88907b62800bfad on branch HEAD`, the error message for an incorrect password is `Wrong password! Please try again` as seen below

![image](https://user-images.githubusercontent.com/9512405/105544982-68f7c580-5cb0-11eb-94e9-0547a4ec47fc.png)

This does not directly encourage using `CODA_PRIVKEY_PASS` so I am assuming this is not implemented yet. There was a recent change to include a message when `CODA_PRIVKEY_PASS` is used as detailed here (https://github.com/MinaProtocol/mina/pull/7514). This has confirmed to work as seen blow.

![image](https://user-images.githubusercontent.com/9512405/105545406-e3c0e080-5cb0-11eb-834b-0482e3dea85c.png)

**Comment by aneesharaines** [comment]
Part of a larger discussion around handling passwords (do we want to point ppl towards the evn or get rid of it)?

**Comment by aneesharaines** [comment]
what do other blockchains do?

**Comment by aneesharaines** [comment]
@aneesharaines  to see what other blockchains do
