### ISSUE TITLE
[Bug] Lost slot to create block

### ISSUE THREAD

**Issue by mrworksome** [MinaProtocol/mina#7526]
there will be a bug here 
if find a script to crash the daemon
you can get a lot of slots for the production of blocks
because when you first start the daemon there is no check for slots by public key and the network will give you a free slot as a new one BP

today I made sure that it is possible
when my daemon crashed im re-install him
and when node is synced i got the next slot a few days later for block production
but my current time to create block 3 hours remaining and i get new slot to create block

thus, you can increase the number of slots produced by one block producer. crashing coda daemon again and again

in order to avoid this, you need to create a slot only after creating a block

**Comment by EmrePiconbello** [comment]
The slots are precalculated every epoch so you can't get extra slots afaik. But looks like there are some issues with node keep track of the slots might be the reason I missed last 2 blocks while didn't miss any in that unstable time frame. I am still going through logs.

**Comment by mrworksome** [comment]
I believe that this allows you to get additional slots when producing blocks.
when synchronizing a node, a new slot is allocated and this can pose an additional threat to control the production of blocks. if slot precalculated, then why do we lose the current block production slot when daemon crashed.

accordingly, when synchronizing a node, you should check for a slot in the current era of block production, so that only after the block has been produced, we can get a new slot.

**Comment by EmrePiconbello** [comment]
There was an issue earlier causing block time calculation being wrong since after a crash data changes it's probably something similar I missed 2 blocks with recent updates they never appear anywhere that's why I am considering that possibility I still didn't check the logs maybe I can have a better understanding after changing it.

**Comment by deepthiskumar** [comment]
This could happen when the node restarts and it has not synced yet. Explained it here https://github.com/MinaProtocol/mina/issues/6956#issuecomment-739411599. If blocks are generated for some old epoch, they will be shorter than the canonical chain and therefore be rejected.

**Comment by deepthiskumar** [comment]
Regarding blocks not appearing, if they were generated after being synced then in the logs you could check for logs `Successfully produced a new block` and `Broadcasting new state over gossip net` with the state hash of the block you produced. You may see `Internally generated block $state_hash cannot be rebroadcast because it's not a valid time to do so ($timing)` if the block wasn't generated within the 3min slot in which case, i'd check the proving time `Protocol_state_proof proving time(ms)`. Also possible that you are seeing an issue described here https://github.com/MinaProtocol/mina/issues/7446

**Comment by mrworksome** [comment]
> Regarding blocks not appearing, if they were generated after being synced then in the logs you could check for logs `Successfully produced a new block` and `Broadcasting new state over gossip net` with the state hash of the block you produced. You may see `Internally generated block $state_hash cannot be rebroadcast because it's not a valid time to do so ($timing)` if the block wasn't generated within the 3min slot in which case, i'd check the proving time `Protocol_state_proof proving time(ms)`. Also possible that you are seeing an issue described here #7446

this does not explain the fact that you can win a slot in advance, while losing the current one due to incorrect synchronization
may be need update checking VRF and slots by Public Key in slots??

**Comment by garethtdavies** [comment]
I checked another one of these. Block was produced with `Broadcasting new state over gossip net` and state hash `3NL9Cuqyn6M2TKSmb8XFLBcYWnJKFX7V5R8YQd8obD5jHL8n8y2V`. It's parent block was https://minaexplorer.com/block/3NLZsht3kJmkbXv7DzCFRyt1LR7jbGx2PCBdNewZBfnAMDXtoPur (which should be noted was produced 20 mins after the block at that height on canonical chain).

Then I checked explorer logs, this state hash is only referenced as a previous state hash i.e.:

```
"message": "Received a block from $sender",
  "metadata": {
    "external_transition": {
      "protocol_state": {
        "previous_state_hash": "3NL9Cuqyn6M2TKSmb8XFLBcYWnJKFX7V5R8YQd8obD5jHL8n8y2V",
        "body": {
          "genesis_state_hash": "3NLxYrjb7zmHdoFgBrubCN8ijM8v7eT8kvLiPLc9DHt3M8XrDDEG",
          "blockchain_state": {
            "staged_ledger_hash": {
              "non_snark": {
```

This block's state hash was `3NLG3SFAdQwhBPG1EyiRoWfV94LGgSWXhYRtWcR6G1GRPdbReidV`. Then this block gave an error:

```
"message": "Validation error: external transition with state hash $state_hash was rejected for reason $reason",
  "metadata": {
    "reason": "invalid time",
    "slot_diff": "1",
    "state_hash": "3NLG3SFAdQwhBPG1EyiRoWfV94LGgSWXhYRtWcR6G1GRPdbReidV",
    "time_error": "too late"
```

So, as this block was never accepted I guess the node didn't go looking for the missing parent block either.

**Comment by mrworksome** [comment]
why after crash daemon  i win last slot in epoch
but my friend win 2 block for 2 days is not correct working winning slot for create block

**Comment by mrworksome** [comment]
in order to win a slot, the node must be synced, then why the VRF checking can start when it is in other states.

**Comment by methodnumber13** [comment]
And again, I have the same issue 
![Screenshot from 2021-01-20 14-23-06](https://user-images.githubusercontent.com/26242969/105168375-19d45800-5b2b-11eb-91a1-0ad76d03aee6.png)

**Comment by EmrePiconbello** [comment]
@mrworksome As I explained previously the slots are predefined at the start of the epoch you need to be synced to create a valid block but you don't need to be synced to create a block. Your slot is already there either you got synced or not.

**Comment by mrmr1993** [comment]
> in order to win a slot, the node must be synced, then why the VRF checking can start when it is in other states.

There are a few other issues with more detailed proposals on improving this (e.g. #7005), and I don't think there's anything else actionable here. Closing.
