### ISSUE TITLE
new release (0.2.6) snark-worker sometimes stop

### ISSUE THREAD

**Issue by scraido** [MinaProtocol/mina#7529]
Program version:                3.0.2
Operating system:               Linux
Operating system name:     Ubuntu
Operating system version:  18.04
Kernel version:                    4.15.0
Hardware platform:            x86_64
coda version:                      Commit [DIRTY]5c08d6d51111d31269e77f3c62a544b3262ee4c8 on branch HEAD
Sync status:                         Synced
SNARK worker:                    B62qr6Ef4JtL5uAfLx51usxRSGMBPtFhYjYYihbh3rWRW6ZvmURjcEH
SNARK work fee:                 500000000
processor:                           8vCPU
model name:                      Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
cpu MHz:                            2199.996
cache size:                          16384 KB

                     total            used            free            shared   buff/cache   available
Mem:           30875040    21553928    4580596     1040      4740516      10399360
Swap:           2097148      114484        1982664

du -sh:                              1.8G
Capasity:                           800GB SSD 

daemon.json:                    not configure
crontab -e:                        send tx every 15 min
Block producers running: 1 (B62qr6Ef4JtL5uAfLx51usxRSGMBPtFhYjYYihbh3rWRW6ZvmURjcEH)
Speedtest by Ookla:

    Latency:     0.40 ms   (0.24 ms jitter)
   Download:   526.41 Mbps (data used: 442.5 MB)
     Upload:   558.99 Mbps (data used: 279.4 MB)
Packet Loss:     0.0%

Connecting Doc:              https://minaprotocol.com/docs/connecting
Connected using:            systemd
-super-catchup:               enable
ufw:                                  enable
ufw allow:                        value based on Hackerone notes
ufw deny out:                  value based on Hackerone notes

issue:                               sometimes everytime i check the terminal, the snark-worker stop, and it makes me to setting it up again

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
