### ISSUE TITLE
Current State of helm + terraform in develop

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#7543]
Largely these issues relate to integration tests, but its also just the integration tests doing their job and showing that part of the integration is broken.

- [x] Nodes not connecting to the k8s seed, could be related to an issue introduced in the cluster over the weekend, could be related to CONNECT_PRIVATE_IPS env var
- [x] runtimeConfig not working the way integration tests are using it
- [x] -generate-genesis-proof=true should be possible to configure in helm independent of the runtimeConfig variable
- [x] Static PeerIDs in a dynamic peers.txt list (@AryehAlexander is picking this up)
- [x] Master should not build every hour, only every commit (or even every tag). If we do want to re-run master frequently it needs to only release new packages when manually triggered.
- [x]  Add `sudo -n` so that sudo doesn't hang when prompting for a password
- [x]  Remove need for `sudo chmod` in the one-click deploy steps because its not portable enough.

**Comment by 0x0I** [comment]
>     * Master should not build every hour, only every commit (or even every tag). If we do want to re-run master frequently it needs to only release new packages when manually triggered.

Discussed offline w/ @lk86 and the @hourly `master` job has been removed while build idempotence (against master + other branches) issues are investigated.

**Comment by 0x0I** [comment]
>     * -generate-genesis-proof=true should be possible to configure in helm independent of the runtimeConfig variables

Will create an Issue and work on a PR for this.

**Comment by 0x0I** [comment]
>     * [ ]   Remove need for `sudo chmod` in the one-click deploy steps because its not portable enough.

Truth, will look into this.

**Comment by 0x0I** [comment]
>     * [x]   Add `sudo -n` so that sudo doesn't hang when prompting for a password
> 
>     * [x]   Remove need for `sudo chmod` in the one-click deploy steps because its not portable enough.

Resolved with #7607
