### ISSUE TITLE
Tool / client command for validating keypairs and passwords

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#7553]
As a sanity check, we should have a tool -- and functionality built into the binary itself, to ensure that it is consistent with the latest version -- 
* check that a password is correct for a keypair
* confirm a public key is derived from a private key
* confirm that the keypair is valid (presumably by signing something and verifying the signature)

**Comment by aneesharaines** [comment]
https://www.notion.so/minaprotocol/Keypairs-Redux-901b3491ea5141d9a33d3c0bef6e61b3

**Comment by aneesharaines** [comment]
1. Add version into mina-gdenerate-keypair - 

3. Fix password input SHELL variable regression

2. Daemon tool thing that Andrew was talking about

- Easily create a genesis ledger with *exactly* 2 keys (1. that you generated with all the stake in it — 2. is another one that is your "hot wallet")
- Instructions on running the daemon in block-production *using* that key
    - Using the key that was generated in a *delegating capacity* if it was generated with the ledger hardware
- Determine if VRFs successfully complete successfully within the first 20 slots — or just computing the vrf
    - Exit successfully if a VRF is found within 20 slots with a happy message

**Comment by mrmr1993** [comment]
This is done. Closing.
