### ISSUE TITLE
Suspected out-of-memory: verifier crashes with "memory allocation of 8388608 bytes failed"

### ISSUE THREAD

**Issue by mnguyen-io** [MinaProtocol/mina#7558]
Hi - Looks like mina crashed, but I'm not sure how to replicate this - it just so happened to appear while I was testing something unrelated. The logs are below, hope they are helpful:

n 20 18:22:17 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:22:17 UTC [Error] Verifier stderr: "memory allocation of 8388608 bytes failed"
Jan 20 18:22:17 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:22:17 UTC [Error] verifier terminated unexpectedly
Jan 20 18:22:17 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:22:17 UTC [Info] verifier successfully stopped
Jan 20 18:22:17 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:22:17 UTC [Info] Daemon started process of kind "Verifier" with pid 21633
Jan 20 18:22:53 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:22:53 UTC [Error] Verifier stderr: "memory allocation of 8388608 bytes failed"
Jan 20 18:23:05 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:23:05 UTC [Error] verifier terminated unexpectedly
Jan 20 18:23:05 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:23:05 UTC [Info] verifier successfully stopped
Jan 20 18:23:05 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:23:05 UTC [Warn] failed to reset stream (this means it was probably closed successfully): $error
Jan 20 18:23:05 mina-testworld-dev-2 coda[4855]: #011error: {
Jan 20 18:23:05 mina-testworld-dev-2 coda[4855]:   "string":
Jan 20 18:23:05 mina-testworld-dev-2 coda[4855]:     "RPC #165518 failed: \"internal RPC error error: unknown stream_idx\""
Jan 20 18:23:05 mina-testworld-dev-2 coda[4855]: }
Jan 20 18:23:05 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:23:05 UTC [Info] Daemon started process of kind "Verifier" with pid 21687
Jan 20 18:23:12 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:23:12 UTC [Info] Sending transition_chain_proof to $peer
Jan 20 18:23:12 mina-testworld-dev-2 coda[4855]: #011peer: {
Jan 20 18:23:12 mina-testworld-dev-2 coda[4855]:   "host": "158.51.121.47",
Jan 20 18:23:12 mina-testworld-dev-2 coda[4855]:   "peer_id": "12D3KooWAmjDr9TbTRQQgyqs9P34nBdR3zy5fW5bifHZtdPaSABo",
Jan 20 18:23:12 mina-testworld-dev-2 coda[4855]:   "libp2p_port": 8302
Jan 20 18:23:12 mina-testworld-dev-2 coda[4855]: }
Jan 20 18:23:35 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:23:35 UTC [Error] Verifier stderr: "memory allocation of 8388608 bytes failed"
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:00 UTC [Error] verifier terminated unexpectedly
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:00 UTC [Info] verifier successfully stopped
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:00 UTC [Error] after "the remote host" closed the stream, stream state invariant broke (previous state: "Mina_net2.FullyOpen")
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:00 UTC [Error] error sending message on stream 148917: $error
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]: #011error: {
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]:   "string":
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]:     "RPC #165661 failed: \"only wrote 0 out of 9 bytes error: libp2p error error: closed stream\""
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]: }
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:00 UTC [Warn] failed to reset stream (this means it was probably closed successfully): $error
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]: #011error: {
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]:   "string":
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]:     "RPC #165666 failed: \"internal RPC error error: unknown stream_idx\""
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]: }
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:00 UTC [Warn] failed to reset stream (this means it was probably closed successfully): $error
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]: #011error: {
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]:   "string":
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]:     "RPC #165667 failed: \"internal RPC error error: unknown stream_idx\""
Jan 20 18:24:00 mina-testworld-dev-2 coda[4855]: }
Jan 20 18:24:01 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:01 UTC [Info] Daemon started process of kind "Verifier" with pid 21742
Jan 20 18:24:08 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:08 UTC [Error] Verifier stderr: $stderr
Jan 20 18:24:08 mina-testworld-dev-2 coda[4855]: #011stderr: "memory allocation of memory allocation of memory allocation of memory allocation of 83886088388608 bytes failed bytes failed8388608 bytes failed8388608 bytes failed"
Jan 20 18:24:08 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:08 UTC [Error] verifier terminated unexpectedly
Jan 20 18:24:08 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:08 UTC [Info] verifier successfully stopped
Jan 20 18:24:11 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:11 UTC [Info] Daemon started process of kind "Verifier" with pid 21796
Jan 20 18:24:14 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:14 UTC [Error] Verifier stderr: $stderr
Jan 20 18:24:14 mina-testworld-dev-2 coda[4855]: #011stderr: "memory allocation of memory allocation of memory allocation of memory allocation of 83886088388608 bytes failed bytes failed8388608 bytes failed8388608 bytes failed"
Jan 20 18:24:41 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:41 UTC [Error] verifier terminated unexpectedly
Jan 20 18:24:41 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:41 UTC [Info] verifier successfully stopped
Jan 20 18:24:41 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:24:41 UTC [Info] Daemon started process of kind "Verifier" with pid 21849
Jan 20 18:25:21 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:25:21 UTC [Info] Daemon child process 21849 terminated after receiving signal "sigabrt"
Jan 20 18:25:21 mina-testworld-dev-2 coda[4855]: 2021-01-20 18:25:21 UTC [Error] Child process of kind "Verifier" with pid 21849 has terminated
Jan 20 18:25:38 mina-testworld-dev-2 coda[22006]: 2021-01-20 18:25:38 UTC [Info] Coda daemon is booting up; built with commit "[DIRTY]d44a1339bdbdd5ebe747124c7146f435a3f73453" on branch "HEAD"
Jan 20 18:25:38 mina-testworld-dev-2 coda[22006]: 2021-01-20 18:25:38 UTC [Info] Removing lockfile for terminated process
Jan 20 18:25:38 mina-testworld-dev-2 coda[22006]: 2021-01-20 18:25:38 UTC [Info] Daemon will expire at "2024-12-10 14:00:00-07:00"
Jan 20 18:25:38 mina-testworld-dev-2 coda[22006]: 2021-01-20 18:25:38 UTC [Info] Booting may take several seconds, please wait
Jan 20 18:25:38 mina-testworld-dev-2 coda[22006]: 2021-01-20 18:25:38 UTC [Info] Reading configuration files $config_files

4 core, 32GB memory.

**Comment by mrmr1993** [comment]
These messages seem to indicate that high memory usage is causing problems, e.g.
```
2021-01-20 18:22:17 UTC [Error] Verifier stderr: "memory allocation of 8388608 bytes failed"
```

@mnguyen-io can you confirm whether you're seeing high (close to 100%) memory usage on your node?

**Comment by mnguyen-io** [comment]
Hi, the VM has 32GB of RAM and the only thing that's really running on it is Mina (it's been running for about a week now). I didn't get a chance to see the memory usage at the time of the crash, I'll setup some monitoring around it. FYI - It is not running as a block producer.

I can see it's currently utilizing 16GB of memory and it's been running for about 2 hours.

**Comment by mrmr1993** [comment]
We're seeing better behaviour around memory usage after #7551. Tentatively closing this.
