### ISSUE TITLE
Reject multiple transitions from the same public key during the same slot

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#756]
If more than one transition for a specific public key and slot are received, that means that the node that proposed the slots is either an adversary or has had their public key compromised. In this event, other nodes should not accept any of the transitions with that public key and that slot. As to whether or not other nodes should accept future transitions from that public key should be determined as well.

@cmr thinks we should at least log when this happens.

**Comment by jkrauska** [comment]
Wouldn't these be valid if an account was wanting to submit txns to two difference recipients in the same slot?  Isn't this what incrementing the nonce is for?

**Comment by enolan** [comment]
This is about external transitions i.e. blocks.

**Comment by jkrauska** [comment]
> This is about external transitions i.e. blocks.

thanks
