### ISSUE TITLE
All nodes should be talking to some archive node deployment

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#7563]
The archive node supports many daemons connecting to the same archive node (we're not sure how many, this needs testing), but our infrastructure does not. The block producer chart needs to optionally accept an archive node config, and we then need to test how many simultaneous connections can the archive node keep up with.

**Comment by es92** [comment]
Is this needed for mainnet if we have a partner running an archive node? Would propose we do other work first (like having alerts + monitoring for all the things we talk about) before implementing this

**Comment by lk86** [comment]
Also handle making the postgres DB or entire deployment "serializable" using on of the methods defined in comments on https://github.com/MinaProtocol/mina/pull/7707#issuecomment-769825661
