### ISSUE TITLE
multiple archive processes, daemon, and databases

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#7567]
1. Determine a safe upper-bound for the number of daemons that can connect to the archive process that would not overload the archive process with multiple rpc requests. (Keep in mind each node will receive multiple blocks per slot that would be sent to the archive process)
2. can multiple archive processes write to one postgres database without issues? If so, determine a safe upper-bound for the number of archive processes

The infrastructure for archive node redundancy needs to be designed based on this information

**Comment by deepthiskumar** [comment]
#### multiple daemons connecting to an archive process
max concurrent rpc connections is 10,000 (from [here](https://github.com/janestreet/async_unix/blob/4d399ddf54400c19bd81ae7954f8fe6f79a67f2f/src/tcp.ml#L4019)). So connecting multiple daemon to an archive process should be fine since each daemon would only have one connection at a time.

#### multiple archive processes writing to the same postgres instance
Read up on some postgres documentation on concurrency https://www.postgresql.org/docs/current/transaction-iso.html.

   1. Having multiple archive nodes write (without any pruning) to the same database would not cause data inconsistencies. The default strategy `Read Committed` ensures there are no dirty reads and given none of our operations update a column based on the previous value of the column (like, `update table X set X.count = X.count + 1 where id=..`), the updates won't cause data corruption. But it is possible that the one process will error out when trying to commit an already committed block by another process. And when there are multiple processes trying only one of them will ever be successful and the others may fail due to constraint violation errors. 
For example, when two archive processes try to add same block to the database and if the first process commits it shortly after the second checks for existence of the state_hash, then as per our current implementation, the second process would go ahead and try to update/insert the data and cause uniqueness constraint failures.

   2. Pruning blocks may cause some data inconsistencies though, like referencing foreign keys in one process and some of those getting  deleted (and committed) by another process. The first process would then commit a foreign key reference that no longer exists.

Given the possibility of these issues, I think we should to set the transaction isolation level to `Serializable`. This will ensure concurrent transactions are executed as if they were run serially and prevent data corruption. We will have to implement a retry logic in our archive process code because some of the commits might fail initially but in the subsequent tries they would all be no-op if the block data was successfully added by one of the other archive processes .
The command to do this is `ALTER DATABASE <DATABASE NAME> SET DEFAULT_TRANSACTION_ISOLATION TO SERIALIZABLE ;`

Also, max concurrent connections to the postgres database is 100 by default and caqti reserves a max of  8 connections by default or what is set in env variable `CAQTI_POOL_MAX_SIZE` (we don't use this). We don't have to change the defaults if it is working for us (changing max connections involves changing the shared buffer size as well which requires changing the kernel max segment size). Given all that, we should probably have at most 6 archive processes connected to the same db (at most 50% of max connections, just to be safe)
We could start with two archive processes and go from there.

**Comment by aneesharaines** [comment]
Need docs

**Comment by yourbuddyconner** [comment]
Docs PR Here: https://github.com/MinaProtocol/mina/pull/7864
