### ISSUE TITLE
Move archive data recovery command to the archive process

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#7569]
Having the archive process and related tooling reside in the node running the archive process will make it easier to use them
Move `coda advanced archive-blocks` to the archive process. `missing_subchains`, `missing_blocks_auditor` are standalone tools that be installed in the same node as the archive process

**Comment by psteckler** [comment]
The `missing_subchains` and `missing_blocks_auditor` tools interact directly with Postgresql, without requiring the `archive` process to be running.

So, does this mean, create a new tool, like `archive_blocks`, that works in the same way? 

That would certainly be more convenient than the current setup, which requires a running daemon and archive process.

**Comment by deepthiskumar** [comment]
A standalone tool would be nice. @mrmr1993 suggested we retain the daemon version as well, gives us an option to do it remotely using graphql

**Comment by psteckler** [comment]
I tried to archive a block using GraphQL, had trouble formatting the input -- maybe there's a trick I didn't see.
