### ISSUE TITLE
Coda process exited with status code 139

### ISSUE THREAD

**Issue by Igor-Tselkovskiy** [MinaProtocol/mina#7572]
https://drive.google.com/file/d/1EHBkXsgyjhd7lwEXpbC1n2W8klCu3K74/view?usp=sharing

{"timestamp":"2021-01-20 22:07:36.352926Z","level":"Debug","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 169, characters 8-20"},"message":"Snark worker working directory $dir","metadata":{"dir":"/root","pid":359,"process":"Snark Worker"}}
{"timestamp":"2021-01-20 22:07:36.353004Z","level":"Debug","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 181, characters 6-18"},"message":"Snark worker using daemon $addr","metadata":{"addr":"127.0.0.1:8301","pid":359,"process":"Snark Worker"}}
{"timestamp":"2021-01-20 22:07:36.727423Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 201, characters 10-21"},"message":"SNARK work $work_ids received from $address. Starting proof generation","metadata":{"address":"127.0.0.1:8301","pid":359,"process":"Snark Worker","work_ids":[727884389,658267815]}}
2021-01-20 22:08:29 UTC [Info] verifier successfully got sigkill
2021-01-20 22:08:29 UTC [Info] verifier successfully stopped
2021-01-20 22:08:29 UTC [Info] Daemon started process of kind "Verifier" with pid 568
/root/init_coda_baked.sh: line 14:    12 Segmentation fault      (core dumped) coda "$command" -config-file "/root/daemon.json" "$@" 2>&1 > coda.log
+ echo 'Coda process exited with status code 139'
+ sleep 10
Coda process exited with status code 139
+ kill 13
+ '[' '!' -f stay_alive ']'
+ exit 0

**Comment by mrmr1993** [comment]
Closing in favour of #7333. I've moved your comment to there.
