### ISSUE TITLE
Possible Solutions for DNS on k8s nodes

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#7593]
Goals:
- Simple implementation / integration with our existing tooling on GKE
- Minimal changes to our existing security/trust model around manipulating this service to mislead network traffic
  - The system around static peer keys helps to mitigate this, but peer public keys are not as human-readable as DNS

- CoreDNS: https://github.com/coredns/coredns
  - Fully serves DNS, could be moved into infrastructure we completely control (as opposed to relying on a cloud provider)
  - Uses plugins for easy compatibility with the cloud providers we use and with k8s itself
  - Serves DNS over TLS/https, even serves over gRPC via a non-standard protocol
  - Could eventually build tooling around very securely querying a server we control, but should also work out of the box with traditional DNS
  - Supports ENS w/ a plugin
  - Also handles internal caching and DNS resolution within the cluster (claims to be more efficient than the original kube-dns)

- ExternalDNS: https://pkg.go.dev/sigs.k8s.io/external-dns#readme-what-it-does https://github.com/kubernetes-sigs/external-dns/blob/v0.7.6/docs/tutorials/gke.md
  - Does not actually serve DNS for us, only configures Google's managed product
  - Should be very quick to incorporate into our existing process
  - Requires a very small amount of infrastructure that we maintain (just provides a bridge between k8s and google cloud DNS)
  - Simpler than CoreDNS

**Comment by 0x0I** [comment]
+1 on the *ExternalDNS* solution and cool mostly impartial to the underlying public DNS server/provider (route53, google cloud dns etc)
