### ISSUE TITLE
 2982 block is red

### ISSUE THREAD

**Issue by bugz34btc** [MinaProtocol/mina#7616]
2982 block is red
https://minaexplorer.com/block/3NLFi89Lbx8vc4mzENUCcQU17hUQzRJsMLmrJ8PqZfLRLS271Z88
The node was synchronized. There was definitely no lag in the blocks. Everything was exactly the same as in esplorer. The snark wasn't turned on. Home PC. The block was created but it was created in red. The session was started in tmux and I can't get the logs right now. For what reason the block is red and my block was taken away https://minaexplorer.com/block/3NK4AaNkLVnNRkffW5LEsd4YuAVZ2e8kWWNtfpHqMsss2L3Dzzqc
slot and time are the same.  i got fresh peers. correct block height and max observed block height.

**Comment by garethtdavies** [comment]
This isn't an issue and is expected as there can be multiple block producers in the same slot see https://minaprotocol.com/docs/troubleshooting#why-was-my-block-orphaned--why-did-i-not-get-a-block-reward

**Comment by mrmr1993** [comment]
Closing, this is expected behaviour.
