### ISSUE TITLE
Implement and test watchdog alerts

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#7619]
Name | Alert level | Description | Frequency | Added? | Tested?
-- | -- | -- | -- | -- | --
Block broadcast | Red | Telemetry is showing > 90% of nodes that are synced are synced to within 3 blocks of the top block height | At least once per 30 minutes |   |  
Node state health | Red | Telemetry is showing > 50% of nodes are synced | At least once per hour |  |  
Prover errors | Red | Telemetry is showing a node with a prover error (either for block production or snark work) | At least once per hour |  |  
Blocks added to network block data | Red | Check at least one block has been posted to the google block storage bucket in the last 30 minutes | At least once per 30 minutes |  |  
Seed list down | Red | Check if can connect to at least one peer in the seed list | At least once per hour |  |  
Seed list degraded | Orange | Check if can connect to ≥ 50% of peers in seed list | At least once per hour |  |  
No cluster node crashes | Yellow | None of the cluster nodes has crashed unexpectedly | At least once per 30 minutes |  |

**Comment by es92** [comment]
Telemetry is showing > 90% of nodes that are synced are synced to within 3 blocks of the top block height
Telemetry is showing > 50% of nodes are synced
Telemetry is showing a node with a prover error (either for block production or snark work)
Check at least one block has been posted to the google block storage bucket in the last 30 minutes
Check if can connect to at least one peer in the seed list
Check if can connect to ≥ 50% of peers in seed list
None of the cluster nodes has crashed unexpectedly

**Comment by aneesharaines** [comment]
Break up into metrics based tickets - TODO

**Comment by es92** [comment]
Split out into different issues
