### ISSUE TITLE
Add exit code to child process logs when they exit to help debug nodes crashing during first catchup

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#7620]
This would help verify if they're being killed from memory pressure, if the code turns out to be 137

Recent example:

{"timestamp":"2021-01-22 09:41:55.394467Z","level":"Info","source":{"module":"Dune__exe__Coda","location":"File \"src/app/cli/src/coda.ml\", line 491, characters 16-27"},"message":"Daemon child process $child_pid terminated after receiving signal $signal","metadata":{"$duplicated_keys":["host","peer_id","port"],"child_pid":73,"host":"34.70.183.242","peer_id":"12D3KooWDqXFAw3JEZji5Qj2rUaUeLyz2CkcN1UYuKms6wNy7iRr","pid":12,"port":10507,"signal":"sigkill"}}

{"timestamp":"2021-01-22 09:41:55.394535Z","level":"Error","source":{"module":"Child_processes__Termination","location":"File \"src/lib/child_processes/termination.ml\", line 31, characters 6-18"},"message":"Child process of kind $process_kind with pid $child_pid has terminated","metadata":{"$duplicated_keys":["host","peer_id","port"],"child_pid":73,"host":"34.70.183.242","peer_id":"12D3KooWDqXFAw3JEZji5Qj2rUaUeLyz2CkcN1UYuKms6wNy7iRr","pid":12,"port":10507,"process_kind":"Prover"}}

**Comment by psteckler** [comment]
The call to `wait` provides a signal or an exit code. So if you see a `SIGKILL`, as above, there's no exit code available.

If you look at the Linux man pages for `wait/waitpid/waitid`, you get the signal number, or an exit code, but not both.

**Comment by aneesharaines** [comment]
There's no action to really take here?  The sigkill seems to be a pretty solid pointer.  We can add an additional error message though to help users understand the likelihood of this being caused by memory pressure.

**Comment by psteckler** [comment]
Added new log in #7696.
