### ISSUE TITLE
Add password trial timeout to cli commands

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#7638]
It is possible to brute force wallet keypair passwords via the CLI as we do not attempt to provide any kind of timeout for repeated attempts to unlock wallets. This is also true of direct GraphQL api calls.

**Comment by aneesharaines** [comment]
@figitaki  - can you add the spec for what the new behavior will be?

**Comment by mrmr1993** [comment]
Shouldn't we use a stronger crypto algorithm instead of papering over this with UI? Otherwise, any vaguely competent adversary can extract the algorithm and do the same attack.

**Comment by aneesharaines** [comment]
@figitaki to push the branch

**Comment by emberian** [comment]
Secret_box uses a strong password hash, Argon2, this should not be a realistic concern. We could crank up the difficulty, the next level up suggests about 3.5 seconds per unlock.

**Comment by emberian** [comment]
from https://www.ory.sh/choose-recommended-argon2-parameters-password-hashing/, good generic advice for choosing difficulty parameters:

> To reach the desired execution time, you can tweak two variables. It is recommended to start with the highest amount of memory possible and one iteration. Reduce the memory until one hashing operation takes less than your desired duration. Next, advance the number of iterations to approach the desired execution time as close as possible.
