### ISSUE TITLE
Why is it that the longer my nodes run, the fewer my peers？

### ISSUE THREAD

**Issue by MisterBigfeng** [MinaProtocol/mina#7648]
Why is it that the longer my nodes run, the fewer my peers？After a few days of operation, there will be several fellow travelers left, and even less, there will be one

**Comment by mrmr1993** [comment]
@MisterBigfeng it's not possible for us to investigate this without your logs.

I'm closing this for now, but please update here with your logs (using the `client export-logs` subcommand) so that we can reopen and start investigating.
