### ISSUE TITLE
Multiple Transaction_pool.apply calls may race, losing transactions

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#7651]
`Transaction_pool.apply` may yield to the async scheduler before or between applying transactions. In particular, this means that 2 or more calls may race such that the last to finish is the only one whose transactions are stored in the final pool.

Sample run:
1. thread 1 [captures the current contents of the pool](https://github.com/MinaProtocol/mina/blob/9a260feaf175f173f01b22f52ec5a5bb0a214152/src/lib/network_pool/transaction_pool.ml#L1194) (`P`)
2. thread 1 [applies a transaction its copy of the pool](https://github.com/MinaProtocol/mina/blob/9a260feaf175f173f01b22f52ec5a5bb0a214152/src/lib/network_pool/transaction_pool.ml#L947) (`P+txn1`)
3. thread 1 [yields to the async scheduler](https://github.com/MinaProtocol/mina/blob/9a260feaf175f173f01b22f52ec5a5bb0a214152/src/lib/network_pool/transaction_pool.ml#L1024)
4. thread 2 is scheduled and also captures the current contents of the pool (`P`)
5. thread 2 applies a transaction to its copy of the pool (`P+txn2`)
6. thread 2 yields to the scheduler (or not, we have a race either way)
7. thread 1 [writes its updated pool to the shared reference](https://github.com/MinaProtocol/mina/blob/9a260feaf175f173f01b22f52ec5a5bb0a214152/src/lib/network_pool/transaction_pool.ml#L908) (`P+txn1`)
8. thread 1 finishes or yields to the scheduler
9. thread 2 also writes its updated pool to the shared reference (`P+txn2`)

The final pool is `P+txn2`; the transaction(s) from thread 1 are lost due to the race. We should use some kind of locking to avoid races in writes to the pool.

**Comment by mrmr1993** [comment]
Proposed fix: write to the pool before every async yield, read the pool back after.

**Comment by aneesharaines** [comment]
!approved-for-mainnet
