### ISSUE TITLE
Two green blocks in a row

### ISSUE THREAD

**Issue by iuriizzz** [MinaProtocol/mina#7653]
I have noticed an account that produced 2 green blocks in a row. 
I guess, it is possible to get the next slot with an incredible amount of luck, but it still looks suspicious. Maybe you may check how is that happened. 

![45c31c63af443ad612b943b38769276c](https://user-images.githubusercontent.com/61374760/105574721-e1798780-5d7f-11eb-818e-64f25879dd95.png)

**Comment by mrmr1993** [comment]
Some stats:
* block fill rate as of that block is 3093/3945=0.78
  - I think we're expecting a value of 0.75, ~5% margin of error seems reasonable
* 2025 accounts in the genesis ledger [here](https://github.com/MinaProtocol/mina/blob/compatible/automation/terraform/testnets/testworld/genesis_ledger.json), assuming they're all block producers with equal chance of winning each block

```
P = P(the next block isn't empty and the same producer won the next block)
  = P(the next block isn't empty) * P(the same producer won the next block)
  = 0.78 * 1/2025
  = 0.78 * 0.00049
  = 0.00039
  ≈ 1/2596
```

By this very rudimentary analysis, we would have expected to see this happen `~ 3093/2596 = 1.19` times over the course of 3093 blocks, so I recon it was actually a little overdue!

**Comment by iuriizzz** [comment]
Well, I though it is more unique. Thanks for calculation
