### ISSUE TITLE
Improve error message for coda advanced add-peers

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#7655]
Currently, if you add an invalid peer the command `coda advanced add-peers` just returns immediately with no feedback. If that was your first time running it you would assume that it worked, however, that means the format was likely incorrect.

When it works the output is ```Requested to add peers:``` but there should be something of an error message when something that isn't valid is added or a general error that it was unable to add the peers rather than silently fail.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
