### ISSUE TITLE
Random block selection

### ISSUE THREAD

**Issue by Woodchipstar** [MinaProtocol/mina#7657]
My first Block will be produced in just over 10 hrs, this will be 20 days after I started running the node. I can see some node operators who have created 10 blocks in the last 5 days. 

Query - under the random selection pretence the chances of this imbalance happening are astronomical so would lead me to believe the current selection process can be gamed and has been by some. 

With the current random selection some nodes potentially having long gaps in-between blocks I wonder if this creates a security risk with node operators deciding to no longer run their nodes at an imbalanced rate to others, leading to a less decentralised Blockchain?

I have heard of other projects who have put a cap per epoch on an individual node creating to many blocks therefor increase the chance of others. I know this raises concerns as well but just raising as a potential issue moving ahead.

In this testnet I have been negatively impacted by not being able to produce blocks which may well affect my ability to reach the Genesis group.

If you want to have a look my public key is B62qrUZCvBiaGi8BWVS7zGxf9mPUxkL2DVh8foPSzhcexUk1U6UtALU

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
