### ISSUE TITLE
a subprocesses has no name

### ISSUE THREAD

**Issue by jkrauska** [MinaProtocol/mina#766]
rpc_parallel worker processes have non-specific names

eg.
/proc/39466/exe parallel-worker

it would be nice to wrap/alter the spawn code to name spawned subprocesses with something for operators to glean.

eg. 
coda-validator or coda-prover or coda-snark-worker

**Comment by jkrauska** [comment]
@nholland94  @cmr 
is possible

perl snippit
```
$0="what you looking at nathan";
sleep(120);
```

run it
```
perl foo.pl
```

results
```
jkrauska  65812  0.0  0.1 110180  4268 ?        S    10:58   0:01      \_ sshd: jkrauska@pts/0,pts/1
jkrauska  65813  0.0  0.1  30416  5644 pts/0    Ss   10:58   0:01          \_ -bash
jkrauska  75437  0.0  0.0  26940  3856 pts/0    S+   18:46   0:00          |   \_ what you looking at nathan
```

**Comment by jkrauska** [comment]
https://unix.stackexchange.com/questions/167490/how-can-a-process-appear-to-have-different-name-in-ps-output

**Comment by jkrauska** [comment]
in utop, this is ineffective.  Not sure if it works in non REPL universe.
```
utop # Sys.argv;;
- : string array = [|"/usr/bin/utop"|]

utop # Sys.argv.(0);;
- : string = "/usr/bin/utop"

Sys.argv.(0) <-  "hello";;
- : unit = ()

utop # Sys.argv;;
- : string array = [|"hello"|]


...

ps 
jkrauska  65812  0.0  0.1 110180  4268 ?        S    10:58   0:02      \_ sshd: jkrauska@pts/0,pts/1
jkrauska  65813  0.0  0.1  30416  5644 pts/0    Ss   10:58   0:01          \_ -bash
jkrauska  77096  0.1  0.3  59036 13448 pts/0    Sl+  19:00   0:00          |   \_ /usr/bin/ocamlrun /usr/bin/utop

```

**Comment by cmr** [comment]
The runtime doesn't expose the raw argv values, it copies them into ocaml values. But, it stores them in a C symbol called `caml_main_argv`, so we could manipulate that with some C code (I don't think ctypes will be able to see that symbol?)

**Comment by jkrauska** [comment]
@nholland94 
@cmr 
@psteckler 

Workable solution found! (thanks Paul!)

libbsd [1] has a C function that exposes the ability to rename a running process and is readily available on debian/ubuntu

I was able to do a fairly trivial Ctypes implementation with some tricky dune build options.

spttest.ml
```
open Ctypes
open Foreign

let setproctitle =
    foreign
      "setproctitle"
      (string @-> returning void)

let _ = setproctitle "Hello Nathan" ;
        Unix.sleep 900
```

dune
```
(executable
 (name spttest)
 (libraries unix ctypes ctypes.foreign)
 (link_flags -cclib -Wl,-z,nodlopen -cclib -Wl,-u,libbsd_init_func  -cclib -lbsd-ctor -cclib -lbsd)
 (modes native))
```

Without the -cstor you ALSO need to call an init function which proved tricky to trivially accomplish in Ctypes.

The libbsd code is less cross platform, but is easy to find in debian.

However, several places pointed to postgres [2] as having a very portable cross platform solution...

Both code seems similar.  It may be easier to ONLY bring over this particular file/content instead of requiring the whole library.


1. https://gitlab.freedesktop.org/libbsd/libbsd

2. https://github.com/postgres/postgres/blob/master/src/backend/utils/misc/ps_status.c

Let me know if we can add this to the rpc_parallel forked code to identify those subprocesses by name.

**Comment by enolan** [comment]
GHC does this for worker processes, I tweaked the code for it a year or so ago. Let me see if I can find it.

**Comment by enolan** [comment]
[Here](https://gitlab.haskell.org/ghc/ghc/blob/cd07086ada34888c08585f4dc98a961618748ed0/rts/posix/OSThreads.c#L141) they are calling `pthread_setname_np`, which unsurprisingly only works on pthreads. If the workers are actual processes you need one of the other techniques, but if they're threads this is the right thing.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
