### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Madbustazz** [MinaProtocol/mina#7661]
Hi! My Crash report

Git SHA-1: [DIRTY]a9402473584c36b347d52df4f4000b7286385987

2021-01-24 07:37:04 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: {
  "sexp": [
    "monitor.ml.Error",
    [ "Failure", "recursive add_exn failed" ],
    [
      "Raised at file \"stdlib.ml\", line 33, characters 17-33",
      "Called from file \"src/lib/network_pool/indexed_pool.ml\", line 928, characters 10-55",
      "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 947, characters 28-321",
      "Called from file \"src/result.ml\", line 96, characters 19-24",
      "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file \"lib/read.mll\", line 712, characters 13-36",
    "Called from file \"lib/read.mll\", line 241, characters 23-47"
  ]
}

**Comment by mrmr1993** [comment]
@Madbustazz can you attach the your logs from the `client export-logs` command?

**Comment by Madbustazz** [comment]
No problem!
https://drive.google.com/file/d/1Qy5AISWKt-qKLPGLoFDA3IsekYuCGeh7/view?usp=sharing

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
