### ISSUE TITLE
No Block for 20 days

### ISSUE THREAD

**Issue by Woodchipstar** [MinaProtocol/mina#7662]
Can someone look at the probability of a node...aka me, not getting a slot for 20 days. Something seems wrong.

Also when my slot comes available right now there is a problem, the snark work is not happening so even if i get the block i will get no reward for it.

Enjoying playing with the node(outside of no blocks), well done.

**Comment by mrmr1993** [comment]
* at slot 5115 (arbitrarily choosing [this recent block](https://minaexplorer.com/block/3NLSMLw9vA2Rw9jkNECoaS5EEC2vLmYv1swjr8LUBJSDbjeAg77z))
* 2025 accounts in the genesis ledger [here](https://github.com/MinaProtocol/mina/blob/compatible/automation/terraform/testnets/testworld/genesis_ledger.json), assuming they're all block producers with equal chance of winning each block

The probabilistic calculation that relates the VRF to winning a block is [here](https://github.com/MinaProtocol/mina/blob/9a260feaf175f173f01b22f52ec5a5bb0a214152/src/lib/consensus/proof_of_stake.ml#L833):
`vrf_output / 2^256 <= c * (1 - (1 - f)^(amount / total_stake))`

```
P(no slots won)
= P(didn't win slot 1 and didn't win slot 2 and ... and didn't win slot 5115)
= P(didn't win slot 1) * P(didn't win slot 2) * ... * P(didn't win slot 5115)
= P(didn't win a slot)^5115
= (1 - P(won a slot))^5115
= (1 - (c * (1 - (1 - f)^(amount / total_stake))))^5115
```
Subbing in `c = 1`, `f = 3/4` (these are constants) and `amount / total_stake = 1/2025` gives
```
= (1 - (1 * (1 - (1 - 3/4)^(1/2025))))^5115
= ((1/4)^(1/2025))^(5115)
= (1/4)^(5115/2025)
~= 3%
```

I'm going to close this: this probability is low, but not so low that it would be unexpected.

> Also when my slot comes available right now there is a problem, the snark work is not happening so even if i get the block i will get no reward for it.

We've found and fixed the issue, snark work should be back to normal now. There's some more detail in issue #7656 and its linked pull requests.
