### ISSUE TITLE
Snark-job hasn't a cryptographic signature

### ISSUE THREAD

**Issue by diman-io** [MinaProtocol/mina#7667]
I think you have a vulnerability in snark-worker communication with the network.

Look.
I can run snark-worker without a private key, I only need the public key to run a snark-worker.

But this means that someone on the network can read my messages with completed snark-job and send a copy of the message after changing (decreasing) the amount of the commission and the author (public key).

Snark-job has no cryptographic signature. This is a problem.

**Comment by mrmr1993** [comment]
A signature of knowledge is associated with snark proofs, which has type [`Sok_digest.t`](https://github.com/MinaProtocol/mina/blob/9a260feaf175f173f01b22f52ec5a5bb0a214152/src/lib/mina_base/sok_message.ml#L8), including the prover's public key and the fee. This is required by the [`verify`](https://github.com/MinaProtocol/mina/blob/9a260feaf175f173f01b22f52ec5a5bb0a214152/src/lib/transaction_snark/transaction_snark.mli#L235) function, and the proof won't verify if it doesn't match, providing exactly this cryptographic security.
