### ISSUE TITLE
Node crashed with "recursive add_exn failed"

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#7668]
`whale-block-producer-11-547d8c85bd-s4wvv` crashed with this error
```
exn: {
    backtrace: [
     0: "Raised at file "stdlib.ml", line 33, characters 17-33"      
     1: "Called from file "src/lib/network_pool/indexed_pool.ml", line 881, characters 14-49"      
     2: "Called from file "src/lib/network_pool/transaction_pool.ml", line 947, characters 28-321"      
     3: "Called from file "src/result.ml", line 96, characters 19-24"      
     4: "Called from file "src/deferred1.ml", line 17, characters 40-45"      
     5: "Called from file "src/job_queue.ml" (inlined), line 131, characters 2-5"      
     6: "Called from file "src/job_queue.ml", line 171, characters 6-47"      
    ]
    sexp: [
     0: "monitor.ml.Error"      
     1: [
      0: "Failure"       
      1: "recursive add_exn failed"       
     ]
     2: [
      0: "Raised at file "stdlib.ml", line 33, characters 17-33"       
      1: "Called from file "src/lib/network_pool/indexed_pool.ml", line 881, characters 14-49"       
      2: "Called from file "src/lib/network_pool/transaction_pool.ml", line 947, characters 28-321"       
      3: "Called from file "src/result.ml", line 96, characters 19-24"       
      4: "Called from file "src/deferred1.ml", line 17, characters 40-45"       
      5: "Called from file "src/job_queue.ml" (inlined), line 131, characters 2-5"       
      6: "Called from file "src/job_queue.ml", line 171, characters 6-47"       
      7: "Caught by monitor coda" 
```

link to the stackdriver crash log 

https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=o1labs-192920&minLogLevel=0&expandAll=false&timestamp=2021-01-25T17%3A55%3A47.517000000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22coda%22%0Aresource.labels.project_id%3D%22o1labs-192920%22%0Aresource.labels.pod_name%3D%22whale-block-producer-11-547d8c85bd-s4wvv%22%0Aresource.labels.cluster_name%3D%22coda-infra-central1%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.namespace_name%3D%22testworld%22%0Atimestamp%3D%222021-01-25T08%3A37%3A30.238568216Z%22%0AinsertId%3D%22auqky3hdv0b48zm5y%22&scrollTimestamp=2021-01-25T08%3A39%3A20.519129145Z

**Comment by gregbostrom** [comment]
I just had this crash as well.
```
2021-01-26 06:22:06 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: {
  "sexp": [
    "monitor.ml.Error",
    [ "Failure", "recursive add_exn failed" ],
    [
      "Raised at file \"stdlib.ml\", line 33, characters 17-33",
      "Called from file \"src/lib/network_pool/indexed_pool.ml\", line 928, characters 10-55",
      "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 947, characters 28-321",
      "Called from file \"src/result.ml\", line 96, characters 19-24",
      "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
```
with version
```
Commit [DIRTY]a9402473584c36b347d52df4f4000b7286385987 on branch HEAD
```

**Comment by gregbostrom** [comment]
Had it again using the same version listed above.

```
2021-01-27 04:14:38 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: {
  "sexp": [
    "monitor.ml.Error",
    [ "Failure", "recursive add_exn failed" ],
    [
      "Raised at file \"stdlib.ml\", line 33, characters 17-33",
      "Called from file \"src/lib/network_pool/indexed_pool.ml\", line 928, characters 10-55",
      "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 947, characters 28-321",
      "Called from file \"src/result.ml\", line 96, characters 19-24",
      "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
```

**Comment by dimaelkhsos** [comment]
I have same issue,
Generating crash report
    exn: {
  "sexp": [
    "monitor.ml.Error",
    [ "Failure", "recursive add_exn failed" ],
    [
      "Raised at file "stdlib.ml", line 33, characters 17-33",
      "Called from file "src/lib/network_pool/indexed_pool.ml", line 928, characters 10-55",
      "Called from file "src/lib/network_pool/transaction_pool.ml", line 947, characters 28-321",
      "Called from file "src/result.ml", line 96, characters 19-24",
      "Called from file "src/deferred1.ml", line 17, characters 40-45",
      "Called from file "src/job_queue.ml" (inlined), line 131, characters 2-5",
      "Called from file "src/job_queue.ml", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file "stdlib.ml", line 33, characters 17-33",
    "Called from file "src/lib/network_pool/indexed_pool.ml", line 928, characters 10-55",
    "Called from file "src/lib/network_pool/transaction_pool.ml", line 947, characters 28-321",
    "Called from file "src/result.ml", line 96, characters 19-24",
    "Called from file "src/deferred1.ml", line 17, characters 40-45",
    "Called from file "src/job_queue.ml" (inlined), line 131, characters 2-5",
    "Called from file "src/job_queue.ml", line 171, characters 6-47"
  ]
}

**Comment by aneesharaines** [comment]
Is this still happening in 0.2.11?

**Comment by mrmr1993** [comment]
These errors are no longer fatal, and instead are handled at the pool level. See #7705. Closing.
