### ISSUE TITLE
Integration Test: Archive Node

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#7684]
Write a new test which deploys a network with an archive node and a few block producers. Let the network run for a bit while ensuring the archive node does not throw any errors (the log engine automatically accumulates errors from nodes to fail the test, but the archive node is currently not deployed or subscribed to). Additionally, once the test it complete, have the test export data from the archive node and save this information to the local filesystem. In the near future, we will run further tests against this exported data to test the archive recovery functionality. The exported data should include a psql dump of the database as well as a copy of the block log.

Implementing this will meet the acceptance feature requirement for archive node exporting.

**Comment by aneesharaines** [comment]
Need to expose postgres port - - @nholland94 and @QuiteStochastic to coordinate on picking this up
Also blocked on integration test not working.

**Comment by QuiteStochastic** [comment]
archive node test is not yet in CI, also the latest fix for the integration test isn't playing nice with the archive node test and needs to be investigated and fixed.  looks like the archive pod doesn't get assigned to a k8s node quickly enough

**Comment by QuiteStochastic** [comment]
Getting the archive node test fixed requires https://github.com/MinaProtocol/mina/issues/8471 to be completed.
