### ISSUE TITLE
Integration Test: Common Prefix

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#7686]
The integration test framework needs the capability to perform a common prefix check. A common prefix check looks at every node's best tip path, and determines the common prefix of all those paths, asserting that this common prefix is within some reasonable number of blocks back from each node's best tip. We would want to have a function `val check_common_prefix : Network.Node.t list -> unit Malleable_error.t` which can be called from tests to perform this check.

To do this, there are a few options.

1) We stream structured log events back from nodes running on the network, and using those, we can construct a network wide view of what nodes have seen what blocks through a "global frontier" like data structure. This data structure wouldn't necessarily contain whole blocks, but it would provide us a DAG of state hashes where each graph node contains a set of which daemons have seen that block. This data structure would be stored in the `Network_state.t`, which already contains other relevant information, such as each daemon's current best tip.

2) We can request best tip paths via graphql from each node. This option gives us an instananeous view of the state for each daemon we need to compute the common prefix, but it does not scale as well for when we want to run larger networks in the future. It would be ok to do this for now, but we may need to redo this approach in the future.

3) If, for some reason, option 1 is not quite reliable enough, we can do a hybrid between 1 and 2. In this world, the check would look at the data structure of 1 to do the computation, and make graphql requests like in step 2 whenever it encounters a conflict in data. I don't think we need to consider this option unless we see bugs with option 1, which I think is unlikely.

Out of these options, I think the best to try and implement is option 1. You can do option 2 if that is too difficult for now, and migrate to option 3 instead when we need to scale up.

**Comment by aneesharaines** [comment]
Blocked by Node failed to init bug, should be fixed by fix for graphql ingress

**Comment by aneesharaines** [comment]
Sometimes the test times out and buildkite kills the job and restarts due to the length of the time.   @ghost-not-in-the-shell to reduce the time it takes by reducing the number of blocks.  

Good candidate for nightlie.

**Comment by QuiteStochastic** [comment]
CI fixed, now merged
