### ISSUE TITLE
Integration Test: Gossip Consistency

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#7687]
Create a new test which deploys a network with a series of block producers and monitors the flow of gossip traffic to ensure that block gossips are consistent. This should be implemented in a way that can be easily reused in other tests in the future as well. If possible, try to come up with a network state data structure for doing this which does not leak memory over time.

Bonus: send payments and assert that they are also consistent (perhaps even extend to snark work submitted by the coordinator).

Implementing this will meet the acceptance feature requirement for gossip consistency checks.

**Comment by imeckler** [comment]
Does consistency mean "check that after some interval all nodes have seen the same data"?

**Comment by aneesharaines** [comment]
https://github.com/MinaProtocol/mina/pull/7884

**Comment by aneesharaines** [comment]
@nholland94 to try to land this this week once CI is fixed

**Comment by aneesharaines** [comment]
Needs to be merged now that CI is fixed

**Comment by QuiteStochastic** [comment]
actively working on debugging this test.

**Comment by QuiteStochastic** [comment]
completion of this issue blocked by and dependent on #8600

**Comment by QuiteStochastic** [comment]
this is done, just waiting for PR review and merge
