### ISSUE TITLE
Snark fees more than transaction fees

### ISSUE THREAD

**Issue by diman-io** [MinaProtocol/mina#7716]
https://minaexplorer.com/block/3NKZzE9Jyf6ewkiijAZweKfj3sHvScHZVeQmWfSMoRgea6pAQ3F2

Same case will be very bad for mainnet.

**Comment by diman-io** [comment]
Is there a protection against paying snark fees to another account?

**Comment by deepthiskumar** [comment]
Yes, if the coinbase receiver (in this example coinbase receiver = block creator) was different from the snark-worker account then this block would have been invalid (and rejected) because the transaction fees cannot pay the snark-worker account.
