### ISSUE TITLE
Automate the npm publish of the client SDK

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#7720]

**Comment by lk86** [comment]
Short circuiting when you're on a tagged commit:
```
TAG=$(git tag --points-at HEAD)

[[ -n $TAG ]] && exit
```

And you should be able to add it to https://github.com/MinaProtocol/mina/blob/develop/buildkite/scripts/client-sdk-tool.sh on the end of the existing client sdk job.
