### ISSUE TITLE
transfer of mina points to the wrong account

### ISSUE THREAD

**Issue by eraysen59** [MinaProtocol/mina#7736]
**mina, two accounts opened in my name appear on the panel. But I have an account. The 3750 points that appear here are my original account. But my duties have been transferred to an account with 2600 points. I request that these accounts be merged and transferred to my main account, Eray#1382.**
![eray1](https://user-images.githubusercontent.com/72926842/106359136-afd56300-6321-11eb-9f32-b0f3bed3314d.png)
**![eray2](https://user-images.githubusercontent.com/72926842/106359140-b49a1700-6321-11eb-8c3b-5f026d32a945.png)**

**Comment by eraysen59** [comment]
I'm waiting for your return

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
