### ISSUE TITLE
Signing on client-sdk incompatible with Mina daemon

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#7741]
Signatures via the client-sdk don’t seem to be broadcast properly on the network. Perhaps it’s missing token-id data?

**Comment by psteckler** [comment]
After getting some details from the person(s) who reported this issue, it appears that they were using a bogus keypair when signing the transaction.

Specifically, given the private key, deriving the corresponding public key gives a different result than the public key in the keypair. Moreover, the public key in the keypair, given in Base58Check format, while it can be decoded to an instance of `Public_key.Compressed.t`, does not successfully decompress.

I discovered these anomalies when trying to add the transaction to the client SDK signature comparison tests, using their keypair (and a receiver public key).

My belief is that there's no incompatibility. The tests in `scripts/compare_test_signatures.sh` compare payment and delegation signatures between the native consensus code (as in the daemon) and JS nonconsensus code (as in the client SDK), and those tests have been passing in CI, and locally for me.

**Comment by psteckler** [comment]
We could add a method to the SDK like `validKeypair`, which returns `Ok | Public_decompression_failure | Mismatched_public_key`

**Comment by psteckler** [comment]
Doesn't appear to be a bug.
