### ISSUE TITLE
The sync status is Synced, but the block height is behind

### ISSUE THREAD

**Issue by lesterli** [MinaProtocol/mina#7749]
By executing the command `coda client status`, it displays the sync status is **Synced**, but actually, the block height (**4553**) is behind the normal (**4916**). 

The below is the screenshot.

![image](https://user-images.githubusercontent.com/4919882/106544404-729beb80-6542-11eb-9ff6-1f40871391e0.png)

 `coda client export-local-logs`, the below is the log files.

[2021-02-02_02-25-53.tar.gz](https://github.com/MinaProtocol/mina/files/5908237/2021-02-02_02-25-53.tar.gz)

Pls. check it. Thanks.

**Comment by GialloRossi10** [comment]
Have the same problem couple of times and I see this issue on a regular basis in qa-task-force

**Comment by mrmr1993** [comment]
This is a dup of #7555. Closing.
