### ISSUE TITLE
stuck at the wrong height

### ISSUE THREAD

**Issue by Comdex** [MinaProtocol/mina#7750]
My node has been stuck at the wrong height for a long time.
The log has been uploaded in the attachment.
![捕获55](https://user-images.githubusercontent.com/3725514/106544999-8005a580-6543-11eb-9264-4a4a015d3d50.PNG)

[2021-02-02_02-29-20.tar.gz](https://github.com/MinaProtocol/mina/files/5908249/2021-02-02_02-29-20.tar.gz)

**Comment by mnguyen-io** [comment]
I've seen the same issue the past week (multiple times).

![image](https://user-images.githubusercontent.com/16768116/106790903-38098000-6622-11eb-8ab5-ec71102ca5dd.png)

**Comment by mrmr1993** [comment]
This is the same as #7555, closing in favour of that.
