### ISSUE TITLE
Flag to restrict surface area of GraphQL

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#7753]
## Background

This task blocks finishing the foundation re-delegation software

We need a way to reliably get uptime data for the purposes of measuring "block producer uptime" for redelegation. We also wish to make it easy to get information about the blockchain to detect synced-ness and we'd like a way to make it work without needing privileged access to our cluster.

A simple way to achieve this would be exposing the GraphQL server on nodes. Folks in the eligibility foundation delegation group would be required to opt-in to this.

Unfortunately, exposing the GraphQL server to the public internet is unsafe. For now, we've been suggesting proxies that remove unsafe endpoints and have DoS safety -- but something simple we can do: Make the endpoint authenticated (maybe also disable messing with private keys too in that mode).

## Details Around Restricted GraphQL Server

Make a new second restricted GraphQL server on a different port that can be optionally turned on. This is what we'd suggest folks port-forward if they don't trust consumers with private keys.

Include the following APIs (and only the following APIs):

Query:
* block

Mutation:
None

Subscription:
None

## Configuration

The authentication method with a properly configured SSH server as @mrmr1993 suggested below seems like the best path

**Comment by imeckler** [comment]
Could use client authentication in https://github.com/mirleft/ocaml-tls

**Comment by mrmr1993** [comment]
If we wanted to go down the ssh route for auth, we could use 'forced commands' and limited port forwarding. The manpage is a bit sparse on the topic, but [this SE answer](https://unix.stackexchange.com/a/337445) seems to cover pretty much what we would want.

**Comment by bkase** [comment]
@mrmr1993 ’s solution seems great — then all we need to do is make a flag to restrict the surface area of the graphql to hide the private key things

**Comment by mrmr1993** [comment]
To clarify: we don't want a flag to reduce the scope of the GraphQL server. That would prevent the node operator from running any commands that use GraphQL on their node, which at this point is basically all of them.

Instead, we want a second server (disabled by default, enabled by passing a flag to specify its port) to expose only the whitelisted APIs.

@bkase can you update here with the list of commands we want?

**Comment by aneesharaines** [comment]
@bkase  can you confirm which endpoint should be exposed here?
