### ISSUE TITLE
Expose the transactional chain hash function as MVP

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#7754]
Many folks are asking about how they can verify transactions as there is no history. The best way to do this is the receipt chain system, but, unfortunately, this has bitrot when we ripped the RocksDB database here out of the daemon.

We can always redirect people to look at a block explorer or run an archive node themselves, but it's better and simpler to take advantage of the receipt chain.

**Comment by aneesharaines** [comment]
Expose the transactional chain hash function as an MVP
