### ISSUE TITLE
cant connect to peers

### ISSUE THREAD

**Issue by Y0Y0jojo** [MinaProtocol/mina#7825]
I know you are probably aware by now that folks are having trouble connecting to peers. just figured I'd send you my logs just in case. sorry if its a bore.
[mina-log.txt](https://github.com/MinaProtocol/mina/files/5934498/mina-log.txt)
coda process exited with status code 1
2021-02-05 17:46:36 UTC [Error] Failed to find any peers during initialization (crashing because this is not a seed node)

**Comment by olton** [comment]
Same error.
Version [DIRTY]5493fe344b40b6e668315fb8db4aa7eef4f1963f

**Comment by argonau7** [comment]
Has this been solved? @olton @Y0Y0jojo ?

**Comment by Y0Y0jojo** [comment]
Hi, Yes this has been resolved. This is from a long time ago. Sorry i never closed it out.

**Comment by argonau7** [comment]
Ideally I'd know the solution 😄

Y0Y0jojo ***@***.***> schrieb am Do., 4. Nov. 2021, 15:58:
