### ISSUE TITLE
addPeers returns an error after the update to encore

### ISSUE THREAD

**Issue by kobigurk** [MinaProtocol/mina#7838]
I've been using the addPeers command in test world, but now I'm getting an error every time I use it: 
`Error: Argument seed of type Boolean! expected on field addPeers, but not provided. (in null)`

**Comment by imeckler** [comment]
Hi @kobigurk -- there is a fix up but there won't be an official release with it until after this weekend. In the meantime, you can

- use the docker image at `codaprotocol/coda-daemon:0.3.1-fix-add-peers-command`
- use the deb package [here](https://buildkite.com/organizations/o-1-labs-2/pipelines/mina/builds/10887/jobs/7cfa4755-528e-4a02-8b91-03756d3f952b/artifacts/52337508-bc49-4ffe-9536-d3f8f0a01835)

**Comment by bugz34btc** [comment]
0.3.1 still error "add peers"
![image](https://user-images.githubusercontent.com/36723711/107145958-34456880-6956-11eb-862e-4915b1f9f5f7.png)
![image](https://user-images.githubusercontent.com/36723711/107145961-3c9da380-6956-11eb-83d9-f9c6a1f684ff.png)

**Comment by mrmr1993** [comment]
@bugz34btc the fix hasn't been released yet, you can use the version [linked above](https://github.com/MinaProtocol/mina/issues/7838#issuecomment-774513183) in the meantime.

**Comment by kobigurk** [comment]
> Hi @kobigurk -- there is a fix up but there won't be an official release with it until after this weekend. In the meantime, you can
> 
> * use the docker image at `codaprotocol/coda-daemon:0.3.1-fix-add-peers-command`
> * use the deb package [here](https://buildkite.com/organizations/o-1-labs-2/pipelines/mina/builds/10887/jobs/7cfa4755-528e-4a02-8b91-03756d3f952b/artifacts/52337508-bc49-4ffe-9536-d3f8f0a01835)

Thanks @imeckler. The docker image seems like a bare image rather than the "baked" one prepared for the qa network. Is there a nice way to transform it to that one?

**Comment by mrmr1993** [comment]
The fix for this has been released. Closing.
