### ISSUE TITLE
Add JS SDK support keystore functionality 

### ISSUE THREAD

**Issue by wjdfx** [MinaProtocol/mina#7839]
For some user which use mina-generate-keypair tool generate keystore file, They also need import/export to wallet(such as app/extension) by keystore. 
But no Mina JS SDK didn't support handling keystore. It's very important. So whether consider adding a feature that allows the wallet tool to handle keystore.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
