### ISSUE TITLE
Doesn't restart when VM reboots

### ISSUE THREAD

**Issue by airocket** [MinaProtocol/mina#7845]
If the settings are made following the instructions (https://minaprotocol.com/docs/connecting) and not by the root user, then after the system reboot, the mina service will not autostart.
Mina service create file /usr/lib/systemd/user/**mina.service**:

```
[Unit]
Description=Mina Daemon Service
After=network.target
StartLimitIntervalSec=60
StartLimitBurst=3

[Service]
EnvironmentFile=%h/.mina-env
Type=simple
Restart=always
RestartSec=15
ExecStart=/usr/local/bin/coda daemon \
  -peer-list-file %h/peers.txt \
  -block-producer-key %h/keys/my-wallet \
  -generate-genesis-proof true \
  -log-level Info \
  $EXTRA_FLAGS
ExecStop=/usr/local/bin/coda client stop-daemon

[Install]
WantedBy=multi-user.target
```

Unit loaded with multi-user.target, but there is no such target in the user systemd, such a target is eaten only as root

For everything to work, you need to change **multi-user.target** to **default.target**
Change file /usr/lib/systemd/user/**mina.service**:

```
[Unit]
Description=Mina Daemon Service
After=network.target
StartLimitIntervalSec=60
StartLimitBurst=3

[Service]
EnvironmentFile=%h/.mina-env
Type=simple
Restart=always
RestartSec=15
ExecStart=/usr/local/bin/coda daemon \
  -peer-list-file %h/peers.txt \
  -block-producer-key %h/keys/my-wallet \
  -generate-genesis-proof true \
  -log-level Info \
  $EXTRA_FLAGS
ExecStop=/usr/local/bin/coda client stop-daemon

[Install]
WantedBy=default.target
```

I repeat this is relevant if the mine service is launched not under the user's root
I ask you to check and supplement the documentation, this is very important for validators

$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

$coda version
Commit [DIRTY]5493fe344b40b6e668315fb8db4aa7eef4f1963f on branch HEAD

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
