### ISSUE TITLE
Prometheus Coda_Network_peers returns 0

### ISSUE THREAD

**Issue by kobigurk** [MinaProtocol/mina#7851]
Sometimes, after restarting a node, the `Coda_Network_peers` metric is 0 and remains 0 (seemingly forever).

Example:
![image](https://user-images.githubusercontent.com/3520024/107273635-fcbee500-6a57-11eb-9886-5f367053dae7.png)
![image](https://user-images.githubusercontent.com/3520024/107273650-00eb0280-6a58-11eb-881e-d03d94a458f7.png)

I have a node currently up with this problem for debugging if helpful.

**Comment by garethtdavies** [comment]
I replicated this on a node that was working before a restart (shows around 09:10). Also works fine on another host. The only change was to modify peers.txt. It does not recover itself.

<img width="1908" alt="CleanShot 2021-02-10 at 10 22 29@2x" src="https://user-images.githubusercontent.com/135382/107553724-e618ab00-6b89-11eb-8520-22844dc23c66.png">

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
