### ISSUE TITLE
Incorrect block height. Synchronized 4 days 27 peers

### ISSUE THREAD

**Issue by Igor-Tselkovskiy** [MinaProtocol/mina#7855]
Incorrect block height, if I had not checked the height I would never have found out about it. Currently the correct height is 5780

Global number of accounts:                     3994
Block height:                                  5487
Max observed block height:                     5487
Local uptime:                                  4d1h11m51s
Ledger Merkle root:                            jwwYmD8CEXeTkzAw1REzNQ5C3agqMvPfWi6qCWi5oc4Drf8raAk
Protocol state hash:                           3NLiNPkZnsSy7VzNwEnrctg5isyM7JkpxGqZoEdnCYjMYUWtHqqX
Chain id:                                      d33c99867950152ed7185074629b558a79b792a23a505202d6b7c3b7419ebcf5
Git SHA-1:                                     [DIRTY]5493fe344b40b6e668315fb8db4aa7eef4f1963f
Configuration directory:                       /root/.coda-config
Peers:                                         27
User_commands sent:                            0
SNARK worker:                                  None
SNARK work fee:                                25000000
Sync status:                                   Synced
Catchup status:
        To build breadcrumb:           0
        To initial validate:           0
        Finished:                      365
        To verify:                     0
        To download:                   0
        Waiting for parent to finish:  0

Block producers running:                       1 (B62qj7rPP3jr67BwfC7vzfT9R5ivKjx7eg2j6vzg9V6S6oYBm2ovHuU)
Best tip consensus time:                       epoch=0, slot=1862
Best tip global slot (across all hard-forks):  18640
Next block will be produced in:                in 4.557d
Consensus time now:                            epoch=0, slot=1993
Consensus mechanism:                           proof_of_stake
Consensus configuration:
        Delta:                     0
        k:                         290
        Slots per epoch:           7140
        Slot duration:             3m
        Epoch duration:            14d21h
        Chain start timestamp:     2021-02-04 20:00:00.000000Z
        Acceptable network delay:  3m

Addresses and ports:
        External IP:    87.255.8.92
        Bind IP:        0.0.0.0
        Libp2p PeerID:  12D3KooWSA5EEpmrAjfunSNYeRjSVMjJSxus9uu2NhS65f44AqMT
        Libp2p port:    8302
        Client port:    8301

**Comment by Igor-Tselkovskiy** [comment]
https://drive.google.com/file/d/14axnT99VW7iongyYsQnwIlCIe9PdSW8_/view?usp=sharing

**Comment by lesterli** [comment]
Already had the same problem #7749

**Comment by GialloRossi10** [comment]
Have the same problem couple of times and I see this issue on a regular basis in qa-task-force
