### ISSUE TITLE
Shutdown before Coda instance was created, not saving a visualization

### ISSUE THREAD

**Issue by olton** [MinaProtocol/mina#7860]
Node constantly crashes with this error. A crash
[coda_crash_report_2021-02-09_13-24-00.495330.tar.gz](https://github.com/MinaProtocol/mina/files/5951613/coda_crash_report_2021-02-09_13-24-00.495330.tar.gz)
 report in attach

**Comment by leafyshark** [comment]
Same issue - was this resolved?

**Comment by samuelarogbonlo** [comment]
@olton I have the same issue, how did you resolve yours?

**Comment by olton** [comment]
now there is no such error, perhaps it rarely happens, but I stopped paying attention.

**Comment by samuelarogbonlo** [comment]
Could you check this issue here [https://github.com/MinaProtocol/mina/issues/9273](https://github.com/MinaProtocol/mina/issues/9273)? Thanks!

**Comment by deepthiskumar** [comment]
The error is `Couldn't determine our IP from the internet, use -external-ip flag`
`Failed to query our own IP from $provider: $exn","metadata":{"exn":"(monitor.ml.Error\n  (\"Failed to resolve Uri\" ((scheme (http)) (host (api.ipify.org))))\n  (\"Raised at file \\\"src/error.ml\\\" (inlined), line 9, characters 14-30\"\n    \"Called from file \\\"src/or_error.ml\\\", line 72, characters 17-32\"\n    \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"))","pid":15095,"provider":"http://api.ipify.org"}}

@olton Might have something to do with your network configuration. Are you running you node behind a NAT? 
try passing your IP explicitly using the flag `--external-ip`
`

**Comment by olton** [comment]
@deepthiskumar thanks, no longer relevant, the error does not occur anymore

**Comment by shimkiv** [comment]
Closing since no longer relevant by author's words.
