### ISSUE TITLE
Archive node metrics

### ISSUE THREAD

**Issue by mnguyen-io** [MinaProtocol/mina#7863]
Can we have metrics to monitor the health of archive nodes?

- Missing blocks
- Missing Parent_id/hash (any crucial DB stuff in general)
- Errors inserting/processing entries

**Comment by deepthiskumar** [comment]
There is a tool `missing_block_auditor` to check for missing blocks  in the archive db and errors captured in logs. The daemon logs should have error logs if it fails to send a block and archive process logs in stout/stderr. We also have a usage doc in progress for archive-node redundancy  [here](https://github.com/MinaProtocol/mina/pull/7864)

**Comment by nholland94** [comment]
Addressed in https://github.com/MinaProtocol/mina/pull/8158
