### ISSUE TITLE
Interesting fork story - outdated main fork?

### ISSUE THREAD

**Issue by podlodkin** [MinaProtocol/mina#7882]
Hi! 

My discord ID: svd#2372

Docker image: minaprotocol/mina-daemon-baked:0.3.0-5493fe3-encore-6fe6a3e

Interesting "forks" story. Yesterday I had mined block Nr. 5868. It was green. After sometime it's became to red. I checked mined block sequnce. My block was mined 15 minutes before green 5868.
The next red block 5869 was mined before green 5686 (see image) too (!). And, ooough, there is 5578(!) red block beetween 5868 red and 5889 red blocks. In mainnet it's means we need minumum 11 confirmation (>60min) to accept deposit in exchange. It's not a major bug, but no so good.

Logs: https://bit.ly/3d3hBnR

![image](https://user-images.githubusercontent.com/23024800/107507449-41f22c80-6ba8-11eb-819b-13173409ce0e.png)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
