### ISSUE TITLE
GraphQL blockchainState utcDate returns wrong time

### ISSUE THREAD

**Issue by omerzach** [MinaProtocol/mina#7895]
```
genesisBlock { protocolState { blockchainState { utcDate } } }
```
returns time relative to genesis block rather than relative to January 1, 1970, despite the description clearly stating it should be UTC date.

```
utcDate (stringified Unix time - number of milliseconds since January 1, 1970). Time offsets are adjusted to reflect true wall-clock time instead of genesis time.
```

This is causing Rosetta `block/` endpoints to return incorrect dates.

**Comment by omerzach** [comment]
CC @bkase

**Comment by omerzach** [comment]
Against testnet:
```
query MyQuery { 
    genesisBlock {
      protocolState {
        blockchainState {
          date
          utcDate
        }
      }
    }
}
```
returns
```
{
  "data": {
    "genesisBlock": {
      "protocolState": {
        "blockchainState": {
          "date": "0",
          "utcDate": "0"
        }
      }
    }
  }
}
```

And against a local run of `(cd src/app/rosetta && ./start.sh FOREVER)` it returns:

{
  "data": {
    "genesisBlock": {
      "protocolState": {
        "blockchainState": {
          "date": "0",
          "utcDate": "64194879000" // Thu Jan 13 18:54:39 EST 1972
        }
      }
    }
  }
}

`./start.sh` includes:
```
genesis_time=$(date -d '2019-01-30 20:00:00.000000Z' '+%s')
now_time=$(date +%s)
export CODA_TIME_OFFSET=$(( $now_time - $genesis_time ))
```

**Comment by garethtdavies** [comment]
This is a duplicate of #6700

**Comment by omerzach** [comment]
Ah thanks @garethtdavies, I'll close this one
