### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by figitaki** [MinaProtocol/mina#7897]
## Summary
[summary]: #summary

This proposal outlines a new organization structure for our user facing documentation, as well as an updated process for generating the documentation site. This new implementation will allow us to move the documentation into the main repository and support embedding the static content into an external website.

## Motivation
[motivation]: #motivation

After more than a year of running testnets and iterating on the protocol, our documentation has gotten disorganized. Additionally we are in the process of migrating our website infrastructure to Wordpress which requires us to change the way we build our documentation site. After surveying the user-base and conducting an audit of our current documentation, we've come up with the following proposal.

## Detailed design
[detailed-design]: #detailed-design

This proposal involves two components, a content re-organization and migrating the infrastructure we use to build and deploy the documentation site.

### Content Reorganization

The current documentation has a large number of pages at the top level of the navigation which leads to a confusing user experience as users begin exploring more advanced topics. This problem continues to get worse as we add new pages since there isn't a clear organization strategy for adding new documentation.

The new documentation site would be organized into the following categories:

1. Quick Start (Connecting to the network)
2. Advanced Node Operator (Technical walkthrough of protocol features and tools)
3. Developer tooling (GraphQL API, CLI Reference, Archive Schema, tooling documentation)
4. Protocol Architecture

To see a full overview of the proposed organization please see this document: https://www.notion.so/minaprotocol/Documentation-Manifesto-e8cb31aa6e66438da62943a226e6926d

### Documentation Site Generation

Our documentation currently lives in a seperate repository from the protocol code. This creates a seperation between the workflows for deploying a new version of the daemon and a new version of the documentation. To solve this problem we will move the documentation out of the github.com/mina/website repository into the main repository under the `docs/` subfolder.

Another issue we will encounter as the protocol matures, is supporting multiple versions of the daemon. Once we have multiple versions in the wild and we need to make major or breaking changes, we'll need to keep the old versions of the documentation accessible for those who are unable or do not wish to upgrade to the latest version.

Currently we're using a custom built markdown based site generator. This process has served us well since it's based on MDX we can have complex components in the documentation, and community members can easily edit the content of the documentation using GitHub. This tool has served us well over the past few years but there's a few areas in which it could be improved: 

* Multi-version support
* SEO
* Search

To address these issues while maintaining the feature-set of our current solution, we will migrate onto [Gatsby + Gitbook](https://github.com/hasura/gatsby-gitbook-starter).

## Drawbacks
[drawbacks]: #drawbacks

One potential issue with this new process would be tying the documentation to our regular release cycle. While this solves more issues than it creates, this does make it tougher to make minor tweaks to the documentation in between releases. The obvious solution to this though is to have shorter release cycles.

## Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

* Due to our SEO requirements, we will need to keep the documentation as a sub-site under the main domain. This presents specific requirements that are best fulfilled by using a static site generator such as gatsby.
* One altertanative we considered was keeping our custom built documentation generation tooling and simply moving the content over into the new site. However having to maintain this tooling and add the functionality to bring us to parity with Gitbook would be more effort than it's worth.

## Unresolved questions
[unresolved-questions]: #unresolved-questions

* Will this design satisfy the SEO requirements and be compatible with the new site architecture?
* How will we ensure the documentation stays up-to-date with each release? (Who's responsibility)

**Comment by garethtdavies** [comment]
> To see a full overview of the proposed organization please see this document: https://www.notion.so/minaprotocol/Documentation-Manifesto-e8cb31aa6e66438da62943a226e6926d

Is it possible for this to be public?

**Comment by aneesharaines** [comment]
@figitaki some comments feedback:
- Can the requirements be captured here as well?  I would think they are (1) to be able to be consumed as a subsite in WP (2) the community can easily contribute (3) improved ability for users to be able to find the right content quickly.   But it would be good to be explicit
- Can you add more information on how you are proposing we implement the versioning and search using gitbook + gatsby?  
- Can more info be added about how this will be integrated with the WP site?  What would be the flow from taking the merged changes and the generated sub site? 
-  We need to define an explicit process for updating docs, in review, but I think its really important that we not be restricted to docs changes only during a protocol release
- Where will UI components of the subsite live/be owned?

**Comment by aneesharaines** [comment]
@figitaki - to add the proposed docs including how it works with the branching structure

**Comment by figitaki** [comment]
Versioning plan: https://www.notion.so/minaprotocol/Documentation-Versioning-e56b2241f52f4d7090bde449862decf8
Translation plan: https://www.notion.so/minaprotocol/Documentation-Translation-24047f44a73842299d5fc175ab54f450

**Comment by emberian** [comment]
Looks done!
