### ISSUE TITLE
GrahQL schema - Validation errors

### ISSUE THREAD

**Issue by olton** [MinaProtocol/mina#7906]
Hi! The GraphQL schema contains two types `mutation` and `protocolStateProof` without a field definition. The lack of field definitions in these types causes a validation error: **type ... must define one or more fields**.

**Comment by garethtdavies** [comment]
Also #6317

**Comment by psteckler** [comment]
How are you trying to validate the schema?

**Comment by psteckler** [comment]
That's apparently generated by this bit of OCaml code:
```ocaml
  let protocol_state_proof : (Mina_lib.t, Proof.t option) typ =
    (* TODO *)
    obj "protocolStateProof" ~fields:(fun _ -> [])
```

**Comment by olton** [comment]
The error showed up when I'm trying to start your original proxy. The problem could not be solved, so I had to write my own proxy server with a special hack in the GraphQL.js validator.

Repo for my proxy https://github.com/olton/mina-graphql-proxy.

Thank you.
