### ISSUE TITLE
protocolStateProof breaks the Graphql schema

### ISSUE THREAD

**Issue by nerdvibe** [MinaProtocol/mina#7909]
Working with the Mina Node GraphQL API, I found out a `todo` in the code that is generating an invalid GraphQL schema. 

The type [protocolStateProof](https://minaprotocol.com/graphql-docs/protocolstateproof.doc.html) breaks the GraphQL schema validation because is an empty type, which is not a valid definition. 
Some clients might ignore the issue but stricter clients will fail.

Code definition:
https://github.com/MinaProtocol/mina/blob/22c1608ba40b135e256a0b368ba7e4a8f320b5ae/src/lib/mina_graphql/mina_graphql.ml#L1378

From the [GraphQL specs](http://spec.graphql.org/June2018/#sec-Objects)
> An Object type must define one or more fields.

## Suggestion:
If you don't want to consider deleting it or commenting it, then assign a dummy definition to it like the following:
```
type protocolStateProof {
  _ : Boolean
}
```

(carbonara from Discord)

**Comment by garethtdavies** [comment]
See #7906 and #6137

**Comment by mrmr1993** [comment]
This was fixed in #7941. Closing.
