### ISSUE TITLE
Archive node redundancy in mainNet infra

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#7917]

**Comment by deepthiskumar** [comment]
I deployed a network where multiple archive processes are connected to the same database ( a few different combination- 2 archive processes and 1 db, 3 archive processes and 1 db, 3 archive processes and 2 DBs). The blocks are getting added. Will let it run for a couple of days and see if there are any issues. 

The multi-daemon-single-archive configuration seems to be not working. Specified the following two variables in block producer config. 

```
        enableArchive          = true
        archiveAddress         = "archive-1:3086"
```
(full config is https://github.com/MinaProtocol/mina/blob/test/archive-node-redundancy/automation/terraform/testnets/archive-test/main.tf)

But I don't see the --archive-address` flag in the daemon command


```
     - args:
        - daemon
        - -log-level
        - Info
        - -log-json
        - -enable-peer-exchange
        - "true"
        - -discovery-keypair
        - /root/libp2p-keys/key
        - -peer
        - /dns4/fish-block-producer-1.archive-test/tcp/10501/p2p/12D3KooWKgKQuGcNGzt8kUv996Fj7PNxudZ5xztpr25vExJ7J8QH
        - -peer
        - /dns4/seed-1.archive-test/tcp/10000/p2p/12D3KooWCG4zy8uNL35K3mZREPeXBnAQ4b9TDfSdL1Vm3GSYMKgm
        - -peer
        - /dns4/whale-block-producer-1.archive-test/tcp/10502/p2p/12D3KooWRsGebMHvLB2UvBfoQSxhnDbALsi2qgeo31mtyrgyNHpZ
        - -peer
        - /dns4/whale-block-producer-2.archive-test/tcp/10503/p2p/12D3KooWEsbmonniTta587iwMzkSDzwQvNQhv84kgKvLtJYp5vzk
        - -peer
        - /dns4/whale-block-producer-3.archive-test/tcp/10504/p2p/12D3KooWCqP5784VScxH6AZuyJfYW2o3QcQWStLSVSwsqHrH4yZR
        - -peer
        - /dns4/whale-block-producer-4.archive-test/tcp/10505/p2p/12D3KooWB2fzjtmsKECB1MBnNg1q9iFNdhH9qjht1gsSWEjndKnq
        - -peer
        - /dns4/whale-block-producer-5.archive-test/tcp/10506/p2p/12D3KooWPtdMNBAnj3JACvfsxGBCR4FKpwpK2M9QWX826oh2Z14o
        - -config-directory
        - /root/.coda-config
        - -client-port
        - $(DAEMON_CLIENT_PORT)
        - -rest-port
        - $(DAEMON_REST_PORT)
        - -insecure-rest-server
        - -external-port
        - $(DAEMON_EXTERNAL_PORT)
        - -metrics-port
        - $(DAEMON_METRICS_PORT)
        - -block-producer-key
        - /root/wallet-keys/key
        - -config-file
        - /config/daemon.json
        - -generate-genesis-proof
        - "true" 
   ```

All my changes are in this PR https://github.com/MinaProtocol/mina/pull/7973

**Comment by 0x0I** [comment]
As mentioned offline, the chart changes are only local and haven't been released yet (as they are still under test). To test, there is a flag in *helm.tf*, `use_local_charts`, which directs the terraform to  launch the local repo chart versions: https://github.com/MinaProtocol/mina/pull/7781/files#diff-750220162b9a640a644eadd529bb0f000f97899550a57db76582097fa3f61f29R9.

**Comment by deepthiskumar** [comment]
tested this and we also have archive node redundancy configured for mainnet.
