### ISSUE TITLE
More robust vendoring

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#796]
https://github.com/o1-labs/nanobit/pull/794#issuecomment-424895430 mentions some stuff. 

Right now, if we update one of our "opam vendored deps" (as opposed to the "jbuild vendored deps"), there is a manual step where you need to update your opam pins. There's no way right now to know that this needs to be done, so you'll just get mysterious build failures.

**Comment by shimkiv** [comment]
Hey @mrmr1993 can you please take a look.
