### ISSUE TITLE
Stop crashing the daemon when it is offline for 15-mins?

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#7970]

**Comment by jrwashburn** [comment]
For things like this, changing behavior that is understood has a high likelihood of having been integrated into operations. Perhaps a comment period longer than a few hours would be useful for the community. This should rarely be an issue. It was exciting last night, but how often are you starting a new network from scratch. Why stay up (relatively) quietly when the node is not seeing any traffic?

**Comment by riokresnawan** [comment]
amazing
