### ISSUE TITLE
Coda crashes during installation on Mac+Docker 

### ISSUE THREAD

**Issue by gbaci** [MinaProtocol/mina#7981]
[2021-02-19_14-50-40.tar.gz](https://github.com/MinaProtocol/mina/files/6010846/2021-02-19_14-50-40.tar.gz)

Something keeps crashing while installing the Mina image and container on docker. Logs attached.

**Comment by gnosed** [comment]
I guess we can close this issue. The daemon was crashing because of a lack of memory. The docker has a limit of 2 GB RAM and the computer has 8 GB.
