### ISSUE TITLE
Coda 2 Mina - Infra changes to support

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#7989]

**Comment by yourbuddyconner** [comment]
List of places that need to be changed outside the monorepo that I am aware of: 
- Dockerhub org name `codaprotocol` -> `minaprotocol`
- Dockerhub repo names `coda-daemon` -> `mina-daemon`, `coda-archive` -> `mina-archive`
- Helm Chart Repo: `https://coda-charts.storage.googleapis.com` -> `https://mina-charts.storage.googleapis.com`

**Comment by yourbuddyconner** [comment]
related https://github.com/MinaProtocol/mina/issues/6280
