### ISSUE TITLE
mina-rosetta still requires archive node

### ISSUE THREAD

**Issue by jrwashburn** [MinaProtocol/mina#8001]
expected result: mina-rosetta works without archive-uri for certain calls.

actual result: mina-rosetta starts up okay without archive-uri 
(e.g. mina-rosetta --port 3087 --graphql-uri http://127.0.0.1:3085/graphql) 
however, calls to network list endpoint return an error:
http://127.0.0.1:3087/network/list

{"code":1,"message":"SQL failure","description":"We encountered a SQL failure.","retriable":false,"details":{"body":["Sql","No archive URI set"],"error":"No archive URI set"}}

**Comment by omerzach** [comment]
Currently only `construction/*` endpoints work without `archive-uri` set. I think there was a miscommunication or misunderstanding somewhere on what we need runnable without an archive node running. I'll look into what it takes to support `network/list` and other endpoints without `archive-uri` set though right away.
