### ISSUE TITLE
mina-rosetta network/list endpoint returns code 2 json parse error

### ISSUE THREAD

**Issue by jrwashburn** [MinaProtocol/mina#8002]
Not sure what expected result is - never run this before. But the ledger wallet wants something useful back that it is not getting.

mina-rosetta endpoint http://127.0.0.1/network/list
returns:
{"code":2,"message":"JSON parse error","description":"We encountered an error while parsing JSON.","retriable":false,"details":{"body":["Json_parse","Metadata_request.t"],"error":"Metadata_request.t","extra":"Request"}}

**Comment by omerzach** [comment]
Hey, thanks for reporting your issue. Can you share your full command to that endpoint (or more context on how it's being called)? I think the issue may be that Rosetta requires you to provide `{}` as the request body even though no body parameters are required.

https://www.rosetta-api.org/docs/NetworkApi.html

```
omer@Omers-MacBook-Pro mina % curl --header "Content-Type: application/json" --request POST http://localhost:3087/network/list
{"code":2,"message":"JSON parse error","description":"We encountered an error while parsing JSON.","retriable":false,"details":{"body":["Json_parse","Metadata_request.t"],"error":"Metadata_request.t","extra":"Request"}}


omer@Omers-MacBook-Pro mina % curl --header "Content-Type: application/json" --request POST --data '{}' http://localhost:3087/network/list
{"network_identifiers":[{"blockchain":"coda","network":"debug"}]}
```

**Comment by jrwashburn** [comment]
I probably should have closed this; apologies. This was me trying to figure out why ledger was returning ("Failed to get network identifiers") and snooping the ledger-app-mina code quickly, seeing this on line 136 
network_resp = requests.post(MINA_URL + '/network/list' 
and then just trying to hit the endpoint directly. 

It turns out that with the correct parameters, that is not an actual problem, and I got ledger working yesterday afternoon. I should have come back to close sorry!

**Comment by omerzach** [comment]
No worries! Saw there was discussion in Discord yesterday but didn't have time then to look closely.
