### ISSUE TITLE
☠  Coda Daemon crashed.

### ISSUE THREAD

**Issue by zl-8888** [MinaProtocol/mina#8016]
2021-02-23 14:55:03 UTC [Warn] Shutdown before Coda instance was created, not saving a visualization

  ☠  Coda Daemon crashed.
   The Coda Protocol developers would like to know why!

    Please:
      Open an issue:
        <https://github.com/CodaProtocol/coda/issues/new>

      Briefly describe what you were doing and attach the crash report /root/.coda-config/coda_crash_report_2021-02-23_14-55-03.393135.tar.gz

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
