### ISSUE TITLE
shut down old networks

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#8061]
Shutdown testworld, encore and zenith. Leave the bug-net, I doubt anyone is using it but also its not really in our way so let it run for hackerone.

**Comment by 0x0I** [comment]
Testnets targeted above (+ others identified as CRUFT) have been deprecated/cleaned up.

@bijanshahrokhi *bug-net* was also destroyed though we don't believe it's had much if any traffic or public activity. Ping me or #reliability-engineering if it makes sense to spin up another.
