### ISSUE TITLE
Alert - logs appear in stack driver

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#8062]
Ensure testnet component logs are ingested into Stackdriver.
 
**Note:**
Stackdriver's Grafana [datasource.](https://grafana.com/grafana/plugins/stackdriver) which provides a base set of metrics re: Stackdriver's GCP logging ingestion profile, is installed by default with our Grafanacloud service. There also already exists a `Stackdriver-Prod` datasource setup for the existing O(1) Lab GCP Project (**ID #:** o1labs-192920) so it makes sense to piggyback this prior work and integrate with the developed solution.

**Comment by 0x0I** [comment]
Looks like we may be able to base an alert off something like the stackdriver metric [Logging : Log bytes ingested](https://o1testnet.grafana.net/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Stackdriver-Prod%22,%7B%22metricQuery%22:%7B%22editorMode%22:%22visual%22,%22projectName%22:%22o1labs-192920%22,%22metricType%22:%22logging.googleapis.com%2Fbilling%2Fbytes_ingested%22,%22metricKind%22:%22DELTA%22,%22valueType%22:%22INT64%22,%22unit%22:%22By%22,%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22alignmentPeriod%22:%22cloud-monitoring-auto%22,%22perSeriesAligner%22:%22ALIGN_DELTA%22,%22groupBys%22:%5B%5D,%22filters%22:%5B%22resource.type%22,%22%3D%22,%22global%22,%22AND%22,%22metric.label.resource_type%22,%22%3D%22,%22k8s_pod%22%5D,%22aliasBy%22:%22%22,%22query%22:%22%22%7D,%22queryType%22:%22metrics%22,%22sloQuery%22:%7B%22projectName%22:%22o1labs-192920%22,%22alignmentPeriod%22:%22cloud-monitoring-auto%22,%22aliasBy%22:%22%22,%22selectorName%22:%22select_slo_health%22,%22serviceId%22:%22%22,%22sloId%22:%22%22%7D,%22hide%22:false%7D%5D) along with the `resource_type` label constrained to *k8s_pod|container* to verify pods are emitting logs.
