### ISSUE TITLE
GraphQL: Add command type to fee transfer

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#8072]
The archive node has a `type` for internal commands. This is useful in determining how much a block producer has actually received as the `fee_transfer_via_coinbase` needs to be subtracted from any coinbase and fee transfer received.

In GraphQL the feeTransfer only includes the amount and recipient i.e.

```
feeTransfer {
        fee
        recipient
      }
```

It would be helpful to additionally include the type to identify the `fee_transfer_via_coinbase` field i.e.

```
feeTransfer {
        fee
        recipient
        type
      }
```

**Comment by deepthiskumar** [comment]
Would it be ok if the `coinbase` field is expanded to include the amount and the fee transfer instead of the new `type` field? That way when there are two coinbase transactions it is easy to disambiguate the fee transfers. It might not be needed for a simple balance deduction but it is nice to have that separation.

**Comment by garethtdavies** [comment]
@deepthiskumar That would be perfect. For clarity could you provide an example - so we currently have:

```
"transactions" : {
        "coinbase" : 720000000000
```

Are you thinking of something like this (numbers are arbitrary but coinbase would sum to the block coinbase)? 

```
"transactions" : [{
    "coinbase": 200000000000,
    "fee_transfer": 101010
  },
  {
    "coinbase": 520000000000,
    "fee_transfer": 1010010
  }
]
```

**Comment by deepthiskumar** [comment]
Fee transfer would be similar to what it is now. So something like this-
```
"transactions": {
  "coinbase": [{
    "amount": 200000000000,
    "fee_transfer":[{
       "fee":101010,
       "recipient":<public key>
    }]
  },
  {
    "amount": 520000000000,
    "fee_transfer":[]
  }] ```

using a list to represent 0 or 1 fee transfer in a coinbase transaction

**Comment by garethtdavies** [comment]
This would work for me. It would also break quite a few things so ideally there'd be a bit of a chance to test this and obviously I have no idea how others are currently using this field.

**Comment by deepthiskumar** [comment]
@bkase would communicating this change before releasing it be enough to make the breaking change? Given this is in graphQL it seems like a better way to encode fee transfers than specify a type like the way it is done in archive database. This way we are also being explicit about the fact that there can be two coinbase transactions. But if breaking changes are a big no-no then I can just add the type. 

@garethtdavies Regarding coinbase amount calculation, maybe some docs on that would help?

**Comment by bkase** [comment]
@deepthiskumar we shouldn't make a backward-incompatible change, but you can create a new field name to workaround that if we want this new API too. We may as well add the type there also since we need to keep it for backwards compatibility

**Comment by deepthiskumar** [comment]
Added just the fee transfer type for now #8112

**Comment by deepthiskumar** [comment]
#8113 merged
