### ISSUE TITLE
Bug in Rosetta construction/parse unsigned tx checking for minimum fee

### ISSUE THREAD

**Issue by jspada** [MinaProtocol/mina#8084]
When seding a transaction `mina_ledger_wallet` obtains the default fee and current nonce from the Rosetta `construction/metadata` interface.  Currently Rosetta is responding that the default fee is 1 Mina.

The `mina_ledger_wallet` command allows the user to chose their own fee, thus, overriding the default fee.

Later in the Rosetta protocol, the transaction is validated prior to sending using the `construction/parse` interface.  According to the Rosetta protocol the tx is validated at two stages: _after the unsigned transaction is formed_ and after _the signed transaction is constructed_ (before sending).

If the user overrides the default fee to, for example, 0.0001 then the `construction/parse` on the unsigned transaction returns success.

However, on the signed transaction it returns "Invalid user command. Fee 0.0001 is less than the minimum fee, 0.001."

This is quite late in the protocol.  (For the Ledger, this happens after the user has waited over a minute for signing to complete! 👀) 

Rosetta `construction/parse` should catch the minimum fee error earlier in the game, ie. on the unsigned transaction.

```
$ mina version
Commit fd3980820fb82c7355af49462ffefe6718800b77 on branch master
```

**Comment by jspada** [comment]
As discussed. I've created a separate ticket for fixing the defauts (#8100)

**Comment by jspada** [comment]
Investigated and found that

`construction/parse` (parse unsigned tx)
- Only validates transaction JSON
         (Does not catch invalid fees, unknown source accounts, etc)

`construction/parse` (parse signed tx)
* Only validates signed transactions fully
  * Uses GraphQL validatePayment
  * Catches invalid fees, unknown source accounts, etc
* Does not work for unsigned transactions (see above)
  * GraphQL validatePayment requires a signature field
  * Does not validate delegation transactions
    * GraphQL doesn't have a validateDelegation query supported AFAIK
    
Thus, the changes required are more significant than we first thought and Risk is probably not low.  We should probably not do this one as a hotfix.

**Comment by robinbb** [comment]
@jspada Would you like to offload this Rosetta-related issue to the Mina Foundation engineering team?

**Comment by kantp** [comment]
I spoke to Joseph. We're taking this on, but it's not a critical issue, merely a suboptimal situation. It's not a blocker for the hardfork, so it's not top priority.

**Comment by ejMina226** [comment]
We're having issues reproducing the bug. This is because we are unsure of how to run the construction tests.

**Comment by ejMina226** [comment]
Now looking to run our own commands against the construction api to inspect the output.

**Comment by robinbb** [comment]
@ejMina226 It would be nice to understand what you perceive as next steps for this task, and whether you intend to take them.

**Comment by ejMina226** [comment]
Hi @robinbb . It's not clear to me what the expected behaviour should be, and I will need to discuss this with the team as my experience with Rosetta is limited. We are, at least, getting consistent behaviour now. The `parse` endpoint returns the same response regardless if it is a signed or unsigned transaction, which is good. However, this ticket mentions that at some point (2 years ago) the endpoint had the functionality to reject a transaction based on an inaccurate fee, which I'm no longer seeing. It is possible that I am not reproducing the workflow in the manner expected; however, it is not clear from the online documentation that the parse endpoint should even be able to do what the ticket is describing as it's just meant to be a "sanity check".

**Comment by ejMina226** [comment]
I see two paths forward for the bug:
- The original author of the ticket may have confused endpoints. The `combine` endpoint gives the described behaviour, but not the `parse` one. In this case, we can close the ticket.
- The endpoint has lost functionality that needs to be re-introduced. However, from the online documentation, this does not look to be the case as I don't think the `parse` endpoint should reject a transaction. It's just meant to be a sanity-check and confirm the details of the transaction that have been encoded in payload.

**Comment by ejMina226** [comment]
We've decided on the second option. The functionality looks to have been lost in the endpoint and we will put in a guard and a check that the included fee is not less than the minimum fee.
