### ISSUE TITLE
Missing -generate-genesis-proof flag throws an ugly error

### ISSUE THREAD

**Issue by Julian-dev28** [MinaProtocol/mina#8093]
Crash_log 

{"OS_type":"Unix","Release":"5.4.0-1037-gcp","Machine":"x86_64","Sys_name":"Linux","Exception":{"commit_id":"fd3980820fb82c7355af49462ffefe6718800b77","sexp":["monitor.ml.Error","No genesis proof file was found and not allowed to generate a new genesis proof",["Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30","Called from file \"src/app/cli/src/mina.ml\", line 653, characters 12-27","Called from file \"src/deferred1.ml\", line 17, characters 40-45","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47","Caught by monitor coda"]],"backtrace":["Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30","Called from file \"src/app/cli/src/mina.ml\", line 653, characters 12-27","Called from file \"src/deferred1.ml\", line 17, characters 40-45","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47"]},"Command":"Command: (mina daemon)","Coda_branch":"master","Coda_commit":"fd3980820fb82c7355af49462ffefe6718800b77"}
~

**Comment by mrmr1993** [comment]
@Julian-dev28 looks like you haven't passed the `--generate-genesis-proof true` flag, can you try again using that?

**Comment by Julian-dev28** [comment]
Hello mrmr1993

Thank you for the solution and sorry for the late reply. The CLI is throwing the error: -generate-genesis-proof: command not found

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
