### ISSUE TITLE
Node status, confirm it is working. 

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#8103]

**Comment by psteckler** [comment]
#8131 may fix failures in the watchdog.

**Comment by aneesharaines** [comment]
@ghost-not-in-the-shell - going to try to test this via making the call directly to the daemon

**Comment by aneesharaines** [comment]
Going to test the partial fix on dev net, but doesn't seem to work with more that 200 peers, @nholland94 suggests there's interaction with peer trimming logic here
