### ISSUE TITLE
New reports of bootstrap/catchup failing with 500+ peers

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#8106]
User `goginn[Twitch]` has encountered crashes during bootstrap with a very high peer count, similar what `Boston Mike` reported during Zenith. User `akishino` has reported running into the same thing during both networks, and proposed a workaround by limiting their initial peers list and using the flag `--isolate-network true` to prevent peer-exchange.

akishino's complete workaround: 
```
For me, I dumped the peers using `mina advanced get-peers > ~/manualPeers.txt.` At the time there were too many peers in that file, so I picked a handful, and removed a majority of them. Once the daemon was relaunched with `--isolate-network true`, I used:
`cat /home/mina/manualPeers.txt | xargs -I % mina advanced add-peers %` which adds each peer in that file.
```

goginn's hardware: `AMD Ryzen 7 PRO 2700 Eight-Core Processor(8 CORE), RAM 16GB, SSD 120GB`
likely physical hardware on a home network, running from the debian package on ubuntu
if I remember correctly this is effectively identical to Boston Mike's node from zenith

Some Screenshots from goginn's node:

![](https://cdn.discordapp.com/attachments/746316198806814760/816448985048547378/2021-03-03_04-16-06.png)

![](https://cdn.discordapp.com/attachments/746316198806814760/816451926308814878/2021-03-03_04-28-09.png)

**Comment by nano-max** [comment]
reporting the same issue.
trying to connect to "final final 2", but the node stays in bootstrap with 4000+ peers.
hardware & OS: 8c, 32gb, running from the debian package on ubuntu.

[logs](https://github.com/MinaProtocol/mina/files/6096002/2021-03-06.logs.forever.bootstrap.with.many.peers.txt)
[mina client status](https://github.com/MinaProtocol/mina/files/6096003/2021-03-06.mina.clients.tatus.-.forever.bootstrap.with.many.peers.txt)

**Comment by aneesharaines** [comment]
Could be fixed by the latest libp2p change

**Comment by aneesharaines** [comment]
@nholland94  - this is on at least one of our seed nodes...  is that enough to verify this works?
