### ISSUE TITLE
Feature: add coinbase receiver info to mina client status

### ISSUE THREAD

**Issue by gnosed** [MinaProtocol/mina#8125]
At the moment, there is no way to display the current coinbase receiver through the CLI.
It could be useful to see it by typing `mina client status`. It would allow to double check if it's set properly in the daemon and is active. e.g. under the "block producers running" field:

```bash
Block producers running:                       1 (<block_producer_pubkey>)
Coinbase receiver:                             <coinbase_receiver_pubkey>
Best tip consensus time:                       epoch=0, slot=2633
```

**Comment by mrmr1993** [comment]
This was done in #8127. Closing.
