### ISSUE TITLE
BUG: debug_level config constant misspelled

### ISSUE THREAD

**Issue by mobileink** [MinaProtocol/mina#8145]
Easy fix but I can't get to it immediately.

In [src/config/debug_level/all.mlh](https://github.com/MinaProtocol/mina/tree/master/src/config/debug_level/all.mlh) we have the singular:

`[%%define cache_exception true]`

In the other files (some and none) we have the plural:

`[%%define cache_exceptions false]`

**Comment by psteckler** [comment]
I'll create a PR.

**Comment by psteckler** [comment]
Fixed.
