### ISSUE TITLE
crash report 

### ISSUE THREAD

**Issue by EmreNOP** [MinaProtocol/mina#8149]
report attached. 
[coda_crash_report_2021-03-06_08-50-00.444248.tar.gz](https://github.com/MinaProtocol/mina/files/6095337/coda_crash_report_2021-03-06_08-50-00.444248.tar.gz)

Generating crash report
        exn: {
  "commit_id": "fd3980820fb82c7355af49462ffefe6718800b77",
  "sexp": [
    "monitor.ml.Error",
    [
      "Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference(\"dfd937db-6e59-3f36-e37c-baf8184a762a\", \"File \\\"src/lib/merkle_mask/maskable_merkle_tree.ml\\\", line 239, characters 37-44\")"
    ],
    [
      "Raised at file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 116, characters 10-57",
      "Called from file \"src/lib/merkle_mask/masking_merkle_tree.ml\" (inlined), line 131, characters 18-38",
      "Called from file \"src/lib/staged_ledger/staged_ledger.ml\", line 846, characters 45-68",
      "Called from file \"src/lib/staged_ledger/staged_ledger.ml\", line 1063, characters 6-235",
      "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 116, characters 10-57",
    "Called from file \"src/lib/merkle_mask/masking_merkle_tree.ml\" (inlined), line 131, characters 18-38",
    "Called from file \"src/lib/staged_ledger/staged_ledger.ml\", line 846, characters 45-68",
    "Called from file \"src/lib/staged_ledger/staged_ledger.ml\", line 1063, characters 6-235",
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}
Mina process exited with status code 1

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
