### ISSUE TITLE
GraphQL: Cannot identify failed transactions

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#8151]
I thought (incorrectly) on the current release it was not possible for a tx to fail but the archive node shows many instances of a failed tx with `Amount_insufficient_to_create_account`. The issue is there is no way of knowing the transaction has failed via GraphQL so as an example the explorer displays transactions that never actually completed e.g. https://minaexplorer.com/wallet/B62qkoJNnwHMEtLy9eWePAhXEWL2xyrKyDAv6iXiwcgGGDPgPPAeie4

<img width="636" alt="CleanShot 2021-03-06 at 18 34 29@2x" src="https://user-images.githubusercontent.com/135382/110227193-9b4d3300-7eaa-11eb-8f19-560c6214b375.png">

As a resolution, either add the status to GraphQL (this will be needed presumably later, as I had this issue with tokens) or check that the recipient account is in the ledger or if not the transfer amount is > account creation fee and fail before broadcasting.

<img width="1795" alt="CleanShot 2021-03-06 at 18 37 02@2x" src="https://user-images.githubusercontent.com/135382/110227224-f7b05280-7eaa-11eb-8953-0d3f98f76345.png">

**Comment by garethtdavies** [comment]
Also see https://github.com/MinaProtocol/mina/issues/5960

**Comment by psteckler** [comment]
Closing because #8192
