### ISSUE TITLE
FinalFinal2(1.0.0): stuck at lower block height again

### ISSUE THREAD

**Issue by lampardlb** [MinaProtocol/mina#8161]
current height 1474, observed height 1441. rejected-block and other files are attached below.
Screen shot:
<img width="1018" alt="Screenshot 2021-03-08 at 09 33 14" src="https://user-images.githubusercontent.com/1702296/110263343-639cd300-7ff1-11eb-8317-c85f1804bf8d.png">
Rejected blocks log:
[mina-rejected-blocks.log](https://github.com/MinaProtocol/mina/files/6098400/mina-rejected-blocks.log)
mina export log file:
https://1drv.ms/u/s!AlOGZ7BQqAI1iKliQsDFmJv2ZhHkdQ?e=o8giB3

**Comment by mrmr1993** [comment]
This is the same as #7555, closing in favour of that.
