### ISSUE TITLE
Can't sync my node without "--isolate-network true"

### ISSUE THREAD

**Issue by jetlag666** [MinaProtocol/mina#8165]
Hello I'm having a issue with my node not syncing without "isolate-network true" argument. Anyone else with this problem?

Current version: 06f3c5cdeb635b2564fcb2edac4f10db85b93c36 on branch master

I attached my logs to this post.
[mina.log](https://github.com/MinaProtocol/mina/files/6103466/mina.log)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
