### ISSUE TITLE
Bug: the daemon parameter --config-directory is not fully active

### ISSUE THREAD

**Issue by Comdex** [MinaProtocol/mina#8193]
After I use --config-directory to specify a new directory to start the daemon, I notice that when I use mina accounts import to import the wallet, the default folder .mina-config is also generated in the user directory. 
The imported wallet file is not placed in the configuration directory I specified, which leads to the fact that when I use mina accounts list, it shows no wallet.

**Comment by mrmr1993** [comment]
This is a consequence of issue #6110. PR #7282 has been proposed to fix it, but it's still pending review.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
