### ISSUE TITLE
Mina advanced command to convert rosetta-formatted transactions to format accepted by GraphQL without broadcasting

### ISSUE THREAD

**Issue by jbaumruk** [MinaProtocol/mina#8201]
To supplement #8167 and allow user to output converted transaction without broadcasting, as either an `--offline` type argument to `advanced send-rosetta-transactions` or as a separate command.

**Comment by mrmr1993** [comment]
I've opened #8202 to add a GraphQL command for this. Not sure that this warrants a dedicated `advanced` command if it will be used with GraphQL anyway, but I'll wait to hear what others think.

**Comment by jbaumruk** [comment]
Not sure what the difference would be in doing it as a GraphQL, but ideally would like to have it be functional completely offline to get a tx that could be fed into a GraphQL later without additional complication (e.g. https://minaexplorer.com/broadcast-tx).

**Comment by psteckler** [comment]
@mrmr1993 the input to `to_mina_signed` is in the format returned by `signRosettaTransaction` in the client SDK?

It would be easy enough to call `to_mina_signed` from the client SDK, and return the transaction in JSON format. That JSON is what you'd provide to GraphQL? Which query or mutation?

I think @bkase or @figitaki might have a better sense than me of how such a method would be used in practice.

**Comment by aneesharaines** [comment]
@psteckler  to add the underlying implementation and then product team can add the js wrapper needed

**Comment by psteckler** [comment]
@jbaumruk, we added this facility to the client SDK in #8324.

Can I close this issue?

**Comment by psteckler** [comment]
@jbaumruk Here's an example of what the client SDK returns:
```json
{"data":{"payload":{"common":{"fee":"0.01","fee_token":"1","fee_payer_pk":"B62qnzbXmRNo9q32n4SNu2mpB8e7FYYLH8NmaX6oFCBYjjQ8SbD7uzV","nonce":"0","valid_until":"4294967295","memo":"E4YM2vTHhWEg66xpj52JErHUBU4pZ1yageL4TVDDpTTSsv8mK6YaH"},"body":["Payment",{"source_pk":"B62qnzbXmRNo9q32n4SNu2mpB8e7FYYLH8NmaX6oFCBYjjQ8SbD7uzV","receiver_pk":"B62qnzbXmRNo9q32n4SNu2mpB8e7FYYLH8NmaX6oFCBYjjQ8SbD7uzV","token_id":"1","amount":"1000000000"}]},"signer":"B62qnzbXmRNo9q32n4SNu2mpB8e7FYYLH8NmaX6oFCBYjjQ8SbD7uzV","signature":"7mXNqSTyAoaXzxiKaCjmUMzTAGN9gMASnQDczrhYBDbu71kAxJDykxxquYy4pCsni127BLdm67Ru4XTScVzTpQt7RkPbGJPE"}}
```
Is that acceptable?

**Comment by jbaumruk** [comment]
@psteckler That's perfect, thanks! Closing.
