### ISSUE TITLE
Intg test: Consolidate integration tests for efficiency

### ISSUE THREAD

**Issue by QuiteStochastic** [MinaProtocol/mina#8210]
Collapse related integration tests into each other so that less integration tests are run, thereby saving resources.

Send payment test and pmt-timed acccts

block prod and bootstrap

**Comment by QuiteStochastic** [comment]
this ticket dependent on https://github.com/MinaProtocol/mina/issues/8220

**Comment by nholland94** [comment]
First round has been done as part of #8220 (landed in #8620). Still need to consolidate some of the remaining tests, mainly the transaction/payment tests.
