### ISSUE TITLE
Intg Test: Add Sections to the DSL

### ISSUE THREAD

**Issue by QuiteStochastic** [MinaProtocol/mina#8220]
Add a feature to the intg test DSL called a section, which is a sub-test of an integration test.  sections can be run in parallel so long as they don't conflict with each other to increase speed.

Then pretty-print the results of each section.

hard and soft errors are mapped to their own section.  each section can experience it's own hard errors, and the test as a whole will not progress past the point where the sections `join` together

using a section would look something like this
```

let%bind () = wait_for node_to_initialize in
let%bind () =
  section "send txns" (
    let%bind () = send_my_txn () in
    send_my_other_txn ())
in
...
```

the interface for the section in the DSL would look like this

```val section : string -> 'a Malleable_error.t -> 'a Mallebale_error.t```

**Comment by QuiteStochastic** [comment]
@nholland94 is actively working on this

**Comment by aneesharaines** [comment]
Mostly done just need to clean up the error reporting

**Comment by aneesharaines** [comment]
Pr is out just need to get 1 test passing
