### ISSUE TITLE
Coda Daemon crashed

### ISSUE THREAD

**Issue by nenashevdv** [MinaProtocol/mina#8228]
As I have re-launched my Mac (it off off due to travel), i have tried to check for the status of Mina at the SHH windows and got en error claiming it cannot reach Mina. 

After that I straight way tried to launch the daemon and it started doing various jobs, never theles it crashed. 

I have the impression I should have unlocked my account first. 

Below copy/pasting the report, as it was asked to let know developers about that crash. 

======

2021-03-12 08:53:43 UTC [Info] Setting current protocol version to "2.0.0" from compile-time config
2021-03-12 08:54:39 UTC [Info] Daemon started process of kind "Prover" with pid 10874
2021-03-12 08:54:39 UTC [Info] Daemon started process of kind "Verifier" with pid 11008
2021-03-12 08:54:39 UTC [Info] Registering async shutdown handler: "Close transition frontier, if exists"
2021-03-12 08:54:39 UTC [Info] libp2p peer ID this session is $peer_id
        peer_id: "12D3KooWGredUvZa861S331wF2DdmUbVERdLx18kk7USrGKiXGN6"
2021-03-12 08:54:39 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: {
  "commit_id": "06f3c5cdeb635b2564fcb2edac4f10db85b93c36",
  "sexp": [
    "monitor.ml.Error",
    [
      "Failed to connect to libp2p_helper process",
      "RPC #2 failed: \"internal RPC error error: failed to parse multiaddr \\\"<?xml version='1.0' encoding='UTF
-8'?><Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><Details>Bucket na
mes must be at least 3 characters in length, got 1: 's'</Details></Error>\\\": must begin with /\""
    ],
    [
      "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
      "Called from file \"src/lib/gossip_net/libp2p.ml\", line 144, characters 8-94",
      "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
    "Called from file \"src/lib/gossip_net/libp2p.ml\", line 144, characters 8-94",
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}
2021-03-12 08:54:39 UTC [Warn] Shutdown before Coda instance was created, not saving a visualization
  ☠  Coda Daemon crashed.
   The Coda Protocol developers would like to know why!
    Please:
      Open an issue:
        <https://github.com/CodaProtocol/coda/issues/new>
      Briefly describe what you were doing and attach the crash report /home/dmitry_nen/.mina-config/coda_crash_r
eport_2021-03-12_08-54-39.681312.tar.gz

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
