### ISSUE TITLE
Transaction paymentId / hash inconsistencies

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#8244]
There are a few inconsistencies between payment ids and transaction hashes between various tools. It would be nice if there was some consistency in the tooling for these. For example:

In GraphQL `transactionStatus` takes a payment id and not a hash
In GraphQL `pooledUserCommands` is filterable on hash but not payment id
If getting the `pooledUserCommands` via `mina advanced pooled-user-commands` there is only a payment id and no hash.

**Comment by mrmr1993** [comment]
#8293 added support for passing IDs to `pooledUserCommands`, to try to make these more consistent. Closing.
