### ISSUE TITLE
Hide containers that aren't running from grafana / combine container runs from the same pod

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#8272]
Containers in the same pod have distinct names, so
* a new container will distort the scale of the graph unhelpfully by showing 0 for all times before it was started
* a killed container will 'hang around' at its last produced value, giving the appearance of stalls

For example, currently on devnet2, we have 
* `whale-block-producer-2-5654ccfff-8kzst`
  - died at block height 2260, stuck at that value forever
* `whale-block-producer-2-5654ccfff-fsxc9`
  - started at block height 2262, all past values are 0

It would be better for usability if the containers could share the name of their metrics, or if the graphs would stop including data for metrics which aren't producing data when they stop producing data.

**Comment by aneesharaines** [comment]
The new simplified mainNet dashboard helps with this
