### ISSUE TITLE
Dumping staking ledger for mainNet

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#8278]
Need to setup a job that exports the current staking ledger every day

- [x] 1: finish #8468, Dockerfile entrypoint refactor to allow for the use of a single docker image that can be configured at runtime with environment variables to run various scripts and/or run the daemon with various initialization settings

- [x] 2: write out the script that needs to be run
- [x] 2.1: start the daemon, wait for daemon to come online and fully sync, run `mina ledger export staking-epoch-ledger` and `mina ledger export next-epoch-ledger`.  output these into files that include the hash obtained by `mina ledger hash --ledger-file <filename>`
- [x] 2.2: upload files to gcp cloud storage bucket `gs://mina-staking-ledgers`

- [x] 3: bake above script into mina daemon docker image, and configure it to be run 

- [x] 4: write the GKE cronjob yaml which uses the improved mina daemon image which is set to run the above script, and 
- [x] 4.1: apply it in the mainnet namespace using `kubectl apply -f mainnet-dump-staking-ledger-cronjob.yaml`

**Comment by aneesharaines** [comment]
@psteckler got the timing and it was no more than 1s, so it's fine.

**Comment by QuiteStochastic** [comment]
@aneesharaines where are we dumping this to? gcp cloud storage? aws s3?

**Comment by QuiteStochastic** [comment]
never mind andrew created a gcp cloud storage bucket, gs://mina-staking-ledgers
