### ISSUE TITLE
Fix monitoring update manual command for use on Macs

### ISSUE THREAD

**Issue by O1ahmad** [MinaProtocol/mina#8298]
Monitoring and alerting [guidelines](https://github.com/MinaProtocol/mina/blob/7b3c66cc491dc26844a46500200205394e14600b/automation/terraform/monitoring/README.md#update-alert-receivers) currenty only support installatation of the `cortextool` for Linux OSes. Considering operators may be running on Macs or Windows machines, remove this limitation and allow for independent install of the tool.

**Comment by mrmr1993** [comment]
No longer relevant, we don't support Mac or Windows currently.
