### ISSUE TITLE
Rosetta docker image build CI jobs fail on mina develop branch

### ISSUE THREAD

**Issue by 0x0I** [MinaProtocol/mina#8307]
Rosetta image builds (basic and dev/dune profiles) are failing consistently in CI with the following error ([example](https://buildkite.com/o-1-labs-2/mina/builds/14551#04576ace-d4c4-41a6-b2c9-7949ca464fbd)):
```
(monitor.ml.Error
\nInvalid base58 character in Non zero curve point compressed"
("Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30"
```
Issue doesn't appear to be affecting *compatible* and *develop-next* branches.

**Comment by robinbb** [comment]
@lk86 Possible to take this off of your plate and assign to Mina Foundation engineering?

**Comment by kantp** [comment]
Putting this in the todo state. The task at this point is to check whether the builds are still failing, and then either close the issue, or fix the builds.

**Comment by kaozenn** [comment]
I ran a build against develop: https://buildkite.com/o-1-labs-2/mina/builds/25765

All Jobs related to Rosetta Docker Build are successful.
- rosetta-stretch-docker-image
- rosetta-bionic-docker-image
- rosetta-bulleyes-docker-image
- rosetta-focal-docker-image

Closing issue
