### ISSUE TITLE
Fix prometheus/alertmanager discord webhook integration

### ISSUE THREAD

**Issue by 0x0I** [MinaProtocol/mina#8322]
Per https://github.com/metalmatze/alertmanager-bot/issues/78, Discord isn't officially supported as an Alertmanager receiver though there are workarounds (e.g. creating a proxy), which is currently preventing alert notifications to O(1)'s discord alert notification channel.

**Comment by shimkiv** [comment]
@lk86 can you please check if we need to work on this or it was already done?
