### ISSUE TITLE
Node status on RC

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#8335]
The network health report on RC only gets a small number of response. The number of queried nodes are ~900, and the number of responses are ~130.

**Comment by ghost-not-in-the-shell** [comment]
According to watchdog's log. Most of the queries timed out. We have a timeout of 400ms for `getPeerNodeStatusMsg` in libp2p layer. It times out there. We could try to increase the timeout.

**Comment by aneesharaines** [comment]
@ghost-not-in-the-shell  is still working on confirming this works
