### ISSUE TITLE
Remove transaction replacement fee of 5

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#8347]
1. remove https://github.com/MinaProtocol/mina/blob/9f49e57fd9c147f24873bdc89f8fdf3f72e62ef2/src/lib/network_pool/indexed_pool.ml#L14
2. Move this up one level  https://github.com/MinaProtocol/mina/blob/9f49e57fd9c147f24873bdc89f8fdf3f72e62ef2/src/lib/network_pool/indexed_pool.ml#L873
3. change `>=` to  `>` on this line https://github.com/MinaProtocol/mina/blob/9f49e57fd9c147f24873bdc89f8fdf3f72e62ef2/src/lib/network_pool/indexed_pool.ml#L947
4. test

**Comment by p-shahi** [comment]
will address https://github.com/MinaProtocol/mina/issues/2385
