### ISSUE TITLE
Mina daemon crash

### ISSUE THREAD

**Issue by Ferdinand-33** [MinaProtocol/mina#8349]
Stopped the daemon with ctrl c command. Tried to restart but crashes.
[coda_crash_report_2021-03-19_15-19-08.669455.tar.gz](https://github.com/MinaProtocol/mina/files/6172330/coda_crash_report_2021-03-19_15-19-08.669455.tar.gz)

**Comment by shimkiv** [comment]
Closing as stale. Please open new one in case of any new issues observed. Thank you.
