### ISSUE TITLE
[Bug] Single Block producer creates multiple blocks in one slot

### ISSUE THREAD

**Issue by EmrePiconbello** [MinaProtocol/mina#8351]
While we were testing some stuff our single node created 3 blocks at the same slot which is 1185. The duplicated blocks got rejected but the out of sync blocks just can go and with a single node without any extra my node pushed 3 blocks in a slot. This might create an issue with parties flooding invalid blocks in a single slot effecting other nodes and more. I feel like it should be investigated a bit further.
![image](https://user-images.githubusercontent.com/54602437/111813289-eadf2600-88d0-11eb-8de9-31b94d973bf3.png)

**Comment by garethtdavies** [comment]
This has been replicated by others on Discord and I also just experienced this. Here's my metrics for block produced showing multiple blocks produced in a single slot (epoch 1 slot 864)

<img width="1492" alt="CleanShot_2021-04-02_at_10 37 212x" src="https://user-images.githubusercontent.com/135382/113439716-f2f29780-939f-11eb-96e8-2a147adf6fb8.png">

**Comment by garethtdavies** [comment]
Many more reports of this on Github, plus if you win multiple slots within a short time frame this can produce a lot of additional blocks. 

<img width="1495" alt="CleanShot_2021-04-03_at_10 53 442x" src="https://user-images.githubusercontent.com/135382/113487138-1fbfb100-946b-11eb-8025-f96817b9a21e.png">

**Comment by aneesharaines** [comment]
@EmrePiconbello - Could you send us the logs from this time period when these were evaluated?  Also are you passing in multiple block producer keys and if so, using what method?

**Comment by EmrePiconbello** [comment]
@aneesharaines - I didn't have it right now but I can replicate the same thing. Simply you can replicate it by stoping the node and wiping the node's data just before a block production. I was keeping a node in the old state and run it before the block production slot.
I am not passing multiple block producer keys it's just a normal node I am just manipulating the node by stopping it down and starting back up. I didn't have much time to go into details and test various situations so I didn't follow it up.

**Comment by garethtdavies** [comment]
Just to add to @EmrePiconbello description this will also happen on a node that persists the state. The only thing you need to do is to be in catchup when it is your turn for block production and multiple blocks will be produced in the slot - it seems as fast as your machine can complete a proof. 

There are many instances of this already reported on Discord or visible by looking at blocks produced in a slot. These are just normal nodes in catchup producing multiple blocks per slot.

**Comment by jrwashburn** [comment]
Adding one more example to this. Unfortunately I let the logs rollover and just noticed it now. Contributing anecdote anyway in case helpful. 

I have a scenario where a single BP produced a block that made it in as the canonical block, and then produced again. Canonical: https://minaexplorer.com/block/3NKXYYvB5yH7BD9aDrwW3kHmDdnpDZGEK6mDEztXkgY9MghmMguw 
and duplicate about a minute later: https://minaexplorer.com/block/3NKbJcUrrCbKKHFUYmWxnDzWSMUyWCgwYLgPsqWBSKBuLmk8yGGG 

(My redundant BPs are now identified by unique coinbase receiver, so I know this was the same node.)

**Comment by yourbuddyconner** [comment]
Throwing in my hat into this ring, had this occur to me today:
<img width="671" alt="Screen Shot 2021-04-28 at 4 23 56 PM" src="https://user-images.githubusercontent.com/2635475/116485125-522cb600-a83f-11eb-824a-0b18cec2f3d1.png">
None of my blocks ended up being gossiped, missed the slot as a result. Bummer!

**Comment by p-shahi** [comment]
Our thought is this bug is not reproducible in the latest releases. Will reopen if its encountered again.
