### ISSUE TITLE
Empty blocks are chosen over paying fees out of coinbase amount

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#8363]
If there are no transactions available to place in a block, the [budget check](https://github.com/MinaProtocol/mina/blob/1b0be2c3b1eadb0f51814410b9e906275a6de4d4/src/lib/staged_ledger/staged_ledger.ml#L1380) in staged ledger won't allow any snark work to be bought with fee > 0.

This means that block producers will 'choose' to forgo the coinbase altogether instead of paying any snark fees to include their coinbase transaction.

This should be fixed before #8098 is merged, otherwise blocks will be empty and profitable block production will halt each time the transaction pool is empty and the next snark work is not free. We are currently in a less bad world where when one unlucky block producer has to buy snark work, they buys as much as they can afford from fees (and will fit in their block), so far fewer blocks trigger the budgeting code at all.

**Comment by deepthiskumar** [comment]
from the discord convo for posterity:
The fee transfers in that budget calculation are only for transactions. Coinbase fee transfers are not included in it and are tracked separately. see here https://github.com/MinaProtocol/mina/blob/66e0ef27230cc8b8a8e2247437b54b449bc9dce8/src/lib/staged_ledger/staged_ledger.ml#L1238 If the budget is insufficient which means there are some transactions, the transactions are discarded. Coinbase transaction will get deleted only if the work constraint is not satisfied (edit: Or if the cheapest of all the work is > coinbase amount)
