### ISSUE TITLE
Low min window density in Mainnet RC

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#8373]
Min window density in the release candidate has come down to 43. The grace period of 3 days ended on 03/20/2020 00:00:00 UTC and the min window density has been reducing ever since
https://o1testnet.grafana.net/d/4BrFOXyMk/alerts?viewPanel=18&orgId=1&var-testnet=mainnet&from=now-7d&to=now
Fill rate has also reduced to ~65%
https://o1testnet.grafana.net/d/4BrFOXyMk/alerts?viewPanel=17&orgId=1&var-testnet=mainnet&from=now-7d&to=now

**Comment by deepthiskumar** [comment]
fill rate is currently at 69.8

**Comment by aneesharaines** [comment]
Need to update the alerts dashboard to the new threshold

**Comment by deepthiskumar** [comment]
Updated the threshold
