### ISSUE TITLE
make block data public 

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#8394]
Make block data from mainnet RC (stored in a google storage bucket `mina_network_block_data`) publicly accessible.

**Comment by 0x0I** [comment]
All testnet, mainnet etc block data within `mina_network_block_data` is now publicly accessible. See `mina_network_block_data` [permissions](https://console.cloud.google.com/storage/browser/mina_network_block_data;tab=permissions?forceOnBucketsSortingFiltering=false&authuser=1&organizationId=707281238400&project=o1labs-192920) for more details.

**Comment by nerdvibe** [comment]
wow, this makes me so happy! Thank you 🙌

**Comment by nerdvibe** [comment]
what are the bucket URLs? (don't have the GCP account with me)

**Comment by deepthiskumar** [comment]
I think you just need a gmail account? the url is https://console.cloud.google.com/storage/browser/mina_network_block_data

**Comment by 0x0I** [comment]
> what are the bucket URLs? (don't have the GCP account with me)

@nerdvibe You can also access each of the bucket items using something like:

`curl https://mina_network_block_data.storage.googleapis.com/<block-data-json -- e.g. mainnet-3NK2vr9c2cR7PMamHavq9pRoghzLM4eoe2PPYcrjfeamZF9gmduV.json>`

or

`curl https://storage.googleapis.com/mina_network_block_data/mainnet-3NK2vr9c2cR7PMamHavq9pRoghzLM4eoe2PPYcrjfeamZF9gmduV.json`
