### ISSUE TITLE
[mina spec] - Ouroboros Samasika consensus - breadth-first skeleton and sliding window density details

### ISSUE THREAD

**Issue by jspada** [MinaProtocol/mina#8407]
Write specification for Mina's Ouroboros Samasika consensus implementation.

Important to
* Factor out implementation specific details from the specification
* Discern `protocol types` from implementation specific types

Protocol types are those that appear over the wire (i.e. as part of the networking protocol) that 3rd party implementations will need to deserialize.

**Comment by imeckler** [comment]
Figure 9 on page 25 [here](https://eprint.iacr.org/2020/352.pdf) indicates differences from Ouroboros Praos

**Comment by nholland94** [comment]
Note: I believe the selection rule in the whitepaper is missing some tie breaking rules we implemented in the code (e.g. protocol state hash and hash of vrf tie breaking).

**Comment by jspada** [comment]
Thanks.  Yeah, I was those.  I think the ones you're referring to are the stuff involving `candidate_vrf_is_bigger` and `blockchain_length_is_longer`, etc?

Link to work in progress https://github.com/jspada/mina/blob/feature/8407-spec-ouroboros-samasika-consensus/docs/specs/consensus/README.md#32-decentralized-checkpointing

**Comment by joseandro** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snapps-Core-61d625818b23760010988cf2/issues/MinaProtocol/mina/8407?planning-poker) with ZenHub @aneesharaines
