### ISSUE TITLE
Validation tool for delegation rewards send-back

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#8408]
There are two contexts under which it's useful to verify that rewards are being sent back properly for delegations. One is more or less a subset of the other, so they should be verified with the same tool. We will consume both archive database data and staking-ledger-export dumps to answer these questions.

1. Answer the question: Exactly how many MINA tokens has an address received as payback for its delegation during this epoch?

To determine this look at transactions originating from the address that is being delegated to AND ones originating from an account which is the coinbase-receiver from a block that was created by the address being delegated to.

Take as input:
* the staking ledger for that epoch
* a handle to the postgres database of the archive node
* a public key for the address in question

The output should include:
* How many tokens were paid back?
* Across how many transactions?
* What was this address' contribution to the account that was staking? (show this address' stake during the epoch, the full amount in the pool, and the percentage)

2. Have my rewards paybacks met my expectations from the perspective of a token-provider in the Delegation Program?

Print the above output AND

Follow the rules outlined in the doc here: https://minaprotocol.com/docs/advanced/foundation-delegation-program ; be sure to use "string contains" on the discord-id check

And output either "Yes, the expectations are met" (and exit 0) or
"No, the expectations are not met because (reason)" (and exit non-zero)

**Comment by psteckler** [comment]
> originating from an account which is the coinbase-receiver from a block

The archive db does not include the coinbase receiver for a block.
