### ISSUE TITLE
Infrastructure for the Delegation Program bot system

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#8409]
In `automation/services/mina-bp-stats`, we already have a side-car node and a lambda ingest service that stores uptime data from block producers that opt-in to sending it into a Google Cloud bucket.

We ~~will soon~~ now also have: https://github.com/MinaProtocol/mina/pull/8377 
1. a Docker container containing a "script" that we need to run every 30minutes that expects a handle to a postgres database and access to a Gcloud bucket that crunches the raw data and generates reports in the postgres database
2. a Docker container containing the backend for a leaderboard web server that needs to be online and accessible via some frontend
3. the frontend website logic
4. A Docker container that sends SendGrid emails

We need to deploy infrastructure that
* Has a postgres database inside it
* Runs (1) on an interval
* Runs (2) forever to server (3)

**Comment by aneesharaines** [comment]
- need to update to the deployments

**Comment by aneesharaines** [comment]
Allow network access to send grid in the cluster.
