### ISSUE TITLE
Important subsystems of the codebase to document -> specify

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#8410]
As we move towards a world where we have proper specs for our protocol, we may as well improve our development experience on the way (thanks @mrmr1993 for the proposal). As such, we should start adding doc-comments throughout our code.

The question is: where do we start? There are (at least) two questions for prioritizing this work.
1. How soon would an alternate client implementation need to start working on the subsystem?
2. How much would it benefit developers looking to explore parts of the codebase they are unfamiliar with?

Here's a suggested list mostly focused on (1):

* Consensus -- @jspada is already working on this
* Verification of proofs: Blocks, proofs, verification logic, verification keys, etc
* Ledgers: Merkle trees, Merkle masks, snarking Merkle trees, etc (avoid staged ledger for now)
* Transition Frontier: The data structure and the subsytem
* Gossip Network: the ml code, the libp2p code, everything in between

We will start with docs and head towards specs!

**Comment by aneesharaines** [comment]
@bkase - do you have an example of a good level of documentation?

**Comment by aneesharaines** [comment]
We should also update the systems diagrams

**Comment by aneesharaines** [comment]
https://www.notion.so/minaprotocol/Docs-Info-c969cd7e3c1c4f4394cd48bff354cddc
