### ISSUE TITLE
(Partial) Specification of bin_io protocol

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#8411]
This must be done before April 1!

In order to speed up folks that may want to work on bin_io implementations in other languages, we should do some OCaml macro reverse engineering with folks internally who are experts in OCaml macros:

We should time box this work to 2 days and make sure to do at least the following:
* One primitive type
* Polymorphic variants
* Custom serializers

If we have time, we should also move forwards with speccing different pieces in sorted order by what is the most complicated to understand for someone new to ppx to least. I imagine objects may be next, but up to you.

For formatting, follow @jspada 's example of specs shown here https://github.com/MinaProtocol/mina/pull/8374/files

**Comment by imeckler** [comment]
There is a bin_prot spec here https://github.com/janestreet/bin_prot

**Comment by imeckler** [comment]
One thing worth mentioning is we have a custom bin_prot for field elements, which uses a little endian encoding of a field element as 32 bytes.

**Comment by aneesharaines** [comment]
@bkase  and @psteckler   to sync on best approach
