### ISSUE TITLE
Intg test; replace current intg test graphql ingress

### ISSUE THREAD

**Issue by QuiteStochastic** [MinaProtocol/mina#8420]
the current graphql ingress for the intg tests uses GCP's default ingress feature, as done in this ticket (https://github.com/MinaProtocol/mina/issues/7316).

however, GCP's ingress is proving to be very slow, inadequate, and not performant, and a new one is needed.

This could possibly be fixed by the same work as done for the and DNS network routing portion of this ticket (https://github.com/MinaProtocol/mina/issues/6153)

nginx was also floated as a possible solution to this problem.  @0x0I discussed possibly using kubernetes traefik instead of nginx

**Comment by aneesharaines** [comment]
@0x0I investigating traffik as a solution
