### ISSUE TITLE
mina-validate-keypair and mina account import disagree on public-key for same private key

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#8421]
Very weird behavior, but I'm seeing mina-validate-keypair and `mina account import` disagree on public keys for the same private key file.

Why is this weird? mina-validate-keypair checks that the public key associated with the key is the same as the base58-check encoded key. `mina account import` also derives the public key for that private key in the same manner (as far as I can tell).

Clearly, I'm missing something

**Comment by bkase** [comment]
mina-validate-keypair @ 718eba4826794f83d51c0d8dcf538e78b0259528
mina @ 48401e92d94948c066c03ca76326c065e5cbfc92

**Comment by lk86** [comment]
One of the old generate keypair tools would create keys with this behavior, I think it means the key uses the wrong curve constants? Maybe there is another bug causing a similar result, but that's my best theory.

**Comment by aneesharaines** [comment]
@psteckler  to help investigate what's going on here

**Comment by psteckler** [comment]
The private key and public keys were mismatched. The user's `mina-validate-keypair` was an old version, which only checked that the private key could sign a transaction. `accounts import` derived the matching public key, which was different than the original public key.

The current `mina-validate-keypair` checks that the public key matches the private key.

Conclusion: operator error, not a bug.
