### ISSUE TITLE
No genesis proof file was found and not allowed to generate a new genesis proof

### ISSUE THREAD

**Issue by tobiasatw11k** [MinaProtocol/mina#8466]
I followed the instruction of this documentation: https://minaprotocol.com/docs/connecting. running ubuntu 20 on a vps with plesk. for further details, see attached log:

[coda_crash_report_2021-03-26_13-50-23.432444.zip](https://github.com/MinaProtocol/mina/files/6212211/coda_crash_report_2021-03-26_13-50-23.432444.zip)

**Comment by aleksey-mahanov** [comment]
Same error, running `debian:9` in Docker.

```sh
docker run \
  --env-file $HERE/.env \
  -p 8302:8302 \
  --restart=always \
  --mount "type=bind,source=${HERE}/keys,dst=/keys,readonly" \
  --mount "type=bind,source=${HERE}/.mina-config,dst=/root/.mina-config" \
  --name my-mina \
  my-mina \
  daemon \
  --block-producer-key /keys/my-wallet \
  --insecure-rest-server \
  --file-log-level Debug \
  --log-level Info \
  --peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt
```

[coda_crash_report_2021-03-29_06-50-39.365662.tar.gz](https://github.com/MinaProtocol/mina/files/6219790/coda_crash_report_2021-03-29_06-50-39.365662.tar.gz)

**Comment by aleksey-mahanov** [comment]
The issue is solved for me. I had to instruct mina daemon to `--generate-genesis-proof true` when connecting for the first time. It is mentioned at the top of the "Start up a node" chapter however missing from the "Docker" chapter.

**Comment by tobiasatw11k** [comment]
thanks for the hint @aleksey-mahanov looking at the docker daemon config, it seems that the `--block-producer-key $PATH_TO_WALLET` was missing. so it also worked for me with that option.
