### ISSUE TITLE
node starting issue, can't generate-genesis-proof

### ISSUE THREAD

**Issue by bdichter** [MinaProtocol/mina#8476]
I have carefully followed these instructions: https://minaprotocol.com/docs/connecting

After checking the logs, it seems that this file: "https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a" should be copied to: "/tmp/s3_cache_dir/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"

getting a 404 for this URI: https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a

Is this correct? Is there another location where this file is located?

Thanks!

**Comment by psteckler** [comment]
Can you run `mina client export-local-logs`, and attach the file that's generated?

**Comment by bdichter** [comment]
Hey @psteckler, thanks for responding. I reviewed the steps and found that the error was mine after all. This issue has been resolved, thanks!

**Comment by ramonqlee** [comment]
@bdichter I get the same error. Can you share your solution?

**Comment by bdichter** [comment]
@ramonqlee first, I created a new instance with the correct specs but this time I waited for the process to fully start. The first time, I killed the process too soon which is what I think caused the failure. Be patient, eventually you'll see in the log that it's working.

**Comment by ramonqlee** [comment]
@bdichter you see following message, but wait and finally mina daemon is still working?

I have carefully followed these instructions: https://minaprotocol.com/docs/connecting

After checking the logs, it seems that this file: "https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a" should be copied to: "/tmp/s3_cache_dir/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"

getting a 404 for this URI: https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a
