### ISSUE TITLE
File not found:https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"

### ISSUE THREAD

**Issue by mallchain** [MinaProtocol/mina#8479]
2021-03-30 05:43:30 UTC [Info] Initializing with runtime configuration. Ledger name: "mainnet"
2021-03-30 05:43:30 UTC [Info] Using the compiled constraint constants
2021-03-30 05:43:38 UTC [Info] Genesis proof file $path does not exist
	path: "/root/.mina-config/genesis/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-03-30 05:43:38 UTC [Info] Genesis proof file $path does not exist
	path: "/var/lib/coda/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-03-30 05:43:38 UTC [Info] Genesis proof file $path does not exist
	path: "/usr/local/var/coda/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-03-30 05:43:38 UTC [Info] Genesis proof file $path does not exist
	path: "/tmp/s3_cache_dir/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-03-30 05:43:38 UTC [Info] Genesis proof file $path does not exist
	path: "/tmp/coda_cache_dir/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-03-30 05:43:38 UTC [Info] Genesis proof file $path does not exist
	path: "/var/lib/coda/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-03-30 05:43:38 UTC [Info] Could not download genesis proof file from $uri: $error
	uri: "https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
	error: {
  "commit_id": "a8893ab6dd8a68171e7b99a5dc6b76940411350b",
  "exn_name": "Async_kernel__Monitor.Error_",
  "exn": [
    "monitor.ml.Error",
    [
      "Process.run failed",
      [
        [ "prog", "curl" ],
        [
          "args",
          [
            "--fail", "--silent", "--show-error", "-o",
            "/tmp/s3_cache_dir/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a",
            "https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
          ]
        ],
        [ "exit_status", [ "Exit_non_zero", "22" ] ],
        [ "stdout", "" ],
        [
          "stderr",
          [
            "curl: (22) The requested URL returned error: 404 Not Found", ""
          ]
        ]
      ]
    ],
    [
      "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
      "Called from file \"src/or_error.ml\", line 72, characters 17-32",
      "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
    ]
  ]
}
2021-03-30 05:43:38 UTC [Info] No genesis proof file was found for $base_hash, generating a new genesis proof
	base_hash: "ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"

**Comment by psteckler** [comment]
What was your command line to run the daemon?

Can you run `mina client export-local-logs`, and attach the result?

**Comment by ramonqlee** [comment]
mina client export-local-logs
[2021-03-30_20-39-44.tar.gz](https://github.com/MinaProtocol/mina/files/6232083/2021-03-30_20-39-44.tar.gz)

**Comment by xuzhitong** [comment]
> run mina daemon --generate-genesis-proof true --peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt
> and report same error.
> 
> mina client export-local-logs
> [2021-03-30_20-39-44.tar.gz](https://github.com/MinaProtocol/mina/files/6232083/2021-03-30_20-39-44.tar.gz)

the same error

**Comment by mallchain** [comment]
U can ignore this error and start mina as follows:
systemctl --user daemon-reload
systemctl --user start mina
systemctl --user enable mina
sudo loginctl enable-linger

Finally mina will start and check its status out with 'mina client status' command
