### ISSUE TITLE
Receiver balances in archive db don't match replayer ledger

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#8504]
I downloaded the archive db from mainnet, with the maximum global slot of 7542 in epoch 1.

The replayer test failed because the balance for a fee transfer receiver did not match the balance in the ledger maintained by the replayer. The discrepancy happens when there's a "combined fee transfer", that is, two fee transfers with the same sequence number, but distinct secondary sequence numbers. Those are combined into a single fee transfer via `Fee_transfer.create`, and then applied using `Ledger.fee_transfer`.

Here's the replayer log:
```
{"timestamp":"2021-04-01 18:00:10.129645Z","level":"Info","source":{"module":"Dune__exe__Replayer","location":"File \"src/app/replayer/replayer.ml\", line 313, characters 2-13"},"message":"Applying internal command (coinbase) with global\
 slot 1877, sequence number 2, and secondary sequence number 0","metadata":{"pid":20945}}
{"timestamp":"2021-04-01 18:00:10.132075Z","level":"Info","source":{"module":"Dune__exe__Replayer","location":"File \"src/app/replayer/replayer.ml\", line 381, characters 2-13"},"message":"Applying combined fee transfers with sequence nu\
mber 3","metadata":{"pid":20945}}
{"timestamp":"2021-04-01 18:00:10.136812Z","level":"Error","source":{"module":"Dune__exe__Replayer","location":"File \"src/app/replayer/replayer.ml\", line 305, characters 4-16"},"message":"Claimed balance does not match actual balance i\
n ledger","metadata":{"actual_balance":"8640.17279854","claimed_balance":"1.0000002","pid":20945,"who":"combined fee transfer"}}
```

If the balance verification for combined fee transfers is skipped, the replayer test succeeds, and all other balances and ledger hashes match up. The balances for other internal commands, including fee transfers that are not combined, all match up. That suggests that the ledger is being updated correctly, but just the balances for this case are not correct in the archive db.

The replayer code was verifying the balance for only one of the receivers in the combined transfer, but really should be checking both.

**Comment by psteckler** [comment]
The bug is that the balances are swapped in the archive db between the two receivers of the fee transfer.

It's an easy fix, but what to do about extant archive dbs?

**Comment by jrwashburn** [comment]
> The bug is that the balances are swapped in the archive db between the two receivers of the fee transfer.
> 
> It's an easy fix, but what to do about extant archive dbs?

Can this fix include a patch script to update incorrect data in existing archives?

**Comment by psteckler** [comment]
> Can this fix include a patch script to update incorrect data in existing archives?

We should have information on how to do this soon.

**Comment by psteckler** [comment]
> Can this fix include a patch script to update incorrect data in existing archives?

@jrwashburn I had said we'd have a script to patch the balances soon, sorry it's taken so long. It should be available in the next few days.

**Comment by psteckler** [comment]
I believe this issue has been resolved.
