### ISSUE TITLE
Metrics for rejected blocks

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#8510]
Create a new prometheus metric for tracking rejected blocks. There are different reasons why a block would get rejected and so having a different metric for each of the block would be helpful. For example:
1.  Blocks rejected because of no common ancestor
2. Blocks rejected due to invalid proof
3. Blocks rejected for being late

**Comment by aneesharaines** [comment]
The metrics are done now working on improving the fork alerts which will be captured in another pr
