### ISSUE TITLE
Mina Daemon crashed.

### ISSUE THREAD

**Issue by akabedin** [MinaProtocol/mina#8547]
Running Mina in Docker on Mac
Following instructions on Connecting Overview (https://minaprotocol.com/docs/connecting) after successfully generating key pair
Attempting the docker run --name mina ... command with password for private key

Attaching crash report
[coda_crash_report_2021-04-03_22-22-09.475060.tar.gz](https://github.com/MinaProtocol/mina/files/6253594/coda_crash_report_2021-04-03_22-22-09.475060.tar.gz)

**Comment by deepthiskumar** [comment]
@akabedin Could be the Docker resources allocated (see #8505) could you increase the size limit and try?

**Comment by shimkiv** [comment]
Hey @akabedin, do you have any updates about this issue? Did the above suggestion helped?

**Comment by shimkiv** [comment]
Closing this issue because of being inactive for long time.
Please feel free to open another ticket should you experience any further issues.
