### ISSUE TITLE
payment transaction dropped after inclusion in orphan

### ISSUE THREAD

**Issue by jrwashburn** [MinaProtocol/mina#8548]
Scenario: sent several payment transactions, all made it to an orphaned block, after which most made it into the canonical chain, but at least one was never included in the canonical chain. Since all were included in an orphaned block, it is clear that the missing transaction was broadcast. 

This orphaned block 5338 contains 6 user commands for nonces 18-23 from key B62qpRMMLBrU3TEwtw1Fbaz41LcgX7H8y6JYH14MaiSFWzhbV8wVunu  
https://minaexplorer.com/block/3NK8bzDTLwnFnTdjedwKKC7srkbZSJ8ck1BwXuntFA5nLB2Vv3z8

Nonces 18-22 were then successfully included in this canonical block 5338:
https://minaexplorer.com/block/3NLYnpNToKogfSPTDsehSFEZMVJ14NhMw6mrwg989R1YKbir4kzW

Nonce 23 was somehow dropped and never re-included in any block. It was eventually re-created and broadcast with a different memo, which made it onto the canonical chain in this block 5348:
https://minaexplorer.com/block/3NKsW8y5336DxNCeRBxzW7thi1pqGHZtm3HgyJEamyHpt9F6bhEh

Between blocks 5338 and 5348, only ~40 other user commands were included, so this is not a problem related to transaction volume or the pool being full. Most of those (all but 5) are at the same fee (0.01 mina) although 4 did go through at 0.1 and one at .001. There does not seem to be any obvious reason that the transaction should have been dropped from the pool.

**Comment by jrwashburn** [comment]
Just noticed the orphan and the successful blocks for height 5338 were from the same creator. May be a factor.

**Comment by garethtdavies** [comment]
I think this is similar to https://github.com/MinaProtocol/mina/issues/8331? Do you see `Locally generated commands $cmds dropped because they conflicted with a committed command.` in your logs as that's the commonality for both instances listed in that proper issue.

**Comment by jrwashburn** [comment]
> I think this is similar to #8331? Do you see `Locally generated commands $cmds dropped because they conflicted with a committed command.` in your logs as that's the commonality for both instances listed in that proper issue?

I looked at #8331 but think this is different - if I understood it correctly. Everything I read there seemed to indicate/relate to errors sending. This transaction was sent - and even included in an (orphaned) block on another node, then dropped.

**Comment by garethtdavies** [comment]
Yeh, maybe it is different. The payments in #8331 are sent and a payment id is returned, they just got dropped later (actually after some time, as we were both sending on delayed intervals). I've experienced it again since and it's incredibly frustrating that they disappear after being successfully sent.

**Comment by deepthiskumar** [comment]
Thiis 

> > I think this is similar to #8331? Do you see `Locally generated commands $cmds dropped because they conflicted with a committed command.` in your logs as that's the commonality for both instances listed in that proper issue?
> 
> I looked at #8331 but think this is different - if I understood it correctly. Everything I read there seemed to indicate/relate to errors sending. This transaction was sent - and even included in an (orphaned) block on another node, then dropped.

This is noted in #8331 (not send-payment error).  Transactions were being dropped from mempool when processing a block. To be specific, when removing payments from pool that are included in a block. This could also happen with orphaned blocks- i.e., if a now-orphaned block was in the canonical chain before being replaced.
