### ISSUE TITLE
Shutdown before Coda instance was created, not saving a visualization

### ISSUE THREAD

**Issue by cryptotrade3** [MinaProtocol/mina#8549]
Mina deamon creashed after starting by this command: 

`mina daemon -generate-genesis-proof true --peer-list-url https://storage.googleapis.com/seed-lists/devnet_seeds.txt`

I am using Linux Mint 19 Tara

[coda_crash_report_2021-04-04_13-05-24.600505.tar.gz](https://github.com/MinaProtocol/mina/files/6254582/coda_crash_report_2021-04-04_13-05-24.600505.tar.gz)

**Comment by timsmith1337** [comment]
`"Couldn't determine our IP from the internet, use -external-ip flag"`
