### ISSUE TITLE
Some folks are seeing 10-20sec long async cycles

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#8564]
These are on nodes that are actively serving requests via GraphQL. Talk to @bkase to get more details

**Comment by aneesharaines** [comment]
Need to get more information on under what circumstances this is happening.  Possibly related to #7718.

Are they using best chain query alot?

**Comment by psteckler** [comment]
From `mnguyen-io` on Discord:
```
I'm not sure what other queries @Dan Sosedoff was seeing this issue with, 
but he did mention to me that he was running this and seeing problems: query status { version }
Both nodes are archive nodes if that helps any```

**Comment by psteckler** [comment]
And from `@Dan Sosedoff`:
```
yea sorry for late response - but we were just running the regular version check queries, 
and they were pretty slow sometimes.```

**Comment by aneesharaines** [comment]
@psteckler  to try to get logs when this happens
