### ISSUE TITLE
I just entered Mina daemon and the result says that my daemon is crashed

### ISSUE THREAD

**Issue by 3785515** [MinaProtocol/mina#8569]
I am yang heon Shim, one of the genesis founding member of the Mina portocol. I've delegate my tokens but ssuddenly today,  I just wanted to access to my Mina account to see my status and the program said I have an error at running Daemon. So I entered Mina daemon at the program and it said that my daemon is crashed. There was a github link where I could ask this isseue so I just came like this. Wonder what's the issue of my daemon.  
 
error: {
  "commit_id": "a8893ab6dd8a68171e7b99a5dc6b76940411350b",
  "string":
    "No genesis proof file was found and not allowed to generate a new genesis proof"
}
2021-04-06 13:53:21 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: {
  "commit_id": "a8893ab6dd8a68171e7b99a5dc6b76940411350b",
  "sexp": [
    "monitor.ml.Error",
    "No genesis proof file was found and not allowed to generate a new genesis proof",
    [
      "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
      "Called from file \"src/app/cli/src/mina.ml\", line 653, characters 12-27",
      "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
    "Called from file \"src/app/cli/src/mina.ml\", line 653, characters 12-27",
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}
2021-04-06 13:53:21 UTC [Warn] Shutdown before Coda instance was created, not saving a visualization

  ☠  Mina Daemon crashed.
   The Mina Protocol developers would like to know why!

    Please:
      Open an issue:
        <https://github.com/MinaProtocol/mina/issues/new>

      Briefly describe what you were doing and attach the crash report /home/jawshun/.mina-config/coda_crash_report_2021-04-06_13-53-21.743397.tar.gz

![daemon crashed](https://user-images.githubusercontent.com/82041191/113724951-d3f05e80-972d-11eb-8a10-8f09a2e28bc0.jpg)

**Comment by mrmr1993** [comment]
You'll need to pass the `--generate-genesis-proof true` flag to the daemon, as per the instructions [here](https://minaprotocol.com/docs/using_mina/connecting).

**Comment by 3785515** [comment]
If I put this code at the program, it says they failed in running the process mina daemon --generate-genesis-proof true --peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt

**Comment by 3785515** [comment]
> You'll need to pass the `--generate-genesis-proof true` flag to the daemon, as per the instructions [here](https://minaprotocol.com/docs/using_mina/connecting).
If I put this code at the program, it says they failed in running the process mina daemon --generate-genesis-proof true --peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt
