### ISSUE TITLE
mina daemon --generate-genesis-proof true  -> No genesis proof

### ISSUE THREAD

**Issue by 3785515** [MinaProtocol/mina#8579]
2021-04-07 01:30:25 UTC [Info] Coda daemon is booting up; built with commit "a8893ab6dd8a68171e7b99a5dc6b76940411350b" on branch "master"
2021-04-07 01:30:25 UTC [Info] Removing lockfile for terminated process
2021-04-07 01:30:25 UTC [Info] Daemon will expire at "2024-12-10 14:00:00-07:00"
2021-04-07 01:30:25 UTC [Info] Booting may take several seconds, please wait
2021-04-07 01:30:25 UTC [Info] Reading configuration files $config_files
        config_files: [
  "/var/lib/coda/config_a8893ab6.json",
  "/home/jawshun/.mina-config/daemon.json"
]
2021-04-07 01:30:26 UTC [Warn] Could not read configuration from "/home/jawshun/.mina-config/daemon.json": $error
        error: {
  "commit_id": "a8893ab6dd8a68171e7b99a5dc6b76940411350b",
  "exn_name": "Async_kernel__Monitor.Error_",
  "exn": [
    "monitor.ml.Error",
    [
      "Unix.Unix_error", "No such file or directory", "open",
      "((filename /home/jawshun/.mina-config/daemon.json) (mode (O_RDONLY O_CLOEXEC)) (perm 0o0))"
    ],
    [
      "Raised at file \"src/result.ml\", line 158, characters 17-26",
      "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor try_with_or_error"
    ]
  ]
}
2021-04-07 01:30:26 UTC [Info] Initializing with runtime configuration. Ledger name: "mainnet"
2021-04-07 01:30:26 UTC [Info] Using the compiled constraint constants
2021-04-07 01:30:27 UTC [Info] Genesis proof file $path does not exist
        path: "/home/jawshun/.mina-config/genesis/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-04-07 01:30:27 UTC [Info] Genesis proof file $path does not exist
        path: "/var/lib/coda/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-04-07 01:30:27 UTC [Info] Genesis proof file $path does not exist
        path: "/usr/local/var/coda/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-04-07 01:30:27 UTC [Info] Genesis proof file $path does not exist
        path: "/tmp/s3_cache_dir/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-04-07 01:30:27 UTC [Info] Genesis proof file $path does not exist
        path: "/tmp/coda_cache_dir/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-04-07 01:30:27 UTC [Info] Genesis proof file $path does not exist
        path: "/var/lib/coda/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-04-07 01:30:28 UTC [Info] Could not download genesis proof file from $uri: $error
        uri: "https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
        error: {
  "commit_id": "a8893ab6dd8a68171e7b99a5dc6b76940411350b",
  "exn_name": "Async_kernel__Monitor.Error_",
  "exn": [
    "monitor.ml.Error",
    [
      "Process.run failed",
      [
        [ "prog", "curl" ],
        [
          "args",
          [
            "--fail", "--silent", "--show-error", "-o",
            "/tmp/s3_cache_dir/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a",
            "https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
          ]
        ],
        [ "exit_status", [ "Exit_non_zero", "22" ] ],
        [ "stdout", "" ],
        [
          "stderr",
          [
            "curl: (22) The requested URL returned error: 404 Not Found", ""
          ]
        ]
      ]
    ],
    [
      "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
      "Called from file \"src/or_error.ml\", line 72, characters 17-32",
      "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
    ]
  ]
}
2021-04-07 01:30:28 UTC [Info] No genesis proof file was found for $base_hash, generating a new genesis proof
        base_hash: "ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
Transaction_snark.system: 12.824s

**Comment by kgricour** [comment]
I have the same problem and when I run `mina client status` I get: `unabled to connect to mina daemon`

**Comment by kgricour** [comment]
@3785515 have you found a solution ?

**Comment by 3785515** [comment]
> @3785515 have you found a solution ?

Not yet. My daemon is crashed and I don't know how to solve it.

**Comment by dfmb99** [comment]
Same problem

**Comment by 3785515** [comment]
DId anybody solved the problem?

**Comment by MattiasIngered** [comment]
I thought it was a problem, but it just took a bloody long time for it to generate the genesis. 
Following the guide, on a dual CPU server, it took about 15 minutes before mina daemon started and I got to bootstrapping.

You can see if you run "top" that alot of things are ongoing in the background until mina finaly goes up.

**Comment by Gaofancy** [comment]
A week passed, The problem is still unresolved.

**Comment by mauguzun** [comment]
i have same problem ;(

**Comment by 3785515** [comment]
> I thought it was a problem, but it just took a bloody long time for it to generate the genesis.
> Following the guide, on a dual CPU server, it took about 15 minutes before mina daemon started and I got to bootstrapping.
> 
> You can see if you run "top" that alot of things are ongoing in the background until mina finaly goes up.

Does that mean after starting Ubuntu, we need to type Mina -daemon after 15min pass?

**Comment by 3785515** [comment]
@Mattias3891 Well, I just waited after the command and the result comes out 'killed' and the daemon is still crashing. Can I ask if you know what is the problem of this?

**Comment by Mattias3891** [comment]
I followed the setup guide and it just took a long time to proceed from the last log line "No genesis proof file was found for $base_hash, generating a new genesis proof". Looking at any process viewer, I saw lots of stuff going on in the background, so I left it to do it's thing and 10-15 minutes later it's up and running.

I've set up eight nodes from scratch by now and it's the exact same thing. Takes a while to proceed from there, the first time it's started up. All of them Ubuntu 18.04 LTS.

**Comment by deepthiskumar** [comment]
@3785515  As others have responded, when you run it for the first time, it downloads the keys and generates the genesis proof which might take time depending on your processor and internet speed.
If it crashed for you, could you post the crash log or the crash report?

**Comment by 3785515** [comment]
@deepthiskumar 

![image](https://user-images.githubusercontent.com/82041191/116110284-847bcd80-a6f0-11eb-8a26-07aa457b6e82.png)

It comes out like this. Still, It says Mina daemon is crashed. Seems like I'm doing wrong.

**Comment by shimkiv** [comment]
Closing this issue because of being inactive for long time.
Please feel free to open another ticket should you experience any further issues.
