### ISSUE TITLE
Duplicate producer and slot

### ISSUE THREAD

**Issue by ioannist** [MinaProtocol/mina#8580]
I am running a snark worker. 16G RAM, Ubuntu 18

2021-04-06 20:29:51 UTC [Error] Duplicate producer and slot: producer = $block_producer, consensus_time = $consensus_time, previous protocol state hash = $hash, current protocol state hash = $current_protocol_state_hash
	block_producer: "B62qp17siioFbT7ugFCJwtfcSn9SHFsBNAkUAxKjaFtorKqQ2Z46L1G"
	consensus_time: { "slot_number": "10009", "slots_per_epoch": "7140" }
	hash: "3NKK7ETsTdLqsb6qB26BcSCqt5hf5LyiXTaCSyK2zyMuvVHNj5rx"
	current_protocol_state_hash: "3NKck4Cdcri8RZbtR3hesSzs39P4TGeQ553LETrtKMEaErEW64WN"
2021-04-06 20:29:52 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: {
  "commit_id": "a8893ab6dd8a68171e7b99a5dc6b76940411350b",
  "sexp": [
    "monitor.ml.Error",
    [ "Pipe_lib.Strict_pipe.Overflow(\"bootstrap controller pipe\")" ],
    [
      "Raised at file \"src/lib/pipe_lib/strict_pipe.ml\", line 258, characters 34-79",
      "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file \"src/lib/pipe_lib/strict_pipe.ml\", line 258, characters 34-79",
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}

[coda_crash_report_2021-04-06_20-29-52.882808.tar.gz](https://github.com/MinaProtocol/mina/files/6269076/coda_crash_report_2021-04-06_20-29-52.882808.tar.gz)

**Comment by deepthiskumar** [comment]
```javascript


   "message":"Unhandled top-level exception: $exn\nGenerating crash report",
   "metadata":{
      "$duplicated_keys":[
         "host",
         "peer_id",
         "port"
      ],
      "exn":{
         "commit_id":"a8893ab6dd8a68171e7b99a5dc6b76940411350b",
         "sexp":[
            "monitor.ml.Error",
            [
               "Pipe_lib.Strict_pipe.Overflow(\"bootstrap controller pipe\")"
            ],
            [
               "Raised at file \"src/lib/pipe_lib/strict_pipe.ml\", line 258, characters 34-79",
               "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
               "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
               "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
               "Caught by monitor coda"
            ]
         ],
         "backtrace":[
            "Raised at file \"src/lib/pipe_lib/strict_pipe.ml\", line 258, characters 34-79",
            "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
            "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
            "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
         ]
      }

Already raised here 8502
```
