### ISSUE TITLE
Daemon Crashes

### ISSUE THREAD

**Issue by gaia** [MinaProtocol/mina#8623]
[coda_crash_report_2021-04-13_04-15-04.524572.zip](https://github.com/MinaProtocol/mina/files/6301203/coda_crash_report_2021-04-13_04-15-04.524572.zip)

was working fine. stopped working after a reboot today.

zip password is my github username

**Comment by mrmr1993** [comment]
```json
{
  "timestamp": "2021-04-13 03:15:52.164521Z",
  "level": "Fatal",
  "source": {
    "module": "Mina_net2",
    "location": "File \"src/lib/mina_net2/mina_net2.ml\", line 1592, characters 18-30"
  },
  "message": "libp2p_helper process died unexpectedly: $exit_status",
  "metadata": {
    "exit_status": "died after receiving sigterm (signal number 15)"
  }
}
```

Your node most likely ran out of memory and the operating system killed it. Closing, there isn't any information in the logs that we could use to investigate this further.

**Comment by gaia** [comment]
This box has 32GB, 8 dedicated Xeon cores. This is surely not the case.

![image](https://user-images.githubusercontent.com/87547/114602440-74bdad00-9c4b-11eb-8a5b-657470602643.png)

**Comment by gaia** [comment]
BTW it was stopped by me, because it stood at `[Info] Setting current protocol version to "2.0.0" from compile-time config` for 30+ minutes.

**Comment by mrmr1993** [comment]
> BTW it was stopped by me, because it stood at `[Info] Setting current protocol version to "2.0.0" from compile-time config` for 30+ minutes.

This appears to be due to downloading the snark proving keys; normally a restart fixes the issue. Have you seen this again after restarting?

**Comment by gaia** [comment]
yes, i restarted it a few times.
