### ISSUE TITLE
FATAL ERROR: Ineffective mark-compact transform[stderr]: s near heap limit Allocation failed - JavaScript heap out of memory  

### ISSUE THREAD

**Issue by UltronOne** [MinaProtocol/mina#8646]
Description

I am using @o1labs/client-sdk (https://www.npmjs.com/package/@o1labs/client-sdk) in my react-native project.
The metro bundler shows error below.
![image](https://user-images.githubusercontent.com/41232566/114763032-aaa18500-9d62-11eb-899c-e3c53bd9377c.png)

**Comment by shimkiv** [comment]
![image.png](https://images.zenhubusercontent.com/627b3c4459b2d4072eb1a8aa/07a4d1a0-8c39-4f33-9f06-6e4c2065fcf6)
