### ISSUE TITLE
Hello Could you pls help me ,

### ISSUE THREAD

**Issue by mauguzun** [MinaProtocol/mina#8665]
IO error: While lock file: /home/mauguzun/.mina-config/trust/LOCK: Resource temporarily unavailable"
[coda_crash_report_2021-04-16_09-45-03.984208.tar.gz](https://github.com/MinaProtocol/mina/files/6324087/coda_crash_report_2021-04-16_09-45-03.984208.tar.gz)

2021-04-16 09:45:02 UTC [Info] Coda daemon is booting up; built with commit "a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a" on branch "master"
2021-04-16 09:45:02 UTC [Info] Removing lockfile for terminated process
2021-04-16 09:45:02 UTC [Info] Daemon will expire at "2024-12-10 14:00:00-07:00"
2021-04-16 09:45:02 UTC [Info] Booting may take several seconds, please wait
2021-04-16 09:45:02 UTC [Info] Reading configuration files $config_files
	config_files: [
  "/var/lib/coda/config_a42bdeef.json",
  "/home/mauguzun/.mina-config/daemon.json"
]
2021-04-16 09:45:02 UTC [Info] Initializing with runtime configuration. Ledger name: "mainnet"
2021-04-16 09:45:02 UTC [Info] Using the compiled constraint constants
2021-04-16 09:45:02 UTC [Info] Found genesis proof file at $path
	path: "/home/mauguzun/.mina-config/genesis/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-04-16 09:45:02 UTC [Info] Loaded ledger from $ledger_file and genesis proof from $proof_file
	ledger_file: "/home/mauguzun/.mina-config/genesis/genesis_ledger_accounts_71d4f4a0e8c1f3e78760b989234760584969ea0144ed1a3057234f6f0e73621a.tar.gz"
	proof_file: "/home/mauguzun/.mina-config/genesis/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-04-16 09:45:02 UTC [Info] Using block producer keypair private-key password from environment variable CODA_PRIVKEY_PASS
2021-04-16 09:45:03 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: {
  "commit_id": "a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a",
  "sexp": [
    "monitor.ml.Error",
    [
      "Failure",
      "IO error: While lock file: /home/mauguzun/.mina-config/trust/LOCK: Resource temporarily unavailable"
    ],
    [
      "Raised at file \"stdlib.ml\", line 33, characters 17-33",
      "Called from file \"src/lib/rocksdb/database.ml\", line 16, characters 34-63",
      "Called from file \"src/lib/trust_system/peer_trust.ml\", line 106, characters 15-33",
      "Called from file \"src/app/cli/src/mina.ml\", line 922, characters 25-54",
      "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file \"stdlib.ml\", line 33, characters 17-33",
    "Called from file \"src/lib/rocksdb/database.ml\", line 16, characters 34-63",
    "Called from file \"src/lib/trust_system/peer_trust.ml\", line 106, characters 15-33",
    "Called from file \"src/app/cli/src/mina.ml\", line 922, characters 25-54",
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}
2021-04-16 09:45:04 UTC [Warn] Shutdown before Coda instance was created, not saving a visualization

  ☠  Mina Daemon crashed.
   The Mina Protocol developers would like to know why!

    Please:
      Open an issue:
        <https://github.com/MinaProtocol/mina/issues/new>

      Briefly describe what you were doing and attach the crash report /home/mauguzun/.mina-config/coda_crash_report_2021-04-16_09-45-03.984208.tar.gz

**Comment by psteckler** [comment]
That's the trust database lockfile (RocksDB). Did a daemon crash just before this?

(I wonder if we don't always cleanup RocksDb on termination.)

**Comment by mauguzun** [comment]
> That's the trust database lockfile (RocksDB). Did a daemon crash just before this?
> 
> (I wonder if we don't always cleanup RocksDb on termination.)
Yea, i was delete that hyperv intance :( 
,

**Comment by deepthiskumar** [comment]
Closing this one in favor of #8692 which has some more information
