### ISSUE TITLE
Failed to connect to libp2p_helper process

### ISSUE THREAD

**Issue by mauguzun** [MinaProtocol/mina#8679]
Generating crash report
	exn: {
  "commit_id": "a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a",
  "sexp": [
    "monitor.ml.Error",
    [
      "Failed to connect to libp2p_helper process",
      "RPC #2 failed: \"internal RPC error error: failed to parse multiaddr \\\"seed-one.o1test.net\\\": must begin with /\""
    ],
    [
      "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
      "Called from file \"src/lib/gossip_net/libp2p.ml\", line 148, characters 8-94",
      "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
    "Called from file \"src/lib/gossip_net/libp2p.ml\", line 148, characters 8-94",
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}
2021-04-18 06:31:37 UTC [Warn] Shutdown before Coda instance was created, not saving a visualization

[coda_crash_report_2021-04-18_06-25-06.882954.tar.gz](https://github.com/MinaProtocol/mina/files/6330601/coda_crash_report_2021-04-18_06-25-06.882954.tar.gz)

**Comment by psteckler** [comment]
I believe the peers have to be given as multiaddresses, where you've given DNS hostnames.

A multiaddress can begin with `/ip4/` or `/dns4`, for example.

**Comment by mauguzun** [comment]
> I believe the peers have to be given as multiaddresses, where you've given DNS hostnames.
> 
> A multiaddress can begin with `/ip4/` or `/dns4`, for example.

Thank for you replay, could you pls help me fix that, what shall i do?
"peers": ["seed-one.o1test.net", "seed-two.o1test.net

**Comment by TheRealAngelus** [comment]
Hi! I had the same issue. I just removed the line and it worked for me. I think node uses peers.txt. It is unnecessary to define it again in daemon.json.

**Comment by mauguzun** [comment]
> Hi! I had the same issue. I just removed the line and it worked for me. I think node uses peers.txt. It is unnecessary to define it again in daemon.json. Btw I'm a newbie :)

thank you , i will try

**Comment by mauguzun** [comment]
Hi, i did that yesterday and got new error, i opened new issue yesterday

**Comment by mauguzun** [comment]
> Hi! I had the same issue. I just removed the line and it worked for me. I think node uses peers.txt. It is unnecessary to define it again in daemon.json. Btw I'm a newbie :)

i did that and that help me ,thank you
