### ISSUE TITLE
https://codaprotocol.com/docs/getting-started is not reachable

### ISSUE THREAD

**Issue by Esser50K** [MinaProtocol/mina#8680]
I got an email recommending I should check out https://minaprotocol.com/blog/testnet-beta-retrospective-phase-2-3 to start helping with MinaProtocol. There I found a link to the getting started page at: https://codaprotocol.com/docs/getting-started. However that URL does not seem reachable.

![Screenshot 2021-04-18 at 12 33 46](https://user-images.githubusercontent.com/18497570/115144038-576d5200-a042-11eb-94d1-dcc9762bf620.png)

**Comment by timsmith1337** [comment]
Hi, did you receive this link _recently_ on the email? The blog post it refers to is dated from 2019 and all links on the `body` are surely linked to codaprotocol.com. `Getting started` links on the _header_ and _footer_ of the page is working correctly which is https://docs.minaprotocol.com/en/getting-started. In future for any problems relating to website please create an issue in https://github.com/MinaProtocol/website/issues.
