### ISSUE TITLE
Provide a layout sample for vendor CS

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#8718]

**Comment by psteckler** [comment]
```json
{
  "layout_loc":
    "File \"src/lib/mina_networking/mina_networking.ml\", line 321, characters 8-143:",
  "version_opt": null,
  "type_decl":
    "type response = (State_hash.Stable.V1.t * State_body_hash.Stable.V1.t list) option",
  "bin_io_derived": true,
  "bin_prot_rule": [
    "Option",
    [
      "Tuple",
      [
        [
          "Reference",
          [
            "Resolved",
            {
              "source_type_decl": "type t = { version: int ; t: typ }",
              "ref_rule": [
                "Record",
                [
                  { "field_name": "version", "field_rule": [ "Int" ] },
                  {
                    "field_name": "t",
                    "field_rule": [
                      "Reference",
                      [
                        "Resolved",
                        {
                          "source_type_decl": "type typ = t",
                          "ref_rule": [
                            "Reference",
                            [
                              "Resolved",
                              {
                                "source_type_decl": "type t = Field.t",
                                "ref_rule": [
                                  "Reference",
                                  [
                                    "Resolved",
                                    {
                                      "source_type_decl": "Tick.Field.t",
                                      "ref_rule": [ "String" ]
                                    }
                                  ]
                                ]
                              }
                            ]
                          ]
                        }
                      ]
                    ]
                  }
                ]
              ]
            }
          ]
        ],
        [
          "List",
          [
            "Reference",
            [
              "Resolved",
              {
                "source_type_decl": "type t = { version: int ; t: typ }",
                "ref_rule": [
                  "Record",
                  [
                    { "field_name": "version", "field_rule": [ "Int" ] },
                    {
                      "field_name": "t",
                      "field_rule": [
                        "Reference",
                        [
                          "Resolved",
                          {
                            "source_type_decl": "type typ = t",
                            "ref_rule": [
                              "Reference",
                              [
                                "Resolved",
                                {
                                  "source_type_decl": "type t = Field.t",
                                  "ref_rule": [
                                    "Reference",
                                    [
                                      "Resolved",
                                      {
                                        "source_type_decl": "Tick.Field.t",
                                        "ref_rule": [ "String" ]
                                      }
                                    ]
                                  ]
                                }
                              ]
                            ]
                          }
                        ]
                      ]
                    }
                  ]
                ]
              }
            ]
          ]
        ]
      ]
    ]
  ]
}

```

**Comment by psteckler** [comment]
Just to note, fields don't serialize to `String`, that's a dummy entry for now.

**Comment by jspada** [comment]
Is there some documentation kicking around that describes this layout formula?

Could you provide some simple examples of layout -> rust/pseudocode for some basic toy structs?

**Comment by psteckler** [comment]
> Is there some documentation kicking around that describes this layout format?

Here is the OCaml file defining the format:

  https://github.com/o1-labs/ppx_version/blob/master/src/runtime/bin_prot_layout.ml

That refers to the rules in this file: 

  https://github.com/o1-labs/ppx_version/blob/master/src/runtime/bin_prot_rule.ml

Here are some tests that give an OCaml type with their expected layout: 

  https://github.com/o1-labs/ppx_version/blob/feature/layouts-via-ppx-bin-prot/test/layouts_good.ml

**Comment by psteckler** [comment]
> Could you provide some extremely simple examples of layout -> rust/pseudocode for some basic toy structs?

I don't know Rust well enough to attempt that.

**Comment by creativcoder** [comment]
@bkase @psteckler @jspada 
In an attempt to create a layout parser in https://github.com/ChainSafe/mina-rs/pull/25, we felt a few quirks about the json layout:

1. Record rules does not contain the record name, making it difficult to generate/reference equivalent Rust types.
2. The leaf nodes of the `bin_prot_rule` json tree currently resolves to a string and not the actual type
3. json expansion of type defs is repeated quite a bit and probably that makes the type def quite large for some types (ex: external_transition.ml. Feeding external_transition layout json takes like 3 minutes to parse.

cc @willemolding

**Comment by psteckler** [comment]
As mentioned, the rules for some types, like `Field.t`, are placeholders for now.

I think it's possible to add the module path to types, including record types.

Not sure what to do with the size of the JSON. It might be possible to splice out the `Reference` indirections, though those are useful to understand where the types came from.

**Comment by psteckler** [comment]
For `Resolved` references, I can add an autogenerated module path, like:
```
"Resolved",
 {
  "source_type_decl":
  "type t = { version: int ; t: typ }",
  "source_module_path":"src/lib/mina_state/protocol_state.ml.Body.Value",
  "bin_io_derived":true,
  "ref_rule": [ Record ...
```
Does that help? @creativcoder

**Comment by psteckler** [comment]
I can probably refine that to syntax like `Protocol_state.Body.Value`

**Comment by psteckler** [comment]
We can probably compress chains of `Resolved` indirections to a single `Resolved`, which would shrink the size of the JSON.

**Comment by creativcoder** [comment]
Hey @psteckler  yes, tidying module path and compressing references and resolved subtree would reduce the complexity by a fair amount.

**Comment by willemolding** [comment]
We are making great progress with parsing a block from a layout. Currently it appears the only thing it is choking on is the `Vector_{2,4,8,16}` types. 

As previously mentioned these types use a custom serialization strategy and so a custom deserializer must be provided. This is the strategy used for the other custom serialization types (e.g. Field.t, StateHash etc.). 

Unlike the other custom strategies the Vector types appear to be generic over their elements. What this means is that even though we might know the overall strategy for serializing a vector type (e.g. serialize and write the elements sequentially with a null termination byte), the information about the types of the elements and their serialization is lost when producing a layout.

---

While I'm not sure of the feasibility of this, as a consumer of a layout file the ideal solution would be to have vector types have their own custom BinProtRule variant:
```ocaml
  | Vec of int * t
```
which would contain the length of the vec (e.g. 2,4,6,18) and the rule to be used to when deserializing the elements.

---

This is currently the main thing blocking our ability to deserialize blocks from the network and meet milestone 1 so it would be great to throw some ideas out there. Any thoughts @psteckler @creativcoder ?

**Comment by psteckler** [comment]
I'm reluctant to add special-case rules that don't correspond to the Jane Street rules.
Instead, for each OCaml-side custom serialization, at the Rust end, I would suggest matching the type involved, and invoke custom serialization code there.

The serialization of these vector types are parametric in a length. For `Vector_2`:
```ocaml
include Make.Binable (Nat.N2)
 ```
The result of these functor invocations are serializers and deserializers that are themselves parametric in the element type, because the type has a parameter `a`:
```ocaml
type 'a t = ('a, Nat.N2.n) vec
```
Presumably, you could write a family of serializers/deserializers that are parametric on the length and element type in a similar way.

The bit that I don't understand is how the serialization provided by `Make.Binable` works. Can @imeckler or @mrmr1993 shed any light?

**Comment by willemolding** [comment]
Thanks @psteckler, That seems totally reasonable as well. The trick is going to be ensuring that the rules for serializing the concrete types provided in the type parameters (is that what they are called in OCaml?) are available in the layout file.

Perhaps we could allow the `Custom` variant to carry a list of rules (similar to the Tuple rule variant). It would then be up to the author of the deserializer to match the type and consume these rules in the deserialization code.

**Comment by psteckler** [comment]
At the definition of `Vector_2`, for instance, you don't know what the element type is, of course.

Somewhere, that type gets instantiated, and maybe that's missing from the layout, as currently given.

**Comment by psteckler** [comment]
Yes, all the type parameter instantiation is known at compile-time.

The layout code is new, and there may be things I've overlooked.

**Comment by psteckler** [comment]
After discussion with Matthew, it looks like the serialization of a `Vector_n` uses a nested tuple format. For `'a Vector_2`, the rule would be:
```ocaml
Tuple [the_rule_for_a;Tuple [the_rule_for_a;Unit]]
```
For any `'a Vector_n`, the list arguments to `Tuple` have two elements, where the first element is the rule for `'a`, and the second element is either another such `Tuple` rule, or `Unit`.

@willemolding is that enough to go on?

**Comment by willemolding** [comment]
Sweet, I had managed to figure that much out already by inspecting the binary but it is great to have it confirmed. 

---

The issue still stands currently that the `the_rule_for_a` is not present in the layout. For example here is a vector_2 in the external_transition_layout:
```json
{
    "source_type_decl": "type 'a typ = 'a t",
    "source_module_path": "Vector.Vector_2",
    "bin_io_derived": false,
    "ref_rule": [
        "Custom"
    ]
}
```
As you can see it does not expand any further as to the type of `'a`. 

I don't have the OCaml knowledge or understanding of ppx_version to add it in unfortunately.
