### ISSUE TITLE
Tagged Alpha Builds on compatible

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#8719]
Andrew to setup a meeting to discuss and determine the best path forward

**Comment by lk86** [comment]
For testing the existing changes that have landed in compatible, the next steps are:
- to update the pipeline in compatible to publish alpha releases when it is tagged (similar to how the master pipeline works).
- determine a testing process (future QA Process meetings to decide this)
- announce the alpha release to adventurous folks (coordinate w/ Foundation)
- fix critical bugs and continue to add to compatible, then re-release alpha2/alpha3 etc.
- stablize and graduate the alpha to a beta release on a new release/1.1.6 branch
