### ISSUE TITLE
[Alert] Whale producer 2 in devnet did not log anything in stackdriver for > 10mins

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#8727]
The logs are present on disk so seems like some issue with the exporting
[whale2-devnet-28.log](https://github.com/MinaProtocol/mina/files/6368942/whale2-devnet-28.log)

https://console.cloud.google.com/logs/viewer?interval=CUSTOM&project=o1labs-192920&minLogLevel=0&expandAll=false&timestamp=2021-04-24T03:22:14.798000000Z&customFacets=resource.labels.pod_name,resource.labels.container_name&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22o1labs-192920%22%0Aresource.labels.location%3D%22us-east4%22%0Aresource.labels.cluster_name%3D%22coda-infra-east4%22%0Aresource.labels.namespace_name%3D%22devnet2%22%0Aresource.labels.pod_name:%22whale-block-producer-2%22%0Aresource.labels.container_name%3D%22coda%22&scrollTimestamp=2021-04-24T03:06:07.799663897Z&dateRangeStart=2021-04-24T02:50:33.761Z&dateRangeEnd=2021-04-24T03:06:33.787Z

**Comment by bkase** [comment]
We want to check if the log file contains lines of log at the loglevel that stackdriver looks at.

We need to think about how to make this alert not flaky in the world where stackdriver seems to be flaky

**Comment by bkase** [comment]
We could:

Increase the threshold above 10minutes, and consider uploading logs elsewhere as well

**Comment by deepthiskumar** [comment]
This is not a stackdriver issue. `log-level` for block producers is `Info` and there was no info log for 10 minutes probably because of low activity
