### ISSUE TITLE
Invalid_curvepoint

### ISSUE THREAD

**Issue by orefkov** [MinaProtocol/mina#8762]
I has many errors for snark worker in log: "Error submitting work ..... Zexe_backend_common.Curve.Make(BaseField)(ScalarField)(Params)(C).Affine.Stable.V1.Invalid_curvepoint()".
What is it and how I can fix it?
There is log
`Apr 29 16:43:35 mid mina[2883]: {"timestamp":"2021-04-29 13:43:35.660298Z","level":"Error","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 157, characters 8-20"},"message":"Error submitting work: ((rpc_error\n  (Bin_io_exn\n   ((location \"server-side rpc query un-bin-io'ing\")\n    (exn\n     (\"Zexe_backend_common.Curve.Make(BaseField)(ScalarField)(Params)(C).Affine.Stable.V1.Invalid_curve_point(_)\")))))\n (connection_description (\"Client connected via TCP\" (127.0.0.1 8301)))\n (rpc_tag submit_work) (rpc_version 1))","metadata":{"pid":8641,"process":"Snark Worker"}}
`

**Comment by aneesharaines** [comment]
@orefkov  can you provide the logs to help us understand the issue better?  Thanks!

**Comment by psteckler** [comment]
`mina client export-local-logs` will generate a file with logs.

**Comment by orefkov** [comment]
I turn off snark worker some days ago.
Exported logs: https://drive.google.com/file/d/1bQoe88nvgul9nbWdtPMuyED5cbK8h99i/view?usp=sharing

**Comment by shimkiv** [comment]
Closing this issue because of being inactive for long time.
Please feel free to open another ticket should you experience any further issues.
