### ISSUE TITLE
Invalid proof generation

### ISSUE THREAD

**Issue by orefkov** [MinaProtocol/mina#8763]
What could lead to such mistakes and what to do to avoid them?
```

Apr 29 14:32:06 mid mina[2883]: {"timestamp":"2021-04-29 11:32:05.820297Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 201, characters 10-21"},"message":"SNARK work $work_ids received from $address. Starting proof generation","metadata":{"address":"127.0.0.1:8301","pid":8641,"process":"Snark Worker","work_ids":[786227321,1071283144]}}
Apr 29 14:32:14 mid mina[2883]: 2021-04-29 11:32:14 UTC [Error] Verifier stderr: "bad verify: linearization_check\n"
Apr 29 14:32:15 mid mina[2883]: 2021-04-29 11:32:15 UTC [Error] Error verifying transaction snark from "Local": $error
Apr 29 14:32:15 mid mina[2883]:         error: {
Apr 29 14:32:15 mid mina[2883]:   "commit_id": "a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a",
Apr 29 14:32:15 mid mina[2883]:   "string": "Invalid proof"
Apr 29 14:32:15 mid mina[2883]: }
Apr 29 14:32:15 mid mina[2883]: 2021-04-29 11:32:15 UTC [Error] Error verifying transaction snark from "Local": $error
Apr 29 14:32:15 mid mina[2883]:         error: {
Apr 29 14:32:15 mid mina[2883]:   "commit_id": "a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a",
Apr 29 14:32:15 mid mina[2883]:   "string": "Invalid proof"
Apr 29 14:32:15 mid mina[2883]: }

```

**Comment by aneesharaines** [comment]
@orefkov - do you have logs that you could share to help debug this issue?

**Comment by aneesharaines** [comment]
@imeckler - any idea on what could be happening here?

**Comment by mkoppanen** [comment]
I think I encountered this during today:
```
$ grep 'Invalid proof' mina_logs.out | wc -l
13796
```
The node seemed to stop producing snarks. I took steps:

1. Stop the node
2. Remove .mina-config/snark_pool
3. Start the node

And it seems to be back to normal operation now. Let me know if there is any info I can provide.

**Comment by mkoppanen** [comment]
Spoke too soon, looks like my node consistently shows this now:

2021-06-09 07:46:23 UTC [Error] Error verifying transaction snark from "Local": $error
	error: {
  "commit_id": "a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a",
  "string": "Invalid proof"
}
2021-06-09 07:46:23 UTC [Error] Error verifying transaction snark from "Local": $error
	error: {
  "commit_id": "a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a",
  "string": "Invalid proof"
}

**Comment by shimkiv** [comment]
@deepthiskumar can you please help with this issue?

**Comment by mrmr1993** [comment]
We now have a new proof system that hopefully will not encounter this issue. Closing, but please re-open if you're seeing it after the 3.0.0 release.
