### ISSUE TITLE
Integration test: local execution engine

### ISSUE THREAD

**Issue by QuiteStochastic** [MinaProtocol/mina#8819]
Implement the local execution engine for the new integration testing framework. This engine should implement the existing engine interface to run nodes locally, utilizing minikube, docker-compose, or raw docker (depending on difficulty and required level of control). Importantly, this local execution engine must support all of the existing features in the interface, including 

- [ ] starting/stopping nodes dynamically, 
- [ ] sending GraphQL requirests to nodes, 
- [ ] streaming event logs back from nodes for processing
- [ ] spawning nodes based on test configuration

**Comment by joseandro** [comment]
@yorickvP what's the latest on this ticket?

**Comment by yorickvP** [comment]
This work ended up in the tweag-cleanup branch. e4fa0d5, 6593cda

**Comment by Firobe** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Velocity-62264fddc441a100183f7f86/issues/MinaProtocol/mina/8819?planning-poker) with ZenHub @balsoft @yorickvP

**Comment by mrmr1993** [comment]
This work was completed and is now used in CI. Closing.
