### ISSUE TITLE
Retrieve multi-accounts in one request

### ISSUE THREAD

**Issue by crackerli** [MinaProtocol/mina#8858]
Mina has such graphql interface:
query MyQuery {
&nbsp;&nbsp;accounts(publicKey: "B62qismRE8v8sPKR8hPSUzdyHLwXu1nCXZuGuWDWsbb6ZDxMLWAAnnk") {. 
&nbsp;&nbsp;&nbsp;&nbsp;balance {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;total
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;publicKey
&nbsp;&nbsp;&nbsp;&nbsp;}
}

it returns:
{
&nbsp;&nbsp;"data": { 
&nbsp;&nbsp;&nbsp;&nbsp;"accounts": [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"balance": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"total": "2315500000"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"publicKey": "B62qismRE8v8sPKR8hPSUzdyHLwXu1nCXZuGuWDWsbb6ZDxMLWAAnnk"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;]
&nbsp;&nbsp;}
}

But with it, we can only get one account info each time. If I want to get multi-accounts info, I need to do the request multi-times.

Can the node graphql server provider the extra api look like:
&nbsp;&nbsp;query MyQuery {
&nbsp;&nbsp;&nbsp;&nbsp;accounts(publicKey: "**_address1;address2;address3_**") {
&nbsp;&nbsp;&nbsp;&nbsp;balance {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;total
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;publicKey
&nbsp;&nbsp;}
}

Then I can get all the info about the accounts I want in one request.

**Comment by vanphandinh** [comment]
Why don't query like this?

`  query batchBalance {
    
  B62qni3bf3gZ1EEL1AzYXnUvxfQELqM4eVSpQs2CZvD1UyscVxxxxxx: accounts (publicKey: "B62qni3bf3gZ1EEL1AzYXnUvxfQELqM4eVSpQs2CZvD1UyscVxxxxxx") {
    balance {
      total
    }
  }
  ,
  B62qkiJuTwdJBARAPGAvStuEa37kZVZPyDrQoUCuM7WQUmZZyyyyyyy: accounts (publicKey: "B62qkiJuTwdJBARAPGAvStuEa37kZVZPyDrQoUCuM7WQUmZZyyyyyyy") {
    balance {
      total
    }
  }
  
  }`

**Comment by shimkiv** [comment]
Mentioned query above will work. Thank you.
