### ISSUE TITLE
`timing_info` in archive database not updated

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#8862]
In the archive database, the `timing_info` table is populated with the genesis ledger accounts, but is never updated. It should be updated when a new account is created.

There are Rosetta queries that rely on this table, so it should be kept up-to-date.

**Comment by mrmr1993** [comment]
Looks like it is an issue (see [here](https://github.com/MinaProtocol/mina/blob/f88edb440e321114e26f7691e599adab30ce16cd/src/app/rosetta/lib/account.ml#L118)). Probably only needs an `Option.value ~default:Untimed` or such.

**Comment by aneesharaines** [comment]
Ok, thanks @mrmr1993 - moving this out to revisit when creating time locked accounts
