### ISSUE TITLE
Graphql calls are taking a long time 

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#8867]
A script that gets the current node version is taking a long time indicating a long async cycle there:
example profile:
started=2021-04-02 17:49:32 -0500 ended=2021-04-02 17:49:52 -0500: 20.21904
started=2021-04-02 17:53:09 -0500 ended=2021-04-02 17:53:31 -0500: 21.273059
started=2021-04-02 17:55:13 -0500 ended=2021-04-02 17:55:18 -0500: 5.252327
started=2021-04-02 17:55:20 -0500 ended=2021-04-02 17:55:28 -0500: 7.739734
started=2021-04-02 17:55:45 -0500 ended=2021-04-02 17:56:05 -0500: 19.765823
started=2021-04-02 17:58:39 -0500 ended=2021-04-02 17:58:48 -0500: 9.387711
started=2021-04-02 17:59:29 -0500 ended=2021-04-02 17:59:44 -0500: 14.966712
started=2021-04-02 18:02:00 -0500 ended=2021-04-02 18:02:09 -0500: 9.278158
started=2021-04-02 18:02:11 -0500 ended=2021-04-02 18:02:32 -0500: 20.342541
started=2021-04-02 18:07:02 -0500 ended=2021-04-02 18:07:11 -0500: 8.72624
started=2021-04-02 18:07:27 -0500 ended=2021-04-02 18:07:32 -0500: 5.094603
started=2021-04-02 18:07:32 -0500 ended=2021-04-02 18:07:39 -0500: 6.61814
started=2021-04-02 18:07:48 -0500 ended=2021-04-02 18:08:08 -0500: 19.820103
started=2021-04-02 18:09:14 -0500 ended=2021-04-02 18:09:18 -0500: 3.502407
started=2021-04-02 18:10:15 -0500 ended=2021-04-02 18:10:20 -0500: 4.928087

https://discord.com/channels/484437221055922177/696794400998817793/827683564173787146

We can start by trying to repro the issue under heavy load on an long running network (mainNet or devNet).  

Todo:  create a script that makes this call at high frequency, attach a node to a current long standing network and run there to get the response times.  If we're seeing similar long response times we can

**Comment by psteckler** [comment]
I ran Jiawei's script with
 - a demo node
 - a mainnet seed
 - devnet2 whale
 - devnet2 fish

For the demo node, the time was usually around 2/1000 of a second. For all the cloud nodes, the time was around 1/4 second.

**Comment by aneesharaines** [comment]
Not seeing the >1s times that were reported.    @ghost-not-in-the-shell suggestion to add the response times as metrics to to watchdog to monitor.

**Comment by garethtdavies** [comment]
Can you clarify if this is a specific issue with getting the version or the more general "GraphQL is really slow"

**Comment by psteckler** [comment]
> Can you clarify if this is a specific issue with getting the version or the more general "GraphQL is really slow" to respond to queries?

The fast times that I observed with the getting the version suggests it's a more general problem. The `version` calls just returns a constant.
