### ISSUE TITLE
[MacOS/Docker] Mina Daemon crashes

### ISSUE THREAD

**Issue by MinaFMN** [MinaProtocol/mina#8878]
Hello,

I followed documentation using docker on Mac OS (Big Sur) on an Macbook Air M1 16Gb RAM.

Everything is going fine until I run the last command to start up the Mina Daemon which crashes.

I attached the crash log file for analysis

[coda_crash_report_2021-05-13_16-37-35.483697.tar.gz](https://github.com/MinaProtocol/mina/files/6473857/coda_crash_report_2021-05-13_16-37-35.483697.tar.gz)

**Comment by garethtdavies** [comment]
There are currently no compatible builds for ARM so it's not going to work on the M1.

**Comment by MinaFMN** [comment]
Thanks for you quick reply. That's too bad. Hope it might come in the future ;)
