### ISSUE TITLE
Sidecar gets HTTP 500: Internal Server Error when sending data

### ISSUE THREAD

**Issue by jrwashburn** [MinaProtocol/mina#8886]
Sidecar can fail to report due to receiving and HTTP 500 error back from the node.

Apr 18 19:58:19 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 11240...
Apr 18 19:55:19 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 11240...
Apr 18 19:53:08 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data
Apr 18 19:53:08 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 11238...
Apr 18 19:50:08 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 11238...
Apr 18 19:47:57 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data
Apr 18 19:47:57 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 11237...
Apr 18 19:44:57 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 11237...
Apr 18 19:42:45 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data
Apr 18 19:42:45 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 11236...
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]: ERROR:root:Sleeping for 30s and trying again
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]: urllib.error.HTTPError: HTTP Error 500: Internal Server Error
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:   File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:     result = func(*args)
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:   File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:     return self._call_chain(*args)
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:   File "/usr/lib/python3.9/urllib/request.py", line 561, in error
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:     response = self.parent.error(
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:   File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:     response = meth(req, response)
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:   File "/usr/lib/python3.9/urllib/request.py", line 523, in open
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:     return opener.open(url, data, timeout)
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:   File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:     response = urllib.request.urlopen(request)
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:   File "/usr/local/bin/mina-bp-stats-sidecar", line 122, in send_update
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:     send_update(block_data, current_finalized_tip)
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]:   File "/usr/local/bin/mina-bp-stats-sidecar", line 153, in <module>
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]: Traceback (most recent call last):
Apr 18 19:42:15 mina-mainnet-vt-1 python3[35040]: ERROR:root:HTTP Error 500: Internal Server Error
Apr 18 19:40:04 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data
Apr 18 19:40:04 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 11236...
Apr 18 19:37:04 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 11236...
Apr 18 19:34:52 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data
Apr 18 19:34:52 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 11234...
Apr 18 19:31:52 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 11234...
Apr 18 19:29:41 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data
Apr 18 19:29:41 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 11232...
Apr 18 19:26:41 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 11232...
Apr 18 19:24:30 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data
Apr 18 19:24:30 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 11232...
Apr 18 19:21:30 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 11232...
Apr 18 19:19:19 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data
Apr 18 19:19:18 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 11232...
Apr 18 19:16:18 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 11232...
Apr 18 19:14:07 mina-mainnet-vt-1 python3[35040]: INFO:root:Got block data
Apr 18 19:14:07 mina-mainnet-vt-1 python3[35040]: INFO:root:Fetching block 11231...
Apr 18 19:11:07 mina-mainnet-vt-1 python3[35040]: INFO:root:Finished! New tip 11231...

**Comment by shivlim** [comment]
Have same error here and misses reporting block

May 23 07:57:58 mina-bp-stats-sidecar[9979]: INFO:root:Finished! New tip 22999...
May 23 08:00:58  mina-bp-stats-sidecar[9979]: INFO:root:Fetching block 22999...
May 23 08:00:58 mina-bp-stats-sidecar[9979]: INFO:root:Got block data
May 23 08:00:59 ERROR:root:HTTP Error 500: Internal Server Error
May 23 08:00:59  Traceback (most recent call last):
May 23 08:00:59  File "/usr/local/bin/mina-bp-stats-sidecar", line 159, in <module>
May 23 08:00:59     send_update(block_data, current_finalized_tip)
May 23 08:00:59   File "/usr/local/bin/mina-bp-stats-sidecar", line 122, in send_update
May 23 08:00:59     response = urllib.request.urlopen(request)
May 23 08:00:59   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
May 23 08:00:59      return opener.open(url, data, timeout)
May 23 08:00:59    File "/usr/lib/python3.6/urllib/request.py", line 532, in open
May 23 08:00:59     response = meth(req, response)
May 23 08:00:59  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
May 23 08:00:59      'http', request, response, code, msg, hdrs)
May 23 08:00:59   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
May 23 08:00:59     return self._call_chain(*args)
May 23 08:00:59   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
May 23 08:00:59     result = func(*args)
May 23 08:00:59   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
May 23 08:00:59      raise HTTPError(req.full_url, code, msg, hdrs, fp)
May 23 08:00:59  urllib.error.HTTPError: HTTP Error 500: Internal Server Error
May 23 08:00:59 ERROR:root:Sleeping for 30s and trying again
May 23 08:01:50 mina-bp-stats-sidecar[9979]: INFO:root:Found new head at 23013
May 23 08:01:50 mina-bp-stats-sidecar[9979]: INFO:root:Continuing with finalized tip block of 23001
May 23 08:01:50 mina-bp-stats-sidecar[9979]: INFO:root:Fetching block 23001...
May 23 08:01:50  mina-bp-stats-sidecar[9979]: INFO:root:Got block data
May 23 08:01:51 mina-bp-stats-sidecar[9979]: INFO:root:Finished! New tip 23001...

**Comment by jrwashburn** [comment]
Closing; new uptime system so this will be irrelevant.
