### ISSUE TITLE
Watchdog pod eviction

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#8887]
Watchdog pod on devnet got evicted triggering a bunch of alerts.

|Message | Reason | First Seen | Last Seen | Count |  
|-- | -- | -- | -- | -- | --|
|Started container watchdog | Started | May 16, 2021, 1:52:34 PM | May 16, 2021, 1:52:34 PM | 1 |  
|Created container watchdog | Created | May 16, 2021, 1:52:33 PM | May 16, 2021, 1:52:33 PM | 1 |  
Successfully pulled image "gcr.io/o1labs-192920/watchdog:0.4.11" | Pulled | May 16, 2021, 1:52:10 PM | May 16, 2021, 1:52:10 PM | 1 |  
Cancelling deletion of Pod devnet2/watchdog-764f4647bb-wptmh | TaintManagerEviction | May 12, 2021, 12:04:59 PM | May 16, 2021, 1:51:48 PM | 9 |  
Pulling image "gcr.io/o1labs-192920/watchdog:0.4.11" | Pulling | May 16, 2021, 1:51:40 PM | May 16, 2021, 1:51:40 PM | 1 |  
Started container watchdog | Started | May 16, 2021, 1:28:54 PM | May 16, 2021, 1:28:54 PM | 1 |  
Created container watchdog | Created | May 16, 2021, 1:28:54 PM | May 16, 2021, 1:28:54 PM | 1 |  
Successfully pulled image "gcr.io/o1labs-192920/watchdog:0.4.11" | Pulled | May 16, 2021, 1:28:31 PM | May 16, 2021, 1:28:31 PM | 1 |  
Pulling image "gcr.io/o1labs-192920/watchdog:0.4.11" | Pulling | May 16, 2021, 1:27:55 PM | May 16, 2021, 1:27:55 PM | 1 |

**Comment by deepthiskumar** [comment]
From the [docs](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)- a kubernetes node will be mark as tainted if any of the following conditions are met and the pod that's running on the node gets evicted unless we specify `tolerations` for taints in the our deployment i.e., saying it is ok to continue running the pod even if the node was marked as tainted (which we don't)

```
node.kubernetes.io/not-ready: Node is not ready. This corresponds to the NodeCondition Ready being "False".
node.kubernetes.io/unreachable: Node is unreachable from the node controller. This corresponds to the NodeCondition Ready being "Unknown".
node.kubernetes.io/memory-pressure: Node has memory pressure.
node.kubernetes.io/disk-pressure: Node has disk pressure.
node.kubernetes.io/pid-pressure: Node has PID pressure.
node.kubernetes.io/network-unavailable: Node's network is unavailable.
node.kubernetes.io/unschedulable: Node is unschedulable.
node.cloudprovider.kubernetes.io/uninitialized: When the kubelet is started with "external" cloud provider, this taint is set on a node to mark it as unusable. After a controller from the cloud-controller-manager initializes this node, the kubelet removes this taint.
```

Since this is happening a lot with watchdog and only on devnet, could be due to the watchdog process itself and probably from some change that was recently introduced

**Comment by aneesharaines** [comment]
Next steps:  diff the versions between devnet and mainNet to see what could be causing the resource contention.  cc: @ghost-not-in-the-shell

**Comment by deepthiskumar** [comment]
Looks like some taints are by default tolerated: This is from the watchdog spec from cluster logs
```
tolerations: [
     0: {
      effect: "NoExecute"       
      key: "node.kubernetes.io/not-ready"       
      operator: "Exists"       
      tolerationSeconds: 300       
     }
     1: {
      effect: "NoExecute"       
      key: "node.kubernetes.io/unreachable"       
      operator: "Exists"       
      tolerationSeconds: 300       
     }
    ]
```

1. One instance of watchdog crashing when querying the node status

https://console.cloud.google.com/logs/viewer?interval=CUSTOM&project=o1labs-192920&minLogLevel=0&expandAll=false&timestamp=2021-05-20T01:37:53.615000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22o1labs-192920%22%0Aresource.labels.location%3D%22us-east4%22%0Aresource.labels.cluster_name%3D%22coda-infra-east4%22%0Aresource.labels.namespace_name%3D%22devnet2%22%0Aresource.labels.pod_name:%22watchdog-%22%0Aresource.labels.container_name%3D%22watchdog%22%0A&scrollTimestamp=2021-05-17T21:26:52.761517411Z&dateRangeStart=2021-05-17T20:00:48.000Z&dateRangeEnd=2021-05-17T21:26:53.000Z

2. chekcing google bucket 
3.

**Comment by deepthiskumar** [comment]
No crashes seen after the pod resources were increased.
