### ISSUE TITLE
Staking ledger dumping automation name formatting

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#8891]
(Some) of the delegation policy tools expect the following naming scheme (modulo the extra md5, which they will):

```
staking-<epoch#>-<hash>-<md5>.json
```

We should adjust the automation to always upload with this naming scheme and overwrite existing files. To clarify here are all the components of the file:

1. The string "staking"
2. The current epoch# for the staking ledger (you can compute by looking at the ((current time - genesis time) / 3min) / 7140 (the # of slots per epoch)
3. The staking ledger hash
4. An md5 sum of the contents of the JSON file

Why did we add the md5 sum?

This covers the case where different nodes _may_ accidentally be uploading slightly different files for the same staking ledger. At least in that case, we won't lose any data.

**Comment by QuiteStochastic** [comment]
what about for the next epoch ledger, whats the name scheme for that?
