### ISSUE TITLE
the label in consensus subcircuit is wrong

### ISSUE THREAD

**Issue by woodstock-xkx** [MinaProtocol/mina#8905]
https://github.com/MinaProtocol/mina/blob/d2a75095d3a93bcfcedfe31c3311ed68e28dbb33/src/lib/consensus/proof_of_stake.ml#L2313

It should be "larger" rather than "less".

**Comment by woodstock-xkx** [comment]
@deepthiskumar

**Comment by mrmr1993** [comment]
Fixed in PR https://github.com/MinaProtocol/mina/pull/15997. Closing.
