### ISSUE TITLE
Mina Daemon Crash Logs on Linux Distro Ubuntu 20.04 (DigitalOcean c-8-16gib)

### ISSUE THREAD

**Issue by leafyshark** [MinaProtocol/mina#8930]
_crash_summary.json_
**{
   "OS_type":"Unix",
   "Release":"5.4.0-73-generic",
   "Machine":"x86_64",
   "Sys_name":"Linux",
   "Exception":{
      "commit_id":"a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a",
      "sexp":[
         "monitor.ml.Error",
         [
            "Failure",
            "IO error: While lock file: /root/.mina-config/trust/LOCK: Resource temporarily unavailable"
         ],
         [
            "Raised at file \"stdlib.ml\", line 33, characters 17-33",
            "Called from file \"src/lib/rocksdb/database.ml\", line 16, characters 34-63",
            "Called from file \"src/lib/trust_system/peer_trust.ml\", line 106, characters 15-33",
            "Called from file \"src/app/cli/src/mina.ml\", line 922, characters 25-54",
            "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
            "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
            "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
            "Caught by monitor coda"
         ]
      ],
      "backtrace":[
         "Raised at file \"stdlib.ml\", line 33, characters 17-33",
         "Called from file \"src/lib/rocksdb/database.ml\", line 16, characters 34-63",
         "Called from file \"src/lib/trust_system/peer_trust.ml\", line 106, characters 15-33",
         "Called from file \"src/app/cli/src/mina.ml\", line 922, characters 25-54",
         "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
         "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
         "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
      ]
   },
   "Command":"Command: (mina daemon --generate-genesis-proof true --peer-list-url\n https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt)",
   "Coda_branch":"master",
   "Coda_commit":"a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a"
}**

_crash_status.json_
**"Shutdown before Coda instance was created"**

**Comment by shimkiv** [comment]
https://github.com/MinaProtocol/mina/issues/8692
