### ISSUE TITLE
caml_bigint_256_to_bytes does not perform serialization

### ISSUE THREAD

**Issue by jspada** [MinaProtocol/mina#8956]
We have encountered this when providing documentation for the Rust implementation of Mina.

The `caml_bigint_256_to_bytes` function which is called by `bin_prot` when serializing the big integers of field elements takes a copy of the `BigInteger256` structure without serializing it.

https://github.com/MinaProtocol/mina/blob/91d6d536345f7e313b73fcb78bdea657ff584b72/src/lib/marlin_plonk_bindings/stubs/src/bigint_256.rs#L109

This means that for hosts with different endianness `bin_prot` will produced different results.

Speaking with Matthew the code has a check to only allow Mina to run on little-endian machine.   Thus, the protocol packets have field elements in little-endian.

In order to proceed with any 3rd party implementations we need to agree on the correct network representation for the various protocol messages and types.  For big integers there are a few possibilities:
  1. Use big-endian (aka network byte order) everywhere
  2. Use little-endian everywhere
  3. Use whatever the current mainnet uses (could be a mixture)
  
(1) is what's normally used by protocols, but this would require a lot of code changes and could be complex and disruptive to release
(2) the same as (1), but use little-endian, which is uncommon for network order
(3) would be the least disruptive change to the code

We need to decide which path to take.

If we chose (3), then since the protocol currently uses little-endian for field elements we would stick with this.  If so, then we could update `caml_bigint_256_to_bytes` to call the canonical serialization available in the `marlin` code for `BigInteger256`.  The result should be that both little-endian and big-endian machine both serialize big integers through `bin_prot` the same way.

**Comment by mrmr1993** [comment]
@psteckler and I discussed something similar shortly before mainnet, but we found we couldn't (at least, easily) change the serialisation of field elements without changing the encodings of public keys etc. At the time, we decided to stick with the status quo to avoid changing the format of public keys after people had already generated theirs.

That's not to say that we shouldn't do this, but we will have to disentangle different serialisations if we want to avoid breaking public keys etc.

**Comment by mimoo** [comment]
my 2 cents: I think it doesn't matter much as long as we agree and document how things are serialized. FWIW I've seen little-endian being used in other places in crypto: https://datatracker.ietf.org/doc/html/rfc8032#section-3.1

**Comment by jspada** [comment]
@mrmr1993 - approach (3) is not proposing the change the serialization.  It's proposing to leave it whatever it is currently (little-endian), but to make sure to call the serialization method to explicitly put it in little-endian format.  The result should be that for existing litttle-endian machines it stays in the same order and that for big-endian machines it's put into little-endian order, which is the issue to be fixed.
