### ISSUE TITLE
Update deb dependencies for newer Ubuntu/Debian versions

### ISSUE THREAD

**Issue by ozppupbg** [MinaProtocol/mina#8959]
Hello,

currently I get an error message similar to this one when trying to install mina-mainnet on any reasonably recent Debian (buster) or Ubuntu (20.01):
> The following packages have unmet dependencies:
>  mina-mainnet :
> * Depends: libffi6 but it is not installable
> * Depends: libjemalloc1 but it is not installable
> * Depends: libprocps6 but it is not installable

The packages have been updated to libffi7, libjemalloc2 and libprocps7/8 respectively (depending on the platform and version).
The actually available packages are currently for example:
**Ubuntu 20.01:**
> \# apt search libffi7
> libffi7/focal,focal,now 3.3-4 amd64 [installed]
>   Foreign Function Interface library runtime
> 
> \# apt search libjemalloc2
> libjemalloc2/focal,focal 5.2.1-1ubuntu1 amd64
>   general-purpose scalable concurrent malloc(3) implementation
> 
> \# apt search libprocps8
> libprocps8/focal-updates,focal-updates 2:3.3.16-1ubuntu2.1 amd64 [upgradable from: 2:3.3.16-1ubuntu2]

**Debian buster:**

> \# apt search libffi6
> libffi6/stable,stable 3.2.1-9 i386
>   Foreign Function Interface library runtime
> 
> \# apt search libjemalloc2
> libjemalloc2/stable,stable 5.1.0-3 i386
>   general-purpose scalable concurrent malloc(3) implementation
> 
> \# apt search libprocps7
> libprocps7/stable,stable 2:3.3.15-2 i386
>   library for accessing process information from /proc

Can you please update the packages or provide packages for recent versions of Debian/Ubuntu?

Thank you!

**Comment by SuriViruS** [comment]
Yeah I tried to set it up on lubuntu (latest) but I presume we have to try ubuntu 18.04

**Comment by timsmith1337** [comment]
```
For ubuntu 20.04:

cd
mkdir -p  #deps
cd deps
sudo apt update
wget http://de.archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
wget http://de.archive.ubuntu.com/ubuntu/pool/universe/j/jemalloc/libjemalloc1_3.6.0-11_amd64.deb
wget http://archive.ubuntu.com/ubuntu/pool/main/p/procps/libprocps6_3.3.12-3ubuntu1_amd64.deb
sudo dpkg -i *.deb
cd
rm -rf deps
```

Source Aki: [Discord](https://discord.com/channels/484437221055922177/583400552487059546/822269019687354418)

**Comment by shimkiv** [comment]
Closing as no longer relevant.
