### ISSUE TITLE
 Mina Daemon crashed after IO error

### ISSUE THREAD

**Issue by hunzai** [MinaProtocol/mina#8962]
**Command:**
When I ran `mina daemon -peer-list ~/peers.txt -run-snark-worker $MINA_PUBLIC_KEY -snark-worker-fee 0.000960000` the daemon crashed

**Report:**
I am getting the following crash report 

`2021-05-30 16:09:28 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: {
  "commit_id": "a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a",
  "sexp": [
    "monitor.ml.Error",
    [
      "Failure",
      "IO error: While lock file: /root/.mina-config/trust/LOCK: Resource temporarily unavailable"
    ],
    [
      "Raised at file \"stdlib.ml\", line 33, characters 17-33",
      "Called from file \"src/lib/rocksdb/database.ml\", line 16, characters 34-63",
      "Called from file \"src/lib/trust_system/peer_trust.ml\", line 106, characters 15-33",
      "Called from file \"src/app/cli/src/mina.ml\", line 922, characters 25-54",
      "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file \"stdlib.ml\", line 33, characters 17-33",
    "Called from file \"src/lib/rocksdb/database.ml\", line 16, characters 34-63",
    "Called from file \"src/lib/trust_system/peer_trust.ml\", line 106, characters 15-33",
    "Called from file \"src/app/cli/src/mina.ml\", line 922, characters 25-54",
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}
2021-05-30 16:09:28 UTC [Warn] Shutdown before Coda instance was created, not saving a visualization

  ☠  Mina Daemon crashed.
   The Mina Protocol developers would like to know why!

    Please:
      Open an issue:
        <https://github.com/MinaProtocol/mina/issues/new>

      Briefly describe what you were doing and attach the crash report /root/.mina-config/coda_crash_report_2021-05-30_16-09-28.341811.tar.gz

**Log**

`{"OS_type":"Unix","Release":"5.4.0-73-generic","Machine":"x86_64","Sys_name":"Linux","Exception":{"commit_id":"a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a","sexp":["monitor.ml.Error",["Failure","IO error: While lock file: /root/.mina-config/trust/LOCK: Resource temporarily unavailable"],["Raised at file \"stdlib.ml\", line 33, characters 17-33","Called from file \"src/lib/rocksdb/database.ml\", line 16, characters 34-63","Called from file \"src/lib/trust_system/peer_trust.ml\", line 106, characters 15-33","Called from file \"src/app/cli/src/mina.ml\", line 922, characters 25-54","Called from file \"src/deferred0.ml\", line 56, characters 64-69","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47","Caught by monitor coda"]],"backtrace":["Raised at file \"stdlib.ml\", line 33, characters 17-33","Called from file \"src/lib/rocksdb/database.ml\", line 16, characters 34-63","Called from file \"src/lib/trust_system/peer_trust.ml\", line 106, characters 15-33","Called from file \"src/app/cli/src/mina.ml\", line 922, characters 25-54","Called from file \"src/deferred0.ml\", line 56, characters 64-69","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47"]},"Command":"Command: (mina daemon -peer-list-file /root/peers.txt -run-snark-worker\n B62qkNTZDrgLHsWvWnm4G6vwNsuY8zgk7RuXSJrkGiFynvUVzgCZ5wk -snark-worker-fee\n 0.000960000)","Coda_branch":"master","Coda_commit":"a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a"}`
    `

**Comment by shimkiv** [comment]
https://github.com/MinaProtocol/mina/issues/8692
