### ISSUE TITLE
Crash occurs on MacBook Air M1 with Docker

### ISSUE THREAD

**Issue by maxpanki** [MinaProtocol/mina#8970]
I was trying to install mina on my MacBook and faced an issue when entering a `docker logs -f mina` command. As it was written in the docs I am opening an issue. Please refer to the attached files for more information. If you have any suggestions please let me know.
[coda_crash_report_2021-06-02_18-40-39.431449.tar.gz](https://github.com/MinaProtocol/mina/files/6586738/coda_crash_report_2021-06-02_18-40-39.431449.tar.gz)

**Comment by shimkiv** [comment]
@maxpanki can you please try it with the most recent Mina Daemon release version?

**Comment by LuisMalhadas** [comment]
Macbook M1 Max with all resources available allocated to docker:

sudo docker run --name mina -d \
-p 8302:8302 \
-e MINA_PRIVKEY_PASS="password" \
--restart=always \
--mount "type=bind,source=$(pwd)/keys,dst=/keys,readonly" \                
--mount "type=bind,source=$(pwd)/.mina-config,dst=/root/.mina-config" \
--platform linux/amd64 \
minaprotocol/mina-daemon:1.3.2beta2-6e4c7fc-bullseye-mainnet \
daemon \
--peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt \
--block-producer-key /keys/my-wallet \
--insecure-rest-server \
--file-log-level Debug \
--log-level Info



[ERROR] Entrypoint script /entrypoint.d/. is not a regular file, ignoring
[ERROR] Entrypoint script /entrypoint.d/.. is not a regular file, ignoring
2022-08-29 16:50:08 UTC [Info] Mina daemon is booting up; built with commit "6e4c7fc28157b7316122cdb341c18aca32398526" on branch "release/1.3.2"
2022-08-29 16:50:08 UTC [Info] Created daemon lockfile "/root/.mina-config/.mina-lock"
2022-08-29 16:50:08 UTC [Info] Registering async shutdown handler: "Remove daemon lockfile"
2022-08-29 16:50:08 UTC [Info] Daemon will expire at "2024-12-10 14:00:00-07:00"
2022-08-29 16:50:08 UTC [Info] Booting may take several seconds, please wait
2022-08-29 16:50:08 UTC [Info] Reading configuration files $config_files
	config_files: [ "/var/lib/coda/config_6e4c7fc2.json", "/root/.mina-config/daemon.json" ]
2022-08-29 16:50:08 UTC [Warn] Could not read configuration from "/root/.mina-config/daemon.json"
2022-08-29 16:50:08 UTC [Info] Initializing with runtime configuration. Ledger name: "mainnet"
2022-08-29 16:50:08 UTC [Info] Using the compiled constraint constants
2022-08-29 16:50:08 UTC [Info] Loaded genesis ledger from $ledger_file
	ledger_file: "/root/.mina-config/genesis/genesis_ledger_accounts_71d4f4a0e8c1f3e78760b989234760584969ea0144ed1a3057234f6f0e73621a.tar.gz"
Using block producer keypair private-key password from environment variable MINA_PRIVKEY_PASS
Transaction_snark.system: 1.625m
2022-08-29 16:52:50 UTC [Info] Setting current protocol version to "2.0.0" from compile-time config
2022-08-29 16:52:50 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: {
  "commit_id": "6e4c7fc28157b7316122cdb341c18aca32398526",
  "sexp": [
    "monitor.ml.Error",
    [
      "Writer error from inner_monitor",
      [
        "Unix.Unix_error", "Broken pipe", "writev_assume_fd_is_nonblocking",
        ""
      ],
      [
        "writer",

[
          [ "id", "6" ],
          [
            "fd",
            [
              [ "file_descr", "26" ],
              [
                "info",
                [
                  "child process",
                  [
                    "stdin",
                    [ "pid", "102" ],
                    [ "prog", "/proc/40/exe" ],
                    [ "args", [ "parallel-worker" ] ]
                  ],
                  "src/process.ml:62:17"
                ]
              ],
              [ "kind", "Fifo" ],
              [ "supports_nonblock", "true" ],
              [ "have_set_nonblock", "true" ],
              [ "state", [ "Open", "Empty" ] ],
              [
                "watching",
                [ [ "read", "Not_watching" ], [ "write", "Not_watching" ] ]
              ],
              [ "watching_has_changed", "false" ],
              [ "num_active_syscalls", "0" ],
              [ "close_finished", "Empty" ]
            ]

          ],
          [
            "monitor",
            [
              [
                [ "name", [ "id", "110" ] ],
                [ "here", [] ],
                [ "id", "110" ],
                [ "has_seen_error", "false" ],
                [ "is_detached", "false" ]
              ],
              [
                [ "name", "" ],
                [ "here", [ "src/lib/mina_lib/mina_lib.ml:1288:35" ] ],
                [ "id", "95" ],
                [ "has_seen_error", "false" ],
                [ "is_detached", "true" ]
              ]
            ]

          ],
          [
            "inner_monitor",
            [
              [
                [ "name", [ "id", "111" ] ],
                [ "here", [] ],
                [ "id", "111" ],
                [ "has_seen_error", "true" ],
                [ "is_detached", "true" ]
              ],
              [
                [ "name", "" ],
                [ "here", [ "src/lib/mina_lib/mina_lib.ml:1288:35" ] ],
                [ "id", "95" ],
                [ "has_seen_error", "false" ],
                [ "is_detached", "true" ]
              ]
            ]

          ],
          [ "background_writer_state", [ "Stopped_permanently", "Error" ] ],
          [ "background_writer_stopped", [ "Full", [] ] ],
          [ "syscall", "Per_cycle" ],
          [ "bytes_received", "326" ],
          [ "bytes_written", "0" ],
          [ "scheduled_bytes", "0" ],
          [ "scheduled_back", "0" ],
          [ "back", "0" ],
          [ "close_state", "Open" ],
          [ "close_finished", "Empty" ],
          [ "close_started", "Empty" ],
          [ "num_producers_to_flush_at_close", "0" ],
          [ "flush_at_shutdown_elt", [ "<opaque>" ] ],
          [
            "check_buffer_age",
            [
              [
                [ "writer", "<opaque>" ],
                [ "maximum_age", "2m" ],
                [ "bytes_received_at_now_minus_maximum_age", "0" ],
                [ "bytes_received_queue", [] ],
                [ "times_received_queue", [] ],
                [ "bytes_seen", "0" ],
                [ "too_old", "Empty" ],
                [
                  "for_this_time_source",
                  [
                    [ "active_checks", [ "<opaque>", "<opaque>" ] ],
                    [ "closed", "Empty" ]
                  ]
                ]
              ]
            ]

          ],
          [ "consumer_left", [ "Full", [] ] ],
          [ "raise_when_consumer_leaves", "true" ],
          [ "open_flags", [ "Full", [ "Ok", [ "wronly" ] ] ] ],
          [ "line_ending", "Unix" ]

]
      ]
    ],
    [ "Caught by monitor (id 110)" ]
  ],
  "backtrace": [
    "Raised at Base__Result.ok_exn in file \"src/result.ml\", line 201, characters 17-26",
    "Called from Async_kernel__Deferred1.M.map.(fun) in file \"src/deferred1.ml\", line 17, characters 40-45",
    "Called from Async_kernel__Job_queue.run_job in file \"src/job_queue.ml\" (inlined), line 128, characters 2-5",
    "Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 169, characters 6-47"
  ]
}
2022-08-29 16:52:50 UTC [Warn] Shutdown before Coda instance was created, not saving a visualization
  ☠  Mina Daemon crashed.
   The Mina Protocol developers would like to know why!
    Please:
      Open an issue:
        <https://github.com/MinaProtocol/mina/issues/new>
      Briefly describe what you were doing and attach the crash report /root/.mina-config/coda_crash_report_2022-08-29_16-52-50.824501.tar.gz
    
Mina process exited with status code 1

**Comment by shimkiv** [comment]
M1 is using ARM cpu architecture and instruction set, as opposed to `amd64 / x86`. The command flag `--platform linux/amd64` with the Docker command is telling Docker to fake or simulate `amd64` for compatibility. 
The simulation for Linux/amd64 is not efficient enough, but it could be if we built `arm64` containers (likely with `Nix`) and then Docker only has to emulate Linux vs `macOS`.

For now you can build Mina rom sources using [Nix](https://github.com/MinaProtocol/mina/blob/develop/nix/README.md)

Created this one to be implemented alter: https://github.com/MinaProtocol/mina/issues/11745
