### ISSUE TITLE
Wallet with 1 txn doesn't match balance

### ISSUE THREAD

**Issue by pyreton** [MinaProtocol/mina#8974]
This wallet has one txn that should have rxd 1.1 mina, but the balance shows 0.1

I can DM a dev more details if helpful.
<img width="1157" alt="unbalanced" src="https://user-images.githubusercontent.com/27087581/120693254-a25df000-c45d-11eb-9b41-f7bdc2a0a958.png">

**Comment by garethtdavies** [comment]
I answered here https://discord.com/channels/484437221055922177/672481591292985365/850076127753797672 but this is the 1 MINA ledger creation fee. 

Related to #8669

**Comment by pyreton** [comment]
Thanks - I got booted from Discord for an unknown reason so came over here. Will +1 that bug.
