### ISSUE TITLE
Mina Daemon crashed.

### ISSUE THREAD

**Issue by newideas86** [MinaProtocol/mina#8984]
I used following command after this Mina Daemon crashed after reboot 

sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo shutdown -r 0

--------------------------------------

2021-06-04 19:32:06 UTC [Info] Initializing with runtime configuration. Ledger name: "mainnet"
2021-06-04 19:32:06 UTC [Info] Using the compiled constraint constants
2021-06-04 19:32:07 UTC [Info] Found genesis proof file at $path
        path: "/home/coffee/.mina-config/genesis/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-06-04 19:32:07 UTC [Info] Loaded ledger from $ledger_file and genesis proof from $proof_file
        ledger_file: "/home/coffee/.mina-config/genesis/genesis_ledger_accounts_71d4f4a0e8c1f3e78760b989234760584969ea0144ed1a3057234f6f0e73621a.tar.gz"
        proof_file: "/home/coffee/.mina-config/genesis/genesis_proof_ef3659d87a794d5c0159273bc7e596fe7a92b766a0aeb4be3437f582e716697a"
2021-06-04 19:32:07 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: {
  "commit_id": "a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a",
  "sexp": [
    "monitor.ml.Error",
    [ "Yojson.Safe.Util.Type_error(\"Expected int or null, got float\", _)" ],
    [
      "Raised at file \"util.ml\", line 15, characters 20-60",
      "Called from file \"src/app/cli/src/mina.ml\", line 725, characters 10-36",
      "Called from file \"src/app/cli/src/mina.ml\", line 693, characters 33-43",
      "Called from file \"src/list.ml\", line 226, characters 12-15",
      "Called from file \"src/app/cli/src/mina.ml\", line 688, characters 14-315",
      "Called from file \"src/app/cli/src/mina.ml\", line 702, characters 14-56",
      "Called from file \"src/app/cli/src/mina.ml\", line 727, characters 8-148",
      "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file \"util.ml\", line 15, characters 20-60",
    "Called from file \"src/app/cli/src/mina.ml\", line 725, characters 10-36",
    "Called from file \"src/app/cli/src/mina.ml\", line 693, characters 33-43",
    "Called from file \"src/list.ml\", line 226, characters 12-15",
    "Called from file \"src/app/cli/src/mina.ml\", line 688, characters 14-315",
    "Called from file \"src/app/cli/src/mina.ml\", line 702, characters 14-56",
    "Called from file \"src/app/cli/src/mina.ml\", line 727, characters 8-148",
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}
2021-06-04 19:32:07 UTC [Warn] Shutdown before Coda instance was created, not saving a visualization

  ☠  Mina Daemon crashed.
   The Mina Protocol developers would like to know why!

    Please:

**Comment by newideas86** [comment]
[Uploading coda_crash_report_2021-06-04_19-32-07.040100.tar.gz…]()

**Comment by deepthiskumar** [comment]
@newideas86 I'm not able to download the crash log. But from looking at the exception it seems like you passed a float value for snark-worker-fee in the config file while it accepts only int. There is a discrepancy in the format fees are passed in command line vs config file. So if you wanted to specify 0.5 mina then you'd have 500000000 in the config file or if you wanted to specify 1 mina then you'd have 1000000000

**Comment by shimkiv** [comment]
Daemon's CLI doc reference also gives an example with `Int`
```
  [--snark-worker-fee FEE]                             Amount a worker wants to
                                                       get compensated for
                                                       generating a snark proof
                                                       (default: 100000000)
                                                       (alias:
                                                       -snark-worker-fee)
```
I'm going to close the issue since there were no updates on it for a long time already.
