### ISSUE TITLE
Exporting staged ledger times out

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#8988]
From @garethtdavies on Discord:

`With the ledger growing in size, I'm struggling to dump the full ledger as just times out. RPC connection error: ((rpc_error (Connection_closed ("No heartbeats received for 1m."))) Any workarounds for this?`

I (@psteckler) can reproduce this error by exporting the staged ledger from a mainnet seed node.

**Comment by garethtdavies** [comment]
This issue has reappeared for me.

```
mina ledger export staged-ledger > /data/ledger.json
RPC connection error: ((rpc_error (Connection_closed ("No heartbeats received for 1m.")))
 (connection_description <created-directly>) (rpc_tag Get_ledger)
 (rpc_version 0))
```
