### ISSUE TITLE
Mina Daemon crashed.

### ISSUE THREAD

**Issue by Rever1987** [MinaProtocol/mina#8989]
I was trying to connect to peers in the node.

{"OS_type":"Unix","Release":"5.4.0-1043-gcp","Machine":"x86_64","Sys_name":"Linux","Exception":{"commit_id":"a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a","sexp":["monitor.ml.Error",["Unix.Unix_error","No child processes","waitpid","((mode (WNOHANG)) (pid 19684))"],["Raised at file \"src/core_unix.ml\", line 50, characters 4-43","Called from file \"src/core_unix.ml\", line 930, characters 4-246","Called from file \"src/unix_syscalls.ml\", line 596, characters 10-39","Called from file \"src/unix_syscalls.ml\" (inlined), line 602, characters 21-55","Called from file \"src/unix_syscalls.ml\", line 610, characters 33-48","Called from file \"camlinternalLazy.ml\", line 27, characters 17-27","Re-raised at file \"camlinternalLazy.ml\", line 34, characters 4-11","Called from file \"src/process.ml\" (inlined), line 142, characters 13-25","Called from file \"src/process.ml\", line 148, characters 25-31","Called from file \"src/deferred0.ml\", line 56, characters 64-69","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47","Caught by monitor coda"]],"backtrace":["Raised at file \"src/core_unix.ml\", line 50, characters 4-43","Called from file \"src/core_unix.ml\", line 930, characters 4-246","Called from file \"src/unix_syscalls.ml\", line 596, characters 10-39","Called from file \"src/unix_syscalls.ml\" (inlined), line 602, characters 21-55","Called from file \"src/unix_syscalls.ml\", line 610, characters 33-48","Called from file \"camlinternalLazy.ml\", line 27, characters 17-27","Re-raised at file \"camlinternalLazy.ml\", line 34, characters 4-11","Called from file \"src/process.ml\" (inlined), line 142, characters 13-25","Called from file \"src/process.ml\", line 148, characters 25-31","Called from file \"src/deferred0.ml\", line 56, characters 64-69","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47"]},"Command":"Command: (mina daemon --generate-genesis-proof true --peer-list-url\n https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt)","Coda_branch":"master","Coda_commit":"a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a"}

**Comment by shimkiv** [comment]
Closing this issue because of being inactive for long time.
Please feel free to open another ticket should you experience any further issues.
