### ISSUE TITLE
Saved staking ledgers disagree on hash

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#8990]
There are two staking epoch ledgers for epoch 5 here:

  https://console.cloud.google.com/storage/browser/mina-staking-ledgers;tab=objects?forceOnBucketsSortingFiltering=false&authuser=1&project=o1labs-192920&prefix=&forceOnObjectsSortingFiltering=false

These two ledgers disagree on hash, so at least one of them is wrong.

**Comment by psteckler** [comment]
Looking at the archive db, following pointers from a block in epoch 5, it looks like this is the correct file:

`staking-5-jwJXdYzAikMHnTsw2kYyS1WQxJrGQsy1FKT5c18eHP2wGANafKf-5a8ceffe310ee03243713f74b4bb8545.json`

**Comment by psteckler** [comment]
No, that's not right at all. The correct file is:

```staking-5-jxVF5YbC3B5Rk6ibfsL97WaqojfxrgWtEqMJST9pb4X8s3kRD2T-9b0527b771675d90d73a47bb4dcba9d7.json```

Explanation:

The blocks for epoch 5 are have global slot >= 5 * 7140 = 35700.
In the mainnet archive dumped from `archive-3-postgresql-0`, all such blocks have staking_epoch_data_id = 31832.
At id 31832, the ledger_hash_id is 864.
At id 864, the snarked_ledger_hash value is `jxVF5YbC3B5Rk6ibfsL97WaqojfxrgWtEqMJST9pb4X8s3kRD2T`.

**Comment by psteckler** [comment]
The staking ledger for epoch 5 with the wrong hash has the same hash as the next staking ledger for epoch 5. Could the file have been copied manually to the wrong location?

There is a race condition in the cron script. The ledger is saved to a file, then the filename is determined. If those two actions straddle an epoch boundary, the ledger could have the wrong epoch number in its filename. That would result in the next or staking ledger from the previous epoch being given the epoch number of the current epoch. 

That data race is very unlikely, and it's not what happened here. If it had, we'd expect the wrongly-named file from epoch 5 to have the hash from the epoch 4 staking ledger.

**Comment by psteckler** [comment]
The scarier possibility here is that `ledger export staking-epoch-ledger` returned the next epoch ledger, instead of the staking epoch ledger.

**Comment by psteckler** [comment]
The cron job logs: https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22o1labs-192920%22%0Aresource.labels.location%3D%22us-east1%22%0Aresource.labels.cluster_name%3D%22coda-infra-east%22%0Aresource.labels.namespace_name%3D%22mainnet%22%0Alabels.k8s-pod%2Fjob-name:%22mainnet-dump-staking-ledger-cronjob-%22%20severity%3E%3DDEFAULT%0A%2528NOT%20%22waiting%22%2529;timeRange=2021-05-29T20:01:23.000Z%2F2021-05-31T11:10:23.000Z;summaryFields=:true:32:beginning;cursorTimestamp=2021-05-31T11:08:47.059815165Z?customFacets=&scrollTimestamp=2021-05-31T11:08:47.059815165Z&authuser=1&project=o1labs-192920

That shows the staking and next ledgers were identical, there was not a manual copying of the file.

**Comment by psteckler** [comment]
#9020 adds the daemon logs to the Gcloud in hopes of resolving this issue.

**Comment by aneesharaines** [comment]
Haven't seen this in the most recent epoch.  Going to close and keep an eye on this and reopen if it happens again.
