### ISSUE TITLE
Delegation Scaling: split slot checks off into separate process

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#9002]
It currently takes ~3s to evaluated 1k vrf checks (this scales linearly). This is a problem because each slot check we perform is currently done in a single async cycle, so long slot checks will pause the async scheduler for however long it takes. Since slot checks happen back to back until we find a winning slot, this provides a high likelihood that nodes will desync from the network, and that likelihood increases as more delegations are added.

As an immediate fix for this issue, we should split the slot checks out into their own process so that they do not pause the scheduler as they run. This is preferable over trying to split slot checks up into multiple async cycles since doing that would damage our ability to dedicate enough time to vrf checks each slot. We can implement this approach with rpc_parallel, with a pipe that pushes slot wins back up to the parent process.

UPDATE: We tried a couple of simpler approaches first before re-aligning on the separate process approach. @mrmr1993 and myself met and fleshed out some details for how this would work.

We spawn and maintain a child worker via rpc_parallel for evaluating vrfs. At the beginning of every epoch, we serialize and send the delegatee table and other required information for performing vrf evaluations in the current epoch. The child worker process asynchronously begins evaluating slots for the entire epoch. Once every slot, the daemon process will poll the child worker to ask for updated information regarding the vrf evaluations. The child process will surface where it currently is in checking slots for the current epoch, as well as any new winning slots it has found since the last time the daemon polled it's state.

In this world, the daemon will no longer only look for the next proposal, but will look for all possible proposals in a slot and keep those in a queue inside of the block producer subsystem. We can also easily surface this information via the CLI to give users increased information on block producer state, which is something users have requested in the past.

**Comment by psteckler** [comment]
`Async.In_thread` might work here, or not.
