### ISSUE TITLE
Mitigate Memory Leak in Libp2p Helper

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#9005]
Chainsafe gave some advice for how we can mitigate our libp2p helper memory leak. We should implement their suggestions and measure to see if there is a reduction in memory growth.

I will post the details of the advice Chainsafe gave us in this issue.

**Comment by c29r3** [comment]
I am seeing this issue on my seed node:
process coda-libp2p_helper takes about 10-60 gigabytes of RAM (after a while)
`Daemon_version: minaprotocol/mina-daemon-baked:1.1.7-d5ff5aa-mainnet`
![image](https://user-images.githubusercontent.com/52304443/134178506-e8613a5c-f28e-4946-989b-0d95bb546428.png)
statistics for 7 days
![statistics for 7 days](https://user-images.githubusercontent.com/52304443/134178538-21175e26-4377-4b81-a60a-907ccccfb3a7.png)

**Comment by ilhanu** [comment]
Getting the same on our machine as a seed-node for Staker Space

- Full-load CPU alert
- High Ram alerts
