### ISSUE TITLE
Investigate high sync time under high load

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#9006]

**Comment by aneesharaines** [comment]
Suspect this is due to networking 

- Matthew will send log from failed catchup 
- Can we measure and monitor the initial catchup?
- Can we also use the catch up status logs?

**Comment by pedroapero** [comment]
Synchronization (excluding genesis proof generation) took me about 30 minutes.
I have a 20Mb bandwidth, my last sync took place 6 days ago (not sure it that matters), and I'm using a i7-4702MQ with some NVMe SSD.

**Comment by aneesharaines** [comment]
Adding timing information to catch up.
