### ISSUE TITLE
Implement archive node for local framework

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#9009]

**Comment by robinbb** [comment]
This issue looks stale. Can it, and the associated PR, be revived, or should the work be restarted?

**Comment by robinbb** [comment]
@MartinMinkov Can this issue be taken away from you to be worked on by the Mina Foundation engineering team? @aneesharaines What do you think?

**Comment by kantp** [comment]
I think we can close this ticket. We have something close enough to it with the setup for testing the rosetta API, and the redesign of the archive node will do the rest.
