### ISSUE TITLE
Excessive memory allocation crashes node

### ISSUE THREAD

**Issue by mkoppanen** [MinaProtocol/mina#9012]
Version: docker minaprotocol/mina-daemon-baked:1.1.5-a42bdee

{"timestamp":"2021-06-09 08:35:54.903255Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 201, characters 10-21"},"message":"SNARK work $work_ids received from $address. Starting proof generation","metadata":{"address":"127.0.0.1:8301","pid":389,"process":"Snark Worker","work_ids":[941533748,942929155]}}
2021-06-09 08:36:00 UTC [Info] Received a block from $sender
        sender: {
  "Remote": {
    "host": "144.172.126.135",
    "peer_id": "12D3KooWD1jRXC39ZWnraxF95fv6QqSN5sUvvEhctSiiFfYeLEHu",
    "libp2p_port": 6069
  }
}
2021-06-09 08:36:00 UTC [Error] Duplicate producer and slot: producer = $block_producer, consensus_time = $consensus_time, previous protocol state hash = $hash, current protocol state hash = $current_protocol_state_hash
        block_producer: "B62qkd4tZQGe9mo5tK3wQi5PUoMdtUGtLWps6Se9o1qWdwNwuUtdWdr"
        consensus_time: { "slot_number": "40491", "slots_per_epoch": "7140" }
        hash: "3NK74UBE7S6MYvvj1Bo3P6N4v9EL5CqUBeXKWfuNhAmEFbVzQHPT"
        current_protocol_state_hash: "3NLxUgu45yunHapzGpxCtpJw2tKTDkahLE2BUKza6U4mM2DUT2NB"
2021-06-09 08:36:00 UTC [Error] Validation error: external transition with state hash $state_hash was rejected for reason "invalid time"
        state_hash: "3NLxUgu45yunHapzGpxCtpJw2tKTDkahLE2BUKza6U4mM2DUT2NB"
2021-06-09 08:36:50 UTC [Warn] validation callback timed out before we could respond
2021-06-09 08:36:50 UTC [Error] validation timed out :(
{"timestamp":"2021-06-09 08:37:12.962566Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 134, characters 12-27"},"message":"Base SNARK generated in $time","metadata":{"pid":389,"process":"Snark Worker","time":"38.374s"},"event_id":"885328f9dca84fa1cfb99089080613d6"}
{"timestamp":"2021-06-09 08:37:12.962623Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 134, characters 12-27"},"message":"Base SNARK generated in $time","metadata":{"pid":389,"process":"Snark Worker","time":"39.184s"},"event_id":"885328f9dca84fa1cfb99089080613d6"}
{"timestamp":"2021-06-09 08:37:12.963021Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 217, characters 14-25"},"message":"Submitted completed SNARK work $work_ids to $address","metadata":{"address":"127.0.0.1:8301","pid":389,"process":"Snark Worker","work_ids":[941533748,942929155]}}
{"timestamp":"2021-06-09 08:37:13.148488Z","level":"Debug","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 169, characters 8-20"},"message":"Snark worker working directory $dir","metadata":{"dir":"/root","pid":389,"process":"Snark Worker"}}
{"timestamp":"2021-06-09 08:37:13.148607Z","level":"Debug","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 181, characters 6-18"},"message":"Snark worker using daemon $addr","metadata":{"addr":"127.0.0.1:8301","pid":389,"process":"Snark Worker"}}
{"timestamp":"2021-06-09 08:37:13.695705Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 201, characters 10-21"},"message":"SNARK work $work_ids received from $address. Starting proof generation","metadata":{"address":"127.0.0.1:8301","pid":389,"process":"Snark Worker","work_ids":[579051359,171267017]}}
2021-06-09 08:37:36 UTC [Info] Received a block from $sender
        sender: {
  "Remote": {
    "host": "85.241.36.246",
    "peer_id": "12D3KooWAVGEZGqkbFsjvjSaFPpd24C85DzocfmuPSYuNPQTKBtu",
    "libp2p_port": 8302
  }
}
Attempted to allocate 137367361787 bytesFatal error: out of memory.
Mina process exited with status code 2

**Comment by hsq125** [comment]
Hi,

This was already reported in https://github.com/MinaProtocol/mina/issues/8367

Maybe consider closing this ticket and add you vote over there so the issue take more weight.

Best regards.

**Comment by mkoppanen** [comment]
Closing in favour of #8367
