### ISSUE TITLE
balances dont match

### ISSUE THREAD

**Issue by mahalamobile** [MinaProtocol/mina#9028]
Hi

Please see https://minaexplorer.com/wallet/B62qkmrLj9odLjkpWGw67iypLPqX7yZpXmfitA5T7Fy7BYR5pA8eVyQ
balance is 269.397000000

btw the above is the correct amount

now on my server
mina client get-balance --public-key B62qkmrLj9odLjkpWGw67iypLPqX7yZpXmfitA5T7Fy7BYR5pA8eVyQ
Balance: 175.841 mina

what is going on here please :)
thanks

**Comment by mahalamobile** [comment]
ok so my server said it was synced but after looking seems it got stuck at 30172 block and wasnt updating

i have restarted the node and now in bootstrap mode.
seems it lost all data on restart

will keep posted but not good that node falls over but is reporting is synced

thanks :)

**Comment by garethtdavies** [comment]
This getting stuck is a very common issue and requires monitoring see https://github.com/MinaProtocol/mina/issues/7555. This should be improved in the upcoming release.

**Comment by mahalamobile** [comment]
ok will check it out thanks

will also keep eye for next release ;)

**Comment by shimkiv** [comment]
Hey @mahalamobile, It's been a while since the issue was last time updated. Do you think it is still relevant issue?

**Comment by mahalamobile** [comment]
Nope ;)

**Comment by shimkiv** [comment]
Thank you!
