### ISSUE TITLE
Exported epoch staking ledger has wrong epoch number

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#9033]
The staking epoch ledger here:

https://console.cloud.google.com/storage/browser/_details/mina-staking-ledgers/staking-5-jx7buQVWFLsXTtzRgSxbYcT8EYLS8KCZbLrfDcJxMtyy4thw2Ee-387f7d9318862985a4a115d814029817.json?authuser=1&project=o1labs-192920

has the hash from epoch 6, while the filename suggests it's from epoch 5.

(I exported the epoch 6 staking ledger from a local node, which has the hash indicated here.)

**Comment by deepthiskumar** [comment]
My guess is because we don't wait long enough for the daemon to sync. So the epoch length which is from the client status output doesn't match the epoch ledger (which gets synced at the beginning of  bootstrap after we have a best-tip to bootstrap to)

**Comment by psteckler** [comment]
> My guess is because we don't wait long enough for the daemon to sync.

Waiting for a sync could take a long time.

Instead, we could do the epoch calculation by hand.

**Comment by psteckler** [comment]
Added a wait-for-daemon-sync loop in #9020, tested by running cron job by hand.

The wait loop succeeded after about 10 minutes, the exported ledgers had the correct epoch number, the daemon logs were saved to GCloud.
