### ISSUE TITLE
[Kubernetes] Block producer does not get out of "Bootstrap" status

### ISSUE THREAD

**Issue by peix2** [MinaProtocol/mina#9057]
Deployed docker image onto my k8s cluster with all necessary configuration.
Container starts up, syncs up and keeps height on top but does not get of bootstrap.
I see between 50 and 70 peers connected. 
K8s cluster is behind NAT but port forwarding is statically set and https://www.yougetsignal.com/tools/open-ports/ show it is open. I am also able to telnet from remote, Internet located host to it and get connected to mina. 
I tried option with Metallb as loadbalancer service attached to mina pod as well as NodePort service and no luck.

Grepping for "bootstrap" that's what I see in the log:
`{"timestamp":"2021-06-16 06:15:27.040850Z","level":"Error","source":{"module":"Bootstrap_controller","location":"File \"src/lib/bootstrap_controller/bootstrap_controller.ml\", line 384, characters 8-20"},"message":"Failed to find scan state for the transition with hash $state_hash from the peer or received faulty scan state: $error. Retry bootstrap","metadata":{"error":{"commit_id":"a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a","sexp":[["rpc_error",["Connection_closed",["EOF or connection closed"]]],["connection_description",["Client connected via TCP",["localhost","36539"]]],["rpc_tag","rpc_parallel_plain_1"],["rpc_version","0"]]},"expected_staged_ledger_hash":{"non_snark":{"ledger_hash":"jwcP1xqbHKpAtTG192hwgkNc8d9JhCppBK2fw18rbj8EjogMKm8","aux_hash":"V9StAyLTy4Kx3m4gTkUyAAHgTdxYe59efMArDDUS94fYo3hCXU","pending_coinbase_aux":"Wp17ooTz85MQC7EJYvoAcqJhTn1nLoVh4hr1QBWoLc3MrA5SGP"},"pending_coinbase_hash":"2mzc7E6wna5yJWcmdbwZvsqNsXJZE9vX6hrK4jhEgSSkTWUCfPwL"},"host":"121.74.163.7","peer_id":"12D3KooWDh43P3pmWGZZom1ArPPPeQc4vWeNGUEJqJJeBWCdfENv","pid":1,"port":8302,"state_hash":"3NL1sbBoQadbJ7YppeJF8efxBNvzcWpeMJLcBKg1nSGUNUuKsqzk"}}
{"timestamp":"2021-06-16 06:22:20.475638Z","level":"Error","source":{"module":"Bootstrap_controller","location":"File \"src/lib/bootstrap_controller/bootstrap_controller.ml\", line 384, characters 8-20"},"message":"Failed to find scan state for the transition with hash $state_hash from the peer or received faulty scan state: $error. Retry bootstrap","metadata":{"error":{"commit_id":"a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a","sexp":[["rpc_error",["Connection_closed",["EOF or connection closed"]]],["connection_description",["Client connected via TCP",["localhost","33043"]]],["rpc_tag","rpc_parallel_plain_1"],["rpc_version","0"]]},"expected_staged_ledger_hash":{"non_snark":{"ledger_hash":"jxLxhaXr6qAQ7udWVWRx3K7eZVbzAnooheN2avCmPXe1zG3h7XX","aux_hash":"W2RHFJTNX8h7yLrV6hqxDtxYWfKqFWvedwnuAK453u2faBZL8f","pending_coinbase_aux":"Xf9LyHUGsLq3nu2811v5cFnidd63EnRdKo1dvg59HTct8A2NET"},"pending_coinbase_hash":"2n1u5ysaAY5Vyrx8WQqWfNt8oyKHi7UsMB8oD2uydk8KhwuiqGmg"},"host":"121.74.163.7","peer_id":"12D3KooWDh43P3pmWGZZom1ArPPPeQc4vWeNGUEJqJJeBWCdfENv","pid":1,"port":8302,"state_hash":"3NL7yKb7iZ514vvKsw3iEDfdcfU7WQ85N3NRVZdEVxmNL5S79VEP"}}
`

Status of the node:

```
root@mina-snark-5b7978c4cb-nb8qg:~# mina client status
Using password from environment variable CODA_PRIVKEY_PASS
Mina daemon status
-----------------------------------

Max observed block height:              31181
Max observed unvalidated block height:  31181
Local uptime:                           1h34m35s
Chain id:                               5f704cc0c82e0ed70e873f0893d7e06f148524e3f0bdae2afb02e7819a0c24d1
Git SHA-1:                              a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a
Configuration directory:                /root/.mina-config
Peers:                                  51
User_commands sent:                     0
SNARK worker:                           None
SNARK work fee:                         100000000
Sync status:                            Bootstrap
Block producers running:                1 (B62qkyo6eqy3BahzuN6mar1cKcQcC2GgowSxB9Fr2TmLEeWATUwu4TG)
Consensus time now:                     epoch=6, slot=965
Consensus mechanism:                    proof_of_stake
Consensus configuration:                
	Delta:                     0
	k:                         290
	Slots per epoch:           7140
	Slot duration:             3m
	Epoch duration:            14d21h
	Chain start timestamp:     2021-03-17 00:00:00.000000Z
	Acceptable network delay:  3m

Addresses and ports:                    
	External IP:    121.74.163.7
	Bind IP:        0.0.0.0
	Libp2p PeerID:  12D3KooWDh43P3pmWGZZom1ArPPPeQc4vWeNGUEJqJJeBWCdfENv
	Libp2p port:    8302
	Client port:    8301
```

It is fair to assume to I did something wrong however IMO all mina configuration has been done according to documentation. I might be missing something. Therefore helpful approach will be appreciated.

**Comment by ttalle** [comment]
I had the exact same symptoms using Docker (not Kubernetes). What the issue seemed to be in my case was that during initialization the container crashed/got killed from an OOM intervention. After that it was left in a broken state.

To fix it I had to:
- Purge the complete container and all container data.
- Ensure I had enough memory available (16GB seemed to work).
- Start a new container and let it fully initialize.

After that the node was done with bootstrapping in a few minutes and started syncing. Maybe it helps...

**Comment by peix2** [comment]
It helped!
I was cleaning up db so many times but never actually cleaned up all "mina-config" fully. Seems deleting all from it and letting daemon to re-create it did the trick.
Almost gave up on project seeing no one's interest in helping to solve issue but looks like now I have mina running on Kubernetes.
Thanks!
