### ISSUE TITLE
Whale producers on devnet2 failed to receive part of snark works

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#9080]
During 2021-6-15 to 2021-6-17, we saw several blocks being produced with no coinbases and no transactions. One thing that contribute to this bug is that after restart block producers could take a long time to sync their snark pool with the network.

Jiawei's conjecture is that sometimes the libp2p pipe is throttled during catchup and some of the snark pool diff messages are tugged under the queue.

The following are some details for the investigation.

Here's the time for nodes finished catchup and the time for them to have proofs available during these 3 days:
whale-1,
2021-6-15 21:58 catchup finished, then at 22:00, 220 proofs are ready for purchase;
2021-6-15 23:18 catchup finished, then at 23:42, 52 proofs are ready for purchase; there's a lot of message throttled afterwards;
2021-6-16 18:31 catchup finished, then at 13:36, 10 proofs are ready for purchase;
2021-6-16 21:53 catchup finished, then at 22:06, 6 proofs are ready for purchase;
2021-6-17 13:51 catchup finished, then at 13:54, 6 proofs are ready for purchase;
whale-2,
2021-6-15 18:41 catchup finished, then at 18:42, 10 proofs are ready for purchase;
2021-6-15 19:30 catchup finished, then at 19:33, 4 proofs are ready for purchase;
2021-6-16 03:44 catchup finished, then at 04:18, 2 proofs are ready for purchase; there's a lot of message throttled in between;
2021-6-16 15:24 transition frontier mode started, then I saw 164 proofs are ready for purchase immediately, no catchup is involved;
2021-6-16 17:56 to 19:06, whale-2 restarted multiple times. I skipped those because sometimes catchup seems not even finished;
2021-6-16 22:14 catchup finished, then at 23:09, 4 proofs are ready for purchase, there's a lot of message throttled in between;
2021-6-17 04:08 catchup finished, this catchup takes a long time; then at 04:15, 14 proofs are ready for purchase.

**Comment by mrmr1993** [comment]
Theory:
* the first time the libp2p_helper sees a message, it marks it as seen
* we drop snark work on the OCaml side while we're in catch-up
* every subsequent time we see it (up to 30 mins after the first time, I believe) libp2p_helper won't forward the message to OCaml again

This seems like it could lead to long delays in syncing the snark pool after catchup, at least if throughput is low and a lot of snark work is already ready.

**Comment by mrmr1993** [comment]
Logs are no longer retained, no ability to debug further. Closing.
