### ISSUE TITLE
Metrics: No block height metric for detecting stuck nodes

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#9091]
While the more common stuck pattern is for `Max observed block height` to trail `Max observed unvalidated block height` I have seen many instances where `Block height` alone does not increment while `Max observed block height` and `Max observed unvalidated block height` both keep increasing.

As there is no metric for `Block height` this can't be detected via the metrics and so needs a secondary alerting system for this specific condition.

![image](https://user-images.githubusercontent.com/135382/122791791-6654c880-d26e-11eb-97e2-6e26a23f3123.png)

Creating as a separate issue but also related to https://github.com/MinaProtocol/mina/issues/7822

**Comment by dguess** [comment]
I would like to see this implemented as well. There's currently no simple way of setting up an alerting for the scenario @garethtdavies described above; I'm using a work around with `Coda_Transition_frontier_best_tip_slot_time_sec` for this purpose but it's not ideal.

**Comment by garethtdavies** [comment]
Closing as this was added :)
