### ISSUE TITLE
Snark coordinator stuck at old block height on devnet2 on 6/17

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#9092]
Snark coordinator was stuck at old block height on devnet2. It was doing catchup but stuck at initial validation at the last 2 blocks. There's no obvious reason other than this: "RPC call error for $rpc: get_transition_chain_proof".

**Comment by ghost-not-in-the-shell** [comment]
It happened again on 6/19, catchup finished 9:11 am pdt on snarked coordinator and then the nodes got stuck during catchup for initial validation.https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22o1labs-192920%22%0Aresource.labels.location%3D%22us-east4%22%0Aresource.labels.cluster_name%3D%22coda-infra-east4%22%0Aresource.labels.namespace_name%3D%22devnet2%22%0Aresource.labels.pod_name:%22snark-coordinator%22;timeRange=2021-06-19T16:11:11.813Z%2F2021-06-19T16:11:11.813Z--PT1H;summaryFields=jsonPayload%252Fmetadata%252Fproof_count,jsonPayload%252Fmetadata%252Ftxn_count,jsonPayload%252Fmetadata%252Ferror_extra%252Fexpected_nonce,jsonPayload%252Fmetadata%252Ferror_extra%252Fnonce,jsonPayload%252Fmetadata%252Fcmd%255B1%255D%252Fsigner,jsonPayload%252Fmetadata%252Fcmd%255B1%255D%252Fpayload%252Fcommon%252Fnonce,jsonPayload%252Fmetadata%252Frate_limiter%252Fby_peer_id%255B0%255D%255B0%255D,jsonPayload%252Fmetadata%252Frate_limiter%252Fby_peer_id%255B0%255D%255B1%255D%252Fcapacity_used,jsonPayload%252Fmetadata%252Fwork_ids,jsonPayload%252Fmetadata%252Freorg_best_tip,jsonPayload%252Fmetadata%252Fadded_transitions%255B0%255D%252Fprotocol_state%252Fbody%252Fconsensus_state%252Fcurr_global_slot%252Fslot_number,jsonPayload%252Fmetadata%252Fadded_transitions%255B0%255D%252Fprotocol_state%252Fbody%252Fconsensus_state%252Fblockchain_length:true:32:beginning;cursorTimestamp=2021-06-19T16:11:56.208611232Z?scrollTimestamp=2021-06-16T06:34:26.958027389Z&dateRangeUnbound=both&authuser=1&project=o1labs-192920

**Comment by ghost-not-in-the-shell** [comment]
Also happened on 6/19, catchup finished at 12:54 pm pdt on snark coordinator and then the nodes got stuck during catchup.
https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22o1labs-192920%22%0Aresource.labels.location%3D%22us-east4%22%0Aresource.labels.cluster_name%3D%22coda-infra-east4%22%0Aresource.labels.namespace_name%3D%22devnet2%22%0Aresource.labels.pod_name:%22snark-coordinator%22%0A;timeRange=2021-06-19T19:54:31.813Z%2F2021-06-19T19:54:31.813Z--PT6H;summaryFields=jsonPayload%252Fmetadata%252Fproof_count,jsonPayload%252Fmetadata%252Ftxn_count,jsonPayload%252Fmetadata%252Ferror_extra%252Fexpected_nonce,jsonPayload%252Fmetadata%252Ferror_extra%252Fnonce,jsonPayload%252Fmetadata%252Fcmd%255B1%255D%252Fsigner,jsonPayload%252Fmetadata%252Fcmd%255B1%255D%252Fpayload%252Fcommon%252Fnonce,jsonPayload%252Fmetadata%252Frate_limiter%252Fby_peer_id%255B0%255D%255B0%255D,jsonPayload%252Fmetadata%252Frate_limiter%252Fby_peer_id%255B0%255D%255B1%255D%252Fcapacity_used,jsonPayload%252Fmetadata%252Fwork_ids,jsonPayload%252Fmetadata%252Freorg_best_tip,jsonPayload%252Fmetadata%252Fadded_transitions%255B0%255D%252Fprotocol_state%252Fbody%252Fconsensus_state%252Fcurr_global_slot%252Fslot_number,jsonPayload%252Fmetadata%252Fadded_transitions%255B0%255D%252Fprotocol_state%252Fbody%252Fconsensus_state%252Fblockchain_length:true:32:beginning;cursorTimestamp=2021-06-19T19:57:51.396985207Z?scrollTimestamp=2021-06-16T06:34:26.958027389Z&dateRangeUnbound=both&authuser=1&project=o1labs-192920

**Comment by mrmr1993** [comment]
Logs are no longer available for debugging. Closing.
