### ISSUE TITLE
Use docker images in tests/CI jobs to avoid repeatedly installing the same packages

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#9105]
Specifically, use the archive image for the archive-node related tests, and use the normal daemon image everywhere else. Complex jobs may still need to install packages, but a lot less of them.

**Comment by lk86** [comment]
Requires some dhall glue to read the docker image from the proper job. #9151 has some changes to update job dependencies for this change, but there is more time / repeated work to be saved here. In the process, working towards a dhall refactor to make this "glue" reusable in some other jobs as well.

**Comment by robinbb** [comment]
@lk86 Is this issue now closable?

**Comment by robinbb** [comment]
@kaozenn Can you verify that this is indeed done, and close if so?

**Comment by kaozenn** [comment]
I can confirm that on the _developer_ branch, all the tests/CI jobs uses docker images.
Issue is marked as Done in the United Sprint Board
[PR](https://github.com/MinaProtocol/mina/pull/9151) raised against that issue is also merged.
Closing ticket
