### ISSUE TITLE
Merge the archive node artifact job with the main build-artifact job

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#9106]
All of the binaries required for the archive node package are built as part of build-artifact anyway, this should reduce overall runtime / total cpu cycles

**Comment by lk86** [comment]
Results of this have not yet been fully tested, but the pipeline is all green with an implementation of this strategy in #9151

**Comment by robinbb** [comment]
@lk86 Should this issue be closed, given that it was moved to Done?

**Comment by robinbb** [comment]
@kaozenn Possible for you to confirm that this is indeed done? (And not by bothering @lk86 as I have done, but by checking the code, as I have not done.)
