### ISSUE TITLE
Mina daemon crashes when starting

### ISSUE THREAD

**Issue by jgrciv** [MinaProtocol/mina#9128]
Logfile attached.
[Uploading coda_crash_report_2021-06-23_19-45-10.704172.tar.gz…]()

**Comment by shimkiv** [comment]
Hey @jgrciv, apologies this ticket was not processed in time and no response provided.
I will close this issue hoping that the most recent version of Daemon are more stable for you.
Please feel free to report new issues should you face any.
Thank you.
