### ISSUE TITLE
Dump the archive node db daily

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#9138]
Cron for dumping a snapshot archive node dumps. `archive-dump-<timestamp>.sql`, daily in a public gcloud storage bucket

**Comment by psteckler** [comment]
Here's the command I use to dump the archive db locally:

```
kubectl exec -n mainnet archive-3-postgresql-0 -- pg_dump --no-owner --create postgres://postgres:foobar@localhost:5432/archive > mainnet_archive.sql
```

**Comment by psteckler** [comment]
The latest dump is about 120Mb. If I tar-gzip that, it's about 36Mb. 

I'd recommend doing the compression, to reduce storage requirements.

**Comment by aneesharaines** [comment]
@QuiteStochastic can you add some details?  where is this running?  How often?  And where are the dumps be stored?

**Comment by QuiteStochastic** [comment]
update 2022/11/09, this is now running for berkeley as well as mainnet

https://console.cloud.google.com/storage/browser/mina-archive-dumps
