### ISSUE TITLE
mina-archive:1.2.0beta1-c856692-mainnet - container fails to start with "[dumb-init] run: No such file or directory"

### ISSUE THREAD

**Issue by hsq125** [MinaProtocol/mina#9148]
Hello,

The archive container fails to start, with the following error in the log

`[dumb-init] run: No such file or directory`

Output of `docker ps --no-trunc`

`4254c5.....5   gcr.io/o1labs-192920/mina-archive:1.2.0beta1-c856692-mainnet   "/usr/bin/dumb-init /entrypoint.sh run --postgres-uri postgres://postgres:SOME_RANDOM_PASSWORD_BUT_YOU_CAN_LEAVE_THIS_UNCHANGED@db:5432/mina_archive_mainnet --server-port 3086 --metrics-port 3085 --log-level Info" `

My config

- Docker version 20.10.7, build f0df350
- Linux cs3 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lk86** [comment]
This is due to a small change in the entrypoint script for that container, now you just have to specify the name of the tool before `run`, so `mina-archive run ...`
