### ISSUE TITLE
1.2.0beta1 client frequent restarts

### ISSUE THREAD

**Issue by lampardlamps** [MinaProtocol/mina#9152]
on one of my nodes, the client restarts every a few hours after upgrading from 1.1.5. I've checked the logs and the reason is not very clear to me, so I've exported the logs and uploaded it to onedrive:
https://1drv.ms/u/s!AlOGZ7BQqAI1iKlq3IrcFtFI6jK7yQ?e=6WapwJ
I have another node running 1.2.0beta1, and it used to be restarting a lot, but seems to have stablised after I removed .mina-config and restarted. Did the same for the one mentioned above but did not work.

**Comment by deepthiskumar** [comment]
From the logs the node restarted twice. first time failed with
```"exn":{"commit_id":"c856692fddc525a673ba075f714811b5c50bd3a7","sexp":["monitor.ml.Error",["Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference(\"b4bceb6f-3547-33f8-413a-6e338c7a2478\", \"File \\\"src/lib/mina_lib/mina_lib.ml\\\", line 1228, characters 49-56\")"],["Raised at file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 116, characters 10-57","Called from file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 542, characters 6-26","Called from file \"src/lib/network_pool/snark_pool.ml\", line 265, characters 18-115","Called from file \"src/lib/network_pool/snark_pool.ml\", line 429, characters 10-59","Called from file \"src/lib/network_pool/snark_pool_diff.ml\", line 121, characters 17-65","Called from file \"src/lib/network_pool/network_pool_base.ml\", line 167, characters 27-73","Called from file \"src/pipe.ml\", line 873, characters 10-13","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47","Caught by monitor coda"]],"backtrace":["Raised by primitive operation at file \"src/signal.ml\", line 162, characters 6-61"]}```.
I don't see any exception the second time but saw a lot of gossip messages being rejected just before the crash. Blocks were also being rejected for being too late

**Comment by lampardlamps** [comment]
> From the logs the node restarted twice. first time failed with
> `"exn":{"commit_id":"c856692fddc525a673ba075f714811b5c50bd3a7","sexp":["monitor.ml.Error",["Merkle_mask.Masking_merkle_tree.Make(Inputs).Attached.Dangling_parent_reference(\"b4bceb6f-3547-33f8-413a-6e338c7a2478\", \"File \\\"src/lib/mina_lib/mina_lib.ml\\\", line 1228, characters 49-56\")"],["Raised at file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 116, characters 10-57","Called from file \"src/lib/merkle_mask/masking_merkle_tree.ml\", line 542, characters 6-26","Called from file \"src/lib/network_pool/snark_pool.ml\", line 265, characters 18-115","Called from file \"src/lib/network_pool/snark_pool.ml\", line 429, characters 10-59","Called from file \"src/lib/network_pool/snark_pool_diff.ml\", line 121, characters 17-65","Called from file \"src/lib/network_pool/network_pool_base.ml\", line 167, characters 27-73","Called from file \"src/pipe.ml\", line 873, characters 10-13","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47","Caught by monitor coda"]],"backtrace":["Raised by primitive operation at file \"src/signal.ml\", line 162, characters 6-61"]}`.
> I don't see any exception the second time but saw a lot of gossip messages being rejected just before the crash. Blocks were also being rejected for being too late

Thanks for looking into this. When I export the logs, how far does it go back? I've attached logs from the other node that upgraded from 1.1.5 to 1.2.0beta1, and by exporting the command `journalctl --user-unit mina --since " 2021-06-29 00:00:00" --until "2021-07-02 10:00:00"` I can see 48 instances of the text `Stopped Mina Daemon`. 
https://1drv.ms/u/s!AlOGZ7BQqAI1iKlrN3MKyY0txCPOEA?e=NG2QTH

**Comment by mrmr1993** [comment]
Fixed in #9201. Closing.
