### ISSUE TITLE
Daemon Process 1.2.0beta1 - crashing with the follownig message "killed because out of memory"

### ISSUE THREAD

**Issue by hsq125** [MinaProtocol/mina#9153]
The daemon version `1.2.0beta1` crashed with the follownig message in the log `killed because out of memory`

I already reported about memory issue in the past, but I don't know if it is the same problem (maybe the same problem, with different error management and logging). See https://github.com/MinaProtocol/mina/issues/6965#issuecomment-854651798.

Here is what I found in the log

`2021-07-02 10:28:28 UTC [Error] Possible reason for signal: "Process killed because out of memory"`

Another information - the machine has 16 GB RAM and 16 GB of swap just in case. The swap has never been touched. It means that memory allocation attempt (admitting is related to that) was rejected upfront by the system, not even trying to do it. 

Log export is at 
https://s3.amazonaws.com/mina.crowbar.systems/mainnet/export/2021-07-02_18-46-13.tar.gz

**Log extract**
2021-07-02 10:27:31 UTC [Warn] RPC call error for "get_transition_chain_proof"
2021-07-02 10:27:35 UTC [Error] error sending message on stream 25703: $error
	error: {
  "commit_id": "c856692fddc525a673ba075f714811b5c50bd3a7",
  "string":
    "RPC #46101 failed: \"only wrote 0 out of 9 bytes error: libp2p error error: closed stream\""
}
2021-07-02 10:27:35 UTC [Warn] RPC call error for "get_transition_chain"
2021-07-02 10:27:41 UTC [Warn] initial_validate: disconnected chain
2021-07-02 10:27:51 UTC [Warn] Not rebroadcasting block $state_hash because it was received "1 slots too late"
	state_hash: "3NLex6ZoBK5FxhxRwPwmEBHLVEycVBf2kWULC9gTcDwPq5wskHQz"
2021-07-02 10:27:51 UTC [Info] Saw block with state hash $state_hash
	state_hash: "3NLex6ZoBK5FxhxRwPwmEBHLVEycVBf2kWULC9gTcDwPq5wskHQz"
2021-07-02 10:27:51 UTC [Warn] initial_validate: disconnected chain
2021-07-02 10:27:51 UTC [Warn] initial_validate: disconnected chain

[...] 

2021-07-02 10:27:51 UTC [Warn] initial_validate: disconnected chain
2021-07-02 10:27:54 UTC [Warn] RPC call error for "get_transition_chain_proof"
2021-07-02 10:27:55 UTC [Info] Received a block from $sender
	sender: {
  "Remote": {
    "host": "34.122.226.192",
    "peer_id": "12D3KooWAbpbSc9WbfkrJE8FQNLebzL9A7WGUVaMFaEjexW4MPmU",
    "libp2p_port": 8302
  }
}
2021-07-02 10:28:05 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: {
  "commit_id": "c856692fddc525a673ba075f714811b5c50bd3a7",
  "sexp": [
    "monitor.ml.Error",
    "Cached item has already been finalized",
    [
      "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
      "Called from file \"src/lib/cache_lib/impl.ml\", line 173, characters 30-51",
      "Called from file \"src/lib/cache_lib/impl.ml\", line 199, characters 6-69",
      "Called from file \"src/lib/ledger_catchup/super_catchup.ml\", line 928, characters 25-58",
      "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file \"format.ml\" (inlined), line 242, characters 35-52",
    "Called from file \"format.ml\", line 469, characters 8-33",
    "Called from file \"format.ml\", line 484, characters 6-24"
  ]
}
2021-07-02 10:28:05 UTC [Info] Updating new available work took 21.804094314575195 ms
2021-07-02 10:28:28 UTC [Error] Daemon child process 97 terminated after receiving signal "sigkill"
2021-07-02 10:28:28 UTC [Error] Possible reason for signal: "Process killed because out of memory"
2021-07-02 10:28:28 UTC [Error] Child process of kind "Prover" with pid 97 has unexpectedly terminated
2021-07-02 10:28:28 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: {
  "commit_id": "c856692fddc525a673ba075f714811b5c50bd3a7",
  "sexp": [
    "monitor.ml.Error",
    [ "Failure", "Child process of kind Prover has unexpectedly terminated" ],
    [
      "Raised at file \"stdlib.ml\", line 33, characters 17-33",
      "Called from file \"src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml\", line 579, characters 10-94",
      "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised by primitive operation at file \"src/signal.ml\", line 162, characters 6-61"
  ]
}
2021-07-02 10:28:28 UTC [Error] verifier terminated unexpectedly
2021-07-02 10:28:28 UTC [Info] Starting a new verifier process
2021-07-02 10:28:28 UTC [Info] verifier successfully stopped
2021-07-02 10:28:28 UTC [Info] Rebroadcasting $state_hash
	state_hash: "3NLnPyR37jEecT8RdmJ6m7HKnNxicr8gj1kKA4x5iZC4nueGevJ4"
2021-07-02 10:28:28 UTC [Fatal] libp2p_helper process died unexpectedly: "died after receiving sigkill (signal number 9)"
2021-07-02 10:28:28 UTC [Error] error during validationComplete, ignoring and continuing: $error
	error: {
  "commit_id": "c856692fddc525a673ba075f714811b5c50bd3a7",
  "string":
    "helper process already exited (doing RPC {\"seqno\":25735,\"is_valid\":\"accept\"})"
}

Environnement
- `Docker version 20.10.7, build f0df350`
- `Linux cs3 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Intel Core i5 16GB RAM + 16GB SWAP.

Feel free to ask if you need more info.
O.

**Comment by hsq125** [comment]
By reading the log a second time...  I see that there is also another error logged in FATAL level.

`2021-07-02 10:28:28 UTC [Fatal] libp2p_helper process died unexpectedly: "died after receiving sigkill (signal number 9)"`

**Comment by deepthiskumar** [comment]
The crash is because of `"Cached item has already been finalized"` and not due to memory. The daemon then sends sigkill to all its processes. The out of memory message is hardcoded as a possible cause and is misleading in this case.

**Comment by nholland94** [comment]
Not sure how this is happening, but it might be a good idea to make this condition only log an error rather than crashing https://github.com/MinaProtocol/mina/blob/develop/src/lib/cache_lib/impl.ml#L203. Doesn't fix the bug, but this would mitigate its effect.

**Comment by ghost-not-in-the-shell** [comment]
One thing I noticed in this log is that there're a lot of blocks were detected to be `disconnected` after 7/2 9 AM. This means the node's frontier is rejecting almost every block  from the network. Since it only has the `info` logs, I can not tell why the `consensus.select` failed on those blocks. My guess is that the node somehow got stuck on a old block height and produced a sidechain accidentally and since it is on a side chain, it would reject the blocks on the canonical chain.

**Comment by ghost-not-in-the-shell** [comment]
As to the actual crash, it's not related to my change in super_catchup. A simple change would be as nathan's suggestion. Just ignore those assertion.

**Comment by shimkiv** [comment]
Closing this issue because of being inactive for long time.
Please feel free to open another ticket should you experience any further issues.
