### ISSUE TITLE
1.2beta1 crashes

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#9157]
Please specify your issue and add a link to the exported logs. 
Note: The logs are of fixed size and therefore older logs are overwritten. Please export the logs as soon as you see the issue.

**Comment by icohigh** [comment]
03.07.21 Stacked at block 37227 after around 4 days uptime in Sync status: Offline. 
At that moment, the block height in the network was 37236.

Logs with last 10000 rows:
[1.2.0-stack-logs-tail-10000.zip](https://github.com/MinaProtocol/mina/files/6771946/1.2.0-stack-logs-tail-10000.zip)
