### ISSUE TITLE
1.2.0 beta 1 crash - Too many open files

### ISSUE THREAD

**Issue by jrwashburn** [MinaProtocol/mina#9163]
Node eventually crashes after many errors re: "too many open files". Logs from mainnet:

https://drive.google.com/file/d/1wKvS32XduiyDi5OemzBh0zJLb5zrJU6i/view?usp=sharing

`
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]: 2021-07-05 10:42:29 UTC [Error] Failed to create a new verifier process: $err. Retrying...
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:         err: {
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:   "commit_id": "c856692fddc525a673ba075f714811b5c50bd3a7",
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:   "exn_name": "Async_kernel__Monitor.Error_",
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:   "exn": [
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:     "monitor.ml.Error",
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:     [
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:       "Unix.Unix_error", "Too many open files", "dup",
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:       "((prog /proc/770444/exe) (args (parallel-worker)) (env (Extend ((ASYNC_PARALLEL_IS_CH>
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:     ],
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:     [
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:       "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:       "Called from file \"src/or_error.ml\", line 72, characters 17-32",
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:       "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:       "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:       "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:       "Caught by monitor Verifier RPC worker at file \"src/lib/verifier/prod.ml\", line 307,>
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:     ]
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]:   ]
Jul 05 06:42:29 mina-mainnet-vt-1 mina[770444]: }
`

Will attach logs and lsof snapshots from devnet on next devnet crash.

**Comment by jrwashburn** [comment]
Linking to #9157

**Comment by jrwashburn** [comment]
In devnet, I am running lsof every time the total handles increase by more than 100. Here are 8 full days of the results, and some very simple/quick analysis here showing a count by type of handle each day. As noted above, I will also update when it crashes, but providing this in case helpful now.

The number of named pipes is increasing daily - perhaps leaking?

Simple count of file descriptor types per day:
https://docs.google.com/spreadsheets/d/1YIaM0IhoR1DscPytvmjhn5m6hbvBJpsBrfQqGKeOp0I/edit?usp=sharing

Acutal lsof output for each day:
https://drive.google.com/file/d/1ZoQ9z_4tbVyX3DCNq9BoMUyJdyhW8ROI/view?usp=sharing

**Comment by psteckler** [comment]
Thanks for the lsof data. Investigating ...

**Comment by psteckler** [comment]
While the number of FIFOs is increasing, the Linux limit is 16k, so that doesn't appear to be an issue, within the reported time frame. 

For reference, when I run Zoom, it shows 1500+ FIFOs, twice as many as Mina. The FIFOs don't appear to count as open files for `ulimit` purposes.

The number of open files (REG) did increase at the end, but had decreased earlier. In the latest `lsof` log, there are 255 open files from processes other than Mina, and 117 from Mina. 

Could the fix be just to increase the open files allowed with `ulimit -n`?

**Comment by jrwashburn** [comment]
I think it was premature to send the information since the devnet node has not crashed yet. I'm not a fan of upping the limit because it doesn't seem to be necessary and I would expect it happens due to a leak. I'd rather just wait for the crash and see what we learn. I'm confident it will crash again since it also happened in mainnet. I'm at 9d17h uptime and it lasted just over 10day last time, so hopefully we'll see it soon.

**Comment by jrwashburn** [comment]
I expect the problem is the pipes, and it is hitting the soft limit. From https://man7.org/linux/man-pages/man7/pipe.7.html re:  /proc/sys/fs/pipe-user-pages-soft: "The default value for this file is 16384, which permits creating up to 1024 pipes with the default capacity." Is there a reason the number of pipes open should be ever-increasing at a rate of ~100 per day? Seems like a slow leak?

**Comment by jrwashburn** [comment]
Node did not crash this time, but instead was restarted because it cot "stuck" (validated block height > 5 blocks behind, so my monitor restarted mina.) I think that is happening because the verifiers cannot be started due to out of FD. So perhaps the stuck node issue others reported is also related to this? New logs shared here: https://drive.google.com/file/d/1rYpu2KrKkRzByrE5SChoP6NozSI2zF4s/view?usp=sharing  

and final lsof: 
https://drive.google.com/file/d/1rYpu2KrKkRzByrE5SChoP6NozSI2zF4s/view?usp=sharing

**Comment by jrwashburn** [comment]
1.20 beta 2 - looks good. No growth in FD count for 24 hours - on both devnet and mainnet. I think this can be closed.
