### ISSUE TITLE
QAnet for gossip data collection

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#9166]
1. Create a network of at least 200 nodes.  
- [x] total 192 block producers (96 unique ones, each with 1-3 duplicates)
- [x] 10 snark coordinators with 5 snark workers each
- [x] 2 seed nodes should be fine
- [x] 10 plain ndoes
2. 25k mina accounts.  Stake distribution similar to mainnet
3. Multiple transaction sending cycles

This will go on coda-infra-central1

----------------------------------

Aftercare:

So in the course of creating the gossip_qa testnet, I had to change the following terraform modules:
-   automation/terraform/modules/kubernetes/testnet
- automation/terraform/modules/o1-testnet (happens to use modules/kubernetes/testnet)

This effects other modules and testnets which depend on the above modules.  For example, the integration tests are broken in this branch because integration tests uses o1-testnet as a module.  Everything that depends on the above modules directly or indirectly needs to be fixed

the following modules use the above two modules:
- [x]   automation/terraform/modules/o1-integration (uses o1-testnet)

the following testnets use the above affected modules:

- [x]   devnet2 (uses o1-testnet)
- [x]   whatever testnet is generated from the integration test framework (uses o1-integration)
- [x]   mainnet (uses o1-testnet)
- [x]   ci-net (uses o1-testnet)
- [x]   nightly (uses o1-testnet)
- [x]   test-labels (uses o1-testnet)

Since i'm already messing with all the testnets, i will also coda->mina for all of them

**Comment by QuiteStochastic** [comment]
all the programming work is now merged to compatible, but we haven't run the actual network yet
