### ISSUE TITLE
enable libp2p metrics for gossip data collection

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#9167]
1. Export existing metrics
2. Add any additional metrics
     1. No. of messages dropped from the queue
     2. latency of message received at the OCaml side (to understand how long libp2p takes to process messages)

**Comment by nholland94** [comment]
- IPC latency (at minimum, libp2p_helper -> daemon direction)
- pipe overflows
- validation delays (min, max, avg) per msg type (mempool diffs x2, blocks)
- counts of validation results (ignore, accept, reject) per msg type (mempool diffs x2, blocks)
- validation timeouts
- count of blocks received too late
- RPC counts (in and out; this is implemented in release/1.2.0 already)
- RPC successes/failures rate
