### ISSUE TITLE
Tokens: remaining work

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#9182]
### Remaining bugfixes

Currently we have an implementation of tokens, although currently disabled. A few small but critical issues remain, mostly related to overflows in various endpoints. The things that should be tested and fixed as necessary:
* [x] amounts / fees close to `2^64-1` in the GraphQL APIs
* [x] amounts / fees close to `2^64-1` stored to the archive node db
* [ ] amounts / fees close to `2^64-1` communicated over rosetta
* [X] balance overflows in the transaction logic (less important, since we're replacing transaction logic for snapps)
* [X] balance overflows in the transaction snark (less important, since we're replacing transaction logic for snapps)

### ERC20/ERC777 compliance

In order to be [ERC20-compliant](https://eips.ethereum.org/EIPS/eip-20), we would also need to add
* [ ] support for adding token names
  - proposal: add a global names table that is updated when a new token is created, associating name and symbol <-> token_id, and storing the root hash of this table (encoded as a merkle tree) in the protocol state
  - even where this feature is required by ERC777, we shouldn't require every use of the tokens concept to abide by it, to give users the maximum flexibility
* [ ] add support for looking up the name + symbol in transactions / accounts
* [x] add support for specifying tokens by the 'owning' public key to GraphQL and CLI (GraphQL completed)
* [ ] use the sync ledger protocol to sync this table
* [ ] store the token name and symbol in the archive db

`approve` and `allowance` can both be implemented as simple snapps on the individual accounts, as well as any more sophisticated permissions. Similarly, [ERC777](https://eips.ethereum.org/EIPS/eip-777)'s additional features all lend themselves to implementation 'over the top' with snapps.

#### Interaction with the snapps transaction spec

* `totalSupply` support can be rolled-up into the work on the transaction spec. It seems most straightforward to use the balance field of the token owner to track this. We should stop tracking that the sum of transaction amounts in a token is 0 and instead let the snapp for the token make this and other guarantees; then, we need only provide a library that implements this.
  - we should probably instead do no checks on the total balance of token transactions
  - this also makes the implementation of fees for creating token accounts trivial, since we need only to track the balance for the default MINA token, from which we can charge fees etc as well.
* Token permissions can be implemented by forcing that the first 'party' in the [new transaction model](https://github.com/MinaProtocol/mina/pull/8068) to be the token owner when 'switching' to a different token.

**Comment by A-Manning** [comment]
> add a global names table that is updated when a new token is created, associating name and symbol <-> token_id, and storing the root hash of this table (encoded as a merkle tree) in the protocol state
> add support for looking up the name + symbol in transactions / accounts
>use the sync ledger protocol to sync this table
>store the token name and symbol in the archive db

ERC20 token names and symbols are not necessarily unique. IMO it's best not to include these in the protocol state, or to ever do a lookup of token id using name and symbol as keys. 

It would be best to allow users to set their own aliases to name tokens, and perhaps to provide a default set of aliases for convenience.

**Comment by imeckler** [comment]
We'll have to disable transfer of tokens in non-snapp transactions right @mrmr1993 ?

**Comment by bkase** [comment]
Can you be more specific with how we can get name/symbol if it's not directly on chain? It's very important folks can easily name their tokens and those names/symbols can be acquired easily by others.

**Comment by mrmr1993** [comment]
If we follow the `[[snapp_for_token1_owner; txn1_in_token1; txn2_in_token1]; [snapp_for_token2_owner; txn1_in_token2; txn2_in_token2]]` bundling for tokens, we're effectively enforcing this anyway, right?

**Comment by mrmr1993** [comment]
@bkase if you guys need for it to be on-chain and persisted, we can store that data in accounts, and add reverse lookups for `token_symbol -> account_id` like we have for `token_id` at the moment.

**Comment by bkase** [comment]
> @bkase if you guys need for it to be on-chain and persisted, we can store that data in accounts, and add reverse lookups for `token_symbol -> account_id` like we have for `token_id` at the moment.

it doesn't necessarily need to be on-chain and persisted if there were an alternative way for folks to easily get this information (for example, Jason suggested we could maybe pull it from some part of transactions that is persisted in archive nodes), but then of course we depend on archive nodes. What are the downsides with having them on-chain? Do we need to expand the account record size?

**Comment by mrmr1993** [comment]
It'll probably need to be 'new bytes'. We can reclaim a few booleans, but not enough to encode strings.

**Comment by mrmr1993** [comment]
> What are the downsides with having them on-chain? Do we need to expand the account record size?

Yea, this is the downside.

How about:
* a few bytes (4? 6?) for a 'token symbol'
* a reverse lookup table for `token_symbol -> account_id`
* enough bytes for an ipfs link to the code for the snapp
  - any other data can be returned by snapp functions in this code

**Comment by deepthiskumar** [comment]
@bkase could you help me understand what the flow would be? Like, would a user try to look up a snapp account using a  token name and then use that snapp account in their transaction? Like @A-Manning mentioned, if it is not unique then this is not a good idea. Are there any other use-cases? 
Does it make sense for the snapp's API to provide the account ID given a token name and vice versa? This would be less ambiguous for the user and no ambiguity at the protocol level when applying transactions.

**Comment by bkase** [comment]
There were a few in person conversations today which I'll summarize here:
1. The new universal transaction spec will subsume tokens more or less, so there's not really any extra work that falls out of enabling tokens
2. The suggestion Matthew made above seems reasonable: a few bytes for the token symbol (where few needs to be further defined) that we add to all accounts + enough bytes to support a link to something like ipfs which we need anyway to link to the source code of the snapp -- here we can include the full token name. This indirection can be transparent to the end user and exposed via the CLI tool

Regarding the token symbol -> account-id. I think we can rely on blockexplorers and other tools outside the main client for this, maybe Jason can confirm.

Does this answer your question @deepthiskumar ?

**Comment by deepthiskumar** [comment]
Added `token_symbol` and `zkapp_uri` to accounts (and therefore on-chain state) and token_id -> accounts lookup. We should open a new ticket if we still need token_symbol -> account lookups. Rest everything in this PR is completed.
