### ISSUE TITLE
1.1.5-a42bdee missing from packages.o1test.net

### ISSUE THREAD

**Issue by jadechip** [MinaProtocol/mina#9213]
I am trying to download mina version 1.1.5-a42bdee using one of the official Docker images.
However this fails due to `1.1.5-a42bdee` not being present at https://packages.o1test.net, or am I missing something?
```
RUN echo "Building image with version $deb_version from repo $deb_release $deb_codename for network $network" \
  && echo "deb [trusted=yes] http://packages.o1test.net $deb_codename $deb_release" > /etc/apt/sources.list.d/o1.list \
  && apt-get update \
  && apt-get install -y --allow-downgrades mina-mainnet
```

Please advise.

**Comment by shimkiv** [comment]
Hey @jadechip , apologies this ticket was not processed in time and no response provided.
You mentioned an attempt to download the Docker Image while showing the code snippet of installing the Linux package.
Do you need any further assistance or you made it on your end using the most recent Mina Daemon versions?

**Comment by shimkiv** [comment]
Closing this issue because of being inactive for long time.
Please feel free to open another ticket should you experience any further issues.
