### ISSUE TITLE
    "RPC #3011 failed: \"only wrote 0 out of 15 bytes error: libp2p error error: closed stream\""

### ISSUE THREAD

**Issue by malingzhao** [MinaProtocol/mina#9230]

**Comment by malingzhao** [comment]
RPC call error for "answer_sync_ledger_query"

**Comment by shimkiv** [comment]
Hey @malingzhao, apologies this ticket was not processed in time and no response provided.
It seems like some networking issues took place back then.
I will close this issue hoping that the most recent version of Daemon are more stable for you.
Please feel free to report new issues should you face any.
Thank you.
