### ISSUE TITLE
Head-versioning of serialized data

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#9238]
Each versioned type, when serialized, is prefixed by an integer indicating a version number. For small version numbers, that's a single byte, according to the `Bin_prot` specification.

Currently, each contained type also has its own version number prefix. That means we can serialize any versioned type, and know how to deserialize it. But due to the compile-time enforcement of the versioning system, the version of a containing type statically implies the version of all contained types, so their version bytes are redundant, and could be omitted from serializations. For complex types, the number of version bytes can be significant (Izaak may have numbers on that).

As a reminder, a brief description of how the Mina code uses versioning:

- There are two versioning schemes at play, the versions for types, as implemented by `ppx_version`, and versions for RPC calls, as implemented by the Jane St libraries.

- Upon an RPC connection, the greatest common RPC version between the querying node and responding node is used. A particular RPC version implies type versions for the query and response types. Each node calls  coercion functions to translate the data to and from the query and response types associated with its own greatest RPC version, which may be greater than that used for the call.

- This setup allows soft forks, where the updated code can use a an RPC type with a new version, and still communicate with nodes running old code.

Proposal 1:

We could have a setup which retains the current serializations and, alongside that, allow serializations prefixed by the version number of the containing type, with no other version numbers, which could be used by RPCs.

We can distinguish serializations from these two schemes by prefixing the head-only versioning with MAXINT, followed by the actual version number. The versions-all-the-way-down serializations will still begin with a version number, which is never MAXINT. That way, deserializing the data is deterministic.

Upon reflection, I think this change does require a hard fork. If new code uses this arrangement, old code won't know how to interpret new serializations containing the MAXINT prefix.

Proposal 2:

We could scrap the existing system, and have only head-only serializations, which certainly requires a hard fork. In this case, the MAXINT prefix is not needed.

The `bin_io` functions for a given type would always use the head-versioning setup.

Implementation:

The head-only serialization would use the `bin_io` functions, as they're generated by the `ppx_bin_prot`. In the case of `bin_write_t`, the version number would be prepended, and `bin_read_t` would verify the version number.

**Comment by georgeee** [comment]
A few points from me:

* If we are going to redesign networking communication layer (which seems we are about to), we are to consider using something different from `binprot` (something standardized)
* Versioning can be negotiated at the very beginning of RPC communication by means of a handshake (basically, nodes exchange version maps of all of RPCs).

My question is: why do you call it "head-only". AFAIU there is already a negotiation phase of RPC connection establishment. Why not we just drop all of the version bytes from all of the data?

**Comment by mrmr1993** [comment]
Note that we also use this format for persisted data. This scheme was supposed to let us modify any of our serialised types, as long as we provide a new version and a conversion to the latest version, and enforce that they can't change otherwise so we don't break upgradability.

The leading version byte identifies which version we're currently on; this issue is for removing the version bytes for the types nested within the main type, since they're not of any further use. As you mentioned, for RPCs the version is negotiated directly, so we can elide that byte altogether.

**Comment by psteckler** [comment]
Assuming a hard fork and that we don't have to read any existing persisted data, we could do the following:

- use the `ppx_bin_prot`-generated functions, as is
- for each `Stable.Vn` module, add a contained module `With_version` where the `bin_io` functions write/read a prepended version number; the contained data won't have any version numbers
- the `bin_read_to_latest_opt` function is in the `With_version` module

Then the RPC functions use the ordinary `bin_io` functions. When writing/reading persisted data, we use the `With_version` functions.

**Comment by mrmr1993** [comment]
Can we switch them around, so that we have a `No_version` (and under-the-hood use that with bin_prot via ppx_version)?

I think we'll want to be able to read old data to be able to upgrade the ledger for the hard fork; is there some hack we could do (e.g. an annotation, like `[@@@always version]`) to keep the old behaviour for the existing versions?

**Comment by psteckler** [comment]
What persisted versioned-serialized data do we need to think about for compatibility, if we make this change?

A node can still bootstrap if the persisted frontier can't be read, for example.

**Comment by psteckler** [comment]
Whatever changes happen with the serialization, we need to keep the format of keys, etc. unchanged. Some Base58 representations depend on serializations.

**Comment by psteckler** [comment]
Changes described in RFC 0047 cover this, and have been implemented.
