### ISSUE TITLE
1.2.0beta2 crash report

### ISSUE THREAD

**Issue by EmreNOP** [MinaProtocol/mina#9243]
exn: {
  "commit_id": "23842acf84226b55b654f00bdca8b23da1432916",
  "sexp": [
    "monitor.ml.Error",
    [
      "Hashtbl.add_exn got key already present",
      "11338597825129596045024975545776382011383231391041456291243598083941269614751"
    ],
    [
      "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
      "Called from file \"src/hashtbl.ml\", line 140, characters 4-21",
      "Called from file \"src/lib/transition_frontier/full_frontier/full_frontier.ml\", line 520, characters 6-131",
      "Called from file \"src/lib/transition_frontier/full_frontier/full_frontier.ml\", line 729, characters 31-74",
      "Called from file \"list.ml\", line 117, characters 24-34",
      "Called from file \"src/list0.ml\" (inlined), line 22, characters 40-81",
      "Called from file \"src/lib/transition_frontier/full_frontier/full_frontier.ml\", line 727, characters 4-484",
      "Called from file \"src/lib/transition_frontier/transition_frontier.ml\", line 333, characters 4-214",
      "Called from file \"src/lib/transition_handler/processor.ml\", line 63, characters 9-67",
      "Called from file \"src/lib/transition_handler/processor.ml\", line 326, characters 21-120",
      "Called from file \"src/result.ml\", line 151, characters 9-15",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file \"format.ml\" (inlined), line 242, characters 35-52",
    "Called from file \"format.ml\", line 469, characters 8-33",
    "Called from file \"format.ml\", line 484, characters 6-24"
  ]
}
2021-07-21 17:31:31 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: {
  "commit_id": "23842acf84226b55b654f00bdca8b23da1432916",
  "sexp": [
    "monitor.ml.Error",
    [
      "Failure",
      "traced task `R&transition_handler_processor` failed, exception reported to parent monitor"
    ],
    [
      "Raised at file \"stdlib.ml\", line 33, characters 17-33",
      "Called from file \"src/lib/pipe_lib/strict_pipe.ml\", line 159, characters 28-37",
      "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file \"format.ml\" (inlined), line 242, characters 35-52",
    "Called from file \"format.ml\", line 469, characters 8-33",
    "Called from file \"format.ml\", line 484, characters 6-24"
  ]
}
[coda_crash_report_2021-07-21_17-39-49.193892.tar.bz2.zip](https://github.com/MinaProtocol/mina/files/6857967/coda_crash_report_2021-07-21_17-39-49.193892.tar.bz2.zip)

**Comment by shimkiv** [comment]
Hey @EmreNOP, apologies this ticket was not processed in time and no response provided.
I will close this issue hoping that the most recent version of Daemon are more stable for you.
Please feel free to report new issues should you face any.
Thank you.
