### ISSUE TITLE
Group libraries, apps by .opam files

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#9277]
All the `.opam` files are in `src/` now. That means each file is separated from the library source that it applies to, which is confusing, and leads to clutter and the presence of orphaned files.

I've found that moving the file to the library directory allows compilation, if there is also a `dune-project` file in the same directory. Those files could be symlinks to a master `dune-project`.

**Comment by A-Manning** [comment]
For this kind of project layout, it is advisable to make use of a `dune-workspace` file at the root.

**Comment by psteckler** [comment]
Better: create a few .opam files, group the libraries by the categories named in those files.

Possible categories:
- crypto
- ledger
- networking

There cannot be cyclic dependencies among these .opam files, so this idea may be a non-starter.

**Comment by psteckler** [comment]
Abandoning, for now.
