### ISSUE TITLE
Rosetta: Package latest docker container to-spec

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#9292]

**Comment by robinbb** [comment]
@lk86 Okay to take this from you and assign to the Mina Foundation engineering team?

**Comment by lk86** [comment]
Mainly just don't change the basic usage or build process of the rosetta container, and then it should remain to-spec. See here for the specification itself: https://www.rosetta-api.org/docs/node_deployment.html

**Comment by robinbb** [comment]
@lk86 Okay, I think that you are confirming that it's okay to take this from you and assign to the Mina Foundation engineering team. I'll assign to @kaozenn for now, and @kantp can re-assign as appropriate.

**Comment by kaozenn** [comment]
I think this work is already covered in this PR:
https://github.com/MinaProtocol/mina/pull/12341/files#diff-7fbbf33479e8cc2cce4c0e1bed57ecc2b9947ffa7be392820572e0131a98aefaR59

The main change from https://www.rosetta-api.org/docs/node_deployment.html is to support 2 instances (online and offline) of the Rosetta API.

@lk86 , can you please confirm and Close the ticket as needed.

Thank you

**Comment by lk86** [comment]
Correct I think this is already good to go and all of the recent changes are still to-spec, lgtm
