### ISSUE TITLE
Rosetta: Update to the current spec -- make sure whatever changes we've made on the protocol haven't broken anything. Verify with our tests and the official test suite

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#9294]

**Comment by psteckler** [comment]
How do we run tests against the current spec? / @bkase

**Comment by psteckler** [comment]
Which tests are to be run?

Is the latest `mina-rosetta` a suitable container?

**Comment by psteckler** [comment]
Is the Rosetta spec tagged with `v1.4.9`? Or do we want `master`?

**Comment by psteckler** [comment]
Assuming the spec is `v1.4.9`, after generating new .ml files, nothing is generated for the existing files:
```
construction_hash_response.ml
construction_submit_response.ml
```

**Comment by psteckler** [comment]
Branch `rosetta-new-model-testing` contains changes with the models updated to `v1.4.9`.

Issues:
- in the Rosetta docker, the `docker-start.sh` script has the Postgresql version hard-coded to 11. Substituting 9.6 allows Postgresql to start
- the runtime ledger used by the Docker container is taken from `src/app/rosetta/config.json`, which contains keys in a format that's no longer used
