### ISSUE TITLE
allow configuring march flag in build system

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#930]
Right now `-march=westmere` is [hardcoded](https://github.com/CodaProtocol/coda/pull/929) into the build system. Ideally this should be a cmake tweakable. It should default to not passing anything (same as `-march=generic`) probably. We should document somewhere that the default build configuration doesn't generate the fastest possible binaries.

**Comment by shimkiv** [comment]
Hey @nholland94 can you please take a look.
