### ISSUE TITLE
mini RFC: Spec for HTTPSnapps server API and JS Client lib

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#9306]
## Background

Many Snapps will run in the browser thanks to the the WASM in-browser snark support.

Before we have snapp transactions connected to a network, we can still prototype the ux and tooling for the snark circuit side using a browser verifier running the verification logic too.

Snapps will typically need to reach out to some HTTPS-secured data source to pull information to include in a snark. While we wait for this infrastructure to be fully built-out, we can stub this with an oracle that signs responses to API requests.

Developers of Snapps will typically write some code out-of-the-snark that pulls this HTTPS-secured data, and, for now, this amounts to asking the HTTPSnapps oracle server to make a request and sign the response. This, to me, motivates the creation of some little JS micro-library to help do this work since it will be done in so many applications.

This issue aims to spec out what that library might look like and how it would interact with this temporary oracle, later we can swap out the oracle request for actually performing the httpsnapps verification properly.

## HTTPSnapps Oracle API

Let's keep things simple for now, no auth/api tokens.

```
// Get raw data from some API using GET or POST (forward along whatever is sent)

{GET,POST} /verify?url=<url-encoded url>&params=<url-encoded comma separated q=v query params>

Headers: (TODO come up with some way to forward headers, we can get away with leaving this stubbed until we need it)

POST Data: <arbitrary>       // Forward the POST data as is

Response:
200 -> returns a signable(string)
	{
        "publicKey": "B64q...",
		"signature": {
		      "field": string,
		      "scalar": string,
		    },
		"payload": string // stringified response from the API
    }
   such that this verifies with `verifyMessage` from the client-sdk and the public key is the official HTTPSnapps oracle's published key
   
4xx -> bad encoding of query
   { payload: string // error message }
   
502 -> some error on the upstream server
   { error: number, payload: string // stringified response from the upstream server } 

5xx -> error on this server
   { payload: string // error message }
```

## Microlibrary: httpsnapper

This microlibrary doesn't depend on the client-sdk directly so we don't accidentally vendor two different versions of it and increase the bundle size too much. (reviewers, tell me if this is not something to care about)

Exports a single function:

`async verify(method: 'GET'|'POST', url: string, params: QueryParams, postData: string?) -> { ok: signable(string)?, error: Error? }`

Usage by a developer:

```js
const httpsnapps = require('@o1labs/httpsnapper')
const MinaSDK = require('@o1labs/client-sdk')

const res = await httpsnapps.verify('GET', 'https://example.com', { key: "value" }, null)
if (!res.ok) {
  // show failure in the UI
  return
} else {
  // show request finished in the UI, verifying...
  if (MinaSDK.verifyMessage(res.ok)) {
  	// show request verified successfully
  	// use the signature and payload for subsequent snapp purposes here
  } else {
    // show that signature verification failed
  }
}
```

**Comment by jasongitmail** [comment]
- Would suggest ES6 style imports & PascalCase, for var names of classes or objects containing other methods.

```js
import HttpSnapps from '@o1labs/httpsnapp';
import Mina from '@o1labs/mina-sdk'; 
```

- For the lib name, what do you think about?:
```
@o1labs/httpsnapp (client)
@o1labs/httpsnapp-server (server) (if this will be on NPM)
```
More intuitive?

**Comment by dillongrove** [comment]
Might make sense to expose a function per method, e.g. `httpsnapp.get(...)`, `httpsnapp.post(...)`. This is what I've seen most popular promise-based request libraries do (e.g. [superagent](https://github.com/visionmedia/superagent), [axios](https://github.com/axios/axios)).

Or if we want to make extra clear that it's verified, something like `httpsnapp.verifiedGet(...)`, etc

**Comment by mrmr1993** [comment]
No longer relevant. Closing.
