### ISSUE TITLE
1.2.0 beta 2 crash - Too many open files

### ISSUE THREAD

**Issue by jrwashburn** [MinaProtocol/mina#9313]
I think I closed #9163 prematurely - Issue occured again in devnet on beta2 eventually. I am opening a new issue instead of reopening since this is on 1.2.0beta2 and some changes were merged for 9163 already. Daemon crashes due to Too many open files, and it still looks like a pipe leak - FIFO handles just keep growing.

Simple summary of type of file descriptor growth here (see lower section with Beta 2 handles)
https://docs.google.com/spreadsheets/d/1YIaM0IhoR1DscPytvmjhn5m6hbvBJpsBrfQqGKeOp0I/edit?usp=sharing

Output from the last lsof I captured before the crash is here: https://drive.google.com/file/d/1oGchdcPHxfDwE-x-IbUQLASWoqA5AIKP/view?usp=sharing

Crash files are not present. Not attaching logs as I think this says it all -- if desired, I have them preserved.

Initially reports several Warn messages re: gsutil upload (using GCS for block backups)
`
2021-07-26 19:55:25 UTC [Warn] Uploading block to gcloud with command $command failed: $error
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]:         command: "gsutil cp -n /tmp/upload_block_file.tmp.55c351 gs://mina-devnet-blocks/devne
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]:         error: {
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]:   "commit_id": "c856692fddc525a673ba075f714811b5c50bd3a7",
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]:   "exn_name": "Unix.Unix_error",
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]:   "exn": [
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]:     "Unix.Unix_error", "Too many open files", "safe_pipe",
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]:     "((prog bash) (args (-c \"gsutil cp -n /tmp/upload_block_file.tmp.55c351 gs://mina-devnet-
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]:   ],
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]:   "tags": [
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]:     {
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]:       "tag":
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]:         "File \"src/lib/mina_lib/coda_subscriptions.ml\", line 196, characters 55-62"
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]:     }
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]:   ]
Jul 26 19:55:25 mina-devnet-do-1 mina[10217]: }
`
Then trips on to Error when it cannot create verifiers:
`
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]: 2021-07-26 20:02:54 UTC [Error] Failed to create a new verifier process: $err. Retrying...
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:         err: {
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:   "commit_id": "c856692fddc525a673ba075f714811b5c50bd3a7",
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:   "exn_name": "Async_kernel__Monitor.Error_",
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:   "exn": [
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:     "monitor.ml.Error",
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:     [
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:       "Unix.Unix_error", "Too many open files", "safe_pipe",
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:       "((prog /proc/10217/exe) (args (parallel-worker)) (env (Extend ((ASYNC_PARALLEL_IS_CHILD
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:     ],
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:     [
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:       "Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30",
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:       "Called from file \"src/or_error.ml\", line 72, characters 17-32",
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:       "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:       "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:       "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:       "Caught by monitor Verifier RPC worker at file \"src/lib/verifier/prod.ml\", line 307, c
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:     ]
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]:   ]
Jul 26 20:02:54 mina-devnet-do-1 mina[10217]: }
`
And then goes Fatal:
`
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]: 2021-07-26 20:04:01 UTC [Fatal] Unhandled top-level exception: $exn
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]: Generating crash report
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:         exn: {
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:   "commit_id": "c856692fddc525a673ba075f714811b5c50bd3a7",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:   "sexp": [
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     "monitor.ml.Error",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     [ "Unix.Unix_error", "Too many open files", "accept", "((fd 56))" ],
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     [
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "Raised at file \"src/core_unix.ml\", line 50, characters 4-43",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "Called from file \"src/core_unix.ml\", line 2419, characters 17-40",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "Called from file \"src/raw_fd.ml\", line 282, characters 10-26",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "Re-raised at file \"src/unix_syscalls.ml\", line 956, characters 20-29",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "Called from file \"src/unix_syscalls.ml\", line 961, characters 12-32",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "Called from file \"src/deferred1.ml\", line 174, characters 6-13",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "Caught by monitor coda"
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     ]
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:   ],
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:   "backtrace": [
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     "Raised at file \"src/result.ml\", line 158, characters 17-26",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:   ]
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]: }
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]: 2021-07-26 20:04:01 UTC [Fatal] Unhandled top-level exception: $exn
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]: Generating crash report
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:         exn: {
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:   "commit_id": "c856692fddc525a673ba075f714811b5c50bd3a7",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:   "sexp": [
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     "monitor.ml.Error",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     [
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "Unix.Unix_error", "Too many open files", "mkstemp",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "/home/minar/.mina-config/snark_pool"
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     ],
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     [
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "Raised at file \"src/result.ml\", line 158, characters 17-26",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:       "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     ]
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:   ],
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:   "backtrace": [
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     "Raised at file \"format.ml\" (inlined), line 242, characters 35-52",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     "Called from file \"format.ml\", line 469, characters 8-33",
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:     "Called from file \"format.ml\", line 484, characters 6-24"
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]:   ]
Jul 26 20:04:01 mina-devnet-do-1 mina[10217]: }

Jul 26 20:05:04 mina-devnet-do-1 mina[10217]: 2021-07-26 20:05:04 UTC [Fatal] Unhandled top-level exception: $exn
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]: Generating crash report
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:         exn: {
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:   "commit_id": "c856692fddc525a673ba075f714811b5c50bd3a7",
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:   "sexp": [
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:     "monitor.ml.Error",
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:     [ "Failure", "Child process of kind Prover has unexpectedly terminated" ],
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:     [
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:       "Raised at file \"stdlib.ml\", line 33, characters 17-33",
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:       "Called from file \"src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml\", line 579, c
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:       "Called from file \"src/deferred0.ml\", line 56, characters 64-69",
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:       "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:       "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:       "Caught by monitor coda"
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:     ]
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:   ],
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:   "backtrace": [
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:     "Raised by primitive operation at file \"src/signal.ml\", line 162, characters 6-61"
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]:   ]
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]: }
Jul 26 20:05:04 mina-devnet-do-1 mina[10217]: 2021-07-26 20:05:04 UTC [Fatal] Timed out while generated crash report
Jul 26 20:05:05 mina-devnet-do-1 systemd[30507]: mina.service: Main process exited, code=exited, status=1/FAILURE
`

**Comment by c29r3** [comment]
Show output:  
`ulimit -n`
and 
`docker exec mina /bin/bash -c 'ulimit -a'`

**Comment by psteckler** [comment]
@jrwashburn Have you observed this with later betas?

Is it possible to log the file opens, with something like 
```
strace -f -e openat,pipe,pipe2 mina daemon ... >& trace.log
```

**Comment by c29r3** [comment]
I don't see any problem here
This is statistics from my seed node (15 days)
![image](https://user-images.githubusercontent.com/52304443/134795184-f34f5123-3154-476b-842d-9938eedd5136.png)
```bash
ulimit -n
1000000
```

Block producer (15 days)
![image](https://user-images.githubusercontent.com/52304443/134795175-24dcfcdb-6869-4ce8-b8e5-3753e2978c5f.png)
```bash
ulimit -n
65535
```

**Comment by shimkiv** [comment]
Hey @jrwashburn, @c29r3,
Do you still experience the same/similar issues using the most recent Mina Daemon versions?

**Comment by jrwashburn** [comment]
> Too many open files

No, I do not see this error any longer.
