### ISSUE TITLE
README.md contain broken links

### ISSUE THREAD

**Issue by danielorihuela** [MinaProtocol/mina#9316]
README.md contain a couple of broken links:

- Become a Node Operator -> https://docs.minaprotocol.com/en/node-operator/
- Directory structure -> https://github.com/MinaProtocol/mina/blob/develop/frontend/website-redesign/docs/developers/directory-structure.mdx
- Lifecycle of a payment -> https://github.com/MinaProtocol/mina/blob/develop/frontend/website-redesign/docs/architecture/lifecycle-payment.mdx

**Comment by amc-ie** [comment]
The links in the readme.md now resolve to the correct content so I am closing this defect. Please reopen if you disagree or spot anything else adding any relevant information. Thanks!
