### ISSUE TITLE
[HARD FORK] Persist and reuse libp2p keypair

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#9320]
We should be doing this anyway, but this is required for the upcoming Bitswap work. If a node goes offline, we want the libp2p keypair to be the same when it comes back online so that the DHT entries that point to a node as being able to serve Bitswap blocks will still be valid. Otherwise, we would need to create a mechanism that re-advertises all of a node's Bitswap blocks on bootup, which is not ideal and wouldn't fit into the DHT's cache timeout logic we wish to utilize. As part of this, we also need to provide more messaging urging our node operators to persist their config directories, and we will need to implement volume persistence on our seed nodes in mainnet.

**Comment by georgeee** [comment]
It's an OCaml-side feature

**Comment by georgeee** [comment]
We already have logic to specify the libp2p keypair. Do you suggest removing the option to generate random key if the keypair is not provided. I.e. exit instead of random generation of a keypair?

**Comment by p-shahi** [comment]
> Instead we give an error to the user when no key is present. 

I like this approach, it makes our intended behavior and usage of the keypair explicit. 

> We can provide a simple CLI to generate a keypair for you and stick it into the right place on-disk.

I see that we reference `mina advanced generate-libp2p-keypair` in our [documentation for seed peers](https://docs.minaprotocol.com/en/advanced/seed-peers), I think we should use that same CLI to generate the kp. Is its default behavior to generate the kp in the `pwd` or in the config directory?

**Comment by bkase** [comment]
Sounds good but let’s be really careful to have clear error messages an. I think this should have a PRD outlining what the CLI flow should look like from a user’s perspective and then the implementation can be checked against the PRD in code review.

> I see that we reference mina advanced generate-libp2p-keypair in our [documentation for seed peers](https://docs.minaprotocol.com/en/advanced/seed-peers), I think we should use that same CLI to generate the kp. Is its default behavior to generate the kp in the pwd or in the config directory?

I think we should move it out of advanced if it’s something everyone is expected to execute and maybe make the name of the command simpler. I don’t remember what the behavior currently is, but I think we should just think about it from first principles anyway, ignoring the current status. It should be super easy to change this to whatever we need it to be.
