### ISSUE TITLE
Patch the holes in the archive data on devnet

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#9330]
We must have a full archive node on an active devnet or else developers won't really be able to use it properly.

**Comment by psteckler** [comment]
On node archive-1-postgresql-0, there is just one missing block:
```
{"timestamp":"2021-08-03 19:16:04.505922Z","level":"Info","source":{"module":"Dune__exe__Missing_blocks_auditor","location":"File \"src/app/missing_blocks_auditor/missing_blocks_auditor.ml\", line 30, characters 10-21"},"message":"Block has no parent in archive db","metadata":{"block_id":14157,"parent_hash":"3NLm9huRf6dSria3Ttdin7abGyBP5CVnJ8wHkAUggihNqp9j41Kb","pid":25455,"state_hash":"3NKfoep1VWnZXYEW2YBRmjH56F2VHBRyZBJB2UcQBbHbFWSg3jdv"}}
```
From the other archive db on pod archive-3-postgresql-0, here is that missing block:
```
{
  "state_hash": "3NLm9huRf6dSria3Ttdin7abGyBP5CVnJ8wHkAUggihNqp9j41Kb",
  "parent_hash": "3NLNQi3gwjWWYszpRn6X8aXEZb2yKSVdtttSt7RpBLevynbxUSrN",
  "creator": "B62qoQVHjnNMcBR1viXabDYH7voTTXpQYCL2XWkCGqLGaocuPgxaNZu",
  "block_winner": "B62qjgzBa5Z8MSe9CdWMtyZ7Gawndurpp4CUqSDx48pxrxzjQ3rT8QV",
  "snarked_ledger_hash":
    "jwSaqNRHNCoEWNHKyBjHfLoMHw5Ltpg53GumgjniRcUt51t9EFV",
  "staking_epoch_seed":
    "2vbMcprkuoxyvPdLN7z4XcSND47TDLkSqwnRv24aLCdZN6VPZB7k",
  "staking_epoch_ledger_hash":
    "jxkx5tG7if37WCYybvfP1aP27Ai9MDz6LLMjwnzFEbZPTLiECH5",
  "next_epoch_seed": "2vbG9PshMAcRmGK8Y9NuVPh2FG7hU1H885hP1Uz5DSvbS1zTnFi3",
  "next_epoch_ledger_hash":
    "jwE4VGvQK2gR5X36yazDnkYP1RTUSBJj5W1kH9E5uNFpK4u9B1Y",
  "ledger_hash": "jwVfpw65CbMpba6tPJ7ykv8XHKa2D88RTpYRwxd8Z5WT22bgzrJ",
  "height": "10016",
  "global_slot": "16117",
  "global_slot_since_genesis": "16117",
  "timestamp": "1618167655903",
  "user_cmds": [],
  "internal_cmds": [
    {
      "sequence_no": 0,
      "secondary_sequence_no": 0,
      "typ": "coinbase",
      "receiver": "B62qoQVHjnNMcBR1viXabDYH7voTTXpQYCL2XWkCGqLGaocuPgxaNZu",
      "receiver_balance": "5603586969171873",
      "fee": "1440",
      "token": "1",
      "hash": "CkpZdkkeaMe4R4YD9Zt7d9F2dmNAb5cQgFKnNigVospDVrphabLnY"
    }
  ]
}
```
We should:
-- add this block to this archive db
-- extract the missing blocks from this archive db, and add them to the other archive db

@bkase

**Comment by psteckler** [comment]
`archive-1-postgresql-0` is patched, no holes there.

**Comment by psteckler** [comment]
archive-3-postgresql-0 was missing many more blocks than `missing_blocks_auditor` reported. Patching just those blocks revealed they also had missing parents. In fact, there was a chain of over 200 missing blocks.

To patch those:
- determine which global slots are missing, look for a gap in the blocks table
- extract all blocks from a block with a given state hash back to genesis
- grep for the missing global slots in the extracted block files, sort by global slot
- archive the missing blocks

**Comment by psteckler** [comment]
archive-3-postgresql-0 is also patched.

Of course, new holes may appear. We were lucky in this instance that the two databases had all the blocks, but that may not always be true.
