### ISSUE TITLE
Resolve bitrot issues with Rosetta since early this year

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#9334]
Current state:
* Regenerated models for latest spec; they need to be massaged after auto-generated
* No issue with setStaking -- you need to unlock an account before you can setStaking ; logs are clearer now
* Some of the tests involve token transactions but those are disabled so we need to rip out those tests
* Roadblock involving historical balances ; #9271 something with runtime constants -- now we can lookup compiled-constants (maybe)
* rosetta check:data tool checking what issues are there

**Comment by psteckler** [comment]
#9339 gets the test-agent to run in `compatible`.

The branch used for #9310 contains the same changes to get the test-agent to run with the new models.
