### ISSUE TITLE
/construction/parse shouldn't depend on a GraphQL request to the daemon. We can validate everything in the Rosetta process

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#9350]
Currently, this endpoint depends on the `validatePayment` graphql endpoint which checks the signature properly (devnet / mainnet). Can we do this in the executable easily if we don't have a separate binary for devnet/mainnet?

@A-Manning does the new crypto logic for devnet/mainnet signing fix this? Is this fix on compatible? We can chat

---

For now -- we can decouple the testnet / mainnet signature conditional logic with the functions (ie. write a testnetSignatureVerify() and mainnetSignatureVerify()) , then branch on which network in the request , and then we're golden

**Comment by psteckler** [comment]
Some code in branch `feature/rosetta-construction-parse-nographql`.
