### ISSUE TITLE
Lost 3 consecutive slots with 1.2.0beta2 

### ISSUE THREAD

**Issue by gmkevinren** [MinaProtocol/mina#9360]
Hi all! I running 1.2.0beta2 on mainnet had no blocks coming out of 3 consecutive slots that he won - not even red blocks - even though he was running 3 nodes and all were synced. was this normal behaviour please? 
Here is the logs, too big in size ,so I uploaded it to web.:https://share.weiyun.com/xv2xOgPX

**Comment by shimkiv** [comment]
Hey @gmkevinren, apologies this ticket was not processed in time and no response provided.
Do you still need an assistance with this issue?

**Comment by shimkiv** [comment]
Closing this issue because of being inactive for long time.
Please feel free to open another ticket should you experience any further issues.
