### ISSUE TITLE
Catchup integration test

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [MinaProtocol/mina#9388]
Here's the basic scenario for the catchup integration test:

1. at least 2 nodes are needed (one of which must be block producer)
2. start the network and let the nodes run for a while
3. stop one of the node (make sure the network has at least one block producer running)
4. wait for a few blocks being produced over the network (4-5 blocks would be enough)
5. restart the node and wait for catchup
6. once the node is synced, check the best chain of that node, make sure the best chain is up to date

A more advanced version would switch step 3 and step 5 with the following:
3. isolate the node with the network (keep it running but don't send gossip to it)
5. reconnect the node with the network and wait for catchup
This requires us to implement a primitive to isolate nodes on the network and can be tricky to implement. We can first implement the basic scenario.

----------------

Information on catchup:

https://www.notion.so/minaprotocol/Catchup-30f15b3850054b2b97a10ccb7a0c708c

**Comment by QuiteStochastic** [comment]
the test should be fine at this point but still trying to fix the bug from #9064, which will go into this PR
