### ISSUE TITLE
cannot connect to Mainet using Mac using apple silicon and docker 

### ISSUE THREAD

**Issue by nikhilsukhwani** [MinaProtocol/mina#9421]
Hi need help sorting this out been struggling.

Cannot generate OTP for the discord thought I should post the issue here;

Please find the attached crash logs
[mina-log.txt](https://github.com/MinaProtocol/mina/files/7084517/mina-log.txt)

**Comment by psteckler** [comment]
This looks like a `SIGPIPE` signal, which we probably should have the daemon ignore.

**Comment by psteckler** [comment]
I regret that the Apple silicon Macs are not currently supported for Mina.
