### ISSUE TITLE
Cache rosetta builds from the toolchain image for the appropriate platform

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#9442]
The rosetta dockerfile in production is now a superset of the toolchain container for the first few stages and the rest of CI all depends on this container so we know it is always maintained and functional. Instead of --no-cache for the rosetta-ubuntu container and default caching for the debian versions, --cache-from the specific toolchain image in use by CI at the time to save ~5-10 minutes of build time.

**Comment by kantp** [comment]
Hi @lk86, do you know whether this issue is still relevant? If so, we can take it on as part of the rosetta API work.

**Comment by kantp** [comment]
@balsoft It sounds to me like this is something that we will automatically get when we're building with nix. Would you agree?
