### ISSUE TITLE
where is faucet mina coin for devnet?

### ISSUE THREAD

**Issue by stone89son** [MinaProtocol/mina#9445]
hi.
I research about Mina protocol, i want to faucet some mina coin on devnet. 
Can you give me the link for faucet mina coin?
Thank for support and test.

**Comment by Kakashi010** [comment]
Please post your devnet address in #devnet-faucet ch in the Mina Discord. Here is the [LINK](https://bit.ly/MinaDiscord).

**Comment by stone89son** [comment]
Thank for help, but too inconvenient.
