### ISSUE TITLE
Infer nonce for the fee payer in Snapp txns sent via GraphQL

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#9465]
The anticipated GraphQL endpoint to submit Snapp transactions accepts a `Party.Signed.t` for the fee payer, which includes a nonce in the `predicate` field.

Allow the nonce to be elided and inferred, as is done for ordinary user transactions.

**Comment by deepthiskumar** [comment]
Closing this since nonces are retrieved from the chain before generating a zkapp transaction using snarkyJS. The cli /graphql command simply accepts a fully constructed zkapp transaction.
