### ISSUE TITLE
Write up instructions on how to test Rosetta in our infrastructure

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#9485]

**Comment by lk86** [comment]
> @lk86 Okay to take this from you, and assign to Mina Foundation engineering?

yes go for it, let me know if you need any info

**Comment by Sventimir** [comment]
I started working on instructions on how to run `rosetta-cli` tests against a sandboxed node. I have written about how to run a sandbox node already, but I want to gatrher more data about the `rosetta-cli`, because there's quite a bit of configuration which I'd like to understand well.

**Comment by Sventimir** [comment]
I created PR to close this one: https://github.com/MinaProtocol/mina/pull/12069.
