### ISSUE TITLE
Audit code for use of global slots

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#9502]
The replayer uses the `global_slot` field in the archive db, denoting the slot since the last hard fork, where it should probably be using `global_slot_since_genesis`, the slot since network launch.

Fix that code, and audit other code to make sure the correct slot value is being used.

**Comment by deepthiskumar** [comment]
For the replayer it may not always make sense to apply transactions across hard forks. For example, when the ledger changes in one of the hard forks, passing the genesis ledger at launch as input may not result in the latest ledger in the archive node

**Comment by psteckler** [comment]
The replayer can start with an arbitrary staged ledger, not just the genesis ledger. If it never replays across hard forks, then using the current slot is OK.

What I want to be sure of is that the slot it uses is unique along the canonical chain. The slot since genesis gives you that.

In the current replayer, you can specify a start slot. If that means a current slot, that's ambiguous. With the slot since genesis, it's unambiguous.

**Comment by mrmr1993** [comment]
Can we combine both fields into a single record, to make us be more thoughtful about this? Field names like `since_genesis` and `since_last_hard_fork_for_consensus` might hopefully make it easier to tell which is the intended for most uses.

**Comment by psteckler** [comment]
I think renaming `current_slot` to `global_slot_since_last_hard_fork` is enough to avoid confusion.

For the archive db, that means a migration script to rename the column, and a software update to access the column.

**Comment by psteckler** [comment]
Where in the code do we use a global slot that denotes the slot since the last hard fork?

**Comment by psteckler** [comment]
For the hard fork, see this comment: https://github.com/MinaProtocol/mina/pull/9511#issuecomment-924000192

**Comment by psteckler** [comment]
Also: the replayer should be using the since-genesis slot of the parent block when applying transactions, not the slot of the block in which the transaction occurs.
