### ISSUE TITLE
Daemon 1.2.0beta6 crash on Docker after "Using uptime submitter keypair private-key password from environment variable UPTIME_PRIVKEY_PASS"

### ISSUE THREAD

**Issue by hsq125** [MinaProtocol/mina#9508]
Hi,

When running on Docker, the daemon is crashing just after logging its last word;

` "Using uptime submitter keypair private-key password from environment variable UPTIME_PRIVKEY_PASS"`

The problem is on **1.2.0beta6** (and has been encountered on  1.2.0beta5 and  1.2.0beta3).

It looks like it happens only on docker, where the version 1.2.0beta2 was working perfectly fine for weeks. A native installation does not have this problem.

I tried to set the log level to Debug, but it does not give more info. 

Available to provide more info if needed. 
O.

**Comment by hsq125** [comment]
OK... absolutely not related to Docker at all. 

I spent the whole afternoon building a native config... everything was going fine, until I encountered the same problem ! But this time with on MORE information...

```
Sep 18 18:10:52 cs3 mina[128978]: 2021-09-18 18:10:52 UTC [Info] Using block producer keypair private-key password from environment variable CODA_PRIVKEY_PASS
Sep 18 18:11:09 cs3 mina[128978]: Transaction_snark.system: 16.84s
Sep 18 18:11:31 cs3 mina[128978]: 2021-09-18 18:11:31 UTC [Info] Setting current protocol version to "2.0.0" from compile-time config
Sep 18 18:11:31 cs3 mina[128978]: 2021-09-18 18:11:31 UTC [Info] Using uptime submitter keypair private-key password from environment variable UPTIME_PRIVKEY_PASS
Sep 18 18:11:31 cs3 mina[128978]: FATAL ERROR
Sep 18 18:11:31 cs3 mina[128978]:   ☠  Mina Daemon encountered a configuration error loading uptime submitter keypair.
Sep 18 18:11:31 cs3 mina[128978]:   
Sep 18 18:11:31 cs3 mina[128978]: Cannot open file: /home/mina/mina-node/data/wallets/store/B62qrcQDeAfg2qSnZhdF8wQ78G9QmKNDqpESVt2SL43F97kF3Cyv32a
```

What changed from previous step in building the config ... adding the 

`--config-directory /home/mina/mina-node/data`

option.

So... to recap : 1.2.0.beta2+ will crash when specifying this option. 

I'll let it write in .mina for now. 

It is damn crazy. 
O.

**Comment by hsq125** [comment]
Question : is it possible to specify the config folder for the import tool ? 

`mina accounts import --privkey-path mina-node/keys/my-wallet`

**Comment by hsq125** [comment]
Back with this option on the daemon

`--config-directory /home/mina/mina-node/data`

The poin is that key had to be re-imported using 

`mina accounts import --privkey-path keys/my-wallet --config-directory data/daemon`

Obvious afterward, but error message (when visible!) do not help in figuring out what is wrong.

Maybe add an indication saying 

'make sure you imported the private key'. 

But can be closed for me in any case.

**Comment by psteckler** [comment]
Do you know what `mina.log` showed when this error occurred?

**Comment by psteckler** [comment]
#9499, when merged, will allow using an uptime submitter key that hasn't been imported.

**Comment by shimkiv** [comment]
xzClosing this issue because of being inactive for long time.
Please feel free to open another ticket should you experience any further issues.
