### ISSUE TITLE
Permission on key file should be 500 and not 700

### ISSUE THREAD

**Issue by hsq125** [MinaProtocol/mina#9509]
Hello,

Permission on key file should be 500 and not 700. The daemon (and anyone else) is supposed to write in the key files.

```
Sep 18 17:49:50 cs3 mina[127088]: The key was corrupted: insecure permissions on `/home/XXXX/XXXX/keys`. They should be 0700, they are 500
Sep 18 17:49:50 cs3 mina[127088]: Hint: chmod 700 /home/XXXX/XXXX/keys
```

Cheers,
Octave

**Comment by psteckler** [comment]
A permission of `500` means a directory is readable and executable, but not writable by the user. That means files cannot be created in the directory.

A permission of `700` adds writability to the directory.

```
$ mkdir foo
$ chmod 500 foo
$ ls -l | grep foo
dr-x------  2 steck steck      4096 Sep 20 20:07 foo
$ chmod 700 foo
$ ls -l | grep foo
drwx------  2 steck steck      4096 Sep 20 20:07 foo
```
