### ISSUE TITLE
Generate `to_latest` in versioned types, where possible

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#9510]
In many cases, `to_latest` can be generated for versioned types.

As a simple example, if we have:
```ocaml
module V2 = struct
  type t = Foo.Stable.V7.t
end
module V1 = struct
  type t = Foo.Stable.V5.t
end
```
then `V1.to_latest` is `Foo.Stable.V5.to_latest`. The most recent version of any type must be using the most recent version of any types it refers to, so this is principled.

For records and sum types, we can extend this idea homomorphically, field-by-field or constructor-by-constructor.

If a new version elides record fields, then `to_latest` just deletes them. If a new version adds record fields, those should have option types, and `to_latest` yields None for those. If they're not option types, then fail.

If a new version elides constructors for sums, then `to_latest` fails when those constructors appear.
If it adds constructors, `to_latest` injects into the new type.

For the most recent version, `to_latest` is always the identity function, which can be generated.

If the most recent version has a different structure than an older version, then all bets are off, and `to_latest` will have to be added manually.

**Comment by mrmr1993** [comment]
To extend this, if we have some way to specify 'default' values for fields, we can also automatically provide the coercion using those values. `[@versioned.default expr]` perhaps?

**Comment by psteckler** [comment]
We should also generate `of_latest`. RPC queries from newer to older nodes need to "downgrade" the data.
