### ISSUE TITLE
Unable to run mina-rosetta container

### ISSUE THREAD

**Issue by PrernaPadhee** [MinaProtocol/mina#9532]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/issues-experiment/discussions

### Description

I have been following the steps as mentioned in the readme for rosetta setup (https://github.com/MinaProtocol/mina/tree/develop/src/app/rosetta). I have successfully built the image. However when I try to execute the command to run the container to connect to the Mainnet
docker run -it --rm --name rosetta --entrypoint=./docker-start.sh -p 10101:10101 -p 3085:3085 -p 3086:3086 -p 3087:3087 mina-rosetta:v1

However I am facing following errors
![image](https://user-images.githubusercontent.com/29208607/135040889-0b58dcd8-ff83-40f9-b2f8-781fcd07fa30.png)
I have added an explicit path to the data folder in the docker-start.sh file, but it is not helping.
I am running the command from the path /mina/src/app/rosetta where the shell script file is stored.
what value needs to come against MINA_CLIENT_TRUSTLIST?

### Steps to Reproduce

1. Build image : cat dockerfiles/stages/1-build-deps dockerfiles/stages/2-toolchain dockerfiles/stages/3-opam-deps dockerfiles/stages/4-builder dockerfiles/stages/5-prod-ubuntu | docker build -t mina-rosetta:v1 --build-arg "deb_codename=stretch" --build-arg "MINA_BRANCH=rosetta-v1" -
2. Go to /mina/src/app/rosetta
3. Run : docker run -it --rm --name rosetta --entrypoint=./docker-start.sh -p 10101:10101 -p 3085:3085 -p 3086:3086 -p 3087:3087 mina-rosetta:v1
...

### Expected Result

Container should be running

### Actual Result

Container is not created and then is killed 
![image](https://user-images.githubusercontent.com/29208607/135042186-0e0f0d2d-8883-49ef-977b-2dcc14bf9458.png)

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

High

### Status

```shell
Not getting any output right now
```

**Comment by lk86** [comment]
Try again with the docs for v2, which should now be up-to-date on the latest commit to develop. The trustlist is not your fault and was fixed in v2

**Comment by PrernaPadhee** [comment]
In the docs for v2, they instruct to checkout the rosetta-v2 branch. Is that branch up to date or I should checkout develop branch only? Also, how stable is the rosetta implementation for mina ?

**Comment by joseandro** [comment]
@PrernaPadhee You can use the `develop` branch. Please let us know if that solved your problem. Thanks
