### ISSUE TITLE
Node fails to sync with rosetta-v3

### ISSUE THREAD

**Issue by PrernaPadhee** [MinaProtocol/mina#9675]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

I have setup my node following the readme instructions specific to rosetta-v3, after bootstrapping he node attains a block height and does not proceed further. The status remains stuck at 'Catchup'. The same output is observed through rosetta-v2.

Response to 
curl --data '{ network_identifier: { blockchain: "mina", network: "devnet" }, metadata: {} }' 'localhost:1332/network/status'
is 
{
    "current_block_identifier": {
        "index": 72698,
        "hash": "3NKbXdqsoF78rm1bkjaHcDuAQQ8qZQP12usjXwzGTq3kj1X47yd4"
    },
    "current_block_timestamp": 1634744880000,
    "genesis_block_identifier": {
        "index": 1,
        "hash": "3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ"
    },
    "sync_status": {
        "current_index": 72698,
        "stage": "Catchup"
    },
    "peers": [
        {
            "peer_id": "12D3KooWKnZceQDZeFwHoevTz7GQ5c29ias3HX4xa6BbyCT3tu2j"
        },
        {
            "peer_id": "12D3KooWHX2mE1L5dFo1yuBMzepwA2pDhzLgB6kp6WnkAV21xQPh"
        },
        {
            "peer_id": "12D3KooWEq6YZXFWeEeNhXWWwg8GMyPiFEHBaErs4PimS5AmcaT1"
        },
        {
            "peer_id": "12D3KooWJXuqJmijA8PT4BzkwY6tjmfCGHwjY9MkNRxSytWq3wGV"
        },
        {
            "peer_id": "12D3KooWRyP51U2owdFrWt5tZKBs2JMecSoMRwNn1MBfyRboVyDo"
        },
        {
            "peer_id": "12D3KooWAASAoFtDURkqmGLsVjYfkZb5Ky4QXmAChYkXbLMiRrNs"
        },
        {
            "peer_id": "12D3KooWBCYq2oPgy6pgnF5xjjJi1sYB4asAVBcXvWfEeHoeuzdx"
        },
        {
            "peer_id": "12D3KooWEwhjP7RTTChpa9iXnrTGfo3efvi3nGZBKFdjVAPrisxv"
        },
        {
            "peer_id": "12D3KooWC2kCiSvxM6qmGTyj5oKVnpj1qkC3LjG2txdyQ8taHhR9"
        },
        {
            "peer_id": "12D3KooWKuqWE6B2JbrxoapyEd7PFUUXvkPevhUyPU9vv8onoY6J"
        },
        {
            "peer_id": "12D3KooWH7hxayzD6CWCBadRvrpSQhb7y8ACEmd1nFRH3Ew7vwK8"
        },
        {
            "peer_id": "12D3KooWGoExxDbqAYHESwDXJbLmhGRK5LsKoTAhryvTvyG112hk"
        },
        {
            "peer_id": "12D3KooWQDzXUXFDHn6FRmDx6Yna8Dwq7r9PogzAL85s46X78d6m"
        },
        {
            "peer_id": "12D3KooWPehKD9rasjAzmnRXQy6CUfgjbWJ59bPU8HnJxYyhyJFV"
        },
        {
            "peer_id": "12D3KooWCXssSCznEP1zzeTnrqfcdiPaGpCVAks7kT7Q8qT8pqXS"
        },
        {
            "peer_id": "12D3KooWP4X17i9LMtMKj9t55JuAMzEr6eHrKka5i7qrtrj6HHCZ"
        },
        {
            "peer_id": "12D3KooWNDSfgoYKx2ZFJTkXGkLvtf1hKA9rMh6R3TcHnY2j22qB"
        },
        {
            "peer_id": "12D3KooWPoUo7ienGCe9Y5XJGoHgxGJw4phY4BjBr5gPV7MRgVqM"
        },
        {
            "peer_id": "12D3KooWCJgHTGhSNKb4wX6wPN8i2MdkjwUoiTwQTaUQV3xpzdP2"
        },
        {
            "peer_id": "12D3KooWSLMXxyWJsUdUB62yZiuJpw8kS574GW9UheBAyKNAHVsR"
        },
        {
            "peer_id": "12D3KooWS1kY2t6REYK7soX6gW1ZRMDVMwhBGjWnnr5RgWaA38YW"
        },
        {
            "peer_id": "12D3KooWGWL4URXNM61cBi5XEuNKcn94Ngw3LM2X6WuDgowtJAn4"
        },
        {
            "peer_id": "12D3KooWSxxCtzRLfUzoxgRYW9fTKWPUujdvStuwCPSPUN3629mb"
        },
        {
            "peer_id": "12D3KooWMoVmY6TxV9PzJQ9ALWqQ5M73qQmhSKPkoxWfYu1iihgU"
        },
        {
            "peer_id": "12D3KooWRqdbJszoX6AB2E47KR45Kex1RptichA2MDkNSCqX5eb4"
        },
        {
            "peer_id": "12D3KooWKBrFPyHehU2RsX98htK7sbaaxXNANouJJo7GPkdUVVNo"
        },
        {
            "peer_id": "12D3KooWHDfMZSfKEpR4euGV4Ln19oCEfu12fTooyrG3eHmEprTz"
        },
        {
            "peer_id": "12D3KooWMog4ra1sq23hy4KhsaBuanZnzyBq6dUEzPyESzWFSYpL"
        },
        {
            "peer_id": "12D3KooWEcYHcJ71u1TbrMAHio37BFHb2zuLiVaiKWuHCwz6Sc5d"
        },
        {
            "peer_id": "12D3KooWFvVpBETiPjHRyHnQwCbs6xnTJQquKsLrxALG6BQjisJ2"
        },
        {
            "peer_id": "12D3KooWB6d2P93FpXFnYc5mqfbkqqHASfzKEHKZa9fp2x69UQXV"
        }
    ]
}

### Steps to Reproduce

1. Create image -> cat dockerfiles/stages/1-build-deps dockerfiles/stages/2-toolchain dockerfiles/stages/3-opam-deps dockerfiles/stages/4-builder dockerfiles/stages/5-prod-ubuntu | sudo docker build -t mina-rosetta:v3 --build-arg "deb_codename=stretch" --build-arg "MINA_BRANCH=rosetta-v3" -
2. Run container -> sudo docker run -it --rm --name rosetta --entrypoint=./docker-devnet-start.sh -p 10101:10101 -p 3085:3085 -p 3086:3086 -p 1332:3087 mina-rosetta:v3

### Expected Result

Node should sync upto latest block

### Actual Result

Syncs upto one block and remains at it. Currently stuck at 72698.
Container logs :

{"timestamp":"2021-10-21 18:48:22.448039Z","level":"Debug","source":{"module":"Network_pool__Network_pool_base","location":"File \"src/lib/network_pool/network_pool_base.ml\", line 172, characters 20-42"},"message":"Refusing to rebroadcast $diff. Verification error: $error","metadata":{"diff":"Snark_pool_diff for work [280789945,224592129] added with fee-prover {\"fee\":\"0.025\",\"prover\":\"B62qnbehH2RBTrJmRApx1rGrJGkrjTRYqJiCRgtwp8S6J7D9VqNP9Po\"}","error":{"commit_id":"[DIRTY]57ca5409b382f369dcf700f7d4e0950690932e3b","string":"failed to verify snark pool diff"},"host":"13.86.126.217","peer_id":"12D3KooWKHct71nrYxPNPpcA3myyVwi9Gbc6TCGnsZw61snKK8d7","pid":165,"port":10101}}
{"timestamp":"2021-10-21 18:48:22.448000Z","level":"Debug","source":{"module":"Libp2p_helper.Go.codanet.Helper","location":"(not tracked)"},"message":"why u fail to validate :(","metadata":{}}
{"timestamp":"2021-10-21 18:48:22.508000Z","level":"Debug","source":{"module":"Libp2p_helper.Go.codanet.Helper","location":"(not tracked)"},"message":"validating a new pubsub message ...","metadata":{}}
{"timestamp":"2021-10-21 18:48:22.510556Z","level":"Debug","source":{"module":"Network_pool__Network_pool_base","location":"File \"src/lib/network_pool/network_pool_base.ml\", line 149, characters 10-32"},"message":"Verifying $diff from $sender","metadata":{"diff":"Snark_pool_diff for work [280789945,224592129] added with fee-prover {\"fee\":\"0.0001\",\"prover\":\"B62qq7nRR2R2PX28zF1HJV9nDVTbyQV1p6VZa9thNJq8JykjE18snWk\"}","host":"13.86.126.217","peer_id":"12D3KooWKHct71nrYxPNPpcA3myyVwi9Gbc6TCGnsZw61snKK8d7","pid":165,"port":10101,"sender":{"Remote":{"host":"95.217.113.57","peer_id":"12D3KooWMoVmY6TxV9PzJQ9ALWqQ5M73qQmhSKPkoxWfYu1iihgU","libp2p_port":8302}}}}
{"timestamp":"2021-10-21 18:48:22.512902Z","level":"Debug","source":{"module":"Network_pool__Snark_pool","location":"File \"src/lib/network_pool/snark_pool.ml\", line 474, characters 12-34"},"message":"Work $stmt not referenced","metadata":{"fee":"0.0001","host":"13.86.126.217","peer_id":"12D3KooWKHct71nrYxPNPpcA3myyVwi9Gbc6TCGnsZw61snKK8d7","pid":165,"port":10101,"prover":"B62qq7nRR2R2PX28zF1HJV9nDVTbyQV1p6VZa9thNJq8JykjE18snWk","sender":{"Remote":{"host":"95.217.113.57","peer_id":"12D3KooWMoVmY6TxV9PzJQ9ALWqQ5M73qQmhSKPkoxWfYu1iihgU","libp2p_port":8302}},"stmt":["Two",{"source":"jwaXQXVAG13GzuMfLf66q8PA4JFhZRzA4UN53cLgq44Vk1pJypU","target":"jwQBdLnxwzHDzKsmccJNEJ9fRoB7Qo4Z917KbkZkta4XFza7jci","supply_increase":"720000000000","pending_coinbase_stack_state":{"source":{"data":"4QP8au6ii7WriZ2nRBeP7595ap41P4boHsv3VhwXeTTYnWd6qdPq","state":{"init":"4YxwXtBcQBvn78hZvKXkcariQ6NwZ61f2PBdnKVvHresHCXK94MD","curr":"4YyruNVyyuUsYoKLwqVMaJcvv2Sx3pnw8XFNC66Wx59abLmzBL3z"}},"target":{"data":"4QPJhrojFYtsn1teeK7e47zcJf1Z1Xk5aQa3jHGfEjV6d9sFdNk9","state":{"init":"4YxwXtBcQBvn78hZvKXkcariQ6NwZ61f2PBdnKVvHresHCXK94MD","curr":"4YyruNVyyuUsYoKLwqVMaJcvv2Sx3pnw8XFNC66Wx59abLmzBL3z"}}},"fee_excess":[{"token":"1","amount":{"magnitude":"0","sgn":["Pos"]}},{"token":"1","amount":{"magnitude":"0","sgn":["Pos"]}}],"next_available_token_before":"2","next_available_token_after":"2","sok_digest":null},{"source":"jwQBdLnxwzHDzKsmccJNEJ9fRoB7Qo4Z917KbkZkta4XFza7jci","target":"jwhrtC3jmzLe6YTUxc2qm4FECYvsV7GStydSD3xivXevAPHqbZ2","supply_increase":"0","pending_coinbase_stack_state":{"source":{"data":"4QPJhrojFYtsn1teeK7e47zcJf1Z1Xk5aQa3jHGfEjV6d9sFdNk9","state":{"init":"4YxwXtBcQBvn78hZvKXkcariQ6NwZ61f2PBdnKVvHresHCXK94MD","curr":"4YyruNVyyuUsYoKLwqVMaJcvv2Sx3pnw8XFNC66Wx59abLmzBL3z"}},"target":{"data":"4QPJhrojFYtsn1teeK7e47zcJf1Z1Xk5aQa3jHGfEjV6d9sFdNk9","state":{"init":"4YxwXtBcQBvn78hZvKXkcariQ6NwZ61f2PBdnKVvHresHCXK94MD","curr":"4YyruNVyyuUsYoKLwqVMaJcvv2Sx3pnw8XFNC66Wx59abLmzBL3z"}}},"fee_excess":[{"token":"1","amount":{"magnitude":"0.043","sgn":["Neg"]}},{"token":"1","amount":{"magnitude":"0","sgn":["Pos"]}}],"next_available_token_before":"2","next_available_token_after":"2","sok_digest":null}]}}
{"timestamp":"2021-10-21 18:48:22.513142Z","level":"Debug","source":{"module":"Network_pool__Network_pool_base","location":"File \"src/lib/network_pool/network_pool_base.ml\", line 172, characters 20-42"},"message":"Refusing to rebroadcast $diff. Verification error: $error","metadata":{"diff":"Snark_pool_diff for work [280789945,224592129] added with fee-prover {\"fee\":\"0.0001\",\"prover\":\"B62qq7nRR2R2PX28zF1HJV9nDVTbyQV1p6VZa9thNJq8JykjE18snWk\"}","error":{"commit_id":"[DIRTY]57ca5409b382f369dcf700f7d4e0950690932e3b","string":"failed to verify snark pool diff"},"host":"13.86.126.217","peer_id":"12D3KooWKHct71nrYxPNPpcA3myyVwi9Gbc6TCGnsZw61snKK8d7","pid":165,"port":10101}}
{"timestamp":"2021-10-21 18:48:22.513000Z","level":"Debug","source":{"module":"Libp2p_helper.Go.codanet.Helper","location":"(not tracked)"},"message":"why u fail to validate :(","metadata":{}}

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
Mina daemon status
-----------------------------------

Global number of accounts:                     65750
Block height:                                  72698
Max observed block height:                     72992
Max observed unvalidated block height:         73030
Local uptime:                                  3h41m38s
Ledger Merkle root:                            jxYWkb8ueNKU7DpBVEhjTdLj3dmh9tgnRwEYrzuEzWwzSLfUqGc
Protocol state hash:                           3NKbXdqsoF78rm1bkjaHcDuAQQ8qZQP12usjXwzGTq3kj1X47yd4
Chain id:                                      5f704cc0c82e0ed70e873f0893d7e06f148524e3f0bdae2afb02e7819a0c24d1
Git SHA-1:                                     [DIRTY]57ca5409b382f369dcf700f7d4e0950690932e3b
Configuration directory:                       /data/.mina-config
Peers:                                         34
User_commands sent:                            0
SNARK worker:                                  None
SNARK work fee:                                100000000
Sync status:                                   Catchup
Catchup status:
        To build breadcrumb:           0
        To initial validate:           233
        Finished:                      2
        To download:                   0
        Waiting for parent to finish:  7
        To verify:                     58

Block producers running:                       0
Coinbase receiver:                             Block producer
Best tip consensus time:                       epoch=14, slot=4516
Best tip global slot (across all hard-forks):  104476
Next block will be produced in:                None this epoch… checking at in 4.325d (Generated from consensus at slot: 104472 slot-since-genesis: 104472)
Consensus time now:                            epoch=14, slot=5064
Consensus mechanism:                           proof_of_stake
Consensus configuration:
        Delta:                     0
        k:                         290
        Slots per epoch:           7140
        Slot duration:             3m
        Epoch duration:            14d21h
        Chain start timestamp:     2021-03-17 00:00:00.000000Z
        Acceptable network delay:  3m

Addresses and ports:
        External IP:    13.86.126.217
        Bind IP:        0.0.0.0
        Libp2p PeerID:  12D3KooWKHct71nrYxPNPpcA3myyVwi9Gbc6TCGnsZw61snKK8d7
        Libp2p port:    10101
        Client port:    8301
```

**Comment by robinbb** [comment]
@joseandro Can Mina Foundation take this Rosetta-related issue from you? Also, it seems that the author replied, so perhaps the waiting-author-response label is no longer appropriate?

**Comment by kantp** [comment]
@PrernaPadhee In picking this ticket back up, we saw that it's about a rather old docker image, where the demon doesn't connect to the network anymore, so I'm closing the issue as stale. If you are experiencing the same errors using the most recent release as well, please reopen with a comment.
