### ISSUE TITLE
Fix tokens implementation (parties)

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#9744]
The tokens implementation is currently disabled. To enable it, we need to:
* track the 'active current token' in the snapp
* ensure that we only update the excess when the 'active current token' is the default
* ensure that the first party when switching to a different token is the token owner
* re-enable token minting (and set the token owner field)

**Comment by yourbuddyconner** [comment]
This issue has been mentioned on **MinaResearch**. There might be relevant details there:

https://forums.minaprotocol.com/t/mina-token-standard-smart-contract-implementation-discussion/5187/8
