### ISSUE TITLE
Dockerfile-base and opam.export desyncs

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#975]
When we build the `base` dockerfile, we run `opam install` and whatever the newest version of the dep is at the time when the docker image was built.

We also have this `opam.export` file that is supposed to approximate pinned dependencies. This will be important for reproducible builds, but also just sanity.

Currently, these don't agree. They ought to.

**Comment by shimkiv** [comment]
Closing as `stale` one.
