### ISSUE TITLE
Daemon crashes on system suspending/sleep (at least on Mac)

### ISSUE THREAD

**Issue by DjawadNowrouzi** [MinaProtocol/mina#9781]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Summary

The Imac went to sleepmode and the system crashed.
coda_crash_report_2021-11-06_21-49-38.217914.tar.gz
### Steps to Resolve this Issue

1.Turn the sleemode off
2.
3.
...

**Comment by shimkiv** [comment]
Self-assigning to grab more details, I think I also faced "closed lid" kind of crashes.

**Comment by shimkiv** [comment]
We don't think it's worth the engineering effort to fix this workflow. 
It's a lot more than just the child processes that rely on time. Consensus, networking, and pretty much everything relies on time and the ability to maintain active connections to the network. 
While we could make this work, it would take a lot of effort and testing to fix it and know that when the node comes back after sleep that it isn't broken. 
As such, crashing sounds like the best thing to do.
