### ISSUE TITLE
Review ChainSafe test plans for M1

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#9831]

**Comment by jspada** [comment]
Met with Hailong Mu as recommended by Lerna to discuss Chainsafe's M1 test plans

Minutes
* High level testing overview
  * Unit tests
    * Bin-prot / Jane Street test vectors
    * Layout unit tests
  * End-to-end tests (mina types)
  * Benchmarking and profiling
* Suggested actions
  * Add CI check that layouts match current mina (e.g. develop branch) layouts
    * Mina may need to setup CI job to auto-export these somewhere
    * mina-rs to compare its layouts against mina-exported current layouts
  * Prevents projects from drifting apart
  * [Hailong Mu] More testing/investigation that test coverage for layouts is correct
  * Add Benchmark results to revision control
    * Can be compared and looked back on easily
    * Setup CI warning in case someone breaks performance
  * Add more negative test cases
  * Explicitly add tests for unsafe derserialization
  * Noted not to work on verification/signing/keypair code which is in a state of change and belongs to another milestone
      * Hailong current instructed to work on keypair verification code
      * https://github.com/ChainSafe/mina-rs/pull/101
  * [Hailong Mu] Noted that comms not fully in sync

**Comment by jspada** [comment]
Overall I feel like they are doing a good job and testing plan seems comprehensive.  They also appear very open to incorporate our suggestions and have contributed some good ideas.
