### ISSUE TITLE
Sandbox docker not starting

### ISSUE THREAD

**Issue by mcauthorn** [MinaProtocol/mina#9840]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

`docker run -it --name mina-demo1 -e RUN_DEMO=true  minaprotocol/mina-daemon:1.2.1beta1-45440dc-devnet`

...produces a CODA_PRIVKEY_PASS error:
```
FATAL ERROR
  ☠  Mina Daemon encountered a configuration error loading block producer keypair.
No password was specified in environment variable CODA_PRIVKEY_PASS

```

Providing a blank private key pass via:

`docker run -it  --name mina-demo1 -e RUN_DEMO=true -e CODA_PRIVKEY_PASS=  minaprotocol/mina-daemon:1.2.1beta1-45440dc-devnet`

...produces:

```
+ INPUT_ARGS=
+ LOG_FILES=('mina.log')
+ declare -a LOG_FILES
+ VERBOSE_LOG_FILES=('.mina-config/mina-prover.log' '.mina-config/mina-verifier.log' '.mina-config/mina-best-tip.log')
+ declare -a VERBOSE_LOG_FILES
+ for script in /entrypoint.d/*
+ '[' -x /entrypoint.d/01-override-genesis-ledger.sh ']'
+ /entrypoint.d/01-override-genesis-ledger.sh
+ for script in /entrypoint.d/*
+ '[' -x /entrypoint.d/01-override-peers-list.sh ']'
+ /entrypoint.d/01-override-peers-list.sh
+ for script in /entrypoint.d/*
+ '[' -x /entrypoint.d/01-run-demo.sh ']'
+ /entrypoint.d/01-run-demo.sh
Running Mina demo...
Genesis State Timestamp for this run is: 2021-11-17T11:33:17Z
Rewriting config file from template daemon.json.template to /root/.mina-config/daemon.json}
Contents of config file /root/.mina-config/daemon.json}:
{"genesis": {"genesis_state_timestamp": ""},"ledger":{"name":"mina-demo","accounts":[{"pk":"B62qiZfzW27eavtPrnF6DeDSAKEjXuGFdkouC3T5STRa6rrYLiDUP2p","balance":"66000","sk":null,"delegate":null}]}}
2021-11-17 11:33:18 UTC [Info] Coda daemon is booting up; built with commit "45440dc7e4c5dac480dd075357c1d369b893fbe1" on branch "release/1.2.0"
Using password from environment variable CODA_PRIVKEY_PASS
Using password from environment variable CODA_PRIVKEY_PASS
Using password from environment variable CODA_PRIVKEY_PASS
2021-11-17 11:33:18 UTC [Info] Created daemon lockfile "/root/.mina-config/.mina-lock"
2021-11-17 11:33:18 UTC [Info] Registering async shutdown handler: "Remove daemon lockfile"
2021-11-17 11:33:18 UTC [Info] Daemon will expire at "2024-12-10 14:00:00-07:00"
2021-11-17 11:33:18 UTC [Info] Booting may take several seconds, please wait
2021-11-17 11:33:18 UTC [Info] Reading configuration files $config_files
	config_files: [ "/var/lib/coda/config_45440dc7.json", "/root/.mina-config/daemon.json" ]
2021-11-17 11:33:18 UTC [Warn] Could not read configuration from "/root/.mina-config/daemon.json"
2021-11-17 11:33:18 UTC [Info] Initializing with runtime configuration. Ledger name: "devnet"
2021-11-17 11:33:18 UTC [Info] Using the compiled constraint constants
2021-11-17 11:33:41 UTC [Info] Loaded genesis ledger from $ledger_file
	ledger_file: "/root/.mina-config/genesis/genesis_ledger_accounts_07c4db3946017fb3bd5383864c78e30e6a5571d63c2d3ca3c9a822e7f97b4d87.tar.gz"
2021-11-17 11:33:42 UTC [Info] Using block producer keypair private-key password from environment variable CODA_PRIVKEY_PASS
2021-11-17 11:33:43 UTC [Info] Starting node as a seed node
Transaction_snark.system: 40.756s
/entrypoint.sh: line 19:    10 Killed                  "$script" $INPUT_ARGS
```

Any ideas what the documentation is missing?

### Steps to Reproduce

1. Follow the prescribed sandbox docker commands
2. Tail container logs

### Expected Result

A running sandbox container

### Actual Result

A failed container startup

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Blocker

### Status

```shell
Daemon won't start, can't get status.
```

**Comment by stevenplatt** [comment]
Hi, can you paste a link to the documents you are following?

When running the docker container, you will need to pass the private key you want it to use. "-e CODA_PRIVKEY_PASS=" would be "-e CODA_PRIVKEY_PASS=kljfdhslkfhjsdjkl" (substituting the random text with your actual private key value.) Doing this should resolve the error you are having. 

If you paste the link here for the document you are following, I can follow it as well and request updated for the parts that are not clear. 

- Cheers

**Comment by garethtdavies** [comment]
If that doesn't work try this container as were other issues (related to not reading the config file properly).

```docker run -it --rm --name mina-demo -e RUN_DEMO=true -e CODA_PRIVKEY_PASS='' minaprotocol/mina-daemon:1.2.0-fe51f1e-demo```

That being said, it looks like yours is being killed very early on in the process so it likely is a resource issue. Increase the RAM/CPU you have allocated to Docker.

**Comment by stevenplatt** [comment]
Searching the "docs" repository for keyphrase "minaprotocol/mina-daemon:", the source information seems to come from: https://docs.minaprotocol.com/en/advanced/connecting-devnet. I will hold now for confirmation if the recommendations resolved the issue (then the doc can be updated

**Comment by garethtdavies** [comment]
> Searching the "docs" repository for keyphrase "minaprotocol/mina-daemon:", the source information seems to come from: https://docs.minaprotocol.com/en/advanced/connecting-devnet. I will hold now for confirmation if the recommendations resolved the issue (then the doc can be updated

It's probably this page https://docs.minaprotocol.com/en/developers/sandbox-node which can likely be updated to the above image for now (and add the required `CODA_PRIVKEY_PASS` env var), as the one listed doesn't work (more details here https://discord.com/channels/484437221055922177/502176205211041794/908466105100669048)

**Comment by mcauthorn** [comment]
Looks like your suggestions worked - thank you. Increased resources, and
used your alternate container worked. Thank you!

**Comment by stevenplatt** [comment]
Thanks for confirming. 
Tagging @jasongitmail for visibility. I am told he is refreshing the Mina technical documentation at this time.
