### ISSUE TITLE
Design phase: break down the network performance test into smaller tasks

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#9856]
More info can be gathered here: https://www.notion.so/minaprotocol/Network-stress-test-at-its-limits-9b3be119ed074973b82d98dcf149e9ca

**Comment by stevenplatt** [comment]
Initial Proposal of Network Performance Tests: 
Additional context and detail can be found within this [Notion link](https://www.notion.so/minaprotocol/Network-stress-test-at-its-limits-9b3be119ed074973b82d98dcf149e9ca). 

Pre-Work Items
- [ ] Identify time allocated per consensus "slot".
- [ ] Identify current block size and whether this is expected to change with future network updates. 
- [ ] Identify all messages and any governing timeouts used between nodes during consensus. 
- [ ] Identity impacts of blocks not being received during a given slot time. 
- [ ] Identity for Mina discovers and trims unresponsive peers. 
- [ ] Identify how meshed mainnet peer relationships are (any potential graph bottlenecks). 
- [ ] Identify average network performance and quality of community nodes. 
- [ ] Identify what portion of community nodes are below the recommended hardware spec. 


### **Node Performance Tests**

_Seed Node_

- [ ] Validate at what number of seed connections, node CPU is exhausted.
- [ ] Validate at what number of seed connections, node RAM is exhausted.
- [ ] Validate at what number of seed connections, node SSD is exhausted.

_Block Producer Node_
- [ ] Validate at what block volume, node CPU is exhausted. 
- [ ] Validate at what block volume, node RAM is exhausted. 
- [ ] Validate at what block volume, node SSD is exhausted. 

_Archive Node_
- [ ] Validate at what block volume, node CPU is exhausted. 
- [ ] Validate at what block volume, node RAM is exhausted. 
- [ ] Validate at what block volume, node SSD is exhausted.

_Archive Database Node_
- [ ] Validate at what block volume (DB writes), node CPU is exhausted. 
- [ ] Validate at what block volume (DB writes), node RAM is exhausted. 
- [ ] Validate at what block volume (DB writes), node SSD is exhausted.
~
- [ ] Validate at what query volume (DB reads), node CPU is exhausted.
- [ ] Validate at what query volume (DB reads), node RAM is exhausted.
- [ ] Validate at what query volume (DB reads), node SSD is exhausted.

_Snark Coordinator_
- [ ] Validate at what block volume, node CPU is exhausted. 
- [ ] Validate at what block volume, node RAM is exhausted. 
- [ ] Validate at what block volume, node SSD is exhausted.

_Snark Worker_
- [ ] Validate at what block volume, node CPU is exhausted. 
- [ ] Validate at what block volume, node RAM is exhausted. 
- [ ] Validate at what block volume, node SSD is exhausted.

_Rosetta API Provider_ (for each API resource)
- [ ] Validate at what request volume, node CPU is exhausted. 
- [ ] Validate at what request volume, node RAM is exhausted. 
- [ ] Validate at what request volume, node SSD is exhausted.

_Rosetta Database_  (for each query)
- [ ] Validate at what request volume, node CPU is exhausted. 
- [ ] Validate at what request volume, node RAM is exhausted. 
- [ ] Validate at what request volume, node SSD is exhausted.

**Comment by joseandro** [comment]
Requesting review from @bkase @nholland94 @deepthiskumar @lk86

**Comment by bkase** [comment]
In the pre-work tasks, as you're identifying things and understanding how they work, it would be great to also jot down notes about how you think it should change. Consensus related bits are fixed, but for example: "how Mina discovers and trims unresponsive peers" is probably something we can tweak in our Libp2p config.

**Comment by lk86** [comment]
I would consider thinking about transaction density as an additional metric to consider alongside block volume for archival, and the snark worker, and transaction pool size for the block producers / snark coordinator. Transactions affect the complexity of validating blocks, and in the world of Snapps transactions they also become larger and potentially harder to validate.

**Comment by nholland94** [comment]
An important piece of performance is how the network reacts to increasing ledger sizes. In particular, as ledger size increases, bootstrap takes long and utilized more bandwidth on the network. So we would want to know how bootstrap time increases with ledger size (stateless bootstrap is of primary interest here), and we would also want to know how a large number of nodes bootstrapping effects the rest of the network.

**Comment by nholland94** [comment]
For snark coordinators, we should be measuring performance scaling as the number of snark workers running under a single coordinator increases. Ideally, we should also measure the impact that parallel snark work has on the network, as submitting snark work to the network takes up a lot of the pubsub bandwidth.

**Comment by stevenplatt** [comment]
I have updated the testing list to include the new feedback.

**Comment by deepthiskumar** [comment]
Block producer nodes:
* measure the impact as snark pool grows

Archive nodes:
* We should try measuring the same when there are multiple daemons talking to the same archive process
Would also be nice to assess the impact of having multiple archive processes write to one database.
