### ISSUE TITLE
How to upgrade ubuntu 20.04 - running multiple BP and more?

### ISSUE THREAD

**Issue by mahalamobile** [MinaProtocol/mina#9875]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Hi all,

So ive built mina originally from source and made a few changes to get it working on ubuntu 20.04.
I have a BP, snark stopper and sidecar and uptime script all running. I can never get close to 90% uptime, so hoping this new upgrade will help a few things

1. any documents to upgrade from source and or apt etc for ubuntu 20.04, or do i need a new install and import keys?
2. is there any documentation and or recommendation in running 2 BP nodes with all the side scripts?
3. this new upgrade, do i need to still run sidecar, uptime script and snark stopper?
4. ive tried the discord but seems very vague, people dont seem to wanna help as they are building their own pools. i really like the project but a project contact that will help with no hidden agenda will be apprecaited
thanks again

### Steps to Reproduce

1. build manually ubuntu 20.04
2.
3.
...

### Expected Result

?

### Actual Result

?

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

High

### Status

```shell
Mina daemon status
-----------------------------------

Global number of accounts:                     77976
Block height:                                  84261
Max observed block height:                     84261
Max observed unvalidated block height:         84261
Local uptime:                                  14h55m16s
Ledger Merkle root:                            jxZM6SQ1x5uHRkHRSG52HfgUpd7Ssvc4o                                                                                                             EH9o94WMq4GsZsnKQ7
Protocol state hash:                           3NKUqgSoY2iY6yMZG5wFfo8NwG5sPvkwy                                                                                                             h976p2cmBJYizAwA9Yf
Chain id:                                      5f704cc0c82e0ed70e873f0893d7e06f1                                                                                                             48524e3f0bdae2afb02e7819a0c24d1
Git SHA-1:                                     b10c0e3db9112a2a8aebc3eec7c6d2570                                                                                                             fcc4044
Configuration directory:                       /home/ubuntu/.mina-config
Peers:                                         57
User_commands sent:                            0
SNARK worker:                                  B62qkmrLj9odLjkpWGw67iypLPqX7yZpX                                                                                                             mfitA5T7Fy7BYR5pA8eVyQ
SNARK work fee:                                10000000
Sync status:                                   Synced
Catchup status:
        To build breadcrumb:           0
        To initial validate:           0
        Finished:                      382
        To verify:                     0
        To download:                   0
        Waiting for parent to finish:  0

Block producers running:                       1 (B62qkmrLj9odLjkpWGw67iypLPqX7y                                                                                                             ZpXmfitA5T7Fy7BYR5pA8eVyQ)
Best tip consensus time:                       epoch=17, slot=326
Best tip global slot (across all hard-forks):  121706
Next block will be produced in:                None this epoch… checking at in 1                                                                                                             4.191d (Generated from consensus at slot: 121394 slot-since-genesis: 121394)
Consensus time now:                            epoch=17, slot=328
Consensus mechanism:                           proof_of_stake
Consensus configuration:
        Delta:                     0
        k:                         290
        Slots per epoch:           7140
        Slot duration:             3m
        Epoch duration:            14d21h
        Chain start timestamp:     2021-03-17 00:00:00.000000Z
        Acceptable network delay:  3m

Addresses and ports:
        External IP:    196.30.29.2
        Bind IP:        0.0.0.0
        Libp2p PeerID:  12D3KooWR2Gd7GzD5BsRYXpyP5mF8kKcR9J52hcphvmS78ASESoa
        Libp2p port:    8302
        Client port:    8301
```

### Additional information

please help

**Comment by garethtdavies** [comment]
1). See this message to install dependencies for 20.04 https://discord.com/channels/484437221055922177/583400552487059546/822269019687354418. Alternatively, you can use Docker.
2). You can just duplicate the exact setup on a second (and potentially third) machine
3). You don't need to run the snarkstopper unless you are actively snarking and producing blocks. If you are most concerned about uptime, I would recommend you don't snark on the same machine.
4). I've always found the opposite, you'll get plenty of help in #mentor-nodes

**Comment by shimkiv** [comment]
I believe this one can be closed now. Thank you to all participants.
