### ISSUE TITLE
Reload client_whitelist if it has changed

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#988]
A bit awkward to do with the current setup, which just pushes a list down. Push a ref down? Should we try using file watching APIs (I see there is https://github.com/whitequark/ocaml-inotify), or just poll on every connection? I see https://github.com/mirage/irmin-watcher, and it's mac/linux compat, but it's lwt -- easy to port though.

**Comment by jkrauska** [comment]
@cmr I'd like to reopen this perhaps as a CLI call instead?

coda advanced whitelist list
coda advanced whitelist add 192.168.1.1
coda advanced whitelist del 192.168.1.1

I feel like this should be pretty easy?

It would help a lot with enabling dynamic-scaling of snark workers.

**Comment by imeckler** [comment]
@jkrauska would like to arbitrarily spin up machines and whitelist them to be able to request snark work.

**Comment by yourbuddyconner** [comment]
Would it be appropriate to also allow the whitelist to be turned off entirely/whitelist a whole subnet? 

I'm imagining the scenario where a fleet of snark workers is partitioned from the internet via network routing rules and only able to access a coordinator.
