### ISSUE TITLE
Release: 1.3.0alpha1 daemon crash soon after restart

### ISSUE THREAD

**Issue by jrwashburn** [MinaProtocol/mina#9983]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

Daemon 1.3 (running on mainnet) crashed and dump file generated.
Also exported logs - about 30 minutes after the dump.

Daemon had 5.7 days uptime until it failed two mina client status polls 5 mins apart, and was then restarted automatically by monitoring script. It restarted at ~23:10, got in sync, but then crashed and restarted again. Crash dump was generated from that crash with short uptime.

Logs and crash dump shared here:
https://drive.google.com/drive/folders/10L7W7U7wPFEUX-NBQRj1WtErtKyechLj?usp=sharing

### Steps to Reproduce

1. Unknown

### Expected Result

1. Daemon would have been responsive to mina client status (and therefore would not have been restarted.)
2. Daemon would not crash.

### Actual Result

Non-responsive; crashed after restart.

### How frequently do you see this issue?

Rarely

### What is the impact of this issue on your ability to run a node?

Medium

### Status

```shell
Status is included in dump.
```

**Comment by jrwashburn** [comment]
Experienced another crash with 1.3 A 1 - logs added to the same folder. Logs dated 20210116.

**Comment by p-shahi** [comment]
@jrwashburn are you still seeing this on latest releases?

**Comment by jrwashburn** [comment]
I have not observed it on stable nor the new beta - okay to close.
