### ISSUE TITLE
lookup: add lookup commitments and evaluations (optionally) to proof type in pickles

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#9990]
We still need to add to support for plookup in pickles. This will require editing the type
```ocaml
module Evals = struct
  [%%versioned
  module Stable = struct
    module V2 = struct
      type 'a t =
        { w : 'a Columns_vec.Stable.V1.t
        ; z : 'a
        ; s : 'a Permuts_minus_1_vec.Stable.V1.t
        ; generic_selector : 'a
        ; poseidon_selector : 'a
        }
      [@@deriving fields, sexp, compare, yojson, hash, equal]
    end
  end]
```
to add the relevant lookup evaluations, matching the rust evaluations type, and the types
```ocaml
module Messages = struct
  open Poly_comm

  module Poly = struct
    type ('w, 'z, 't) t = { w : 'w; z : 'z; t : 't }
    [@@deriving sexp, compare, yojson, fields, hash, equal, hlist]
  end

  [%%versioned
  module Stable = struct
    module V2 = struct
      type 'g t =
        { w_comm : 'g Without_degree_bound.Stable.V1.t Columns_vec.Stable.V1.t
        ; z_comm : 'g Without_degree_bound.Stable.V1.t
        ; t_comm : 'g Without_degree_bound.Stable.V1.t
        }
      [@@deriving sexp, compare, yojson, fields, hash, equal, hlist]
    end
  end]
```
to add the commitments as in rust. Both should be optional so that lookups can be used or not.

Both these types are in src/lib/pickles_types/dlog_plonk_types.ml

After modifying the types, the functions for converting to and from the rust versions will need to be implemented.

Then, the circuits themselves will need to be updated to optionally handle lookups. This should be done so that there is no overhead in the case that lookups are definitely not used.

**Comment by jspada** [comment]
Is this still a thing?
