### ISSUE TITLE
Review current Helm charts for final Deployments

### ISSUE THREAD

**Issue by samuelarogbonlo** [MinaProtocol/mina#9999]
- Address any issues left in the charts.
- Move stable version to Artifact hub for testing with TF.
- Round up the charts finally.
- Implements snark coordinator and worker.
- Test each node required.

*From the roadmap:*
This will make network deployments easier and more maintainable. It will also make testing easier. This single chart will replace the use of the former 10 old charts.

- Make sure that the default set of enabled features “just works” without external inputs, and publish the result to artifacthub
- Introduce a new demo single-node network config with genesis ledger, block producer key, libp2p key, and any other external inputs to the chart to allow for all features to be enabled
    - Extend health checks to verify that all features are working
- Add new features as needed to support the Terraform design and/or outstanding incomplete features like watchdog or the user agent

**Comment by joseandro** [comment]
This task is mapped to the goal Q1.10 of our roadmap: Use Helm to deploy Berkley testnet
